{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-03-30',
 'EntryPath': 'Favorites/Movies/snapshot/Snowpiercer',
 'EntryURL': 'https://www.imdb.com/title/tt1706620',
 'Entry_json': 'Favorites/Movies/snapshot/Snowpiercer/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Snowpiercer/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Snowpiercer/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Chris Evans',
            'url': '/name/nm0262635/'},
           {'@type': 'Person', 'name': 'Jamie Bell', 'url': '/name/nm0068260/'},
           {'@type': 'Person',
            'name': 'Tilda Swinton',
            'url': '/name/nm0842770/'},
           {'@type': 'Person', 'name': 'Ed Harris', 'url': '/name/nm0000438/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 291698,
                     'ratingValue': '7.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jacques Lob',
              'url': '/name/nm2441468/'},
             {'@type': 'Person',
              'name': 'Benjamin Legrand',
              'url': '/name/nm0499429/'},
             {'@type': 'Person',
              'name': 'Jean-Marc Rochette',
              'url': '/name/nm2440893/'},
             {'@type': 'Person',
              'name': 'Bong Joon Ho',
              'url': '/name/nm0094435/'},
             {'@type': 'Person',
              'name': 'Bong Joon Ho',
              'url': '/name/nm0094435/'},
             {'@type': 'Person',
              'name': 'Kelly Masterson',
              'url': '/name/nm1031176/'},
             {'@type': 'Organization', 'url': '/company/co0364224/'},
             {'@type': 'Organization', 'url': '/company/co0157434/'},
             {'@type': 'Organization', 'url': '/company/co0058896/'},
             {'@type': 'Organization', 'url': '/company/co0017390/'},
             {'@type': 'Organization', 'url': '/company/co0680017/'},
             {'@type': 'Organization', 'url': '/company/co0043365/'},
             {'@type': 'Organization', 'url': '/company/co0742834/'},
             {'@type': 'Organization', 'url': '/company/co0730288/'},
             {'@type': 'Organization', 'url': '/company/co0457724/'}],
 'datePublished': '2013-08-01',
 'description': 'Snowpiercer is a movie starring Chris Evans, Jamie Bell, and '
                'Tilda Swinton. In a future where a failed climate-change '
                'experiment has killed all life except for the lucky few who '
                'boarded the Snowpiercer, a train that travels around...',
 'director': {'@type': 'Person',
              'name': 'Bong Joon Ho',
              'url': '/name/nm0094435/'},
 'duration': 'PT2H6M',
 'genre': ['Action', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ3NzA1MTY3MV5BMl5BanBnXkFtZTgwNzE2Mzg5MTE@._V1_.jpg',
 'keywords': 'train,perpetual winter,closed ecological system,population '
             'control,dystopia',
 'name': 'Snowpiercer',
 'trailer': {'@type': 'VideoObject',
             'description': 'In a future where a failed global-warming '
                            'experiment kills off all life on the planet '
                            'except for a lucky few that boarded the '
                            'Snowpiercer, a train that travels around the '
                            'globe, where a class system evolves.',
             'embedUrl': '/video/imdb/vi1214688537',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjE5OTYwNjUxNV5BMl5BanBnXkFtZTgwODc5MTAyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjE5OTYwNjUxNV5BMl5BanBnXkFtZTgwODc5MTAyMzE@._V1_.jpg',
             'uploadDate': '2014-05-31T08:20:53Z'},
 'url': '/title/tt1706620/'}