{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Super-Smash-Bros-Melee-2001',
 'EntryURL': 'https://rawg.io/games/super-smash-bros-melee-2001',
 'Entry_json': 'Favorites/Games/snapshot/Super-Smash-Bros-Melee-2001/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Super-Smash-Bros-Melee-2001/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Super-Smash-Bros-Melee-2001/thumb.jpg',
 'added': 351,
 'background_image': 'https://media.rawg.io/media/screenshots/2d5/2d51296133a91f1e5ef9eec5aa029fd8.jpg',
 'developers': ['HAL Laboratory', 'HAL Laboratory, Inc.'],
 'genres': ['Action', 'Casual', 'Fighting'],
 'name': 'Super Smash Bros. Melee',
 'platforms': ['GameCube'],
 'publishers': ['Nintendo'],
 'released': '2001-11-21',
 'slug': 'super-smash-bros-melee-2001'}