<?php
$infoArray = array('Actors' => array('Andrew Duncan',
            'Arthur Burghardt',
            'Beatrice Straight',
            'Betty Ford',
            'Conchata Ferrell',
            'Darryl Hickman',
            'David Susskind',
            'Ed Crowley',
            'Faye Dunaway',
            'Fred Stuthman',
            'Gerald Ford',
            'Howard K Smith',
            'Jerome Dempsey',
            'John Carpenter',
            'John Chancellor',
            'John Gabriel',
            'Jordan Charney',
            'Kathy Cronkite',
            'Ken Kercheval',
            'Kenneth Kimmins',
            'Lance Henriksen',
            'Lane Smith',
            'Lee Richardson',
            'Marlene Warfield',
            'Michael Lipton',
            'Michael Lombard',
            'Michael Tucker',
            'Mitchell Jason',
            'Ned Beatty',
            'Paul Jenkins',
            'Peter Finch',
            'Raymond Martino',
            'Robert Duvall',
            'Roy Poole',
            'Sasha von Scherler',
            'Stanley Grover',
            'Ted Sorel',
            'Tim Robbins',
            'Todd Everett',
            'Walter Cronkite',
            'Wesley Addy',
            'William Holden',
            'William Prince',
            'Zane Lasky'),
 'Added' => '2013-02-24',
 'Countries' => array('USA'),
 'Description' => "\nNetwork: A TV network cynically exploits a deranged ex-TV anchor's ravings and revelations about the media for their own profit. ",
 'Director' => array('Sidney Lumet'),
 'Genres' => array('Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt0074958',
 'PrimeWire' => 'http://www.primewire.ag/watch-1048-Network',
 'Ratings' => array('IMDB' => '8.2/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.99/5',
             'RT' => '91%',
             'Votes' => '139'),
 'Released' => '1976-11-27',
 'Runtime' => '121 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1048_Network_1976.jpg',
 'Title' => 'Network');
?>