{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Gran-Turismo-4',
 'EntryURL': 'https://rawg.io/games/gran-turismo-4',
 'Entry_json': 'Favorites/Games/snapshot/Gran-Turismo-4/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Gran-Turismo-4/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Gran-Turismo-4/thumb.jpg',
 'added': 79,
 'background_image': 'https://media.rawg.io/media/games/113/113392a3c185a57020fa8e4801588acf.jpg',
 'developers': ['Polyphony Digital'],
 'genres': ['Racing'],
 'name': 'Gran Turismo 4',
 'platforms': ['PlayStation 2'],
 'publishers': ['Sony Computer Entertainment'],
 'released': '2004-12-28',
 'slug': 'gran-turismo-4'}