{'Actors': ['Penn Jillette&tv', 'Teller&tv'],
 'Added': '2015-09-04',
 'Countries': ['USA'],
 'Description': "\nPenn & Teller: Bullshit!: Using a combination of set ups, descriptions, rants and film of practitioners, Penn & Teller show the Bull Shit that's everywhere... ",
 'Director': [],
 'Genres': ['Comedy&tv', 'Documentary&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0346369',
 'PrimeWire': 'http://www.primewire.ag/tv-5191-Penn-Teller-Bullshit',
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.84/5',
             'RT': 'N/A',
             'Votes': '351'},
 'Released': '2003-01-24',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5191_Penn_Teller_Bullshit_2003.jpg',
 'Title': 'Penn-Teller-Bullshit'}