{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-House-I-Live-In',
 'EntryURL': 'https://www.imdb.com/title/tt2125653',
 'Entry_json': 'Favorites/Movies/snapshot/The-House-I-Live-In/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-House-I-Live-In/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-House-I-Live-In/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Eugene Jarecki',
            'url': '/name/nm0418659/'},
           {'@type': 'Person',
            'name': 'David Simon',
            'url': '/name/nm0800108/'},
           {'@type': 'Person',
            'name': 'Shanequa Benitez',
            'url': '/name/nm10981839/'},
           {'@type': 'Person',
            'name': 'William Julius Wilson',
            'url': '/name/nm1352293/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 5109,
                      'ratingValue': '7.9',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Eugene Jarecki',
              'url': '/name/nm0418659/'},
             {'@type': 'Person',
              'name': 'Christopher St. John',
              'url': '/name/nm3261459/'},
             {'@type': 'Organization', 'url': '/company/co0393381/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'},
             {'@type': 'Organization', 'url': '/company/co0157676/'},
             {'@type': 'Organization', 'url': '/company/co0351101/'},
             {'@type': 'Organization', 'url': '/company/co0072367/'},
             {'@type': 'Organization', 'url': '/company/co0176028/'},
             {'@type': 'Organization', 'url': '/company/co0067184/'},
             {'@type': 'Organization', 'url': '/company/co0028644/'},
             {'@type': 'Organization', 'url': '/company/co0018439/'},
             {'@type': 'Organization', 'url': '/company/co0078814/'}],
 'datePublished': '2012-10-05',
 'description': 'The House I Live In is a movie starring Eugene Jarecki, David '
                'Simon, and Shanequa Benitez. From the dealer to the narcotics '
                'officer, the inmate to the federal judge, a penetrating look '
                "inside America's criminal justice system,...",
 'director': [{'@type': 'Person',
               'name': 'Eugene Jarecki',
               'url': '/name/nm0418659/'}],
 'duration': 'PT1H48M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk4ODQxNzE4N15BMl5BanBnXkFtZTcwMjY3MjUzOA@@._V1_.jpg',
 'keywords': 'u.s. mexico border,despair,american history,judge,federal judge',
 'name': 'The House I Live In',
 'trailer': [{'@type': 'VideoObject',
              'description': "An investigative look at America's war on drugs "
                             'and its impact on the criminal justice system, '
                             'with a focus on the experiences of Nannie Jeter, '
                             "a former employee of filmmaker Eugene Jarecki's "
                             'family.',
              'embedUrl': '/video/imdb/vi4175930393',
              'name': 'Theatrical Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQyNjUzMzI1MV5BMl5BanBnXkFtZTcwODc3MTM0OA@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQyNjUzMzI1MV5BMl5BanBnXkFtZTcwODc3MTM0OA@@._V1_.jpg',
              'uploadDate': '2012-09-05T09:07:20Z'}],
 'url': '/title/tt2125653/'}