{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-03-11',
 'EntryPath': 'Favorites/TV/snapshot/Banshee',
 'EntryURL': 'https://www.imdb.com/title/tt2017109',
 'Entry_json': 'Favorites/TV/snapshot/Banshee/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Banshee/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Banshee/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Antony Starr',
            'url': '/name/nm1102278/'},
           {'@type': 'Person',
            'name': 'Ivana Milicevic',
            'url': '/name/nm0587431/'},
           {'@type': 'Person',
            'name': 'Ulrich Thomsen',
            'url': '/name/nm0860947/'},
           {'@type': 'Person',
            'name': 'Frankie Faison',
            'url': '/name/nm0265670/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 82550,
                      'ratingValue': '8.4',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'David Schickler',
              'url': '/name/nm1416926/'},
             {'@type': 'Person',
              'name': 'Jonathan Tropper',
              'url': '/name/nm2267086/'},
             {'@type': 'Organization', 'url': '/company/co0247237/'},
             {'@type': 'Organization', 'url': '/company/co0042496/'}],
 'datePublished': '2013-01-11',
 'description': 'Banshee is a TV series starring Antony Starr, Ivana '
                'Milicevic, and Ulrich Thomsen. An ex-con assumes the identity '
                'of a murdered sheriff in the small town of Banshee, '
                'Pennsylvania, where he has some unfinished business.',
 'genre': ['Action', 'Crime', 'Drama', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTkzNTA1MDI5M15BMl5BanBnXkFtZTcwNTY3NjAwOQ@@._V1_.jpg',
 'keywords': 'man with no name,pennsylvania,thief,tough girl,double life',
 'name': 'Banshee',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Second season 4 trailer for Banshee on Cinemax.',
              'embedUrl': '/video/imdb/vi1681503513',
              'name': 'Season 4 Trailer #2',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTk5MDEzNjIwNl5BMl5BanBnXkFtZTgwODE5NTQxODE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTk5MDEzNjIwNl5BMl5BanBnXkFtZTgwODE5NTQxODE@._V1_.jpg',
              'uploadDate': '2016-02-26T10:54:51Z'}],
 'url': '/title/tt2017109/'}