{'Actors': ['Frankie Faison&tv',
            'Ivana Milicevic&tv',
            'Matt Servitto&tv',
            'Rus Blackwell&tv',
            'Steve Coulter&tv',
            'Ulrich Thomsen&tv'],
 'Added': '2013-03-11',
 'Countries': ['USA'],
 'Description': '\n'
                'Banshee: An ex-con and master thief who assumes the identity '
                'of the sheriff of Banshee, Pennsylvania, where he continues '
                'his criminal activities, even as hes hunted by the shadowy '
                'gangsters he betrayed years earlier. ',
 'Director': ['NA'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Banshee',
 'EntryURL': 'http://www.imdb.com/title/tt2017109',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Banshee/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Banshee/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Banshee/info.py',
 'Genres': ['Crime&tv', 'Drama&tv', 'Mystery&tv'],
 'IMDB': 'http://www.imdb.com/title/tt2017109',
 'PrimeWire': 'http://www.primewire.ag/tv-2737140-Banshee',
 'Ratings': {'IMDB': '8.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.44/5',
             'RT': 'N/A',
             'Votes': '1041'},
 'Released': '2013-01-11',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2737140_Banshee_2013.jpg',
 'Title': 'Banshee'}