apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ResumePPCluster
  region: ${aws_region}
vpc:
  id: ${VPC}
  subnets:
    private:
      us-west-2a:
        id: ${PrivateSubnet01}
      us-west-2b:
        id: ${PrivateSubnet02}
    public:
      us-west-2c:
        id: ${PublicSubnet01}
      us-west-2d:
        id: ${PublicSubnet02}

managedNodeGroups:
  - name: ResumePPWebNodes
    instanceType: ${instanceType}
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 5
    ssh:
      allow: true
      publicKeyPath: ${aws_publickey_path}
      # new feature for restricting SSH access to certain AWS security group IDs
      sourceSecurityGroupIds: [" ${ControlPlaneSecurityGroup} "]
    labels: 
      role: webserver
      app: webserver
    tags:
      nodegroup-role: webserver
      app: webserver
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

  - name: ResumePPDataNodes
    instanceType: ${instanceType}
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 5
    ssh:
      allow: true
      publicKeyPath: ${aws_publickey_path}
      # new feature for restricting SSH access to certain AWS security group IDs
      sourceSecurityGroupIds: [" ${ControlPlaneSecurityGroup} "]
    labels: 
      role: datascraper
      app: datascraper
    tags:
      nodegroup-role: datascraper
      app: datascraper
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
