apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ResumePP_Cluster
  region: ${aws_region}
vpc:
  id: ${aws_vpc_name}
#  subnets:
#    private:
#      us-west-2a:
#        id: ${subnet1_name}
#      us-west-2b:
#        id: ${subnet2_name}
#    public:
#      us-west-2c:
#        id: ${subnet3_name}
#      us-west-2d:
#        id: ${subnet4_name}

managedNodeGroups:
  - name: ResumePP_WebNodes
    instanceType: ${instanceType}
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 5
    ssh:
      allow: true
      publicKeyPath: ${aws_key_path}
      # new feature for restricting SSH access to certain AWS security group IDs
      sourceSecurityGroupIds: [" ${GroupId} "]
    labels: 
      role: webserver
      app: webserver
    tags:
      nodegroup-role: webserver
      app: webserver
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

  - name: ResumePP_DataNodes
    instanceType: ${instanceType}
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 5
    ssh:
      allow: true
      publicKeyPath: ${aws_key_path}
      # new feature for restricting SSH access to certain AWS security group IDs
      sourceSecurityGroupIds: [" ${GroupId} "]
    labels: 
      role: datascraper
      app: datascraper
    tags:
      nodegroup-role: datascraper
      app: datascraper
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
