version: '3'

services:
  resume-service:
    image: php:apache
    expose:
      - 80
    volumes:
      - ../:/var/www/html/
    ports:
      - 8080:80
  datascraper-service:
    build: ../
    volumes:
      - ../:/mnt/w/