{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Limitless',
 'EntryURL': 'https://www.imdb.com/title/tt1219289',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Limitless/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Limitless/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Limitless/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bradley Cooper',
            'url': '/name/nm0177896/'},
           {'@type': 'Person', 'name': 'Anna Friel', 'url': '/name/nm0295484/'},
           {'@type': 'Person',
            'name': 'Abbie Cornish',
            'url': '/name/nm0180411/'},
           {'@type': 'Person',
            'name': 'Robert De Niro',
            'url': '/name/nm0000134/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 515003,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Leslie Dixon',
              'url': '/name/nm0228908/'},
             {'@type': 'Person',
              'name': 'Alan Glynn',
              'url': '/name/nm2982186/'},
             {'@type': 'Organization', 'url': '/company/co0142678/'},
             {'@type': 'Organization', 'url': '/company/co0310456/'},
             {'@type': 'Organization', 'url': '/company/co0311504/'},
             {'@type': 'Organization', 'url': '/company/co0328487/'},
             {'@type': 'Organization', 'url': '/company/co0053368/'},
             {'@type': 'Organization', 'url': '/company/co0040675/'}],
 'datePublished': '2011-03-17',
 'description': 'Limitless is a movie starring Bradley Cooper, Anna Friel, and '
                'Abbie Cornish. With the help of a mysterious pill that '
                'enables the user to access 100% of his brain abilities, a '
                'struggling writer becomes a financial wizard, but it also...',
 'director': {'@type': 'Person',
              'name': 'Neil Burger',
              'url': '/name/nm1139726/'},
 'duration': 'PT1H45M',
 'genre': ['Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYmViZGM0MGItZTdiYi00ZDU4LWIxNDYtNTc1NWQ5Njc2N2YwXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
 'keywords': 'drug,experimental drug,brain capacity,rapid '
             'learning,intelligence',
 'name': 'Limitless',
 'trailer': {'@type': 'VideoObject',
             'description': 'Limitless -- Super Bowl Spot',
             'embedUrl': '/video/imdb/vi2114755097',
             'name': 'Super Bowl Spot',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTc0NDYzMzAxN15BMl5BanBnXkFtZTcwMDA2NzI0NA@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTc0NDYzMzAxN15BMl5BanBnXkFtZTcwMDA2NzI0NA@@._V1_.jpg',
             'uploadDate': '2011-02-05T15:37:03Z'},
 'url': '/title/tt1219289/'}