{'Actors': ['&#xC1;lvaro Guerrero',
            '&#xC1;ngeles Mar&#xED;n',
            'Adriana Barraza',
            'Ana Mar&#xED;a Gonz&#xE1;lez',
            'Carlos Samperio',
            'Dagoberto Gama',
            'Dunia Sald&#xED;var',
            'Emilio Echevarr&#xED;a',
            'Gael Garc&#xED;a Bernal',
            'Goya Toledo',
            'Gustavo S&#xE1;nchez Parra',
            'Jorge Salinas',
            'Jose Luis Barraza',
            'Jose Sefami',
            'Laura Almela',
            'Mauricio Mart&#xED;nez',
            'Patricio Castillo',
            'Ricardo Dalmacci',
            'Roberto Medina',
            'Rosa Mar&#xED;a Bianchi',
            'Vanessa Bauche'],
 'Added': '2013-02-23',
 'Countries': ['Mexico'],
 'Description': '\n'
                'Amores perros: A horrific car accident connects three '
                'stories, each involving characters dealing with loss, regret, '
                "and life's harsh realities, all in the name of love. ",
 'Director': ['Alejandro Gonz&#xE1;lez I&#xF1;&#xE1;rritu'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Amores-perros',
 'EntryURL': 'http://www.imdb.com/title/tt0245712',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Amores-perros/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Amores-perros/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Amores-perros/info.py',
 'Genres': ['Drama', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt0245712',
 'PrimeWire': 'http://www.primewire.ag/watch-4623-Amores-perros',
 'Ratings': {'IMDB': '8.1/10',
             'Metascore': '83%',
             'PrimeWire': '3.72/5',
             'RT': '92%',
             'Votes': '282'},
 'Released': '2000-05-14',
 'Runtime': '154 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/4623_Amores_perros_2000.jpg',
 'Title': 'Amores-perros'}