{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Amores-perros',
 'EntryURL': 'https://www.imdb.com/title/tt0245712',
 'Entry_json': 'Favorites/Movies/snapshot/Amores-perros/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Amores-perros/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Amores-perros/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Emilio Echevarría',
            'url': '/name/nm0248408/'},
           {'@type': 'Person',
            'name': 'Gael García Bernal',
            'url': '/name/nm0305558/'},
           {'@type': 'Person',
            'name': 'Goya Toledo',
            'url': '/name/nm0865949/'},
           {'@type': 'Person',
            'name': 'Álvaro Guerrero',
            'url': '/name/nm0346270/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 216930,
                      'ratingValue': '8.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Guillermo Arriaga',
              'url': '/name/nm0037247/'},
             {'@type': 'Organization', 'url': '/company/co0133276/'},
             {'@type': 'Organization', 'url': '/company/co0007410/'}],
 'datePublished': '2000-06-16',
 'description': 'Amores perros is a movie starring Emilio Echevarría, Gael '
                'García Bernal, and Goya Toledo. A horrific car accident '
                'connects three stories, each involving characters dealing '
                "with loss, regret, and life's harsh realities, all in the...",
 'director': [{'@type': 'Person',
               'name': 'Alejandro G. Iñárritu',
               'url': '/name/nm0327944/'}],
 'duration': 'PT2H34M',
 'genre': ['Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMWJhOTg5MWQtYTJjMi00YmFkLTg4ODgtYmU2YWVhODQ4ZDM3XkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg',
 'keywords': 'multiple storyline,dog,mexico city,multiple '
             'perspectives,nonlinear timeline',
 'name': 'Amores perros',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Original trailer - do not delete without '
                             'contacting gamazoa -',
              'embedUrl': '/video/imdb/vi2171189785',
              'name': 'Tráiler [OV]',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZGI5M2EzNDMtYmQ1My00ZDBmLWFiODEtYWZiOTkyOWVkM2UwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZGI5M2EzNDMtYmQ1My00ZDBmLWFiODEtYWZiOTkyOWVkM2UwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-02-15T17:56:45Z'}],
 'url': '/title/tt0245712/'}