<?php
$infoArray = array('Actors' => array('Amy Adams',
            'Chris Pratt',
            'Joaquin Phoenix',
            'Katherine Boecher',
            'Laura Meadows',
            'Matt Letscher',
            'Olivia Wilde',
            'Rooney Mara',
            'Sam Jaeger',
            'Scarlett Johansson'),
 'Added' => '2014-01-09',
 'Countries' => array('USA'),
 'Description' => "\nHer: A lonely writer develops an unlikely relationship with his newly-purchased operating system that's designed to meet his every need. ",
 'Director' => array('Spike Jonze'),
 'Genres' => array('Drama', 'Romance', 'Sci-Fi'),
 'IMDB' => 'http://www.imdb.com/title/tt1798709',
 'PrimeWire' => 'http://www.primewire.ag/watch-2743656-Her',
 'Ratings' => array('IMDB' => '8.0/10',
             'Metascore' => '90%',
             'PrimeWire' => '4.02/5',
             'RT' => '94%',
             'Votes' => '1408'),
 'Released' => '2013-12-18',
 'Runtime' => '126 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2743656_Her_2014.jpg',
 'Title' => 'Her');
?>