{'Actors': ['Bo Svenson',
            'Caitlin Keats',
            'Chia Hui Liu',
            'Christopher Allen Nelson',
            'Clark Middleton',
            'Daryl Hannah',
            'David Carradine',
            'Gary Rodriguez',
            'Helen Kim',
            'Jeannie Epper',
            'Jorge Silva',
            'Julie Dreyfus',
            'Larry Bishop',
            'Laura Cayouette',
            'Lawrence Bender',
            'Lucy Liu',
            'Michael Madsen',
            'Michael Parks',
            'Quentin Tarantino',
            'Samuel L Jackson',
            'Sid Haig',
            'Stevo Polyi',
            'Uma Thurman',
            'Venessia Valentino',
            'Vivica A Fox'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': "\nKill Bill: Vol. 2: The murderous Bride continues her vengeance quest against her ex-boss, Bill, and his two remaining associates; his younger brother Budd, and Bill's latest flame Elle. ",
 'Director': ['Quentin Tarantino'],
 'Genres': ['Action', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt0378194',
 'PrimeWire': 'http://www.primewire.ag/watch-606-Kill-Bill-Vol-2',
 'Ratings': {'IMDB': '8.0/10',
             'Metascore': '83%',
             'PrimeWire': '3.65/5',
             'RT': '84%',
             'Votes': '1296'},
 'Released': '2004-04-16',
 'Runtime': '136 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/606_Kill_Bill_Vol_2_2004.jpg',
 'Title': 'Kill-Bill-Vol-2'}