{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-20',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Garden-State',
 'EntryURL': 'https://www.imdb.com/title/tt0333766',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Garden-State/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Garden-State/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Garden-State/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Zach Braff', 'url': '/name/nm0103785/'},
           {'@type': 'Person',
            'name': 'Peter Sarsgaard',
            'url': '/name/nm0765597/'},
           {'@type': 'Person',
            'name': 'Natalie Portman',
            'url': '/name/nm0000204/'},
           {'@type': 'Person', 'name': 'Ian Holm', 'url': '/name/nm0000453/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 204465,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Zach Braff',
              'url': '/name/nm0103785/'},
             {'@type': 'Organization', 'url': '/company/co0084122/'},
             {'@type': 'Organization', 'url': '/company/co0010434/'},
             {'@type': 'Organization', 'url': '/company/co0118437/'},
             {'@type': 'Organization', 'url': '/company/co0095140/'},
             {'@type': 'Organization', 'url': '/company/co0249085/'}],
 'datePublished': '2004-08-20',
 'description': 'Garden State is a movie starring Zach Braff, Peter Sarsgaard, '
                'and Natalie Portman. A quietly troubled young man returns '
                "home for his mother's funeral after being estranged from his "
                'family for a decade.',
 'director': {'@type': 'Person',
              'name': 'Zach Braff',
              'url': '/name/nm0103785/'},
 'duration': 'PT1H42M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjc5MDE0NjkxOF5BMl5BanBnXkFtZTcwNzA0NTkyMw@@._V1_.jpg',
 'keywords': 'funeral,home,actor,pills,implied sex',
 'name': 'Garden State',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi1873084697',
             'name': 'Garden State',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjZjYjA3ZGMtNzcwMC00MDY3LWIyMWQtZTg4NGJlYTA3ZjcxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjZjYjA3ZGMtNzcwMC00MDY3LWIyMWQtZTg4NGJlYTA3ZjcxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:01:29Z'},
 'url': '/title/tt0333766/'}