{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Super-Mario-Bros-3',
 'EntryURL': 'https://rawg.io/games/super-mario-bros-3',
 'Entry_json': 'Favorites/Games/snapshot/Super-Mario-Bros-3/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Super-Mario-Bros-3/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Super-Mario-Bros-3/thumb.jpg',
 'added': 562,
 'background_image': 'https://media.rawg.io/media/screenshots/092/092fc1910f067a95a07c0fbfdbe25f03.jpg',
 'developers': ['Nintendo'],
 'genres': ['Action', 'Adventure', 'Platformer'],
 'name': 'Super Mario Bros. 3',
 'platforms': ['SNES',
               'Nintendo Switch',
               'Game Boy Color',
               'NES',
               'Nintendo 3DS',
               'Wii U',
               'Wii'],
 'publishers': ['Nintendo'],
 'released': '1988-10-23',
 'slug': 'super-mario-bros-3'}