{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-30',
 'EntryPath': 'Favorites/Movies/snapshot/Sophie-Scholl-Die-letzten-Tage',
 'EntryURL': 'https://www.imdb.com/title/tt0426578',
 'Entry_json': 'Favorites/Movies/snapshot/Sophie-Scholl-Die-letzten-Tage/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Sophie-Scholl-Die-letzten-Tage/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Sophie-Scholl-Die-letzten-Tage/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Julia Jentsch',
            'url': '/name/nm0421799/'},
           {'@type': 'Person',
            'name': 'Fabian Hinrichs',
            'url': '/name/nm1443396/'},
           {'@type': 'Person',
            'name': 'Alexander Held',
            'url': '/name/nm0374901/'},
           {'@type': 'Person',
            'name': 'Johanna Gastdorf',
            'url': '/name/nm0309404/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 25919,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Fred Breinersdorfer',
              'url': '/name/nm0106937/'},
             {'@type': 'Organization', 'url': '/company/co0138178/'},
             {'@type': 'Organization', 'url': '/company/co0054991/'}],
 'datePublished': '2005-02-24',
 'description': 'Sophie Scholl - Die letzten Tage is a movie starring Julia '
                'Jentsch, Fabian Hinrichs, and Alexander Held. A dramatization '
                'of the final days of Sophie Scholl, one of the most famous '
                'members of the German World War II anti-Nazi...',
 'director': [{'@type': 'Person',
               'name': 'Marc Rothemund',
               'url': '/name/nm0745131/'}],
 'duration': 'PT2H',
 'genre': ['Biography', 'Crime', 'Drama', 'History', 'Thriller', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk3OTk2NTAyMV5BMl5BanBnXkFtZTcwMzAyMDIzMQ@@._V1_.jpg',
 'keywords': 'resistance,anti nazi,gestapo,nazi,student',
 'name': 'Sophie Scholl - Die letzten Tage',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Zeitgeist Films',
              'embedUrl': '/video/imdb/vi3565748505',
              'name': 'Sophie Scholl: The Final Days',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZmI1MTliNzYtN2IyNC00ZjMxLWExODQtMTg1MDAyMjg2NmI5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZmI1MTliNzYtN2IyNC00ZjMxLWExODQtMTg1MDAyMjg2NmI5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T16:12:13Z'}],
 'url': '/title/tt0426578/'}