{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Fight-Club',
 'EntryURL': 'https://www.imdb.com/title/tt0137523',
 'Entry_json': 'Favorites/Movies/snapshot/Fight-Club/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Fight-Club/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Fight-Club/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Brad Pitt', 'url': '/name/nm0000093/'},
           {'@type': 'Person',
            'name': 'Edward Norton',
            'url': '/name/nm0001570/'},
           {'@type': 'Person', 'name': 'Meat Loaf', 'url': '/name/nm0001533/'},
           {'@type': 'Person',
            'name': 'Zach Grenier',
            'url': '/name/nm0340260/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1786841,
                     'ratingValue': '8.8',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Chuck Palahniuk',
              'url': '/name/nm0657333/'},
             {'@type': 'Person', 'name': 'Jim Uhls', 'url': '/name/nm0880243/'},
             {'@type': 'Organization', 'url': '/company/co0017497/'},
             {'@type': 'Organization', 'url': '/company/co0021592/'},
             {'@type': 'Organization', 'url': '/company/co0038102/'},
             {'@type': 'Organization', 'url': '/company/co0064947/'},
             {'@type': 'Organization', 'url': '/company/co0088185/'},
             {'@type': 'Organization', 'url': '/company/co0117688/'},
             {'@type': 'Organization', 'url': '/company/co0043164/'}],
 'datePublished': '1999-10-15',
 'description': 'Fight Club is a movie starring Brad Pitt, Edward Norton, and '
                'Meat Loaf. An insomniac office worker and a devil-may-care '
                'soapmaker form an underground fight club that evolves into '
                'something much, much more.',
 'director': {'@type': 'Person',
              'name': 'David Fincher',
              'url': '/name/nm0000399/'},
 'duration': 'PT2H19M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'surprise ending,fighting,anti establishment,insomnia,multiple '
             'personality disorder',
 'name': 'Fight Club',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Fight Club',
             'embedUrl': '/video/imdb/vi781228825',
             'name': 'Fight Club',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTNmYzllNWYtYzU1Yi00YWFmLTgwMzMtZmY4OGE3NzExNzEzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTNmYzllNWYtYzU1Yi00YWFmLTgwMzMtZmY4OGE3NzExNzEzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-01-01T06:12:45Z'},
 'url': '/title/tt0137523/'}