{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Fear-and-Loathing-in-Las-Vegas',
 'EntryURL': 'https://www.imdb.com/title/tt0120669',
 'Entry_json': 'Favorites/Movies/snapshot/Fear-and-Loathing-in-Las-Vegas/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Fear-and-Loathing-in-Las-Vegas/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Fear-and-Loathing-in-Las-Vegas/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Johnny Depp',
            'url': '/name/nm0000136/'},
           {'@type': 'Person',
            'name': 'Benicio Del Toro',
            'url': '/name/nm0001125/'},
           {'@type': 'Person',
            'name': 'Tobey Maguire',
            'url': '/name/nm0001497/'},
           {'@type': 'Person',
            'name': 'Michael Lee Gogin',
            'url': '/name/nm0324672/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 252072,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Hunter S. Thompson',
              'url': '/name/nm0860219/'},
             {'@type': 'Person',
              'name': 'Terry Gilliam',
              'url': '/name/nm0000416/'},
             {'@type': 'Person',
              'name': 'Tony Grisoni',
              'url': '/name/nm0342617/'},
             {'@type': 'Person',
              'name': 'Tod Davies',
              'url': '/name/nm0204000/'},
             {'@type': 'Person', 'name': 'Alex Cox', 'url': '/name/nm0007182/'},
             {'@type': 'Organization', 'url': '/company/co0095293/'},
             {'@type': 'Organization', 'url': '/company/co0032380/'},
             {'@type': 'Organization', 'url': '/company/co0095294/'},
             {'@type': 'Organization', 'url': '/company/co0046206/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'}],
 'datePublished': '1998-05-22',
 'description': 'Fear and Loathing in Las Vegas is a movie starring Johnny '
                'Depp, Benicio Del Toro, and Tobey Maguire. An oddball '
                'journalist and his psychopathic lawyer travel to Las Vegas '
                'for a series of psychedelic escapades.',
 'director': [{'@type': 'Person',
               'name': 'Terry Gilliam',
               'url': '/name/nm0000416/'}],
 'duration': 'PT1H58M',
 'genre': ['Adventure', 'Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjA2ZDY3ZjYtZmNiMC00MDU5LTgxMWEtNzk1YmI3NzdkMTU0XkEyXkFqcGdeQXVyNjQyMjcwNDM@._V1_.jpg',
 'keywords': 'drugs,hallucination,1970s,lawyer,journalist',
 'name': 'Fear and Loathing in Las Vegas',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Three Reasons Criterion Collection Trailer for '
                             'Fear and Loathing in Las Vegas',
              'embedUrl': '/video/imdb/vi2996149273',
              'name': 'Fear and Loathing in Las Vegas: Criterion Collection',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYzk4NGQ4ZjItODE5My00MjNiLWE2NjYtMjNhYWE3OGY3YThkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYzk4NGQ4ZjItODE5My00MjNiLWE2NjYtMjNhYWE3OGY3YThkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2011-06-23T03:16:26Z'}],
 'url': '/title/tt0120669/'}