{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Ozark',
 'EntryURL': 'https://www.imdb.com/title/tt5071412',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Ozark/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Ozark/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Ozark/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Ozark/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jason Bateman',
            'url': '/name/nm0000867/'},
           {'@type': 'Person',
            'name': 'Laura Linney',
            'url': '/name/nm0001473/'},
           {'@type': 'Person',
            'name': 'Sofia Hublitz',
            'url': '/name/nm6019117/'},
           {'@type': 'Person',
            'name': 'Skylar Gaertner',
            'url': '/name/nm3228287/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 155639,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Bill Dubuque',
              'url': '/name/nm4057793/'},
             {'@type': 'Person',
              'name': 'Mark Williams',
              'url': '/name/nm0931251/'},
             {'@type': 'Organization', 'url': '/company/co0086332/'},
             {'@type': 'Organization', 'url': '/company/co0194736/'}],
 'datePublished': '2017-07-21',
 'description': 'Ozark is a TV series starring Jason Bateman, Laura Linney, '
                'and Sofia Hublitz. A financial advisor drags his family from '
                'Chicago to the Missouri Ozarks, where he must launder money '
                'to appease a drug boss.',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2Q3MjQ3NDAtZDk4NS00MDIwLTllZGUtMmY1ZDU2OTJkNGY2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'netflix original,missouri,mexico,drug cartel,financial advisor',
 'name': 'Ozark',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'laragi'},
            'dateCreated': '2020-05-05',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt5071412/'},
            'name': 'Very unique. Terrific Actors',
            'reviewBody': 'I never would have watched this if not for the '
                          "quarantine. It wasn't promoted well. I LOVED IT! "
                          'Great script, tons of action and characters that '
                          'you love to hate and hate to love.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Official Trailer for Ozark Season 3. All new '
                            'episodes arrive on Netflix March 27, 2020. They '
                            'are all in. The Byrdes are back in business and '
                            'the stakes have never been higher. As tensions '
                            'mount surrounding their new casino, The Missouri '
                            'Belle, Marty and Wendy struggle to balance their '
                            "family's safety with the growing success of their "
                            'money laundering empire.',
             'embedUrl': '/video/imdb/vi3030564377',
             'name': 'Season 3 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODEzZGZmNWQtNTI4Ny00MGNiLWFlMGYtNzdlM2EyZGNhYTc4XkEyXkFqcGdeQWFybm8@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODEzZGZmNWQtNTI4Ny00MGNiLWFlMGYtNzdlM2EyZGNhYTc4XkEyXkFqcGdeQWFybm8@._V1_.jpg',
             'uploadDate': '2020-03-05T18:13:26Z'},
 'url': '/title/tt5071412/'}