{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds',
 'EntryURL': 'https://www.imdb.com/title/tt0361748',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Brad Pitt', 'url': '/name/nm0000093/'},
           {'@type': 'Person',
            'name': 'Diane Kruger',
            'url': '/name/nm1208167/'},
           {'@type': 'Person', 'name': 'Eli Roth', 'url': '/name/nm0744834/'},
           {'@type': 'Person',
            'name': 'Mélanie Laurent',
            'url': '/name/nm0491259/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1212710,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0150452/'},
             {'@type': 'Organization', 'url': '/company/co0019267/'},
             {'@type': 'Organization', 'url': '/company/co0053177/'},
             {'@type': 'Organization', 'url': '/company/co0282627/'}],
 'datePublished': '2009-08-19',
 'description': 'Inglourious Basterds is a movie starring Brad Pitt, Diane '
                'Kruger, and Eli Roth. In Nazi-occupied France during World '
                'War II, a plan to assassinate Nazi leaders by a group of '
                "Jewish U.S. soldiers coincides with a theatre owner's...",
 'director': {'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
 'duration': 'PT2H33M',
 'genre': ['Adventure', 'Drama', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
 'keywords': 'nazi,revenge,nazi hunter,massacre,world war two',
 'name': 'Inglourious Basterds',
 'trailer': {'@type': 'VideoObject',
             'description': 'International trailer',
             'embedUrl': '/video/imdb/vi3738173977',
             'name': 'Inglourious Basterds: International Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTY2MzMzMTMyOF5BMl5BanBnXkFtZTgwNzA3MTEyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTY2MzMzMTMyOF5BMl5BanBnXkFtZTgwNzA3MTEyMzE@._V1_.jpg',
             'uploadDate': '2009-07-07T03:43:15Z'},
 'url': '/title/tt0361748/'}