{'Actors': ['Aleksandrs Petukhovs',
            'Andre Penvern',
            'Arndt Schwering-Sohnrey',
            'August Diehl',
            'Bela B Felsenheimer',
            'Bo Svenson',
            'Brad Pitt',
            'Buddy Joe Hooker',
            'Christian Berkel',
            'Christian Br&#xFC;ckner',
            'Christoph Waltz',
            'Daniel Br&#xFC;hl',
            'Denis Menochet',
            'Diane Kruger',
            'Eli Roth',
            'Enzo G Castellari',
            'Gedeon Burkhard',
            'Gregory Nicotero',
            'Guido F&#xF6;hrwei&#xDF;er',
            'Harvey Keitel',
            'Hel&#xE8;ne Cardona',
            'Hilmar Eichhorn',
            'Jana Pallaske',
            'Julie Dreyfus',
            'Ken Duken',
            'Lea Seydoux',
            'Ludger Pistor',
            'Martin Wuttke',
            'Mélanie Laurent',
            'Michael Bacall',
            'Michael Fassbender',
            'Mike Myers',
            'Patrick Elias',
            'Richard Sammel',
            'Rod Taylor',
            'Sabrina Rattey',
            'Samm Levine',
            'Samuel L Jackson',
            'Sylvester Groth',
            'Til Schweiger',
            'Tina Rodriguez',
            'Wilfried Hochholdinger'],
 'Added': '2013-02-19',
 'Countries': ['USA', 'Germany'],
 'Description': '\r\n'
                '              Inglourious Basterds: In Nazi-occupied France '
                'during World War II, a group of Jewish-American soldiers '
                'known as "The Basterds" are chosen specifically to spread '
                'fear throughout the Third Reich by scalping and brutally '
                'killing Nazis.            ',
 'Director': ['Quentin Tarantino'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds',
 'EntryURL': 'https://www.imdb.com/title/tt0361748',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Inglourious-Basterds/info.py',
 'Genres': ['Action', 'Drama', 'War'],
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': '69%',
             'PrimeWire': '3.82/5',
             'RT': '88%',
             'Votes': '1854'},
 'Released': '2009-08-21',
 'Runtime': '153 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/18058_Inglourious_Basterds_2009.jpg',
 'Title': 'Inglourious-Basterds'}