{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Tomb-Raider-1996',
 'EntryURL': 'https://rawg.io/games/tomb-raider-1996',
 'Entry_json': 'Favorites/Games/snapshot/Tomb-Raider-1996/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Tomb-Raider-1996/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Tomb-Raider-1996/thumb.jpg',
 'added': 292,
 'background_image': 'https://media.rawg.io/media/screenshots/dfc/dfc6b42f0833183b0491403ec93653a7.jpg',
 'developers': ['Core Design Limited'],
 'genres': ['Action'],
 'name': 'Tomb Raider',
 'platforms': ['PlayStation',
               'iOS',
               'Android',
               'PSP',
               'PS Vita',
               'PlayStation 3',
               'PC'],
 'publishers': ['Eidos Interactive'],
 'released': '1996-11-15',
 'slug': 'tomb-raider-1996'}