{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-10-08',
 'EntryPath': 'Favorites/TV/snapshot/Last-Week-Tonight-with-John-Oliver',
 'EntryURL': 'https://www.imdb.com/title/tt3530232',
 'Entry_json': 'Favorites/TV/snapshot/Last-Week-Tonight-with-John-Oliver/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Last-Week-Tonight-with-John-Oliver/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Last-Week-Tonight-with-John-Oliver/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Oliver',
            'url': '/name/nm1056659/'},
           {'@type': 'Person', 'name': 'David Kaye', 'url': '/name/nm0443286/'},
           {'@type': 'Person',
            'name': 'Ryan Barger',
            'url': '/name/nm2175486/'},
           {'@type': 'Person',
            'name': 'Noel MacNeal',
            'url': '/name/nm0534115/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 74669,
                      'ratingValue': '8.9',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Organization', 'url': '/company/co0339089/'},
             {'@type': 'Organization', 'url': '/company/co0103754/'},
             {'@type': 'Organization', 'url': '/company/co0008693/'}],
 'datePublished': '2014-04-27',
 'description': 'Last Week Tonight with John Oliver is a TV series starring '
                'John Oliver, David Kaye, and Ryan Barger. Former Daily Show '
                'host and correspondent John Oliver brings his persona to this '
                'weekly news satire program.',
 'genre': ['Comedy', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTZiOTFjZTUtNDUxYi00OWRhLWE5NTctYmUyY2VlYTJhM2M4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'news satire,woke,2010s,anti trump media,trump hate',
 'name': 'Last Week Tonight with John Oliver',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Last Week Tonight With John Oliver: Season 3',
              'embedUrl': '/video/imdb/vi3962944793',
              'name': 'Last Week Tonight With John Oliver: Season 3',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDQxYTJkZWMtMjRlNC00ZDJkLThkZDgtNzU0YzFhMjMyZTczXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDQxYTJkZWMtMjRlNC00ZDJkLThkZDgtNzU0YzFhMjMyZTczXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-04-09T17:01:51Z'}],
 'url': '/title/tt3530232/'}