{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-06',
 'EntryPath': 'Favorites/Movies/snapshot/Castles-in-the-Sky',
 'EntryURL': 'https://www.imdb.com/title/tt3311900',
 'Entry_json': 'Favorites/Movies/snapshot/Castles-in-the-Sky/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Castles-in-the-Sky/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Castles-in-the-Sky/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Eddie Izzard',
            'url': '/name/nm0412850/'},
           {'@type': 'Person',
            'name': 'Laura Fraser',
            'url': '/name/nm0292182/'},
           {'@type': 'Person',
            'name': 'Arran Tulloch',
            'url': '/name/nm6728450/'},
           {'@type': 'Person',
            'name': 'Lesley Harcourt',
            'url': '/name/nm0362003/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 868,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Ian Kershaw',
              'url': '/name/nm0449959/'},
             {'@type': 'Organization', 'url': '/company/co0454322/'},
             {'@type': 'Organization', 'url': '/company/co0197375/'},
             {'@type': 'Organization', 'url': '/company/co0096128/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'}],
 'datePublished': '2014-06-23',
 'description': 'Castles in the Sky is a movie starring Eddie Izzard, Laura '
                'Fraser, and Arran Tulloch. It is the mid-1930s and the storm '
                'clouds of WWII are forming in Germany. This film charts the '
                'work of Robert Watson Watt, the pioneer of Radar,...',
 'director': {'@type': 'Person',
              'name': 'Gillies MacKinnon',
              'url': '/name/nm0533564/'},
 'duration': 'PT1H30M',
 'genre': ['Biography', 'Drama', 'History', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjI0NTkwMDg5OF5BMl5BanBnXkFtZTgwOTM4ODIyNzE@._V1_.jpg',
 'keywords': '1930s,world war two,radar,scientist,winston churchill',
 'name': 'Castles in the Sky',
 'url': '/title/tt3311900/'}