{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Riven-The-Sequel-To-Myst',
 'EntryURL': 'https://rawg.io/games/riven-the-sequel-to-myst',
 'Entry_json': 'Favorites/Games/snapshot/Riven-The-Sequel-To-Myst/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Riven-The-Sequel-To-Myst/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Riven-The-Sequel-To-Myst/thumb.jpg',
 'added': 261,
 'background_image': 'https://media.rawg.io/media/games/369/36925f823ec3e9e28a91729c88bf31ec.jpg',
 'developers': ['Cyan Worlds', 'Noodlecake Studios Inc'],
 'genres': ['Adventure', 'Casual', 'Puzzle'],
 'name': 'Riven: The Sequel to Myst',
 'platforms': ['Android', 'PC', 'iOS', 'macOS'],
 'publishers': ['Cyan Worlds', 'Cyan Worlds, Inc', 'Cyan Inc'],
 'released': '1997-11-29',
 'slug': 'riven-the-sequel-to-myst'}