{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-09',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Reader',
 'EntryURL': 'https://www.imdb.com/title/tt0976051',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Reader/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Reader/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Reader/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kate Winslet',
            'url': '/name/nm0000701/'},
           {'@type': 'Person',
            'name': 'Ralph Fiennes',
            'url': '/name/nm0000146/'},
           {'@type': 'Person', 'name': 'Bruno Ganz', 'url': '/name/nm0004486/'},
           {'@type': 'Person',
            'name': 'Jeanette Hain',
            'url': '/name/nm0354198/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 225643,
                     'ratingValue': '7.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'David Hare',
              'url': '/name/nm0002376/'},
             {'@type': 'Person',
              'name': 'Bernhard Schlink',
              'url': '/name/nm0772384/'},
             {'@type': 'Organization', 'url': '/company/co0150452/'},
             {'@type': 'Organization', 'url': '/company/co0038270/'},
             {'@type': 'Organization', 'url': '/company/co0053177/'},
             {'@type': 'Organization', 'url': '/company/co0002254/'},
             {'@type': 'Organization', 'url': '/company/co0445695/'},
             {'@type': 'Organization', 'url': '/company/co0130575/'},
             {'@type': 'Organization', 'url': '/company/co0130222/'},
             {'@type': 'Organization', 'url': '/company/co0066028/'}],
 'datePublished': '2009-01-02',
 'description': 'The Reader is a movie starring Kate Winslet, Ralph Fiennes, '
                'and Bruno Ganz. Post-WWII Germany: Nearly a decade after his '
                'affair with an older woman came to a mysterious end, law '
                'student Michael Berg re-encounters his former lover as...',
 'director': {'@type': 'Person',
              'name': 'Stephen Daldry',
              'url': '/name/nm0197636/'},
 'duration': 'PT2H4M',
 'genre': ['Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM0NDQxNjA0N15BMl5BanBnXkFtZTcwNDUwMzcwMg@@._V1_.jpg',
 'keywords': 'war crime,trial,secret,sex with a minor,nazi',
 'name': 'The Reader',
 'trailer': {'@type': 'VideoObject',
             'description': 'Post-WWII Germany: Nearly a decade after his '
                            'affair with an older woman came to a mysterious '
                            'end, a law student re-encounters his former lover '
                            '(Winslet) as she testifies in a war-crimes trial.',
             'embedUrl': '/video/imdb/vi1750597657',
             'name': 'The Reader: Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTAxODY1Mzc4MzdeQTJeQWpwZ15BbWU4MDY2NTMxMzMx._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTAxODY1Mzc4MzdeQTJeQWpwZ15BbWU4MDY2NTMxMzMx._V1_.jpg',
             'uploadDate': '2008-11-06T10:49:07Z'},
 'url': '/title/tt0976051/'}