{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/American-Beauty',
 'EntryURL': 'https://www.imdb.com/title/tt0169547',
 'Entry_json': 'Favorites/Movies/snapshot/American-Beauty/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/American-Beauty/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/American-Beauty/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kevin Spacey',
            'url': '/name/nm0000228/'},
           {'@type': 'Person',
            'name': 'Annette Bening',
            'url': '/name/nm0000906/'},
           {'@type': 'Person',
            'name': 'Thora Birch',
            'url': '/name/nm0000301/'},
           {'@type': 'Person',
            'name': 'Wes Bentley',
            'url': '/name/nm0004747/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1045723,
                      'ratingValue': '8.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alan Ball',
              'url': '/name/nm0050332/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0021095/'}],
 'datePublished': '1999-10-01',
 'description': 'American Beauty is a movie starring Kevin Spacey, Annette '
                'Bening, and Thora Birch. A sexually frustrated suburban '
                'father has a mid-life crisis after becoming infatuated with '
                "his daughter's best friend.",
 'director': [{'@type': 'Person',
               'name': 'Sam Mendes',
               'url': '/name/nm0005222/'}],
 'duration': 'PT2H2M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BNTBmZWJkNjctNDhiNC00MGE2LWEwOTctZTk5OGVhMWMyNmVhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'adulterous wife,cheating wife,midlife crisis,unfaithful '
             'wife,virginity',
 'name': 'American Beauty',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Lester Burnham, a depressed suburban father in a '
                             'mid-life crisis, decides to turn his hectic life '
                             'around after developing an infatuation for his '
                             "daughter's attractive friend.",
              'embedUrl': '/video/imdb/vi788506137',
              'name': 'Theatrical Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTU5NDcyNTgzNl5BMl5BanBnXkFtZTgwNTMwNzU0NzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTU5NDcyNTgzNl5BMl5BanBnXkFtZTgwNTMwNzU0NzE@._V1_.jpg',
              'uploadDate': '2013-04-03T14:22:07Z'}],
 'url': '/title/tt0169547/'}