{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Swearnet-The-Movie',
 'EntryURL': 'https://www.imdb.com/title/tt2380564',
 'Entry_json': 'Favorites/Movies/snapshot/Swearnet-The-Movie/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Swearnet-The-Movie/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Swearnet-The-Movie/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Mike Smith', 'url': '/name/nm1034266/'},
           {'@type': 'Person', 'name': 'Robb Wells', 'url': '/name/nm1036211/'},
           {'@type': 'Person',
            'name': 'John Paul Tremblay',
            'url': '/name/nm1033215/'},
           {'@type': 'Person',
            'name': 'Patrick Roach',
            'url': '/name/nm1200571/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 2313,
                      'ratingValue': '5.9',
                      'worstRating': '1.0'}],
 'contentRating': 'NC-17',
 'creator': [{'@type': 'Person',
              'name': 'Mike Smith',
              'url': '/name/nm1034266/'},
             {'@type': 'Person',
              'name': 'John Paul Tremblay',
              'url': '/name/nm1033215/'},
             {'@type': 'Person',
              'name': 'Robb Wells',
              'url': '/name/nm1036211/'},
             {'@type': 'Organization', 'url': '/company/co0393265/'}],
 'datePublished': '2014-08-29',
 'description': 'Swearnet: The Movie is a movie starring Mike Smith, Robb '
                'Wells, and John Paul Tremblay. Fed up with being censored in '
                'their post-Trailer Park Boys lives, the out of work '
                "stars/world-renowned 'swearists', Mike Smith, Robb Wells "
                'and...',
 'director': [{'@type': 'Person',
               'name': 'Warren P. Sonoda',
               'url': '/name/nm1284464/'}],
 'duration': 'PT1H52M',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjM3MzU2NjM2OF5BMl5BanBnXkFtZTgwMTI2MzE1MjE@._V1_.jpg',
 'keywords': 'male frontal nudity,sponsorship,lawsuit,bleeped speech,male '
             'orgasm',
 'name': 'Swearnet: The Movie',
 'url': '/title/tt2380564/'}