{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Swearnet-The-Movie',
 'EntryURL': 'https://www.imdb.com/title/tt2380564',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Swearnet-The-Movie/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Swearnet-The-Movie/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Swearnet-The-Movie/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Swearnet-The-Movie/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Mike Smith', 'url': '/name/nm1034266/'},
           {'@type': 'Person', 'name': 'Robb Wells', 'url': '/name/nm1036211/'},
           {'@type': 'Person',
            'name': 'John Paul Tremblay',
            'url': '/name/nm1033215/'},
           {'@type': 'Person',
            'name': 'Patrick Roach',
            'url': '/name/nm1200571/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2313,
                     'ratingValue': '5.9',
                     'worstRating': '1.0'},
 'contentRating': 'NC-17',
 'creator': [{'@type': 'Person',
              'name': 'Mike Smith',
              'url': '/name/nm1034266/'},
             {'@type': 'Person',
              'name': 'John Paul Tremblay',
              'url': '/name/nm1033215/'},
             {'@type': 'Person',
              'name': 'Robb Wells',
              'url': '/name/nm1036211/'},
             {'@type': 'Organization', 'url': '/company/co0393265/'}],
 'datePublished': '2014-08-29',
 'description': 'Swearnet: The Movie is a movie starring Mike Smith, Robb '
                'Wells, and John Paul Tremblay. Fed up with being censored in '
                'their post-Trailer Park Boys lives, the out of work '
                "stars/world-renowned 'swearists', Mike Smith, Robb Wells "
                'and...',
 'director': {'@type': 'Person',
              'name': 'Warren P. Sonoda',
              'url': '/name/nm1284464/'},
 'duration': 'PT1H52M',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjM3MzU2NjM2OF5BMl5BanBnXkFtZTgwMTI2MzE1MjE@._V1_.jpg',
 'keywords': 'male frontal nudity,sponsorship,lawsuit,bleeped speech,male '
             'orgasm',
 'name': 'Swearnet: The Movie',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'brundais'},
            'dateCreated': '2018-05-12',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt2380564/'},
            'name': 'Why did they do this to themselves?',
            'reviewBody': 'This movie is horrible. I absolutely loved anything '
                          'TPB but this completely changed my opinion of the '
                          'actors/writers. What an embarrassment... Why would '
                          'they ever think this was a good idea?',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '2',
                             'worstRating': '1'}},
 'url': '/title/tt2380564/'}