<?php
$infoArray = array('Actors' => array('Alan Mandell',
            'Alberta Watson',
            'Andrea Martin',
            'Gene Pyrz',
            'John Cameron Mitchell',
            'Karen Hines',
            'Maggie Moore',
            'Maurice Dean Wint',
            'Michael Pitt',
            'Michael Stevens',
            'Miriam Shor',
            'Rob Campbell',
            "Rosie O'Donnell",
            'Sook-Yin Lee',
            'Taylor Abrahamse'),
 'Added' => '2013-02-23',
 'Countries' => array('USA'),
 'Description' => '\nHedwig and the Angry Inch: A transexual punk rock girl from East Berlin tours the US with her rock band as she tells her life story and follows the ex-boyfriend/bandmate who stole her songs. ',
 'Director' => array('John Cameron Mitchell'),
 'Genres' => array('Drama', 'Comedy', 'Music'),
 'IMDB' => 'http://www.imdb.com/title/tt0248845',
 'PrimeWire' => 'http://www.primewire.ag/watch-2818-Hedwig-and-the-Angry-Inch',
 'Ratings' => array('IMDB' => '7.8/10',
             'Metascore' => '85%',
             'PrimeWire' => '3.66/5',
             'RT' => '92%',
             'Votes' => '143'),
 'Released' => '2001-01-19',
 'Runtime' => '95 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2818_Hedwig_and_the_Angry_Inch_2001.jpg',
 'Title' => 'Hedwig-and-the-Angry-Inch');
?>