{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-03-21',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Gamechangers',
 'EntryURL': 'https://www.imdb.com/title/tt4590930',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Gamechangers/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Gamechangers/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Gamechangers/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Daniel Radcliffe',
            'url': '/name/nm0705356/'},
           {'@type': 'Person',
            'name': 'Bill Paxton',
            'url': '/name/nm0000200/'},
           {'@type': 'Person',
            'name': 'Joe Dempsie',
            'url': '/name/nm1478079/'},
           {'@type': 'Person', 'name': 'Ryan Gage', 'url': '/name/nm2187587/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2236,
                     'ratingValue': '6.3',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'James Wood',
              'url': '/name/nm1198822/'},
             {'@type': 'Organization', 'url': '/company/co0486601/'}],
 'datePublished': '2015-09-15',
 'description': 'The Gamechangers is a TV movie starring Daniel Radcliffe, '
                "Bill Paxton, and Joe Dempsie. The struggle of Houser's legal "
                'feud against American lawyer Jack Thompson, over the morality '
                'of the Grand Theft Auto video game series.',
 'director': {'@type': 'Person',
              'name': 'Owen Harris',
              'url': '/name/nm2787176/'},
 'duration': 'PT1H30M',
 'genre': ['Biography', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg5NDg5NjAxNV5BMl5BanBnXkFtZTgwNDM0MTg5NjE@._V1_.jpg',
 'keywords': 'docudrama',
 'name': 'The Gamechangers',
 'url': '/title/tt4590930/'}