{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-04-03',
 'EntryPath': 'Favorites/Movies/snapshot/Inside-The-Scientology-Center',
 'EntryURL': 'https://www.imdb.com/title/tt4967868',
 'Entry_json': 'Favorites/Movies/snapshot/Inside-The-Scientology-Center/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Inside-The-Scientology-Center/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Inside-The-Scientology-Center/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Milo Twomey',
            'url': '/name/nm0878653/'},
           {'@type': 'Person',
            'name': 'Sam Domingo',
            'url': '/name/nm7543556/'},
           {'@type': 'Person',
            'name': 'Linda Dubrow-Marshall',
            'url': '/name/nm7175833/'},
           {'@type': 'Person',
            'name': 'Rod Dubrow-Marshall',
            'url': '/name/nm7567633/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 11,
                      'ratingValue': '6.5',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0118163/'}],
 'datePublished': '2015-08-24',
 'director': [{'@type': 'Person',
               'name': 'Dan Murdoch',
               'url': '/name/nm3121969/'},
              {'@type': 'Person',
               'name': 'Mike Wafer',
               'url': '/name/nm2175786/'}],
 'duration': 'PT1H',
 'genre': 'Documentary',
 'keywords': "scientology,jehovah's witnesses,religion,cult,ex scientologist",
 'name': 'Inside Scientology... And Escaping the Witnesses',
 'url': '/title/tt4967868/'}