<?php
$infoArray = array('Actors' => array('Annie Corley',
            'Arron Shiver',
            'Benicio Del Toro',
            'Carlo Alban',
            'Catherine Dent',
            'Chance Romero',
            'Charlotte Gainsbourg',
            'Clea DuVall',
            'Danny Huston',
            "Denis O'Hare",
            'Eddie Marsan',
            'Jennifer Pfalzgraff',
            'John Rubinstein',
            'Kevin Chapman',
            'Lew Temple',
            'Melissa Leo',
            'Naomi Watts',
            'Nick Nichols',
            'Pamela Blair',
            'Paul Calderon',
            'Roberto Medina',
            'Sean Penn',
            'Stephen Bridgewater',
            'Tom Irwin',
            'Tony Vaughn'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\n21 Grams: A freak accident brings together a critically ill mathematician (Penn), a grieving mother (Watts) and a born-again ex-con (Del Toro). ',
 'Director' => array('Alejandro Gonz&#xE1;lez I&#xF1;&#xE1;rritu'),
 'Genres' => array('Drama', 'Thriller', 'Crime'),
 'IMDB' => 'http://www.imdb.com/title/tt0315733',
 'PrimeWire' => 'http://www.primewire.ag/watch-4330-21-Grams',
 'Ratings' => array('IMDB' => '7.7/10',
             'Metascore' => '70%',
             'PrimeWire' => '3.74/5',
             'RT' => '80%',
             'Votes' => '277'),
 'Released' => '2003-09-05',
 'Runtime' => '124 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/4330_21_Grams_2003.jpg',
 'Title' => '21-Grams');
?>