{'Actors': [],
 'Added': '2013-06-15',
 'Countries': ['Denmark', 'Finland', 'Sweden', 'Italy'],
 'Description': '\nInto Eternity: Finland has decided to bury its nuclear waste several kilometres underground in a facility called Omika (hiding place). This film discusses why this is being done and what the ramifications of this are both to Finland and the rest of the World. It in ',
 'Director': ['Michael Madsen'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1194612',
 'PrimeWire': 'http://www.primewire.ag/watch-1864173-Into-Eternity',
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': '68%',
             'PrimeWire': '3.80/5',
             'RT': '100%',
             'Votes': '15'},
 'Released': '2010-01-06',
 'Runtime': '75 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1864173_Into_Eternity_2010.jpg',
 'Title': 'Into-Eternity'}