{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Elder-Scrolls-Iv-Oblivion',
 'EntryURL': 'https://rawg.io/games/the-elder-scrolls-iv-oblivion',
 'Entry_json': 'Favorites/Games/snapshot/The-Elder-Scrolls-Iv-Oblivion/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Elder-Scrolls-Iv-Oblivion/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Elder-Scrolls-Iv-Oblivion/thumb.jpg',
 'added': 1830,
 'background_image': 'https://media.rawg.io/media/games/615/61503312a95d451198d80d9bae275f79.jpg',
 'developers': ['Bethesda Game Studios', 'Bethesda Softworks'],
 'genres': ['RPG'],
 'name': 'The Elder Scrolls IV: Oblivion',
 'platforms': ['PC', 'PlayStation 3', 'Xbox 360'],
 'publishers': ['2K Games', 'Bethesda Softworks'],
 'released': '2006-03-20',
 'slug': 'the-elder-scrolls-iv-oblivion'}