{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-10-02',
 'EntryPath': 'Favorites/TV/snapshot/Key-and-Peele',
 'EntryURL': 'https://www.imdb.com/title/tt1981558',
 'Entry_json': 'Favorites/TV/snapshot/Key-and-Peele/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Key-and-Peele/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Key-and-Peele/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Keegan-Michael Key',
            'url': '/name/nm1221047/'},
           {'@type': 'Person',
            'name': 'Jordan Peele',
            'url': '/name/nm1443502/'},
           {'@type': 'Person',
            'name': 'Metta World Peace',
            'url': '/name/nm1927491/'},
           {'@type': 'Person',
            'name': 'Matt Wheeler',
            'url': '/name/nm0923916/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 16065,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Keegan-Michael Key',
              'url': '/name/nm1221047/'},
             {'@type': 'Person',
              'name': 'Jordan Peele',
              'url': '/name/nm1443502/'},
             {'@type': 'Organization', 'url': '/company/co0369433/'},
             {'@type': 'Organization', 'url': '/company/co0369235/'},
             {'@type': 'Organization', 'url': '/company/co0369202/'}],
 'datePublished': '2012-01-31',
 'description': 'Key and Peele is a TV series starring Keegan-Michael Key, '
                'Jordan Peele, and Metta World Peace. Project sees '
                'Keegan-Michael Key and Jordan Peele in front of a live studio '
                'audience bantering about a topic weaved between filmed '
                'shorts...',
 'genre': ['Action', 'Adventure', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjk0ZGI4MWMtNTI3OC00ZmJjLWI1ZmQtODY3ZmMzODBmM2U4XkEyXkFqcGdeQXVyMzU3MTc5OTE@._V1_.jpg',
 'keywords': 'sketch comedy,written by jordan peele,written by keegan michael '
             'key,2010s,comedy central',
 'name': 'Key and Peele',
 'trailer': {'@type': 'VideoObject',
             'description': 'Key & Peele',
             'embedUrl': '/video/imdb/vi3583687961',
             'name': 'Key & Peele',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDEzMWRjYzEtNTZlZC00ZmE1LWJmYjktMDVhNzBmMjZkMzYwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDEzMWRjYzEtNTZlZC00ZmE1LWJmYjktMDVhNzBmMjZkMzYwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-03-17T14:10:46Z'},
 'url': '/title/tt1981558/'}