{'Actors': ['Keegan Michael Key&tv'],
 'Added': '2014-10-02',
 'Countries': ['USA'],
 'Description': '\n'
                'Key and Peele: Project sees Keegan-Michael Key and Jordan '
                'Peele in front of a live studio audience bantering about a '
                'topic weaved between filmed shorts and sketches. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Key-and-Peele',
 'EntryURL': 'http://www.imdb.com/title/tt1981558',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Key-and-Peele/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Key-and-Peele/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Key-and-Peele/info.py',
 'Genres': ['Comedy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt1981558',
 'PrimeWire': 'http://www.primewire.ag/tv-2732182-Key-and-Peele',
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.33/5',
             'RT': 'N/A',
             'Votes': '543'},
 'Released': '2012-01-31',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2732182_Key_and_Peele_2012.jpg',
 'Title': 'Key-and-Peele'}