{'Actors': ['Amy Adams',
            'Forest Whitaker',
            'Jeremy Renner',
            'Michael Stuhlbarg'],
 'Added': '2017-02-20',
 'Countries': ['USA'],
 'Description': '\nArrival: When 12 mysterious spacecraft appear around the world, linguistics professor Louise Banks is tasked with interpreting the language of the apparent alien visitors. ',
 'Director': ['Denis Villeneuve'],
 'Genres': ['Drama', 'Mystery', 'Sci-Fi'],
 'IMDB': 'http://www.imdb.com/title/tt2543164',
 'PrimeWire': 'http://www.primewire.ag/watch-2788371-Arrival',
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': '81%',
             'PrimeWire': '3.91/5',
             'RT': '94%',
             'Votes': '1229'},
 'Released': '2016-11-11',
 'Runtime': '116 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2788371_Arrival_2016.jpg',
 'Title': 'Arrival'}