{'Actors': ['Amy Adams',
            'Forest Whitaker',
            'Jeremy Renner',
            'Michael Stuhlbarg'],
 'Added': '2017-02-20',
 'Countries': ['USA'],
 'Description': '\n'
                'Arrival: When 12 mysterious spacecraft appear around the '
                'world, linguistics professor Louise Banks is tasked with '
                'interpreting the language of the apparent alien visitors. ',
 'Director': ['Denis Villeneuve'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Arrival',
 'EntryURL': 'https://www.imdb.com/title/tt2543164',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Arrival/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Arrival/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Arrival/info.py',
 'Genres': ['Drama', 'Mystery', 'Sci-Fi'],
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': '81%',
             'PrimeWire': '3.91/5',
             'RT': '94%',
             'Votes': '1229'},
 'Released': '2016-11-11',
 'Runtime': '116 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2788371_Arrival_2016.jpg',
 'Title': 'Arrival'}