{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2017-02-20',
 'EntryPath': 'Favorites/Movies/snapshot/Arrival',
 'EntryURL': 'https://www.imdb.com/title/tt2543164',
 'Entry_json': 'Favorites/Movies/snapshot/Arrival/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Arrival/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Arrival/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Amy Adams', 'url': '/name/nm0010736/'},
           {'@type': 'Person',
            'name': 'Jeremy Renner',
            'url': '/name/nm0719637/'},
           {'@type': 'Person',
            'name': 'Forest Whitaker',
            'url': '/name/nm0001845/'},
           {'@type': 'Person',
            'name': 'Michael Stuhlbarg',
            'url': '/name/nm0836121/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 565893,
                     'ratingValue': '7.9',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Eric Heisserer',
              'url': '/name/nm2104063/'},
             {'@type': 'Person',
              'name': 'Ted Chiang',
              'url': '/name/nm5384213/'},
             {'@type': 'Organization', 'url': '/company/co0296971/'},
             {'@type': 'Organization', 'url': '/company/co0251858/'},
             {'@type': 'Organization', 'url': '/company/co0158853/'},
             {'@type': 'Organization', 'url': '/company/co0616808/'}],
 'datePublished': '2016-11-10',
 'description': 'Arrival is a movie starring Amy Adams, Jeremy Renner, and '
                'Forest Whitaker. A linguist works with the military to '
                'communicate with alien lifeforms after twelve mysterious '
                'spacecraft appear around the world.',
 'director': {'@type': 'Person',
              'name': 'Denis Villeneuve',
              'url': '/name/nm0898288/'},
 'duration': 'PT1H56M',
 'genre': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_.jpg',
 'keywords': 'alien contact,linguistics,nonlinear timeline,linguist,based on '
             'short story',
 'name': 'Arrival',
 'trailer': {'@type': 'VideoObject',
             'description': 'A linguist is recruited by the military to assist '
                            'in translating alien communications.',
             'embedUrl': '/video/imdb/vi4225807897',
             'name': 'Final Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzA4Mzg5OTY5Nl5BMl5BanBnXkFtZTgwMDk4ODg0MDI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzA4Mzg5OTY5Nl5BMl5BanBnXkFtZTgwMDk4ODg0MDI@._V1_.jpg',
             'uploadDate': '2016-11-01T22:34:15Z'},
 'url': '/title/tt2543164/'}