{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-24',
 'EntryPath': 'Favorites/Movies/snapshot/Citizenfour',
 'EntryURL': 'https://www.imdb.com/title/tt4044364',
 'Entry_json': 'Favorites/Movies/snapshot/Citizenfour/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Citizenfour/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Citizenfour/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Edward Snowden',
            'url': '/name/nm5722984/'},
           {'@type': 'Person',
            'name': 'Glenn Greenwald',
            'url': '/name/nm3390925/'},
           {'@type': 'Person',
            'name': 'William Binney',
            'url': '/name/nm5015568/'},
           {'@type': 'Person',
            'name': 'Jacob Appelbaum',
            'url': '/name/nm3335834/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 51138,
                      'ratingValue': '8.0',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Organization', 'url': '/company/co0245372/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'},
             {'@type': 'Organization', 'url': '/company/co0139821/'}],
 'datePublished': '2014-10-17',
 'description': 'Citizenfour is a movie starring Edward Snowden, Glenn '
                'Greenwald, and William Binney. A documentarian and a reporter '
                'travel to Hong Kong for the first of many meetings with '
                'Edward Snowden.',
 'director': [{'@type': 'Person',
               'name': 'Laura Poitras',
               'url': '/name/nm0688636/'}],
 'duration': 'PT1H54M',
 'genre': ['Documentary', 'Biography', 'News', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTc0MTM0MTA5MF5BMl5BanBnXkFtZTgwNzEwODEwMzE@._V1_.jpg',
 'keywords': 'mass surveillance,corrupt government,government '
             'surveillance,nsa,edward snowden',
 'name': 'Citizenfour',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A documentarian and a reporter travel to Hong '
                             'Kong for the first of many meetings with Edward '
                             'Snowden.',
              'embedUrl': '/video/imdb/vi2548870937',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTY3NzU1MTY2MV5BMl5BanBnXkFtZTgwNTg1MzU5MjE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTY3NzU1MTY2MV5BMl5BanBnXkFtZTgwNTg1MzU5MjE@._V1_.jpg',
              'uploadDate': '2014-10-12T14:33:20Z'}],
 'url': '/title/tt4044364/'}