{'Actors': [],
 'Added': '2015-08-24',
 'Countries': ['Germany', 'USA'],
 'Description': '\n'
                'Citizenfour: A documentarian and a reporter travel to Hong '
                'Kong for the first of many meetings with Edward Snowden. ',
 'Director': ['Laura Poitras'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Citizenfour',
 'EntryURL': 'https://www.imdb.com/title/tt4044364',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Citizenfour/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Citizenfour/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Citizenfour/info.py',
 'Genres': ['Documentary'],
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': '88%',
             'PrimeWire': '4.39/5',
             'RT': '98%',
             'Votes': '357'},
 'Released': '2014-11-06',
 'Runtime': '114 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2756961_Citizenfour_2014.jpg',
 'Title': 'Citizenfour'}