{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-06-29',
 'EntryPath': 'Favorites/TV/snapshot/Vanguard',
 'EntryURL': 'https://www.imdb.com/title/tt2016109',
 'Entry_json': 'Favorites/TV/snapshot/Vanguard/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Vanguard/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Vanguard/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Mariana van Zeller',
            'url': '/name/nm2447662/'},
           {'@type': 'Person',
            'name': 'Christof Putzel',
            'url': '/name/nm1779890/'},
           {'@type': 'Person',
            'name': 'Adam Yamaguchi',
            'url': '/name/nm4545017/'},
           {'@type': 'Person',
            'name': 'Laura Ling',
            'url': '/name/nm2053030/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 51,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0160937/'}],
 'datePublished': '2006-04-19',
 'description': 'Vanguard is a TV series starring Mariana van Zeller, Christof '
                'Putzel, and Adam Yamaguchi. TV documentary about "stand your '
                'ground" laws in the US.',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY4NzE0MzczMF5BMl5BanBnXkFtZTcwMjg1NzM2Nw@@._V1_.jpg',
 'keywords': 'law',
 'name': 'Vanguard',
 'url': '/title/tt2016109/'}