{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Southland-Tales',
 'EntryURL': 'https://www.imdb.com/title/tt0405336',
 'Entry_json': 'Favorites/Movies/snapshot/Southland-Tales/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Southland-Tales/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Southland-Tales/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Dwayne Johnson',
            'url': '/name/nm0425005/'},
           {'@type': 'Person',
            'name': 'Sarah Michelle Gellar',
            'url': '/name/nm0001264/'},
           {'@type': 'Person',
            'name': 'Seann William Scott',
            'url': '/name/nm0005405/'},
           {'@type': 'Person',
            'name': 'Carlos Amezcua',
            'url': '/name/nm0024782/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 36512,
                      'ratingValue': '5.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Richard Kelly',
              'url': '/name/nm0446819/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0099690/'},
             {'@type': 'Organization', 'url': '/company/co0118694/'},
             {'@type': 'Organization', 'url': '/company/co0123050/'},
             {'@type': 'Organization', 'url': '/company/co0182444/'},
             {'@type': 'Organization', 'url': '/company/co0123049/'},
             {'@type': 'Organization', 'url': '/company/co0146944/'},
             {'@type': 'Organization', 'url': '/company/co0017834/'},
             {'@type': 'Organization', 'url': '/company/co0119195/'},
             {'@type': 'Organization', 'url': '/company/co0024845/'}],
 'datePublished': '2007-12-07',
 'description': 'Southland Tales is a movie starring Dwayne Johnson, Sarah '
                'Michelle Gellar, and Seann William Scott. During a three-day '
                'heat wave just before a huge 4th of July celebration, an '
                'action star stricken with amnesia meets up with a porn...',
 'director': [{'@type': 'Person',
               'name': 'Richard Kelly',
               'url': '/name/nm0446819/'}],
 'duration': 'PT2H25M',
 'genre': ['Comedy', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDk0ZDY4NTItOTY3Zi00MjU1LTkzNDgtZjg1MDA3Nzc4YWRiXkEyXkFqcGdeQXVyMjQwMjk0NjI@._V1_.jpg',
 'keywords': 'duplicate,anarchy,doppelganger,surveillance,tragic event',
 'name': 'Southland Tales',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Samuel Goldwyn',
              'embedUrl': '/video/imdb/vi3867410713',
              'name': 'Southland Tales',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2Y3MDExMjgtOWIzYy00MzgxLThjODAtNmVmNDhmY2M1Nzg3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2Y3MDExMjgtOWIzYy00MzgxLThjODAtNmVmNDhmY2M1Nzg3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T15:56:07Z'}],
 'url': '/title/tt0405336/'}