{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Fallout-3',
 'EntryURL': 'https://rawg.io/games/fallout-3',
 'Entry_json': 'Favorites/Games/snapshot/Fallout-3/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Fallout-3/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Fallout-3/thumb.jpg',
 'added': 3727,
 'background_image': 'https://media.rawg.io/media/games/5a4/5a4e70bb8a862829dbaa398aa5f66afc.jpg',
 'developers': ['Bethesda Game Studios', 'Bethesda Softworks'],
 'genres': ['Shooter', 'RPG'],
 'name': 'Fallout 3',
 'platforms': ['PC', 'Xbox 360', 'PlayStation 3'],
 'publishers': ['Bethesda Softworks'],
 'released': '2008-10-28',
 'slug': 'fallout-3'}