{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-10-29',
 'EntryPath': 'Favorites/Movies/snapshot/Piper',
 'EntryURL': 'https://www.imdb.com/title/tt5613056',
 'Entry_json': 'Favorites/Movies/snapshot/Piper/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Piper/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Piper/thumb.jpg',
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 24577,
                      'ratingValue': '8.4',
                      'worstRating': '1.0'}],
 'contentRating': 'G',
 'creator': [{'@type': 'Person',
              'name': 'Alan Barillaro',
              'url': '/name/nm0054659/'},
             {'@type': 'Organization', 'url': '/company/co0017902/'}],
 'datePublished': '2016-06-16',
 'director': [{'@type': 'Person',
               'name': 'Alan Barillaro',
               'url': '/name/nm0054659/'}],
 'duration': 'PT6M',
 'genre': ['Animation', 'Short', 'Family'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzhhMDkwNWItMmRlMS00ODg1LTkzMzAtZGM3NTAwNzViZGU5XkEyXkFqcGdeQXVyOTI3MDg0NzA@._V1_.jpg',
 'keywords': 'computer animation,no dialogue,baby bird,sand,water',
 'name': 'Piper',
 'url': '/title/tt5613056/'}