{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-06-30',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Caprica',
 'EntryURL': 'https://www.imdb.com/title/tt0799862',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Caprica/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Caprica/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Caprica/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Eric Stoltz',
            'url': '/name/nm0000655/'},
           {'@type': 'Person',
            'name': 'Esai Morales',
            'url': '/name/nm0005246/'},
           {'@type': 'Person',
            'name': 'Paula Malcomson',
            'url': '/name/nm0539155/'},
           {'@type': 'Person',
            'name': 'Alessandra Torresani',
            'url': '/name/nm0003779/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 23382,
                     'ratingValue': '7.1',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Remi Aubuchon',
              'url': '/name/nm0041469/'},
             {'@type': 'Person',
              'name': 'Ronald D. Moore',
              'url': '/name/nm0601822/'},
             {'@type': 'Organization', 'url': '/company/co0176813/'},
             {'@type': 'Organization', 'url': '/company/co0196576/'}],
 'datePublished': '2010-01-22',
 'description': 'Caprica is a TV series starring Eric Stoltz, Esai Morales, '
                'and Paula Malcomson. Two families, the Graystones and the '
                'Adamas, live together on a peaceful planet known as Caprica, '
                'where a startling breakthrough in artificial...',
 'genre': ['Action', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjAxMjM4NDQyMV5BMl5BanBnXkFtZTcwMjEyNDYzMg@@._V1_.jpg',
 'keywords': 'planetary romance,shared universe,outer space,artificial '
             'intelligence,tattoo',
 'name': 'Caprica',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Caprica: Season 1.0',
             'embedUrl': '/video/imdb/vi2855180569',
             'name': 'Caprica: Season 1.0',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTc0MGU3ZWEtZmViYy00ZjM5LWFmM2EtYmQxYzc4M2IyYTIyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTc0MGU3ZWEtZmViYy00ZjM5LWFmM2EtYmQxYzc4M2IyYTIyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2010-10-15T03:09:40Z'},
 'url': '/title/tt0799862/'}