{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-10-06',
 'EntryPath': 'Favorites/Movies/snapshot/The-Fear-of-13',
 'EntryURL': 'https://www.imdb.com/title/tt5083702',
 'Entry_json': 'Favorites/Movies/snapshot/The-Fear-of-13/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Fear-of-13/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Fear-of-13/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Herbert A. Fuchs',
            'url': '/name/nm6443793/'},
           {'@type': 'Person',
            'name': 'Sammy Silverwatch',
            'url': '/name/nm5815854/'},
           {'@type': 'Person',
            'name': 'Nick Yarris',
            'url': '/name/nm7671113/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 6503,
                     'ratingValue': '7.7',
                     'worstRating': '1.0'},
 'datePublished': '2015-08-04',
 'description': 'The Fear of 13 is a movie starring Herbert A. Fuchs, Sammy '
                'Silverwatch, and Nick Yarris. A convicted murderer who has '
                'spent 23 years on Death Row tells his story.',
 'director': {'@type': 'Person',
              'name': 'David Sington',
              'url': '/name/nm2270163/'},
 'duration': 'PT1H36M',
 'genre': ['Documentary', 'Crime', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ4Mzk3NDE0MF5BMl5BanBnXkFtZTgwMDc5ODc2NzE@._V1_.jpg',
 'keywords': 'death row,reenactment,legal system,prison',
 'name': 'The Fear of 13',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for The Fear of 13',
             'embedUrl': '/video/imdb/vi2836706585',
             'name': 'The Fear of 13',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTc0MmJkMTgtZTMwNy00NzcyLThlZDAtZWVmODZhYThiNTExXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTc0MmJkMTgtZTMwNy00NzcyLThlZDAtZWVmODZhYThiNTExXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2016-03-06T08:08:26Z'},
 'url': '/title/tt5083702/'}