{'Actors': [],
 'Added': '2016-10-06',
 'Countries': ['UK'],
 'Description': '\n'
                'The Fear of 13: A convicted murderer who has spent 23 years '
                'on Death Row tells his story. ',
 'Director': ['David Sington'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fear-of-13',
 'EntryURL': 'https://www.imdb.com/title/tt5083702',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fear-of-13/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fear-of-13/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fear-of-13/info.py',
 'Genres': ['Documentary'],
 'Ratings': {'IMDB': '8.1/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.87/5',
             'RT': '92%',
             'Votes': '127'},
 'Released': '2015-11-15',
 'Runtime': '96 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2773721_The_Fear_of_13_2015.jpg',
 'Title': 'The-Fear-of-13'}