{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Oddworld-Abes-Oddysee',
 'EntryURL': 'https://rawg.io/games/oddworld-abes-oddysee',
 'Entry_json': 'Favorites/Games/snapshot/Oddworld-Abes-Oddysee/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Oddworld-Abes-Oddysee/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Oddworld-Abes-Oddysee/thumb.jpg',
 'added': 3626,
 'background_image': 'https://media.rawg.io/media/screenshots/124/124dd314f9effb6cc153589db7975e9a.jpg',
 'developers': ['Oddworld Inhabitants',
                'Sony Interactive Entertainment',
                'Saffire Corporation',
                'Digital Dialect (PC)'],
 'genres': ['Action', 'Platformer'],
 'name': "Oddworld: Abe's Oddysee",
 'platforms': ['PC',
               'PlayStation',
               'Android',
               'Game Boy',
               'PSP',
               'PS Vita',
               'PlayStation 3'],
 'publishers': ['Oddworld Inhabitants',
                'GT Interactive Software',
                'SoftBank',
                'PSN',
                'SCE'],
 'released': '1997-08-31',
 'slug': 'oddworld-abes-oddysee'}