{'Actors': ['Adrian Lester',
            'Alexander Siddig',
            'Bob Hoskins',
            'Cal Macaninch',
            'Cecil Carter',
            'Chris Robson',
            'Chris Wilson',
            'Craig Conway',
            'Darren Morfitt',
            "David O'Hara",
            'DTeflon',
            'George Bailey',
            'Jeremy Crutchley',
            'John Carson',
            'Malcolm McDowell',
            'Martin Ball',
            'Martin Compston',
            'MyAnna Buring',
            'Nora-Jane Noone',
            'Rhona Mitra',
            'Rick Warden',
            'Sean Pertwee',
            'Stephen Hughes',
            'Stephen Modell',
            'Susan Danford'],
 'Added': '2013-02-23',
 'Countries': ['UK', 'USA', 'South Africa', 'Germany'],
 'Description': '\n'
                'Doomsday: A futuristic action thriller where a team of people '
                'work to prevent a disaster threatening the future of the '
                'human race. ',
 'Director': ['Neil Marshall'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Doomsday',
 'EntryURL': 'http://www.imdb.com/title/tt0483607',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Doomsday/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Doomsday/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Doomsday/info.py',
 'Genres': ['Action', 'Sci-Fi', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt0483607',
 'PrimeWire': 'http://www.primewire.ag/watch-239-Doomsday',
 'Ratings': {'IMDB': '6.0/10',
             'Metascore': '51%',
             'PrimeWire': '3.77/5',
             'RT': '49%',
             'Votes': '519'},
 'Released': '2008-03-14',
 'Runtime': '105 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/239_Doomsday_2008.jpg',
 'Title': 'Doomsday'}