{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Doomsday',
 'EntryURL': 'https://www.imdb.com/title/tt0483607',
 'Entry_json': 'Favorites/Movies/snapshot/Doomsday/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Doomsday/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Doomsday/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Rhona Mitra',
            'url': '/name/nm0593961/'},
           {'@type': 'Person',
            'name': 'Bob Hoskins',
            'url': '/name/nm0001364/'},
           {'@type': 'Person',
            'name': 'Alexander Siddig',
            'url': '/name/nm0796502/'},
           {'@type': 'Person',
            'name': 'Caryn Peterson',
            'url': '/name/nm2944939/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 71283,
                      'ratingValue': '6.0',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Neil Marshall',
              'url': '/name/nm0551076/'},
             {'@type': 'Organization', 'url': '/company/co0123433/'},
             {'@type': 'Organization', 'url': '/company/co0059753/'},
             {'@type': 'Organization', 'url': '/company/co0004724/'},
             {'@type': 'Organization', 'url': '/company/co0133024/'},
             {'@type': 'Organization', 'url': '/company/co0044704/'},
             {'@type': 'Organization', 'url': '/company/co0239956/'}],
 'datePublished': '2008-03-14',
 'description': 'Doomsday is a movie starring Rhona Mitra, Bob Hoskins, and '
                'Alexander Siddig. A futuristic action thriller where a team '
                'of people work to prevent a disaster threatening the future '
                'of the human race.',
 'director': [{'@type': 'Person',
               'name': 'Neil Marshall',
               'url': '/name/nm0551076/'}],
 'duration': 'PT1H45M',
 'genre': ['Action', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTUwODU2NzE2OF5BMl5BanBnXkFtZTcwMTAwMDA2MQ@@._V1_.jpg',
 'keywords': 'quarantine,virus,wall,britain,contagion',
 'name': 'Doomsday',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Doomsday Trailer',
              'embedUrl': '/video/imdb/vi1269956889',
              'name': 'Doomsday',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjQ1NzM0NjkxOF5BMl5BanBnXkFtZTgwNDYyNzkxMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjQ1NzM0NjkxOF5BMl5BanBnXkFtZTgwNDYyNzkxMzE@._V1_.jpg',
              'uploadDate': '2008-01-17T21:26:39Z'}],
 'url': '/title/tt0483607/'}