<?php
$infoArray = array('Actors' => array('Daniel Caltagirone',
            'Guillaume Canet',
            'Hel&#xE8;ne de Fougerolles',
            'Josh Cole',
            'Lars Arentz-Hansen',
            'Leonardo DiCaprio',
            'Lidija Zovkic',
            'Michael Thorpe',
            'Paterson Joseph',
            'Peter Gevisser',
            'Peter Youngblood Hills',
            'Robert Carlyle',
            'Saskia Mulder',
            'Stacy Hart',
            'Staffan Kihlbom',
            'Tilda Swinton',
            'Victoria Smurfit',
            'Virginie Ledoyen'),
 'Added' => '2013-02-19',
 'Countries' => array('USA', 'UK'),
 'Description' => '\nThe Beach: Twenty-something Richard travels to Thailand and finds himself in possession of a strange map. Rumours state that it leads to a solitary beach paradise, a tropical bliss - excited and intrigued, he sets out to find it. ',
 'Director' => array('Danny Boyle'),
 'Genres' => array('Drama', 'Thriller', 'Adventure'),
 'IMDB' => 'http://www.imdb.com/title/tt0163978',
 'PrimeWire' => 'http://www.primewire.ag/watch-2118-The-Beach',
 'Ratings' => array('IMDB' => '6.6/10',
             'Metascore' => '43%',
             'PrimeWire' => '3.86/5',
             'RT' => '19%',
             'Votes' => '659'),
 'Released' => '2000-02-02',
 'Runtime' => '119 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2118_The_Beach_2000.jpg',
 'Title' => 'The-Beach');
?>