{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Velvet-Buzzsaw',
 'EntryURL': 'https://www.imdb.com/title/tt7043012',
 'Entry_json': 'Favorites/Movies/snapshot/Velvet-Buzzsaw/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Velvet-Buzzsaw/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Velvet-Buzzsaw/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jake Gyllenhaal',
            'url': '/name/nm0350453/'},
           {'@type': 'Person', 'name': 'Rene Russo', 'url': '/name/nm0000623/'},
           {'@type': 'Person',
            'name': 'Zawe Ashton',
            'url': '/name/nm1534698/'},
           {'@type': 'Person',
            'name': 'Tom Sturridge',
            'url': '/name/nm0836432/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 50215,
                      'ratingValue': '5.7',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Dan Gilroy',
              'url': '/name/nm0319659/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2019-02-01',
 'description': 'Velvet Buzzsaw is a movie starring Jake Gyllenhaal, Rene '
                'Russo, and Zawe Ashton. A satire set in the contemporary art '
                'world scene of Los Angeles, where big money artists and '
                'mega-collectors pay a high price when art collides with...',
 'director': [{'@type': 'Person',
               'name': 'Dan Gilroy',
               'url': '/name/nm0319659/'}],
 'duration': 'PT1H53M',
 'genre': ['Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjExMDQ1NjMzOV5BMl5BanBnXkFtZTgwMjkxMzMyNzM@._V1_.jpg',
 'keywords': 'artist,satire,gay man has sex with a woman,supernatural '
             'horror,dark satire',
 'name': 'Velvet Buzzsaw',
 'trailer': [{'@type': 'VideoObject',
              'description': 'After a series of paintings by an unknown artist '
                             'are discovered, a supernatural force enacts '
                             'revenge on those who have allowed their greed to '
                             'get in the way of art.',
              'embedUrl': '/video/imdb/vi487701017',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMmYwZWI2YjItYmEwMC00NzBlLWE2ZTQtODgwMGVhNWZhODM1XkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMmYwZWI2YjItYmEwMC00NzBlLWE2ZTQtODgwMGVhNWZhODM1XkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
              'uploadDate': '2019-01-10T14:48:31Z'}],
 'url': '/title/tt7043012/'}