{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-07-10',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland',
 'EntryURL': 'https://www.imdb.com/title/tt1981140',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Vanessa Kirby',
            'url': '/name/nm3948952/'},
           {'@type': 'Person', 'name': 'Iwan Rheon', 'url': '/name/nm3701064/'},
           {'@type': 'Person',
            'name': 'Matthew Lewis',
            'url': '/name/nm0507535/'},
           {'@type': 'Person',
            'name': 'Luke Treadaway',
            'url': '/name/nm2008435/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 3465,
                     'ratingValue': '6.5',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Rowan Athale',
              'url': '/name/nm1424282/'},
             {'@type': 'Organization', 'url': '/company/co0377031/'},
             {'@type': 'Organization', 'url': '/company/co0289424/'},
             {'@type': 'Organization', 'url': '/company/co0121295/'},
             {'@type': 'Organization', 'url': '/company/co0353402/'},
             {'@type': 'Organization', 'url': '/company/co0362154/'},
             {'@type': 'Organization', 'url': '/company/co0020757/'}],
 'datePublished': '2013-07-26',
 'description': 'The Rise is a movie starring Vanessa Kirby, Iwan Rheon, and '
                'Matthew Lewis. A young man recently released from prison '
                'recruits his three best friends to rob the local drug kingpin '
                'who is responsible for his incarceration. Can he get...',
 'director': {'@type': 'Person',
              'name': 'Rowan Athale',
              'url': '/name/nm1424282/'},
 'duration': 'PT1H48M',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE2ODYyNDM5OV5BMl5BanBnXkFtZTcwNDMyODk3OQ@@._V1_.jpg',
 'keywords': 'revenge,release from prison,planning robbery,welding,police '
             'interrogation',
 'name': 'The Rise',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'alihiltontk'},
            'dateCreated': '2018-02-28',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt1981140/'},
            'name': 'Dont miss out',
            'reviewBody': 'I missed this film and caught up with it on '
                          'Netflix..  What a decent film this is...Lots of '
                          'twists and turns bit hard to follow but it all '
                          'comes out at the end... Bit like Pulp Fiction the '
                          'plot line..  Well worth watching and you would '
                          'watch it again.. Its on my ship wreck list',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '10',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'A young Englishman recently released from prison '
                            'recruits his three best friends and to rob the '
                            'local drug kingpin who is responsible for his '
                            'incarceration. Can he get revenge and win back '
                            'his fed-up girlfriend?',
             'embedUrl': '/video/imdb/vi847620377',
             'name': 'Theatrical Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTUxMDkwNTM0M15BMl5BanBnXkFtZTgwODU4NzAyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTUxMDkwNTM0M15BMl5BanBnXkFtZTgwODU4NzAyMzE@._V1_.jpg',
             'uploadDate': '2013-07-11T10:07:29Z'},
 'url': '/title/tt1981140/'}