{'Actors': ['Andy Calderwood',
            'Brad Moore',
            'David OConnor',
            'Gerard Kearns',
            'Grant Crookes',
            'Iwan Rheon',
            'Liam Tulley',
            'Lucy Fenton',
            'Luke Treadaway',
            'Matthew Lewis',
            'Neil Maskell',
            'Paul Clayton',
            'Peter Foster',
            'Timothy Spall',
            'Vanessa Kirby'],
 'Added': '2013-07-10',
 'Countries': ['UK'],
 'Description': '\n'
                'Wasteland: A young Englishman recently released from prison '
                'recruits his three best friends and to rob the local drug '
                'kingpin who is responsible for his incarceration. Can he get '
                'revenge and win back his fed-up girlfriend? ',
 'Director': ['Rowan Athale'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland',
 'EntryURL': 'https://www.imdb.com/title/tt1981140',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Wasteland/info.py',
 'Genres': ['Crime', 'Drama', 'Thriller'],
 'Ratings': {'IMDB': '6.6/10',
             'Metascore': '52%',
             'PrimeWire': '3.61/5',
             'RT': '63%',
             'Votes': '147'},
 'Released': '2012-09-07',
 'Runtime': '108 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2740461_Wasteland_2013.jpg',
 'Title': 'Wasteland'}