{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-12-15',
 'EntryPath': 'Favorites/TV/snapshot/Alpha-House',
 'EntryURL': 'https://www.imdb.com/title/tt3012160',
 'Entry_json': 'Favorites/TV/snapshot/Alpha-House/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Alpha-House/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Alpha-House/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Goodman',
            'url': '/name/nm0000422/'},
           {'@type': 'Person',
            'name': 'Clark Johnson',
            'url': '/name/nm0424800/'},
           {'@type': 'Person',
            'name': 'Matt Malloy',
            'url': '/name/nm0540164/'},
           {'@type': 'Person',
            'name': 'Mark Consuelos',
            'url': '/name/nm0176175/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 4160,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Garry Trudeau',
              'url': '/name/nm0874034/'},
             {'@type': 'Organization', 'url': '/company/co0463309/'},
             {'@type': 'Organization', 'url': '/company/co0463308/'},
             {'@type': 'Organization', 'url': '/company/co0319272/'},
             {'@type': 'Organization', 'url': '/company/co0459918/'}],
 'datePublished': '2013-04-19',
 'description': 'Alpha House is a TV series starring John Goodman, Clark '
                'Johnson, and Matt Malloy. Four Republican senators share the '
                'same D.C. house rental, and face re-election battles, looming '
                'indictments, and parties -- all with a sense of humor.',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQyNDcwMDU5Nl5BMl5BanBnXkFtZTgwMDEwMjE4MjE@._V1_.jpg',
 'keywords': 'politics',
 'name': 'Alpha House',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Four Republican senators share the same D.C. '
                             'house rental, and face re-election battles, '
                             'looming indictments, and parties -- all with a '
                             'sense of humor.',
              'embedUrl': '/video/imdb/vi149597977',
              'name': 'Season 2 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2OTEwNjk5Nl5BMl5BanBnXkFtZTgwOTY1MTQ5MjE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2OTEwNjk5Nl5BMl5BanBnXkFtZTgwOTY1MTQ5MjE@._V1_.jpg',
              'uploadDate': '2014-10-11T14:18:04Z'}],
 'url': '/title/tt3012160/'}