{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Bloodborne',
 'EntryURL': 'https://rawg.io/games/bloodborne',
 'Entry_json': 'Favorites/Games/snapshot/Bloodborne/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Bloodborne/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Bloodborne/thumb.jpg',
 'added': 5203,
 'background_image': 'https://media.rawg.io/media/games/238/238ff9c62fcc94f152a7d4b612907c43.jpg',
 'developers': ['FromSoftware', 'Sony Interactive Entertainment'],
 'genres': ['Action', 'RPG'],
 'name': 'Bloodborne',
 'platforms': ['PlayStation 4'],
 'publishers': [],
 'released': '2015-03-24',
 'slug': 'bloodborne'}