<?php
$infoArray = array('Actors' => array("'Cousin Brucie' Morrow",
            'Andrea Bertola',
            'Arabella Holzbog',
            'Aristedes Philip DuVal',
            'Ben Hauck',
            'Bill Buell',
            'Bill Irwin',
            'Bill Richards',
            'Bono',
            'Brian M Wixson',
            'Brian Smyj',
            'Bruce Williamson',
            'Cameron Stevens',
            'Carol Woods',
            'Chris Margaritis',
            'Chris McGarry',
            'Chris McMullin',
            'Chris Miskiewicz',
            'Daniel Ezralow',
            'Daniel Stewart Sherman',
            'Deidre Goodwin',
            'Dennis Funny',
            'Dolores McDougal',
            'Dylan Baker',
            'Eddie Izzard',
            'Edwin Freeman',
            'Eric Michael Kochmer',
            'Evan Rachel Wood',
            'Frank Hopf',
            'Frank Stellato',
            'Gail Yudain',
            'Gloria Parks',
            'Harry Lennix',
            'Jacob Pitts',
            'James Urbaniak',
            'Jarlath Conroy',
            'Jennifer Van Dyck',
            'Jessica Frank',
            'Jim Ford',
            'Jim Sturgess',
            'Joe Anderson',
            'Joe Cocker',
            'Joe Dolinsky',
            'Jonah Falcon',
            'Julie Jei',
            'Julie McNiven',
            'Justin Restivo',
            'Katherine Hoskins Mackey',
            'Keith Moyer',
            "Kel O'Neill",
            'Kevin Alexander Stea',
            'Kevin Cannon',
            'Kevin Watson',
            'Kiva Dawson',
            'Linda Emond',
            'Logan Marshall-Green',
            'Luther Creek',
            'Lynn Cohen',
            'Marcus Collins',
            'Mark Keller'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nAcross the Universe: The music of the Beatles and the Vietnam War form the backdrop for the romance between an upper-class American girl and a poor Liverpudlian artist. ',
 'Director' => array('Julie Taymor'),
 'Genres' => array('Drama', 'Romance', 'Musical', 'Adventure'),
 'IMDB' => 'http://www.imdb.com/title/tt0445922',
 'PrimeWire' => 'http://www.primewire.ag/watch-1433-Across-the-Universe',
 'Ratings' => array('IMDB' => '7.5/10',
             'Metascore' => '56%',
             'PrimeWire' => '4.00/5',
             'RT' => '53%',
             'Votes' => '583'),
 'Released' => '2007-09-10',
 'Runtime' => '133 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1433_Across_the_Universe_2007.jpg',
 'Title' => 'Across-the-Universe');
?>