{'Actors': ['Chlo&#xEB; Sevigny',
            'Daniel Franzese',
            'Diana Scarwid',
            'Dylan McDermott',
            'John Stamos',
            'Macaulay Culkin',
            'Manny Perez',
            'Marilyn Manson',
            'Mia Kirshner',
            'Michael Kaycheck',
            'Natasha Lyonne',
            'Seth Green',
            'Steven Marcus',
            'Wilmer Valderrama',
            'Wilson Cruz'],
 'Added': '2013-02-19',
 'Countries': ['USA', 'Netherlands'],
 'Description': '\nParty Monster: This is the true story of ',
 'Director': ['Fenton Bailey'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Party-Monster',
 'EntryURL': 'https://www.imdb.com/title/tt0320244',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Party-Monster/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Party-Monster/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Party-Monster/info.py',
 'Genres': ['Drama', 'Thriller', 'Crime', 'Biography'],
 'Ratings': {'IMDB': '6.3/10',
             'Metascore': '36%',
             'PrimeWire': '3.86/5',
             'RT': '29%',
             'Votes': '210'},
 'Released': '2003-01-18',
 'Runtime': '98 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/6894_Party_Monster_2003.jpg',
 'Title': 'Party-Monster'}