{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Party-Monster',
 'EntryURL': 'https://www.imdb.com/title/tt0320244',
 'Entry_json': 'Favorites/Movies/snapshot/Party-Monster/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Party-Monster/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Party-Monster/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Macaulay Culkin',
            'url': '/name/nm0000346/'},
           {'@type': 'Person',
            'name': 'Wilson Cruz',
            'url': '/name/nm0190497/'},
           {'@type': 'Person', 'name': 'Seth Green', 'url': '/name/nm0001293/'},
           {'@type': 'Person',
            'name': 'Diana Scarwid',
            'url': '/name/nm0769311/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 14664,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Fenton Bailey',
              'url': '/name/nm0047259/'},
             {'@type': 'Person',
              'name': 'Randy Barbato',
              'url': '/name/nm0053190/'},
             {'@type': 'Person',
              'name': 'James St. James',
              'url': '/name/nm1306654/'},
             {'@type': 'Organization', 'url': '/company/co0093416/'},
             {'@type': 'Organization', 'url': '/company/co0030755/'},
             {'@type': 'Organization', 'url': '/company/co0031020/'},
             {'@type': 'Organization', 'url': '/company/co0071294/'},
             {'@type': 'Organization', 'url': '/company/co0242810/'}],
 'datePublished': '2003-10-17',
 'description': 'Party Monster is a movie starring Macaulay Culkin, Wilson '
                'Cruz, and Seth Green. Based on the true story of Michael '
                'Alig, a Club Kid party organizer whose life was sent '
                'spiraling down when he bragged on television about killing '
                'his...',
 'director': [{'@type': 'Person',
               'name': 'Fenton Bailey',
               'url': '/name/nm0047259/'},
              {'@type': 'Person',
               'name': 'Randy Barbato',
               'url': '/name/nm0053190/'}],
 'duration': 'PT1H38M',
 'genre': ['Biography', 'Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYjZlMWM1MGEtY2M5OS00MWZhLWI1OGUtYTAwY2JlM2U1ZTgwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'gay,homosexual,ketamine,true crime,bare chested male',
 'name': 'Party Monster',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Party Monster',
              'embedUrl': '/video/imdb/vi279904537',
              'name': 'Party Monster (2003)',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2JkOGMwZjktMjRiYi00YTE4LTlkMTYtN2U2YWM5Njg2NzAwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2JkOGMwZjktMjRiYi00YTE4LTlkMTYtN2U2YWM5Njg2NzAwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:34:21Z'}],
 'url': '/title/tt0320244/'}