{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontline',
 'EntryURL': 'https://www.imdb.com/title/tt0133302',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontline/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontline/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontline/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontline/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Will Lyman', 'url': '/name/nm0528164/'},
           {'@type': 'Person',
            'name': 'Sarah Childress',
            'url': '/name/nm4153580/'},
           {'@type': 'Person', 'name': 'Arun Rath', 'url': '/name/nm1947669/'},
           {'@type': 'Person',
            'name': 'Priyanka Boghani',
            'url': '/name/nm6640272/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1519,
                     'ratingValue': '8.5',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'datePublished': '1983-01-17',
 'description': 'Frontline is a TV series starring Will Lyman, Sarah '
                'Childress, and Arun Rath. Investigative journalist '
                'documentaries.',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTYwOTI3NjcwMF5BMl5BanBnXkFtZTgwMDM0MDE1NjM@._V1_.jpg',
 'keywords': 'united states,public affairs,investigative '
             'journalism,military,armed forces',
 'name': 'Frontline',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'BlobbyLight'},
            'dateCreated': '2020-04-09',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0133302/'},
            'name': 'Just no.',
            'reviewBody': 'These glowing reviews are frankly speaking a joke. '
                          'The show ranges from interesting well informed '
                          'topics to downright propagandized disinformation.. '
                          'making for a completely unbalanced and ultimately '
                          'untrustworthy source of "news". Seeking truthful '
                          'information on a particular topic? Begin by taking '
                          'a hard pass on Frontline. NEXT.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '1',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Storm Over Everest',
             'embedUrl': '/video/imdb/vi458996761',
             'name': 'Storm Over Everest',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BN2YwMWRjZmMtNGNhMS00MDY3LTg3ZDQtOTViZDhjY2ZkOTk1XkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BN2YwMWRjZmMtNGNhMS00MDY3LTg3ZDQtOTViZDhjY2ZkOTk1XkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
             'uploadDate': '2019-08-06T19:52:51Z'},
 'url': '/title/tt0133302/'}