{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Wall-Street',
 'EntryURL': 'https://www.imdb.com/title/tt0094291',
 'Entry_json': 'Favorites/Movies/snapshot/Wall-Street/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Wall-Street/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Wall-Street/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Charlie Sheen',
            'url': '/name/nm0000221/'},
           {'@type': 'Person',
            'name': 'Michael Douglas',
            'url': '/name/nm0000140/'},
           {'@type': 'Person',
            'name': 'Tamara Tunie',
            'url': '/name/nm0876645/'},
           {'@type': 'Person',
            'name': 'Franklin Cover',
            'url': '/name/nm0184429/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 140366,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Stanley Weiser',
              'url': '/name/nm0007140/'},
             {'@type': 'Person',
              'name': 'Oliver Stone',
              'url': '/name/nm0000231/'},
             {'@type': 'Organization', 'url': '/company/co0000756/'},
             {'@type': 'Organization', 'url': '/company/co0065783/'},
             {'@type': 'Organization', 'url': '/company/co0022392/'}],
 'datePublished': '1987-12-11',
 'description': 'Wall Street is a movie starring Charlie Sheen, Michael '
                'Douglas, and Tamara Tunie. A young and impatient stockbroker '
                'is willing to do anything to get to the top, including '
                'trading on illegal inside information taken through a...',
 'director': [{'@type': 'Person',
               'name': 'Oliver Stone',
               'url': '/name/nm0000231/'}],
 'duration': 'PT2H6M',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNmEyZGQ4NDQtNTEzZC00MDczLWE4ZTEtYTg0ODg2NTkyMWM3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'capitalism,blow job,1980s,fired from the job,critique of '
             'capitalism',
 'name': 'Wall Street',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from 20th Century Fox Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi3554738457',
              'name': 'Wall Street',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNGU4ZDc2Y2QtMTg3Ny00NzM4LWIyOTMtODU0N2Y3YzMyNTkzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNGU4ZDc2Y2QtMTg3Ny00NzM4LWIyOTMtODU0N2Y3YzMyNTkzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-18T12:00:39Z'}],
 'url': '/title/tt0094291/'}