{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Insatiable',
 'EntryURL': 'https://www.imdb.com/title/tt6487482',
 'Entry_json': 'Favorites/TV/snapshot/Insatiable/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Insatiable/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Insatiable/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Dallas Roberts',
            'url': '/name/nm1316767/'},
           {'@type': 'Person', 'name': 'Debby Ryan', 'url': '/name/nm2913275/'},
           {'@type': 'Person',
            'name': 'Christopher Gorham',
            'url': '/name/nm0330913/'},
           {'@type': 'Person',
            'name': 'Kimmy Shields',
            'url': '/name/nm5777436/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 20795,
                      'ratingValue': '6.6',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Lauren Gussis',
              'url': '/name/nm0348940/'},
             {'@type': 'Organization', 'url': '/company/co0274041/'},
             {'@type': 'Organization', 'url': '/company/co0188589/'},
             {'@type': 'Organization', 'url': '/company/co0448478/'}],
 'datePublished': '2018-08-10',
 'description': 'Insatiable is a TV series starring Dallas Roberts, Debby '
                'Ryan, and Christopher Gorham. A disgraced, dissatisfied civil '
                'lawyer-turned-beauty pageant coach takes on a vengeful, '
                "bullied teenager as his client and has no idea what he's...",
 'genre': ['Comedy', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODUzODY1NzEtYjNiNy00NzEwLThhYzEtZGUxZjQ4MDRiNjY2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'beauty pageant,teenage girl,weight loss,lawyer,high school',
 'name': 'Insatiable',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A coming of rage story: "Insatiable," starring '
                             'Debby Ryan, arrives Aug. 10, 2018, on Netflix.',
              'embedUrl': '/video/imdb/vi2965682969',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWI2N2VkZWQtYWZmYi00ZmY4LWI1MGYtNmRjOTljOTljMWM1XkEyXkFqcGdeQXRzdGFzaWVr._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWI2N2VkZWQtYWZmYi00ZmY4LWI1MGYtNmRjOTljOTljMWM1XkEyXkFqcGdeQXRzdGFzaWVr._V1_.jpg',
              'uploadDate': '2018-07-19T17:19:47Z'}],
 'url': '/title/tt6487482/'}