{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Insatiable',
 'EntryURL': 'https://www.imdb.com/title/tt6487482',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Insatiable/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Insatiable/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Insatiable/info.py',
 'Title': 'Insatiable',
 'actor': [{'@type': 'Person',
            'name': 'Dallas Roberts',
            'url': '/name/nm1316767/'},
           {'@type': 'Person', 'name': 'Debby Ryan', 'url': '/name/nm2913275/'},
           {'@type': 'Person',
            'name': 'Christopher Gorham',
            'url': '/name/nm0330913/'},
           {'@type': 'Person',
            'name': 'Kimmy Shields',
            'url': '/name/nm5777436/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 20790,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Lauren Gussis',
              'url': '/name/nm0348940/'},
             {'@type': 'Organization', 'url': '/company/co0274041/'},
             {'@type': 'Organization', 'url': '/company/co0188589/'},
             {'@type': 'Organization', 'url': '/company/co0448478/'}],
 'datePublished': '2018-08-10',
 'description': 'Insatiable is a TV series starring Dallas Roberts, Debby '
                'Ryan, and Christopher Gorham. A disgraced, dissatisfied civil '
                'lawyer-turned-beauty pageant coach takes on a vengeful, '
                "bullied teenager as his client and has no idea what he's...",
 'genre': ['Comedy', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODUzODY1NzEtYjNiNy00NzEwLThhYzEtZGUxZjQ4MDRiNjY2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'beauty pageant,teenage girl,weight loss,lawyer,high school',
 'name': 'Insatiable',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'marhruby'},
            'dateCreated': '2018-08-10',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt6487482/'},
            'name': "It's not offensive.",
            'reviewBody': "I'm politically extremely liberal. I'm from the "
                          "Silicon Valley for Christ's sake. I was extremely "
                          "fat in high school. And I didn't think it was "
                          "offensive at all. It's a SATIRICAL take on the "
                          "pageant world and teen angst. If you're offended by "
                          'this show you need to take the stick out of your '
                          'butt. The show is MEANT to be ridiculous and dark. '
                          'Come on now for goodness sakes lol.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'A coming of rage story: "Insatiable," starring '
                            'Debby Ryan, arrives Aug. 10, 2018, on Netflix.',
             'embedUrl': '/video/imdb/vi2965682969',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWI2N2VkZWQtYWZmYi00ZmY4LWI1MGYtNmRjOTljOTljMWM1XkEyXkFqcGdeQXRzdGFzaWVr._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWI2N2VkZWQtYWZmYi00ZmY4LWI1MGYtNmRjOTljOTljMWM1XkEyXkFqcGdeQXRzdGFzaWVr._V1_.jpg',
             'uploadDate': '2018-07-19T17:19:47Z'},
 'url': '/title/tt6487482/'}