{'Actors': ['Bruce Dern',
            'Channing Tatum',
            'James Parks',
            'Jennifer Jason Leigh',
            'Kurt Russell',
            'Michael Madsen',
            'Samuel L Jackson',
            'Tim Roth',
            'Walton Goggins'],
 'Added': '2015-12-25',
 'Countries': ['USA'],
 'Description': '\n'
                'The Hateful Eight: In post-Civil War Wyoming, bounty hunters '
                'try to find shelter during a blizzard but get involved in a '
                'plot of betrayal and deception. Will they survive? ',
 'Director': ['Quentin Tarantino'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hateful-Eight',
 'EntryURL': 'https://www.imdb.com/title/tt3460252',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hateful-Eight/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hateful-Eight/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hateful-Eight/info.py',
 'Genres': ['Western'],
 'IMDB': 'http://www.imdb.com/title/tt3460252',
 'PrimeWire': 'http://www.primewire.ag/watch-2772075-The-Hateful-Eight',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '3.92/5',
             'RT': 'N/A',
             'Votes': '1608'},
 'Released': '2015-12-07',
 'Runtime': '168 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2772073_The_Hateful_Eight_2016.jpg',
 'Title': 'The-Hateful-Eight'}