{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-12-25',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hateful-Eight',
 'EntryURL': 'https://www.imdb.com/title/tt3460252',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hateful-Eight/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hateful-Eight/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hateful-Eight/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Samuel L. Jackson',
            'url': '/name/nm0000168/'},
           {'@type': 'Person',
            'name': 'Kurt Russell',
            'url': '/name/nm0000621/'},
           {'@type': 'Person',
            'name': 'Jennifer Jason Leigh',
            'url': '/name/nm0000492/'},
           {'@type': 'Person',
            'name': 'Walton Goggins',
            'url': '/name/nm0324658/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 490326,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Organization', 'url': '/company/co0282627/'},
             {'@type': 'Organization', 'url': '/company/co0118437/'},
             {'@type': 'Organization', 'url': '/company/co0159642/'}],
 'datePublished': '2015-12-30',
 'description': 'The Hateful Eight is a movie starring Samuel L. Jackson, Kurt '
                'Russell, and Jennifer Jason Leigh. In the dead of a Wyoming '
                'winter, a bounty hunter and his prisoner find shelter in a '
                'cabin currently inhabited by a collection of...',
 'director': {'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
 'duration': 'PT2H48M',
 'genre': ['Crime', 'Drama', 'Mystery', 'Thriller', 'Western'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_.jpg',
 'keywords': 'murder,bounty hunter,blizzard,blood vomiting,projectile vomiting',
 'name': 'The Hateful Eight',
 'trailer': {'@type': 'VideoObject',
             'description': 'In post-Civil War Wyoming, bounty hunters try to '
                            'find shelter during a blizzard but get involved '
                            'in a plot of betrayal and deception. Will they '
                            'survive?',
             'embedUrl': '/video/imdb/vi2079306521',
             'name': 'Teaser',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjE4MjQ3MzgyNl5BMl5BanBnXkFtZTgwNDcwMDM1NjE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjE4MjQ3MzgyNl5BMl5BanBnXkFtZTgwNDcwMDM1NjE@._V1_.jpg',
             'uploadDate': '2015-08-13T06:24:30Z'},
 'url': '/title/tt3460252/'}