{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting',
 'EntryURL': 'https://www.imdb.com/title/tt0117951',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ewan McGregor',
            'url': '/name/nm0000191/'},
           {'@type': 'Person',
            'name': 'Ewen Bremner',
            'url': '/name/nm0001971/'},
           {'@type': 'Person',
            'name': 'Jonny Lee Miller',
            'url': '/name/nm0001538/'},
           {'@type': 'Person',
            'name': 'Kevin McKidd',
            'url': '/name/nm0571727/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 617855,
                     'ratingValue': '8.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Irvine Welsh',
              'url': '/name/nm0920543/'},
             {'@type': 'Person',
              'name': 'John Hodge',
              'url': '/name/nm0388076/'},
             {'@type': 'Organization', 'url': '/company/co0103532/'},
             {'@type': 'Organization', 'url': '/company/co0103732/'},
             {'@type': 'Organization', 'url': '/company/co0011025/'}],
 'datePublished': '1996-02-23',
 'description': 'Trainspotting is a movie starring Ewan McGregor, Ewen '
                'Bremner, and Jonny Lee Miller. Renton, deeply immersed in the '
                'Edinburgh drug scene, tries to clean up and get out, despite '
                'the allure of the drugs and influence of friends.',
 'director': {'@type': 'Person',
              'name': 'Danny Boyle',
              'url': '/name/nm0000965/'},
 'duration': 'PT1H33M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMzA5Zjc3ZTMtMmU5YS00YTMwLWI4MWUtYTU0YTVmNjVmODZhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'drugs,drug culture,filthy toilet,scotland,heroin addict',
 'name': 'Trainspotting',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Trainspotting',
             'embedUrl': '/video/imdb/vi2148899865',
             'name': 'Trainspotting: Blu-Ray',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOGRmMWQxNTItNGQ5NC00OTY4LTgzZWUtNDEyMmY4OTFhM2EyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOGRmMWQxNTItNGQ5NC00OTY4LTgzZWUtNDEyMmY4OTFhM2EyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-08-20T03:47:24Z'},
 'url': '/title/tt0117951/'}