{'Actors': ['Annie Louise Ross',
            'Billy Riddoch',
            'Dale Winton',
            'Eileen Nicholas',
            'Ewan McGregor',
            'Ewen Bremner',
            'Finlay Welsh',
            'Fiona Bell',
            'Hugh Ross',
            'James Cosmo',
            'Jonny Lee Miller',
            'Kate Donnelly',
            'Keith Allen',
            'Kelly Macdonald',
            'Kevin Allen',
            'Kevin McKidd',
            'Pauline Lynch',
            'Peter Mullan',
            'Robert Carlyle',
            'Shirley Henderson',
            'Stuart McQuarrie',
            'Susan Vidler',
            'Tom Delmar',
            'Vincent Friell'],
 'Added': '2013-02-19',
 'Countries': ['UK'],
 'Description': '\n'
                'Trainspotting: Renton, deeply immersed in the Edinburgh drug '
                'scene, tries to clean up and get out, despite the allure of '
                'the drugs and influence of friends. ',
 'Director': ['Danny Boyle'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting',
 'EntryURL': 'https://www.imdb.com/title/tt0117951',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Trainspotting/info.py',
 'Genres': ['Drama', 'Comedy', 'Crime'],
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': '83%',
             'PrimeWire': '4.29/5',
             'RT': '89%',
             'Votes': '609'},
 'Released': '1996-02-23',
 'Runtime': '94 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/946_Trainspotting_1996.jpg',
 'Title': 'Trainspotting'}