{'Actors': ['Alan Rickman',
            'Albie Woodington',
            'Alex Argenti',
            'Anna Chancellor',
            'Bill Bailey',
            'Bill Nighy',
            'Dan Ellis',
            'Dominique Jackson',
            'Edgar Wright',
            'Helen Mirren',
            'Ian McNeice',
            'Jason Schwartzman',
            'Jerome Blake',
            'John Malkovich',
            'Kelly Macdonald',
            'Mak Wilson',
            'Mark Gatiss',
            'Mark Smith',
            'Martin Freeman',
            'Mos Def',
            'Nigel Plaskitt',
            'Peter Burroughs',
            'Ray Donn',
            'Reece Shearsmith',
            'Richard Griffiths',
            'Sam Rockwell',
            'Simon Jones',
            'Spencer Wilding',
            'Stephen Fry',
            'Steve Pemberton',
            'Su Elliot',
            'Susie Gossling Valerio',
            'Thomas Lennon',
            'Warwick Davis',
            'Zooey Deschanel'],
 'Added': '2013-06-07',
 'Countries': ['USA', 'UK'],
 'Description': '\r\n'
                "              The Hitchhiker's Guide to the Galaxy: Mere "
                'seconds before the Earth is to be demolished by an alien '
                'construction crew, journeyman Arthur Dent is swept off the '
                'planet by his friend Ford Prefect, a researcher penning a new '
                'edition of "The Hitchhiker\'s Guide to the '
                'Galaxy."            ',
 'Director': ['Garth Jennings'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hitchhikers-Guide-to-the-Galaxy',
 'EntryURL': 'http://www.imdb.com/title/tt0371724',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hitchhikers-Guide-to-the-Galaxy/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hitchhikers-Guide-to-the-Galaxy/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Hitchhikers-Guide-to-the-Galaxy/info.py',
 'Genres': ['Comedy', 'Sci-Fi', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0371724',
 'PrimeWire': 'http://www.primewire.ag/watch-1720-The-Hitchhikers-Guide-to-the-Galaxy',
 'Ratings': {'IMDB': '6.8/10',
             'Metascore': '63%',
             'PrimeWire': '4.01/5',
             'RT': 'N/A',
             'Votes': '570'},
 'Released': '2005-04-20',
 'Runtime': '109 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1720_The_Hitchhikers_Guide_to_the_Galaxy_2005.jpg',
 'Title': 'The-Hitchhikers-Guide-to-the-Galaxy'}