{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-07',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hitchhikers-Guide-to-the-Galaxy',
 'EntryURL': 'https://www.imdb.com/title/tt0371724',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hitchhikers-Guide-to-the-Galaxy/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hitchhikers-Guide-to-the-Galaxy/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Hitchhikers-Guide-to-the-Galaxy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Martin Freeman',
            'url': '/name/nm0293509/'},
           {'@type': 'Person', 'name': 'Yasiin Bey', 'url': '/name/nm0080049/'},
           {'@type': 'Person',
            'name': 'Sam Rockwell',
            'url': '/name/nm0005377/'},
           {'@type': 'Person',
            'name': 'Zooey Deschanel',
            'url': '/name/nm0221046/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 183039,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Douglas Adams',
              'url': '/name/nm0010930/'},
             {'@type': 'Person',
              'name': 'Douglas Adams',
              'url': '/name/nm0010930/'},
             {'@type': 'Person',
              'name': 'Karey Kirkpatrick',
              'url': '/name/nm0456732/'},
             {'@type': 'Organization', 'url': '/company/co0049348/'},
             {'@type': 'Organization', 'url': '/company/co0031181/'},
             {'@type': 'Organization', 'url': '/company/co0136709/'},
             {'@type': 'Organization', 'url': '/company/co0104360/'}],
 'datePublished': '2005-04-28',
 'description': "The Hitchhiker's Guide to the Galaxy is a movie starring "
                'Martin Freeman, Yasiin Bey, and Sam Rockwell. Mere seconds '
                'before the Earth is to be demolished by an alien construction '
                'crew, journeyman Arthur Dent is swept off the planet...',
 'director': {'@type': 'Person',
              'name': 'Garth Jennings',
              'url': '/name/nm1134029/'},
 'duration': 'PT1H49M',
 'genre': ['Adventure', 'Comedy', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZmU5MGU4MjctNjA2OC00N2FhLWFhNWQtMzQyMGI2ZmQ0Y2YyL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'hyperspace,robot,cow,norway,male alien',
 'name': "The Hitchhiker's Guide to the Galaxy",
 'trailer': {'@type': 'VideoObject',
             'description': "Trailer for The Hitchhiker's Guide to the Galaxy "
                            '(2005)',
             'embedUrl': '/video/imdb/vi1099150873',
             'name': "The Hitchhiker's Guide to the Galaxy",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjM5NDczOTg3OV5BMl5BanBnXkFtZTgwNjkzMTIyMDI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjM5NDczOTg3OV5BMl5BanBnXkFtZTgwNjkzMTIyMDI@._V1_.jpg',
             'uploadDate': '2016-10-04T05:19:38Z'},
 'url': '/title/tt0371724/'}