{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Mr-Hollands-Opus',
 'EntryURL': 'https://www.imdb.com/title/tt0113862',
 'Entry_json': 'Favorites/Movies/snapshot/Mr-Hollands-Opus/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Mr-Hollands-Opus/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Mr-Hollands-Opus/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Richard Dreyfuss',
            'url': '/name/nm0000377/'},
           {'@type': 'Person',
            'name': 'Glenne Headly',
            'url': '/name/nm0000444/'},
           {'@type': 'Person', 'name': 'Jay Thomas', 'url': '/name/nm0858988/'},
           {'@type': 'Person',
            'name': 'Olympia Dukakis',
            'url': '/name/nm0001156/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 34658,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Patrick Sheane Duncan',
              'url': '/name/nm0242059/'},
             {'@type': 'Organization', 'url': '/company/co0076240/'},
             {'@type': 'Organization', 'url': '/company/co0031772/'},
             {'@type': 'Organization', 'url': '/company/co0030612/'},
             {'@type': 'Organization', 'url': '/company/co0007268/'}],
 'datePublished': '1996-01-18',
 'description': "Mr. Holland's Opus is a movie starring Richard Dreyfuss, "
                'Glenne Headly, and Jay Thomas. A frustrated composer finds '
                'fulfillment as a high school music teacher.',
 'director': {'@type': 'Person',
              'name': 'Stephen Herek',
              'url': '/name/nm0378893/'},
 'duration': 'PT2H23M',
 'genre': ['Drama', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZDZhNDRlZjAtYzdhNy00ZjU1LWFlMDYtNjA5NjliM2Y5ZmVjL2ltYWdlXkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_.jpg',
 'keywords': 'teaching,high school,1990s,deafness,high school teacher',
 'name': "Mr. Holland's Opus",
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Hollywood Pictures',
             'embedUrl': '/video/imdb/vi966459673',
             'name': "Mr. Holland's Opus",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZjUzYTBiMGItNzEzNi00ZjAyLTg4NzMtOGU1OTdiZmM4ZWM5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZjUzYTBiMGItNzEzNi00ZjAyLTg4NzMtOGU1OTdiZmM4ZWM5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T15:20:27Z'},
 'url': '/title/tt0113862/'}