{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Island',
 'EntryURL': 'https://www.imdb.com/title/tt0399201',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Island/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Island/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Island/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Scarlett Johansson',
            'url': '/name/nm0424060/'},
           {'@type': 'Person',
            'name': 'Ewan McGregor',
            'url': '/name/nm0000191/'},
           {'@type': 'Person',
            'name': 'Djimon Hounsou',
            'url': '/name/nm0005023/'},
           {'@type': 'Person',
            'name': 'Steve Buscemi',
            'url': '/name/nm0000114/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 295654,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Caspian Tredwell-Owen',
              'url': '/name/nm1047021/'},
             {'@type': 'Person',
              'name': 'Alex Kurtzman',
              'url': '/name/nm0476064/'},
             {'@type': 'Person',
              'name': 'Roberto Orci',
              'url': '/name/nm0649460/'},
             {'@type': 'Person',
              'name': 'Caspian Tredwell-Owen',
              'url': '/name/nm1047021/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0108321/'},
             {'@type': 'Organization', 'url': '/company/co0176022/'},
             {'@type': 'Organization', 'url': '/company/co0071240/'}],
 'datePublished': '2005-07-20',
 'description': 'The Island is a movie starring Scarlett Johansson, Ewan '
                'McGregor, and Djimon Hounsou. A man living in a futuristic '
                'sterile colony begins to question his circumscribed existence '
                'when his friend is chosen to go to the Island, the last...',
 'director': {'@type': 'Person',
              'name': 'Michael Bay',
              'url': '/name/nm0000881/'},
 'duration': 'PT2H16M',
 'genre': ['Action', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTAwNjk0NjM1ODReQTJeQWpwZ15BbWU3MDc1NjIxMzM@._V1_.jpg',
 'keywords': 'year 2019,island,clone,same actor playing two characters '
             'simultaneously on screen,actress playing dual role',
 'name': 'The Island',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Dreamworks',
             'embedUrl': '/video/imdb/vi2968781081',
             'name': 'The Island',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMmIwYzA2ZmMtZjFmNS00ZjdkLTk1MDAtNjM5Yjg0ZDQ2Y2QxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMmIwYzA2ZmMtZjFmNS00ZjdkLTk1MDAtNjM5Yjg0ZDQ2Y2QxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:50:05Z'},
 'url': '/title/tt0399201/'}