{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/The-Jim-Jefferies-Show',
 'EntryURL': 'https://www.imdb.com/title/tt6987966',
 'Entry_json': 'Favorites/TV/snapshot/The-Jim-Jefferies-Show/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Jim-Jefferies-Show/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Jim-Jefferies-Show/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jim Jefferies',
            'url': '/name/nm1812944/'},
           {'@type': 'Person', 'name': 'Brad Pitt', 'url': '/name/nm0000093/'},
           {'@type': 'Person', 'name': 'Seth Rogen', 'url': '/name/nm0736622/'},
           {'@type': 'Person',
            'name': 'Russell Rope',
            'url': '/name/nm9893604/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 2105,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Jim Jefferies',
              'url': '/name/nm1812944/'},
             {'@type': 'Organization', 'url': '/company/co0485719/'},
             {'@type': 'Organization', 'url': '/company/co0214340/'},
             {'@type': 'Organization', 'url': '/company/co0647992/'},
             {'@type': 'Organization', 'url': '/company/co0029768/'}],
 'datePublished': '2017-06-06',
 'description': 'The Jim Jefferies Show is a TV series starring Jim Jefferies, '
                'Brad Pitt, and Seth Rogen. No-holds-barred Aussie comedian '
                'Jim Jefferies hosts his satirical weekly U.S. talk show, '
                'covering the news, U.S. politics, pop culture, global...',
 'genre': ['Comedy', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjEwNjc2NDI1M15BMl5BanBnXkFtZTgwODEyOTQ2MjI@._V1_.jpg',
 'keywords': 'social satire,political satire,interview,stand up '
             'comedian,australian',
 'name': 'The Jim Jefferies Show',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Jim Jefferies Show, The: Season 1',
              'embedUrl': '/video/imdb/vi1601879321',
              'name': 'Jim Jefferies Show, The: Season 1',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDQ1OGMwZGEtNjRlNy00OTU5LTljYzktZTkwZjAzODA3NzA2XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDQ1OGMwZGEtNjRlNy00OTU5LTljYzktZTkwZjAzODA3NzA2XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-04-13T11:54:48Z'}],
 'url': '/title/tt6987966/'}