{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Alone-In-The-Dark-2008',
 'EntryURL': 'https://rawg.io/games/alone-in-the-dark-2008',
 'Entry_json': 'Favorites/Games/snapshot/Alone-In-The-Dark-2008/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Alone-In-The-Dark-2008/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Alone-In-The-Dark-2008/thumb.jpg',
 'added': 10,
 'background_image': 'https://media.rawg.io/media/screenshots/3d0/3d04aeedcf8eef91157165a8353df433.jpg',
 'developers': ['Eden Games'],
 'genres': ['Action'],
 'name': 'Alone in the Dark (2008)',
 'platforms': ['PC'],
 'publishers': ['Atari'],
 'released': '2008-06-20',
 'slug': 'alone-in-the-dark-2008'}