{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-03-25',
 'EntryPath': 'Favorites/Movies/snapshot/Doomsday-Book',
 'EntryURL': 'https://www.imdb.com/title/tt2297164',
 'Entry_json': 'Favorites/Movies/snapshot/Doomsday-Book/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Doomsday-Book/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Doomsday-Book/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Doona Bae', 'url': '/name/nm0046277/'},
           {'@type': 'Person',
            'name': 'Duk-moon Choi',
            'url': '/name/nm1117728/'},
           {'@type': 'Person',
            'name': 'Hyo-eun Hwang',
            'url': '/name/nm2493384/'},
           {'@type': 'Person',
            'name': 'Ji-hee Jin',
            'url': '/name/nm2987479/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3147,
                      'ratingValue': '5.9',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Jee-woon Kim',
              'url': '/name/nm0453518/'},
             {'@type': 'Person',
              'name': 'Hwan-Hee Lee',
              'url': '/name/nm11715763/'},
             {'@type': 'Person',
              'name': 'Sung-Hwan Park',
              'url': '/name/nm11715764/'},
             {'@type': 'Person',
              'name': 'Jong-kyu Yang',
              'url': '/name/nm11713692/'},
             {'@type': 'Person',
              'name': 'Pil-sung Yim',
              'url': '/name/nm1941507/'},
             {'@type': 'Person',
              'name': 'Pil-sung Yim',
              'url': '/name/nm1941507/'},
             {'@type': 'Organization', 'url': '/company/co0186817/'}],
 'datePublished': '2012-04-11',
 'description': 'In-lyu-myeol-mang-bo-go-seo is a movie starring Doona Bae, '
                'Duk-moon Choi, and Hyo-eun Hwang. The First Chapter of The '
                'Anthology Film- In A Brave New World, a mysterious virus '
                'brings the city to ruins and zombies flood the streets of...',
 'director': [{'@type': 'Person',
               'name': 'Jee-woon Kim',
               'url': '/name/nm0453518/'},
              {'@type': 'Person',
               'name': 'Pil-sung Yim',
               'url': '/name/nm1941507/'},
              {'@type': 'Person',
               'name': 'Pil-sung Yim',
               'url': '/name/nm1941507/'}],
 'duration': 'PT1H55M',
 'genre': ['Comedy', 'Drama', 'Fantasy', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTgyNTA3NjM0MV5BMl5BanBnXkFtZTgwMjUxNzIwMTE@._V1_.jpg',
 'keywords': 'robot,asteroid,artificial intelligence,end of the world,ceo',
 'name': 'In-lyu-myeol-mang-bo-go-seo',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailers for Doomsday Book',
              'embedUrl': '/video/imdb/vi3353066009',
              'name': 'Doomsday Book',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNGVmYzExMzktMjI5Ny00ZDU2LTkzM2YtNDYzMTZkNjIyMDljXkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNGVmYzExMzktMjI5Ny00ZDU2LTkzM2YtNDYzMTZkNjIyMDljXkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg',
              'uploadDate': '2018-12-04T17:11:04Z'}],
 'url': '/title/tt2297164/'}