{'Actors': [''],
 'Added': '2013-03-25',
 'Countries': ['Korea'],
 'Description': '\nDoomsday Book: First Chapter (\x93Heaven\x92s Creation\x94\nA story about a robot who gains consciousness and the abusrdity that follows.\nSecond Chapter (\x93The New Generation\x94\nA clever action film told from the point of view of a boy who has become a zombie, this segment explores how humans lose control of planet Earth, becoming mere food for a different species.\nThird Chapter (\x93Happy Birthday\x94\nA musical movie that re-interprets the beautiful love story \x93The Christmas Gift\x94 by O Henry, this project confronts the basic instincts of a woman and her last chance to survive after witnessing the end of the world. ',
 'Director': [],
 'Genres': ['Drama', 'Sci-Fi'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2734383-Doomsday-Book',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '3.92/5',
             'RT': 'N/A',
             'Votes': '71'},
 'Released': '2012-04-05',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2734383_Doomsday_Book.jpg',
 'Title': 'Doomsday-Book'}