{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Mother',
 'EntryURL': 'https://www.imdb.com/title/tt5109784',
 'Entry_json': 'Favorites/Movies/snapshot/Mother/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Mother/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Mother/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jennifer Lawrence',
            'url': '/name/nm2225369/'},
           {'@type': 'Person',
            'name': 'Javier Bardem',
            'url': '/name/nm0000849/'},
           {'@type': 'Person', 'name': 'Ed Harris', 'url': '/name/nm0000438/'},
           {'@type': 'Person',
            'name': 'Michelle Pfeiffer',
            'url': '/name/nm0000201/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 183073,
                      'ratingValue': '6.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0062935/'}],
 'datePublished': '2017-09-13',
 'description': 'Mother! is a movie starring Jennifer Lawrence, Javier Bardem, '
                "and Ed Harris. A couple's relationship is tested when "
                'uninvited guests arrive at their home, disrupting their '
                'tranquil existence.',
 'director': [{'@type': 'Person',
               'name': 'Darren Aronofsky',
               'url': '/name/nm0004716/'}],
 'duration': 'PT2H1M',
 'genre': ['Drama', 'Horror', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzc5ODExODE0MV5BMl5BanBnXkFtZTgwNDkzNDUxMzI@._V1_.jpg',
 'keywords': 'surrealism,cannibalism,riot,pregnant woman,uninvited guest',
 'name': 'Mother!',
 'trailer': [{'@type': 'VideoObject',
              'description': "A couple's relationship is tested when uninvited "
                             'guests arrive at their home, disrupting their '
                             'tranquil existence.',
              'embedUrl': '/video/imdb/vi2921576729',
              'name': 'Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzVmYTdiZjctMDE5NS00M2RlLWIxNTAtYjJmMWE1MmUzOTBmXkEyXkFqcGdeQXVyMjM4OTI2MTU@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzVmYTdiZjctMDE5NS00M2RlLWIxNTAtYjJmMWE1MmUzOTBmXkEyXkFqcGdeQXVyMjM4OTI2MTU@._V1_.jpg',
              'uploadDate': '2017-08-07T19:48:40Z'}],
 'url': '/title/tt5109784/'}