<?php
$infoArray = array('Actors' => array("Alex O'Loughlin",
            'Bernadette Lords',
            'Dominic Colon',
            'Freddie Highmore',
            'John Farrer',
            'John Knox',
            'Jonathan Rhys Meyers',
            'Keri Russell',
            'Marc Alan Austen',
            'Marian Seldes',
            'Megan Gallagher',
            'Mykelti Williamson',
            'Paul Thornton',
            'Raymond Johnson',
            'Robert Aberdeen',
            'Robert Myers',
            'Robin Williams',
            'Ronald Guttman',
            'Stream',
            'Terrence Howard',
            'Tony Galtieri',
            'Vincent James Russo',
            'William Sadler'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nAugust Rush: A drama with fairy tale elements, where an orphaned musical prodigy uses his gift as a clue to finding his birth parents. ',
 'Director' => array('Kirsten Sheridan'),
 'Genres' => array('Drama', 'Romance', 'Music'),
 'IMDB' => 'http://www.imdb.com/title/tt0426931',
 'PrimeWire' => 'http://www.primewire.ag/watch-1118-August-Rush',
 'Ratings' => array('IMDB' => '7.6/10',
             'Metascore' => '38%',
             'PrimeWire' => '4.33/5',
             'RT' => '37%',
             'Votes' => '974'),
 'Released' => '2007-10-06',
 'Runtime' => '114 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1118_August_Rush_2007.jpg',
 'Title' => 'August-Rush');
?>