{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/August-Rush',
 'EntryURL': 'https://www.imdb.com/title/tt0426931',
 'Entry_json': 'Favorites/Movies/snapshot/August-Rush/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/August-Rush/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/August-Rush/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Freddie Highmore',
            'url': '/name/nm0383603/'},
           {'@type': 'Person',
            'name': 'Keri Russell',
            'url': '/name/nm0005392/'},
           {'@type': 'Person',
            'name': 'Jonathan Rhys Meyers',
            'url': '/name/nm0001667/'},
           {'@type': 'Person',
            'name': 'Terrence Howard',
            'url': '/name/nm0005024/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 101756,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Nick Castle',
              'url': '/name/nm0145309/'},
             {'@type': 'Person',
              'name': 'James V. Hart',
              'url': '/name/nm0366337/'},
             {'@type': 'Person',
              'name': 'Paul Castro',
              'url': '/name/nm1554513/'},
             {'@type': 'Person',
              'name': 'Nick Castle',
              'url': '/name/nm0145309/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0110945/'},
             {'@type': 'Organization', 'url': '/company/co0043365/'}],
 'datePublished': '2007-11-21',
 'description': 'August Rush is a movie starring Freddie Highmore, Keri '
                'Russell, and Jonathan Rhys Meyers. An orphaned musical '
                'prodigy uses his gift to try to find his birth parents.',
 'director': {'@type': 'Person',
              'name': 'Kirsten Sheridan',
              'url': '/name/nm0792202/'},
 'duration': 'PT1H54M',
 'genre': ['Drama', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDIwNjE3NjU2NV5BMl5BanBnXkFtZTcwNTQ2NjQzMw@@._V1_.jpg',
 'keywords': 'baby,cellist,prodigy,rhapsody,genius',
 'name': 'August Rush',
 'trailer': {'@type': 'VideoObject',
             'description': 'August Rush Trailer',
             'embedUrl': '/video/imdb/vi380764441',
             'name': 'August Rush',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTM4OTgzODMyMV5BMl5BanBnXkFtZTYwNTk4NDQ4._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTM4OTgzODMyMV5BMl5BanBnXkFtZTYwNTk4NDQ4._V1_.jpg',
             'uploadDate': '2007-11-28T14:37:33Z'},
 'url': '/title/tt0426931/'}