{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-10-18',
 'EntryPath': 'Favorites/TV/snapshot/Spartacus-Gods-of-the-Arena',
 'EntryURL': 'https://www.imdb.com/title/tt1758429',
 'Entry_json': 'Favorites/TV/snapshot/Spartacus-Gods-of-the-Arena/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Spartacus-Gods-of-the-Arena/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Spartacus-Gods-of-the-Arena/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Hannah',
            'url': '/name/nm0001314/'},
           {'@type': 'Person',
            'name': 'Manu Bennett',
            'url': '/name/nm0071847/'},
           {'@type': 'Person',
            'name': 'Peter Mensah',
            'url': '/name/nm0579795/'},
           {'@type': 'Person',
            'name': 'Dustin Clare',
            'url': '/name/nm1967109/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 122659,
                      'ratingValue': '8.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Steven S. DeKnight',
              'url': '/name/nm0215299/'},
             {'@type': 'Organization', 'url': '/company/co0000869/'}],
 'datePublished': '2011-01-21',
 'description': 'Spartacus: Gods of the Arena is a TV mini-series starring '
                'John Hannah, Manu Bennett, and Peter Mensah. In the time '
                'before the arrival of Spartacus, the House of Batiatus faces '
                'many challenges from competitors, and within its own...',
 'genre': ['Action', 'Adventure', 'Biography', 'Drama', 'History', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTYyMjI4NzYxOF5BMl5BanBnXkFtZTcwNTUwMTc1NA@@._V1_.jpg',
 'keywords': 'arena,gladiator,warrior,sex,female nudity',
 'name': 'Spartacus: Gods of the Arena',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A preview trailer for the Starz original series '
                             '"Spartacus: Gods of the Arena," premiering '
                             'January 21, 2011.',
              'embedUrl': '/video/imdb/vi3829700889',
              'name': 'Spartacus: Gods of the Arena',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTc2NDQwNTg3OF5BMl5BanBnXkFtZTcwNjk4NjExNA@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTc2NDQwNTg3OF5BMl5BanBnXkFtZTcwNjk4NjExNA@@._V1_.jpg',
              'uploadDate': '2010-11-20T13:01:34Z'}],
 'url': '/title/tt1758429/'}