{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Suits',
 'EntryURL': 'https://www.imdb.com/title/tt1632701',
 'Entry_json': 'Favorites/TV/snapshot/Suits/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Suits/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Suits/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gabriel Macht',
            'url': '/name/nm0532683/'},
           {'@type': 'Person',
            'name': 'Patrick J. Adams',
            'url': '/name/nm1140666/'},
           {'@type': 'Person',
            'name': 'Meghan Markle',
            'url': '/name/nm1620783/'},
           {'@type': 'Person',
            'name': 'Sarah Rafferty',
            'url': '/name/nm1423048/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 348226,
                      'ratingValue': '8.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Aaron Korsh',
              'url': '/name/nm0466689/'},
             {'@type': 'Organization', 'url': '/company/co0035615/'},
             {'@type': 'Organization', 'url': '/company/co0242101/'},
             {'@type': 'Organization', 'url': '/company/co0177234/'}],
 'datePublished': '2011-06-23',
 'description': 'Suits is a TV series starring Gabriel Macht, Patrick J. '
                'Adams, and Meghan Markle. On the run from a drug deal gone '
                'bad, brilliant college dropout Mike Ross, finds himself '
                "working with Harvey Specter, one of New York City's best...",
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNmVmMmM5ZmItZDg0OC00NTFiLWIxNzctZjNmYTY5OTU3ZWU3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'lawyer,photographic memory,paralegal,law firm,new york city',
 'name': 'Suits',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Watch the latest teaser from the new season of '
                             '"Suits"!',
              'embedUrl': '/video/imdb/vi1035774745',
              'name': 'TCA Reel',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTkxODI2NzY3NV5BMl5BanBnXkFtZTgwODg3Nzk5MDE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTkxODI2NzY3NV5BMl5BanBnXkFtZTgwODg3Nzk5MDE@._V1_.jpg',
              'uploadDate': '2014-01-19T10:23:12Z'}],
 'url': '/title/tt1632701/'}