{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Jane-The-Virgin',
 'EntryURL': 'https://www.imdb.com/title/tt3566726',
 'Entry_json': 'Favorites/TV/snapshot/Jane-The-Virgin/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Jane-The-Virgin/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Jane-The-Virgin/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gina Rodriguez',
            'url': '/name/nm1752221/'},
           {'@type': 'Person',
            'name': 'Andrea Navedo',
            'url': '/name/nm0623085/'},
           {'@type': 'Person',
            'name': 'Yael Grobglas',
            'url': '/name/nm4141803/'},
           {'@type': 'Person',
            'name': 'Ivonne Coll',
            'url': '/name/nm0171583/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 35979,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Jennie Snyder Urman',
              'url': '/name/nm1646565/'},
             {'@type': 'Organization', 'url': '/company/co0277790/'},
             {'@type': 'Organization', 'url': '/company/co0484523/'},
             {'@type': 'Organization', 'url': '/company/co0287554/'},
             {'@type': 'Organization', 'url': '/company/co0274041/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'}],
 'datePublished': '2014-10-13',
 'description': 'Jane the Virgin is a TV series starring Gina Rodriguez, '
                'Andrea Navedo, and Yael Grobglas. A young, devout Catholic '
                'woman discovers that she was accidentally artificially '
                'inseminated.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjUxMDEzNTYyN15BMl5BanBnXkFtZTgwMjQyMzg1NzM@._V1_.jpg',
 'keywords': 'telenovela,miami florida,virginity,pregnant virgin,lesbian '
             'affair',
 'name': 'Jane the Virgin',
 'trailer': [{'@type': 'VideoObject',
              'description': "Watch the extended trailer for The CW's new "
                             'series "Jane the Virgin".',
              'embedUrl': '/video/imdb/vi2071964953',
              'name': 'Extended Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODYyMDM0MzE1OV5BMl5BanBnXkFtZTgwOTU1ODYyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODYyMDM0MzE1OV5BMl5BanBnXkFtZTgwOTU1ODYyMzE@._V1_.jpg',
              'uploadDate': '2014-05-29T12:54:34Z'}],
 'url': '/title/tt3566726/'}