{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Books/snapshot/The-Great-Hunt',
 'EntryURL': 'https://www.goodreads.com/book/show/233649.The_Great_Hunt',
 'Entry_json': 'Favorites/Books/snapshot/The-Great-Hunt/entry.json',
 'Entry_py': 'Favorites/Books/snapshot/The-Great-Hunt/info.py',
 'Entry_thumb': 'Favorites/Books/snapshot/The-Great-Hunt/thumb.jpg',
 'authors': [{'id': '6252',
              'image_url': '\n'
                           'https://images.gr-assets.com/authors/1538507642p5/6252.jpg\n',
              'link': 'https://www.goodreads.com/author/show/6252.Robert_Jordan',
              'name': 'Robert Jordan',
              'role': None,
              'small_image_url': '\n'
                                 'https://images.gr-assets.com/authors/1538507642p2/6252.jpg\n'}],
 'description': 'The Wheel of Time turns and Ages come and pass. What was, '
                'what will be, and what is, may yet fall under the Shadow.<br '
                '/><br /><i>Let the Dragon ride again on the winds of '
                'time.</i>',
 'edition_information': None,
 'format': 'Mass Market Paperback',
 'id': '233649',
 'image_url': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
 'isbn': '0812517725',
 'isbn13': '9780812517729',
 'large_image_url': None,
 'link': 'https://www.goodreads.com/book/show/233649.The_Great_Hunt',
 'num_pages': '705',
 'publication_day': '15',
 'publication_month': '10',
 'publication_year': '1991',
 'published': '1991',
 'publisher': 'Tor Books',
 'small_image_url': 'https://s.gr-assets.com/assets/nophoto/book/50x75-a91bf249278a81aabab721ef782c4a74.png',
 'title': 'The Great Hunt (The Wheel of Time, #2)',
 'title_without_series': 'The Great Hunt',
 'uri': 'kca://book/amzn1.gr.book.v1.oZN1kanobvP9C4naD4sT6Q',
 'work': '  '}