{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Dallas-Buyers-Club',
 'EntryURL': 'https://www.imdb.com/title/tt0790636',
 'Entry_json': 'Favorites/Movies/snapshot/Dallas-Buyers-Club/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Dallas-Buyers-Club/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Dallas-Buyers-Club/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Matthew McConaughey',
            'url': '/name/nm0000190/'},
           {'@type': 'Person',
            'name': 'Jennifer Garner',
            'url': '/name/nm0004950/'},
           {'@type': 'Person', 'name': 'Jared Leto', 'url': '/name/nm0001467/'},
           {'@type': 'Person',
            'name': 'Steve Zahn',
            'url': '/name/nm0001872/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 425020,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Craig Borten',
              'url': '/name/nm1258965/'},
             {'@type': 'Person',
              'name': 'Melisa Wallack',
              'url': '/name/nm2214893/'},
             {'@type': 'Organization', 'url': '/company/co0398657/'},
             {'@type': 'Organization', 'url': '/company/co0179337/'},
             {'@type': 'Organization', 'url': '/company/co0163926/'},
             {'@type': 'Organization', 'url': '/company/co0388064/'},
             {'@type': 'Organization', 'url': '/company/co0490919/'},
             {'@type': 'Organization', 'url': '/company/co0583791/'}],
 'datePublished': '2013-11-22',
 'description': 'Dallas Buyers Club is a movie starring Matthew McConaughey, '
                'Jennifer Garner, and Jared Leto. In 1985 Dallas, electrician '
                'and hustler Ron Woodroof works around the system to help AIDS '
                'patients get the medication they need after he is...',
 'director': {'@type': 'Person',
              'name': 'Jean-Marc Vallée',
              'url': '/name/nm0885249/'},
 'duration': 'PT1H57M',
 'genre': ['Biography', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTYwMTA4MzgyNF5BMl5BanBnXkFtZTgwMjEyMjE0MDE@._V1_.jpg',
 'keywords': 'hiv,gay community,homophobia,drugs,hiv positive',
 'name': 'Dallas Buyers Club',
 'trailer': {'@type': 'VideoObject',
             'embedUrl': '/video/imdb/vi2069674777',
             'name': 'Awards Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZmY5YjFhZGUtNzZlZC00OTBmLWJlZGEtOWFlNWE2OTZmMzJiXkEyXkFqcGdeQXJoYW5uYWg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZmY5YjFhZGUtNzZlZC00OTBmLWJlZGEtOWFlNWE2OTZmMzJiXkEyXkFqcGdeQXJoYW5uYWg@._V1_.jpg',
             'uploadDate': '2018-09-14T21:01:56Z'},
 'url': '/title/tt0790636/'}