{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Memento',
 'EntryURL': 'https://www.imdb.com/title/tt0209144',
 'Entry_json': 'Favorites/Movies/snapshot/Memento/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Memento/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Memento/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Guy Pearce', 'url': '/name/nm0001602/'},
           {'@type': 'Person',
            'name': 'Carrie-Anne Moss',
            'url': '/name/nm0005251/'},
           {'@type': 'Person',
            'name': 'Joe Pantoliano',
            'url': '/name/nm0001592/'},
           {'@type': 'Person',
            'name': 'Mark Boone Junior',
            'url': '/name/nm0095478/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1085725,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
             {'@type': 'Person',
              'name': 'Jonathan Nolan',
              'url': '/name/nm0634300/'},
             {'@type': 'Organization', 'url': '/company/co0082027/'},
             {'@type': 'Organization', 'url': '/company/co0050544/'},
             {'@type': 'Organization', 'url': '/company/co0156819/'},
             {'@type': 'Organization', 'url': '/company/co0046206/'}],
 'datePublished': '2000-10-11',
 'description': 'Memento is a movie starring Guy Pearce, Carrie-Anne Moss, and '
                'Joe Pantoliano. A man with short-term memory loss attempts to '
                "track down his wife's murderer.",
 'director': {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
 'duration': 'PT1H53M',
 'genre': ['Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'memory,hidden truth,short term memory loss,telephone,insulin '
             'overdose',
 'name': 'Memento',
 'trailer': {'@type': 'VideoObject',
             'description': 'Official Trailer',
             'embedUrl': '/video/imdb/vi3220356889',
             'name': 'Memento',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODhmZDI0MWEtNWIzOS00YjBjLWE0YjgtYzdlOTY4MGQ0N2VlXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODhmZDI0MWEtNWIzOS00YjBjLWE0YjgtYzdlOTY4MGQ0N2VlXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
             'uploadDate': '2019-10-11T17:10:11Z'},
 'url': '/title/tt0209144/'}