{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Brain-Hack',
 'EntryURL': 'https://www.imdb.com/title/tt3704676',
 'Entry_json': 'Favorites/Movies/snapshot/The-Brain-Hack/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Brain-Hack/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Brain-Hack/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Edward Franklin',
            'url': '/name/nm3819392/'},
           {'@type': 'Person',
            'name': 'Alexander Owen',
            'url': '/name/nm4998470/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 680,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Joseph White',
              'url': '/name/nm2343646/'},
             {'@type': 'Organization', 'url': '/company/co0527980/'}],
 'datePublished': '2015-02-11',
 'description': 'The Brain Hack is a short starring Edward Franklin and '
                'Alexander Owen. A metaphysical thriller for the digital '
                'generation.',
 'director': {'@type': 'Person',
              'name': 'Joseph White',
              'url': '/name/nm2343646/'},
 'duration': 'PT20M',
 'genre': ['Short', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg1NzEzNDY5OF5BMl5BanBnXkFtZTgwMTkyMDMwNTE@._V1_.jpg',
 'keywords': 'low budget short,surrealism,paranoid '
             'schizophrenia,conspiracy,numeric code',
 'name': 'The Brain Hack',
 'url': '/title/tt3704676/'}