{'Actors': [],
 'Added': '2015-02-19',
 'Countries': ['UK'],
 'Description': '\n'
                'The Brain Hack: A metaphysical thriller for the digital '
                'generation. ',
 'Director': ['Joseph White'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Brain-Hack',
 'EntryURL': 'https://www.imdb.com/title/tt3704676',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Brain-Hack/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Brain-Hack/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Brain-Hack/info.py',
 'Genres': ['Short'],
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.09/5',
             'RT': 'N/A',
             'Votes': '22'},
 'Released': '2014-06-04',
 'Runtime': '20 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2758243_The_Brain_Hack_1969_24.jpg',
 'Title': 'The-Brain-Hack'}