{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-Vi',
 'EntryURL': 'https://rawg.io/games/final-fantasy-vi',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-Vi/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-Vi/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-Vi/thumb.jpg',
 'added': 643,
 'background_image': 'https://media.rawg.io/media/games/98c/98c87b286cd2a2ba942167df384a9bd3.jpg',
 'developers': ['Sony Interactive Entertainment', 'Square Enix', 'Square'],
 'genres': ['RPG'],
 'name': 'FINAL FANTASY VI',
 'platforms': ['iOS',
               'Android',
               'PC',
               'PlayStation 3',
               'Wii',
               'Wii U',
               'SNES',
               'PlayStation',
               'Game Boy Advance',
               'PSP',
               'PS Vita'],
 'publishers': ['Electronic Arts',
                'Square Enix',
                'Sony Computer Entertainment',
                'Nintendo',
                'Square'],
 'released': '1994-04-02',
 'slug': 'final-fantasy-vi'}