{'Actors': ['Brent Anderson&tv',
            'David Hoflin&tv',
            'Emily Warfield&tv',
            'Felicity Huffman&tv',
            'Timothy Hutton&tv',
            'Todd Terry&tv'],
 'Added': '2015-03-28',
 'Countries': [],
 'Description': '\n'
                'American Crime (2015): The lives of the participants in a '
                'trial with significant racial motives are forever changed '
                'during the legal process. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//American-Crime-2015',
 'EntryURL': 'http://www.imdb.com/title/tt3488298',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//American-Crime-2015/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//American-Crime-2015/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//American-Crime-2015/info.py',
 'Genres': ['Crime&tv', 'Drama&tv'],
 'IMDB': 'http://www.imdb.com/title/tt3488298',
 'PrimeWire': 'http://www.primewire.ag/tv-2759191-American-Crime-2015',
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.85/5',
             'RT': 'N/A',
             'Votes': '89'},
 'Released': '2015-03-05',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2759191_American_Crime_2015_2015_48.jpg',
 'Title': 'American-Crime-2015'}