{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-Viii',
 'EntryURL': 'https://rawg.io/games/final-fantasy-viii',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-Viii/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-Viii/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-Viii/thumb.jpg',
 'added': 1040,
 'background_image': 'https://media.rawg.io/media/games/f77/f77510051b6a61decc35c5257193fc9e.jpg',
 'developers': ['Square'],
 'genres': ['RPG'],
 'name': 'FINAL FANTASY VIII',
 'platforms': ['PC',
               'PlayStation 4',
               'PlayStation 3',
               'PSP',
               'PS Vita',
               'PlayStation'],
 'publishers': ['Square Enix',
                'Eidos Interactive',
                'Square',
                'SCE Australia',
                'Microsoft Studios'],
 'released': '1999-01-11',
 'slug': 'final-fantasy-viii'}