{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Halo-Combat-Evolved',
 'EntryURL': 'https://rawg.io/games/halo-combat-evolved',
 'Entry_json': 'Favorites/Games/snapshot/Halo-Combat-Evolved/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Halo-Combat-Evolved/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Halo-Combat-Evolved/thumb.jpg',
 'added': 371,
 'background_image': 'https://media.rawg.io/media/games/abf/abffd94ed6fe34027c720bee593c06d2.jpg',
 'developers': ['Bungie, Inc.', 'Gearbox Software'],
 'genres': ['Action', 'Shooter', 'Adventure'],
 'name': 'Halo: Combat Evolved',
 'platforms': ['PC', 'macOS', 'Xbox'],
 'publishers': ['Microsoft Studios'],
 'released': '2001-11-15',
 'slug': 'halo-combat-evolved'}