{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Fable-2',
 'EntryURL': 'https://rawg.io/games/fable-2',
 'Entry_json': 'Favorites/Games/snapshot/Fable-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Fable-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Fable-2/thumb.jpg',
 'added': 57,
 'background_image': 'https://media.rawg.io/media/screenshots/686/6861d78c6705ac95094f528e35de3106.jpg',
 'developers': [],
 'genres': ['Action', 'Adventure', 'RPG'],
 'name': 'Fable',
 'platforms': ['macOS', 'Xbox', 'PC'],
 'publishers': [],
 'released': '2004-09-14',
 'slug': 'fable-2'}