{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Blood-Drive',
 'EntryURL': 'https://www.imdb.com/title/tt4898282',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Blood-Drive/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Blood-Drive/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Blood-Drive/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Alan Ritchson',
            'url': '/name/nm2024927/'},
           {'@type': 'Person',
            'name': 'Christina Ochoa',
            'url': '/name/nm3079593/'},
           {'@type': 'Person',
            'name': 'Thomas Dominique',
            'url': '/name/nm8025305/'},
           {'@type': 'Person',
            'name': 'Marama Corlett',
            'url': '/name/nm3744128/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 5367,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': {'@type': 'Person',
             'name': 'James Roland',
             'url': '/name/nm1078938/'},
 'datePublished': '2017-06-14',
 'description': 'Blood Drive is a TV series starring Alan Ritchson, Christina '
                'Ochoa, and Thomas Dominique. In a dystopian alternate 1999, a '
                'former cop is forced to take part in a death race in which '
                'cars run on human blood as fuel.',
 'genre': ['Action', 'Adventure', 'Comedy', 'Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BY2E1NmRjNDctOGYwZC00MWU2LWI3MmYtNTRiOGY2OTgzM2JhXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg',
 'keywords': 'grindhouse series,dystopia,exploding head,ex cop,car racing',
 'name': 'Blood Drive',
 'trailer': {'@type': 'VideoObject',
             'description': 'Blood Drive: Booby Traps',
             'embedUrl': '/video/imdb/vi1479392537',
             'name': 'Blood Drive: Booby Traps',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODE4ZjRiMjQtOTUzYS00OGY1LWIxZjQtYzVhZGRjOTZkMDA2XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODE4ZjRiMjQtOTUzYS00OGY1LWIxZjQtYzVhZGRjOTZkMDA2XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-04-10T22:07:17Z'},
 'url': '/title/tt4898282/'}