{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff',
 'EntryURL': 'https://www.imdb.com/title/tt0119094',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Travolta',
            'url': '/name/nm0000237/'},
           {'@type': 'Person',
            'name': 'Nicolas Cage',
            'url': '/name/nm0000115/'},
           {'@type': 'Person', 'name': 'Joan Allen', 'url': '/name/nm0000260/'},
           {'@type': 'Person',
            'name': 'Alessandro Nivola',
            'url': '/name/nm0005273/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 340373,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mike Werb',
              'url': '/name/nm0108273/'},
             {'@type': 'Person',
              'name': 'Michael Colleary',
              'url': '/name/nm0171718/'},
             {'@type': 'Organization', 'url': '/company/co0011800/'},
             {'@type': 'Organization', 'url': '/company/co0049348/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0020967/'},
             {'@type': 'Organization', 'url': '/company/co0041998/'}],
 'datePublished': '1997-06-27',
 'description': 'Face/Off is a movie starring John Travolta, Nicolas Cage, and '
                'Joan Allen. In order to foil a terrorist plot, an FBI agent '
                'undergoes facial transplant surgery and assumes the identity '
                'of a criminal mastermind, who murdered his only...',
 'director': {'@type': 'Person', 'name': 'John Woo', 'url': '/name/nm0000247/'},
 'duration': 'PT2H18M',
 'genre': ['Action', 'Crime', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzFjNzIxMmEtMzY5NS00YTgzLTkwYWEtN2FjMmY0NmNkZWY3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'face transplant,death of child,girl in panties,face ripped '
             'off,severed face',
 'name': 'Face/Off',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi3188700185',
             'name': 'Face/Off',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTAxMWNjYzktYTVmYy00YjJjLTlhMzUtYWVhMmJjZjlkZGU0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTAxMWNjYzktYTVmYy00YjJjLTlhMzUtYWVhMmJjZjlkZGU0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2016-06-03T21:20:19Z'},
 'url': '/title/tt0119094/'}