{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff',
 'EntryURL': 'https://www.imdb.com/title/tt0119094',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/FaceOff/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Travolta',
            'url': '/name/nm0000237/'},
           {'@type': 'Person',
            'name': 'Nicolas Cage',
            'url': '/name/nm0000115/'},
           {'@type': 'Person', 'name': 'Joan Allen', 'url': '/name/nm0000260/'},
           {'@type': 'Person',
            'name': 'Alessandro Nivola',
            'url': '/name/nm0005273/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 340349,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mike Werb',
              'url': '/name/nm0108273/'},
             {'@type': 'Person',
              'name': 'Michael Colleary',
              'url': '/name/nm0171718/'},
             {'@type': 'Organization', 'url': '/company/co0011800/'},
             {'@type': 'Organization', 'url': '/company/co0049348/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0020967/'},
             {'@type': 'Organization', 'url': '/company/co0041998/'}],
 'datePublished': '1997-06-27',
 'description': 'Face/Off is a movie starring John Travolta, Nicolas Cage, and '
                'Joan Allen. In order to foil a terrorist plot, an FBI agent '
                'undergoes facial transplant surgery and assumes the identity '
                'of a criminal mastermind, who murdered his only...',
 'director': {'@type': 'Person', 'name': 'John Woo', 'url': '/name/nm0000247/'},
 'duration': 'PT2H18M',
 'genre': ['Action', 'Crime', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzFjNzIxMmEtMzY5NS00YTgzLTkwYWEtN2FjMmY0NmNkZWY3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'face transplant,death of child,girl in panties,face ripped '
             'off,severed face',
 'name': 'Face/Off',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'gatsby2244'},
            'dateCreated': '2005-07-23',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0119094/'},
            'name': 'An   Action Classic  That   Will  Never Lose  Its Appeal',
            'reviewBody': 'I consider John Woo to be one of the greatest '
                          'action movie directors in the world,and "Face/Off" '
                          'proves just that.However,the element that makes '
                          'this film one of the most intense and spectacular '
                          'action movies to ever come from Hollywood is the '
                          'presence of two tremendously talented actors,both '
                          'of whom are my favorites.Yes,when you have John '
                          'Travolta and Nicholas Cage together in a movie ,the '
                          'results are bound to be over the top. John Travolta '
                          'plays Sean Archer,a dedicated FBI agent who '
                          'survived a murder attempt by notorious criminal '
                          'Castor Troy six years ago. However,tragically his '
                          'son died instead of him and since than Archer is '
                          'relentlessly chasing Troy.Nicholas Cage plays '
                          'Troy,and the film begins with a spectacular chase '
                          'where we see the sheer intensity generated by both '
                          'these great actors,and you realize that this is not '
                          'going to be just another action flick. Troy '
                          'escapes,but his younger brother Pollux Troy(played '
                          "by Alessandro Nivola) falls into Archer's "
                          'hands,along with a floppy that contains the '
                          'blueprint for a bomb to be detonated in downtown '
                          'L.A. Pollux refuses to reveal the location of the '
                          'bomb and then a desperate Archer is given an option '
                          'that is so spine-chilling that Archer refuses '
                          'immediately.Realizing soon that he has no other '
                          'choice,he decides to do what he is asked to-to '
                          "exchange his face for Troy's, and what's more,to "
                          'alter his entire physical attributes,so that he can '
                          'go to the prison where his brother is being '
                          'kept,and fool him into believing that he is Troy '
                          'and get the location of the bomb from him.The plan '
                          'seems to work until the moment Castor realizes what '
                          "has happened,puts on Archer's face,and sets out for "
                          "revenge.He fools the FBI,fools Archer's wife and "
                          'sleeps with her and just when one thinks that this '
                          "is too much,the real Archer escapes prison and it's "
                          'payback time. Both Travolta and Cage play their '
                          'roles perfectly,and they do a fantastic job playing '
                          'each other too. The rest of the cast simply fades '
                          'away in comparison,and who cares ? Dominique Swain '
                          "as Archer's rebellious daughter looks good on "
                          "screen-but that's about it.Joan Allen as his wife "
                          "is not too impressive either.Gina Gershon as Troy's "
                          'lover seems much more real in comparison.John Woo '
                          'provides the film with a novel and flawless '
                          'script,and some of the best action sequences ever '
                          'filmed.This film is an absolute must for any action '
                          'fan,and definitely the best Woo ever made.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi3188700185',
             'name': 'Face/Off',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTAxMWNjYzktYTVmYy00YjJjLTlhMzUtYWVhMmJjZjlkZGU0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTAxMWNjYzktYTVmYy00YjJjLTlhMzUtYWVhMmJjZjlkZGU0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2016-06-03T21:20:19Z'},
 'url': '/title/tt0119094/'}