{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-01-19',
 'EntryPath': 'Favorites/TV/snapshot/The-Expanse',
 'EntryURL': 'https://www.imdb.com/title/tt3230854',
 'Entry_json': 'Favorites/TV/snapshot/The-Expanse/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Expanse/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Expanse/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Steven Strait',
            'url': '/name/nm1711829/'},
           {'@type': 'Person', 'name': 'Cas Anvar', 'url': '/name/nm0031679/'},
           {'@type': 'Person',
            'name': 'Dominique Tipper',
            'url': '/name/nm4625680/'},
           {'@type': 'Person',
            'name': 'Wes Chatham',
            'url': '/name/nm1434871/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 93836,
                      'ratingValue': '8.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Mark Fergus',
              'url': '/name/nm1318843/'},
             {'@type': 'Person',
              'name': 'Hawk Ostby',
              'url': '/name/nm1319757/'},
             {'@type': 'Organization', 'url': '/company/co0054452/'},
             {'@type': 'Organization', 'url': '/company/co0007038/'}],
 'datePublished': '2015-11-23',
 'description': 'The Expanse is a TV series starring Steven Strait, Cas Anvar, '
                'and Dominique Tipper. A police detective in the asteroid '
                'belt, the first officer of an interplanetary ice freighter, '
                'and an earth-bound United Nations executive slowly...',
 'genre': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNGJlNzU1OTEtZDRmNy00YTM3LTgxNDgtMWEwNTg2OGI1YzYwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'asteroid belt,false flag operation,space opera,dead '
             'girlfriend,shootout',
 'name': 'The Expanse',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi4290952985',
              'name': 'Season 4 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMDRkZmU4N2MtNDFmOC00ZGE0LWFiNDctMzQ5NzUxN2Q1MTYzXkEyXkFqcGdeQWpnYW1i._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMDRkZmU4N2MtNDFmOC00ZGE0LWFiNDctMzQ5NzUxN2Q1MTYzXkEyXkFqcGdeQWpnYW1i._V1_.jpg',
              'uploadDate': '2019-11-15T19:16:02Z'}],
 'url': '/title/tt3230854/'}