{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Alone-In-The-Dark-The-New-Nightmare',
 'EntryURL': 'https://rawg.io/games/alone-in-the-dark-the-new-nightmare',
 'Entry_json': 'Favorites/Games/snapshot/Alone-In-The-Dark-The-New-Nightmare/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Alone-In-The-Dark-The-New-Nightmare/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Alone-In-The-Dark-The-New-Nightmare/thumb.jpg',
 'added': 204,
 'background_image': 'https://media.rawg.io/media/screenshots/e3b/e3b7053c9ba6467e28c69fe4b798f5aa.jpg',
 'developers': ['Darkworks',
                'Sony Interactive Entertainment',
                'Spiral House',
                'DarkWorks S.A.',
                'Pocket Studios'],
 'genres': ['Action', 'Adventure'],
 'name': 'Alone in the Dark: The New Nightmare',
 'platforms': ['PC',
               'PlayStation 2',
               'Game Boy Color',
               'Dreamcast',
               'PlayStation',
               'PlayStation 3',
               'PSP'],
 'publishers': ['Atari',
                'THQ Nordic',
                'Infogrames',
                'Infogrames Entertainment'],
 'released': '2001-05-18',
 'slug': 'alone-in-the-dark-the-new-nightmare'}