{'Actors': ['Alister Mazzotti',
            'Amelda Brown',
            'Andy Callaghan',
            'Andy Rashleigh',
            'Ben Miles',
            'Ben Posener',
            'Chad Stahelski',
            'Charles Cork',
            'Chris Wilson',
            'Christopher Fosh',
            'David Decio',
            'David Leitch',
            'David Merheb',
            'Eamon Geoghegan',
            'Eddie Marsan',
            'Forbes KB',
            'Guy Henry',
            'Hugo Weaving',
            'Ian Burfield',
            'Imogen Poots',
            'Jo&#xE3;o Costa Menezes',
            'John Hurt',
            'John Ringham',
            'John Standing',
            'Julie Brown',
            'Juliet Howland',
            'Malcolm Sinclair',
            'Martin McGlade',
            'Martin Savage',
            'Matt Wilkinson',
            'Megan Gay',
            'Michael Simkins',
            'Natalie Portman',
            'Natasha Wightman',
            'Nicolas de Pruyssenaere',
            'Norman Campbell Rees',
            'Richard Laing',
            'Roderic Culver',
            'Roger Allam',
            'Rupert Graves',
            'Selina Giles',
            'Simon Newby',
            'Sinead Cusack',
            'Stephen Fry',
            'Stephen Rea',
            'Tim Pigott-Smith',
            'William Tapley'],
 'Added': '2013-02-19',
 'Countries': ['USA', 'UK', 'Germany'],
 'Description': '\r\n'
                '              V for Vendetta: A shadowy freedom fighter known '
                'only as "V" uses terrorist tactics to fight against his '
                'totalitarian society. Upon rescuing a girl from the secret '
                'police, he also finds his best chance at having an '
                'ally.            ',
 'Director': ['James McTeigue'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/V-for-Vendetta',
 'EntryURL': 'https://www.imdb.com/title/tt0434409',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/V-for-Vendetta/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/V-for-Vendetta/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/V-for-Vendetta/info.py',
 'Genres': ['Action', 'Thriller', 'Sci-Fi'],
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': '62%',
             'PrimeWire': '4.48/5',
             'RT': '73%',
             'Votes': '3871'},
 'Released': '2006-03-17',
 'Runtime': '132 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/626_V_for_Vendetta_2006.jpg',
 'Title': 'V-for-Vendetta'}