{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/V-for-Vendetta',
 'EntryURL': 'https://www.imdb.com/title/tt0434409',
 'Entry_json': 'Favorites/Movies/snapshot/V-for-Vendetta/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/V-for-Vendetta/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/V-for-Vendetta/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Hugo Weaving',
            'url': '/name/nm0915989/'},
           {'@type': 'Person',
            'name': 'Natalie Portman',
            'url': '/name/nm0000204/'},
           {'@type': 'Person',
            'name': 'Rupert Graves',
            'url': '/name/nm0001291/'},
           {'@type': 'Person',
            'name': 'Stephen Rea',
            'url': '/name/nm0001653/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 998109,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Lilly Wachowski',
              'url': '/name/nm0905152/'},
             {'@type': 'Person',
              'name': 'Lana Wachowski',
              'url': '/name/nm0905154/'},
             {'@type': 'Person',
              'name': 'David Lloyd',
              'url': '/name/nm2331222/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0167271/'},
             {'@type': 'Organization', 'url': '/company/co0019968/'},
             {'@type': 'Organization', 'url': '/company/co0167243/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0053177/'},
             {'@type': 'Organization', 'url': '/company/co0130575/'},
             {'@type': 'Organization', 'url': '/company/co0038332/'}],
 'datePublished': '2006-03-15',
 'description': 'V for Vendetta is a movie starring Hugo Weaving, Natalie '
                'Portman, and Rupert Graves. In a future British tyranny, a '
                'shadowy freedom fighter, known only by the alias of "V", '
                'plots to overthrow it with the help of a young woman.',
 'director': [{'@type': 'Person',
               'name': 'James McTeigue',
               'url': '/name/nm0574625/'}],
 'duration': 'PT2H12M',
 'genre': ['Action', 'Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_.jpg',
 'keywords': 'fascist,freedom,revolution,dystopia,right wing government',
 'name': 'V for Vendetta',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for V For Vendetta',
              'embedUrl': '/video/imdb/vi4276093209',
              'name': 'V for Vendetta',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZWVkNmQ2ZjktZTU1My00ZTIyLWIzMTctZmEzNjQ0NTM5YzM2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZWVkNmQ2ZjktZTU1My00ZTIyLWIzMTctZmEzNjQ0NTM5YzM2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T17:38:16Z'}],
 'url': '/title/tt0434409/'}