{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-12',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pontypool',
 'EntryURL': 'https://www.imdb.com/title/tt1226681',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pontypool/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pontypool/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pontypool/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Stephen McHattie',
            'url': '/name/nm0565569/'},
           {'@type': 'Person', 'name': 'Lisa Houle', 'url': '/name/nm0396515/'},
           {'@type': 'Person',
            'name': 'Georgina Reilly',
            'url': '/name/nm2468050/'},
           {'@type': 'Person',
            'name': 'Hrant Alianak',
            'url': '/name/nm0019528/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 28208,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Tony Burgess',
              'url': '/name/nm2997229/'},
             {'@type': 'Person',
              'name': 'Tony Burgess',
              'url': '/name/nm2997229/'},
             {'@type': 'Organization', 'url': '/company/co0240476/'},
             {'@type': 'Organization', 'url': '/company/co0045689/'}],
 'datePublished': '2009-09-18',
 'description': 'Pontypool is a movie starring Stephen McHattie, Lisa Houle, '
                'and Georgina Reilly. A radio host interprets the possible '
                'outbreak of a deadly virus which infects the small Ontario '
                'town he is stationed in.',
 'director': {'@type': 'Person',
              'name': 'Bruce McDonald',
              'url': '/name/nm0567680/'},
 'duration': 'PT1H33M',
 'genre': ['Fantasy', 'Horror', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNWZkMmNmNGItM2MwNC00YTY2LTk0ZDYtMGM0YjM5Nzk0MjVjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'talk radio,ontario canada,survival,post punk,broadcasting',
 'name': 'Pontypool',
 'trailer': {'@type': 'VideoObject',
             'description': 'A psychological thriller in which a deadly virus '
                            'infects a small Ontario town.',
             'embedUrl': '/video/imdb/vi1386283545',
             'name': 'Pontypool',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2MjMwMDQzNl5BMl5BanBnXkFtZTgwNDI4NDYzMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2MjMwMDQzNl5BMl5BanBnXkFtZTgwNDI4NDYzMzE@._V1_.jpg',
             'uploadDate': '2009-05-06T08:36:36Z'},
 'url': '/title/tt1226681/'}