{'Actors': ['Beatriz Yuste',
            'Boyd Banks',
            'Daniel Fathers',
            'Derek Scott',
            'Diane Gordon',
            'Hrant Alianak',
            'Louis Negin',
            'Rick Roberts',
            'Stephen McHattie'],
 'Added': '2014-09-12',
 'Countries': ['Canada'],
 'Description': '\n'
                'Pontypool: A psychological thriller in which a deadly virus '
                'infects a small Ontario town. ',
 'Director': ['Bruce McDonald'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pontypool',
 'EntryURL': 'http://www.imdb.com/title/tt1226681',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pontypool/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pontypool/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pontypool/info.py',
 'Genres': ['Horror', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt1226681',
 'PrimeWire': 'http://www.primewire.ag/watch-6204-Pontypool',
 'Ratings': {'IMDB': '6.7/10',
             'Metascore': '54%',
             'PrimeWire': '3.79/5',
             'RT': '82%',
             'Votes': '253'},
 'Released': '2008-09-06',
 'Runtime': '93 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/6204_Pontypool_2008.jpg',
 'Title': 'Pontypool'}