<?php
$infoArray = array('Actors' => array('Christa Campbell',
            'Erica Leerhsen',
            'Gary Cole',
            'John Carroll Lynch',
            'Josh Hartnett',
            'Nate Mooney',
            'Radha Mitchell',
            'Robert Wisdom',
            'Ron Ford',
            'Rusty Schwimmer',
            'Sheila Kelley',
            'Suzanne Niles'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => "\nMozart and the Whale: A love story between two savants with Asperger's syndrome, a kind of autism, whose conditions sabotage their budding relationship. ",
 'Director' => array('Petter N&#xE6;ss'),
 'Genres' => array('Drama', 'Comedy', 'Romance'),
 'IMDB' => 'http://www.imdb.com/title/tt0392465',
 'PrimeWire' => 'http://www.primewire.ag/watch-20448-Mozart-and-the-Whale',
 'Ratings' => array('IMDB' => '7.0/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.03/5',
             'RT' => 'N/A',
             'Votes' => '77'),
 'Released' => '2005-09-10',
 'Runtime' => '92 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/20448_Mozart_and_the_Whale_2005.jpg',
 'Title' => 'Mozart-and-the-Whale');
?>