<?php
$infoArray = array('Actors' => array('Alexander Allerson',
            'Ekkehardt Belle',
            'Eugene Roche',
            'Friedrich von Ledebur',
            'Gilmer McCormick',
            'Holly Near',
            'Joan Swift',
            'John Dehner',
            'John Wood',
            'Karl-Otto Alberty',
            'Kevin Conway',
            'Lucille Benson',
            'Michael Sacks',
            'Perry King',
            'Richard Schaal',
            'Richard Stahl',
            'Roberts Blossom',
            'Ron Leibman',
            'Sorrell Booke',
            'Stan Gottlieb',
            'Valerie Perrine'),
 'Added' => '2013-02-23',
 'Countries' => array('USA'),
 'Description' => '\nSlaughterhouse-Five: ',
 'Director' => array('George Roy Hill'),
 'Genres' => array('Drama', 'Comedy', 'Sci-Fi', 'War', 'Fantasy'),
 'IMDB' => 'http://www.imdb.com/title/tt0069280',
 'PrimeWire' => 'http://www.primewire.ag/watch-21038-Slaughterhouse-Five',
 'Ratings' => array('IMDB' => '7.0/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.21/5',
             'RT' => '77%',
             'Votes' => '133'),
 'Released' => '1972-03-15',
 'Runtime' => '104 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/21038_Slaughterhouse_Five_1972.jpg',
 'Title' => 'Slaughterhouse-Five');
?>