apiVersion: v1
kind: Service
metadata:
    name: datascraper-service
spec:
    selector:
        app: php:apache
    volumes:
        protocol: TCP
        port: 80
        targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datascraper-deployment
  labels:
    role: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      labels:
        role: webserver
    spec:
      containers:
      - name: datascraper
        image: httpd
        ports:
        - containerPort: 80