def GetFavoriteTVURL(pages=2):
    return 'https://www.imdb.com/list/ls098367816/?sort=list_order,asc&st_dt=&mode=detail&page=1'
def GetFavoriteMoviesURL(pages=8):
    return 'https://www.imdb.com/list/ls098333584/?sort=list_order,asc&st_dt=&mode=detail&page=1'
def GetIMDBURL():
    return 'http://www.imdb.com/name/nm4807696'
def GetGitHubURL():
    return 'http://github.com/MadisonAster'
def GetCodeWarsURL():
    return 'https://www.codewars.com/users/MadisonAster'
def GetLinkedInURL():
    return 'https://www.linkedin.com/in/madisonaster/'