<?php
$infoArray = array('Actors' => array('Alexa Vega',
            'Amber Heard',
            'Antonio Banderas',
            'Charlie Sheen',
            'Cuba Gooding Jr',
            'Danny Trejo',
            'Edward James Olmos',
            'Jessica Alba',
            'Mel Gibson',
            'Michelle Rodriguez',
            'Vanessa Hudgens',
            'William Sadler'),
 'Added' => '2013-11-13',
 'Countries' => array('Russia', 'USA'),
 'Description' => '\nMachete Kills: The U.S. government recruits Machete to battle his way through Mexico in order to take down an arms dealer who looks to launch a weapon into space. ',
 'Director' => array('Robert Rodriguez'),
 'Genres' => array('Action', 'Crime', 'Thriller'),
 'IMDB' => 'http://www.imdb.com/title/tt2002718',
 'PrimeWire' => 'http://www.primewire.ag/watch-2742321-Machete-Kills',
 'Ratings' => array('IMDB' => '5.7/10',
             'Metascore' => '41%',
             'PrimeWire' => '3.43/5',
             'RT' => '29%',
             'Votes' => '496'),
 'Released' => '2013-10-11',
 'Runtime' => '107 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2742321_Machete_Kills_2013.jpg',
 'Title' => 'Machete-Kills');
?>