{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Vice-News-Tonight',
 'EntryURL': 'https://www.imdb.com/title/tt6329790',
 'Entry_json': 'Favorites/TV/snapshot/Vice-News-Tonight/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Vice-News-Tonight/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Vice-News-Tonight/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Arielle Duhaime-Ross',
            'url': '/name/nm9906955/'},
           {'@type': 'Person',
            'name': 'Isobel Yeung',
            'url': '/name/nm6763235/'},
           {'@type': 'Person',
            'name': 'Michael C. Moynihan',
            'url': '/name/nm3389537/'},
           {'@type': 'Person',
            'name': 'Daniel Hernandez',
            'url': '/name/nm5993607/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 371,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': {'@type': 'Organization', 'url': '/company/co0008693/'},
 'datePublished': '2016-10-10',
 'description': 'Vice News Tonight is a TV series starring Arielle '
                'Duhaime-Ross, Isobel Yeung, and Michael C. Moynihan. A '
                'nightly news show Monday through Friday. Discusses current '
                'global issues and various news topics.',
 'genre': 'News',
 'image': 'https://m.media-amazon.com/images/M/MV5BY2I5OGQ1ZWMtNjgxNi00ZjQ4LTk3YmQtZGYzMGNkMDkwNjllXkEyXkFqcGdeQXVyNjMxMDgyNzQ@._V1_.jpg',
 'keywords': 'show',
 'name': 'Vice News Tonight',
 'url': '/title/tt6329790/'}