{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice-News-Tonight',
 'EntryURL': 'https://www.imdb.com/title/tt6329790',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice-News-Tonight/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice-News-Tonight/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice-News-Tonight/info.py',
 'Title': 'Vice News Tonight',
 'actor': [{'@type': 'Person',
            'name': 'Arielle Duhaime-Ross',
            'url': '/name/nm9906955/'},
           {'@type': 'Person',
            'name': 'Isobel Yeung',
            'url': '/name/nm6763235/'},
           {'@type': 'Person',
            'name': 'Michael C. Moynihan',
            'url': '/name/nm3389537/'},
           {'@type': 'Person',
            'name': 'Daniel Hernandez',
            'url': '/name/nm5993607/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 369,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': {'@type': 'Organization', 'url': '/company/co0008693/'},
 'datePublished': '2016-10-10',
 'description': 'Vice News Tonight is a TV series starring Arielle '
                'Duhaime-Ross, Isobel Yeung, and Michael C. Moynihan. A '
                'nightly news show Monday through Friday. Discusses current '
                'global issues and various news topics.',
 'genre': 'News',
 'image': 'https://m.media-amazon.com/images/M/MV5BY2I5OGQ1ZWMtNjgxNi00ZjQ4LTk3YmQtZGYzMGNkMDkwNjllXkEyXkFqcGdeQXVyNjMxMDgyNzQ@._V1_.jpg',
 'keywords': 'show',
 'name': 'Vice News Tonight',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'radioconductor'},
            'dateCreated': '2019-08-01',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt6329790/'},
            'name': 'VICE News',
            'reviewBody': 'Iowa residents (right side of history-ers)* Check '
                          'out my Instagram post about what the Dixie line '
                          'actually is/was....',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '10',
                             'worstRating': '1'}},
 'url': '/title/tt6329790/'}