{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Lord-of-War',
 'EntryURL': 'https://www.imdb.com/title/tt0399295',
 'Entry_json': 'Favorites/Movies/snapshot/Lord-of-War/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Lord-of-War/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Lord-of-War/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Nicolas Cage',
            'url': '/name/nm0000115/'},
           {'@type': 'Person',
            'name': 'Ethan Hawke',
            'url': '/name/nm0000160/'},
           {'@type': 'Person', 'name': 'Jared Leto', 'url': '/name/nm0001467/'},
           {'@type': 'Person',
            'name': 'Bridget Moynahan',
            'url': '/name/nm0005256/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 289176,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Niccol',
              'url': '/name/nm0629272/'},
             {'@type': 'Organization', 'url': '/company/co0120397/'},
             {'@type': 'Organization', 'url': '/company/co0116514/'},
             {'@type': 'Organization', 'url': '/company/co0094902/'},
             {'@type': 'Organization', 'url': '/company/co0010750/'},
             {'@type': 'Organization', 'url': '/company/co0142412/'},
             {'@type': 'Organization', 'url': '/company/co0184307/'},
             {'@type': 'Organization', 'url': '/company/co0112971/'},
             {'@type': 'Organization', 'url': '/company/co0093560/'},
             {'@type': 'Organization', 'url': '/company/co0007143/'}],
 'datePublished': '2005-09-16',
 'description': 'Lord of War is a movie starring Nicolas Cage, Ethan Hawke, '
                'and Jared Leto. An arms dealer confronts the morality of his '
                'work as he is being chased by an INTERPOL Agent.',
 'director': [{'@type': 'Person',
               'name': 'Andrew Niccol',
               'url': '/name/nm0629272/'}],
 'duration': 'PT2H2M',
 'genre': ['Action', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTYzZWE3MDAtZjZkMi00MzhlLTlhZDUtNmI2Zjg3OWVlZWI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
 'keywords': 'arms dealer,gunrunner,prostitution,drug addiction,rehab',
 'name': 'Lord of War',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for this action film starring Nicholas '
                             'Cage as a gun runner',
              'embedUrl': '/video/imdb/vi3548774937',
              'name': 'Lord of War: Blu-Ray',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTQ2MzNhZGYtN2YyOC00ODhiLTk0NmYtZWE2OGI1ZmQxMTczXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTQ2MzNhZGYtN2YyOC00ODhiLTk0NmYtZWE2OGI1ZmQxMTczXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2009-06-03T04:07:13Z'}],
 'url': '/title/tt0399295/'}