{'Actors': ['Bridget Moynahan',
            'Donald Sutherland',
            'Eamonn Walker',
            'Ethan Hawke',
            'Ian Holm',
            'Inna Swann',
            'Jared Burke',
            'Jared Leto',
            'Jean-Michel Richaud',
            'Jeremy Crutchley',
            'Jerry Mofokeng',
            'Mikhail Gorbachev',
            'Nicolas Cage',
            'Sammi Rotibi',
            'Stephen Hughes',
            'Steve J Termath',
            'Steve Ruge',
            'Tony Caprari',
            'Vadim Dobrin',
            'Yevgeni Lazarev'],
 'Added': '2013-02-19',
 'Countries': ['France', 'USA', 'Germany'],
 'Description': '\n'
                'Lord of War: An arms dealer confronts the morality of his '
                'work as he is being chased by an Interpol agent. ',
 'Director': ['Andrew Niccol'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Lord-of-War',
 'EntryURL': 'https://www.imdb.com/title/tt0399295',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Lord-of-War/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Lord-of-War/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Lord-of-War/info.py',
 'Genres': ['Drama', 'Thriller', 'Crime'],
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': '62%',
             'PrimeWire': '4.26/5',
             'RT': '61%',
             'Votes': '661'},
 'Released': '2005-09-16',
 'Runtime': '122 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/746_Lord_of_War_2005.jpg',
 'Title': 'Lord-of-War'}