{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/12-Angry-Men',
 'EntryURL': 'https://www.imdb.com/title/tt0050083',
 'Entry_json': 'Favorites/Movies/snapshot/12-Angry-Men/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/12-Angry-Men/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/12-Angry-Men/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Henry Fonda',
            'url': '/name/nm0000020/'},
           {'@type': 'Person',
            'name': 'Lee J. Cobb',
            'url': '/name/nm0002011/'},
           {'@type': 'Person',
            'name': 'Martin Balsam',
            'url': '/name/nm0000842/'},
           {'@type': 'Person',
            'name': 'John Fiedler',
            'url': '/name/nm0275835/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 657600,
                      'ratingValue': '8.9',
                      'worstRating': '1.0'}],
 'contentRating': 'Approved',
 'creator': [{'@type': 'Person',
              'name': 'Reginald Rose',
              'url': '/name/nm0741627/'},
             {'@type': 'Person',
              'name': 'Reginald Rose',
              'url': '/name/nm0741627/'},
             {'@type': 'Organization', 'url': '/company/co0032902/'}],
 'datePublished': '1957-04-10',
 'description': '12 Angry Men is a movie starring Henry Fonda, Lee J. Cobb, '
                'and Martin Balsam. A jury holdout attempts to prevent a '
                'miscarriage of justice by forcing his colleagues to '
                'reconsider the evidence.',
 'director': [{'@type': 'Person',
               'name': 'Sidney Lumet',
               'url': '/name/nm0001486/'}],
 'duration': 'PT1H36M',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg',
 'keywords': 'jury,dialogue driven,courtroom,single set production,trial',
 'name': '12 Angry Men',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Three Reasons Criterion trailer',
              'embedUrl': '/video/imdb/vi3452609817',
              'name': '12 Angry Men',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjE3MWNhZDYtYjFlMS00MzM4LTg5M2YtYTAwMGY2ZDg0OGY0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjE3MWNhZDYtYjFlMS00MzM4LTg5M2YtYTAwMGY2ZDg0OGY0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2012-08-23T03:04:12Z'}],
 'url': '/title/tt0050083/'}