{'Actors': ['Aaron Douglas',
            'Adrien Dorval',
            'Alexa Davalos',
            'Alexis Llewellyn',
            'Andy Thompson',
            'Ben Cotton',
            'Cedric De Souza',
            'Charles Zuckermann',
            'Christina Cox',
            'Christopher Heyerdahl',
            'Colm Feore',
            'Darcy Laurie',
            'Douglas Arthurs',
            'John Mann',
            'Judi Dench',
            'Karl Urban',
            'Keith David',
            'Kimberly Hawthorne',
            'Kristin Lehman',
            'Linus Roache',
            'Lorena Gale',
            'Mark Acheson',
            'Mark Gibbon',
            'Michasha Armstrong',
            'Mina E Mina',
            'Nick Chinlund',
            'Peter Williams',
            'Raoul Ganeev',
            'Rob Daly',
            'Roger R Cross',
            'Ron Selmour',
            'Shawn Reis',
            'Stefano DiMatteo',
            'Terry Chen',
            'Thandie Newton',
            'Ty Olsson',
            'Vin Diesel',
            'Vitaly Kravchenko',
            'Yorick van Wageningen'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\nThe Chronicles of Riddick: 5 years after Pitch Black, the wanted criminal Riddick arrives on a planet called Helion Prime, and finds himself up against an invading empire called the Necromongers, an army that plans to convert or kill all humans in the universe. ',
 'Director': ['David Twohy'],
 'Genres': ['Action', 'Thriller', 'Sci-Fi', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0296572',
 'PrimeWire': 'http://www.primewire.ag/watch-2055-The-Chronicles-of-Riddick',
 'Ratings': {'IMDB': '6.7/10',
             'Metascore': '38%',
             'PrimeWire': '4.37/5',
             'RT': '29%',
             'Votes': '908'},
 'Released': '2004-06-03',
 'Runtime': '119 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2055_The_Chronicles_of_Riddick_2004.jpg',
 'Title': 'The-Chronicles-of-Riddick'}