{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-11-10',
 'EntryPath': 'Favorites/Movies/snapshot/12-Years-a-Slave',
 'EntryURL': 'https://www.imdb.com/title/tt2024544',
 'Entry_json': 'Favorites/Movies/snapshot/12-Years-a-Slave/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/12-Years-a-Slave/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/12-Years-a-Slave/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Chiwetel Ejiofor',
            'url': '/name/nm0252230/'},
           {'@type': 'Person',
            'name': 'Michael Kenneth Williams',
            'url': '/name/nm0931324/'},
           {'@type': 'Person',
            'name': 'Michael Fassbender',
            'url': '/name/nm1055413/'},
           {'@type': 'Person', 'name': 'Brad Pitt', 'url': '/name/nm0000093/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 616160,
                     'ratingValue': '8.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'John Ridley',
              'url': '/name/nm0725983/'},
             {'@type': 'Person',
              'name': 'Solomon Northup',
              'url': '/name/nm1185849/'},
             {'@type': 'Organization', 'url': '/company/co0021592/'},
             {'@type': 'Organization', 'url': '/company/co0120121/'},
             {'@type': 'Organization', 'url': '/company/co0136967/'},
             {'@type': 'Organization', 'url': '/company/co0025101/'},
             {'@type': 'Organization', 'url': '/company/co0197272/'},
             {'@type': 'Organization', 'url': '/company/co0028932/'},
             {'@type': 'Organization', 'url': '/company/co0046206/'}],
 'datePublished': '2013-11-08',
 'description': '12 Years a Slave is a movie starring Chiwetel Ejiofor, '
                'Michael Kenneth Williams, and Michael Fassbender. In the '
                'antebellum United States, Solomon Northup, a free black man '
                'from upstate New York, is abducted and sold into slavery.',
 'director': {'@type': 'Person',
              'name': 'Steve McQueen',
              'url': '/name/nm2588606/'},
 'duration': 'PT2H14M',
 'genre': ['Biography', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_.jpg',
 'keywords': 'torture,kidnapping,racism,whipping,slavery',
 'name': '12 Years a Slave',
 'trailer': {'@type': 'VideoObject',
             'description': 'In the antebellum United States, Solomon Northup, '
                            'a free black man from upstate New York, is '
                            'abducted and sold into slavery.',
             'embedUrl': '/video/imdb/vi302032921',
             'name': 'UK Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ4MjI1OTI2Nl5BMl5BanBnXkFtZTgwNDMwODQ3MDE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ4MjI1OTI2Nl5BMl5BanBnXkFtZTgwNDMwODQ3MDE@._V1_.jpg',
             'uploadDate': '2013-12-06T15:14:46Z'},
 'url': '/title/tt2024544/'}