<?php
$infoArray = array('Actors' => array('Alfre Woodard',
            'Benedict Cumberbatch',
            'Brad Pitt',
            'Chiwetel Ejiofor',
            'Michael Fassbender',
            'Paul Dano',
            'Paul Giamatti',
            'Sarah Paulson',
            'Scoot McNairy',
            'Taran Killam'),
 'Added' => '2013-11-10',
 'Countries' => array('UK', 'USA'),
 'Description' => "\n12 Years a Slave: Based on an incredible true story of one man's fight for survival and freedom. In the pre-Civil War United States, Solomon Northup (), a free black man from upstate New York, is abducted and sold into slavery. Facing cruelty (personified by a malevolent slave owner, portrayed by ), as well as unexpected kindnesses, Solomon struggles not only to stay alive, but to retain his dignity. In the twelfth year of his unforgettable odyssey, Solomon's chance meeting with a Canadian abolitionist () will forever alter his life. ",
 'Director' => array('Steve McQueen'),
 'Genres' => array('Biography', 'Drama', 'History'),
 'IMDB' => 'http://www.imdb.com/title/tt2024544',
 'PrimeWire' => 'http://www.primewire.ag/watch-2742543-12-Years-a-Slave',
 'Ratings' => array('IMDB' => '8.1/10',
             'Metascore' => '97%',
             'PrimeWire' => '4.13/5',
             'RT' => 'N/A',
             'Votes' => '1260'),
 'Released' => '2013-11-01',
 'Runtime' => '133 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2742543_12_Years_a_Slave_2014.jpg',
 'Title' => '12-Years-a-Slave');
?>