{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Waking-Life',
 'EntryURL': 'https://www.imdb.com/title/tt0243017',
 'Entry_json': 'Favorites/Movies/snapshot/Waking-Life/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Waking-Life/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Waking-Life/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ethan Hawke',
            'url': '/name/nm0000160/'},
           {'@type': 'Person',
            'name': 'Trevor Jack Brooks',
            'url': '/name/nm1085025/'},
           {'@type': 'Person',
            'name': 'Lorelei Linklater',
            'url': '/name/nm1085951/'},
           {'@type': 'Person',
            'name': 'Wiley Wiggins',
            'url': '/name/nm0927812/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 59364,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Richard Linklater',
              'url': '/name/nm0000500/'},
             {'@type': 'Organization', 'url': '/company/co0028932/'},
             {'@type': 'Organization', 'url': '/company/co0046530/'},
             {'@type': 'Organization', 'url': '/company/co0042682/'},
             {'@type': 'Organization', 'url': '/company/co0054189/'},
             {'@type': 'Organization', 'url': '/company/co0123642/'},
             {'@type': 'Organization', 'url': '/company/co0064516/'}],
 'datePublished': '2002-03-07',
 'description': 'Waking Life is a movie starring Ethan Hawke, Trevor Jack '
                'Brooks, and Lorelei Linklater. A man shuffles through a dream '
                'meeting various people and discussing the meanings and '
                'purposes of the universe.',
 'director': [{'@type': 'Person',
               'name': 'Richard Linklater',
               'url': '/name/nm0000500/'}],
 'duration': 'PT1H39M',
 'genre': ['Animation', 'Drama', 'Fantasy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMWM0ZjY5ZjctODNkZi00Nzk0LWE1ODUtNGM4ZDUyMzUwMGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'philosophy,lucid dreams,ukulele,watching television,lucid '
             'dreaming',
 'name': 'Waking Life',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from 20th Century Fox Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi2734358809',
              'name': 'Waking Life',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTdlMmY2OTktMTJmMi00YjJiLWJkM2UtZWFmZTFhNmI2YzYxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTdlMmY2OTktMTJmMi00YjJiLWJkM2UtZWFmZTFhNmI2YzYxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T17:16:16Z'}],
 'url': '/title/tt0243017/'}