{'Actors': ['Alan Lilly',
            'Alice Greczyn',
            'Amanda Crew',
            'Brett Rice',
            'Brian Posehn',
            'Charlie McDermott',
            'Clark Duke',
            'Cleo King',
            'Dave Sheridan',
            'David Koechner',
            'James Marsden',
            'John Ross Bowie',
            'Josh Zuckerman',
            'Keith Hudson',
            'Kyle Gass',
            'Marianne Muellerleile',
            'Michael Cudlitz',
            'Scott Klace',
            'Seth Green',
            'Susie Abromeit'],
 'Added': '2013-02-20',
 'Countries': ['USA'],
 'Description': '\n'
                'Sex Drive: A high school senior drives cross-country with his '
                'best friends to hook up with a babe he met online. ',
 'Director': ['Sean Anders'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Sex-Drive',
 'EntryURL': 'http://www.imdb.com/title/tt1135985',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Sex-Drive/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Sex-Drive/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Sex-Drive/info.py',
 'Genres': ['Comedy'],
 'IMDB': 'http://www.imdb.com/title/tt1135985',
 'PrimeWire': 'http://www.primewire.ag/watch-804-Sex-Drive',
 'Ratings': {'IMDB': '6.6/10',
             'Metascore': '49%',
             'PrimeWire': '3.81/5',
             'RT': '46%',
             'Votes': '543'},
 'Released': '2008-10-17',
 'Runtime': '109 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/804_Sex_Drive_2008.jpg',
 'Title': 'Sex-Drive'}