{'Actors': ['Amelia Campbell',
            'Amy McGee',
            'Chris Freihofer',
            'Chuck Vail',
            'Cindy McBride',
            'Deborah R Jones',
            'Edward Norton',
            'Eric Kelly McFarland',
            'Halley Rachal',
            'James B McDaniel',
            'Jeannie Perrin',
            'Jim Henry',
            'Jimmy Lee Jr',
            'John Foster',
            'Jon Dainty',
            'Josh Pais',
            'Ken Cheeseman',
            'Kent Jude Bernard',
            'Keri Russell',
            'Kimberly Liddell',
            'Krystal Mayo',
            'Lee Ann McDade',
            'Lee Wilkof',
            'Lucy DeVito',
            'Maggie Siff',
            'Matthew Ramsaur',
            'Melanie Lynskey',
            "Michael C 'Mike' Allen",
            'Mysti Nash',
            'Pruitt Taylor Vince',
            'Randal Reeder',
            'Richard Dreyfuss',
            'Robin McGee',
            'Sarah J Thompson',
            'Steven E Williams',
            'Susan Sarandon',
            'Tammy Eaton',
            'Ted Ferguson',
            'Thomas Wallace',
            'Tim Blake Nelson',
            'Tim Ware',
            'Ty Burrell'],
 'Added': '2013-02-20',
 'Countries': ['USA'],
 'Description': '\n'
                'Leaves of Grass: The lives of two identical twins, one an Ivy '
                'League philosophy professor, the other a small-time and '
                'brilliant marijuana grower, intertwine when the professor is '
                'lured back to his Oklahoma hometown for a doomed scheme '
                'against a local drug lord. ',
 'Director': ['Tim Blake Nelson'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Leaves-of-Grass',
 'EntryURL': 'https://www.imdb.com/title/tt1151359',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Leaves-of-Grass/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Leaves-of-Grass/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Leaves-of-Grass/info.py',
 'Genres': ['Drama', 'Comedy', 'Thriller', 'Crime'],
 'Ratings': {'IMDB': '6.5/10',
             'Metascore': '58%',
             'PrimeWire': '3.70/5',
             'RT': '59%',
             'Votes': '191'},
 'Released': '2009-09-14',
 'Runtime': '105 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/27567_Leaves_of_Grass_2009.jpg',
 'Title': 'Leaves-of-Grass'}