{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Condemned-2-Bloodshot',
 'EntryURL': 'https://rawg.io/games/condemned-2-bloodshot',
 'Entry_json': 'Favorites/Games/snapshot/Condemned-2-Bloodshot/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Condemned-2-Bloodshot/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Condemned-2-Bloodshot/thumb.jpg',
 'added': 279,
 'background_image': 'https://media.rawg.io/media/screenshots/d05/d058d2555d52a40192a140d31f0b1560.jpg',
 'developers': ['Monolith Productions', 'SEGA'],
 'genres': ['Action', 'Shooter', 'Fighting'],
 'name': 'Condemned 2: Bloodshot',
 'platforms': ['PlayStation 3', 'Xbox 360'],
 'publishers': ['SEGA'],
 'released': '2008-01-01',
 'slug': 'condemned-2-bloodshot'}