{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Green-Mile',
 'EntryURL': 'https://www.imdb.com/title/tt0120689',
 'Entry_json': 'Favorites/Movies/snapshot/The-Green-Mile/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Green-Mile/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Green-Mile/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Hanks', 'url': '/name/nm0000158/'},
           {'@type': 'Person',
            'name': 'Michael Clarke Duncan',
            'url': '/name/nm0003817/'},
           {'@type': 'Person',
            'name': 'David Morse',
            'url': '/name/nm0001556/'},
           {'@type': 'Person',
            'name': 'Bonnie Hunt',
            'url': '/name/nm0001372/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1095505,
                      'ratingValue': '8.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Stephen King',
              'url': '/name/nm0000175/'},
             {'@type': 'Person',
              'name': 'Frank Darabont',
              'url': '/name/nm0001104/'},
             {'@type': 'Organization', 'url': '/company/co0040620/'},
             {'@type': 'Organization', 'url': '/company/co0029398/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'}],
 'datePublished': '1999-12-10',
 'description': 'The Green Mile is a movie starring Tom Hanks, Michael Clarke '
                'Duncan, and David Morse. The lives of guards on Death Row are '
                'affected by one of their charges: a black man accused of '
                'child murder and rape, yet who has a mysterious gift.',
 'director': [{'@type': 'Person',
               'name': 'Frank Darabont',
               'url': '/name/nm0001104/'}],
 'duration': 'PT3H9M',
 'genre': ['Crime', 'Drama', 'Fantasy', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg',
 'keywords': 'death row inmate,good versus evil,1930s,prison guard,murder',
 'name': 'The Green Mile',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Warner Home Video',
              'embedUrl': '/video/imdb/vi552796441',
              'name': 'The Green Mile',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODU4NmYyMzEtNzkwNy00NmFlLTk3YWItM2I5NDk3YTUyODFhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODU4NmYyMzEtNzkwNy00NmFlLTk3YWItM2I5NDk3YTUyODFhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T16:45:12Z'}],
 'url': '/title/tt0120689/'}