{'Actors': ['Alex Revan',
            'Angela Goethals',
            'Kane Hodder',
            'Kate Lang Johnson',
            'Krissy Carlson',
            'Robert Englund',
            'Scott Wilson',
            'Zelda Rubinstein'],
 'Added': '2016-10-23',
 'Countries': ['USA'],
 'Description': '\nBehind the Mask: The Rise of Leslie Vernon: The next great psycho horror slasher has given a documentary crew exclusive access to his life as he... ',
 'Director': ['Scott Glosserman'],
 'Genres': ['Comedy', 'Thriller', 'Horror'],
 'IMDB': 'http://www.imdb.com/title/tt0437857',
 'PrimeWire': 'http://www.primewire.ag/watch-6545-Behind-the-Mask-The-Rise-of-Leslie-Vernon',
 'Ratings': {'IMDB': '6.8/10',
             'Metascore': '66%',
             'PrimeWire': '3.66/5',
             'RT': '76%',
             'Votes': '160'},
 'Released': '2006-07-08',
 'Runtime': '92 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/6545_Behind_the_Mask_The_Rise_of_Leslie_Vernon_2006.jpg',
 'Title': 'Behind-the-Mask-The-Rise-of-Leslie-Vernon'}