{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-10-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Behind-the-Mask-The-Rise-of-Leslie-Vernon',
 'EntryURL': 'https://www.imdb.com/title/tt0437857',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Behind-the-Mask-The-Rise-of-Leslie-Vernon/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Behind-the-Mask-The-Rise-of-Leslie-Vernon/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Behind-the-Mask-The-Rise-of-Leslie-Vernon/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Nathan Baesel',
            'url': '/name/nm1519453/'},
           {'@type': 'Person',
            'name': 'Angela Goethals',
            'url': '/name/nm0324462/'},
           {'@type': 'Person',
            'name': 'Zelda Rubinstein',
            'url': '/name/nm0748289/'},
           {'@type': 'Person',
            'name': 'Robert Englund',
            'url': '/name/nm0000387/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 20822,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Scott Glosserman',
              'url': '/name/nm1795664/'},
             {'@type': 'Person',
              'name': 'David J. Stieve',
              'url': '/name/nm1818268/'},
             {'@type': 'Organization', 'url': '/company/co0141509/'},
             {'@type': 'Organization', 'url': '/company/co0143069/'}],
 'datePublished': '2006-07-08',
 'description': 'Behind the Mask: The Rise of Leslie Vernon is a movie '
                'starring Nathan Baesel, Angela Goethals, and Zelda '
                'Rubinstein. The next great psycho horror slasher has given a '
                'documentary crew exclusive access to his life as he plans '
                'his...',
 'director': {'@type': 'Person',
              'name': 'Scott Glosserman',
              'url': '/name/nm1795664/'},
 'duration': 'PT1H32M',
 'genre': ['Comedy', 'Horror', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE5MDE3MTQxOV5BMl5BanBnXkFtZTcwNDY0NzA0MQ@@._V1_.jpg',
 'keywords': 'serial killer,masked killer,film crew,virginity,reverse cowboy '
             'sex position',
 'name': 'Behind the Mask: The Rise of Leslie Vernon',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Anchor Bay Films',
             'embedUrl': '/video/imdb/vi3501785369',
             'name': 'Behind the Mask: The Rise of Leslie Vernon',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZjU1YWRiZGQtNTNjMi00NjkxLTkxZTUtZjY3YjZmNzJmMzg1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZjU1YWRiZGQtNTNjMi00NjkxLTkxZTUtZjY3YjZmNzJmMzg1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T12:29:32Z'},
 'url': '/title/tt0437857/'}