<?php
$infoArray = array('Actors' => array('Adelle Lutz',
            'Alexandra Neil',
            'Andrea Thompson',
            'Ann Talman',
            'Anna Levine',
            'Annie McEnroe',
            'Byron Utley',
            'Carol Schneider',
            'Cecilia Peck',
            'Charlie Sheen',
            'Chris Nelson Norris',
            'Chuck Pfeiffer',
            'Daryl Hannah',
            'David Logan',
            'Donnie Kehr',
            'Fran&#xE7;ois Giroday',
            'Frank Adonis',
            'Franklin Cover',
            'George Blumenthal',
            'Grant Shaud',
            'Hal Holbrook',
            'James Bulleit',
            'James Karen',
            'James Spader',
            'Jean De Baer',
            'Jeff Beck',
            'Jeff Rector',
            'John C McGinley',
            'John Capodice',
            'Josh Mostel',
            'Lauren Tom',
            'Leslie Lyles',
            'Liliane Montevecchi',
            'Lisa Zebro',
            'Martin Sheen',
            'Martin Sherman',
            'Michael C Mahon',
            'Michael Douglas',
            "Michael O'Donoghue",
            'Millie Perkins',
            'Monique van Vooren',
            'Oliver Stone',
            'Pat Skipper',
            'Paul Guilfoyle',
            'Richard Dysart',
            'Sam Ingraffia',
            'Saul Rubinek',
            'Sean Stone',
            'Sean Young',
            'Sylvia Miles',
            'Tamara Tunie',
            'Terence Stamp',
            'Thomas Anderson',
            'Yanni Sfinias'),
 'Added' => '2013-02-24',
 'Countries' => array('USA'),
 'Description' => '\nWall Street: A young and impatient stockbroker is willing to do anything to get to the top, including trading on illegal inside information taken through a ruthless and greedy corporate raider whom takes the youth under his wing. ',
 'Director' => array('Oliver Stone'),
 'Genres' => array('Drama', 'Crime'),
 'IMDB' => 'http://www.imdb.com/title/tt0094291',
 'PrimeWire' => 'http://www.primewire.ag/watch-2594-Wall-Street',
 'Ratings' => array('IMDB' => '7.4/10',
             'Metascore' => '56%',
             'PrimeWire' => '3.63/5',
             'RT' => '78%',
             'Votes' => '316'),
 'Released' => '1987-12-11',
 'Runtime' => '126 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2594_Wall_Street_1987.jpg',
 'Title' => 'Wall-Street');
?>