<?php
$infoArray = array('Actors' => array('Alexander Skarsg&#xE5;rd',
            'Fares Fares',
            'Juliette Lewis',
            'Magnus Skogsberg',
            'Michael Mansson',
            'Sandy Mansson',
            'Shanti Roney',
            'Sofia Helin',
            'Stellan Skarsg&#xE5;rd',
            'Udo Kier',
            'Vincent Gallo'),
 'Added' => '2013-06-15',
 'Countries' => array('Sweden', 'Denmark', 'Norway', 'Finland'),
 'Description' => '\nMetropia: In the near future, oil reserves are nearly depleted and Europe is connected by series of underground tunnels. While navigating these tunnels, Roger hears voices, one in particular. Seeking a way to rid himself of the voice only leads Roger deeper into a bizarre conspiracy of control - mind and body. ',
 'Director' => array('Tarik Saleh'),
 'Genres' => array('Animation', 'Thriller', 'Sci-Fi'),
 'IMDB' => 'http://www.imdb.com/title/tt0985058',
 'PrimeWire' => 'http://www.primewire.ag/watch-260365-Metropia',
 'Ratings' => array('IMDB' => '6.3/10',
             'Metascore' => '47%',
             'PrimeWire' => '3.54/5',
             'RT' => '40%',
             'Votes' => '57'),
 'Released' => '2009-09-03',
 'Runtime' => '86 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/260365_Metropia_2009.jpg',
 'Title' => 'Metropia');
?>