{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-03-12',
 'EntryPath': 'Favorites/TV/snapshot/Horace-and-Pete',
 'EntryURL': 'https://www.imdb.com/title/tt5425186',
 'Entry_json': 'Favorites/TV/snapshot/Horace-and-Pete/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Horace-and-Pete/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Horace-and-Pete/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Louis C.K.', 'url': '/name/nm0127373/'},
           {'@type': 'Person',
            'name': 'Steve Buscemi',
            'url': '/name/nm0000114/'},
           {'@type': 'Person', 'name': 'Edie Falco', 'url': '/name/nm0004908/'},
           {'@type': 'Person',
            'name': 'Steven Wright',
            'url': '/name/nm0942833/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 14244,
                     'ratingValue': '8.5',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Louis C.K.',
              'url': '/name/nm0127373/'},
             {'@type': 'Organization', 'url': '/company/co0363979/'}],
 'datePublished': '2016-01-30',
 'description': 'Horace and Pete is a TV series starring Louis C.K., Steve '
                "Buscemi, and Edie Falco. Louis C.K.'s Eugene O'Neill-esque "
                'dramedic web series about two brothers, introverted Horace '
                'and mentally ill Pete, the current owners of their...',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjRhOGY5ZmMtYWE5ZC00ZDA2LTk3NDItN2FlOGE5MjQwMjVkXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
 'keywords': 'web series,bar,character name in title',
 'name': 'Horace and Pete',
 'url': '/title/tt5425186/'}