{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Manhole-Masterpiece-Edition',
 'EntryURL': 'https://rawg.io/games/the-manhole-masterpiece-edition',
 'Entry_json': 'Favorites/Games/snapshot/The-Manhole-Masterpiece-Edition/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Manhole-Masterpiece-Edition/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Manhole-Masterpiece-Edition/thumb.jpg',
 'added': 106,
 'background_image': 'https://media.rawg.io/media/screenshots/df6/df63d242841ec69d1581efe09c1fb6e0.jpg',
 'developers': ['Cyan Worlds'],
 'genres': ['Adventure', 'Casual'],
 'name': 'The Manhole: Masterpiece Edition',
 'platforms': ['PC'],
 'publishers': ['Cyan Worlds'],
 'slug': 'the-manhole-masterpiece-edition'}