{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2017-05-30',
 'EntryPath': 'Favorites/Movies/snapshot/The-Girl-with-All-the-Gifts',
 'EntryURL': 'https://www.imdb.com/title/tt4547056',
 'Entry_json': 'Favorites/Movies/snapshot/The-Girl-with-All-the-Gifts/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Girl-with-All-the-Gifts/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Girl-with-All-the-Gifts/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sennia Nanua',
            'url': '/name/nm6451469/'},
           {'@type': 'Person',
            'name': 'Fisayo Akinade',
            'url': '/name/nm6160535/'},
           {'@type': 'Person',
            'name': 'Dominique Tipper',
            'url': '/name/nm4625680/'},
           {'@type': 'Person',
            'name': 'Paddy Considine',
            'url': '/name/nm0175916/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 52635,
                      'ratingValue': '6.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mike Carey',
              'url': '/name/nm1259998/'},
             {'@type': 'Person',
              'name': 'Mike Carey',
              'url': '/name/nm1259998/'},
             {'@type': 'Organization', 'url': '/company/co0375874/'},
             {'@type': 'Organization', 'url': '/company/co0381819/'},
             {'@type': 'Organization', 'url': '/company/co0398856/'},
             {'@type': 'Organization', 'url': '/company/co0529888/'}],
 'datePublished': '2016-09-23',
 'description': 'The Girl with All the Gifts is a movie starring Sennia Nanua, '
                'Fisayo Akinade, and Dominique Tipper. A scientist and a '
                'teacher living in a dystopian future embark on a journey of '
                'survival with a special young girl named Melanie.',
 'director': [{'@type': 'Person',
               'name': 'Colm McCarthy',
               'url': '/name/nm1142073/'}],
 'duration': 'PT1H51M',
 'genre': ['Action', 'Adventure', 'Drama', 'Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjQ0NzA4NDcxM15BMl5BanBnXkFtZTgwMTk1NjUzOTE@._V1_.jpg',
 'keywords': 'experiment,bitten by a zombie,feral child,scientist,cure',
 'name': 'The Girl with All the Gifts',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A scientist and a teacher living in a dystopian '
                             'future embark on a journey of survival with a '
                             'special young girl named Melanie.',
              'embedUrl': '/video/imdb/vi3426661913',
              'name': 'U.S. Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTY1OTc5NDYwNV5BMl5BanBnXkFtZTgwMjk2NTMwMTI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTY1OTc5NDYwNV5BMl5BanBnXkFtZTgwMjk2NTMwMTI@._V1_.jpg',
              'uploadDate': '2017-01-06T04:33:22Z'}],
 'url': '/title/tt4547056/'}