<?php
$infoArray = array('Actors' => array('Ben Falcone',
            'Dahlia Salem',
            'David Denman',
            'Elle Fanning',
            'Ellen Treanor',
            'Hope Davis',
            'Jim Rash',
            'John Gatins',
            'Martin Yu',
            'Melissa McCarthy',
            'Octavia Spencer',
            'Ryan Reynolds'),
 'Added' => '2013-02-24',
 'Countries' => array('USA'),
 'Description' => '\nThe Nines: A troubled actor, a television show runner, and an acclaimed videogame designer find their lives intertwining in mysterious and unsettling ways. ',
 'Director' => array('John August'),
 'Genres' => array('Drama', 'Sci-Fi', 'Fantasy', 'Mystery'),
 'IMDB' => 'http://www.imdb.com/title/tt0810988',
 'PrimeWire' => 'http://www.primewire.ag/watch-2775-The-Nines',
 'Ratings' => array('IMDB' => '6.4/10',
             'Metascore' => '52%',
             'PrimeWire' => '3.56/5',
             'RT' => '64%',
             'Votes' => '404'),
 'Released' => '2007-01-21',
 'Runtime' => '100 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2775_The_Nines_2007.jpg',
 'Title' => 'The-Nines');
?>