{'Actors': ['Gemma Arterton', 'Glenn Close', 'Paddy Considine'],
 'Added': '2017-05-30',
 'Countries': ['UK', 'USA'],
 'Description': '\nThe Girl with All the Gifts: A scientist and a teacher living in a dystopian future embark on a journey of survival with a special young girl named Melanie. ',
 'Director': ['Colm McCarthy'],
 'Genres': ['Drama'],
 'IMDB': 'http://www.imdb.com/title/tt4547056',
 'PrimeWire': 'http://www.primewire.ag/watch-2787303-The-Girl-with-All-the-Gifts',
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': '73%',
             'PrimeWire': '4.01/5',
             'RT': '83%',
             'Votes': '181'},
 'Released': '2016-09-23',
 'Runtime': '111 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2787303_The_Girl_with_All_the_Gifts_2016.jpg',
 'Title': 'The-Girl-with-All-the-Gifts'}