{'Actors': ['Amanda Walker',
            'Catherine McCormack',
            'Daniel Jefferson',
            'Dean Alexandrou',
            'Garfield Morgan',
            'Harold Perrineau',
            'Idris Elba',
            'Imogen Poots',
            'James Fiddy',
            'Jeremy Renner',
            'Jo&#xE3;o Costa Menezes',
            'Jude Poyer',
            'Karen Meagher',
            'Raymond Waring',
            'Robert Carlyle',
            'Roderic Culver',
            'Rose Byrne',
            'Simon Delaney',
            'Tommy Gunn',
            'Tristan Tait',
            'William Meredith'],
 'Added': '2013-02-19',
 'Countries': ['UK', 'Spain'],
 'Description': '\n'
                '28 Weeks Later: Six months after the rage virus was inflicted '
                'on the population of Great Britain, the US Army helps to '
                'secure a small area of London for the survivors to repopulate '
                'and start again. But not everything goes to plan. ',
 'Director': ['Juan Carlos Fresnadillo'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//28-Weeks-Later',
 'EntryURL': 'https://www.imdb.com/title/tt0463854',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//28-Weeks-Later/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//28-Weeks-Later/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//28-Weeks-Later/info.py',
 'Genres': ['Thriller', 'Sci-Fi', 'Horror', 'Zombies'],
 'IMDB': 'http://www.imdb.com/title/tt0463854',
 'PrimeWire': 'http://www.primewire.ag/watch-1348-28-Weeks-Later',
 'Ratings': {'IMDB': '7.0/10',
             'Metascore': '78%',
             'PrimeWire': '3.98/5',
             'RT': '71%',
             'Votes': '901'},
 'Released': '2007-05-06',
 'Runtime': '100 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1348_28_Weeks_Later_2007.jpg',
 'Title': '28-Weeks-Later'}