{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/28-Weeks-Later',
 'EntryURL': 'https://www.imdb.com/title/tt0463854',
 'Entry_json': 'Favorites/Movies/snapshot/28-Weeks-Later/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/28-Weeks-Later/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/28-Weeks-Later/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jeremy Renner',
            'url': '/name/nm0719637/'},
           {'@type': 'Person', 'name': 'Rose Byrne', 'url': '/name/nm0126284/'},
           {'@type': 'Person',
            'name': 'Robert Carlyle',
            'url': '/name/nm0001015/'},
           {'@type': 'Person',
            'name': 'Harold Perrineau',
            'url': '/name/nm0674782/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 252912,
                     'ratingValue': '7.0',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Rowan Joffe',
              'url': '/name/nm0423626/'},
             {'@type': 'Person',
              'name': 'Juan Carlos Fresnadillo',
              'url': '/name/nm0294379/'},
             {'@type': 'Person',
              'name': 'Enrique López Lavigne',
              'url': '/name/nm0492038/'},
             {'@type': 'Person',
              'name': 'Jesús Olmo',
              'url': '/name/nm0647449/'},
             {'@type': 'Organization', 'url': '/company/co0176225/'},
             {'@type': 'Organization', 'url': '/company/co0103974/'},
             {'@type': 'Organization', 'url': '/company/co0104811/'},
             {'@type': 'Organization', 'url': '/company/co0103732/'},
             {'@type': 'Organization', 'url': '/company/co0080755/'},
             {'@type': 'Organization', 'url': '/company/co0187917/'}],
 'datePublished': '2007-05-10',
 'description': '28 Weeks Later is a movie starring Jeremy Renner, Rose Byrne, '
                'and Robert Carlyle. Six months after the rage virus was '
                'inflicted on the population of Great Britain, the US Army '
                'helps to secure a small area of London for the survivors...',
 'director': {'@type': 'Person',
              'name': 'Juan Carlos Fresnadillo',
              'url': '/name/nm0294379/'},
 'duration': 'PT1H40M',
 'genre': ['Horror', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA5NjE2NDI0OF5BMl5BanBnXkFtZTgwNzU0NzQyMTI@._V1_.jpg',
 'keywords': 'infection,zombie film,zombie outbreak,zombie apocalypse,tied up '
             'while barefoot',
 'name': '28 Weeks Later',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from 20th Century Fox Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi4088594713',
             'name': '28 Weeks Later',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDAyMDE1NzYtMjg3ZC00MjE4LThjOGMtYmZiOTUwOTY5MjA0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDAyMDE1NzYtMjg3ZC00MjE4LThjOGMtYmZiOTUwOTY5MjA0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T03:11:31Z'},
 'url': '/title/tt0463854/'}