<?php
$infoArray = array('Actors' => array('Alice Marie Crowe',
            'Alicia Witt',
            'Ana Maria Quintana',
            'Andrei Sterling',
            'Armand Schultz',
            'Blossom',
            'Brent Sexton',
            'Cameron Diaz',
            'Cameron Watson',
            "Conan O'Brien",
            'Delaina Mitchell',
            'Dustin LaValley',
            'Ivana Milicevic',
            'James Murtaugh',
            'Jan Munroe',
            'Jane Pratt',
            'Jason Lee',
            'Jean Carol',
            'Jeff Weiss',
            'Jennifer Aspen',
            'Jennifer Gimenez',
            'Jennifer Griffin',
            'Johnny Galecki',
            'Ken Leung',
            'Kurt Russell',
            'Laura Fraser',
            'Laurel Wiley',
            'Louis E Rosas',
            'Mark Bramhall',
            'Mark Pinter',
            'Michael Kehoe',
            'Michael Shannon',
            'Noah Taylor',
            'Penelope Cruz',
            'Ray Proscia',
            'Scotch Ellis Loring',
            'Shalom Harlow',
            'Steven Spielberg',
            'Tara Lipinski',
            'Tilda Swinton',
            'Tim Hopper',
            'Timothy Spall',
            'Tom Cruise',
            'Tommy Lee',
            'Tony Collucci',
            'W Earl Brown',
            'William Mapother'),
 'Added' => '2013-02-24',
 'Countries' => array('USA', 'Spain'),
 'Description' => '\nVanilla Sky: A successful publisher finds his life taking a turn for the surreal after a car accident with a jaded lover. ',
 'Director' => array('Cameron Crowe'),
 'Genres' => array('Mystery', 'Romance', 'Sci-Fi', 'Thriller'),
 'IMDB' => 'http://www.imdb.com/title/tt0259711',
 'PrimeWire' => 'http://www.primewire.ag/watch-1222-Vanilla-Sky',
 'Ratings' => array('IMDB' => '6.9/10',
             'Metascore' => '45%',
             'PrimeWire' => '3.92/5',
             'RT' => '41%',
             'Votes' => '403'),
 'Released' => '2001-12-10',
 'Runtime' => '136 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1222_Vanilla_Sky_2001.jpg',
 'Title' => 'Vanilla-Sky');
?>