{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Books/snapshot/Opengl-Es-30-Programming-Guide',
 'EntryURL': 'https://www.goodreads.com/book/show/22291544-opengl-es-3-0-programming-guide',
 'Entry_json': 'Favorites/Books/snapshot/Opengl-Es-30-Programming-Guide/entry.json',
 'Entry_py': 'Favorites/Books/snapshot/Opengl-Es-30-Programming-Guide/info.py',
 'Entry_thumb': 'Favorites/Books/snapshot/Opengl-Es-30-Programming-Guide/thumb.jpg',
 'authors': [{'id': '531123',
              'image_url': '\n'
                           'https://s.gr-assets.com/assets/nophoto/user/u_200x266-e183445fd1a1b5cc7075bb1cf7043306.png\n',
              'link': 'https://www.goodreads.com/author/show/531123.Dan_Ginsburg',
              'name': 'Dan Ginsburg',
              'role': None,
              'small_image_url': '\n'
                                 'https://s.gr-assets.com/assets/nophoto/user/u_50x66-632230dc9882b4352d753eedf9396530.png\n'}],
 'description': None,
 'edition_information': None,
 'format': None,
 'id': '22291544',
 'image_url': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
 'isbn': None,
 'isbn13': None,
 'large_image_url': None,
 'link': 'https://www.goodreads.com/book/show/22291544-opengl-es-3-0-programming-guide',
 'num_pages': None,
 'publication_day': None,
 'publication_month': None,
 'publication_year': None,
 'published': None,
 'publisher': None,
 'small_image_url': 'https://s.gr-assets.com/assets/nophoto/book/50x75-a91bf249278a81aabab721ef782c4a74.png',
 'title': 'OpenGL ES 3.0 Programming Guide (2nd Edition)',
 'title_without_series': 'OpenGL ES 3.0 Programming Guide',
 'uri': 'kca://book/amzn1.gr.book.v1.07SVp9aRVlGs5oMhqiSJjg',
 'work': '  '}