{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/A-Cure-for-Wellness',
 'EntryURL': 'https://www.imdb.com/title/tt4731136',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/A-Cure-for-Wellness/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/A-Cure-for-Wellness/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/A-Cure-for-Wellness/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/A-Cure-for-Wellness/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Dane DeHaan',
            'url': '/name/nm2851530/'},
           {'@type': 'Person',
            'name': 'Jason Isaacs',
            'url': '/name/nm0005042/'},
           {'@type': 'Person', 'name': 'Mia Goth', 'url': '/name/nm5301405/'},
           {'@type': 'Person', 'name': 'Ivo Nandi', 'url': '/name/nm2166477/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 80212,
                     'ratingValue': '6.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Justin Haythe',
              'url': '/name/nm1244808/'},
             {'@type': 'Person',
              'name': 'Justin Haythe',
              'url': '/name/nm1244808/'},
             {'@type': 'Person',
              'name': 'Gore Verbinski',
              'url': '/name/nm0893659/'},
             {'@type': 'Organization', 'url': '/company/co0021592/'},
             {'@type': 'Organization', 'url': '/company/co0230970/'},
             {'@type': 'Organization', 'url': '/company/co0141035/'},
             {'@type': 'Organization', 'url': '/company/co0053177/'},
             {'@type': 'Organization', 'url': '/company/co0420822/'}],
 'datePublished': '2017-02-15',
 'description': 'A Cure for Wellness is a movie starring Dane DeHaan, Jason '
                'Isaacs, and Mia Goth. An ambitious young executive is sent to '
                "retrieve his company's CEO from an idyllic but mysterious "
                '"wellness center" at a remote location in the Swiss...',
 'director': {'@type': 'Person',
              'name': 'Gore Verbinski',
              'url': '/name/nm0893659/'},
 'duration': 'PT2H26M',
 'genre': ['Drama', 'Fantasy', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg5Njg1MzIwNl5BMl5BanBnXkFtZTgwNDU1NjczMDI@._V1_.jpg',
 'keywords': 'father daughter love,spread eagle,deflowering,capitalism,leg '
             'spreading',
 'name': 'A Cure for Wellness',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'roger-stark'},
            'dateCreated': '2020-04-16',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt4731136/'},
            'name': "Ivanka's fave Film",
            'reviewBody': 'Ivanka bought a DVD copy of this film and gave it '
                          'to daddy as a present. It was a token of her love '
                          'for daddy-o.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '7',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': "Watch the Super Bowl Spot for 'A Cure for "
                            "Wellness.'",
             'embedUrl': '/video/imdb/vi2617816601',
             'name': 'Super Bowl Spot',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTRmZWM5MmItMjk0Ni00YmRjLThiODgtNDRkZDk1NWQ4MTBkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTRmZWM5MmItMjk0Ni00YmRjLThiODgtNDRkZDk1NWQ4MTBkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
             'uploadDate': '2017-02-06T10:22:18Z'},
 'url': '/title/tt4731136/'}