{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Channel-Zero',
 'EntryURL': 'https://www.imdb.com/title/tt4820370',
 'Entry_json': 'Favorites/TV/snapshot/Channel-Zero/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Channel-Zero/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Channel-Zero/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Brandon Scott',
            'url': '/name/nm1792900/'},
           {'@type': 'Person',
            'name': 'Marina Stephenson Kerr',
            'url': '/name/nm1011431/'},
           {'@type': 'Person',
            'name': 'Abigail Pniowsky',
            'url': '/name/nm6786013/'},
           {'@type': 'Person',
            'name': 'Diana Bentley',
            'url': '/name/nm4627683/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 8676,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Nick Antosca',
              'url': '/name/nm4528537/'},
             {'@type': 'Organization', 'url': '/company/co0719556/'},
             {'@type': 'Organization', 'url': '/company/co0242101/'}],
 'datePublished': '2016-10-11',
 'description': 'Channel Zero is a TV series starring Brandon Scott, Marina '
                'Stephenson Kerr, and Abigail Pniowsky. An anthology series '
                'based on popular Internet Creepypastas Candle Cove, The '
                "No-End House, Butcher's Block, and The Dream Door.",
 'genre': ['Drama', 'Fantasy', 'Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjExMTMxNjMwNl5BMl5BanBnXkFtZTgwNDA2OTYzNjM@._V1_.jpg',
 'keywords': 'anthology series,2010s,fictional horror series,reference to '
             'candle cove,reference to creepypasta',
 'name': 'Channel Zero',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi2419570713',
              'name': 'Channel Zero Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOGVkY2Y4MzgtYjY2Yi00YzIxLWE1M2EtNmE4YTY2NzQ2NTE1XkEyXkFqcGdeQXVyNzkyNzc3NjU@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOGVkY2Y4MzgtYjY2Yi00YzIxLWE1M2EtNmE4YTY2NzQ2NTE1XkEyXkFqcGdeQXVyNzkyNzc3NjU@._V1_.jpg',
              'uploadDate': '2018-02-27T21:24:56Z'}],
 'url': '/title/tt4820370/'}