{'Actors': ['Alexa Vega',
            'Amber Heard',
            'Antonio Banderas',
            'Charlie Sheen',
            'Cuba Gooding Jr',
            'Danny Trejo',
            'Edward James Olmos',
            'Jessica Alba',
            'Mel Gibson',
            'Michelle Rodriguez',
            'Vanessa Hudgens',
            'William Sadler'],
 'Added': '2013-11-13',
 'Countries': ['Russia', 'USA'],
 'Description': '\n'
                'Machete Kills: The U.S. government recruits Machete to battle '
                'his way through Mexico in order to take down an arms dealer '
                'who looks to launch a weapon into space. ',
 'Director': ['Robert Rodriguez'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Machete-Kills',
 'EntryURL': 'http://www.imdb.com/title/tt2002718',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Machete-Kills/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Machete-Kills/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Machete-Kills/info.py',
 'Genres': ['Action', 'Crime', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt2002718',
 'PrimeWire': 'http://www.primewire.ag/watch-2742321-Machete-Kills',
 'Ratings': {'IMDB': '5.7/10',
             'Metascore': '41%',
             'PrimeWire': '3.43/5',
             'RT': '29%',
             'Votes': '496'},
 'Released': '2013-10-11',
 'Runtime': '107 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2742321_Machete_Kills_2013.jpg',
 'Title': 'Machete-Kills'}