{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-11-13',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Machete-Kills',
 'EntryURL': 'https://www.imdb.com/title/tt2002718',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Machete-Kills/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Machete-Kills/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Machete-Kills/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Danny Trejo',
            'url': '/name/nm0001803/'},
           {'@type': 'Person',
            'name': 'Alexa PenaVega',
            'url': '/name/nm0891786/'},
           {'@type': 'Person', 'name': 'Mel Gibson', 'url': '/name/nm0000154/'},
           {'@type': 'Person',
            'name': 'Jessica Alba',
            'url': '/name/nm0004695/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 72814,
                     'ratingValue': '5.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Kyle Ward',
              'url': '/name/nm2040359/'},
             {'@type': 'Person',
              'name': 'Robert Rodriguez',
              'url': '/name/nm0001675/'},
             {'@type': 'Person',
              'name': 'Marcel Rodriguez',
              'url': '/name/nm0735420/'},
             {'@type': 'Organization', 'url': '/company/co0343536/'},
             {'@type': 'Organization', 'url': '/company/co0335687/'},
             {'@type': 'Organization', 'url': '/company/co0237137/'},
             {'@type': 'Organization', 'url': '/company/co0316574/'},
             {'@type': 'Organization', 'url': '/company/co0317576/'},
             {'@type': 'Organization', 'url': '/company/co0239634/'}],
 'datePublished': '2013-09-26',
 'description': 'Machete Kills is a movie starring Danny Trejo, Alexa '
                'PenaVega, and Mel Gibson. The U.S. government recruits '
                'Machete to battle his way through Mexico in order to take '
                'down an arms dealer who looks to launch a weapon into space.',
 'director': {'@type': 'Person',
              'name': 'Robert Rodriguez',
              'url': '/name/nm0001675/'},
 'duration': 'PT1H47M',
 'genre': ['Action', 'Crime', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA2MzUxMTM3M15BMl5BanBnXkFtZTgwMzA2NzkxMDE@._V1_.jpg',
 'keywords': "murder of a police officer,time bomb,woman breaks a man's "
             'neck,woman murders a man,murderess',
 'name': 'Machete Kills',
 'trailer': {'@type': 'VideoObject',
             'description': 'The U.S. government recruits Machete to battle '
                            'his way through Mexico in order to take down an '
                            'arms dealer who looks to launch a weapon into '
                            'space.',
             'embedUrl': '/video/imdb/vi496085017',
             'name': 'Lady Gaga "Aura" Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjExODE0MTUzOV5BMl5BanBnXkFtZTgwMjMxNTczMDE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjExODE0MTUzOV5BMl5BanBnXkFtZTgwMjMxNTczMDE@._V1_.jpg',
             'uploadDate': '2013-10-05T07:44:30Z'},
 'url': '/title/tt2002718/'}