{'Actors': ['Andre Royo&tv',
            'Dana Delany&tv',
            'Garret Dillahunt&tv',
            'Ron Perlman&tv'],
 'Added': '2015-09-07',
 'Countries': [],
 'Description': '\n'
                'Hand of God: A morally-corrupt judge suffers a breakdown and '
                'believes God is compelling him onto a path of vigilante '
                'justice. ',
 'Director': ['NA'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Hand-of-God',
 'EntryURL': 'https://www.imdb.com/title/tt3973768',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Hand-of-God/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Hand-of-God/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Hand-of-God/info.py',
 'Genres': ['Drama&tv'],
 'IMDB': 'http://www.imdb.com/title/tt3973768',
 'PrimeWire': 'http://www.primewire.ag/tv-2749476-Hand-of-God',
 'Ratings': {'IMDB': '8.0/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.30/5',
             'RT': 'N/A',
             'Votes': '152'},
 'Released': '2014-08-28',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2749476_Hand_of_God.jpg',
 'Title': 'Hand-of-God'}