{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-09-07',
 'EntryPath': 'Favorites/TV/snapshot/Hand-of-God',
 'EntryURL': 'https://www.imdb.com/title/tt3973768',
 'Entry_json': 'Favorites/TV/snapshot/Hand-of-God/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Hand-of-God/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Hand-of-God/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Garret Dillahunt',
            'url': '/name/nm0226813/'},
           {'@type': 'Person',
            'name': 'Emayatzy Corinealdi',
            'url': '/name/nm1538675/'},
           {'@type': 'Person',
            'name': 'Julian Acosta',
            'url': '/name/nm0010208/'},
           {'@type': 'Person',
            'name': 'Ron Perlman',
            'url': '/name/nm0000579/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 10186,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Ben Watkins',
              'url': '/name/nm1219905/'},
             {'@type': 'Organization', 'url': '/company/co0319272/'},
             {'@type': 'Organization', 'url': '/company/co0195799/'},
             {'@type': 'Organization', 'url': '/company/co0463308/'}],
 'datePublished': '2014-08-28',
 'description': 'Hand of God is a TV series starring Garret Dillahunt, '
                'Emayatzy Corinealdi, and Julian Acosta. A morally-corrupt '
                'judge suffers a breakdown and believes God is compelling him '
                'onto a path of vigilante justice.',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTRhNWFjOGEtNWNlYy00MjlkLTk1MjctN2MxMjE3NGVjZDg0XkEyXkFqcGdeQXVyNjkwNzEwMzU@._V1_.jpg',
 'keywords': 'religion,hallucination,suicide,talking to god,rape victim',
 'name': 'Hand of God',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A morally-corrupt judge suffers a breakdown and '
                             'believes God is compelling him onto a path of '
                             'vigilante justice.',
              'embedUrl': '/video/imdb/vi3111368217',
              'name': 'Season 2 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTk3NTFiNDUtYWRhNi00NzI4LTk5NGQtYzA1Njc2ODg0YmNhXkEyXkFqcGdeQXVyNTU4NjY5MzM@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTk3NTFiNDUtYWRhNi00NzI4LTk5NGQtYzA1Njc2ODg0YmNhXkEyXkFqcGdeQXVyNTU4NjY5MzM@._V1_.jpg',
              'uploadDate': '2017-02-15T02:07:42Z'}],
 'url': '/title/tt3973768/'}