{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Zelda-Ii-The-Adventure-Of-Link-2',
 'EntryURL': 'https://rawg.io/games/zelda-ii-the-adventure-of-link-2',
 'Entry_json': 'Favorites/Games/snapshot/Zelda-Ii-The-Adventure-Of-Link-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Zelda-Ii-The-Adventure-Of-Link-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Zelda-Ii-The-Adventure-Of-Link-2/thumb.jpg',
 'added': 190,
 'background_image': 'https://media.rawg.io/media/screenshots/2dc/2dcc5b76de63a99799364f962334525f.jpg',
 'developers': ['Nintendo'],
 'genres': ['RPG'],
 'name': 'Zelda II: The Adventure of Link',
 'platforms': ['Game Boy Advance', 'Wii', 'Wii U', 'NES', 'Nintendo 3DS'],
 'publishers': ['Nintendo'],
 'released': '1987-01-14',
 'slug': 'zelda-ii-the-adventure-of-link-2'}