{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Star-Trek-First-Contact',
 'EntryURL': 'https://www.imdb.com/title/tt0117731',
 'Entry_json': 'Favorites/Movies/snapshot/Star-Trek-First-Contact/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Star-Trek-First-Contact/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Star-Trek-First-Contact/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Patrick Stewart',
            'url': '/name/nm0001772/'},
           {'@type': 'Person',
            'name': 'Jonathan Frakes',
            'url': '/name/nm0000408/'},
           {'@type': 'Person',
            'name': 'Brent Spiner',
            'url': '/name/nm0000653/'},
           {'@type': 'Person',
            'name': 'LeVar Burton',
            'url': '/name/nm0000996/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 115128,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Gene Roddenberry',
              'url': '/name/nm0734472/'},
             {'@type': 'Person',
              'name': 'Rick Berman',
              'url': '/name/nm0075834/'},
             {'@type': 'Person',
              'name': 'Brannon Braga',
              'url': '/name/nm0103804/'},
             {'@type': 'Person',
              'name': 'Ronald D. Moore',
              'url': '/name/nm0601822/'},
             {'@type': 'Person',
              'name': 'Brannon Braga',
              'url': '/name/nm0103804/'},
             {'@type': 'Person',
              'name': 'Ronald D. Moore',
              'url': '/name/nm0601822/'},
             {'@type': 'Organization', 'url': '/company/co0437457/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'}],
 'datePublished': '1996-11-22',
 'description': 'Star Trek: First Contact is a movie starring Patrick Stewart, '
                'Jonathan Frakes, and Brent Spiner. The Borg travel back in '
                "time intent on preventing Earth's first contact with an alien "
                'species. Captain Picard and his crew pursue them...',
 'director': [{'@type': 'Person',
               'name': 'Jonathan Frakes',
               'url': '/name/nm0000408/'}],
 'duration': 'PT1H51M',
 'genre': ['Action', 'Adventure', 'Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTllZjRkY2QtYTJlMy00ZTMxLWE0YWQtMWMwYzY2YTM3YzRjXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'first contact,post world war three,zefram cochrane '
             'character,experimental technology,nuclear missile',
 'name': 'Star Trek: First Contact',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Paramount Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi1265677337',
              'name': 'Star Trek: First Contact',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjExMjg1ZWItYjAzNy00NTAwLWIxZTgtMTU2NjFjNzE4ZWY2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjExMjg1ZWItYjAzNy00NTAwLWIxZTgtMTU2NjFjNzE4ZWY2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2016-06-03T21:59:48Z'}],
 'url': '/title/tt0117731/'}