<?php
$infoArray = array('Actors' => array('Callum Keith Rennie',
            'Carrie-Anne Moss',
            'Guy Pearce',
            'Harriet Sansom Harris',
            'Joe Pantoliano',
            'Jorja Fox',
            'Kimberly Campbell',
            'Larry Holden',
            'Marianne Muellerleile',
            'Mark Boone Junior',
            'Russ Fega',
            'Stephen Tobolowsky',
            'Thomas Lennon'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nMemento: A man, suffering from short-term memory loss, uses notes and tattoos to hunt for the man he thinks killed his wife. ',
 'Director' => array('Christopher Nolan'),
 'Genres' => array('Thriller', 'Mystery'),
 'IMDB' => 'http://www.imdb.com/title/tt0209144',
 'PrimeWire' => 'http://www.primewire.ag/watch-398-Memento',
 'Ratings' => array('IMDB' => '8.5/10',
             'Metascore' => '80%',
             'PrimeWire' => '3.82/5',
             'RT' => '92%',
             'Votes' => '855'),
 'Released' => '2000-10-11',
 'Runtime' => '113 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/398_Memento_2000.jpg',
 'Title' => 'Memento');
?>