<?php
$infoArray = array('Actors' => array('Adam Brody&tv',
            'Alan Tudyk&tv',
            'Cree Summer&tv',
            'Danny McBride&tv',
            'Debi Mazar&tv',
            'Jake Busey&tv',
            'Josh Gad&tv',
            'Kari Wahlgren&tv',
            'Olivia Thirlby&tv',
            'Tony Hale&tv'),
 'Added' => '2012-03-10',
 'Countries' => array('USA'),
 'Description' => '\nGood Vibes: This coming-of-age story set in a beach town is the brainchild of Pineapple Express director David Gordon Green.\n',
 'Director' => array(),
 'Genres' => array('Animation&tv', 'Comedy&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt1701982',
 'PrimeWire' => 'http://www.primewire.ag/tv-2729235-Good-Vibes',
 'Ratings' => array('IMDB' => '7.5/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.35/5',
             'RT' => 'N/A',
             'Votes' => '168'),
 'Released' => '2011-10-27',
 'Runtime' => 'NA',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2729235_Good_Vibes_2011.jpg',
 'Title' => 'Good-Vibes');
?>