{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-15',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Attack-on-Titan',
 'EntryURL': 'https://www.imdb.com/title/tt2072230',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Attack-on-Titan/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Attack-on-Titan/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Attack-on-Titan/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ashly Burch',
            'url': '/name/nm3950075/'},
           {'@type': 'Person',
            'name': 'Bryce Papenbrook',
            'url': '/name/nm0745310/'},
           {'@type': 'Person',
            'name': 'Monica Rial',
            'url': '/name/nm0722676/'},
           {'@type': 'Person',
            'name': 'Brandon Potter',
            'url': '/name/nm2743770/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 11560,
                     'ratingValue': '5.1',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Hajime Isayama',
              'url': '/name/nm4697729/'},
             {'@type': 'Person',
              'name': 'Tomohiro Machiyama',
              'url': '/name/nm3403795/'},
             {'@type': 'Person',
              'name': 'Yûsuke Watanabe',
              'url': '/name/nm2448218/'},
             {'@type': 'Person',
              'name': 'John Burgmeier',
              'url': '/name/nm0121423/'},
             {'@type': 'Person',
              'name': 'J. Michael Tatum',
              'url': '/name/nm2057312/'},
             {'@type': 'Organization', 'url': '/company/co0021660/'},
             {'@type': 'Organization', 'url': '/company/co0191791/'},
             {'@type': 'Organization', 'url': '/company/co0022792/'},
             {'@type': 'Organization', 'url': '/company/co0002219/'},
             {'@type': 'Organization', 'url': '/company/co0364911/'}],
 'datePublished': '2015-08-01',
 'description': 'Shingeki no kyojin is a movie starring Ashly Burch, Bryce '
                'Papenbrook, and Monica Rial. In a world where giant humanoid '
                'Titans prey on humans, Eren joins the scouting legion to get '
                'revenge on the monsters who killed everyone in his...',
 'director': {'@type': 'Person',
              'name': 'Shinji Higuchi',
              'url': '/name/nm0383688/'},
 'duration': 'PT1H38M',
 'genre': ['Action', 'Adventure', 'Drama', 'Fantasy', 'Horror', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZDk5MTcxZmItYWM2Ny00NjIwLWE2YWQtYjczMWFiZThjN2JkXkEyXkFqcGdeQXVyNDQyNzIwNDQ@._V1_.jpg',
 'keywords': 'live action remake of anime,titan,giant,man eating giant,two '
             'parts',
 'name': 'Shingeki no kyojin',
 'trailer': {'@type': 'VideoObject',
             'description': 'The story of a world where most of humanity has '
                            'been destroyed by giants and where the last of '
                            'mankind fights to survive behind three concentric '
                            'walls - walls that were once impenetrable to the '
                            'giants.',
             'embedUrl': '/video/imdb/vi780120857',
             'name': 'U.S. Theatrical Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjIzMzgxMjE5M15BMl5BanBnXkFtZTgwNjgyMjM5NjE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjIzMzgxMjE5M15BMl5BanBnXkFtZTgwNjgyMjM5NjE@._V1_.jpg',
             'uploadDate': '2015-10-01T09:38:53Z'},
 'url': '/title/tt2072230/'}