{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-20',
 'EntryPath': 'Favorites/Movies/snapshot/Van-Wilder',
 'EntryURL': 'https://www.imdb.com/title/tt0283111',
 'Entry_json': 'Favorites/Movies/snapshot/Van-Wilder/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Van-Wilder/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Van-Wilder/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ryan Reynolds',
            'url': '/name/nm0005351/'},
           {'@type': 'Person', 'name': 'Tara Reid', 'url': '/name/nm0005346/'},
           {'@type': 'Person',
            'name': 'Tim Matheson',
            'url': '/name/nm0001513/'},
           {'@type': 'Person', 'name': 'Kal Penn', 'url': '/name/nm0671980/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 101427,
                      'ratingValue': '6.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Brent Goldberg',
              'url': '/name/nm0325166/'},
             {'@type': 'Person',
              'name': 'David Wagner',
              'url': '/name/nm0905858/'},
             {'@type': 'Organization', 'url': '/company/co0033226/'},
             {'@type': 'Organization', 'url': '/company/co0038746/'},
             {'@type': 'Organization', 'url': '/company/co0031555/'},
             {'@type': 'Organization', 'url': '/company/co0018522/'},
             {'@type': 'Organization', 'url': '/company/co0102282/'}],
 'datePublished': '2002-04-04',
 'description': "National Lampoon's Van Wilder is a movie starring Ryan "
                'Reynolds, Tara Reid, and Tim Matheson. The most popular kid '
                'on campus meets a beautiful journalist who makes him realize '
                "that maybe he's afraid to graduate.",
 'director': [{'@type': 'Person',
               'name': 'Walt Becker',
               'url': '/name/nm0065608/'}],
 'duration': 'PT1H32M',
 'genre': ['Comedy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM4YjQxYzAtNzAyNy00Zjk1LTk4ZTMtNTUwNTBjMWY1M2IwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': "female nudity,fraternity,girls' locker room,boy in girls' locker "
             'room,nude modeling',
 'name': "National Lampoon's Van Wilder",
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Artisan',
              'embedUrl': '/video/imdb/vi2644246809',
              'name': "National Lampoon's Van Wilder",
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYmRlNzQ0ZWUtYmU4NS00OGVkLTljY2YtNGNhOTQ3MGY4Y2FmXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYmRlNzQ0ZWUtYmU4NS00OGVkLTljY2YtNGNhOTQ3MGY4Y2FmXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T15:24:43Z'}],
 'url': '/title/tt0283111/'}