{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fat-Head',
 'EntryURL': 'https://www.imdb.com/title/tt1333994',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fat-Head/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fat-Head/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fat-Head/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Peter Paddon',
            'url': '/name/nm6499665/'},
           {'@type': 'Person',
            'name': 'Tom Naughton',
            'url': '/name/nm3236138/'},
           {'@type': 'Person',
            'name': 'Chareva Naughton',
            'url': '/name/nm3222201/'},
           {'@type': 'Person',
            'name': 'Sally Fallon Morell',
            'url': '/name/nm5055404/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1885,
                     'ratingValue': '7.1',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Tom Naughton',
              'url': '/name/nm3236138/'},
             {'@type': 'Organization', 'url': '/company/co0254955/'},
             {'@type': 'Organization', 'url': '/company/co0143181/'},
             {'@type': 'Organization', 'url': '/company/co0118586/'}],
 'datePublished': '2009-02-03',
 'description': 'Fat Head is a movie starring Peter Paddon, Tom Naughton, and '
                'Chareva Naughton. A comedian replies to the "Super Size Me" '
                'crowd by losing weight on a fast-food diet while '
                'demonstrating that almost everything you think you know '
                'about...',
 'director': {'@type': 'Person',
              'name': 'Tom Naughton',
              'url': '/name/nm3236138/'},
 'duration': 'PT1H44M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk2NjQwMjM3M15BMl5BanBnXkFtZTgwOTMwMzA2MDE@._V1_.jpg',
 'keywords': 'fast food,obesity,food',
 'name': 'Fat Head',
 'url': '/title/tt1333994/'}