{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Murder-Mountain',
 'EntryURL': 'https://www.imdb.com/title/tt9078908',
 'Entry_json': 'Favorites/TV/snapshot/Murder-Mountain/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Murder-Mountain/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Murder-Mountain/thumb.jpg',
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 2171,
                      'ratingValue': '6.9',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0002071/'}],
 'datePublished': '2018-09-23',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BZGE5OTMxMjYtNDNjZi00Y2IwLWI5YTYtOTA1NmM5ZmEwYjJhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'tv mini series,weed,marihuana,marijuana',
 'name': 'Murder Mountain',
 'url': '/title/tt9078908/'}