<?php
$infoArray = array('Actors' => array('Bridget Moynahan',
            'Donald Sutherland',
            'Eamonn Walker',
            'Ethan Hawke',
            'Ian Holm',
            'Inna Swann',
            'Jared Burke',
            'Jared Leto',
            'Jean-Michel Richaud',
            'Jeremy Crutchley',
            'Jerry Mofokeng',
            'Mikhail Gorbachev',
            'Nicolas Cage',
            'Sammi Rotibi',
            'Stephen Hughes',
            'Steve J Termath',
            'Steve Ruge',
            'Tony Caprari',
            'Vadim Dobrin',
            'Yevgeni Lazarev'),
 'Added' => '2013-02-19',
 'Countries' => array('France', 'USA', 'Germany'),
 'Description' => '\nLord of War: An arms dealer confronts the morality of his work as he is being chased by an Interpol agent. ',
 'Director' => array('Andrew Niccol'),
 'Genres' => array('Drama', 'Thriller', 'Crime'),
 'IMDB' => 'http://www.imdb.com/title/tt0399295',
 'PrimeWire' => 'http://www.primewire.ag/watch-746-Lord-of-War',
 'Ratings' => array('IMDB' => '7.6/10',
             'Metascore' => '62%',
             'PrimeWire' => '4.26/5',
             'RT' => '61%',
             'Votes' => '661'),
 'Released' => '2005-09-16',
 'Runtime' => '122 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/746_Lord_of_War_2005.jpg',
 'Title' => 'Lord-of-War');
?>