{'Actors': ['Americo Presciutti',
            'Annette Miller',
            'Austin Lysy',
            'Ben Affleck',
            'Billy Silvia',
            'Cady Huffman',
            'Celeste Oliva',
            'Chris Cooper',
            'Craig T Nelson',
            'Dan Marshall',
            'Dana Eskelson',
            'David Wilson Barnes',
            'Dossy Peabody',
            'Eamonn Walker',
            'John Doman',
            'John Franchi',
            'Keith Fluker',
            'Kent Shocknek',
            'Kevin Costner',
            'Kevin DeCoste',
            'Maria Bello',
            'Maryann Plunkett',
            'Patricia Kalember',
            'Rosemarie DeWitt',
            'Sasha Spielberg',
            'Sean Patrick Doherty',
            'Tom Kemp',
            'Tommy Lee Jones',
            'Tonye Patano',
            'William Hill'],
 'Added': '2013-02-19',
 'Countries': ['UK', 'USA'],
 'Description': '\n'
                'The Company Men: The story centers on a year in the life of '
                'three men trying to survive a round of corporate downsizing '
                'at a major company - and how that affects them, their '
                'families, and their communities. ',
 'Director': ['John Wells'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Company-Men',
 'EntryURL': 'https://www.imdb.com/title/tt1172991',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Company-Men/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Company-Men/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Company-Men/info.py',
 'Genres': ['Drama'],
 'IMDB': 'http://www.imdb.com/title/tt1172991',
 'PrimeWire': 'http://www.primewire.ag/watch-1822877-The-Company-Men',
 'Ratings': {'IMDB': '6.8/10',
             'Metascore': '69%',
             'PrimeWire': '3.94/5',
             'RT': '67%',
             'Votes': '189'},
 'Released': '2011-01-22',
 'Runtime': '104 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1822877_The_Company_Men_2010.jpg',
 'Title': 'The-Company-Men'}