{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Company-Men',
 'EntryURL': 'https://www.imdb.com/title/tt1172991',
 'Entry_json': 'Favorites/Movies/snapshot/The-Company-Men/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Company-Men/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Company-Men/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ben Affleck',
            'url': '/name/nm0000255/'},
           {'@type': 'Person',
            'name': 'Chris Cooper',
            'url': '/name/nm0177933/'},
           {'@type': 'Person',
            'name': 'Tommy Lee Jones',
            'url': '/name/nm0000169/'},
           {'@type': 'Person',
            'name': 'Suzanne Rico',
            'url': '/name/nm0725648/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 42652,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'John Wells',
              'url': '/name/nm0920274/'},
             {'@type': 'Organization', 'url': '/company/co0150452/'},
             {'@type': 'Organization', 'url': '/company/co0320835/'},
             {'@type': 'Organization', 'url': '/company/co0114242/'},
             {'@type': 'Organization', 'url': '/company/co0266180/'}],
 'datePublished': '2011-01-27',
 'description': 'The Company Men is a movie starring Ben Affleck, Chris '
                'Cooper, and Tommy Lee Jones. The story centers on a year in '
                'the life of three men trying to survive a round of corporate '
                'downsizing at a major company - and how that affects...',
 'director': {'@type': 'Person',
              'name': 'John Wells',
              'url': '/name/nm0920274/'},
 'duration': 'PT1H44M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQxMTgyNDc5M15BMl5BanBnXkFtZTcwMzk4OTM5Mw@@._V1_.jpg',
 'keywords': 'downsizing,porsche,corporate downsizing,bra,topless female '
             'nudity',
 'name': 'The Company Men',
 'trailer': {'@type': 'VideoObject',
             'description': 'A year in the life of three men trying to survive '
                            'a round of corporate downsizing at a major '
                            'company - and how that affects them, their '
                            'families, and their communities.',
             'embedUrl': '/video/imdb/vi3740599833',
             'name': 'The Company Men: Trailer #2',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQzNDIwNDg3OF5BMl5BanBnXkFtZTgwMzc3Nzg4MjE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQzNDIwNDg3OF5BMl5BanBnXkFtZTgwMzc3Nzg4MjE@._V1_.jpg',
             'uploadDate': '2010-07-28T09:50:39Z'},
 'url': '/title/tt1172991/'}