{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Eternal-Sunshine-of-the-Spotless-Mind',
 'EntryURL': 'https://www.imdb.com/title/tt0338013',
 'Entry_json': 'Favorites/Movies/snapshot/Eternal-Sunshine-of-the-Spotless-Mind/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Eternal-Sunshine-of-the-Spotless-Mind/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Eternal-Sunshine-of-the-Spotless-Mind/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jim Carrey', 'url': '/name/nm0000120/'},
           {'@type': 'Person',
            'name': 'Kate Winslet',
            'url': '/name/nm0000701/'},
           {'@type': 'Person',
            'name': 'Tom Wilkinson',
            'url': '/name/nm0929489/'},
           {'@type': 'Person',
            'name': 'Gerry Robert Byrne',
            'url': '/name/nm0004423/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 878146,
                      'ratingValue': '8.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Charlie Kaufman',
              'url': '/name/nm0442109/'},
             {'@type': 'Person',
              'name': 'Michel Gondry',
              'url': '/name/nm0327273/'},
             {'@type': 'Person',
              'name': 'Pierre Bismuth',
              'url': '/name/nm1410028/'},
             {'@type': 'Person',
              'name': 'Charlie Kaufman',
              'url': '/name/nm0442109/'},
             {'@type': 'Organization', 'url': '/company/co0042399/'},
             {'@type': 'Organization', 'url': '/company/co0017525/'},
             {'@type': 'Organization', 'url': '/company/co0017713/'}],
 'datePublished': '2004-03-19',
 'description': 'Eternal Sunshine of the Spotless Mind is a movie starring Jim '
                'Carrey, Kate Winslet, and Tom Wilkinson. When their '
                'relationship turns sour, a couple undergoes a medical '
                'procedure to have each other erased from their memories.',
 'director': [{'@type': 'Person',
               'name': 'Michel Gondry',
               'url': '/name/nm0327273/'}],
 'duration': 'PT1H48M',
 'genre': ['Drama', 'Romance', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_.jpg',
 'keywords': "memory,loneliness,retrograde narrative,flashback,valentine's day",
 'name': 'Eternal Sunshine of the Spotless Mind',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer',
              'embedUrl': '/video/imdb/vi2292515097',
              'name': 'Eternal Sunshine of the Spotless Mind',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYTA4YjQ5ZjEtMGQ4Mi00NWExLTkxMGQtNzAwYzVmNTU1ODJjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYTA4YjQ5ZjEtMGQ4Mi00NWExLTkxMGQtNzAwYzVmNTU1ODJjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:01:47Z'}],
 'url': '/title/tt0338013/'}