<?php
$infoArray = array('Actors' => array('David Cross',
            'Debbon Ayer',
            "Deirdre O'Connell",
            'Elijah Wood',
            'Gerry Robert Byrne',
            'Jane Adams',
            'Jim Carrey',
            'Josh Flitter',
            'Kate Winslet',
            'Kirsten Dunst',
            'Mark Ruffalo',
            'Thomas Jay Ryan',
            'Tom Wilkinson'),
 'Added' => '2013-02-24',
 'Countries' => array('USA'),
 'Description' => '\nEternal Sunshine of the Spotless Mind: A couple undergo a procedure to erase each other from their memories when their relationship turns sour, but it is only through the process of loss that they discover what they had to begin with. ',
 'Director' => array('Michel Gondry'),
 'Genres' => array('Drama', 'Romance'),
 'IMDB' => 'http://www.imdb.com/title/tt0338013',
 'PrimeWire' => 'http://www.primewire.ag/watch-403-Eternal-Sunshine-of-the-Spotless-Mind',
 'Ratings' => array('IMDB' => '8.4/10',
             'Metascore' => '89%',
             'PrimeWire' => '4.14/5',
             'RT' => '93%',
             'Votes' => '811'),
 'Released' => '2004-03-19',
 'Runtime' => '108 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/403_Eternal_Sunshine_of_the_Spotless_Mind_2004.jpg',
 'Title' => 'Eternal-Sunshine-of-the-Spotless-Mind');
?>