{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-29',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Takedown',
 'EntryURL': 'https://www.imdb.com/title/tt0159784',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Takedown/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Takedown/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Takedown/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Skeet Ulrich',
            'url': '/name/nm0000240/'},
           {'@type': 'Person',
            'name': 'Russell Wong',
            'url': '/name/nm0005568/'},
           {'@type': 'Person',
            'name': 'Angela Featherstone',
            'url': '/name/nm0004911/'},
           {'@type': 'Person',
            'name': 'Donal Logue',
            'url': '/name/nm0006610/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 6510,
                     'ratingValue': '6.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Tsutomu Shimomura',
              'url': '/name/nm0793737/'},
             {'@type': 'Person',
              'name': 'John Markoff',
              'url': '/name/nm0548586/'},
             {'@type': 'Person',
              'name': 'David Newman',
              'url': '/name/nm0628058/'},
             {'@type': 'Person',
              'name': 'Leslie Newman',
              'url': '/name/nm0628174/'},
             {'@type': 'Person',
              'name': 'John Danza',
              'url': '/name/nm0200729/'},
             {'@type': 'Person',
              'name': 'Howard A. Rodman',
              'url': '/name/nm0734912/'},
             {'@type': 'Organization', 'url': '/company/co0019626/'},
             {'@type': 'Organization', 'url': '/company/co0002572/'},
             {'@type': 'Organization', 'url': '/company/co0279038/'}],
 'datePublished': '2000-03-15',
 'description': 'Takedown is a movie starring Skeet Ulrich, Russell Wong, and '
                'Angela Featherstone. This film is based on the story of the '
                'capture of computer hacker Kevin Mitnick.',
 'director': {'@type': 'Person',
              'name': 'Joe Chappelle',
              'url': '/name/nm0152640/'},
 'duration': 'PT1H36M',
 'genre': ['Biography', 'Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODgyOTJiNzAtYzZkOS00ODM2LTliMTItMDgzMDczZWRlOGJkXkEyXkFqcGdeQXVyNjU2MjA0ODc@._V1_.jpg',
 'keywords': 'computer,hacker,computer hacker,computer virus,based on book',
 'name': 'Takedown',
 'url': '/title/tt0159784/'}