{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Ultima-8-Pagan',
 'EntryURL': 'https://rawg.io/games/ultima-8-pagan',
 'Entry_json': 'Favorites/Games/snapshot/Ultima-8-Pagan/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Ultima-8-Pagan/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Ultima-8-Pagan/thumb.jpg',
 'added': 53,
 'background_image': 'https://media.rawg.io/media/screenshots/c78/c7851aa3b3e7c60f56f675684ba11c3e.jpg',
 'developers': ['Origin Systems'],
 'genres': ['RPG'],
 'name': 'Ultima VIII: Pagan',
 'platforms': ['PC'],
 'publishers': ['Electronic Arts'],
 'released': '1994-01-01',
 'slug': 'ultima-8-pagan'}