{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/God-Of-War',
 'EntryURL': 'https://rawg.io/games/god-of-war',
 'Entry_json': 'Favorites/Games/snapshot/God-Of-War/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/God-Of-War/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/God-Of-War/thumb.jpg',
 'added': 1095,
 'background_image': 'https://media.rawg.io/media/games/1aa/1aa4ca34a8a6bb57a2e065c8332dc230.jpg',
 'developers': ['SCE Santa Monica Studio'],
 'genres': ['Action', 'Adventure'],
 'name': 'God of War (2005)',
 'platforms': ['PS Vita', 'PlayStation 3', 'PlayStation 2'],
 'publishers': ['Sony Computer Entertainment'],
 'released': '2005-03-22',
 'slug': 'god-of-war'}