{'Actors': ['Andrew Sensenig',
            'Brina Palencia',
            'Charles Reynolds',
            'Joy Freeman-DeLeon',
            'Juli Erickson',
            'Ted Ferguson'],
 'Added': '2014-11-01',
 'Countries': ['USA'],
 'Description': '\nUpstream Color: A man and woman are drawn together, entangled in the life cycle of an ageless organism. Identity becomes an illusion as they struggle to assemble the loose fragments of wrecked lives. ',
 'Director': ['Shane Carruth'],
 'Genres': ['Drama'],
 'IMDB': 'http://www.imdb.com/title/tt2084989',
 'PrimeWire': 'http://www.primewire.ag/watch-2739278-Upstream-Color',
 'Ratings': {'IMDB': '6.8/10',
             'Metascore': '81%',
             'PrimeWire': '3.48/5',
             'RT': '84%',
             'Votes': '104'},
 'Released': '2013-02-28',
 'Runtime': '96 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2739278_Upstream_Color_2013.jpg',
 'Title': 'Upstream-Color'}