{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Game-of-Thrones',
 'EntryURL': 'https://www.imdb.com/title/tt0944947',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Game-of-Thrones/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Game-of-Thrones/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Game-of-Thrones/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Emilia Clarke',
            'url': '/name/nm3592338/'},
           {'@type': 'Person',
            'name': 'Peter Dinklage',
            'url': '/name/nm0227759/'},
           {'@type': 'Person',
            'name': 'Kit Harington',
            'url': '/name/nm3229685/'},
           {'@type': 'Person',
            'name': 'Lena Headey',
            'url': '/name/nm0372176/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1679620,
                     'ratingValue': '9.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'David Benioff',
              'url': '/name/nm1125275/'},
             {'@type': 'Person',
              'name': 'D.B. Weiss',
              'url': '/name/nm1888967/'},
             {'@type': 'Organization', 'url': '/company/co0008693/'},
             {'@type': 'Organization', 'url': '/company/co0335036/'},
             {'@type': 'Organization', 'url': '/company/co0167350/'},
             {'@type': 'Organization', 'url': '/company/co0231672/'},
             {'@type': 'Organization', 'url': '/company/co0343278/'}],
 'datePublished': '2011-04-17',
 'description': 'Game of Thrones is a TV series starring Emilia Clarke, Peter '
                'Dinklage, and Kit Harington. Nine noble families fight for '
                'control over the lands of Westeros, while an ancient enemy '
                'returns after being dormant for millennia.',
 'genre': ['Action', 'Adventure', 'Drama', 'Fantasy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
 'keywords': 'based on novel,dragon,politics,queen,nudity',
 'name': 'Game of Thrones',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'hf-15699'},
            'dateCreated': '2020-05-02',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0944947/'},
            'name': 'The beast',
            'reviewBody': "One of the best series I've ever seen, but the last "
                          'season was ruined.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Watch the trailer for the final episode of "Game '
                            'of Thrones."',
             'embedUrl': '/video/imdb/vi3672620057',
             'name': 'Season 8, Episode 6 Preview',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYWU5YTUzYmQtNWRkOS00MmQyLWEzYzAtN2UyOTA2ZTM3N2EyXkEyXkFqcGdeQXZ3ZXNsZXk@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYWU5YTUzYmQtNWRkOS00MmQyLWEzYzAtN2UyOTA2ZTM3N2EyXkEyXkFqcGdeQXZ3ZXNsZXk@._V1_.jpg',
             'uploadDate': '2019-05-13T03:06:22Z'},
 'url': '/title/tt0944947/'}