{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-02-16',
 'EntryPath': 'Favorites/TV/snapshot/112263',
 'EntryURL': 'https://www.imdb.com/title/tt2879552',
 'Entry_json': 'Favorites/TV/snapshot/112263/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/112263/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/112263/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'James Franco',
            'url': '/name/nm0290556/'},
           {'@type': 'Person',
            'name': 'Sarah Gadon',
            'url': '/name/nm0300589/'},
           {'@type': 'Person',
            'name': 'George MacKay',
            'url': '/name/nm1126657/'},
           {'@type': 'Person',
            'name': 'Chris Cooper',
            'url': '/name/nm0177933/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 67672,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Bridget Carpenter',
              'url': '/name/nm1531276/'},
             {'@type': 'Organization', 'url': '/company/co0576000/'},
             {'@type': 'Organization', 'url': '/company/co0021593/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'}],
 'datePublished': '2016-02-15',
 'description': '11.22.63 is a TV mini-series starring James Franco, Sarah '
                'Gadon, and George MacKay. A high school teacher travels back '
                "in time to prevent John F. Kennedy's assassination.",
 'genre': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk1NjE5MjUwM15BMl5BanBnXkFtZTgwODk3NTk2OTE@._V1_.jpg',
 'keywords': 'time travel,historical event,year 1963,dallas texas,conspiracy',
 'name': '11.22.63',
 'trailer': [{'@type': 'VideoObject',
              'description': 'High school teacher Jake Epping travels back in '
                             'time to prevent the assassination of President '
                             'John F. Kennedy - but his mission is threatened '
                             'by Lee Harvey Oswald, falling in love, and the '
                             "past itself, which doesn't want to be changed.",
              'embedUrl': '/video/imdb/vi313242905',
              'name': 'Trailer #1',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTU3NzI5MzcyOV5BMl5BanBnXkFtZTgwODAzNjg2NzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTU3NzI5MzcyOV5BMl5BanBnXkFtZTgwODAzNjg2NzE@._V1_.jpg',
              'uploadDate': '2016-01-12T14:12:59Z'}],
 'url': '/title/tt2879552/'}