{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Vanilla-Sky',
 'EntryURL': 'https://www.imdb.com/title/tt0259711',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Vanilla-Sky/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Vanilla-Sky/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Vanilla-Sky/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Cruise', 'url': '/name/nm0000129/'},
           {'@type': 'Person',
            'name': 'Penélope Cruz',
            'url': '/name/nm0004851/'},
           {'@type': 'Person',
            'name': 'Cameron Diaz',
            'url': '/name/nm0000139/'},
           {'@type': 'Person',
            'name': 'Kurt Russell',
            'url': '/name/nm0000621/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 242260,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alejandro Amenábar',
              'url': '/name/nm0024622/'},
             {'@type': 'Person',
              'name': 'Mateo Gil',
              'url': '/name/nm0317834/'},
             {'@type': 'Person',
              'name': 'Cameron Crowe',
              'url': '/name/nm0001081/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0012382/'},
             {'@type': 'Organization', 'url': '/company/co0047730/'},
             {'@type': 'Organization', 'url': '/company/co0080755/'},
             {'@type': 'Organization', 'url': '/company/co0046206/'},
             {'@type': 'Organization', 'url': '/company/co0014903/'}],
 'datePublished': '2001-12-14',
 'description': 'Vanilla Sky is a movie starring Tom Cruise, Penélope Cruz, '
                'and Cameron Diaz. A self-indulgent and vain publishing '
                'magnate finds his privileged life upended after a vehicular '
                'accident with a resentful lover.',
 'director': {'@type': 'Person',
              'name': 'Cameron Crowe',
              'url': '/name/nm0001081/'},
 'duration': 'PT2H16M',
 'genre': ['Fantasy', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzFlMTJjYzUtMWFjYy00NjkyLTg1Y2EtYmZkMjdlOGQ1ZGYwL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'dream,death,mask,nightmare,mental institution',
 'name': 'Vanilla Sky',
 'url': '/title/tt0259711/'}