{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Team-America-World-Police',
 'EntryURL': 'https://www.imdb.com/title/tt0372588',
 'Entry_json': 'Favorites/Movies/snapshot/Team-America-World-Police/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Team-America-World-Police/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Team-America-World-Police/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Trey Parker',
            'url': '/name/nm0005295/'},
           {'@type': 'Person', 'name': 'Matt Stone', 'url': '/name/nm0001778/'},
           {'@type': 'Person', 'name': 'Elle Russ', 'url': '/name/nm1224826/'},
           {'@type': 'Person',
            'name': 'Kristen Miller',
            'url': '/name/nm0588766/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 157146,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Trey Parker',
              'url': '/name/nm0005295/'},
             {'@type': 'Person',
              'name': 'Matt Stone',
              'url': '/name/nm0001778/'},
             {'@type': 'Person',
              'name': 'Pam Brady',
              'url': '/name/nm0103702/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0093765/'},
             {'@type': 'Organization', 'url': '/company/co0152527/'}],
 'datePublished': '2004-10-15',
 'description': 'Team America: World Police is a movie starring Trey Parker, '
                'Matt Stone, and Elle Russ. Popular Broadway actor Gary '
                'Johnston is recruited by the elite counter-terrorism '
                'organization Team America: World Police. As the world begins '
                'to...',
 'director': [{'@type': 'Person',
               'name': 'Trey Parker',
               'url': '/name/nm0005295/'}],
 'duration': 'PT1H38M',
 'genre': ['Action', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM2Nzc4NjYxMV5BMl5BanBnXkFtZTcwNTM1MTcyMQ@@._V1_.jpg',
 'keywords': 'arab stereotype,strong language,swearing,terrorist,puppetry',
 'name': 'Team America: World Police',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Paramount Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi1166541081',
              'name': 'Team America: World Police',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTEyYmRkYWMtZDMxYi00MmRhLThkZTYtYTgyNzg2MzEwODQ3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTEyYmRkYWMtZDMxYi00MmRhLThkZTYtYTgyNzg2MzEwODQ3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T16:06:52Z'}],
 'url': '/title/tt0372588/'}