{'Actors': ['Daran Norris',
            'David Michie',
            'Fred Tatasciore',
            'Jeremy Shada',
            'Josiah D Lee',
            'Kristen Miller',
            'Masasa Moyo',
            'Matt Stone',
            'Maurice LaMarche',
            'Phil Hendrie',
            'Trey Parker',
            'Victor Yerrid'],
 'Added': '2013-02-24',
 'Countries': ['USA', 'Germany'],
 'Description': '\n'
                'Team America: World Police: Popular Broadway actor Gary '
                'Johnston is recruited by the elite counter-terrorism '
                'organization Team America: World Police. As the world begins '
                'to crumble around him, he must battle with terrorists, '
                'celebrities and falling in love. ',
 'Director': ['Trey Parker'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Team-America-World-Police',
 'EntryURL': 'https://www.imdb.com/title/tt0372588',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Team-America-World-Police/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Team-America-World-Police/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Team-America-World-Police/info.py',
 'Genres': ['Action', 'Animation', 'Comedy', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0372588',
 'PrimeWire': 'http://www.primewire.ag/watch-2185-Team-America-World-Police',
 'Ratings': {'IMDB': '7.2/10',
             'Metascore': '64%',
             'PrimeWire': '3.76/5',
             'RT': '77%',
             'Votes': '420'},
 'Released': '2004-10-11',
 'Runtime': '98 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2185_Team_America_World_Police_2004.jpg',
 'Title': 'Team-America-World-Police'}