{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Hedwig-and-the-Angry-Inch',
 'EntryURL': 'https://www.imdb.com/title/tt0248845',
 'Entry_json': 'Favorites/Movies/snapshot/Hedwig-and-the-Angry-Inch/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Hedwig-and-the-Angry-Inch/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Hedwig-and-the-Angry-Inch/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Cameron Mitchell',
            'url': '/name/nm0593463/'},
           {'@type': 'Person',
            'name': 'Miriam Shor',
            'url': '/name/nm0794896/'},
           {'@type': 'Person',
            'name': 'Stephen Trask',
            'url': '/name/nm0871136/'},
           {'@type': 'Person',
            'name': 'Theodore Liscinski',
            'url': '/name/nm0514007/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 31368,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'John Cameron Mitchell',
              'url': '/name/nm0593463/'},
             {'@type': 'Person',
              'name': 'Stephen Trask',
              'url': '/name/nm0871136/'},
             {'@type': 'Person',
              'name': 'John Cameron Mitchell',
              'url': '/name/nm0593463/'},
             {'@type': 'Organization', 'url': '/company/co0030755/'},
             {'@type': 'Organization', 'url': '/company/co0046718/'}],
 'datePublished': '2001-07-27',
 'description': 'Hedwig and the Angry Inch is a movie starring John Cameron '
                'Mitchell, Miriam Shor, and Stephen Trask. A transgender '
                'punk-rock girl from East Berlin tours the U.S. with her band '
                'as she tells her life story and follows the former...',
 'director': [{'@type': 'Person',
               'name': 'John Cameron Mitchell',
               'url': '/name/nm0593463/'}],
 'duration': 'PT1H35M',
 'genre': ['Comedy', 'Drama', 'Music', 'Musical'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZGY5NWUyNDUtZWJhZi00ZjMxLWFmMjMtYmJhZjVkZGZhNWQ4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'teenage boy,drag,handjob,band,rock band',
 'name': 'Hedwig and the Angry Inch',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A transexual punk rock girl from East Berlin '
                             'tours the US with her rock band as she tells her '
                             'life story and follows the ex-boyfriend/bandmate '
                             'who stole her songs.',
              'embedUrl': '/video/imdb/vi3786146073',
              'name': 'Hedwig and the Angry Inch',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTI3MjMzMzEwM15BMl5BanBnXkFtZTcwMjM2ODY2MQ@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTI3MjMzMzEwM15BMl5BanBnXkFtZTcwMjM2ODY2MQ@@._V1_.jpg',
              'uploadDate': '2008-04-11T14:25:24Z'}],
 'url': '/title/tt0248845/'}