{'Actors': ['Adam Scott',
            'Alfre Woodard',
            'Alice Krige',
            'Annette Helde',
            'Brent Spiner',
            'Cully Fredricksen',
            'Dan Woren',
            'David Cowgill',
            'Don Fischer',
            'Don Stark',
            'Dwight Schultz',
            'Eric Steinberg',
            'Ethan Phillips',
            'Gates McFadden',
            'Heinrich James',
            'Jack Shearer',
            'James Cromwell',
            'James Mapes',
            'Jeff Coopwood',
            'Jonathan Frakes',
            'LeVar Burton',
            'Majel Barrett',
            'Marina Sirtis',
            'Marnie McPhail',
            'Michael Dorn',
            'Michael Horton',
            'Michael Zaslow',
            'Neal McDonough',
            'Patrick Stewart',
            'Patti Yasutake',
            'Ray Uhler',
            'Robert Picardo',
            'Robert Zachar',
            'Ronnie Rondell Jr',
            'Scott Haven',
            'Victor Bevine'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\nStar Trek: First Contact: Capt. Picard and his crew pursue the Borg back in time to stop them from preventing Earth from initiating first contact with alien life. ',
 'Director': ['Jonathan Frakes'],
 'Genres': ['Action', 'Thriller', 'Sci-Fi', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0117731',
 'PrimeWire': 'http://www.primewire.ag/watch-146-Star-Trek-First-Contact',
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': '71%',
             'PrimeWire': '4.00/5',
             'RT': '92%',
             'Votes': '249'},
 'Released': '1996-11-22',
 'Runtime': '111 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/146_Star_Trek_First_Contact_1996.jpg',
 'Title': 'Star-Trek-First-Contact'}