{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontier',
 'EntryURL': 'https://www.imdb.com/title/tt4686698',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontier/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontier/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Frontier/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jason Momoa',
            'url': '/name/nm0597388/'},
           {'@type': 'Person',
            'name': 'Landon Liboiron',
            'url': '/name/nm2334994/'},
           {'@type': 'Person', 'name': 'Zoe Boyle', 'url': '/name/nm3018580/'},
           {'@type': 'Person', 'name': 'Greg Bryk', 'url': '/name/nm0117374/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 15472,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Rob Blackie',
              'url': '/name/nm1265275/'},
             {'@type': 'Person',
              'name': 'Peter Blackie',
              'url': '/name/nm4274105/'},
             {'@type': 'Organization', 'url': '/company/co0370709/'}],
 'datePublished': '2016-11-06',
 'description': 'Frontier is a TV series starring Jason Momoa, Landon '
                'Liboiron, and Zoe Boyle. Follows Declan Harp, a '
                'half-Irish/half Cree Native-Canadian outlaw who is '
                "campaigning to breach the Hudson's Bay Company's monopoly on "
                'the fur trade in...',
 'genre': ['Adventure', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2M1YTk0ZmYtZjJhOC00OTdkLThiZTYtYTQ5MzIwMzRlZGMyXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_.jpg',
 'keywords': 'canada,historical,first nations,red coat,biracial',
 'name': 'Frontier',
 'trailer': {'@type': 'VideoObject',
             'description': 'While Harp pursues Lord Benton to rescue Grace, '
                            'Michael takes command of the Black Wolf Company '
                            'and Sokanon embarks on a righteous crusade.',
             'embedUrl': '/video/imdb/vi2531375641',
             'name': 'Season 3 Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZWJjZTVmMWItODEwYy00NWJmLTg0OTEtNzBlNTI1MjA1YWIwXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZWJjZTVmMWItODEwYy00NWJmLTg0OTEtNzBlNTI1MjA1YWIwXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
             'uploadDate': '2018-11-16T00:22:40Z'},
 'url': '/title/tt4686698/'}