{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Crank',
 'EntryURL': 'https://www.imdb.com/title/tt0479884',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Crank/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Crank/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Crank/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jason Statham',
            'url': '/name/nm0005458/'},
           {'@type': 'Person', 'name': 'Amy Smart', 'url': '/name/nm0005442/'},
           {'@type': 'Person',
            'name': 'Carlos Sanz',
            'url': '/name/nm0764430/'},
           {'@type': 'Person',
            'name': 'Jose Pablo Cantillo',
            'url': '/name/nm1504678/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 229507,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mark Neveldine',
              'url': '/name/nm0004410/'},
             {'@type': 'Person',
              'name': 'Brian Taylor',
              'url': '/name/nm0962729/'},
             {'@type': 'Organization', 'url': '/company/co0005323/'},
             {'@type': 'Organization', 'url': '/company/co0060306/'},
             {'@type': 'Organization', 'url': '/company/co0029540/'},
             {'@type': 'Organization', 'url': '/company/co0025423/'}],
 'datePublished': '2006-08-31',
 'description': 'Crank is a movie starring Jason Statham, Amy Smart, and '
                'Carlos Sanz. Professional assassin Chev Chelios learns his '
                'rival has injected him with a poison that will kill him if '
                'his heart rate drops.',
 'director': [{'@type': 'Person',
               'name': 'Mark Neveldine',
               'url': '/name/nm0004410/'},
              {'@type': 'Person',
               'name': 'Brian Taylor',
               'url': '/name/nm0962729/'}],
 'duration': 'PT1H28M',
 'genre': ['Action', 'Crime', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjg0NjAxNDY4MV5BMl5BanBnXkFtZTcwODA5MjMzMw@@._V1_.jpg',
 'keywords': 'upskirt,heart,poison,bare breasts,public sex',
 'name': 'Crank',
 'trailer': {'@type': 'VideoObject',
             'description': 'A man with an hour to live exacts revenge on his '
                            'murderers in this trailer',
             'embedUrl': '/video/imdb/vi3364028953',
             'name': 'Crank',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2FlZTk5N2EtMTY5ZC00NTE5LWIwNmUtOTdhMWVjYTVhNGZjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2FlZTk5N2EtMTY5ZC00NTE5LWIwNmUtOTdhMWVjYTVhNGZjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2009-05-31T03:28:05Z'},
 'url': '/title/tt0479884/'}