<?php
$infoArray = array('Actors' => array('Allen Bloomfield',
            'Amy Smart',
            'Carlos Sanz',
            'Dan Callahan',
            'David Brown',
            'Donnie Smith',
            'Dorian Kingi',
            'Dwight Yoakam',
            'Earl Carroll',
            'Eddie Perez',
            'Edi Gathegi',
            'Efren Ramirez',
            'Francis Capra',
            'Glenn Howerton',
            'Jacki R Chan',
            'Jason Statham',
            'Jose Pablo Cantillo',
            'Ken Moreno',
            'Keone Young',
            'Laurent Schwaar',
            'Michael McLafferty',
            'Noel Gugliemi',
            'Reno Wilson',
            'Rick Shuster',
            'Sam Witwer',
            'Sean Graham',
            'Stephanie Mace',
            'Ted Garcia',
            'Toshi Toda',
            'Troy Robinson',
            'Valarie Rae Miller'),
 'Added' => '2013-02-24',
 'Countries' => array('USA'),
 'Description' => '\nCrank: Professional assassin Chev Chelios learns his rival has injected him with a poison that will kill him if his heart rate drops. ',
 'Director' => array('Mark Neveldine'),
 'Genres' => array('Action', 'Drama', 'Thriller', 'Crime'),
 'IMDB' => 'http://www.imdb.com/title/tt0479884',
 'PrimeWire' => 'http://www.primewire.ag/watch-1792-Crank',
 'Ratings' => array('IMDB' => '7.0/10',
             'Metascore' => '57%',
             'PrimeWire' => '4.01/5',
             'RT' => '61%',
             'Votes' => '485'),
 'Released' => '2006-08-31',
 'Runtime' => '88 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1792_Crank_2006.jpg',
 'Title' => 'Crank');
?>