{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/TV/snapshot/House-of-Cards',
 'EntryURL': 'https://www.imdb.com/title/tt1856010',
 'Entry_json': 'Favorites/TV/snapshot/House-of-Cards/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/House-of-Cards/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/House-of-Cards/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kevin Spacey',
            'url': '/name/nm0000228/'},
           {'@type': 'Person',
            'name': 'Michel Gill',
            'url': '/name/nm0318703/'},
           {'@type': 'Person',
            'name': 'Robin Wright',
            'url': '/name/nm0000705/'},
           {'@type': 'Person', 'name': 'Kate Mara', 'url': '/name/nm0544718/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 451959,
                     'ratingValue': '8.7',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Beau Willimon',
              'url': '/name/nm2802722/'},
             {'@type': 'Organization', 'url': '/company/co0194736/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0375454/'},
             {'@type': 'Organization', 'url': '/company/co0148949/'}],
 'datePublished': '2013-02-01',
 'description': 'House of Cards is a TV series starring Kevin Spacey, Michel '
                'Gill, and Robin Wright. A Congressman works with his equally '
                'conniving wife to exact revenge on the people who betrayed '
                'him.',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BODM1MDU2NjY5NF5BMl5BanBnXkFtZTgwMDkxNTcwNjM@._V1_.jpg',
 'keywords': 'political corruption,government corruption,media '
             'manipulation,machiavellianism,husband wife relationship',
 'name': 'House of Cards',
 'trailer': {'@type': 'VideoObject',
             'description': 'The final season of "House Of Cards" premieres '
                            'Nov. 2, 2018.',
             'embedUrl': '/video/imdb/vi4155226649',
             'name': 'Season 6: Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjA1N2EyNjctNGQ2Ny00ZjhmLWJkZTktYzYwY2VhY2Y2MGY3XkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjA1N2EyNjctNGQ2Ny00ZjhmLWJkZTktYzYwY2VhY2Y2MGY3XkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
             'uploadDate': '2018-10-08T13:06:10Z'},
 'url': '/title/tt1856010/'}