{'Actors': ['Ben Daniels&tv',
            'Constance Zimmer&tv',
            'Corey Stoll&tv',
            'Gilbert Soto&tv',
            'Kevin Spacey&tv',
            'Michael Kelly&tv',
            'Robin Wright&tv',
            'Sakina Jaffrey&tv',
            'Sandrine Holt&tv'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                'House of Cards: Francis Underwood is Majority Whip. He has '
                'his hands on every secret in politics - and is willing to '
                'betray them all to become President. ',
 'Director': ['NA'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-of-Cards',
 'EntryURL': 'http://www.imdb.com/title/tt1856010',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-of-Cards/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-of-Cards/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-of-Cards/info.py',
 'Genres': ['Drama&tv', 'Thriller&tv'],
 'IMDB': 'http://www.imdb.com/title/tt1856010',
 'PrimeWire': 'http://www.primewire.ag/tv-2759743-House-of-Cards',
 'Ratings': {'IMDB': '9.1/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.48/5',
             'RT': 'N/A',
             'Votes': '128'},
 'Released': '2013-02-01',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2737643_House_of_Cards_2013.jpg',
 'Title': 'House-of-Cards'}