{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Braveheart',
 'EntryURL': 'https://www.imdb.com/title/tt0112573',
 'Entry_json': 'Favorites/Movies/snapshot/Braveheart/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Braveheart/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Braveheart/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Mel Gibson', 'url': '/name/nm0000154/'},
           {'@type': 'Person',
            'name': 'Sophie Marceau',
            'url': '/name/nm0000521/'},
           {'@type': 'Person',
            'name': 'Patrick McGoohan',
            'url': '/name/nm0001526/'},
           {'@type': 'Person',
            'name': 'Angus Macfadyen',
            'url': '/name/nm0005171/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 933568,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Randall Wallace',
              'url': '/name/nm0908824/'},
             {'@type': 'Organization', 'url': '/company/co0000700/'},
             {'@type': 'Organization', 'url': '/company/co0042559/'},
             {'@type': 'Organization', 'url': '/company/co0078539/'},
             {'@type': 'Organization', 'url': '/company/co0073417/'}],
 'datePublished': '1995-05-24',
 'description': 'Braveheart is a movie starring Mel Gibson, Sophie Marceau, '
                'and Patrick McGoohan. When his secret bride is executed for '
                'assaulting an English soldier who tried to rape her, William '
                'Wallace begins a revolt against King Edward I of...',
 'director': {'@type': 'Person',
              'name': 'Mel Gibson',
              'url': '/name/nm0000154/'},
 'duration': 'PT2H58M',
 'genre': ['Biography', 'Drama', 'History', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzkzMmU0YTYtOWM3My00YzBmLWI0YzctOGYyNTkwMWE5MTJkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'scotland,revolt,england,legend,idealism',
 'name': 'Braveheart',
 'trailer': {'@type': 'VideoObject',
             'embedUrl': '/video/imdb/vi2874063641',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZmIyZmUwMjgtMjU4OC00MDgxLWIxZWEtODM4NjcwZTJjYTVkXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZmIyZmUwMjgtMjU4OC00MDgxLWIxZWEtODM4NjcwZTJjYTVkXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
             'uploadDate': '2018-09-20T18:51:30Z'},
 'url': '/title/tt0112573/'}