{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-11-02',
 'EntryPath': 'Favorites/Movies/snapshot/The-Cabin-in-the-Woods',
 'EntryURL': 'https://www.imdb.com/title/tt1259521',
 'Entry_json': 'Favorites/Movies/snapshot/The-Cabin-in-the-Woods/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Cabin-in-the-Woods/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Cabin-in-the-Woods/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kristen Connolly',
            'url': '/name/nm1393354/'},
           {'@type': 'Person',
            'name': 'Chris Hemsworth',
            'url': '/name/nm1165110/'},
           {'@type': 'Person',
            'name': 'Anna Hutchison',
            'url': '/name/nm0404307/'},
           {'@type': 'Person',
            'name': 'Fran Kranz',
            'url': '/name/nm0469823/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 364940,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Joss Whedon',
              'url': '/name/nm0923736/'},
             {'@type': 'Person',
              'name': 'Drew Goddard',
              'url': '/name/nm1206844/'},
             {'@type': 'Organization', 'url': '/company/co0173285/'},
             {'@type': 'Organization', 'url': '/company/co0009514/'},
             {'@type': 'Organization', 'url': '/company/co0007143/'},
             {'@type': 'Organization', 'url': '/company/co0026841/'},
             {'@type': 'Organization', 'url': '/company/co0160898/'}],
 'datePublished': '2012-04-12',
 'description': 'The Cabin in the Woods is a movie starring Kristen Connolly, '
                'Chris Hemsworth, and Anna Hutchison. Five friends go for a '
                'break at a remote cabin, where they get more than they '
                'bargained for, discovering the truth behind the cabin in...',
 'director': [{'@type': 'Person',
               'name': 'Drew Goddard',
               'url': '/name/nm1206844/'}],
 'duration': 'PT1H35M',
 'genre': 'Horror',
 'image': 'https://m.media-amazon.com/images/M/MV5BNTUxNzYyMjg2N15BMl5BanBnXkFtZTcwMTExNzExNw@@._V1_.jpg',
 'keywords': 'cabin in the woods,interrupted sex,girl stripped down to '
             'panties,lovecraftian,oral sex',
 'name': 'The Cabin in the Woods',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Five friends go for a break at a remote cabin in '
                             'the woods, where they get more than they '
                             'bargained for. Together, they must discover the '
                             'truth behind the cabin in the woods.',
              'embedUrl': '/video/imdb/vi2572394777',
              'name': 'No.2',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTk0NTI3NDAzM15BMl5BanBnXkFtZTcwNDAyODA1Nw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTk0NTI3NDAzM15BMl5BanBnXkFtZTcwNDAyODA1Nw@@._V1_.jpg',
              'uploadDate': '2012-03-08T13:42:33Z'}],
 'url': '/title/tt1259521/'}