{'Actors': ['Alfie Allen&tv',
            'Ciaran Bermingham&tv',
            'Donald Sumpter&tv',
            'Emilia Clarke&tv',
            'Finn Jones&tv',
            'Harry Lloyd&tv',
            'Iain Glen&tv',
            'Jack Gleeson&tv',
            'Jason Momoa&tv',
            'Joseph Mawle&tv',
            'Kit Harington&tv',
            'Kristian Nairn&tv',
            'Lena Headey&tv',
            'Maisie Williams&tv',
            'Mark Addy&tv',
            'Michelle Fairley&tv',
            'Natalia Tena&tv',
            'Nikolaj Coster-Waldau&tv',
            'Peter Dinklage&tv',
            'Rory McCann&tv',
            'Roy Dotrice&tv',
            'Sean Bean&tv'],
 'Added': '2011-08-19',
 'Countries': ['USA'],
 'Description': "\nGame of Thrones: Seven noble families fight for control of the mythical land of Westeros. Political and sexual intrigue abound. The primary families are the Stark, Lannister, and Baratheon families. Robert Baratheon, King of Westeros, asks his old friend Eddard Stark to serve as his chief advisor. Eddard, suspecting that his predecessor had been murdered, accepts so that he can investigate further. It turns out more than one family is plotting to take the throne. The Queen's family, the Lannisters, may be hatching a plot to take control. Across the sea, the last surviving members of the previously deposed ruling family, the Targaryens, are also plotting a return to power. The conflict between these families and others, including the Greyjoys, the Tullys, the Arryns, and the Tyrells, leads to war. Meanwhile, in the north, an ancient evil awakens. Amidst war and the political confusion, a brotherhood of misfits, The Night's Watch, is all that stands between the realms of men and the horrors beyond. ",
 'Director': [],
 'Genres': ['Adventure&tv', 'Drama&tv', 'Fantasy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0944947',
 'PrimeWire': 'http://www.primewire.ag/tv-1386995-Game-of-Thrones',
 'Ratings': {'IMDB': '9.5/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.59/5',
             'RT': 'N/A',
             'Votes': '12728'},
 'Released': '2011-04-17',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1386995_Game_of_Thrones_2011_81.jpg',
 'Title': 'Game-of-Thrones'}