{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/Breaking-Bad',
 'EntryURL': 'https://www.imdb.com/title/tt0903747',
 'Entry_json': 'Favorites/TV/snapshot/Breaking-Bad/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Breaking-Bad/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Breaking-Bad/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bryan Cranston',
            'url': '/name/nm0186505/'},
           {'@type': 'Person', 'name': 'Aaron Paul', 'url': '/name/nm0666739/'},
           {'@type': 'Person', 'name': 'Anna Gunn', 'url': '/name/nm0348152/'},
           {'@type': 'Person',
            'name': 'Betsy Brandt',
            'url': '/name/nm1336827/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1359381,
                      'ratingValue': '9.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Vince Gilligan',
              'url': '/name/nm0319213/'},
             {'@type': 'Organization', 'url': '/company/co0212797/'},
             {'@type': 'Organization', 'url': '/company/co0071947/'},
             {'@type': 'Organization', 'url': '/company/co0086397/'},
             {'@type': 'Organization', 'url': '/company/co0019701/'}],
 'datePublished': '2008-01-20',
 'description': 'Breaking Bad is a TV series starring Bryan Cranston, Aaron '
                'Paul, and Anna Gunn. A high school chemistry teacher '
                'diagnosed with inoperable lung cancer turns to manufacturing '
                'and selling methamphetamine in order to secure his '
                "family's...",
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'cancer,crystal meth,albuquerque new '
             'mexico,chemistry,methamphetamine',
 'name': 'Breaking Bad',
 'trailer': [{'@type': 'VideoObject',
              'description': "Here's a look at the final eight episodes of "
                             'Breaking Bad, which premieres on Sunday, August '
                             '11 at 9/8c',
              'embedUrl': '/video/imdb/vi338798873',
              'name': '"Say My Name"',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTJiMzgwZTktYzZhZC00YzhhLWEzZDUtMGM2NTE4MzQ4NGFmXkEyXkFqcGdeQWpybA@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTJiMzgwZTktYzZhZC00YzhhLWEzZDUtMGM2NTE4MzQ4NGFmXkEyXkFqcGdeQWpybA@@._V1_.jpg',
              'uploadDate': '2013-08-06T09:15:19Z'}],
 'url': '/title/tt0903747/'}