{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Life',
 'EntryURL': 'https://www.imdb.com/title/tt5442430',
 'Entry_json': 'Favorites/Movies/snapshot/Life/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Life/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Life/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jake Gyllenhaal',
            'url': '/name/nm0350453/'},
           {'@type': 'Person',
            'name': 'Rebecca Ferguson',
            'url': '/name/nm0272581/'},
           {'@type': 'Person',
            'name': 'Ryan Reynolds',
            'url': '/name/nm0005351/'},
           {'@type': 'Person',
            'name': 'Hiroyuki Sanada',
            'url': '/name/nm0760796/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 198454,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Rhett Reese',
              'url': '/name/nm1014201/'},
             {'@type': 'Person',
              'name': 'Paul Wernick',
              'url': '/name/nm1116660/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0152219/'},
             {'@type': 'Organization', 'url': '/company/co0152219/'},
             {'@type': 'Organization', 'url': '/company/co0479739/'}],
 'datePublished': '2017-03-22',
 'description': 'Life is a movie starring Jake Gyllenhaal, Rebecca Ferguson, '
                'and Ryan Reynolds. A team of scientists aboard the '
                'International Space Station discover a rapidly evolving life '
                'form that caused extinction on Mars and now threatens all...',
 'director': {'@type': 'Person',
              'name': 'Daniel Espinosa',
              'url': '/name/nm1174251/'},
 'duration': 'PT1H44M',
 'genre': ['Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzAwMmQxNTctYjVmYi00MDdlLWEzMWUtOTE5NTRiNDhhNjI2L2ltYWdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'extraterrestrial life,international space '
             'station,astronaut,space station,outer space',
 'name': 'Life',
 'trailer': {'@type': 'VideoObject',
             'description': 'An international space crew discovers life on '
                            'Mars.',
             'embedUrl': '/video/imdb/vi376026649',
             'name': 'Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDdiNjI5ZWUtMWZjMy00YjFjLTk4NTYtNjU5N2Q2NzhiMjFkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDdiNjI5ZWUtMWZjMy00YjFjLTk4NTYtNjU5N2Q2NzhiMjFkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg',
             'uploadDate': '2017-03-03T19:30:08Z'},
 'url': '/title/tt5442430/'}