{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cavalcade-of-Cartoon-Comedy',
 'EntryURL': 'https://www.imdb.com/title/tt1295036',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cavalcade-of-Cartoon-Comedy/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cavalcade-of-Cartoon-Comedy/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cavalcade-of-Cartoon-Comedy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Seth MacFarlane',
            'url': '/name/nm0532235/'},
           {'@type': 'Person',
            'name': 'Alec Sulkin',
            'url': '/name/nm1273148/'},
           {'@type': 'Person',
            'name': 'Rachael MacFarlane',
            'url': '/name/nm1484134/'},
           {'@type': 'Person',
            'name': 'John Viener',
            'url': '/name/nm0896742/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2715,
                     'ratingValue': '6.5',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Seth MacFarlane',
              'url': '/name/nm0532235/'},
             {'@type': 'Organization', 'url': '/company/co0065872/'},
             {'@type': 'Organization', 'url': '/company/co0194736/'},
             {'@type': 'Organization', 'url': '/company/co0248494/'},
             {'@type': 'Organization', 'url': '/company/co0159275/'}],
 'datePublished': '2008-09-09',
 'description': "Seth MacFarlane's Cavalcade of Cartoon Comedy is a TV series "
                'starring Seth MacFarlane, Alec Sulkin, and Rachael '
                'MacFarlane. A series of short, non-sequitur skits that could '
                'never be shown as cutaway gags on Family Guy (1999) - but...',
 'genre': ['Animation', 'Short', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZjM2Y2M0NWEtZjAxMi00ZTk2LThhNGQtNmI3NGNlZWRhNTE0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'slapstick comedy,gross out comedy,political satire,absurd '
             'humor,parody',
 'name': "Seth MacFarlane's Cavalcade of Cartoon Comedy",
 'trailer': {'@type': 'VideoObject',
             'description': "Seth Macfarlane's Cavalcade Of Cartoon Comedy",
             'embedUrl': '/video/imdb/vi2862529561',
             'name': "Seth Macfarlane's Cavalcade Of Cartoon Comedy",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODUyYzRjMDMtZDA2NS00ZTMyLTgwOTQtYWNhMjBkNmVhNGM4XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODUyYzRjMDMtZDA2NS00ZTMyLTgwOTQtYWNhMjBkNmVhNGM4XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-04-22T20:37:53Z'},
 'url': '/title/tt1295036/'}