{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/The-Good-Place',
 'EntryURL': 'https://www.imdb.com/title/tt4955642',
 'Entry_json': 'Favorites/TV/snapshot/The-Good-Place/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Good-Place/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Good-Place/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kristen Bell',
            'url': '/name/nm0068338/'},
           {'@type': 'Person',
            'name': 'William Jackson Harper',
            'url': '/name/nm2860379/'},
           {'@type': 'Person',
            'name': 'Jameela Jamil',
            'url': '/name/nm3553139/'},
           {'@type': 'Person',
            'name': "D'Arcy Carden",
            'url': '/name/nm3639013/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 96467,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Michael Schur',
              'url': '/name/nm1321658/'},
             {'@type': 'Organization', 'url': '/company/co0447669/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0046592/'}],
 'datePublished': '2016-09-19',
 'description': 'The Good Place is a TV series starring Kristen Bell, William '
                'Jackson Harper, and Jameela Jamil. Four people and their '
                'otherworldly frienemy struggle in the afterlife to define '
                'what it means to be good.',
 'genre': ['Comedy', 'Drama', 'Fantasy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYmMxNjM0NmItNGU1Mi00OGMwLTkzMzctZmE3YjU1ZDE4NmFjXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg',
 'keywords': 'afterlife,utopia,heaven,ethics,neighborhood',
 'name': 'The Good Place',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi3148002841',
              'name': 'The Good Place Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTczNzExMDM1MF5BMl5BanBnXkFtZTgwMTU2NTY5OTE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTczNzExMDM1MF5BMl5BanBnXkFtZTgwMTU2NTY5OTE@._V1_.jpg',
              'uploadDate': '2016-09-08T08:02:04Z'}],
 'url': '/title/tt4955642/'}