{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/A-Scanner-Darkly',
 'EntryURL': 'https://www.imdb.com/title/tt0405296',
 'Entry_json': 'Favorites/Movies/snapshot/A-Scanner-Darkly/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/A-Scanner-Darkly/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/A-Scanner-Darkly/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Keanu Reeves',
            'url': '/name/nm0000206/'},
           {'@type': 'Person',
            'name': 'Winona Ryder',
            'url': '/name/nm0000213/'},
           {'@type': 'Person',
            'name': 'Robert Downey Jr.',
            'url': '/name/nm0000375/'},
           {'@type': 'Person',
            'name': 'Rory Cochrane',
            'url': '/name/nm0168262/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 104288,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Philip K. Dick',
              'url': '/name/nm0001140/'},
             {'@type': 'Person',
              'name': 'Richard Linklater',
              'url': '/name/nm0000500/'},
             {'@type': 'Organization', 'url': '/company/co0106448/'},
             {'@type': 'Organization', 'url': '/company/co0042682/'},
             {'@type': 'Organization', 'url': '/company/co0013349/'},
             {'@type': 'Organization', 'url': '/company/co0123642/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'}],
 'datePublished': '2006-07-28',
 'description': 'A Scanner Darkly is a movie starring Keanu Reeves, Winona '
                'Ryder, and Robert Downey Jr.. An undercover cop in a '
                'not-too-distant future becomes involved with a dangerous new '
                'drug and begins to lose his own identity as a result.',
 'director': [{'@type': 'Person',
               'name': 'Richard Linklater',
               'url': '/name/nm0000500/'}],
 'duration': 'PT1H40M',
 'genre': ['Animation', 'Crime', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTc2ZGI2MzEtODlkNC00MGQ4LTlkYjQtMDU0YTg1YTI0NDI1L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'rotoscoping,covered in bugs,lodge meeting,washing a dog,collie '
             'dog',
 'name': 'A Scanner Darkly',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Warner Independent '
                             'Pictures',
              'embedUrl': '/video/imdb/vi3384017177',
              'name': 'A Scanner Darkly',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODllNzNkYzEtMDRlZi00ODAxLWI4NDktYWNmZGRiYjU3YTJhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODllNzNkYzEtMDRlZi00ODAxLWI4NDktYWNmZGRiYjU3YTJhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T07:45:00Z'}],
 'url': '/title/tt0405296/'}