{'Actors': [],
 'Added': '2015-02-07',
 'Countries': ['USA'],
 'Description': "\nHuman Revolution: Based on the video game Deus Ex Human revolution, the film dives into the world of Adam Jensen, a serif industries' security consultant that gets augmented after an incident that almost took his life away. ",
 'Director': ['Moe Charif'],
 'Genres': ['Action', 'Short'],
 'IMDB': 'http://www.imdb.com/title/tt3619204',
 'PrimeWire': 'http://www.primewire.ag/watch-2757751-Human-Revolution',
 'Ratings': {'IMDB': '7.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.83/5',
             'RT': 'N/A',
             'Votes': '95'},
 'Released': '2014-03-25',
 'Runtime': '12 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2757751_Human_Revolution_2014.jpg',
 'Title': 'Human-Revolution'}