{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-02-07',
 'EntryPath': 'Favorites/Movies/snapshot/Human-Revolution',
 'EntryURL': 'https://www.imdb.com/title/tt3619204',
 'Entry_json': 'Favorites/Movies/snapshot/Human-Revolution/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Human-Revolution/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Human-Revolution/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bayardo Cesar Ampie',
            'url': '/name/nm6379108/'},
           {'@type': 'Person',
            'name': 'Juan Bofill',
            'url': '/name/nm1282524/'},
           {'@type': 'Person',
            'name': 'Shayna Bofill',
            'url': '/name/nm4754557/'},
           {'@type': 'Person',
            'name': 'Liannet Borrego',
            'url': '/name/nm2546327/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 241,
                      'ratingValue': '6.7',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Moe Charif',
              'url': '/name/nm2332084/'},
             {'@type': 'Organization', 'url': '/company/co0475436/'}],
 'datePublished': '2014-03-25',
 'description': 'Human Revolution is a short starring Bayardo Cesar Ampie, '
                'Juan Bofill, and Shayna Bofill. Based on the video game Deus '
                'Ex: Human Revolution (2011), the film dives into the world of '
                "Adam Jensen, a Sarif Industries' security...",
 'director': [{'@type': 'Person',
               'name': 'Moe Charif',
               'url': '/name/nm2332084/'}],
 'duration': 'PT12M',
 'genre': ['Short', 'Action'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2U1OWNkZjMtZjM4ZC00Y2YwLWE3OWItNGJjOThmNGRkYjVlXkEyXkFqcGdeQXVyNDE4OTY5NzI@._V1_.jpg',
 'name': 'Human Revolution',
 'url': '/title/tt3619204/'}