{'Actors': ['Annie Parisse',
            'Ari Barak',
            'Aura Figueiredo',
            'Brandon Keener',
            'Bruce Willis',
            'Catherine Keener',
            'Christopher Evan Welch',
            'Dave Johnson',
            'David Pearl',
            'Dennis Albanese',
            'Dey Young',
            'Don Abernathy',
            'Eric Shackelford',
            'Felix J Boyle',
            'Floanne Ankah',
            'Gary Teague',
            'Gene Richards',
            'Graham Clarke',
            'Jared Morrison',
            'Jason Kravits',
            'Jay Ferraro',
            'Jean-Michel Richaud',
            'Jill Flint',
            'John Robert',
            'John Turturro',
            'JR Garcia',
            'Kate Burton',
            'Kazu Nagahama',
            'Kristen Stewart',
            'Laurie Lee',
            'Lily Rabe',
            'Linda Lee',
            'Lindy Booth',
            'Logan Grove',
            'Lombardo Boyar',
            'Lu Johnson',
            'Marin Hinkle',
            'Mark Ivanir',
            'Massi Furlan',
            'Michael Lovern',
            'Michael Wincott',
            'Michelle Elkin',
            'Monica Ramon',
            'Moon Bloodgood',
            'Patrizia Barretto',
            'Paul Herman',
            'Paul Lieber',
            'Peter Jacobson',
            'Remy K Selma',
            'Robert De Niro',
            'Robin Wright',
            'Scott L Treger',
            'Sean Penn',
            'Sonny Vellozzi',
            'Stanley Tucci',
            'Tommy Gerrits',
            'Vincent De Paul',
            'William Ragsdale'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'What Just Happened: Two weeks in the life of a fading '
                "Hollywood producer who's having a rough time trying to get "
                'his new picture made. ',
 'Director': ['Barry Levinson'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//What-Just-Happened',
 'EntryURL': 'http://www.imdb.com/title/tt0486674',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//What-Just-Happened/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//What-Just-Happened/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//What-Just-Happened/info.py',
 'Genres': ['Drama', 'Comedy'],
 'IMDB': 'http://www.imdb.com/title/tt0486674',
 'PrimeWire': 'http://www.primewire.ag/watch-469-What-Just-Happened',
 'Ratings': {'IMDB': '5.7/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.09/5',
             'RT': '51%',
             'Votes': '102'},
 'Released': '2008-11-28',
 'Runtime': '104 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/469_What_Just_Happened_2008.jpg',
 'Title': 'What-Just-Happened'}