{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/What-Just-Happened',
 'EntryURL': 'https://www.imdb.com/title/tt0486674',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/What-Just-Happened/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/What-Just-Happened/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/What-Just-Happened/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Robert De Niro',
            'url': '/name/nm0000134/'},
           {'@type': 'Person',
            'name': 'John Turturro',
            'url': '/name/nm0001806/'},
           {'@type': 'Person',
            'name': 'Stanley Tucci',
            'url': '/name/nm0001804/'},
           {'@type': 'Person', 'name': 'Sean Penn', 'url': '/name/nm0000576/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 26149,
                     'ratingValue': '5.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Art Linson',
              'url': '/name/nm0513165/'},
             {'@type': 'Person',
              'name': 'Art Linson',
              'url': '/name/nm0513165/'},
             {'@type': 'Organization', 'url': '/company/co0005596/'},
             {'@type': 'Organization', 'url': '/company/co0079747/'},
             {'@type': 'Organization', 'url': '/company/co0292355/'},
             {'@type': 'Organization', 'url': '/company/co0063961/'}],
 'datePublished': '2008-10-31',
 'description': 'What Just Happened is a movie starring Robert De Niro, John '
                'Turturro, and Stanley Tucci. Two weeks in the life of a '
                "fading Hollywood producer who's having a rough time trying to "
                'get his new picture made.',
 'director': {'@type': 'Person',
              'name': 'Barry Levinson',
              'url': '/name/nm0001469/'},
 'duration': 'PT1H44M',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTEyMDg3ODAwNl5BMl5BanBnXkFtZTcwMzM3MTc3MQ@@._V1_.jpg',
 'keywords': 'eyepatch,falling downhill,looking at oneself in a mirror,woman '
             "in a men's room,hollywood",
 'name': 'What Just Happened',
 'trailer': {'@type': 'VideoObject',
             'description': 'This is the trailer for What Just Happened?, '
                            'directed by Barry Levinson.',
             'embedUrl': '/video/imdb/vi3015835929',
             'name': 'What Just Happened?: Theatrical Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjc4OTk1MTMyNl5BMl5BanBnXkFtZTgwNjc5MjczMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjc4OTk1MTMyNl5BMl5BanBnXkFtZTgwNjc5MjczMzE@._V1_.jpg',
             'uploadDate': '2008-08-05T17:39:18Z'},
 'url': '/title/tt0486674/'}