{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/How-Beer-Saved-the-World',
 'EntryURL': 'https://www.imdb.com/title/tt1832368',
 'Entry_json': 'Favorites/Movies/snapshot/How-Beer-Saved-the-World/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/How-Beer-Saved-the-World/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/How-Beer-Saved-the-World/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Henry Strozier',
            'url': '/name/nm0835231/'},
           {'@type': 'Person',
            'name': 'George Armelagos',
            'url': '/name/nm4826515/'},
           {'@type': 'Person',
            'name': 'Charlie Bamforth',
            'url': '/name/nm4826517/'},
           {'@type': 'Person',
            'name': 'Kyria Boundy-Mills',
            'url': '/name/nm4826792/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 470,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Martyn Ives',
              'url': '/name/nm1038372/'},
             {'@type': 'Organization', 'url': '/company/co0062109/'}],
 'datePublished': '2011-01-30',
 'description': 'How Beer Saved the World is a TV movie starring Henry '
                'Strozier, George Armelagos, and Charlie Bamforth. This show '
                'traces the important role that beer has played in human '
                'history from the probable origins of the first beer at the...',
 'duration': 'PT1H',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTc1OTkyMDc2NF5BMl5BanBnXkFtZTcwOTg4NzI1Ng@@._V1_.jpg',
 'keywords': 'beer,beer bottle,refrigeration,reference to louis '
             'pasteur,medical history',
 'name': 'How Beer Saved the World',
 'url': '/title/tt1832368/'}