{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battered-Bastards-Of-Baseball',
 'EntryURL': 'https://www.imdb.com/title/tt3445270',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battered-Bastards-Of-Baseball/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battered-Bastards-Of-Baseball/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battered-Bastards-Of-Baseball/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Todd Field', 'url': '/name/nm0276062/'},
           {'@type': 'Person',
            'name': 'Kurt Russell',
            'url': '/name/nm0000621/'},
           {'@type': 'Person', 'name': 'Rob Nelson', 'url': '/name/nm6262809/'},
           {'@type': 'Person',
            'name': 'Jim Swanson',
            'url': '/name/nm6262807/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2957,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'datePublished': '2014-07-11',
 'description': 'The Battered Bastards of Baseball is a movie starring Todd '
                'Field, Kurt Russell, and Rob Nelson. The Battered Bastards of '
                "Baseball is one of baseball's last great, unheralded true "
                'stories. In 1973, Hollywood veteran Bing Russell...',
 'director': [{'@type': 'Person',
               'name': 'Chapman Way',
               'url': '/name/nm1331494/'},
              {'@type': 'Person',
               'name': 'Maclain Way',
               'url': '/name/nm6195256/'}],
 'duration': 'PT1H20M',
 'genre': ['Documentary', 'Sport'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE0NDQwNTU2NF5BMl5BanBnXkFtZTgwNDg1MDUyMjE@._V1_.jpg',
 'name': 'The Battered Bastards of Baseball',
 'url': '/title/tt3445270/'}