{'Actors': ['Alan Arkin',
            'Blair Underwood',
            'Chad Christ',
            'Cynthia Martells',
            'David LeBell',
            'Dean Norris',
            'Elias Koteas',
            'Elizabeth Dennehy',
            'Ernest Borgnine',
            'Ethan Hawke',
            'George Marshall Ruge',
            'Gore Vidal',
            'Jayne Brook',
            'Jude Law',
            'Ken Marino',
            'Lindsey Ginter',
            'Loren Dean',
            'Mason Gamble',
            'Maya Rudolph',
            'Russell Milton',
            'Tony Shalhoub',
            'Uma Thurman',
            'Una Damon',
            'William Lee Scott',
            'Xander Berkeley'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Gattaca: A genetically inferior man assumes the identity of a '
                'superior one in order to pursue his lifelong dream of space '
                'travel. ',
 'Director': ['Andrew Niccol'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Gattaca',
 'EntryURL': 'https://www.imdb.com/title/tt0119177',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Gattaca/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Gattaca/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Gattaca/info.py',
 'Genres': ['Drama', 'Romance', 'Sci-Fi', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt0119177',
 'PrimeWire': 'http://www.primewire.ag/watch-2974-Gattaca',
 'Ratings': {'IMDB': '7.8/10',
             'Metascore': '64%',
             'PrimeWire': '4.30/5',
             'RT': '82%',
             'Votes': '719'},
 'Released': '1997-09-07',
 'Runtime': '106 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2974_Gattaca_1997.jpg',
 'Title': 'Gattaca'}