{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Gattaca',
 'EntryURL': 'https://www.imdb.com/title/tt0119177',
 'Entry_json': 'Favorites/Movies/snapshot/Gattaca/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Gattaca/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Gattaca/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ethan Hawke',
            'url': '/name/nm0000160/'},
           {'@type': 'Person',
            'name': 'Uma Thurman',
            'url': '/name/nm0000235/'},
           {'@type': 'Person', 'name': 'Jude Law', 'url': '/name/nm0000179/'},
           {'@type': 'Person',
            'name': 'Gore Vidal',
            'url': '/name/nm0000683/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 273002,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Niccol',
              'url': '/name/nm0629272/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0010434/'}],
 'datePublished': '1997-10-24',
 'description': 'Gattaca is a movie starring Ethan Hawke, Uma Thurman, and '
                'Jude Law. A genetically inferior man assumes the identity of '
                'a superior one in order to pursue his lifelong dream of space '
                'travel.',
 'director': {'@type': 'Person',
              'name': 'Andrew Niccol',
              'url': '/name/nm0629272/'},
 'duration': 'PT1H46M',
 'genre': ['Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDQxOTc0MzMtZmRlOS00OWQ5LWI2ZDctOTAwNmMwOTYxYzlhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'genetics,future,space travel,urine sample,paraplegic',
 'name': 'Gattaca',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Sony Pictures Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi2611282201',
             'name': 'Gattaca',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDUwOGM2ZjMtMDFlNi00N2M1LWFiZjYtNGRhYzkyNWFlMTI4XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDUwOGM2ZjMtMDFlNi00N2M1LWFiZjYtNGRhYzkyNWFlMTI4XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:01:38Z'},
 'url': '/title/tt0119177/'}