{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-01-29',
 'EntryPath': 'Favorites/Movies/snapshot/Poppy',
 'EntryURL': 'https://www.imdb.com/title/tt1458968',
 'Entry_json': 'Favorites/Movies/snapshot/Poppy/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Poppy/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Poppy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Paul Glover',
            'url': '/name/nm0323163/'},
           {'@type': 'Person',
            'name': 'Camille Keenan',
            'url': '/name/nm2415834/'},
           {'@type': 'Person',
            'name': 'Marek Sumich',
            'url': '/name/nm0838557/'},
           {'@type': 'Person',
            'name': 'Matthew Sunderland',
            'url': '/name/nm0839146/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 55,
                      'ratingValue': '7.9',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'David Coyle',
              'url': '/name/nm3502963/'},
             {'@type': 'Organization', 'url': '/company/co0115563/'}],
 'datePublished': '2009-07-03',
 'description': 'Poppy is a short starring Paul Glover, Camille Keenan, and '
                'Marek Sumich. Poppy is a Performance-Captured CGI drama set '
                "on France's western front in World War One. Two New Zealand "
                'soldiers are trapped behind enemy lines and are...',
 'director': [{'@type': 'Person',
               'name': 'James Cunningham',
               'url': '/name/nm0192333/'}],
 'duration': 'PT10M',
 'genre': ['Animation', 'Short'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODI3OTU0NDA2NV5BMl5BanBnXkFtZTcwMDg1MTIwNA@@._V1_.jpg',
 'name': 'Poppy',
 'url': '/title/tt1458968/'}