<?php
$infoArray = array('Actors' => array('Camille Keenan',
            'Marek Sumich',
            'Matthew Sunderland',
            'Paul Glover'),
 'Added' => '2016-01-29',
 'Countries' => array('New Zealand'),
 'Description' => "\nPoppy: Poppy is a Performance-Captured CGI drama set on France's western front in World War One. Two New Zealand soldiers are trapped behind enemy lines and are trying to find their way to safety.... ",
 'Director' => array('James Cunningham'),
 'Genres' => array('Animation', 'Short'),
 'IMDB' => 'http://www.imdb.com/title/tt1458968',
 'PrimeWire' => 'http://www.primewire.ag/watch-2371979-Poppy',
 'Ratings' => array('IMDB' => '7.8/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.81/5',
             'RT' => 'N/A',
             'Votes' => '54'),
 'Released' => '2009-07-03',
 'Runtime' => '10 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2371979_Poppy_2010.jpg',
 'Title' => 'Poppy');
?>