<?php
$infoArray = array('Actors' => array('Abi McKenzie',
            'Adam Clark',
            'Adam Mucci',
            'Alan Wilder',
            'Andre Sogliuzzo',
            'Andrzej Krukowski',
            'Bill Camp',
            'Bill Ibrahim',
            'Billy Crudup',
            'Branka Katic',
            'Carey Mulligan',
            'Casey Siemaszko',
            'Channing Tatum',
            'Christian Bale',
            'Christian Stolte',
            'Dan Latham',
            'David Warshofsky',
            'David Wenham',
            'Diana Krall',
            'Domenick Lombardozzi',
            'Don Frye',
            'Don Harvey',
            'Don Kress',
            'Duane Sharp',
            'Ed Bruce',
            'Emilie de Ravin',
            'Gary Sedlock',
            'Geoffrey Cantor',
            'Giovanni Ribisi',
            'Guy Van Swearingen',
            'J Alec Holmes',
            'James Currie',
            'James Russo',
            'Jason Clarke',
            'Jennifer Badger',
            'Joe DeVito',
            'John Judd',
            'John Michael Bolger',
            'John Ortiz',
            'John Thurner',
            'Johnny Depp',
            'Joseph Mazurk',
            'Keith Kupferer',
            'Kelli Clevenger',
            'Kurt Naebig',
            'Lance Baker',
            'Laurence Mason',
            'Leelee Sobieski',
            'Libby Regnier',
            'Lili Taylor',
            'Lisa Wolf',
            'Marion Cotillard',
            'Matt Craven',
            'Michael Bentt',
            'Michael Sassone',
            'Michael Vieau',
            'Nick Ferrin',
            'Peter Gerety',
            'Rory Cochrane',
            'Shawn Hatosy'),
 'Added' => '2014-09-10',
 'Countries' => array('USA'),
 'Description' => '\nPublic Enemies: The Feds try to take down notorious American gangsters John Dillinger, Baby Face Nelson and Pretty Boy Floyd during a booming crime wave in the 1930s. ',
 'Director' => array('Michael Mann'),
 'Genres' => array('Drama', 'Thriller', 'Crime'),
 'IMDB' => 'http://www.imdb.com/title/tt1152836',
 'PrimeWire' => 'http://www.primewire.ag/watch-6136-Public-Enemies',
 'Ratings' => array('IMDB' => '7.0/10',
             'Metascore' => '70%',
             'PrimeWire' => '3.79/5',
             'RT' => '68%',
             'Votes' => '1314'),
 'Released' => '2009-06-18',
 'Runtime' => '140 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/6136_Public_Enemies_2009.jpg',
 'Title' => 'Public-Enemies');
?>