{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Papers-Please',
 'EntryURL': 'https://rawg.io/games/papers-please',
 'Entry_json': 'Favorites/Games/snapshot/Papers-Please/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Papers-Please/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Papers-Please/thumb.jpg',
 'added': 3666,
 'background_image': 'https://media.rawg.io/media/games/6d3/6d33014a4ed48a19c30a77ead5a0f62e.jpg',
 'developers': ['3909', 'Lucas Pope', '3909 LLC'],
 'genres': ['Simulation', 'Indie', 'Puzzle'],
 'name': 'Papers, Please',
 'platforms': ['macOS', 'Linux', 'PC', 'iOS', 'PS Vita'],
 'publishers': ['3909', '3909 LLC'],
 'released': '2013-08-08',
 'slug': 'papers-please'}