{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Devils-Rejects',
 'EntryURL': 'https://www.imdb.com/title/tt0395584',
 'Entry_json': 'Favorites/Movies/snapshot/The-Devils-Rejects/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Devils-Rejects/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Devils-Rejects/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Sid Haig', 'url': '/name/nm0354085/'},
           {'@type': 'Person',
            'name': 'Sheri Moon Zombie',
            'url': '/name/nm0600667/'},
           {'@type': 'Person',
            'name': 'Bill Moseley',
            'url': '/name/nm0608405/'},
           {'@type': 'Person',
            'name': 'William Forsythe',
            'url': '/name/nm0001235/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 91214,
                      'ratingValue': '6.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Rob Zombie',
              'url': '/name/nm0957772/'},
             {'@type': 'Person',
              'name': 'Rob Zombie',
              'url': '/name/nm0957772/'},
             {'@type': 'Organization', 'url': '/company/co0060306/'},
             {'@type': 'Organization', 'url': '/company/co0018947/'},
             {'@type': 'Organization', 'url': '/company/co0281014/'},
             {'@type': 'Organization', 'url': '/company/co0156988/'},
             {'@type': 'Organization', 'url': '/company/co0156976/'},
             {'@type': 'Organization', 'url': '/company/co0081526/'},
             {'@type': 'Organization', 'url': '/company/co0118138/'},
             {'@type': 'Organization', 'url': '/company/co0215893/'}],
 'datePublished': '2005-07-22',
 'description': "The Devil's Rejects is a movie starring Sid Haig, Sheri Moon "
                'Zombie, and Bill Moseley. The murderous, backwoods Firefly '
                'family take to the road to escape a vengeful police force '
                'which is not afraid of being as ruthless as their...',
 'director': [{'@type': 'Person',
               'name': 'Rob Zombie',
               'url': '/name/nm0957772/'}],
 'duration': 'PT1H47M',
 'genre': 'Horror',
 'image': 'https://m.media-amazon.com/images/M/MV5BZGU4NWMxZTQtNjYwYy00Mjg1LTg4YjQtYTk5M2ZhNTFiMzAxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'motel,revenge,carjacking,brothel,police brutality',
 'name': "The Devil's Rejects",
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer',
              'embedUrl': '/video/imdb/vi2079392025',
              'name': "The Devil's Rejects",
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZWFlMjgxNWYtMGJlZC00MzQ3LTg0NzMtMjJkOGZhMGE2ODI3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZWFlMjgxNWYtMGJlZC00MzQ3LTg0NzMtMjJkOGZhMGE2ODI3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T16:39:13Z'}],
 'url': '/title/tt0395584/'}