{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Super-Mario-Sunshine',
 'EntryURL': 'https://rawg.io/games/super-mario-sunshine',
 'Entry_json': 'Favorites/Games/snapshot/Super-Mario-Sunshine/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Super-Mario-Sunshine/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Super-Mario-Sunshine/thumb.jpg',
 'added': 320,
 'background_image': 'https://media.rawg.io/media/screenshots/04b/04b7fd791867fa25858f6dc7a2cccb9a.jpg',
 'developers': ['Nintendo'],
 'genres': ['Action'],
 'name': 'Super Mario Sunshine',
 'platforms': ['GameCube'],
 'publishers': ['Nintendo'],
 'released': '2002-08-25',
 'slug': 'super-mario-sunshine'}