{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-08',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Flying-Man',
 'EntryURL': 'https://www.imdb.com/title/tt3018700',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Flying-Man/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Flying-Man/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Flying-Man/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Nick Smyth', 'url': '/name/nm1999952/'},
           {'@type': 'Person',
            'name': 'Rick Cordeiro',
            'url': '/name/nm3487588/'},
           {'@type': 'Person',
            'name': 'Justin T. Lee',
            'url': '/name/nm3557211/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 906,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Marcus Alqueres',
              'url': '/name/nm2748516/'},
             {'@type': 'Person',
              'name': 'Henry Grazinoli',
              'url': '/name/nm5768925/'},
             {'@type': 'Person',
              'name': 'Marcus Alqueres',
              'url': '/name/nm2748516/'},
             {'@type': 'Organization', 'url': '/company/co0643018/'}],
 'datePublished': '2013-07-12',
 'description': 'The Flying Man is a short starring Nick Smyth, Rick Cordeiro, '
                'and Justin T. Lee. A super powered vigilante defies the law '
                'using extreme violence to fight crime.',
 'director': {'@type': 'Person',
              'name': 'Marcus Alqueres',
              'url': '/name/nm2748516/'},
 'duration': 'PT10M',
 'genre': ['Short', 'Action', 'Fantasy', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZTdhZTJmYjktY2EzNS00YmU0LThkODMtM2VmOGY0MTg3NmUxXkEyXkFqcGdeQXVyMTY0MDY0NjA@._V1_.jpg',
 'keywords': 'vigilante,night,police helicopter,news report,handgun',
 'name': 'The Flying Man',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'Kirpianuscus'},
            'dateCreated': '2019-06-25',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt3018700/'},
            'name': 'good job',
            'reviewBody': 'A simple story, good special effects, the idea of '
                          'justice and, after Marvel universe, a not so '
                          'strange character looking for do what it must be '
                          'done. A good short film, with a powerfull end, with '
                          'nice science to build the tension and dialogue. '
                          'Short, good start for a new serie.'},
 'url': '/title/tt3018700/'}