{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-18-2020',
 'EntryPath': 'Favorites/TV/snapshot/Goosebumps',
 'EntryURL': 'https://www.imdb.com/title/tt0111987',
 'Entry_json': 'Favorites/TV/snapshot/Goosebumps/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Goosebumps/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Goosebumps/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'R.L. Stine', 'url': '/name/nm0830419/'},
           {'@type': 'Person',
            'name': 'Kathryn Short',
            'url': '/name/nm1368929/'},
           {'@type': 'Person', 'name': 'Cody Jones', 'url': '/name/nm0427796/'},
           {'@type': 'Person',
            'name': 'Scott Wickware',
            'url': '/name/nm0927015/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 11517,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-Y7',
 'creator': [{'@type': 'Person',
              'name': 'R.L. Stine',
              'url': '/name/nm0830419/'},
             {'@type': 'Organization', 'url': '/company/co0005875/'},
             {'@type': 'Organization', 'url': '/company/co0034220/'},
             {'@type': 'Organization', 'url': '/company/co0007719/'},
             {'@type': 'Organization', 'url': '/company/co0012870/'}],
 'datePublished': '1995-10-27',
 'description': 'Goosebumps is a TV series starring R.L. Stine, Kathryn Short, '
                'and Cody Jones. A series of scary anthology stories based on '
                "the children's books by R.L. Stine. Series one was hosted by "
                'R.L. Stine.',
 'genre': ['Family', 'Fantasy', 'Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMmViMGI3NDYtYzIzNi00OTVlLWI1YjMtNDJiNmVmMzE3NjUxXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_.jpg',
 'keywords': 'based on book series,surrealism,based on book,cult '
             'favorite,child in danger',
 'name': 'Goosebumps',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Shared trailer for these two spooky DVDs',
              'embedUrl': '/video/imdb/vi1801323033',
              'name': 'Goosebumps: Attack of the Jack-O-Lanterns/The Headless '
                      'Ghost',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmU3ZjBiZDMtYzI3YS00ZWZjLWJlMGUtMmIzNzEzYTM0ODg5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmU3ZjBiZDMtYzI3YS00ZWZjLWJlMGUtMmIzNzEzYTM0ODg5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2009-10-09T12:25:25Z'}],
 'url': '/title/tt0111987/'}