{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Witcher-2-Assassins-Of-Kings',
 'EntryURL': 'https://rawg.io/games/the-witcher-2-assassins-of-kings',
 'Entry_json': 'Favorites/Games/snapshot/The-Witcher-2-Assassins-Of-Kings/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Witcher-2-Assassins-Of-Kings/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Witcher-2-Assassins-Of-Kings/thumb.jpg',
 'added': 392,
 'background_image': 'https://media.rawg.io/media/screenshots/b22/b22469fa65b3f13df64954b5ea8d6d5c.jpg',
 'developers': ['CD PROJEKT RED'],
 'genres': ['RPG'],
 'name': 'The Witcher 2: Assassins of Kings',
 'platforms': ['PC', 'Xbox 360'],
 'publishers': ['Atari', 'CD PROJEKT RED'],
 'released': '2011-05-17',
 'slug': 'the-witcher-2-assassins-of-kings'}