{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-03-31',
 'EntryPath': 'Favorites/Movies/snapshot/Going-Clear-Scientology-and-the-Prison-of-Belief',
 'EntryURL': 'https://www.imdb.com/title/tt4257858',
 'Entry_json': 'Favorites/Movies/snapshot/Going-Clear-Scientology-and-the-Prison-of-Belief/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Going-Clear-Scientology-and-the-Prison-of-Belief/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Going-Clear-Scientology-and-the-Prison-of-Belief/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Paul Haggis',
            'url': '/name/nm0353673/'},
           {'@type': 'Person',
            'name': 'Jason Beghe',
            'url': '/name/nm0000892/'},
           {'@type': 'Person',
            'name': 'Spanky Taylor',
            'url': '/name/nm7083264/'},
           {'@type': 'Person',
            'name': 'David Miscavige',
            'url': '/name/nm1719336/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 35934,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Alex Gibney',
              'url': '/name/nm0316795/'},
             {'@type': 'Person',
              'name': 'Lawrence Wright',
              'url': '/name/nm0942590/'},
             {'@type': 'Organization', 'url': '/company/co0139821/'},
             {'@type': 'Organization', 'url': '/company/co0133364/'},
             {'@type': 'Organization', 'url': '/company/co0329071/'}],
 'datePublished': '2015-06-25',
 'description': 'Going Clear: Scientology & the Prison of Belief is a movie '
                'starring Paul Haggis, Jason Beghe, and Spanky Taylor. A '
                'documentary looking at the inner-workings of the Church of '
                'Scientology.',
 'director': {'@type': 'Person',
              'name': 'Alex Gibney',
              'url': '/name/nm0316795/'},
 'duration': 'PT1H59M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BZjYxYTA0MWQtYWViYi00YmRhLWEzNzctMDkwMGQ5ODFmM2FjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'dianetics,scientology,based on book,year 2013,e meter',
 'name': 'Going Clear: Scientology & the Prison of Belief',
 'trailer': {'@type': 'VideoObject',
             'description': "A documentary based on Lawrence Wright's book of "
                            'the same name. Scientology is laid bare by a film '
                            'that brings together archive footage, '
                            'testimonials from former high ranking officials '
                            'and public, and dramatic reconstructions.',
             'embedUrl': '/video/imdb/vi1277800729',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjI4MTg1OTk1NV5BMl5BanBnXkFtZTgwMzU5NTAxNTE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjI4MTg1OTk1NV5BMl5BanBnXkFtZTgwMzU5NTAxNTE@._V1_.jpg',
             'uploadDate': '2015-03-31T18:57:28Z'},
 'url': '/title/tt4257858/'}