{'Actors': [],
 'Added': '2015-03-31',
 'Countries': ['USA'],
 'Description': '\n'
                'Going Clear: Scientology and the Prison of Belief: An '
                'in-depth look at the inner-workings of the Church of '
                'Scientology. ',
 'Director': ['Alex Gibney'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Going-Clear-Scientology-and-the-Prison-of-Belief',
 'EntryURL': 'https://www.imdb.com/title/tt4257858',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Going-Clear-Scientology-and-the-Prison-of-Belief/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Going-Clear-Scientology-and-the-Prison-of-Belief/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Going-Clear-Scientology-and-the-Prison-of-Belief/info.py',
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt4257858',
 'PrimeWire': 'http://www.primewire.ag/watch-2760343-Going-Clear-Scientology-and-the-Prison-of-Belief',
 'Ratings': {'IMDB': '9.0/10',
             'Metascore': '81%',
             'PrimeWire': '4.50/5',
             'RT': '91%',
             'Votes': '282'},
 'Released': '2015-01-25',
 'Runtime': '119 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2760343_Going_Clear_Scientology_and_the_Prison_of_Belief_2015_45.jpg',
 'Title': 'Going-Clear-Scientology-and-the-Prison-of-Belief'}