{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death',
 'EntryURL': 'https://www.imdb.com/title/tt1124052',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Ye Liu', 'url': '/name/nm1091782/'},
           {'@type': 'Person', 'name': 'Wei Fan', 'url': '/name/nm1981215/'},
           {'@type': 'Person',
            'name': 'Hideo Nakaizumi',
            'url': '/name/nm0620024/'},
           {'@type': 'Person',
            'name': 'Yuanyuan Gao',
            'url': '/name/nm0304729/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 10082,
                     'ratingValue': '7.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person', 'name': 'Chuan Lu', 'url': '/name/nm1283651/'},
             {'@type': 'Organization', 'url': '/company/co0049799/'},
             {'@type': 'Organization', 'url': '/company/co0491641/'},
             {'@type': 'Organization', 'url': '/company/co0165588/'},
             {'@type': 'Organization', 'url': '/company/co0093755/'},
             {'@type': 'Organization', 'url': '/company/co0163928/'}],
 'datePublished': '2009-04-22',
 'description': 'Nanjing! Nanjing! is a movie starring Ye Liu, Wei Fan, and '
                'Hideo Nakaizumi. In 1937, Japan occupied Nanjing, the Chinese '
                'capital. There was a battle and subsequent atrocities against '
                'the inhabitants, especially those who took refuge...',
 'director': {'@type': 'Person', 'name': 'Chuan Lu', 'url': '/name/nm1283651/'},
 'duration': 'PT2H13M',
 'genre': ['Drama', 'History', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BY2U3YTAwMjQtMmIzNC00MmI0LTliOWEtYTYwMDc1NmU1Mzc3XkEyXkFqcGdeQXVyNzI1NzMxNzM@._V1_.jpg',
 'keywords': 'chinese history,japanese occupation of '
             'china,atrocity,battle,chinese',
 'name': 'Nanjing! Nanjing!',
 'trailer': {'@type': 'VideoObject',
             'description': 'A dramatization of the rape of Nanking in 1937.',
             'embedUrl': '/video/imdb/vi3417376537',
             'name': 'City of Life and Death',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDA4MzcxNTk2OF5BMl5BanBnXkFtZTgwMTcyOTYzMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDA4MzcxNTk2OF5BMl5BanBnXkFtZTgwMTcyOTYzMzE@._V1_.jpg',
             'uploadDate': '2010-04-07T06:45:18Z'},
 'url': '/title/tt1124052/'}