{'Actors': ['Ye Liu'],
 'Added': '2015-08-24',
 'Countries': ['China', 'Hong Kong'],
 'Description': '\n'
                'City of Life and Death: A dramatization of the rape of '
                'Nanking in 1937. ',
 'Director': ['Chuan Lu'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death',
 'EntryURL': 'https://www.imdb.com/title/tt1124052',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/City-of-Life-and-Death/info.py',
 'Genres': ['Drama', 'War', 'History'],
 'Ratings': {'IMDB': '7.7/10',
             'Metascore': '85%',
             'PrimeWire': '3.27/5',
             'RT': '91%',
             'Votes': '88'},
 'Released': '2009-04-22',
 'Runtime': '132 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/11536_City_of_Life_and_Death_2009.jpg',
 'Title': 'City-of-Life-and-Death'}