{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Camino-A-Breaking-Bad-Movie',
 'EntryURL': 'https://www.imdb.com/title/tt9243946',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Camino-A-Breaking-Bad-Movie/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Camino-A-Breaking-Bad-Movie/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Camino-A-Breaking-Bad-Movie/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Aaron Paul', 'url': '/name/nm0666739/'},
           {'@type': 'Person',
            'name': 'Jonathan Banks',
            'url': '/name/nm0052186/'},
           {'@type': 'Person', 'name': 'Matt Jones', 'url': '/name/nm2804503/'},
           {'@type': 'Person',
            'name': 'Charles Baker',
            'url': '/name/nm1889973/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 165001,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Vince Gilligan',
              'url': '/name/nm0319213/'},
             {'@type': 'Person',
              'name': 'Vince Gilligan',
              'url': '/name/nm0319213/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0086397/'},
             {'@type': 'Organization', 'url': '/company/co0212797/'},
             {'@type': 'Organization', 'url': '/company/co0071947/'}],
 'datePublished': '2019-10-11',
 'description': 'El Camino: A Breaking Bad Movie is a movie starring Aaron '
                'Paul, Jonathan Banks, and Matt Jones. El Camino: A Breaking '
                'Bad Movie follows fugitive Jesse Pinkman as he runs from his '
                'captors, the law and his past.',
 'director': {'@type': 'Person',
              'name': 'Vince Gilligan',
              'url': '/name/nm0319213/'},
 'duration': 'PT2H2M',
 'genre': ['Action', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_.jpg',
 'keywords': 'neo noir,happy ending,crystal meth,anti hero,violence',
 'name': 'El Camino: A Breaking Bad Movie',
 'trailer': {'@type': 'VideoObject',
             'description': 'After escaping Jack and his gang, Jesse Pinkman '
                            'goes on the run from the police and tries to '
                            'escape his own inner turmoil.',
             'embedUrl': '/video/imdb/vi2308751129',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjFjOGEwYjAtNDQxYy00OThhLWI3NDYtYTEyOGRlZDRhN2ViXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjFjOGEwYjAtNDQxYy00OThhLWI3NDYtYTEyOGRlZDRhN2ViXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-09-24T16:58:01Z'},
 'url': '/title/tt9243946/'}