{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-01-30',
 'EntryPath': 'Favorites/TV/snapshot/American-Dad',
 'EntryURL': 'https://www.imdb.com/title/tt0397306',
 'Entry_json': 'Favorites/TV/snapshot/American-Dad/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/American-Dad/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/American-Dad/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Seth MacFarlane',
            'url': '/name/nm0532235/'},
           {'@type': 'Person',
            'name': 'Wendy Schaal',
            'url': '/name/nm0769446/'},
           {'@type': 'Person',
            'name': 'Scott Grimes',
            'url': '/name/nm0342241/'},
           {'@type': 'Person',
            'name': 'Rachael MacFarlane',
            'url': '/name/nm1484134/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 113786,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Mike Barker',
              'url': '/name/nm0963341/'},
             {'@type': 'Person',
              'name': 'Seth MacFarlane',
              'url': '/name/nm0532235/'},
             {'@type': 'Person',
              'name': 'Matt Weitzman',
              'url': '/name/nm0963392/'},
             {'@type': 'Organization', 'url': '/company/co0056447/'},
             {'@type': 'Organization', 'url': '/company/co0117746/'},
             {'@type': 'Organization', 'url': '/company/co0221951/'},
             {'@type': 'Organization', 'url': '/company/co0159275/'},
             {'@type': 'Organization', 'url': '/company/co0065872/'},
             {'@type': 'Organization', 'url': '/company/co0047155/'}],
 'datePublished': '2005-02-06',
 'description': 'American Dad! is a TV series starring Seth MacFarlane, Wendy '
                'Schaal, and Scott Grimes. The random escapades of Stan Smith, '
                'a conservative C.I.A. Agent dealing with family life, and '
                'keeping America safe, all in the most absurd way...',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDRkOWIyOTUtMjg5YS00OTJjLTgwNGYtMjgxMTA0NWQ2NGI3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'husband wife relationship,crude humor,family '
             'relationships,violence,cult tv',
 'name': 'American Dad!',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for American Dad!: Volume Five',
              'embedUrl': '/video/imdb/vi2612763417',
              'name': 'American Dad!: Volume Five',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMzAzYmQzOTAtNzI2Zi00NjBlLTk5ZDgtYzdiMTU3ZjQ5NGUzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMzAzYmQzOTAtNzI2Zi00NjBlLTk5ZDgtYzdiMTU3ZjQ5NGUzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2010-12-21T06:05:39Z'}],
 'url': '/title/tt0397306/'}