{'Actors': ['Alan Gifford',
            'Ann Gillis',
            'Bill Weston',
            'Burnell Tucker',
            'Douglas Rain',
            'Ed Bishop',
            'Edwina Carroll',
            'Frank Miller',
            'Gary Lockwood',
            'Glenn Beck',
            'John Ashley',
            'John Clifford',
            'John Jordan',
            'John Swindells',
            'Keir Dullea',
            'Kenneth Kendall',
            'Kevin Scott',
            'Leonard Rossiter',
            'Marcella Markham',
            'Margaret Tyzack',
            'Penny Brahms',
            'Richard Woods',
            'Robert Beatty',
            'Sean Sullivan',
            'Terry Duggan',
            'Tony Jackson',
            'William Sylvester'],
 'Added': '2013-02-24',
 'Countries': ['UK', 'USA'],
 'Description': '\n'
                '2001: A Space Odyssey: Mankind finds a mysterious, obviously '
                'artificial, artifact buried on the moon and, with the '
                'intelligent computer HAL, sets off on a quest. ',
 'Director': ['Stanley Kubrick'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//2001-A-Space-Odyssey',
 'EntryURL': 'http://www.imdb.com/title/tt0062622',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//2001-A-Space-Odyssey/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//2001-A-Space-Odyssey/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//2001-A-Space-Odyssey/info.py',
 'Genres': ['Sci-Fi', 'Adventure', 'Mystery'],
 'IMDB': 'http://www.imdb.com/title/tt0062622',
 'PrimeWire': 'http://www.primewire.ag/watch-902-2001-A-Space-Odyssey',
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': '86%',
             'PrimeWire': '3.83/5',
             'RT': '96%',
             'Votes': '443'},
 'Released': '1968-04-02',
 'Runtime': '141 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/902_2001_A_Space_Odyssey_1968.jpg',
 'Title': '2001-A-Space-Odyssey'}