{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Conkers-Bad-Fur-Day',
 'EntryURL': 'https://rawg.io/games/conkers-bad-fur-day',
 'Entry_json': 'Favorites/Games/snapshot/Conkers-Bad-Fur-Day/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Conkers-Bad-Fur-Day/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Conkers-Bad-Fur-Day/thumb.jpg',
 'added': 87,
 'background_image': 'https://media.rawg.io/media/screenshots/621/62111bd8918fb3f55898954171432dc7.jpg',
 'developers': ['Rare'],
 'genres': ['Action', 'Platformer'],
 'name': "Conker's Bad Fur Day",
 'platforms': ['Nintendo 64'],
 'publishers': ['THQ', 'Rare', 'North America'],
 'released': '2001-03-05',
 'slug': 'conkers-bad-fur-day'}