{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-11-24',
 'EntryPath': 'Favorites/TV/snapshot/Adam-Ruins-Everything',
 'EntryURL': 'https://www.imdb.com/title/tt5034326',
 'Entry_json': 'Favorites/TV/snapshot/Adam-Ruins-Everything/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Adam-Ruins-Everything/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Adam-Ruins-Everything/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Adam Conover',
            'url': '/name/nm4033885/'},
           {'@type': 'Person',
            'name': 'Adam Lustick',
            'url': '/name/nm3713920/'},
           {'@type': 'Person',
            'name': 'Emily Axford',
            'url': '/name/nm3269739/'},
           {'@type': 'Person',
            'name': 'Amos Vernon',
            'url': '/name/nm4447413/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 5930,
                      'ratingValue': '8.0',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Organization', 'url': '/company/co0554645/'}],
 'datePublished': '2015-09-29',
 'description': 'Adam Ruins Everything is a TV series starring Adam Conover, '
                'Adam Lustick, and Emily Axford. Iconoclastic Adam Conover '
                'from CollegeHumor turns life as we know it on its ear by '
                'showing us how unnecessary, and sometimes horrible,...',
 'genre': ['Animation', 'Comedy', 'History', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTEyNzQyNzQyNjJeQTJeQWpwZ15BbWU4MDEwMjIyOTYx._V1_.jpg',
 'keywords': 'debunking a myth,comedy host,spoof,edutainment,educational',
 'name': 'Adam Ruins Everything',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Official series trailer for Adam Ruins '
                             'Everything on truTV.',
              'embedUrl': '/video/imdb/vi1266397977',
              'name': 'Series Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTU3NjEzNjY3MF5BMl5BanBnXkFtZTgwNjEyMjI5NjE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTU3NjEzNjY3MF5BMl5BanBnXkFtZTgwNjEyMjI5NjE@._V1_.jpg',
              'uploadDate': '2015-09-30T06:52:05Z'}],
 'url': '/title/tt5034326/'}