{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-08-08',
 'EntryPath': 'Favorites/TV/snapshot/Black-Jesus',
 'EntryURL': 'https://www.imdb.com/title/tt3589872',
 'Entry_json': 'Favorites/TV/snapshot/Black-Jesus/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Black-Jesus/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Black-Jesus/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': "Gerald 'Slink' Johnson",
            'url': '/name/nm3834526/'},
           {'@type': 'Person',
            'name': 'John Witherspoon',
            'url': '/name/nm0936762/'},
           {'@type': 'Person',
            'name': 'Corey Holcomb',
            'url': '/name/nm1189640/'},
           {'@type': 'Person',
            'name': 'Angela Elayne Gibbs',
            'url': '/name/nm0589900/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3082,
                      'ratingValue': '6.9',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Mike Clattenburg',
              'url': '/name/nm0154104/'},
             {'@type': 'Person',
              'name': 'Aaron McGruder',
              'url': '/name/nm1412298/'},
             {'@type': 'Organization', 'url': '/company/co0473613/'},
             {'@type': 'Organization', 'url': '/company/co0185632/'},
             {'@type': 'Organization', 'url': '/company/co0021520/'},
             {'@type': 'Organization', 'url': '/company/co0008281/'}],
 'datePublished': '2014-08-07',
 'description': "Black Jesus is a TV series starring Gerald 'Slink' Johnson, "
                'John Witherspoon, and Corey Holcomb. The hi-jinks of a '
                'street-smart savior living in modern-day Compton, on a '
                'mission to spread love and kindness throughout the...',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BYjdlNjdjZmUtODJmOC00NWMxLWEwNTQtNjY4MTg3ZmQ5ZDI1XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
 'keywords': 'satire,religion,jesus in title,color in title,two word title',
 'name': 'Black Jesus',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A TV series finds Jesus living in present day '
                             'Compton, CA on a daily mission to spread love '
                             'and kindness throughout the neighborhood with '
                             'the help of his small but loyal group of '
                             'downtrodden followers.',
              'embedUrl': '/video/imdb/vi2295180313',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMzM4Njg2MzU0NV5BMl5BanBnXkFtZTgwMDUzNDgyMjE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMzM4Njg2MzU0NV5BMl5BanBnXkFtZTgwMDUzNDgyMjE@._V1_.jpg',
              'uploadDate': '2014-07-25T08:48:39Z'}],
 'url': '/title/tt3589872/'}