{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/The-Daily-Show',
 'EntryURL': 'https://www.imdb.com/title/tt0115147',
 'Entry_json': 'Favorites/TV/snapshot/The-Daily-Show/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Daily-Show/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Daily-Show/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jon Stewart',
            'url': '/name/nm0829537/'},
           {'@type': 'Person',
            'name': 'Stephen Colbert',
            'url': '/name/nm0170306/'},
           {'@type': 'Person',
            'name': 'Trevor Noah',
            'url': '/name/nm3696388/'},
           {'@type': 'Person',
            'name': 'John Oliver',
            'url': '/name/nm1056659/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 43938,
                      'ratingValue': '8.4',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Madeleine Smithberg',
              'url': '/name/nm0810431/'},
             {'@type': 'Person',
              'name': 'Lizz Winstead',
              'url': '/name/nm0935540/'},
             {'@type': 'Organization', 'url': '/company/co0573674/'},
             {'@type': 'Organization', 'url': '/company/co0093766/'},
             {'@type': 'Organization', 'url': '/company/co0029768/'},
             {'@type': 'Organization', 'url': '/company/co0074014/'},
             {'@type': 'Organization', 'url': '/company/co0171943/'}],
 'datePublished': '1996-07-22',
 'description': 'The Daily Show is a TV series starring Jon Stewart, Stephen '
                'Colbert, and Trevor Noah. Providing comedy/news in the '
                "tradition of TV Nation and SNL's Weekend Update, Comedy "
                "Central's Daily Show reports on the foibles and of the "
                'real...',
 'genre': ['Comedy', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODM0ZjA5ZGItMTJhZC00N2VjLWFjYTQtZjU4YmNkMWU5ZTcyXkEyXkFqcGdeQXVyODg3NDc1OTE@._V1_.jpg',
 'keywords': 'interview,1990s,2000s,2010s,2020s',
 'name': 'The Daily Show',
 'trailer': [{'@type': 'VideoObject',
              'description': 'The Daily Show',
              'embedUrl': '/video/imdb/vi2072165401',
              'name': 'The Daily Show',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOWUwNTU1MTYtYzY4Mi00OGEzLWEzMTYtZjhhNzM2Mzk2YzQ3XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOWUwNTU1MTYtYzY4Mi00OGEzLWEzMTYtZjhhNzM2Mzk2YzQ3XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-04-22T21:39:19Z'}],
 'url': '/title/tt0115147/'}