{'Actors': ['Jon Stewart&tv', 'Stephen Colbert&tv'],
 'Added': '2011-08-19',
 'Countries': ['USA'],
 'Description': "\nThe Daily Show: America's top fake news show. ",
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Daily-Show',
 'EntryURL': 'http://www.imdb.com/title/tt0115147',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Daily-Show/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Daily-Show/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Daily-Show/info.py',
 'Genres': ['Comedy&tv', 'Talk-Show&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0115147',
 'PrimeWire': 'http://www.primewire.ag/tv-13062-The-Daily-Show',
 'Ratings': {'IMDB': '8.9/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.93/5',
             'RT': 'N/A',
             'Votes': '2320'},
 'Released': '1996-07-22',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/13062_The_Daily_Show_1996_63.jpg',
 'Title': 'The-Daily-Show'}