<?php
$infoArray = array('Actors' => array(' Adrian Schiller ',
            ' Celia Imrie ',
            ' Harry Groener ',
            ' Magnus Krepper ',
            ' Peter Benedict ',
            'Dane DeHaan',
            'Ivo Nandi',
            'Jason Isaacs',
            'Mia Goth'),
 'Added' => '2017-05-27',
 'Countries' => array('Germany', 'USA'),
 'Description' => '\r\n              A Cure for Wellness: An ambitious young executive is sent to retrieve his company\'s CEO from an idyllic but mysterious "wellness center" at a remote location in the Swiss Alps, but soon suspects that the spa\'s treatments are not what they seem.            ',
 'Director' => array('Gore Verbinski'),
 'Genres' => array('Drama', 'Fantasy', 'Horror'),
 'IMDB' => 'http://www.imdb.com/title/tt4731136',
 'PrimeWire' => 'http://www.primewire.ag/watch-2791971-A-Cure-for-Wellness',
 'Ratings' => array('IMDB' => '6.6/10',
             'Metascore' => '47%',
             'PrimeWire' => '3.51/5',
             'RT' => 'N/A',
             'Votes' => '323'),
 'Released' => '2016-12-10',
 'Runtime' => '146 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2791971_A_Cure_for_Wellness_2017.jpg',
 'Title' => 'A-Cure-for-Wellness');
?>