{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Dark-Souls',
 'EntryURL': 'https://rawg.io/games/dark-souls',
 'Entry_json': 'Favorites/Games/snapshot/Dark-Souls/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Dark-Souls/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Dark-Souls/thumb.jpg',
 'added': 2072,
 'background_image': 'https://media.rawg.io/media/games/582/582b5518a52f5086d15dde128264b94d.jpg',
 'developers': ['BANDAI NAMCO Entertainment America Inc.', 'FromSoftware'],
 'genres': ['Action', 'RPG'],
 'name': 'Dark Souls',
 'platforms': ['PC', 'PlayStation 3', 'Xbox 360'],
 'publishers': ['BANDAI NAMCO Entertainment America',
                'Bandai Namco Entertainment'],
 'released': '2011-09-22',
 'slug': 'dark-souls'}