{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-08-17',
 'EntryPath': 'Favorites/TV/snapshot/Moonlight-Mile',
 'EntryURL': 'https://www.imdb.com/title/tt1485405',
 'Entry_json': 'Favorites/TV/snapshot/Moonlight-Mile/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Moonlight-Mile/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Moonlight-Mile/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Beth Burns',
            'url': '/name/nm11460599/'},
           {'@type': 'Person',
            'name': 'Charles C. Campbell',
            'url': '/name/nm0132285/'},
           {'@type': 'Person',
            'name': 'Brandon Hearnsberger',
            'url': '/name/nm3033069/'},
           {'@type': 'Person',
            'name': 'Andrew Love',
            'url': '/name/nm0522275/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 22,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'datePublished': '2007-02-04',
 'genre': ['Animation', 'Adventure', 'Drama', 'Sci-Fi'],
 'name': 'Moonlight Mile 2nd shîzun: Touch down',
 'url': '/title/tt1485405/'}