<?php
$infoArray = array('Actors' => array('Hiroaki Hirata&tv', 'Kazuhiko Inoue&tv', 'Rie Tanaka&tv'),
 'Added' => '2015-08-17',
 'Countries' => array(),
 'Description' => '\r\n              Moonlight Mile: After scaling Mt. Everest, mountain climbing partners Saruwatari Gorou and "Lostman" Jack F. Woodbridge see the ISA Space Station, and each vows to make the trek into outerspace.             ',
 'Director' => array(),
 'Genres' => array('Adventure&tv',
            'Animation&tv',
            'Japanese&tv',
            'Sci-Fi&tv',
            'War&tv'),
 'IMDB' => 'NA',
 'PrimeWire' => 'http://www.primewire.ag/tv-2766940-Moonlight-Mile',
 'Ratings' => array('IMDB' => 'N/A',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.56/5',
             'RT' => 'N/A',
             'Votes' => '16'),
 'Released' => '2007-02-04',
 'Runtime' => '25 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2766940_Moonlight_Mile_2007_41.jpg',
 'Title' => 'Moonlight-Mile');
?>