{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Sin-City',
 'EntryURL': 'https://www.imdb.com/title/tt0401792',
 'Entry_json': 'Favorites/Movies/snapshot/Sin-City/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Sin-City/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Sin-City/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Mickey Rourke',
            'url': '/name/nm0000620/'},
           {'@type': 'Person', 'name': 'Clive Owen', 'url': '/name/nm0654110/'},
           {'@type': 'Person',
            'name': 'Bruce Willis',
            'url': '/name/nm0000246/'},
           {'@type': 'Person',
            'name': 'Jessica Alba',
            'url': '/name/nm0004695/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 730322,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Frank Miller',
              'url': '/name/nm0588340/'},
             {'@type': 'Organization', 'url': '/company/co0019626/'},
             {'@type': 'Organization', 'url': '/company/co0035848/'}],
 'datePublished': '2005-04-01',
 'description': 'Sin City is a movie starring Mickey Rourke, Clive Owen, and '
                'Bruce Willis. A movie that explores the dark and miserable '
                'town, Basin City, and tells the story of three different '
                'people, all caught up in violent corruption.',
 'director': [{'@type': 'Person',
               'name': 'Frank Miller',
               'url': '/name/nm0588340/'},
              {'@type': 'Person',
               'name': 'Robert Rodriguez',
               'url': '/name/nm0001675/'},
              {'@type': 'Person',
               'name': 'Quentin Tarantino',
               'url': '/name/nm0000233/'}],
 'duration': 'PT2H4M',
 'genre': ['Crime', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODZmYjMwNzEtNzVhNC00ZTRmLTk2M2UtNzE1MTQ2ZDAxNjc2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'neo noir,corruption,based on graphic novel,night,dark horse '
             'comics',
 'name': 'Sin City',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi667983385',
             'name': 'Sin City',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYjQ1YmQ4ZjItZWMyZS00YjUwLTgxYmUtODNhYmIwZWNjYzY1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYjQ1YmQ4ZjItZWMyZS00YjUwLTgxYmUtODNhYmIwZWNjYzY1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-10-26T03:46:07Z'},
 'url': '/title/tt0401792/'}