<?php
$infoArray = array('Actors' => array('Ana de la Reguera&tv',
            'Boyd Holbrook&tv',
            'Joanna Christie&tv',
            'Maurice Compte&tv',
            'Roberto Urbina&tv',
            'Wagner Moura&tv'),
 'Added' => '2015-08-30',
 'Countries' => array('USA'),
 'Description' => '\nNarcos: A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar. ',
 'Director' => array('NA'),
 'Genres' => array('Crime&tv', 'Drama&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt2707408',
 'PrimeWire' => 'http://www.primewire.ag/tv-2767552-Narcos',
 'Ratings' => array('IMDB' => '9.7/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.61/5',
             'RT' => 'N/A',
             'Votes' => '77'),
 'Released' => '2015-08-28',
 'Runtime' => '60 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2767552_Narcos_2015.jpg',
 'Title' => 'Narcos');
?>