{'Actors': ['Andy Arness',
            'Anthony Wong',
            'Anthony Zerbe',
            'Bernard White',
            'Carrie-Anne Moss',
            'Chris Mitchell',
            'Christine Anu',
            'Christopher Kirby',
            'Clayton Watson',
            'Collin Chou',
            'Cornel West',
            'Daniel Bernhardt',
            'David Franklin',
            'David Kilde',
            'David No',
            'David Roberts',
            'Don Battee',
            'Essie Davis',
            "Genevieve O'Reilly",
            'Gina Torres',
            'Gloria Foster',
            'Harold Perrineau',
            'Harry Lennix',
            'Helmut Bakaitis',
            'Hugo Weaving',
            'Ian Bliss',
            'Jada Pinkett Smith',
            'John Walton',
            'Josephine Byrnes',
            'Keanu Reeves',
            'Kelly Butler',
            'Kevin Scott',
            'Lambert Wilson',
            'Laurence Fishburne',
            'Leigh Whannell',
            'Malcolm Kennard',
            'Matt McColm',
            'Monica Bellucci',
            'Nash Edgerton',
            'Nathaniel Lees',
            'Nick Scoggin',
            'Nona Gaye',
            'Peter Lamb',
            'Randall Duk Kim',
            'Ray Anthony',
            'Rene Naufahu',
            'Robert Mammone',
            'Robyn Nevin',
            'Rupert Reid',
            'Scott McLean',
            'Socratis Otto',
            'Steve Bastoni',
            'Steve Morris',
            'Steve Vella',
            'Tony Lynch',
            'Tory Mussett'],
 'Added': '2013-02-19',
 'Countries': ['USA', 'Australia'],
 'Description': '\nThe Matrix Reloaded: Neo and the rebel leaders estimate that they have 72 hours until 250,000 probes discover Zion and destroy it and its inhabitants. During this, Neo must decide how he can save Trinity from a dark fate in his dreams. ',
 'Director': ['Andy Wachowski'],
 'Genres': ['Action', 'Thriller', 'Sci-Fi', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0234215',
 'PrimeWire': 'http://www.primewire.ag/watch-246-The-Matrix-Reloaded',
 'Ratings': {'IMDB': '7.2/10',
             'Metascore': '62%',
             'PrimeWire': '4.10/5',
             'RT': '73%',
             'Votes': '737'},
 'Released': '2003-05-15',
 'Runtime': '138 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/246_The_Matrix_Reloaded_2003.jpg',
 'Title': 'The-Matrix-Reloaded'}