{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/Futurama',
 'EntryURL': 'https://www.imdb.com/title/tt0149460',
 'Entry_json': 'Favorites/TV/snapshot/Futurama/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Futurama/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Futurama/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Billy West', 'url': '/name/nm0921942/'},
           {'@type': 'Person',
            'name': 'John DiMaggio',
            'url': '/name/nm0224007/'},
           {'@type': 'Person',
            'name': 'Katey Sagal',
            'url': '/name/nm0005408/'},
           {'@type': 'Person',
            'name': 'Tress MacNeille',
            'url': '/name/nm0534134/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 207336,
                      'ratingValue': '8.4',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'David X. Cohen',
              'url': '/name/nm0169326/'},
             {'@type': 'Person',
              'name': 'Matt Groening',
              'url': '/name/nm0004981/'},
             {'@type': 'Organization', 'url': '/company/co0223402/'},
             {'@type': 'Organization', 'url': '/company/co0056447/'},
             {'@type': 'Organization', 'url': '/company/co0159275/'}],
 'datePublished': '1999-03-28',
 'description': 'Futurama is a TV series starring Billy West, John DiMaggio, '
                'and Katey Sagal. Philip J. Fry, a pizza delivery boy, is '
                "accidentally frozen in 1999 and thawed out on New Year's Eve "
                '2999.',
 'genre': ['Animation', 'Comedy', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzA2ZDk2ZTUtMWU2Yi00NDVmLTk1ODEtMmFmMjQyNWYzODI0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
 'keywords': 'alien,robot,delivery boy,future,doctor',
 'name': 'Futurama',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from 20th Century Fox Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi2429813529',
              'name': 'Futurama: Volume One',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOWQ2MDliZjItYjgzNC00OGJhLWFjMjUtNTAzODgwMTllMzM2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOWQ2MDliZjItYjgzNC00OGJhLWFjMjUtNTAzODgwMTllMzM2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2009-01-01T06:40:35Z'}],
 'url': '/title/tt0149460/'}