{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Uncharted-2-Among-Thieves',
 'EntryURL': 'https://rawg.io/games/uncharted-2-among-thieves',
 'Entry_json': 'Favorites/Games/snapshot/Uncharted-2-Among-Thieves/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Uncharted-2-Among-Thieves/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Uncharted-2-Among-Thieves/thumb.jpg',
 'added': 2643,
 'background_image': 'https://media.rawg.io/media/games/74b/74b239f6ef0216a2f66e652d54abb2e6.jpg',
 'developers': ['Naughty Dog'],
 'genres': ['Action', 'Adventure'],
 'name': 'Uncharted 2: Among Thieves',
 'platforms': ['PlayStation 4', 'PlayStation 3'],
 'publishers': ['Sony Computer Entertainment'],
 'released': '2009-10-13',
 'slug': 'uncharted-2-among-thieves'}