{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Super-Mario-Bros',
 'EntryURL': 'https://rawg.io/games/super-mario-bros',
 'Entry_json': 'Favorites/Games/snapshot/Super-Mario-Bros/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Super-Mario-Bros/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Super-Mario-Bros/thumb.jpg',
 'added': 688,
 'background_image': 'https://media.rawg.io/media/games/154/154fea9689109f26c49c6a2db6263ef9.jpg',
 'developers': ['Nintendo'],
 'genres': ['Action', 'Adventure', 'Platformer'],
 'name': 'Super Mario Bros.',
 'platforms': ['SNES',
               'Nintendo Switch',
               'Game Boy Advance',
               'Game Boy Color',
               'NES',
               'Wii U',
               'Wii',
               'Nintendo 3DS'],
 'publishers': ['Nintendo'],
 'released': '1985-09-13',
 'slug': 'super-mario-bros'}