{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2011-09-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Art-of-Flight',
 'EntryURL': 'https://www.imdb.com/title/tt1646967',
 'Entry_json': 'Favorites/Movies/snapshot/The-Art-of-Flight/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Art-of-Flight/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Art-of-Flight/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Travis Rice',
            'url': '/name/nm1751071/'},
           {'@type': 'Person',
            'name': 'Mark Landvik',
            'url': '/name/nm2651375/'},
           {'@type': 'Person',
            'name': 'John Jackson',
            'url': '/name/nm3261915/'},
           {'@type': 'Person',
            'name': 'Nicolas Müller',
            'url': '/name/nm1903764/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 7490,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Organization', 'url': '/company/co0341726/'},
             {'@type': 'Organization', 'url': '/company/co0758861/'},
             {'@type': 'Organization', 'url': '/company/co0144319/'},
             {'@type': 'Organization', 'url': '/company/co0014171/'},
             {'@type': 'Organization', 'url': '/company/co0294964/'},
             {'@type': 'Organization', 'url': '/company/co0466676/'}],
 'datePublished': '2011-09-08',
 'description': 'The Art of Flight is a movie starring Travis Rice, Mark '
                'Landvik, and John Jackson. Two years in the making, this film '
                'gives snowboarder [ling=nm1751071] and friends the '
                'opportunity to redefine what is possible in the mountains.',
 'director': [{'@type': 'Person',
               'name': 'Curt Morgan',
               'url': '/name/nm3240319/'}],
 'duration': 'PT1H20M',
 'genre': ['Documentary', 'Adventure', 'Sport'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTc1NjUwMDU1MF5BMl5BanBnXkFtZTcwMzU5NjA4OA@@._V1_.jpg',
 'keywords': 'four word title,snowboarding,snowboard',
 'name': 'The Art of Flight',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Snowboarder Travis Rice and his friends redefine '
                             'what is possible in the mountains. Experience '
                             'the highs, as new tricks are landed and new '
                             'zones opened, alongside the lows, where '
                             'avalanches, accidents, and wrong-turns strike.',
              'embedUrl': '/video/imdb/vi3382421273',
              'name': 'Theatrical Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTU2Mzg5NTA5NF5BMl5BanBnXkFtZTgwMTk4NjgyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTU2Mzg5NTA5NF5BMl5BanBnXkFtZTgwMTk4NjgyMzE@._V1_.jpg',
              'uploadDate': '2012-12-04T19:26:45Z'}],
 'url': '/title/tt1646967/'}