{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Elder-Scrolls-V-Skyrim',
 'EntryURL': 'https://rawg.io/games/the-elder-scrolls-v-skyrim',
 'Entry_json': 'Favorites/Games/snapshot/The-Elder-Scrolls-V-Skyrim/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Elder-Scrolls-V-Skyrim/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Elder-Scrolls-V-Skyrim/thumb.jpg',
 'added': 9421,
 'background_image': 'https://media.rawg.io/media/games/e9c/e9cbc91e2090638ddab6ae0b3d334f90.jpg',
 'developers': ['Bethesda Game Studios', 'Bethesda Softworks'],
 'genres': ['Action', 'RPG'],
 'name': 'The Elder Scrolls V: Skyrim',
 'platforms': ['PC', 'PlayStation 3', 'Xbox 360', 'Nintendo Switch'],
 'publishers': ['Bethesda Softworks'],
 'released': '2011-11-11',
 'slug': 'the-elder-scrolls-v-skyrim'}