{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Star-Ocean-Till-The-End-Of-Time-2',
 'EntryURL': 'https://rawg.io/games/star-ocean-till-the-end-of-time-2',
 'Entry_json': 'Favorites/Games/snapshot/Star-Ocean-Till-The-End-Of-Time-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Star-Ocean-Till-The-End-Of-Time-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Star-Ocean-Till-The-End-Of-Time-2/thumb.jpg',
 'added': 12,
 'background_image': 'https://media.rawg.io/media/screenshots/984/984217a69d48a938c3c34ecf3986de94.jpg',
 'developers': ['Tri-Ace', 'tri-Crescendo'],
 'genres': ['Action'],
 'name': 'Star Ocean: Till the End of Time',
 'platforms': ['PlayStation 4', 'PlayStation 2'],
 'publishers': ['Square Enix'],
 'released': '2003-02-27',
 'slug': 'star-ocean-till-the-end-of-time-2'}