{'Actors': [],
 'Added': '2015-02-19',
 'Countries': ['UK'],
 'Description': '\nThe Brain Hack: A metaphysical thriller for the digital generation. ',
 'Director': ['Joseph White'],
 'Genres': ['Short'],
 'IMDB': 'http://www.imdb.com/title/tt3704676',
 'PrimeWire': 'http://www.primewire.ag/watch-2758243-The-Brain-Hack',
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.09/5',
             'RT': 'N/A',
             'Votes': '22'},
 'Released': '2014-06-04',
 'Runtime': '20 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2758243_The_Brain_Hack_1969_24.jpg',
 'Title': 'The-Brain-Hack'}