{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-17',
 'EntryPath': 'Favorites/Movies/snapshot/Don-Jon',
 'EntryURL': 'https://www.imdb.com/title/tt2229499',
 'Entry_json': 'Favorites/Movies/snapshot/Don-Jon/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Don-Jon/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Don-Jon/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Joseph Gordon-Levitt',
            'url': '/name/nm0330687/'},
           {'@type': 'Person',
            'name': 'Scarlett Johansson',
            'url': '/name/nm0424060/'},
           {'@type': 'Person',
            'name': 'Julianne Moore',
            'url': '/name/nm0000194/'},
           {'@type': 'Person',
            'name': 'Tony Danza',
            'url': '/name/nm0001103/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 225325,
                      'ratingValue': '6.5',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Joseph Gordon-Levitt',
              'url': '/name/nm0330687/'},
             {'@type': 'Organization', 'url': '/company/co0179337/'},
             {'@type': 'Organization', 'url': '/company/co0301807/'},
             {'@type': 'Organization', 'url': '/company/co0415835/'},
             {'@type': 'Organization', 'url': '/company/co0236721/'}],
 'datePublished': '2013-09-19',
 'description': 'Don Jon is a movie starring Joseph Gordon-Levitt, Scarlett '
                'Johansson, and Julianne Moore. A New Jersey guy dedicated to '
                'his family, friends, and church, develops unrealistic '
                'expectations from watching porn and works to find...',
 'director': [{'@type': 'Person',
               'name': 'Joseph Gordon-Levitt',
               'url': '/name/nm0330687/'}],
 'duration': 'PT1H30M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BN2ZhY2IzMWQtMGU4MC00ODg2LThkNWMtNWMzYmM2OTc5ZDMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'sex,watching porn,pornography,husband wife '
             'relationship,pornography addict',
 'name': 'Don Jon',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Watch a TV spot for Don Jon.  A New Jersey guy '
                             'dedicated to his family, friends, and church, '
                             'develops unrealistic expectations from watching '
                             'porn and works to find happiness and intimacy '
                             'with his potential true love.',
              'embedUrl': '/video/imdb/vi2483071257',
              'name': 'TV Spot',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjI1ODg1MDI1NV5BMl5BanBnXkFtZTgwOTI5NjkyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjI1ODg1MDI1NV5BMl5BanBnXkFtZTgwOTI5NjkyMzE@._V1_.jpg',
              'uploadDate': '2013-08-27T03:19:34Z'}],
 'url': '/title/tt2229499/'}