{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-25',
 'EntryPath': 'Favorites/Movies/snapshot/The-Science-Of-Sleep',
 'EntryURL': 'https://www.imdb.com/title/tt0354899',
 'Entry_json': 'Favorites/Movies/snapshot/The-Science-Of-Sleep/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Science-Of-Sleep/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Science-Of-Sleep/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gael García Bernal',
            'url': '/name/nm0305558/'},
           {'@type': 'Person',
            'name': 'Charlotte Gainsbourg',
            'url': '/name/nm0001250/'},
           {'@type': 'Person', 'name': 'Miou-Miou', 'url': '/name/nm0591877/'},
           {'@type': 'Person',
            'name': 'Alain Chabat',
            'url': '/name/nm0149260/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 66894,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Michel Gondry',
              'url': '/name/nm0327273/'},
             {'@type': 'Organization', 'url': '/company/co0309685/'},
             {'@type': 'Organization', 'url': '/company/co0178269/'},
             {'@type': 'Organization', 'url': '/company/co0044140/'},
             {'@type': 'Organization', 'url': '/company/co0028557/'},
             {'@type': 'Organization', 'url': '/company/co0093477/'},
             {'@type': 'Organization', 'url': '/company/co0025719/'},
             {'@type': 'Organization', 'url': '/company/co0106448/'}],
 'datePublished': '2006-08-16',
 'description': 'La science des rêves is a movie starring Gael García Bernal, '
                'Charlotte Gainsbourg, and Miou-Miou. A man entranced by his '
                'dreams and imagination is love-struck with a French woman and '
                'feels he can show her his world.',
 'director': {'@type': 'Person',
              'name': 'Michel Gondry',
              'url': '/name/nm0327273/'},
 'duration': 'PT1H45M',
 'genre': ['Comedy', 'Drama', 'Fantasy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg3NTcxNzY5NV5BMl5BanBnXkFtZTcwODk5NTQzMQ@@._V1_.jpg',
 'keywords': 'dream,dream world,neighbor,boyfriend girlfriend '
             'relationship,giant hand',
 'name': 'La science des rêves',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Warner Home Video',
             'embedUrl': '/video/imdb/vi4260954393',
             'name': 'The Science of Sleep',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjVkNDlkY2YtN2UzMi00NDlkLThhNzUtZDQwZDk1ODg4YWNiXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjVkNDlkY2YtN2UzMi00NDlkLThhNzUtZDQwZDk1ODg4YWNiXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T17:09:52Z'},
 'url': '/title/tt0354899/'}