{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-12-30',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal',
 'EntryURL': 'https://www.imdb.com/title/tt0362227',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Hanks', 'url': '/name/nm0000158/'},
           {'@type': 'Person',
            'name': 'Catherine Zeta-Jones',
            'url': '/name/nm0001876/'},
           {'@type': 'Person',
            'name': 'Chi McBride',
            'url': '/name/nm0564277/'},
           {'@type': 'Person',
            'name': 'Stanley Tucci',
            'url': '/name/nm0001804/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 390795,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Niccol',
              'url': '/name/nm0629272/'},
             {'@type': 'Person',
              'name': 'Sacha Gervasi',
              'url': '/name/nm0315065/'},
             {'@type': 'Person',
              'name': 'Sacha Gervasi',
              'url': '/name/nm0315065/'},
             {'@type': 'Person',
              'name': 'Jeff Nathanson',
              'url': '/name/nm0622288/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0009119/'},
             {'@type': 'Organization', 'url': '/company/co0108321/'}],
 'datePublished': '2004-06-18',
 'description': 'The Terminal is a movie starring Tom Hanks, Catherine '
                'Zeta-Jones, and Chi McBride. An Eastern European tourist '
                'unexpectedly finds himself stranded in JFK airport, and must '
                'take up temporary residence there.',
 'director': {'@type': 'Person',
              'name': 'Steven Spielberg',
              'url': '/name/nm0000229/'},
 'duration': 'PT2H8M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM1MTIwNTMxOF5BMl5BanBnXkFtZTcwNjIxMjQyMw@@._V1_.jpg',
 'keywords': 'airport,flight attendant,man without a country,fish out of '
             'water,construction site',
 'name': 'The Terminal',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi2012938521',
             'name': 'The Terminal',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMGQxYzk3YWEtZGY4Zi00M2YyLWFiMmQtOWExOTg1MDFjZTVkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMGQxYzk3YWEtZGY4Zi00M2YyLWFiMmQtOWExOTg1MDFjZTVkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T17:15:21Z'},
 'url': '/title/tt0362227/'}