{'Actors': ['Aleksandr Sountsov',
            'Ana Maria Quintana',
            'Barry Julien',
            'Barry Shabaka Henley',
            'Bob Morrisey',
            'Carl Alacchi',
            'Carlease Burke',
            'Cas Anvar',
            'Cass Asher',
            'Catherine Zeta-Jones',
            'Chi McBride',
            'Claudia Barroso',
            'Conrad Pla',
            'Dan Finnerty',
            'Danette Mackay',
            'Diego Luna',
            'Dilva Henry',
            'Eddie Jones',
            'Guillermo D&#xED;az',
            'Holly Traister',
            'Hondo Flemming',
            'Ian Finlay',
            'Jerald Garner',
            'Jim Ishida',
            'John Eddins',
            'Jude Ciccolella',
            'Justin Rodgers Hall',
            'Ken Weiner',
            'Kenneth Choi',
            'Kent Shocknek',
            'Kevin Mukherji',
            'Kevin Ryder',
            'Kumar Pallana',
            'Lydia Blanco',
            'Mark Ivanir',
            'Matt Holland',
            'Mel Rodriguez',
            'Michael Nouri',
            'Michelle Arthur',
            'Mik Scriba',
            'Rachel Oliva',
            'Rini Bell',
            'Robert Covarrubias',
            'Sasha Spielberg',
            'Scott Adsit',
            'Stanley Tucci',
            'Stephen Mendel',
            'Stephon Fuller',
            'Susan Engel',
            'Terry Haig',
            'Tom Hanks',
            'Tony Sagastizado I',
            'Tony Swift',
            'Toufig Tulsiram',
            'Valeri Nikolayev',
            'Zoe Saldana'],
 'Added': '2014-12-30',
 'Countries': ['USA'],
 'Description': '\n'
                'The Terminal: An eastern immigrant finds himself stranded in '
                'JFK airport, and must take up temporary residence there. ',
 'Director': ['Steven Spielberg'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal',
 'EntryURL': 'https://www.imdb.com/title/tt0362227',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Terminal/info.py',
 'Genres': ['Drama', 'Comedy', 'Romance'],
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': '55%',
             'PrimeWire': '4.42/5',
             'RT': '61%',
             'Votes': '781'},
 'Released': '2004-06-09',
 'Runtime': '128 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2060_The_Terminal_2004.jpg',
 'Title': 'The-Terminal'}