{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-12',
 'EntryPath': 'Favorites/Movies/snapshot/2010',
 'EntryURL': 'https://www.imdb.com/title/tt0086837',
 'Entry_json': 'Favorites/Movies/snapshot/2010/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/2010/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/2010/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Roy Scheider',
            'url': '/name/nm0001702/'},
           {'@type': 'Person',
            'name': 'John Lithgow',
            'url': '/name/nm0001475/'},
           {'@type': 'Person',
            'name': 'Helen Mirren',
            'url': '/name/nm0000545/'},
           {'@type': 'Person',
            'name': 'Bob Balaban',
            'url': '/name/nm0000837/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 48458,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Arthur C. Clarke',
              'url': '/name/nm0002009/'},
             {'@type': 'Person',
              'name': 'Peter Hyams',
              'url': '/name/nm0001382/'},
             {'@type': 'Organization', 'url': '/company/co0007143/'}],
 'datePublished': '1984-12-07',
 'description': '2010: The Year We Make Contact is a movie starring Roy '
                'Scheider, John Lithgow, and Helen Mirren. A joint U.S.-Soviet '
                'expedition is sent to Jupiter to learn what happened to the '
                'Discovery, and H.A.L.',
 'director': {'@type': 'Person',
              'name': 'Peter Hyams',
              'url': '/name/nm0001382/'},
 'duration': 'PT1H56M',
 'genre': ['Adventure', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTU1NDQwZjQtODc2YS00MTE4LWE5YTctMmYwYmNiYTU2MzRmXkEyXkFqcGdeQXVyODU2MDg1NzU@._V1_.jpg',
 'keywords': 'year 2010,the white house,lincoln memorial,year as title,1980s '
             'film',
 'name': '2010: The Year We Make Contact',
 'url': '/title/tt0086837/'}