{'Actors': ['Chris Elliott&tv',
            'Daniel Stern&tv',
            'Gary Kroeger&tv',
            'Jackie Hoffman&tv',
            'Jim Wise&tv',
            'Kathy Griffin&tv',
            'Larry Miller&tv',
            'Tom Kenny&tv',
            'Tress MacNeille&tv'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                'Dilbert: Cubicle denizen Dilbert toils away at Path-E-Tech '
                'which makes undefined products. The focus is on his survival '
                'amongst a moronic boss, hostile co-workers and his malevolent '
                'pet, Dogbert. ',
 'Director': ['Rick Del Carmen'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert',
 'EntryURL': 'https://www.imdb.com/title/tt0118984',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert/info.py',
 'Genres': ['Animation&tv', 'Comedy&tv'],
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.61/5',
             'RT': 'N/A',
             'Votes': '33'},
 'Released': '1999-01-25',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/13051_Dilbert_1999.jpg',
 'Title': 'Dilbert'}