{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert',
 'EntryURL': 'https://www.imdb.com/title/tt0118984',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Dilbert/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Daniel Stern',
            'url': '/name/nm0827663/'},
           {'@type': 'Person',
            'name': 'Larry Miller',
            'url': '/name/nm0588777/'},
           {'@type': 'Person',
            'name': 'Gordon Hunt',
            'url': '/name/nm0402460/'},
           {'@type': 'Person',
            'name': 'Chris Elliott',
            'url': '/name/nm0254402/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 5358,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Scott Adams',
              'url': '/name/nm0011346/'},
             {'@type': 'Person',
              'name': 'Larry Charles',
              'url': '/name/nm0153078/'},
             {'@type': 'Organization', 'url': '/company/co0036697/'},
             {'@type': 'Organization', 'url': '/company/co0108291/'},
             {'@type': 'Organization', 'url': '/company/co0061343/'},
             {'@type': 'Organization', 'url': '/company/co0074221/'},
             {'@type': 'Organization', 'url': '/company/co0081438/'}],
 'datePublished': '1999-01-25',
 'description': 'Dilbert is a TV series starring Daniel Stern, Larry Miller, '
                'and Gordon Hunt. Cubicle denizen Dilbert toils away at '
                'Path-E-Tech which makes undefined products. The focus is on '
                'his survival amongst a moronic boss, hostile co-workers...',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM2NTg5MDA1Ml5BMl5BanBnXkFtZTcwNjE5NjQyMQ@@._V1_.jpg',
 'keywords': 'character name as series title,forename as series title,one word '
             'series title,man wears eyeglasses,cubicle',
 'name': 'Dilbert',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Sony Pictures Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi1403126041',
             'name': 'Dilbert',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjMzYWQ2MTgtMTdkMi00YWM1LTgwMjktMDRiZDRkY2MwNDI1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjMzYWQ2MTgtMTdkMi00YWM1LTgwMjktMDRiZDRkY2MwNDI1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T13:51:47Z'},
 'url': '/title/tt0118984/'}