{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Kill-Bill-Vol-2',
 'EntryURL': 'https://www.imdb.com/title/tt0378194',
 'Entry_json': 'Favorites/Movies/snapshot/Kill-Bill-Vol-2/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Kill-Bill-Vol-2/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Kill-Bill-Vol-2/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Uma Thurman',
            'url': '/name/nm0000235/'},
           {'@type': 'Person',
            'name': 'David Carradine',
            'url': '/name/nm0001016/'},
           {'@type': 'Person',
            'name': 'Michael Madsen',
            'url': '/name/nm0000514/'},
           {'@type': 'Person',
            'name': 'Daryl Hannah',
            'url': '/name/nm0000435/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 665558,
                      'ratingValue': '8.0',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Person',
              'name': 'Uma Thurman',
              'url': '/name/nm0000235/'},
             {'@type': 'Organization', 'url': '/company/co0022594/'},
             {'@type': 'Organization', 'url': '/company/co0019267/'},
             {'@type': 'Organization', 'url': '/company/co0086625/'}],
 'datePublished': '2004-04-16',
 'description': 'Kill Bill: Vol. 2 is a movie starring Uma Thurman, David '
                'Carradine, and Michael Madsen. The Bride continues her quest '
                'of vengeance against her former boss and lover Bill, the '
                'reclusive bouncer Budd, and the treacherous, one-eyed...',
 'director': [{'@type': 'Person',
               'name': 'Quentin Tarantino',
               'url': '/name/nm0000233/'}],
 'duration': 'PT2H17M',
 'genre': ['Action', 'Crime', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNmFiYmJmN2QtNWQwMi00MzliLThiOWMtZjQxNGRhZTQ1MjgyXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_.jpg',
 'keywords': 'bride,vengeance,female assassin,martial arts,revenge',
 'name': 'Kill Bill: Vol. 2',
 'trailer': [{'@type': 'VideoObject',
              'description': 'CT #1, post',
              'embedUrl': '/video/imdb/vi405667865',
              'name': 'Kill Bill: Vol. 2',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZjA3OThlOWUtZWZiYi00M2I2LTg0Y2QtNWY2YThjZjE4Y2U1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZjA3OThlOWUtZWZiYi00M2I2LTg0Y2QtNWY2YThjZjE4Y2U1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-09-10T03:24:55Z'}],
 'url': '/title/tt0378194/'}