{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Gran-Turismo',
 'EntryURL': 'https://rawg.io/games/gran-turismo',
 'Entry_json': 'Favorites/Games/snapshot/Gran-Turismo/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Gran-Turismo/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Gran-Turismo/thumb.jpg',
 'added': 105,
 'background_image': 'https://media.rawg.io/media/screenshots/bcb/bcb977460712c1ac2c2026d30699130a.jpg',
 'developers': ['Sony Interactive Entertainment',
                'Cyberhead',
                'Polys Entertainment'],
 'genres': ['Racing'],
 'name': 'Gran Turismo',
 'platforms': ['PlayStation'],
 'publishers': ['Sony Computer Entertainment',
                'Sony Interactive Entertainment'],
 'released': '1997-12-22',
 'slug': 'gran-turismo'}