{'Actors': ['Alexis Thorpe',
            'Annika Peterson',
            'David Lee Smith',
            'Ellen Crawford',
            'John Billingsley',
            'Richard Riehle',
            'Tony Todd',
            'William Katt'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\nThe Man from Earth: An impromptu goodbye party for Professor John Oldman becomes a mysterious interrogation after the retiring... ',
 'Director': ['Richard Schenkman'],
 'Genres': ['Drama', 'Sci-Fi', 'History'],
 'IMDB': 'http://www.imdb.com/title/tt0756683',
 'PrimeWire': 'http://www.primewire.ag/watch-6353-The-Man-from-Earth',
 'Ratings': {'IMDB': '8.0/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.15/5',
             'RT': 'N/A',
             'Votes': '510'},
 'Released': '2007-06-10',
 'Runtime': '87 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/6353_The_Man_from_Earth_2007.jpg',
 'Title': 'The-Man-from-Earth'}