{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-25',
 'EntryPath': 'Favorites/Movies/snapshot/The-Mind-Job',
 'EntryURL': 'https://www.imdb.com/title/tt2312832',
 'Entry_json': 'Favorites/Movies/snapshot/The-Mind-Job/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Mind-Job/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Mind-Job/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Matthew Moore',
            'url': '/name/nm0601599/'},
           {'@type': 'Person',
            'name': 'Krew Boylan',
            'url': '/name/nm1812345/'},
           {'@type': 'Person',
            'name': 'Lorna Lesley',
            'url': '/name/nm0504047/'},
           {'@type': 'Person',
            'name': 'Paul Barry',
            'url': '/name/nm0058124/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 33,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Person',
             'name': 'JJ Winlove',
             'url': '/name/nm4142695/'},
 'description': 'The Mind Job is a short starring Matthew Moore, Krew Boylan, '
                'and Lorna Lesley. When nice guy Zac finds his deepest '
                'fantasies inadvertently appearing on a computer screen in '
                'front of his girlfriend and a policewoman, he has little...',
 'director': {'@type': 'Person',
              'name': 'JJ Winlove',
              'url': '/name/nm4142695/'},
 'duration': 'PT16M',
 'genre': ['Short', 'Comedy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjFkODI2NmYtMGY0MC00M2YwLWFiYzAtODE4OTczNTg4ZGFiXkEyXkFqcGdeQXVyMjEzMDIyMDY@._V1_.jpg',
 'name': 'The Mind Job',
 'url': '/title/tt2312832/'}