{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Yume',
 'EntryURL': 'https://www.imdb.com/title/tt0100998',
 'Entry_json': 'Favorites/Movies/snapshot/Yume/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Yume/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Yume/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Akira Terao',
            'url': '/name/nm0855417/'},
           {'@type': 'Person',
            'name': 'Mitsuko Baishô',
            'url': '/name/nm0047963/'},
           {'@type': 'Person',
            'name': 'Toshie Negishi',
            'url': '/name/nm0624383/'},
           {'@type': 'Person',
            'name': 'Mieko Harada',
            'url': '/name/nm7014801/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 22965,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Akira Kurosawa',
              'url': '/name/nm0000041/'},
             {'@type': 'Person',
              'name': 'Ishirô Honda',
              'url': '/name/nm0393094/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0054092/'}],
 'datePublished': '1990-05-11',
 'description': 'Yume is a movie starring Akira Terao, Mitsuko Baishô, and '
                'Toshie Negishi. A collection of tales based upon the actual '
                'dreams of director Akira Kurosawa.',
 'director': [{'@type': 'Person',
               'name': 'Akira Kurosawa',
               'url': '/name/nm0000041/'},
              {'@type': 'Person',
               'name': 'Ishirô Honda',
               'url': '/name/nm0393094/'}],
 'duration': 'PT1H59M',
 'genre': ['Drama', 'Fantasy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDBkODdjMzEtNTY1NC00ZWQ5LTk3NDUtY2IwMTk5MzhmNTUwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg',
 'keywords': 'japanese boy,japanese woman,japanese mother,mother son '
             'relationship,sandal',
 'name': 'Yume',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Warner Home Video',
             'embedUrl': '/video/imdb/vi105028633',
             'name': "Akira Kurosawa's Dreams",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzg1MzEwZmItMDM0MS00YTBhLTk5M2MtYWJlNzQzYWZkYmZkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzg1MzEwZmItMDM0MS00YTBhLTk5M2MtYWJlNzQzYWZkYmZkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-09-21T03:04:51Z'},
 'url': '/title/tt0100998/'}