{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-22',
 'EntryPath': 'Favorites/Movies/snapshot/Final-Fantasy-VII-Advent-Children',
 'EntryURL': 'https://www.imdb.com/title/tt0385700',
 'Entry_json': 'Favorites/Movies/snapshot/Final-Fantasy-VII-Advent-Children/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Final-Fantasy-VII-Advent-Children/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Final-Fantasy-VII-Advent-Children/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Takahiro Sakurai',
            'url': '/name/nm0757327/'},
           {'@type': 'Person', 'name': 'Ayumi Itô', 'url': '/name/nm0411683/'},
           {'@type': 'Person',
            'name': 'Shôtarô Morikubo',
            'url': '/name/nm0605453/'},
           {'@type': 'Person',
            'name': 'Maaya Sakamoto',
            'url': '/name/nm0757087/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 54444,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Kazushige Nojima',
              'url': '/name/nm1081992/'},
             {'@type': 'Person',
              'name': 'Brian Gray',
              'url': '/name/nm1638748/'},
             {'@type': 'Person',
              'name': 'Yoshinori Kitase',
              'url': '/name/nm0457592/'},
             {'@type': 'Person',
              'name': 'Tetsuya Nomura',
              'url': '/name/nm0634602/'},
             {'@type': 'Person',
              'name': 'Hironobu Sakaguchi',
              'url': '/name/nm0756983/'},
             {'@type': 'Organization', 'url': '/company/co0102823/'},
             {'@type': 'Organization', 'url': '/company/co0040831/'}],
 'datePublished': '2005-09-14',
 'description': 'Fainaru fantajî sebun adobento chirudoren is a movie starring '
                'Takahiro Sakurai, Ayumi Itô, and Shôtarô Morikubo. An '
                'ex-mercenary is forced out of isolation when three mysterious '
                "men kidnap and brainwash the city's children afflicted...",
 'director': [{'@type': 'Person',
               'name': 'Tetsuya Nomura',
               'url': '/name/nm0634602/'},
              {'@type': 'Person',
               'name': 'Takeshi Nozue',
               'url': '/name/nm1481959/'}],
 'duration': 'PT1H41M',
 'genre': ['Animation',
           'Action',
           'Adventure',
           'Drama',
           'Family',
           'Fantasy',
           'Mystery',
           'Sci-Fi',
           'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTk4NjBhZTUtN2MwMy00MzIyLWFhN2ItMmUwYzQ4MWQxODM3L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_.jpg',
 'keywords': 'based on video game,profanity,disease,silver hair,phone',
 'name': 'Fainaru fantajî sebun adobento chirudoren',
 'trailer': {'@type': 'VideoObject',
             'description': 'Blu-Ray trailer for this animated action film',
             'embedUrl': '/video/imdb/vi150209049',
             'name': 'Final Fantasy VII: Advent Children',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmIwN2Q4ZmItNTIxOC00MWNlLTg4OGYtMzBiZWE2YTQxMDc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmIwN2Q4ZmItNTIxOC00MWNlLTg4OGYtMzBiZWE2YTQxMDc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2009-06-13T03:45:40Z'},
 'url': '/title/tt0385700/'}