{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Guarantee',
 'EntryURL': 'https://www.imdb.com/title/tt3843254',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Guarantee/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Guarantee/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Guarantee/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Guarantee/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Orla Fitzgerald',
            'url': '/name/nm1695893/'},
           {'@type': 'Person',
            'name': 'Peter Coonan',
            'url': '/name/nm0177742/'},
           {'@type': 'Person',
            'name': 'David Murray',
            'url': '/name/nm0614903/'},
           {'@type': 'Person',
            'name': 'Morgan C. Jones',
            'url': '/name/nm0428901/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 99,
                     'ratingValue': '5.1',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Colin Murphy',
              'url': '/name/nm6609991/'},
             {'@type': 'Person',
              'name': 'Colin Murphy',
              'url': '/name/nm6609991/'},
             {'@type': 'Organization', 'url': '/company/co0488940/'}],
 'datePublished': '2014-10-30',
 'description': 'The Guarantee is a movie starring Orla Fitzgerald, Peter '
                'Coonan, and David Murray. On the night of September 29, 2008, '
                'the Irish government decided to guarantee the entire domestic '
                "banking system. 'The Guarantee' tells the story of...",
 'director': {'@type': 'Person',
              'name': 'Ian Power',
              'url': '/name/nm0694405/'},
 'duration': 'PT1H16M',
 'genre': ['Drama', 'History', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzgxMTAwNTQ2Ml5BMl5BanBnXkFtZTgwMzM4MDYwMzE@._V1_.jpg',
 'keywords': 'ireland,finance,politics',
 'name': 'The Guarantee',
 'url': '/title/tt3843254/'}