{'Actors': ['Damian Lewis&tv',
            'David Costabile&tv',
            'Maggie Siff&tv',
            'Malin Akerman&tv',
            'Melissa Joyce&tv',
            'Paul Giamatti&tv',
            'Toby Leonard Moore&tv'],
 'Added': '2016-01-27',
 'Countries': ['USA'],
 'Description': '\r\n              Billions: U.S. Attorney Chuck Rhoades goes after hedge fund king, Bobby "Axe" Axelrod in a battle between two powerful New York figures.             ',
 'Director': ['NA'],
 'Genres': ['Action&tv', 'Crime&tv', 'Drama&tv'],
 'IMDB': 'http://www.imdb.com/title/tt4270492',
 'PrimeWire': 'http://www.primewire.ag/tv-2772431-Billions',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '4.29/5',
             'RT': 'N/A',
             'Votes': '487'},
 'Released': '2016-01-17',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2772431_Billions_2016_37.jpg',
 'Title': 'Billions'}