{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-01-27',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Billions',
 'EntryURL': 'https://www.imdb.com/title/tt4270492',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Billions/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Billions/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Billions/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Paul Giamatti',
            'url': '/name/nm0316079/'},
           {'@type': 'Person',
            'name': 'Damian Lewis',
            'url': '/name/nm0507073/'},
           {'@type': 'Person',
            'name': 'Maggie Siff',
            'url': '/name/nm1745019/'},
           {'@type': 'Person',
            'name': 'David Costabile',
            'url': '/name/nm0182345/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 63623,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Brian Koppelman',
              'url': '/name/nm0002718/'},
             {'@type': 'Person',
              'name': 'David Levien',
              'url': '/name/nm0505522/'},
             {'@type': 'Person',
              'name': 'Andrew Ross Sorkin',
              'url': '/name/nm3376444/'},
             {'@type': 'Organization', 'url': '/company/co0048667/'},
             {'@type': 'Organization', 'url': '/company/co0695646/'}],
 'datePublished': '2016-01-01',
 'description': 'Billions is a TV series starring Paul Giamatti, Damian Lewis, '
                'and Maggie Siff. U.S. Attorney Chuck Rhoades goes after hedge '
                'fund king Bobby "Axe" Axelrod in a battle between two '
                'powerful New York figures.',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BNjJkNzdkNjItNmVmZi00MzkzLTg0MTUtZjYzZDhmNzNlMTY4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'u.s. attorney,hedge fund,white collar crime,rivalry,profanity',
 'name': 'Billions',
 'trailer': {'@type': 'VideoObject',
             'embedUrl': '/video/imdb/vi809941529',
             'name': 'Trailer (post live)',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYWI1ZDczOTEtMGFiOS00MjAwLThmMmUtNjRjOGQyNTdhODhmXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYWI1ZDczOTEtMGFiOS00MjAwLThmMmUtNjRjOGQyNTdhODhmXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-03-08T01:01:44Z'},
 'url': '/title/tt4270492/'}