{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Portal',
 'EntryURL': 'https://rawg.io/games/portal',
 'Entry_json': 'Favorites/Games/snapshot/Portal/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Portal/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Portal/thumb.jpg',
 'added': 8944,
 'background_image': 'https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg',
 'developers': ['Valve Software', 'NVIDIA Lightspeed Studios'],
 'genres': ['Action', 'Adventure', 'Puzzle'],
 'name': 'Portal',
 'platforms': ['macOS', 'Android', 'PC', 'Linux', 'PlayStation 3', 'Xbox 360'],
 'publishers': ['Valve'],
 'released': '2007-10-09',
 'slug': 'portal'}