{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Forrest-Gump',
 'EntryURL': 'https://www.imdb.com/title/tt0109830',
 'Entry_json': 'Favorites/Movies/snapshot/Forrest-Gump/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Forrest-Gump/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Forrest-Gump/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Hanks', 'url': '/name/nm0000158/'},
           {'@type': 'Person',
            'name': 'Robin Wright',
            'url': '/name/nm0000705/'},
           {'@type': 'Person',
            'name': 'Gary Sinise',
            'url': '/name/nm0000641/'},
           {'@type': 'Person',
            'name': 'Sally Field',
            'url': '/name/nm0000398/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1732399,
                      'ratingValue': '8.8',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Winston Groom',
              'url': '/name/nm0343165/'},
             {'@type': 'Person',
              'name': 'Eric Roth',
              'url': '/name/nm0744839/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'}],
 'datePublished': '1994-07-06',
 'description': 'Forrest Gump is a movie starring Tom Hanks, Robin Wright, and '
                'Gary Sinise. The presidencies of Kennedy and Johnson, the '
                'events of Vietnam, Watergate and other historical events '
                'unfold through the perspective of an Alabama man with...',
 'director': [{'@type': 'Person',
               'name': 'Robert Zemeckis',
               'url': '/name/nm0000709/'}],
 'duration': 'PT2H22M',
 'genre': ['Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'vietnam war,amputee,war hero,vietnam,mother',
 'name': 'Forrest Gump',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer 1 for Forrest Gump',
              'embedUrl': '/video/imdb/vi3567517977',
              'name': 'Forrest Gump',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYzQyMWQ1ODMtZGE2OS00YzQyLWE2OWYtZmU5OGFiMWMwYmIyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYzQyMWQ1ODMtZGE2OS00YzQyLWE2OWYtZmU5OGFiMWMwYmIyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T13:59:31Z'}],
 'url': '/title/tt0109830/'}