{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Kingdom-Hearts',
 'EntryURL': 'https://rawg.io/games/kingdom-hearts',
 'Entry_json': 'Favorites/Games/snapshot/Kingdom-Hearts/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Kingdom-Hearts/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Kingdom-Hearts/thumb.jpg',
 'added': 313,
 'background_image': 'https://media.rawg.io/media/games/bc3/bc3c433821089108642a41a3057f92c5.jpg',
 'developers': ['Square'],
 'genres': ['RPG'],
 'name': 'Kingdom Hearts',
 'platforms': ['PlayStation 2'],
 'publishers': ['Sony Computer Entertainment', 'Square'],
 'released': '2002-03-28',
 'slug': 'kingdom-hearts'}