{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-25',
 'EntryPath': 'Favorites/Movies/snapshot/Living-in-Oblivion',
 'EntryURL': 'https://www.imdb.com/title/tt0113677',
 'Entry_json': 'Favorites/Movies/snapshot/Living-in-Oblivion/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Living-in-Oblivion/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Living-in-Oblivion/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Steve Buscemi',
            'url': '/name/nm0000114/'},
           {'@type': 'Person',
            'name': 'Catherine Keener',
            'url': '/name/nm0001416/'},
           {'@type': 'Person',
            'name': 'Dermot Mulroney',
            'url': '/name/nm0000551/'},
           {'@type': 'Person',
            'name': 'Danielle von Zerneck',
            'url': '/name/nm0903272/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 15847,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Tom DiCillo',
              'url': '/name/nm0001139/'},
             {'@type': 'Organization', 'url': '/company/co0066819/'},
             {'@type': 'Organization', 'url': '/company/co0001698/'}],
 'datePublished': '1995-07-21',
 'description': 'Living in Oblivion is a movie starring Steve Buscemi, '
                'Catherine Keener, and Dermot Mulroney. This ultimate tribute '
                'to all independent filmmakers takes place during one day on '
                'the set of a non-budget movie.',
 'director': {'@type': 'Person',
              'name': 'Tom DiCillo',
              'url': '/name/nm0001139/'},
 'duration': 'PT1H30M',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BN2U2MDdjZjUtMGU1Ni00MzlkLTllZWQtZmJjNzJmYjE5YjAxXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_.jpg',
 'keywords': 'neo screwball comedy,looking at oneself in a '
             'mirror,1990s,filmmaking,filmmaker',
 'name': 'Living in Oblivion',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Sony Pictures Classics',
             'embedUrl': '/video/imdb/vi111870233',
             'name': 'Living In Oblivion',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODMxZjg5Y2MtMGZiNS00NzE0LTg1ZDAtN2ZiYzM5OTk5ZGM3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODMxZjg5Y2MtMGZiNS00NzE0LTg1ZDAtN2ZiYzM5OTk5ZGM3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:19:55Z'},
 'url': '/title/tt0113677/'}