{'Actors': ['Betsy Baker',
            'Bruce Campbell',
            'John Cameron',
            'Sam Raimi',
            'Scott Spiegel',
            'Ted Raimi'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\nThe Evil Dead: Five friends travel to a cabin in the woods, where they unknowingly release flesh-possessing demons. ',
 'Director': ['Sam Raimi'],
 'Genres': ['Fantasy', 'Horror', 'Thriller', 'Zombies'],
 'IMDB': 'http://www.imdb.com/title/tt0083907',
 'PrimeWire': 'http://www.primewire.ag/watch-899-The-Evil-Dead',
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': '70%',
             'PrimeWire': '4.12/5',
             'RT': '96%',
             'Votes': '638'},
 'Released': '1981-10-15',
 'Runtime': '85 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/899_Evil_Dead_1981.jpg',
 'Title': 'The-Evil-Dead'}