{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2017-06-11',
 'EntryPath': 'Favorites/Movies/snapshot/Inside-Job',
 'EntryURL': 'https://www.imdb.com/title/tt1645089',
 'Entry_json': 'Favorites/Movies/snapshot/Inside-Job/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Inside-Job/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Inside-Job/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Matt Damon', 'url': '/name/nm0000354/'},
           {'@type': 'Person',
            'name': 'Gylfi Zoega',
            'url': '/name/nm4968464/'},
           {'@type': 'Person',
            'name': 'Andri Snær Magnason',
            'url': '/name/nm1674617/'},
           {'@type': 'Person',
            'name': 'Sigridur Benediktsdottir',
            'url': '/name/nm4227570/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 67740,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Charles Ferguson',
              'url': '/name/nm2480587/'},
             {'@type': 'Person',
              'name': 'Chad Beck',
              'url': '/name/nm1556822/'},
             {'@type': 'Person',
              'name': 'Adam Bolt',
              'url': '/name/nm2903269/'},
             {'@type': 'Organization', 'url': '/company/co0014453/'},
             {'@type': 'Organization', 'url': '/company/co0215753/'},
             {'@type': 'Organization', 'url': '/company/co0282265/'}],
 'datePublished': '2010-02-02',
 'description': 'Inside Job is a movie starring Matt Damon, Gylfi Zoega, and '
                'Andri Snær Magnason. Takes a closer look at what brought '
                'about the 2008 financial meltdown.',
 'director': [{'@type': 'Person',
               'name': 'Charles Ferguson',
               'url': '/name/nm2480587/'}],
 'duration': 'PT1H49M',
 'genre': ['Documentary', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ3MjkyODA2Nl5BMl5BanBnXkFtZTcwNzQxMTU4Mw@@._V1_.jpg',
 'keywords': 'money,us dollars,iceland,interview,recession',
 'name': 'Inside Job',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Take a closer look at what brought about the '
                             'financial meltdown.',
              'embedUrl': '/video/imdb/vi751502873',
              'name': 'Inside Job',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTEzMTI4MjM4OF5BMl5BanBnXkFtZTgwMTc1MzIzMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTEzMTI4MjM4OF5BMl5BanBnXkFtZTgwMTc1MzIzMzE@._V1_.jpg',
              'uploadDate': '2010-08-28T07:49:21Z'}],
 'url': '/title/tt1645089/'}