{'Actors': ['John Campbell', 'Matt Damon'],
 'Added': '2017-06-11',
 'Countries': ['USA'],
 'Description': "\nInside Job: 'Inside Job' provides a comprehensive analysis of the global financial crisis of 2008, which at a cost over $20 trillion, caused millions of people to lose their jobs and homes in the worst recession since the Great Depression, and nearly resulted in a global financial collapse. Through exhaustive research and extensive interviews with key financial insiders, politicians, journalists, and academics, the film traces the rise of a rogue industry which has corrupted politics, regulation, and academia. It was made on location in the United States, Iceland, England, France, Singapore, and China. ",
 'Director': ['Charles Ferguson'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1645089',
 'PrimeWire': 'http://www.primewire.ag/watch-2716989-Inside-Job',
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': '88%',
             'PrimeWire': '4.37/5',
             'RT': '98%',
             'Votes': '639'},
 'Released': '2010-02-02',
 'Runtime': '120 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2716988_Inside_Job_2010.jpg',
 'Title': 'Inside-Job'}