{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Game-Change',
 'EntryURL': 'https://www.imdb.com/title/tt1848902',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Game-Change/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Game-Change/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Game-Change/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Ed Harris', 'url': '/name/nm0000438/'},
           {'@type': 'Person',
            'name': 'Julianne Moore',
            'url': '/name/nm0000194/'},
           {'@type': 'Person',
            'name': 'Woody Harrelson',
            'url': '/name/nm0000437/'},
           {'@type': 'Person',
            'name': 'Peter MacNicol',
            'url': '/name/nm0001493/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 20509,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Danny Strong',
              'url': '/name/nm0834960/'},
             {'@type': 'Person',
              'name': 'Mark Halperin',
              'url': '/name/nm0356927/'},
             {'@type': 'Person',
              'name': 'John Heilemann',
              'url': '/name/nm2129264/'},
             {'@type': 'Organization', 'url': '/company/co0005861/'},
             {'@type': 'Organization', 'url': '/company/co0036575/'},
             {'@type': 'Organization', 'url': '/company/co0136709/'}],
 'datePublished': '2012-03-10',
 'description': 'Game Change is a TV movie starring Ed Harris, Julianne Moore, '
                'and Woody Harrelson. Governor Sarah Palin of Alaska becomes '
                "Senator John McCain's running mate in the 2008 Presidential "
                'election.',
 'director': {'@type': 'Person',
              'name': 'Jay Roach',
              'url': '/name/nm0005366/'},
 'duration': 'PT1H58M',
 'genre': ['Biography', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQwNjkzNzg4NV5BMl5BanBnXkFtZTcwODIxMTM0Nw@@._V1_.jpg',
 'keywords': 'american politics,cell phone,down syndrome,presidential '
             'election,21st century',
 'name': 'Game Change',
 'url': '/title/tt1848902/'}