<?php
$infoArray = array('Actors' => array('Alexander Bisping',
            'Boyd Banks',
            'Cliff Curtis',
            'Donna Murphy',
            'Ellen Burstyn',
            'Ethan Suplee',
            'Hugh Jackman',
            'Kevin Kelsall',
            'Lorne Brass',
            'Mark Margolis',
            'Rachel Weisz',
            'Richard McMillan',
            'Sean Patrick Thomas',
            'Stephen McHattie'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nThe Fountain: Spanning over one thousand years, and three parallel stories, The Fountain is a story of love, death, spirituality, and the fragility of our existence in this world. ',
 'Director' => array('Darren Aronofsky'),
 'Genres' => array('Drama', 'Romance', 'Sci-Fi'),
 'IMDB' => 'http://www.imdb.com/title/tt0414993',
 'PrimeWire' => 'http://www.primewire.ag/watch-1869-The-Fountain',
 'Ratings' => array('IMDB' => '7.3/10',
             'Metascore' => '51%',
             'PrimeWire' => '4.08/5',
             'RT' => '51%',
             'Votes' => '500'),
 'Released' => '2006-09-04',
 'Runtime' => '96 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1869_The_Fountain_2006.jpg',
 'Title' => 'The-Fountain');
?>