{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-01-22',
 'EntryPath': 'Favorites/TV/snapshot/The-Nightly-Show-with-Larry-Wilmore',
 'EntryURL': 'https://www.imdb.com/title/tt3722332',
 'Entry_json': 'Favorites/TV/snapshot/The-Nightly-Show-with-Larry-Wilmore/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Nightly-Show-with-Larry-Wilmore/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Nightly-Show-with-Larry-Wilmore/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Larry Wilmore',
            'url': '/name/nm0932831/'},
           {'@type': 'Person', 'name': 'Mike Yard', 'url': '/name/nm1526338/'},
           {'@type': 'Person',
            'name': 'Rory Albanese',
            'url': '/name/nm1088947/'},
           {'@type': 'Person',
            'name': 'Holly Walker',
            'url': '/name/nm2021857/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2805,
                     'ratingValue': '5.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Jon Stewart',
              'url': '/name/nm0829537/'},
             {'@type': 'Organization', 'url': '/company/co0176273/'}],
 'datePublished': '2015-01-19',
 'description': 'The Nightly Show with Larry Wilmore is a TV series starring '
                'Larry Wilmore, Mike Yard, and Rory Albanese. A late night '
                'satirical talk show hosted by Larry Wilmore.',
 'genre': ['Comedy', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzgxZTE2NDAtMzk4ZC00ZGJkLTgyNTktZDlhYWFmOTM0OTRlXkEyXkFqcGdeQXVyNTM0NTU5Mg@@._V1_.jpg',
 'keywords': 'satire',
 'name': 'The Nightly Show with Larry Wilmore',
 'url': '/title/tt3722332/'}