{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Union-The-Business-Behind-Getting-High',
 'EntryURL': 'https://www.imdb.com/title/tt1039647',
 'Entry_json': 'Favorites/Movies/snapshot/The-Union-The-Business-Behind-Getting-High/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Union-The-Business-Behind-Getting-High/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Union-The-Business-Behind-Getting-High/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Adam Scorgie',
            'url': '/name/nm1886635/'},
           {'@type': 'Person',
            'name': 'Chris Bennett',
            'url': '/name/nm2470901/'},
           {'@type': 'Person',
            'name': 'Steve Bloom',
            'url': '/name/nm2295862/'},
           {'@type': 'Person',
            'name': 'Renee Bojee',
            'url': '/name/nm5173656/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 7581,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Brett Harvey',
              'url': '/name/nm1622441/'},
             {'@type': 'Person',
              'name': 'Adam Scorgie',
              'url': '/name/nm1886635/'},
             {'@type': 'Organization', 'url': '/company/co0308225/'}],
 'datePublished': '2007-06-08',
 'description': 'The Union: The Business Behind Getting High is a movie '
                "starring Adam Scorgie, Chris Bennett, and Steve Bloom. BC's "
                'illegal marijuana trade industry has evolved into a business '
                "giant, dubbed by some involved as 'The Union',...",
 'director': [{'@type': 'Person',
               'name': 'Brett Harvey',
               'url': '/name/nm1622441/'}],
 'duration': 'PT1H44M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTYyNjk5NDI1NV5BMl5BanBnXkFtZTcwOTk1NDU0NA@@._V1_.jpg',
 'keywords': 'cannabis,business,marijuana,weed,september 11 2001',
 'name': 'The Union: The Business Behind Getting High',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for The Union: The Business Behind '
                             'Getting High',
              'embedUrl': '/video/imdb/vi327260185',
              'name': 'The Union: The Business Behind Getting High',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNGFiNTM5YmYtNGJjMC00NjZjLThmZjMtOGQ5ZWJjODk2NTJkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNGFiNTM5YmYtNGJjMC00NjZjLThmZjMtOGQ5ZWJjODk2NTJkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2010-12-16T06:31:54Z'}],
 'url': '/title/tt1039647/'}