{'Actors': ['Cheech Marin',
            'George Bush',
            'George W Bush',
            'Greg Cooper',
            'Greg Williams',
            'Jesse Ventura',
            'Joe Rogan',
            'Richard Nixon',
            'Tommy Chong'],
 'Added': '2013-02-24',
 'Countries': ['Canada'],
 'Description': '\n'
                "The Union: The Business Behind Getting High: BC's illegal "
                'marijuana trade industry has evolved into a business giant, '
                "dubbed by some involved as 'The Union'... ",
 'Director': ['Brett Harvey'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Union-The-Business-Behind-Getting-High',
 'EntryURL': 'http://www.imdb.com/title/tt1039647',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Union-The-Business-Behind-Getting-High/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Union-The-Business-Behind-Getting-High/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Union-The-Business-Behind-Getting-High/info.py',
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1039647',
 'PrimeWire': 'http://www.primewire.ag/watch-4411-The-Union-The-Business-Behind-Getting-High',
 'Ratings': {'IMDB': '8.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.22/5',
             'RT': 'N/A',
             'Votes': '143'},
 'Released': '2007-06-08',
 'Runtime': '104 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/4411_The_Union_The_Business_Behind_Getting_High_2007.jpg',
 'Title': 'The-Union-The-Business-Behind-Getting-High'}