{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-05-25',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Silicon-Valley',
 'EntryURL': 'https://www.imdb.com/title/tt2575988',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Silicon-Valley/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Silicon-Valley/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Silicon-Valley/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Thomas Middleditch',
            'url': '/name/nm3042755/'},
           {'@type': 'Person',
            'name': 'T.J. Miller',
            'url': '/name/nm2554352/'},
           {'@type': 'Person',
            'name': 'Josh Brener',
            'url': '/name/nm3091777/'},
           {'@type': 'Person',
            'name': 'Martin Starr',
            'url': '/name/nm0771414/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 119281,
                     'ratingValue': '8.5',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'John Altschuler',
              'url': '/name/nm1014365/'},
             {'@type': 'Person',
              'name': 'Mike Judge',
              'url': '/name/nm0431918/'},
             {'@type': 'Person',
              'name': 'Dave Krinsky',
              'url': '/name/nm1015106/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0480579/'},
             {'@type': 'Organization', 'url': '/company/co0055540/'}],
 'datePublished': '2014-04-06',
 'description': 'Silicon Valley is a TV series starring Thomas Middleditch, '
                'T.J. Miller, and Josh Brener. Follows the struggle of Richard '
                'Hendricks, a Silicon Valley engineer trying to build his own '
                'company called Pied Piper.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BOTcwNzU2MGEtMzUzNC00MzMwLWJhZGItNDY3NDllYjU5YzAyXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
 'keywords': 'computer,startup,satanist,business rivalry,computer nerd',
 'name': 'Silicon Valley',
 'trailer': {'@type': 'VideoObject',
             'description': 'Big tech, bigger data, biggest season. Silicon '
                            'Valley returns for the sixth and final season '
                            'October 27 at 10pm.',
             'embedUrl': '/video/imdb/vi2598485785',
             'name': 'Season 6 Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTdiMmFhYjUtMDJiZS00MzczLTkyYzEtZjJkNzY4YTdkNTU2XkEyXkFqcGdeQWpnYW1i._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTdiMmFhYjUtMDJiZS00MzczLTkyYzEtZjJkNzY4YTdkNTU2XkEyXkFqcGdeQWpnYW1i._V1_.jpg',
             'uploadDate': '2019-10-21T17:14:49Z'},
 'url': '/title/tt2575988/'}