{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Super-Mario-Rpg',
 'EntryURL': 'https://rawg.io/games/super-mario-rpg',
 'Entry_json': 'Favorites/Games/snapshot/Super-Mario-Rpg/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Super-Mario-Rpg/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Super-Mario-Rpg/thumb.jpg',
 'added': 166,
 'background_image': 'https://media.rawg.io/media/screenshots/14b/14bfeab218c254d74e801116740e476b.jpg',
 'developers': ['Square Enix', 'Square'],
 'genres': ['RPG'],
 'name': 'Super Mario RPG: Legend of the Seven Stars',
 'platforms': ['Wii U', 'Wii', 'SNES'],
 'publishers': ['Nintendo'],
 'released': '1996-03-09',
 'slug': 'super-mario-rpg'}