{'Actors': [],
 'Added': '2013-06-29',
 'Countries': ['USA'],
 'Description': '\nVice: News series featuring startling, groundbreaking stories from around the world. ',
 'Director': ['NA'],
 'Genres': ['Documentary&tv'],
 'IMDB': 'http://www.imdb.com/title/tt2782710',
 'PrimeWire': 'http://www.primewire.ag/tv-2739173-Vice',
 'Ratings': {'IMDB': '8.8/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.20/5',
             'RT': 'N/A',
             'Votes': '693'},
 'Released': '2013-04-05',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2739173_Vice_2013.jpg',
 'Title': 'Vice'}