{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-Ix',
 'EntryURL': 'https://rawg.io/games/final-fantasy-ix',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-Ix/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-Ix/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-Ix/thumb.jpg',
 'added': 1043,
 'background_image': 'https://media.rawg.io/media/screenshots/e55/e55d3dfcd6064e796f4dca79879c2e76.jpg',
 'developers': ['Sony Interactive Entertainment',
                'Square Enix',
                'Square',
                'Guld Studio (PS4)',
                'Silicon Studio Thailand',
                'GUILD STUDIO Inc.'],
 'genres': ['Adventure', 'RPG'],
 'name': 'Final Fantasy IX',
 'platforms': ['PlayStation 3',
               'PS Vita',
               'Android',
               'Xbox One',
               'Nintendo Switch',
               'PlayStation',
               'PC',
               'PSP'],
 'publishers': ['Electronic Arts', 'Square Enix', 'Square'],
 'released': '2000-07-07',
 'slug': 'final-fantasy-ix'}