<?php
$infoArray = array('Actors' => array(' Brian Lee Franklin ',
            ' Donald Watkins ',
            ' Jessica Collins ',
            ' Jill Jane Clements ',
            ' Joe Chrest ',
            ' Kerry Cahill ',
            ' Sean Bridgers ',
            ' Thomas Francis Murphy ',
            'Gugu Mbatha-Raw',
            'Keri Russell',
            'Mahershala Ali',
            'Matthew McConaughey'),
 'Added' => '2016-09-14',
 'Countries' => array('USA'),
 'Description' => '\nFree State of Jones: As civil war divides the nation, a poor farmer from Mississippi leads a group of rebels against the Confederate army. ',
 'Director' => array('Gary Ross'),
 'Genres' => array('Action', 'Biography', 'Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt1124037',
 'PrimeWire' => 'http://www.primewire.ag/watch-2781150-Free-State-of-Jones',
 'Ratings' => array('IMDB' => '6.9/10',
             'Metascore' => '53%',
             'PrimeWire' => '4.05/5',
             'RT' => 'N/A',
             'Votes' => '363'),
 'Released' => '2016-06-24',
 'Runtime' => '139 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1729461_Free_State_of_Jones_2016.jpg',
 'Title' => 'Free-State-of-Jones');
?>