{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-15',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Metropia',
 'EntryURL': 'https://www.imdb.com/title/tt0985058',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Metropia/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Metropia/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Metropia/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Vincent Gallo',
            'url': '/name/nm0001252/'},
           {'@type': 'Person',
            'name': 'Juliette Lewis',
            'url': '/name/nm0000496/'},
           {'@type': 'Person', 'name': 'Udo Kier', 'url': '/name/nm0001424/'},
           {'@type': 'Person',
            'name': 'Stellan Skarsgård',
            'url': '/name/nm0001745/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 7315,
                     'ratingValue': '6.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Truls Andersen',
              'url': '/name/nm4885209/'},
             {'@type': 'Person',
              'name': 'Fredrik Edin',
              'url': '/name/nm1926161/'},
             {'@type': 'Person',
              'name': 'Fredrik Edin',
              'url': '/name/nm1926161/'},
             {'@type': 'Person',
              'name': 'Martin Hultman',
              'url': '/name/nm3011351/'},
             {'@type': 'Person',
              'name': 'Stig Larsson',
              'url': '/name/nm0489284/'},
             {'@type': 'Person',
              'name': 'Tarik Saleh',
              'url': '/name/nm0757975/'},
             {'@type': 'Person',
              'name': 'Tarik Saleh',
              'url': '/name/nm0757975/'},
             {'@type': 'Organization', 'url': '/company/co0037084/'},
             {'@type': 'Organization', 'url': '/company/co0202454/'},
             {'@type': 'Organization', 'url': '/company/co0001935/'},
             {'@type': 'Organization', 'url': '/company/co0006862/'},
             {'@type': 'Organization', 'url': '/company/co0079546/'},
             {'@type': 'Organization', 'url': '/company/co0113048/'},
             {'@type': 'Organization', 'url': '/company/co0108142/'},
             {'@type': 'Organization', 'url': '/company/co0136662/'},
             {'@type': 'Organization', 'url': '/company/co0011451/'}],
 'datePublished': '2009-11-27',
 'description': 'Metropia is a movie starring Vincent Gallo, Juliette Lewis, '
                'and Udo Kier. A complex story of a misaligned man, though '
                'good intent, creating a nightmarish Dystopian existence.',
 'director': {'@type': 'Person',
              'name': 'Tarik Saleh',
              'url': '/name/nm0757975/'},
 'duration': 'PT1H26M',
 'genre': ['Animation', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTEzZjNlZTktYmMwZC00ZmNkLWEzOTMtMDQyYTRjMTNkNzRiXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'cell phone ringtone,conspiracy,surveillance,metro,mind control',
 'name': 'Metropia',
 'trailer': {'@type': 'VideoObject',
             'description': 'Visually stunning trailer for this thriller',
             'embedUrl': '/video/imdb/vi3641640729',
             'name': 'Metropia',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMzAxNTUxZGUtMDlmYi00MDMwLTkyNDMtYWJkYjU2N2MzZjc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMzAxNTUxZGUtMDlmYi00MDMwLTkyNDMtYWJkYjU2N2MzZjc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2010-05-18T15:34:56Z'},
 'url': '/title/tt0985058/'}