{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-12',
 'EntryPath': 'Favorites/Movies/snapshot/ABE',
 'EntryURL': 'https://www.imdb.com/title/tt2883236',
 'Entry_json': 'Favorites/Movies/snapshot/ABE/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/ABE/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/ABE/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Sam Hoare', 'url': '/name/nm2397390/'},
           {'@type': 'Person',
            'name': 'Claire Huskisson',
            'url': '/name/nm5429678/'},
           {'@type': 'Person',
            'name': 'Emily Baxter',
            'url': '/name/nm4861860/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1366,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Rob McLellan',
              'url': '/name/nm4818916/'},
             {'@type': 'Person',
              'name': 'Rob McLellan',
              'url': '/name/nm4818916/'},
             {'@type': 'Person',
              'name': 'Sven Hornsey',
              'url': '/name/nm4819065/'},
             {'@type': 'Organization', 'url': '/company/co0081743/'}],
 'datePublished': '2013-04-30',
 'description': 'Abe is a short starring Sam Hoare, Claire Huskisson, and '
                'Emily Baxter. ABE is a tense, psychological horror about a '
                "robot who's looking for love in all the wrong places.",
 'director': {'@type': 'Person',
              'name': 'Rob McLellan',
              'url': '/name/nm4818916/'},
 'duration': 'PT9M',
 'genre': ['Short', 'Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ5MTI5OTAyOV5BMl5BanBnXkFtZTcwNTU3Mjg0OQ@@._V1_.jpg',
 'keywords': 'robot,futuristic,robot as menace,tied to a bed,scalpel',
 'name': 'Abe',
 'url': '/title/tt2883236/'}