{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-12',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/ABE',
 'EntryURL': 'https://www.imdb.com/title/tt2883236',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/ABE/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/ABE/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/ABE/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/ABE/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Sam Hoare', 'url': '/name/nm2397390/'},
           {'@type': 'Person',
            'name': 'Claire Huskisson',
            'url': '/name/nm5429678/'},
           {'@type': 'Person',
            'name': 'Emily Baxter',
            'url': '/name/nm4861860/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1366,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Rob McLellan',
              'url': '/name/nm4818916/'},
             {'@type': 'Person',
              'name': 'Rob McLellan',
              'url': '/name/nm4818916/'},
             {'@type': 'Person',
              'name': 'Sven Hornsey',
              'url': '/name/nm4819065/'},
             {'@type': 'Organization', 'url': '/company/co0081743/'}],
 'datePublished': '2013-04-30',
 'description': 'Abe is a short starring Sam Hoare, Claire Huskisson, and '
                'Emily Baxter. ABE is a tense, psychological horror about a '
                "robot who's looking for love in all the wrong places.",
 'director': {'@type': 'Person',
              'name': 'Rob McLellan',
              'url': '/name/nm4818916/'},
 'duration': 'PT9M',
 'genre': ['Short', 'Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ5MTI5OTAyOV5BMl5BanBnXkFtZTcwNTU3Mjg0OQ@@._V1_.jpg',
 'keywords': 'robot,futuristic,robot as menace,tied to a bed,scalpel',
 'name': 'Abe',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'Hitchcoc'},
            'dateCreated': '2019-04-05',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt2883236/'},
            'name': 'It Goes Where It Goes',
            'reviewBody': "It's all set out there. A robot who loves but gets "
                          'none in return, turns to trying to "fix" those that '
                          "don't love him. Unfortunately, he is a machine and "
                          'has no expertise in handling human bodies. He is '
                          'soft spoken. He covers the mouth of the young woman '
                          'so she is not able to respond in any way. It is a '
                          'brutal little film.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '6',
                             'worstRating': '1'}},
 'url': '/title/tt2883236/'}