<?php
$infoArray = array('Actors' => array('Alan Pottinger',
            'Alexandra Powers',
            'Allelon Ruggiero',
            'Andrew Hill',
            'Debra Mooney',
            'Dylan Kussman',
            'Ethan Hawke',
            'George Martin',
            'James Waterston',
            'Jamie Kennedy',
            'Jane Moore',
            'John Cunningham',
            'Josh Charles',
            'Keith Snyder',
            'Kevin Cooney',
            'Kurtwood Smith',
            'Lara Flynn Boyle',
            'Leon Pownall',
            'Melora Walters',
            'Norman Lloyd',
            'Robert Sean Leonard',
            'Robin Williams',
            'Welker White'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nDead Poets Society: English professor John Keating inspires his students to a love of poetry and to seize the day. ',
 'Director' => array('Peter Weir'),
 'Genres' => array('Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt0097165',
 'PrimeWire' => 'http://www.primewire.ag/watch-3678-Dead-Poets-Society',
 'Ratings' => array('IMDB' => '8.0/10',
             'Metascore' => '79%',
             'PrimeWire' => '3.95/5',
             'RT' => '85%',
             'Votes' => '415'),
 'Released' => '1989-06-02',
 'Runtime' => '128 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/3678_Dead_Poets_Society_1989.jpg',
 'Title' => 'Dead-Poets-Society');
?>