{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Dead-Poets-Society',
 'EntryURL': 'https://www.imdb.com/title/tt0097165',
 'Entry_json': 'Favorites/Movies/snapshot/Dead-Poets-Society/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Dead-Poets-Society/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Dead-Poets-Society/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Robin Williams',
            'url': '/name/nm0000245/'},
           {'@type': 'Person',
            'name': 'Robert Sean Leonard',
            'url': '/name/nm0000494/'},
           {'@type': 'Person',
            'name': 'Ethan Hawke',
            'url': '/name/nm0000160/'},
           {'@type': 'Person',
            'name': 'Josh Charles',
            'url': '/name/nm0001038/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 404158,
                      'ratingValue': '8.1',
                      'worstRating': '1.0'}],
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Tom Schulman',
              'url': '/name/nm0776114/'},
             {'@type': 'Organization', 'url': '/company/co0049348/'},
             {'@type': 'Organization', 'url': '/company/co0133018/'},
             {'@type': 'Organization', 'url': '/company/co0587257/'},
             {'@type': 'Organization', 'url': '/company/co0067672/'}],
 'datePublished': '1989-06-09',
 'description': 'Dead Poets Society is a movie starring Robin Williams, Robert '
                'Sean Leonard, and Ethan Hawke. English teacher John Keating '
                'inspires his students to look at poetry with a different '
                'perspective of authentic knowledge and feelings....',
 'director': [{'@type': 'Person',
               'name': 'Peter Weir',
               'url': '/name/nm0001837/'}],
 'duration': 'PT2H8M',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOGYwYWNjMzgtNGU4ZC00NWQ2LWEwZjUtMzE1Zjc3NjY3YTU1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'english teacher,professor,education,suicide,poet',
 'name': 'Dead Poets Society',
 'url': '/title/tt0097165/'}