{'Actors': ['Darrell Hammond&tv', 'Don Pardo&tv'],
 'Added': '2011-10-23',
 'Countries': ['USA'],
 'Description': '\n'
                'Saturday Night Live: The classic late night live sketch '
                'comedy show. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Saturday-Night-Live',
 'EntryURL': 'http://www.imdb.com/title/tt0072562',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Saturday-Night-Live/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Saturday-Night-Live/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Saturday-Night-Live/info.py',
 'Genres': ['Comedy&tv', 'Music&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0072562',
 'PrimeWire': 'http://www.primewire.ag/tv-5204-Saturday-Night-Live',
 'Ratings': {'IMDB': '8.2/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.37/5',
             'RT': 'N/A',
             'Votes': '802'},
 'Released': '1975-10-11',
 'Runtime': '90 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5204_Saturday_Night_Live_1975.jpg',
 'Title': 'Saturday-Night-Live'}