{'Actors': ['Atom Egoyan',
            'Dan Rather',
            'Eric Johnston',
            'Jack Valenti',
            'John Waters',
            'Kevin Smith',
            'Kirsten Johnson',
            'Maria Bello',
            'Matt Stone',
            'Michael Tucker',
            'Rachel Blanchard',
            'Richard Nixon',
            'Tom Brokaw',
            'Walter Cronkite',
            'Wayne Kramer',
            'Will H Hays'],
 'Added': '2013-06-30',
 'Countries': ['UK', 'USA'],
 'Description': '\n'
                "This Film Is Not Yet Rated: Kirby Dick's exposé about the "
                'American movie ratings board. ',
 'Director': ['Kirby Dick'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//This-Film-Is-Not-Yet-Rated',
 'EntryURL': 'http://www.imdb.com/title/tt0493459',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//This-Film-Is-Not-Yet-Rated/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//This-Film-Is-Not-Yet-Rated/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//This-Film-Is-Not-Yet-Rated/info.py',
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt0493459',
 'PrimeWire': 'http://www.primewire.ag/watch-4776-This-Film-Is-Not-Yet-Rated',
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': '75%',
             'PrimeWire': '3.57/5',
             'RT': '84%',
             'Votes': '157'},
 'Released': '2006-01-25',
 'Runtime': '97 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/4776_This_Film_Is_Not_Yet_Rated_2006.jpg',
 'Title': 'This-Film-Is-Not-Yet-Rated'}