{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-30',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Film-Is-Not-Yet-Rated',
 'EntryURL': 'https://www.imdb.com/title/tt0493459',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Film-Is-Not-Yet-Rated/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Film-Is-Not-Yet-Rated/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Film-Is-Not-Yet-Rated/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Kirby Dick', 'url': '/name/nm0225269/'},
           {'@type': 'Person',
            'name': 'Kimberly Peirce',
            'url': '/name/nm0005303/'},
           {'@type': 'Person',
            'name': 'Darren Aronofsky',
            'url': '/name/nm0004716/'},
           {'@type': 'Person',
            'name': 'Atom Egoyan',
            'url': '/name/nm0000382/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 27131,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'Unrated',
 'creator': [{'@type': 'Person',
              'name': 'Kirby Dick',
              'url': '/name/nm0225269/'},
             {'@type': 'Person',
              'name': 'Eddie Schmidt',
              'url': '/name/nm0772907/'},
             {'@type': 'Person',
              'name': 'Matt Patterson',
              'url': '/name/nm1121472/'},
             {'@type': 'Organization', 'url': '/company/co0046530/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'},
             {'@type': 'Organization', 'url': '/company/co0163927/'},
             {'@type': 'Organization', 'url': '/company/co0187965/'}],
 'datePublished': '2006-09-01',
 'description': 'This Film Is Not Yet Rated is a movie starring Kirby Dick, '
                "Kimberly Peirce, and Darren Aronofsky. Kirby Dick's exposé "
                'about the American movie ratings board.',
 'director': {'@type': 'Person',
              'name': 'Kirby Dick',
              'url': '/name/nm0225269/'},
 'duration': 'PT1H38M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk0NDIwMDUxNl5BMl5BanBnXkFtZTcwMzY3MzIzMQ@@._V1_.jpg',
 'keywords': 'sexuality,orgasm,homosexuality,mpaa,filmmaker',
 'name': 'This Film Is Not Yet Rated',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from IFC',
             'embedUrl': '/video/imdb/vi3958767897',
             'name': 'This Film Is Not Yet Rated',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzgxYTliZmMtZjk1Zi00NGRkLWExMTgtMGUzMjExNDVmYjdlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzgxYTliZmMtZjk1Zi00NGRkLWExMTgtMGUzMjExNDVmYjdlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:57:37Z'},
 'url': '/title/tt0493459/'}