{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-27',
 'EntryPath': 'Favorites/Movies/snapshot/Schooled-The-Price-of-College-Sports',
 'EntryURL': 'https://www.imdb.com/title/tt3057718',
 'Entry_json': 'Favorites/Movies/snapshot/Schooled-The-Price-of-College-Sports/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Schooled-The-Price-of-College-Sports/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Schooled-The-Price-of-College-Sports/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kevin Anderson',
            'url': '/name/nm5897036/'},
           {'@type': 'Person', 'name': 'Jay Bilas', 'url': '/name/nm0082112/'},
           {'@type': 'Person',
            'name': 'Taylor Branch',
            'url': '/name/nm0104373/'},
           {'@type': 'Person',
            'name': 'Bob Costas',
            'url': '/name/nm0182471/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 578,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Organization', 'url': '/company/co0328799/'}],
 'datePublished': '2013-10-16',
 'description': 'Schooled: The Price of College Sports is a movie starring '
                'Kevin Anderson, Jay Bilas, and Taylor Branch. A documentary '
                'that examines how college sports in America became a billion '
                'dollar enterprise built on the backs of its unpaid...',
 'director': [{'@type': 'Person',
               'name': 'Ross Finkel',
               'url': '/name/nm4265029/'},
              {'@type': 'Person',
               'name': 'Trevor Martin',
               'url': '/name/nm4264958/'},
              {'@type': 'Person',
               'name': 'Jon Paley',
               'url': '/name/nm3151327/'}],
 'duration': 'PT1H25M',
 'genre': ['Documentary', 'History', 'Sport'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ2NjI0NDU3Nl5BMl5BanBnXkFtZTgwMDU4OTgzMDE@._V1_.jpg',
 'keywords': 'athlete,college sports,narration,six word title,colon in title',
 'name': 'Schooled: The Price of College Sports',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A documentary that examines how college sports '
                             'in America became a billion dollar enterprise '
                             'built on the backs of its unpaid athletes.',
              'embedUrl': '/video/imdb/vi1185785881',
              'name': 'Theatrical Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTUzNDIwNjM3N15BMl5BanBnXkFtZTgwOTcwNDcyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTUzNDIwNjM3N15BMl5BanBnXkFtZTgwOTcwNDcyMzE@._V1_.jpg',
              'uploadDate': '2013-10-03T15:56:44Z'}],
 'url': '/title/tt3057718/'}