{'Actors': ['50 Cent',
            'Eminem',
            'Matthew Cooke',
            'Susan Sarandon',
            'Woody Harrelson'],
 'Added': '2013-06-30',
 'Countries': ['USA'],
 'Description': '\nHow to Make Money Selling Drugs: Ten easy steps show you how to make money from drugs, featuring a series of interviews with drug dealers, prison employees, and lobbyists arguing for tougher drug laws. ',
 'Director': ['Matthew Cooke'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1276962',
 'PrimeWire': 'http://www.primewire.ag/watch-2021699-How-to-Make-Money-Selling-Drugs',
 'Ratings': {'IMDB': '7.8/10',
             'Metascore': '68%',
             'PrimeWire': '4.32/5',
             'RT': '77%',
             'Votes': '301'},
 'Released': '2013-04-25',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2021699_How_to_Make_Money_Selling_Drugs_0.jpg',
 'Title': 'How-to-Make-Money-Selling-Drugs'}