{'Actors': ['Seth MacFarlane'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\nCavalcade of Cartoon Comedy: From the creator of Family Guy and the co-creator of American Dad! Comes a brand-new animated series of pop culture parodies, skewered stories, and fabulously filthy fun nuggets. Uncensored, uninhibited and unbelievably hilarious, Seth MacFarlane\x92s Cavalcade of Cartoon Comedy is brimming with the kind of raunchy, twisted humor you can\x92t see on television no matter how hard you try. So sit back, veg out and enjoy the show. The possibilities are endless...and so are the laughs! ',
 'Director': [],
 'Genres': ['Animation', 'Comedy', 'Short'],
 'IMDB': 'http://www.imdb.com/title/tt1295036',
 'PrimeWire': 'http://www.primewire.ag/watch-5396-Cavalcade-of-Cartoon-Comedy',
 'Ratings': {'IMDB': '6.5/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.44/5',
             'RT': 'N/A',
             'Votes': '142'},
 'Released': '2008-09-09',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5396_Cavalcade_of_Cartoon_Comedy_2008.jpg',
 'Title': 'Cavalcade-of-Cartoon-Comedy'}