{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Apollo-13',
 'EntryURL': 'https://www.imdb.com/title/tt0112384',
 'Entry_json': 'Favorites/Movies/snapshot/Apollo-13/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Apollo-13/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Apollo-13/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Hanks', 'url': '/name/nm0000158/'},
           {'@type': 'Person',
            'name': 'Bill Paxton',
            'url': '/name/nm0000200/'},
           {'@type': 'Person',
            'name': 'Kevin Bacon',
            'url': '/name/nm0000102/'},
           {'@type': 'Person',
            'name': 'Gary Sinise',
            'url': '/name/nm0000641/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 259122,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Jim Lovell',
              'url': '/name/nm0522554/'},
             {'@type': 'Person',
              'name': 'Jeffrey Kluger',
              'url': '/name/nm0460200/'},
             {'@type': 'Person',
              'name': 'William Broyles Jr.',
              'url': '/name/nm0115310/'},
             {'@type': 'Person',
              'name': 'Al Reinert',
              'url': '/name/nm0718031/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0003687/'}],
 'datePublished': '1995-06-30',
 'description': 'Apollo 13 is a movie starring Tom Hanks, Bill Paxton, and '
                'Kevin Bacon. NASA must devise a strategy to return Apollo 13 '
                'to Earth safely after the spacecraft undergoes massive '
                'internal damage putting the lives of the three astronauts...',
 'director': [{'@type': 'Person',
               'name': 'Ron Howard',
               'url': '/name/nm0000165/'}],
 'duration': 'PT2H20M',
 'genre': ['Adventure', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjEzYjJmNzgtNDkwNy00MTQ4LTlmMWMtNzA4YjE2NjI0ZDg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': '1970s,survival,astronaut,space mission,rescue',
 'name': 'Apollo 13',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Universal Studios Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi1605828889',
              'name': 'Apollo 13',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzZmZGY3YTMtZThkMS00NDQzLWJkYTUtYTRlOWUwYjlhM2U3XkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzZmZGY3YTMtZThkMS00NDQzLWJkYTUtYTRlOWUwYjlhM2U3XkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
              'uploadDate': '2008-04-11T11:46:39Z'}],
 'url': '/title/tt0112384/'}