{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-21',
 'EntryPath': 'Favorites/TV/snapshot/Surviving-the-Cut',
 'EntryURL': 'https://www.imdb.com/title/tt1711419',
 'Entry_json': 'Favorites/TV/snapshot/Surviving-the-Cut/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Surviving-the-Cut/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Surviving-the-Cut/thumb.jpg',
 'actor': {'@type': 'Person',
           'name': 'William Sadler',
           'url': '/name/nm0006669/'},
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 517,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0252276/'},
 'datePublished': '2010-08-18',
 'description': 'Surviving the Cut is a TV series starring William Sadler. '
                'With extraordinary, unprecedented access, Surviving the Cut '
                'takes viewers into the intense world of military elite forces '
                'training. From divers and snipers to para-rescue men...',
 'genre': 'Reality-TV',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ1NTAxMjcxN15BMl5BanBnXkFtZTgwMTAyODcwMzE@._V1_.jpg',
 'keywords': 'special forces,marines,airforce,navy,army',
 'name': 'Surviving the Cut',
 'url': '/title/tt1711419/'}