{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-11',
 'EntryURL': 'https://rawg.io/games/final-fantasy-11',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-11/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-11/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-11/thumb.jpg',
 'added': 74,
 'background_image': 'https://media.rawg.io/media/screenshots/2e5/2e51acd434791f54f845fe344d8b9cb1.jpg',
 'developers': ['Square Product Development Division 3'],
 'genres': ['RPG', 'Massively Multiplayer'],
 'name': 'Final Fantasy XI',
 'platforms': ['PC', 'PlayStation 2'],
 'publishers': ['Square'],
 'released': '2002-11-07',
 'slug': 'final-fantasy-11'}