{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman',
 'EntryURL': 'https://www.imdb.com/title/tt0119925',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kevin Costner',
            'url': '/name/nm0000126/'},
           {'@type': 'Person',
            'name': 'Will Patton',
            'url': '/name/nm0001599/'},
           {'@type': 'Person',
            'name': 'Larenz Tate',
            'url': '/name/nm0005478/'},
           {'@type': 'Person',
            'name': 'Olivia Williams',
            'url': '/name/nm0931404/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 67106,
                     'ratingValue': '6.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'David Brin',
              'url': '/name/nm0109432/'},
             {'@type': 'Person',
              'name': 'Eric Roth',
              'url': '/name/nm0744839/'},
             {'@type': 'Person',
              'name': 'Brian Helgeland',
              'url': '/name/nm0001338/'},
             {'@type': 'Organization', 'url': '/company/co0012524/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'}],
 'datePublished': '1997-12-25',
 'description': 'The Postman is a movie starring Kevin Costner, Will Patton, '
                "and Larenz Tate. A nameless drifter dons a postman's uniform "
                'and bag of mail as he begins a quest to inspire hope to the '
                'survivors living in post-apocalyptic America.',
 'director': {'@type': 'Person',
              'name': 'Kevin Costner',
              'url': '/name/nm0000126/'},
 'duration': 'PT2H57M',
 'genre': ['Action', 'Adventure', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTAyYTFmYmUtNTFhZS00NGQxLWI0OGEtZDM2NDk1OGE4YzFmL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'year 2043,year 2013,woman,worst picture razzie winner,character '
             'name as title',
 'name': 'The Postman',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Miramax',
             'embedUrl': '/video/imdb/vi1861746969',
             'name': 'The Postman',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYmJkNzUyYWMtMThjNy00NjZkLWIyOWEtYzg5YTk3MzYzODA2XkEyXkFqcGdeQWFybm8@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYmJkNzUyYWMtMThjNy00NjZkLWIyOWEtYzg5YTk3MzYzODA2XkEyXkFqcGdeQWFybm8@._V1_.jpg',
             'uploadDate': '2008-04-11T17:03:30Z'},
 'url': '/title/tt0119925/'}