{'Actors': ['Anthony Guidera',
            'Betty Moyer',
            'Brandon Tyler',
            'Brian Anthony Wilson',
            'Brooke Becker',
            'Charles Esten',
            'Daniel von Bargen',
            'Derk Cheetwood',
            'Dolph Lundgren',
            'Dylan Haggerty',
            'Ellen Geer',
            'George Wyner',
            'Giovanni Ribisi',
            'Greg Serano',
            'Gregory Avellone',
            'James Russo',
            'Jeff Johnson',
            'Jeff McGrail',
            'Joe Santos',
            'Joseph McKenna',
            'Judy Herrera',
            'Julie Andrews',
            'Kevin Costner',
            'Kirk Fox',
            'Larenz Tate',
            'Mark Thomason',
            'Mary Stuart Masterson',
            'Olivia Williams',
            'Peggy Lipton',
            'Randle Mell',
            'Rex Linn',
            'Roberta Maxwell',
            'Ron McLarty',
            'Rusty Hendrickson',
            'Ryan Hurst',
            'Scott Bairstow',
            'Shawn Hatosy',
            'Stanton Barrett',
            'Todd Allen',
            'Todd Lewis',
            'Tom Bower',
            'Tom Petty',
            "Ty O'Neal",
            'Will Patton'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                'The Postman: Post-apocalyptic America. What begins as a con '
                "game becomes one man's quest to rebuild civilization by "
                'resuming postal service. ',
 'Director': ['Kevin Costner'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman',
 'EntryURL': 'https://www.imdb.com/title/tt0119925',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Postman/info.py',
 'Genres': ['Action', 'Drama', 'Sci-Fi', 'Adventure'],
 'Ratings': {'IMDB': '5.9/10',
             'Metascore': '29%',
             'PrimeWire': '4.20/5',
             'RT': '9%',
             'Votes': '322'},
 'Released': '1997-12-12',
 'Runtime': '177 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/7569_The_Postman_1997.jpg',
 'Title': 'The-Postman'}