{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Not-Another-Teen-Movie',
 'EntryURL': 'https://www.imdb.com/title/tt0277371',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Not-Another-Teen-Movie/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Not-Another-Teen-Movie/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Not-Another-Teen-Movie/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Chyler Leigh',
            'url': '/name/nm0500200/'},
           {'@type': 'Person',
            'name': 'Jaime Pressly',
            'url': '/name/nm0005326/'},
           {'@type': 'Person',
            'name': 'Chris Evans',
            'url': '/name/nm0262635/'},
           {'@type': 'Person',
            'name': 'Eric Christian Olsen',
            'url': '/name/nm0647638/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 94396,
                     'ratingValue': '5.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mike Bender',
              'url': '/name/nm0070500/'},
             {'@type': 'Person',
              'name': 'Adam Jay Epstein',
              'url': '/name/nm0258418/'},
             {'@type': 'Person',
              'name': 'Andrew Jacobson',
              'url': '/name/nm0414795/'},
             {'@type': 'Person',
              'name': 'Phil Beauman',
              'url': '/name/nm0064556/'},
             {'@type': 'Person',
              'name': 'Buddy Johnson',
              'url': '/name/nm0424688/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0011134/'},
             {'@type': 'Organization', 'url': '/company/co0003654/'}],
 'datePublished': '2001-12-14',
 'description': 'Not Another Teen Movie is a movie starring Chyler Leigh, '
                'Jaime Pressly, and Chris Evans. A sendup of all the teen '
                'movies that have accumulated in the past two decades.',
 'director': {'@type': 'Person',
              'name': 'Joel Gallen',
              'url': '/name/nm0302778/'},
 'duration': 'PT1H29M',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BNTRhNWJmNTUtM2VhYi00NzdkLTgyYTUtMWMzMWI3MzFmNzk5XkEyXkFqcGdeQXVyNjgzMjI4ODE@._V1_.jpg',
 'keywords': 'vibrator,cheerleader,teen sex comedy,female '
             'masturbation,exchange student',
 'name': 'Not Another Teen Movie',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Columbia Pictures',
             'embedUrl': '/video/imdb/vi547225881',
             'name': 'Not Another Teen Movie',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjM0YWVmODctYzAwZi00ZjMyLWJmMjYtZmMzM2RmODg4Y2QxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjM0YWVmODctYzAwZi00ZjMyLWJmMjYtZmMzM2RmODg4Y2QxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T15:30:04Z'},
 'url': '/title/tt0277371/'}