{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-West-Wing',
 'EntryURL': 'https://www.imdb.com/title/tt0200276',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-West-Wing/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-West-Wing/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-West-Wing/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Martin Sheen',
            'url': '/name/nm0000640/'},
           {'@type': 'Person', 'name': 'Rob Lowe', 'url': '/name/nm0000507/'},
           {'@type': 'Person',
            'name': 'Allison Janney',
            'url': '/name/nm0005049/'},
           {'@type': 'Person',
            'name': 'John Spencer',
            'url': '/name/nm0817983/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 59630,
                     'ratingValue': '8.8',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Aaron Sorkin',
              'url': '/name/nm0815070/'},
             {'@type': 'Organization', 'url': '/company/co0037310/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'}],
 'datePublished': '1999-09-22',
 'description': 'The West Wing is a TV series starring Martin Sheen, Rob Lowe, '
                'and Allison Janney. Inside the lives of staffers in the West '
                'Wing of the White House.',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BNjk3ZWE3ZDctN2Q1YS00NzNhLWFjNmYtZTkwYWQxZmQ3NzM3XkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_.jpg',
 'keywords': 'dialogue driven,president,politics,american politics,ensemble '
             'cast',
 'name': 'The West Wing',
 'trailer': {'@type': 'VideoObject',
             'embedUrl': '/video/imdb/vi3802840601',
             'name': 'Trailer Season 1',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTdhYWZkNDUtMDU2Zi00NmNmLWE4M2QtNDgwYzZmMThlOGNhXkEyXkFqcGdeQXN3aWZ0dw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTdhYWZkNDUtMDU2Zi00NmNmLWE4M2QtNDgwYzZmMThlOGNhXkEyXkFqcGdeQXN3aWZ0dw@@._V1_.jpg',
             'uploadDate': '2020-03-11T14:28:44Z'},
 'url': '/title/tt0200276/'}