{'Actors': ['Brian J White',
            'Cody Lightning',
            'Emilie de Ravin',
            'Joseph Gordon-Levitt',
            'Lucas Babin',
            'Lukas Haas',
            "Matt O'Leary",
            'Meagan Good',
            'Noah Fleiss',
            'Noah Segan',
            'Nora Zehetner',
            'Reedy Gibbs',
            'Richard Roundtree'],
 'Added': '2013-03-30',
 'Countries': ['USA'],
 'Description': '\n'
                'Brick: A teenage loner pushes his way into the underworld of '
                'a high school crime ring to investigate the disappearance of '
                'his ex-girlfriend. ',
 'Director': ['Rian Johnson'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Brick',
 'EntryURL': 'http://www.imdb.com/title/tt0393109',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Brick/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Brick/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Brick/info.py',
 'Genres': ['Drama', 'Crime', 'Mystery'],
 'IMDB': 'http://www.imdb.com/title/tt0393109',
 'PrimeWire': 'http://www.primewire.ag/watch-3365-Brick',
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': '72%',
             'PrimeWire': '3.83/5',
             'RT': '80%',
             'Votes': '228'},
 'Released': '2005-09-06',
 'Runtime': '110 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/3365_Brick_2005.jpg',
 'Title': 'Brick'}