{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-03-30',
 'EntryPath': 'Favorites/Movies/snapshot/Brick',
 'EntryURL': 'https://www.imdb.com/title/tt0393109',
 'Entry_json': 'Favorites/Movies/snapshot/Brick/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Brick/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Brick/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Joseph Gordon-Levitt',
            'url': '/name/nm0330687/'},
           {'@type': 'Person', 'name': 'Lukas Haas', 'url': '/name/nm0001305/'},
           {'@type': 'Person',
            'name': 'Emilie de Ravin',
            'url': '/name/nm0211087/'},
           {'@type': 'Person',
            'name': 'Meagan Good',
            'url': '/name/nm0328709/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 99102,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Rian Johnson',
              'url': '/name/nm0426059/'},
             {'@type': 'Organization', 'url': '/company/co0077650/'}],
 'datePublished': '2006-04-07',
 'description': 'Brick is a movie starring Joseph Gordon-Levitt, Lukas Haas, '
                'and Emilie de Ravin. A teenage loner pushes his way into the '
                'underworld of a high school crime ring to investigate the '
                'disappearance of his ex-girlfriend.',
 'director': {'@type': 'Person',
              'name': 'Rian Johnson',
              'url': '/name/nm0426059/'},
 'duration': 'PT1H50M',
 'genre': ['Action', 'Crime', 'Drama', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk4MjQzMzA2N15BMl5BanBnXkFtZTcwMTU2MzIzMQ@@._V1_.jpg',
 'keywords': 'neo noir,alley,cinderblock,neo noirish,hard boiled',
 'name': 'Brick',
 'url': '/title/tt0393109/'}