{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-03-17',
 'EntryPath': 'Favorites/TV/snapshot/Coal',
 'EntryURL': 'https://www.imdb.com/title/tt1745045',
 'Entry_json': 'Favorites/TV/snapshot/Coal/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Coal/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Coal/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Andrew Christian',
            'url': '/name/nm4329982/'},
           {'@type': 'Person',
            'name': 'Andy Christian',
            'url': '/name/nm4329879/'},
           {'@type': 'Person',
            'name': 'Mike Crowder',
            'url': '/name/nm4127147/'},
           {'@type': 'Person',
            'name': 'R.B. Davis',
            'url': '/name/nm4330459/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 90,
                      'ratingValue': '8.3',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0013072/'}],
 'datePublished': '2011-03-30',
 'description': 'Coal is a TV series starring Andrew Christian, Andy '
                'Christian, and Mike Crowder. A docuseries chronicling the '
                'dangerous profession of coal mining, set in West Virginia.',
 'genre': ['Documentary', 'Reality-TV'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjAyNzk0NDkxNV5BMl5BanBnXkFtZTgwMDA4NzcwMzE@._V1_.jpg',
 'keywords': 'coal,coal mining,west virginia',
 'name': 'Coal',
 'url': '/title/tt1745045/'}