{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-09-14',
 'EntryPath': 'Favorites/Movies/snapshot/Money-for-Nothing-Inside-the-Federal-Reserve',
 'EntryURL': 'https://www.imdb.com/title/tt2752724',
 'Entry_json': 'Favorites/Movies/snapshot/Money-for-Nothing-Inside-the-Federal-Reserve/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Money-for-Nothing-Inside-the-Federal-Reserve/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Money-for-Nothing-Inside-the-Federal-Reserve/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Liev Schreiber',
            'url': '/name/nm0000630/'},
           {'@type': 'Person',
            'name': 'Paul Volcker',
            'url': '/name/nm1352862/'},
           {'@type': 'Person',
            'name': 'Janet Yellen',
            'url': '/name/nm5908572/'},
           {'@type': 'Person',
            'name': 'Peter Atwater',
            'url': '/name/nm5908554/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 866,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Jim Bruce',
              'url': '/name/nm1088762/'}],
 'datePublished': '2013-09-06',
 'description': 'Money for Nothing: Inside the Federal Reserve is a movie '
                'starring Liev Schreiber, Paul Volcker, and Janet Yellen. '
                'Nearly 100 years after its creation, the power of the U.S. '
                'Federal Reserve has never been greater. Markets and...',
 'director': [{'@type': 'Person',
               'name': 'Jim Bruce',
               'url': '/name/nm1088762/'}],
 'duration': 'PT1H44M',
 'genre': ['Documentary', 'History', 'News'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjEzODY5MzQ4OF5BMl5BanBnXkFtZTgwNTcxMDMwMDE@._V1_.jpg',
 'keywords': 'economic history,economic power,loan,investment,currency',
 'name': 'Money for Nothing: Inside the Federal Reserve',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Money for Nothing: Inside the '
                             'Federal Reserve',
              'embedUrl': '/video/imdb/vi1354349337',
              'name': 'Money for Nothing: Inside the Federal Reserve',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYzFjN2ZhYmEtZDg5NS00MTE2LWEzMmEtODE0MTU1MTZmMWE2XkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYzFjN2ZhYmEtZDg5NS00MTE2LWEzMmEtODE0MTU1MTZmMWE2XkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg',
              'uploadDate': '2018-05-16T17:13:27Z'}],
 'url': '/title/tt2752724/'}