{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-03-08',
 'EntryPath': 'Favorites/Movies/snapshot/Tusk',
 'EntryURL': 'https://www.imdb.com/title/tt3099498',
 'Entry_json': 'Favorites/Movies/snapshot/Tusk/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Tusk/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Tusk/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Justin Long',
            'url': '/name/nm0519043/'},
           {'@type': 'Person',
            'name': 'Michael Parks',
            'url': '/name/nm0662981/'},
           {'@type': 'Person',
            'name': 'Haley Joel Osment',
            'url': '/name/nm0005286/'},
           {'@type': 'Person',
            'name': 'Genesis Rodriguez',
            'url': '/name/nm1270009/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 44447,
                     'ratingValue': '5.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Kevin Smith',
              'url': '/name/nm0003620/'},
             {'@type': 'Organization', 'url': '/company/co0326257/'}],
 'datePublished': '2014-09-19',
 'description': 'Tusk is a movie starring Justin Long, Michael Parks, and '
                'Haley Joel Osment. A brash and arrogant podcaster gets more '
                'than he bargained for when he travels to Canada to interview '
                'a mysterious recluse... who has a rather disturbing...',
 'director': {'@type': 'Person',
              'name': 'Kevin Smith',
              'url': '/name/nm0003620/'},
 'duration': 'PT1H42M',
 'genre': ['Comedy', 'Drama', 'Horror'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNmQyMmUzMmYtMTA4OS00ZmRjLWE0NWYtNjc0ZGM0N2E4YzQ5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'walrus,canada,search,deception,mansion',
 'name': 'Tusk',
 'trailer': {'@type': 'VideoObject',
             'description': 'When his best friend and podcast co-host goes '
                            'missing in the backwoods of Canada, a young guy '
                            "joins forces with his friend's girlfriend to "
                            'search for him.',
             'embedUrl': '/video/imdb/vi154446873',
             'name': 'Trailer #1',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTk0NTE1OTAwOV5BMl5BanBnXkFtZTgwMTE1NzAyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTk0NTE1OTAwOV5BMl5BanBnXkFtZTgwMTE1NzAyMzE@._V1_.jpg',
             'uploadDate': '2014-07-27T09:00:11Z'},
 'url': '/title/tt3099498/'}