{'Actors': ['Hugh Laurie&tv',
            'Jennifer Morrison&tv',
            'Jesse Spencer&tv',
            'Lisa Edelstein&tv',
            'Olivia Wilde&tv',
            'Omar Epps&tv',
            'Peter Jacobson&tv',
            'Robert Sean Leonard&tv'],
 'Added': '2011-08-19',
 'Countries': ['USA'],
 'Description': '\n'
                'House M.D.: An antisocial maverick doctor who specializes in '
                'diagnostic medicine does whatever it takes to solve puzzling '
                'cases that come his way using his crack team of doctors and '
                'his wits. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-MD',
 'EntryURL': 'https://www.imdb.com/title/tt0412142',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-MD/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-MD/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//House-MD/info.py',
 'Genres': ['Drama&tv', 'Mystery&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0412142',
 'PrimeWire': 'http://www.primewire.ag/tv-5161-House-MD',
 'Ratings': {'IMDB': '8.9/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.35/5',
             'RT': 'N/A',
             'Votes': '3053'},
 'Released': '2004-11-16',
 'Runtime': '45 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5161_House_MD_2004.jpg',
 'Title': 'House-MD'}