{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/House-MD',
 'EntryURL': 'https://www.imdb.com/title/tt0412142',
 'Entry_json': 'Favorites/TV/snapshot/House-MD/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/House-MD/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/House-MD/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Hugh Laurie',
            'url': '/name/nm0491402/'},
           {'@type': 'Person', 'name': 'Omar Epps', 'url': '/name/nm0004898/'},
           {'@type': 'Person',
            'name': 'Robert Sean Leonard',
            'url': '/name/nm0000494/'},
           {'@type': 'Person',
            'name': 'Jesse Spencer',
            'url': '/name/nm0817980/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 398847,
                     'ratingValue': '8.7',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'David Shore',
              'url': '/name/nm0794914/'},
             {'@type': 'Organization', 'url': '/company/co0022072/'},
             {'@type': 'Organization', 'url': '/company/co0146945/'},
             {'@type': 'Organization', 'url': '/company/co0057712/'},
             {'@type': 'Organization', 'url': '/company/co0205765/'},
             {'@type': 'Organization', 'url': '/company/co0129175/'},
             {'@type': 'Organization', 'url': '/company/co0196576/'}],
 'datePublished': '2004-11-16',
 'description': 'House M.D. is a TV series starring Hugh Laurie, Omar Epps, '
                'and Robert Sean Leonard. An antisocial maverick doctor who '
                'specializes in diagnostic medicine does whatever it takes to '
                'solve puzzling cases that come his way using his...',
 'genre': ['Drama', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMDA4NjQzN2ItZDhhNC00ZjVlLWFjNTgtMTEyNDQyOGNjMDE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
 'keywords': 'misanthropy,medical doctor,hospital,maverick doctor,cult '
             'favorite',
 'name': 'House M.D.',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for House: Season Eight',
             'embedUrl': '/video/imdb/vi51488537',
             'name': 'House: Season Eight',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDMyODQ1YTItMjdiZi00M2UyLWFjZGQtNTk3YWI4NTQ5ZWI4XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDMyODQ1YTItMjdiZi00M2UyLWFjZGQtNTk3YWI4NTQ5ZWI4XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2013-01-27T06:18:51Z'},
 'url': '/title/tt0412142/'}