<?php
$infoArray = array('Actors' => array('Aaron Paul&tv',
            'Anna Gunn&tv',
            'Bob Odenkirk&tv',
            'Bryan Cranston&tv',
            'Dean Norris&tv',
            'Giancarlo Esposito&tv',
            'Steven Michael Quezada&tv'),
 'Added' => '2011-08-19',
 'Countries' => array('USA'),
 'Description' => "\nBreaking Bad: A drama about a high school chemistry teacher who's suffering from the world's worst case of mid-life crisis and becomes a criminal. ",
 'Director' => array('NA'),
 'Genres' => array('Crime&tv', 'Drama&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt0903747',
 'PrimeWire' => 'http://www.primewire.ag/tv-2742853-Breaking-Bad',
 'Ratings' => array('IMDB' => '9.5/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.44/5',
             'RT' => 'N/A',
             'Votes' => '1236'),
 'Released' => '2008-01-20',
 'Runtime' => '45 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/4128_Breaking_Bad_2008.jpg',
 'Title' => 'Breaking-Bad');
?>