{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Shadow-Of-The-Colossus-2018',
 'EntryURL': 'https://rawg.io/games/shadow-of-the-colossus-2018',
 'Entry_json': 'Favorites/Games/snapshot/Shadow-Of-The-Colossus-2018/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Shadow-Of-The-Colossus-2018/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Shadow-Of-The-Colossus-2018/thumb.jpg',
 'added': 901,
 'background_image': 'https://media.rawg.io/media/games/5c5/5c5089af36b99bf9465357a8556449f9.jpg',
 'developers': ['SCE Japan Studio', 'Bluepoint Games'],
 'genres': ['Action', 'Adventure'],
 'name': 'Shadow of the Colossus  (2018)',
 'platforms': ['PlayStation 4'],
 'publishers': ['Sony Interactive Entertainment'],
 'released': '2018-02-06',
 'slug': 'shadow-of-the-colossus-2018'}