{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-01-21',
 'EntryPath': 'Favorites/TV/snapshot/Chozen',
 'EntryURL': 'https://www.imdb.com/title/tt3221268',
 'Entry_json': 'Favorites/TV/snapshot/Chozen/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Chozen/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Chozen/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bobby Moynihan',
            'url': '/name/nm1293885/'},
           {'@type': 'Person',
            'name': 'Michael Peña',
            'url': '/name/nm0671567/'},
           {'@type': 'Person',
            'name': 'Hannibal Buress',
            'url': '/name/nm2868110/'},
           {'@type': 'Person',
            'name': 'Nick Swardson',
            'url': '/name/nm0841910/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1771,
                     'ratingValue': '6.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Grant DeKernion',
              'url': '/name/nm6069998/'},
             {'@type': 'Organization', 'url': '/company/co0216537/'},
             {'@type': 'Organization', 'url': '/company/co0284276/'},
             {'@type': 'Organization', 'url': '/company/co0159275/'},
             {'@type': 'Organization', 'url': '/company/co0291982/'}],
 'datePublished': '2014-01-13',
 'description': 'Chozen is a TV series starring Bobby Moynihan, Michael Peña, '
                'and Hannibal Buress. Chozen is an animated comedy about its '
                'title character, "Chozen," a gay white rapper fresh out of '
                'prison. Armed with a new message, Chozen is on a...',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQxMjM2MTE3MF5BMl5BanBnXkFtZTgwMjc2MzQ5MDE@._V1_.jpg',
 'keywords': 'character name as series title,chozen character,one word series '
             'title,homosexual,gay lead character',
 'name': 'Chozen',
 'url': '/title/tt3221268/'}