{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Reloaded',
 'EntryURL': 'https://www.imdb.com/title/tt0234215',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Reloaded/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Reloaded/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Reloaded/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Keanu Reeves',
            'url': '/name/nm0000206/'},
           {'@type': 'Person',
            'name': 'Laurence Fishburne',
            'url': '/name/nm0000401/'},
           {'@type': 'Person',
            'name': 'Carrie-Anne Moss',
            'url': '/name/nm0005251/'},
           {'@type': 'Person',
            'name': 'Hugo Weaving',
            'url': '/name/nm0915989/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 501162,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Lilly Wachowski',
              'url': '/name/nm0905152/'},
             {'@type': 'Person',
              'name': 'Lana Wachowski',
              'url': '/name/nm0905154/'},
             {'@type': 'Person',
              'name': 'Lilly Wachowski',
              'url': '/name/nm0905152/'},
             {'@type': 'Person',
              'name': 'Lana Wachowski',
              'url': '/name/nm0905154/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0108864/'},
             {'@type': 'Organization', 'url': '/company/co0019968/'},
             {'@type': 'Organization', 'url': '/company/co0024939/'},
             {'@type': 'Organization', 'url': '/company/co0190476/'}],
 'datePublished': '2003-05-15',
 'description': 'The Matrix Reloaded is a movie starring Keanu Reeves, '
                'Laurence Fishburne, and Carrie-Anne Moss. Neo and his allies '
                'race against time before the machines discover the city of '
                'Zion and destroy it. While seeking the truth about the...',
 'director': [{'@type': 'Person',
               'name': 'Lana Wachowski',
               'url': '/name/nm0905154/'},
              {'@type': 'Person',
               'name': 'Lilly Wachowski',
               'url': '/name/nm0905152/'}],
 'duration': 'PT2H18M',
 'genre': ['Action', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'oracle,cult film,prophecy,alternate reality,three word title',
 'name': 'The Matrix Reloaded',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi3086352665',
             'name': 'The Matrix Reloaded',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWM3OGI1OTctNDVjNC00NzE1LThkOTYtMDllZGJiOTQ2Mzc4XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWM3OGI1OTctNDVjNC00NzE1LThkOTYtMDllZGJiOTQ2Mzc4XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:56:48Z'},
 'url': '/title/tt0234215/'}