{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Gallery-Episode-2-Heart-Of-The-Emberstone',
 'EntryURL': 'https://rawg.io/games/the-gallery-episode-2-heart-of-the-emberstone',
 'Entry_json': 'Favorites/Games/snapshot/The-Gallery-Episode-2-Heart-Of-The-Emberstone/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Gallery-Episode-2-Heart-Of-The-Emberstone/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Gallery-Episode-2-Heart-Of-The-Emberstone/thumb.jpg',
 'added': 45,
 'background_image': 'https://media.rawg.io/media/screenshots/8eb/8eb83d5c60df11c5f905be48a6c68752.jpg',
 'developers': ['Cloudhead Games ltd.'],
 'genres': ['Adventure', 'Indie'],
 'name': 'The Gallery - Episode 2: Heart of the Emberstone',
 'platforms': ['PC'],
 'publishers': ['Cloudhead Games ltd.'],
 'slug': 'the-gallery-episode-2-heart-of-the-emberstone'}