{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fountain',
 'EntryURL': 'https://www.imdb.com/title/tt0414993',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fountain/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fountain/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Fountain/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Hugh Jackman',
            'url': '/name/nm0413168/'},
           {'@type': 'Person',
            'name': 'Rachel Weisz',
            'url': '/name/nm0001838/'},
           {'@type': 'Person',
            'name': 'Sean Patrick Thomas',
            'url': '/name/nm0859503/'},
           {'@type': 'Person',
            'name': 'Ellen Burstyn',
            'url': '/name/nm0000995/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 223467,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Person',
              'name': 'Ari Handel',
              'url': '/name/nm0359504/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0021592/'},
             {'@type': 'Organization', 'url': '/company/co0062935/'},
             {'@type': 'Organization', 'url': '/company/co0025101/'},
             {'@type': 'Organization', 'url': '/company/co0005803/'},
             {'@type': 'Organization', 'url': '/company/co0140758/'}],
 'datePublished': '2006-11-22',
 'description': 'The Fountain is a movie starring Hugh Jackman, Rachel Weisz, '
                'and Sean Patrick Thomas. As a modern-day scientist, Tommy is '
                'struggling with mortality, desperately searching for the '
                'medical breakthrough that will save the life of his...',
 'director': {'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
 'duration': 'PT1H37M',
 'genre': ['Drama', 'Mystery', 'Romance', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU5OTczMTcxMV5BMl5BanBnXkFtZTcwNDg3MTEzMw@@._V1_.jpg',
 'keywords': 'tree,mayan,eternity,love,tree of life',
 'name': 'The Fountain',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Warner Home Video',
             'embedUrl': '/video/imdb/vi2582774041',
             'name': 'The Fountain',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTFlMzMwYWMtMGM4NS00YjIxLTkyMWYtYzlmNTA3NmYxZDA2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTFlMzMwYWMtMGM4NS00YjIxLTkyMWYtYzlmNTA3NmYxZDA2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:42:54Z'},
 'url': '/title/tt0414993/'}