{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Bojack-Horseman',
 'EntryURL': 'https://www.imdb.com/title/tt3398228',
 'Entry_json': 'Favorites/TV/snapshot/Bojack-Horseman/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Bojack-Horseman/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Bojack-Horseman/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Will Arnett',
            'url': '/name/nm0004715/'},
           {'@type': 'Person',
            'name': 'Amy Sedaris',
            'url': '/name/nm0781238/'},
           {'@type': 'Person',
            'name': 'Alison Brie',
            'url': '/name/nm1555340/'},
           {'@type': 'Person',
            'name': 'Aaron Paul',
            'url': '/name/nm0666739/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 101014,
                      'ratingValue': '8.7',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Raphael Bob-Waksberg',
              'url': '/name/nm4369688/'},
             {'@type': 'Organization', 'url': '/company/co0274437/'},
             {'@type': 'Organization', 'url': '/company/co0043801/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2014-08-22',
 'description': 'BoJack Horseman is a TV series starring Will Arnett, Amy '
                'Sedaris, and Alison Brie. BoJack Horseman was the star of the '
                'hit television show "Horsin\' Around" in the \'80s and \'90s, '
                "now he's washed up, living in Hollywood, complaining...",
 'genre': ['Animation', 'Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYWQwMDNkM2MtODU4OS00OTY3LTgwOTItNjE2Yzc0MzRkMDllXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'sadness,21st century,anthropomorphism,black comedy,talking '
             'animal',
 'name': 'BoJack Horseman',
 'trailer': [{'@type': 'VideoObject',
              'description': 'See how it all ends. The final episodes of '
                             '"BoJack Horseman" are only on Netflix January '
                             '31, 2020.',
              'embedUrl': '/video/imdb/vi1350483737',
              'name': 'Season 6 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTViMjBjZGMtOTI0MS00MDQwLTgwMzktOWVlNjIyMmNkYTUwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTViMjBjZGMtOTI0MS00MDQwLTgwMzktOWVlNjIyMmNkYTUwXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2020-01-15T20:08:08Z'}],
 'url': '/title/tt3398228/'}