{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mark-Felt-The-Man-Who-Brought-Down-The-White-House',
 'EntryURL': 'https://www.imdb.com/title/tt5175450',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mark-Felt-The-Man-Who-Brought-Down-The-White-House/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mark-Felt-The-Man-Who-Brought-Down-The-White-House/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mark-Felt-The-Man-Who-Brought-Down-The-White-House/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Liam Neeson',
            'url': '/name/nm0000553/'},
           {'@type': 'Person', 'name': 'Diane Lane', 'url': '/name/nm0000178/'},
           {'@type': 'Person',
            'name': 'Marton Csokas',
            'url': '/name/nm0190744/'},
           {'@type': 'Person',
            'name': 'Tony Goldwyn',
            'url': '/name/nm0001282/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 11137,
                     'ratingValue': '6.4',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Mark Felt',
              'url': '/name/nm1944541/'},
             {'@type': 'Person',
              'name': "John D. O'Connor",
              'url': '/name/nm2207084/'},
             {'@type': 'Person',
              'name': 'Peter Landesman',
              'url': '/name/nm1481618/'},
             {'@type': 'Organization', 'url': '/company/co0742273/'},
             {'@type': 'Organization', 'url': '/company/co0515853/'},
             {'@type': 'Organization', 'url': '/company/co0535275/'},
             {'@type': 'Organization', 'url': '/company/co0013922/'},
             {'@type': 'Organization', 'url': '/company/co0540798/'},
             {'@type': 'Organization', 'url': '/company/co0259281/'},
             {'@type': 'Organization', 'url': '/company/co0587695/'}],
 'datePublished': '2017-09-27',
 'description': 'Mark Felt: The Man Who Brought Down the White House is a '
                'movie starring Liam Neeson, Diane Lane, and Marton Csokas. '
                'The story of Mark Felt, who under the name "Deep Throat" '
                'helped journalists Bob Woodward and Carl Bernstein uncover...',
 'director': {'@type': 'Person',
              'name': 'Peter Landesman',
              'url': '/name/nm1481618/'},
 'duration': 'PT1H43M',
 'genre': ['Biography', 'Drama', 'History', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjQzMDEwMjMyNF5BMl5BanBnXkFtZTgwNjA1NTA1MzI@._V1_.jpg',
 'keywords': 'whistleblower,father daughter relationship,mother daughter '
             'relationship,hippie,commune',
 'name': 'Mark Felt: The Man Who Brought Down the White House',
 'trailer': {'@type': 'VideoObject',
             'description': 'The story of Mark Felt, who under the name "Deep '
                            'Throat" helped journalists Bob Woodward and Carl '
                            'Bernstein uncover the Watergate scandal in 1974.',
             'embedUrl': '/video/imdb/vi52345113',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTU3MzAwNjg4MV5BMl5BanBnXkFtZTgwNDYxNjczMzI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTU3MzAwNjg4MV5BMl5BanBnXkFtZTgwNDYxNjczMzI@._V1_.jpg',
             'uploadDate': '2017-08-29T14:34:36Z'},
 'url': '/title/tt5175450/'}