{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Satisfactory',
 'EntryURL': 'https://rawg.io/games/satisfactory',
 'Entry_json': 'Favorites/Games/snapshot/Satisfactory/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Satisfactory/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Satisfactory/thumb.jpg',
 'added': 111,
 'background_image': 'https://media.rawg.io/media/screenshots/523/523f60abcb2e46376bb0f6963de1797d.jpg',
 'developers': ['Coffee Stain Studios'],
 'genres': ['Action', 'Adventure', 'Strategy', 'Indie'],
 'name': 'Satisfactory',
 'platforms': ['PC'],
 'publishers': ['Coffee Stain Studios'],
 'released': '2019-03-19',
 'slug': 'satisfactory'}