{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Pans-Labyrinth',
 'EntryURL': 'https://www.imdb.com/title/tt0457430',
 'Entry_json': 'Favorites/Movies/snapshot/Pans-Labyrinth/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Pans-Labyrinth/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Pans-Labyrinth/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ivana Baquero',
            'url': '/name/nm1419440/'},
           {'@type': 'Person',
            'name': 'Ariadna Gil',
            'url': '/name/nm0317725/'},
           {'@type': 'Person',
            'name': 'Sergi López',
            'url': '/name/nm0530365/'},
           {'@type': 'Person',
            'name': 'Maribel Verdú',
            'url': '/name/nm0893941/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 604871,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Guillermo del Toro',
              'url': '/name/nm0868219/'},
             {'@type': 'Organization', 'url': '/company/co0016173/'},
             {'@type': 'Organization', 'url': '/company/co0024845/'},
             {'@type': 'Organization', 'url': '/company/co0040776/'},
             {'@type': 'Organization', 'url': '/company/co0164586/'},
             {'@type': 'Organization', 'url': '/company/co0157705/'},
             {'@type': 'Organization', 'url': '/company/co0058749/'},
             {'@type': 'Organization', 'url': '/company/co0115302/'},
             {'@type': 'Organization', 'url': '/company/co0149944/'}],
 'datePublished': '2006-10-11',
 'description': 'El laberinto del fauno is a movie starring Ivana Baquero, '
                'Ariadna Gil, and Sergi López. In the Falangist Spain of 1944, '
                'the bookish young stepdaughter of a sadistic army officer '
                'escapes into an eerie but captivating fantasy world.',
 'director': [{'@type': 'Person',
               'name': 'Guillermo del Toro',
               'url': '/name/nm0868219/'}],
 'duration': 'PT1H58M',
 'genre': ['Drama', 'Fantasy', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU3ODg2NjQ5NF5BMl5BanBnXkFtZTcwMDEwODgzMQ@@._V1_.jpg',
 'keywords': 'fairy,hiding,maze,spain,labyrinth',
 'name': 'El laberinto del fauno',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi1876343321',
              'name': 'Tráiler [OV]',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYWQzZWZkMGYtNGZkOC00YzlkLTk5MTEtYjQzNzJmY2NkMGRjXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYWQzZWZkMGYtNGZkOC00YzlkLTk5MTEtYjQzNzJmY2NkMGRjXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
              'uploadDate': '2018-11-30T10:00:04Z'}],
 'url': '/title/tt0457430/'}