{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Between-Two-Ferns-The-Movie',
 'EntryURL': 'https://www.imdb.com/title/tt9398640',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Between-Two-Ferns-The-Movie/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Between-Two-Ferns-The-Movie/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Between-Two-Ferns-The-Movie/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Between-Two-Ferns-The-Movie/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Zach Galifianakis',
            'url': '/name/nm0302108/'},
           {'@type': 'Person',
            'name': 'Matthew McConaughey',
            'url': '/name/nm0000190/'},
           {'@type': 'Person',
            'name': 'Rekha Shankar',
            'url': '/name/nm4363130/'},
           {'@type': 'Person',
            'name': 'Olivia Mekdara',
            'url': '/name/nm4156901/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 23639,
                     'ratingValue': '6.1',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Scott Aukerman',
              'url': '/name/nm0042006/'},
             {'@type': 'Person',
              'name': 'Zach Galifianakis',
              'url': '/name/nm0302108/'},
             {'@type': 'Person',
              'name': 'Scott Aukerman',
              'url': '/name/nm0042006/'},
             {'@type': 'Organization', 'url': '/company/co0215655/'}],
 'datePublished': '2019-09-20',
 'description': 'Between Two Ferns: The Movie is a movie starring Zach '
                'Galifianakis, Matthew McConaughey, and Rekha Shankar. Zach '
                'Galifianakis and his oddball crew take a road trip to '
                'complete a series of high-profile celebrity interviews.',
 'director': {'@type': 'Person',
              'name': 'Scott Aukerman',
              'url': '/name/nm0042006/'},
 'duration': 'PT1H22M',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BYzgyNzUyZjAtNDRiZS00MjQwLTgzMzQtZThhY2Y3YjFmYTc1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'celebrity guest,road trip,interview,celebrity,comedian',
 'name': 'Between Two Ferns: The Movie',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'bestford'},
            'dateCreated': '2019-09-28',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt9398640/'},
            'name': 'Okish',
            'reviewBody': 'It was ok. Considering it has a lot of star cameos '
                          'I would have expected more. Some LOL moments but '
                          'not enough to consider it anymore than mediocre.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '5',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Zach Galifianakis and his oddball crew take a '
                            'road trip to complete a series of high-profile '
                            'celebrity interviews and restore his reputation.',
             'embedUrl': '/video/imdb/vi2931801881',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTRiMzFmNmMtMDU5YS00ZjAxLTgzZDUtMDk2ZjViN2ViYTRlXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTRiMzFmNmMtMDU5YS00ZjAxLTgzZDUtMDk2ZjViN2ViYTRlXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-09-03T16:30:58Z'},
 'url': '/title/tt9398640/'}