{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-03-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Cell',
 'EntryURL': 'https://www.imdb.com/title/tt0209958',
 'Entry_json': 'Favorites/Movies/snapshot/The-Cell/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Cell/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Cell/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jennifer Lopez',
            'url': '/name/nm0000182/'},
           {'@type': 'Person',
            'name': 'Vince Vaughn',
            'url': '/name/nm0000681/'},
           {'@type': 'Person',
            'name': "Vincent D'Onofrio",
            'url': '/name/nm0000352/'},
           {'@type': 'Person',
            'name': 'Colton James',
            'url': '/name/nm0416381/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 93083,
                     'ratingValue': '6.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mark Protosevich',
              'url': '/name/nm0698873/'},
             {'@type': 'Organization', 'url': '/company/co0046718/'},
             {'@type': 'Organization', 'url': '/company/co0067485/'},
             {'@type': 'Organization', 'url': '/company/co0029540/'},
             {'@type': 'Organization', 'url': '/company/co0017404/'},
             {'@type': 'Organization', 'url': '/company/co0028247/'}],
 'datePublished': '2000-08-18',
 'description': 'The Cell is a movie starring Jennifer Lopez, Vince Vaughn, '
                "and Vincent D'Onofrio. An F.B.I. Agent persuades a social "
                'worker, who is adept with a new experimental technology, to '
                'enter the mind of a comatose serial killer in order to...',
 'director': {'@type': 'Person',
              'name': 'Tarsem Singh',
              'url': '/name/nm0802248/'},
 'duration': 'PT1H47M',
 'genre': ['Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMDY1NmVmOTItYWU0NC00OGU2LWIyNTctYTU3NTY3ZjJkOWJjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'serial killer,race against time,coma,fbi,subconscious',
 'name': 'The Cell',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for The Cell',
             'embedUrl': '/video/imdb/vi4235764761',
             'name': 'The Cell',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmU3MWZmZTAtZWYwOC00ODAzLTk0YzktNmM2ODAxODU3Y2FjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmU3MWZmZTAtZWYwOC00ODAzLTk0YzktNmM2ODAxODU3Y2FjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2012-10-27T03:34:48Z'},
 'url': '/title/tt0209958/'}