{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Good-Will-Hunting',
 'EntryURL': 'https://www.imdb.com/title/tt0119217',
 'Entry_json': 'Favorites/Movies/snapshot/Good-Will-Hunting/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Good-Will-Hunting/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Good-Will-Hunting/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Robin Williams',
            'url': '/name/nm0000245/'},
           {'@type': 'Person', 'name': 'Matt Damon', 'url': '/name/nm0000354/'},
           {'@type': 'Person',
            'name': 'Ben Affleck',
            'url': '/name/nm0000255/'},
           {'@type': 'Person',
            'name': 'Stellan Skarsgård',
            'url': '/name/nm0001745/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 825716,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Matt Damon',
              'url': '/name/nm0000354/'},
             {'@type': 'Person',
              'name': 'Ben Affleck',
              'url': '/name/nm0000255/'},
             {'@type': 'Organization', 'url': '/company/co0031032/'},
             {'@type': 'Organization', 'url': '/company/co0093776/'},
             {'@type': 'Organization', 'url': '/company/co0022594/'}],
 'datePublished': '1998-01-09',
 'description': 'Good Will Hunting is a movie starring Robin Williams, Matt '
                'Damon, and Ben Affleck. Will Hunting, a janitor at M.I.T., '
                'has a gift for mathematics, but needs help from a '
                'psychologist to find direction in his life.',
 'director': {'@type': 'Person',
              'name': 'Gus Van Sant',
              'url': '/name/nm0001814/'},
 'duration': 'PT2H6M',
 'genre': ['Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'professor,genius,friend,mathematical genius,original story',
 'name': 'Good Will Hunting',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi1575984665',
             'name': 'Good Will Hunting',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzA4ZTY4YWItY2JkMS00NjQ1LTg4MDQtM2NkNWQ2ZTU5YmYxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzA4ZTY4YWItY2JkMS00NjQ1LTg4MDQtM2NkNWQ2ZTU5YmYxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-10-26T03:24:21Z'},
 'url': '/title/tt0119217/'}