<?php
$infoArray = array('Actors' => array('Alison Folland',
            'Barna Moricz',
            'Ben Affleck',
            'Bruce Hunter',
            'Casey Affleck',
            'Chas Lawther',
            'Christopher Britton',
            'Cole Hauser',
            'Daniel Olsen',
            'David Eisner',
            'Frank Nakashima',
            'George Plimpton',
            'Harmony Korine',
            'James Allodi',
            'Kevin Rushton',
            'Matt Damon',
            'Minnie Driver',
            'Philip Williams',
            'Richard Fitzpatrick',
            'Robin Williams',
            'Scott William Winters',
            'Stellan Skarsg&#xE5;rd',
            'Steven Kozlowski',
            'Thomas Lundy',
            'Vik Sahay'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nGood Will Hunting: Will Hunting, a janitor at MIT, has a gift for mathematics which is discovered, and a psychologist tries to help him with his gift and the rest of his life. ',
 'Director' => array('Gus Van Sant'),
 'Genres' => array('Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt0119217',
 'PrimeWire' => 'http://www.primewire.ag/watch-967-Good-Will-Hunting',
 'Ratings' => array('IMDB' => '8.3/10',
             'Metascore' => '70%',
             'PrimeWire' => '4.40/5',
             'RT' => '97%',
             'Votes' => '813'),
 'Released' => '1997-12-02',
 'Runtime' => '126 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/967_Good_Will_Hunting_1997.jpg',
 'Title' => 'Good-Will-Hunting');
?>