{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Dark-Souls8482-Remastered',
 'EntryURL': 'https://rawg.io/games/dark-souls8482-remastered',
 'Entry_json': 'Favorites/Games/snapshot/Dark-Souls8482-Remastered/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Dark-Souls8482-Remastered/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Dark-Souls8482-Remastered/thumb.jpg',
 'added': 2225,
 'background_image': 'https://media.rawg.io/media/games/29c/29c6c21cc0c78cff6f45d23631cc82f4.jpg',
 'developers': ['FromSoftware', 'QLOC'],
 'genres': ['Action'],
 'name': 'Dark Souls: Remastered',
 'platforms': ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
 'publishers': ['Bandai Namco Entertainment', 'FromSoftware, Inc'],
 'released': '2018-05-23',
 'slug': 'dark-souls8482-remastered'}