{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-16',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ovo',
 'EntryURL': 'https://www.imdb.com/title/tt8706906',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ovo/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ovo/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ovo/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Oliver Delaby',
            'url': '/name/nm9975287/'},
           {'@type': 'Person',
            'name': 'Robinson Delacroix',
            'url': '/name/nm4145690/'},
           {'@type': 'Person',
            'name': 'Joël Lesieur',
            'url': '/name/nm9975288/'},
           {'@type': 'Person',
            'name': 'Bob Sanzey',
            'url': '/name/nm3007871/'}],
 'creator': [{'@type': 'Person',
              'name': 'Mathieu Mégemont',
              'url': '/name/nm9693929/'},
             {'@type': 'Organization', 'url': '/company/co0232603/'}],
 'director': {'@type': 'Person',
              'name': 'Mathieu Mégemont',
              'url': '/name/nm9693929/'},
 'duration': 'PT53M',
 'genre': ['Drama', 'Sci-Fi'],
 'name': 'Övo',
 'url': '/title/tt8706906/'}