{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Morrowind',
 'EntryURL': 'https://rawg.io/games/morrowind',
 'Entry_json': 'Favorites/Games/snapshot/Morrowind/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Morrowind/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Morrowind/thumb.jpg',
 'added': 2201,
 'background_image': 'https://media.rawg.io/media/games/ccf/ccf26f6e3d553a04f0033a8107a521b8.jpg',
 'developers': ['Bethesda Game Studios', 'Bethesda Softworks'],
 'genres': ['RPG'],
 'name': 'The Elder Scrolls III: Morrowind',
 'platforms': ['PC', 'Xbox 360', 'Xbox', 'Xbox One'],
 'publishers': ['Bethesda Softworks', 'Ubisoft Entertainment'],
 'released': '2002-05-02',
 'slug': 'morrowind'}