<?php
$infoArray = array('Actors' => array('Bill Couch',
            'Bob Neill',
            'Camilla Carr',
            'Candice Rialson',
            'David Westberg',
            'Dick DeCoit',
            'Farrah Fawcett',
            'Gary Morgan',
            'Glenn R Wilder',
            'Greg Lewis',
            'Greg Michaels',
            'Jenny Agutter',
            'Johnny Haymer',
            'Johnny Timko',
            'Michael Anderson Jr',
            'Michael York',
            'Michelle Stacy',
            'Mitchell Gaylord',
            'Peter Ustinov',
            'Richard Jordan',
            'Richard Kelton',
            'Roscoe Lee Browne'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => "\nLogan's Run: An idyllic sci-fi future has one major drawback: life must end at 30. ",
 'Director' => array('Michael Anderson'),
 'Genres' => array('Drama', 'Romance', 'Sci-Fi', 'Fantasy'),
 'IMDB' => 'http://www.imdb.com/title/tt0074812',
 'PrimeWire' => 'http://www.primewire.ag/watch-3814-Logans-Run',
 'Ratings' => array('IMDB' => '6.8/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.73/5',
             'RT' => '68%',
             'Votes' => '232'),
 'Released' => '1976-06-23',
 'Runtime' => '119 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/3814_Logans_Run_1976.jpg',
 'Title' => 'Logans-Run');
?>