{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Matrix',
 'EntryURL': 'https://www.imdb.com/title/tt0133093',
 'Entry_json': 'Favorites/Movies/snapshot/The-Matrix/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Matrix/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Matrix/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Keanu Reeves',
            'url': '/name/nm0000206/'},
           {'@type': 'Person',
            'name': 'Laurence Fishburne',
            'url': '/name/nm0000401/'},
           {'@type': 'Person',
            'name': 'Carrie-Anne Moss',
            'url': '/name/nm0005251/'},
           {'@type': 'Person',
            'name': 'Hugo Weaving',
            'url': '/name/nm0915989/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1611891,
                     'ratingValue': '8.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Lilly Wachowski',
              'url': '/name/nm0905152/'},
             {'@type': 'Person',
              'name': 'Lana Wachowski',
              'url': '/name/nm0905154/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0108864/'},
             {'@type': 'Organization', 'url': '/company/co0060075/'},
             {'@type': 'Organization', 'url': '/company/co0019968/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'}],
 'datePublished': '1999-03-31',
 'description': 'The Matrix is a movie starring Keanu Reeves, Laurence '
                'Fishburne, and Carrie-Anne Moss. A computer hacker learns '
                'from mysterious rebels about the true nature of his reality '
                'and his role in the war against its controllers.',
 'director': [{'@type': 'Person',
               'name': 'Lana Wachowski',
               'url': '/name/nm0905154/'},
              {'@type': 'Person',
               'name': 'Lilly Wachowski',
               'url': '/name/nm0905152/'}],
 'duration': 'PT2H16M',
 'genre': ['Action', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'simulated reality,artificial reality,war with machines,computer '
             'hacker,post apocalypse',
 'name': 'The Matrix',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Warner Home Video',
             'embedUrl': '/video/imdb/vi1032782617',
             'name': 'The Matrix',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDQ4NTRmN2ItYjgzMS00MzY3LWEwNmYtYmE2ODllZDdhNGI1XkEyXkFqcGdeQXdvbmtpbQ@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDQ4NTRmN2ItYjgzMS00MzY3LWEwNmYtYmE2ODllZDdhNGI1XkEyXkFqcGdeQXdvbmtpbQ@@._V1_.jpg',
             'uploadDate': '2008-12-19T07:12:53Z'},
 'url': '/title/tt0133093/'}