{'Actors': [''],
 'Added': '2014-05-18',
 'Countries': [],
 'Description': '\nThe Third and the Seventh: Alex Roman invites us into a surreal world of architecture and light with his stunning mastery of CG. ',
 'Director': [],
 'Genres': ['Short'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2700713-The-Third-and-the-Seventh',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '3.20/5',
             'RT': 'N/A',
             'Votes': '10'},
 'Released': '2010-01-18',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2700712_The_Third_and_the_Seventh.jpg',
 'Title': 'The-Third-and-the-Seventh'}