{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-19',
 'EntryPath': 'Favorites/Movies/snapshot/From-One-Second-to-the-Next',
 'EntryURL': 'https://www.imdb.com/title/tt3108864',
 'Entry_json': 'Favorites/Movies/snapshot/From-One-Second-to-the-Next/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/From-One-Second-to-the-Next/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/From-One-Second-to-the-Next/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Valetta Bradford',
            'url': '/name/nm11625303/'},
           {'@type': 'Person',
            'name': 'Xzavier Davis-Bilbo',
            'url': '/name/nm11625304/'},
           {'@type': 'Person',
            'name': 'Aurie Parris',
            'url': '/name/nm11625305/'},
           {'@type': 'Person',
            'name': 'Chandler Gerber',
            'url': '/name/nm11625306/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1114,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0026301/'},
             {'@type': 'Organization', 'url': '/company/co0208464/'},
             {'@type': 'Organization', 'url': '/company/co0342601/'},
             {'@type': 'Organization', 'url': '/company/co0384520/'},
             {'@type': 'Organization', 'url': '/company/co0298101/'}],
 'datePublished': '2013-08-07',
 'description': 'From One Second to the Next is a short starring Valetta '
                'Bradford, Xzavier Davis-Bilbo, and Aurie Parris. Stories of '
                'serious traffic accidents caused by texting and driving are '
                'told by the perpetrators and surviving victims.',
 'director': [{'@type': 'Person',
               'name': 'Werner Herzog',
               'url': '/name/nm0001348/'}],
 'duration': 'PT34M',
 'genre': ['Documentary', 'Short'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYmIwYzk4NWYtNzY3Zi00Nzg1LWEyMDgtYWQxMzA2ODU3NjQ4XkEyXkFqcGdeQXVyNDMzNDQ4ODA@._V1_.jpg',
 'keywords': 'driving,text messaging,cell phone,reckless driving,police '
             'officer',
 'name': 'From One Second to the Next',
 'url': '/title/tt3108864/'}