{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Legend-Of-Zelda',
 'EntryURL': 'https://rawg.io/games/the-legend-of-zelda',
 'Entry_json': 'Favorites/Games/snapshot/The-Legend-Of-Zelda/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Legend-Of-Zelda/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Legend-Of-Zelda/thumb.jpg',
 'added': 374,
 'background_image': 'https://media.rawg.io/media/games/e7d/e7d807d4486cb490f21bbc8c3ff35a73.jpg',
 'developers': ['Nintendo'],
 'genres': ['Action', 'Adventure', 'RPG'],
 'name': 'The Legend of Zelda',
 'platforms': ['Nintendo Switch',
               'NES',
               'Game Boy Advance',
               'Wii U',
               'Nintendo 3DS',
               'Wii'],
 'publishers': ['Nintendo'],
 'released': '1986-02-21',
 'slug': 'the-legend-of-zelda'}