{'Actors': [],
 'Added': '2016-11-24',
 'Countries': ['USA'],
 'Description': '\nAdam Ruins Everything: Adam Conover from CollegeHumor turns life as we know it on its ear by showing us how unnecessary, and sometimes horrible, things we think we know to be real and true really are. ',
 'Director': ['NA'],
 'Genres': ['Comedy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt5034326',
 'PrimeWire': 'http://www.primewire.ag/tv-2769551-Adam-Ruins-Everything',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '4.39/5',
             'RT': 'N/A',
             'Votes': '271'},
 'Released': '2015-09-29',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2769551_Adam_Ruins_Everything_2015_37.jpg',
 'Title': 'Adam-Ruins-Everything'}