{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/American-Gangster',
 'EntryURL': 'https://www.imdb.com/title/tt0765429',
 'Entry_json': 'Favorites/Movies/snapshot/American-Gangster/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/American-Gangster/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/American-Gangster/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Denzel Washington',
            'url': '/name/nm0000243/'},
           {'@type': 'Person',
            'name': 'Russell Crowe',
            'url': '/name/nm0000128/'},
           {'@type': 'Person',
            'name': 'Chiwetel Ejiofor',
            'url': '/name/nm0252230/'},
           {'@type': 'Person',
            'name': 'Josh Brolin',
            'url': '/name/nm0000982/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 382663,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Steven Zaillian',
              'url': '/name/nm0001873/'},
             {'@type': 'Person',
              'name': 'Mark Jacobson',
              'url': '/name/nm0414893/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0003687/'},
             {'@type': 'Organization', 'url': '/company/co0142678/'},
             {'@type': 'Organization', 'url': '/company/co0074212/'},
             {'@type': 'Organization', 'url': '/company/co0538351/'}],
 'datePublished': '2007-11-02',
 'description': 'American Gangster is a movie starring Denzel Washington, '
                'Russell Crowe, and Chiwetel Ejiofor. An outcast New York City '
                'cop is charged with bringing down Harlem drug lord Frank '
                'Lucas, whose real life inspired this partly biographical...',
 'director': [{'@type': 'Person',
               'name': 'Ridley Scott',
               'url': '/name/nm0000631/'}],
 'duration': 'PT2H37M',
 'genre': ['Biography', 'Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjFmZGI2YTEtYmJhMS00YTE5LWJjNjAtNDI5OGY5ZDhmNTRlXkEyXkFqcGdeQXVyODAwMTU1MTE@._V1_.jpg',
 'keywords': 'heroin,vietnam,policeman,1970s,breasts',
 'name': 'American Gangster',
 'trailer': [{'@type': 'VideoObject',
              'description': 'American Gangster Trailer',
              'embedUrl': '/video/imdb/vi3216048409',
              'name': 'American Gangster',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjM3OTg2NzE1NV5BMl5BanBnXkFtZTgwNDU3MzQzMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjM3OTg2NzE1NV5BMl5BanBnXkFtZTgwNDU3MzQzMzE@._V1_.jpg',
              'uploadDate': '2007-08-30T08:16:46Z'}],
 'url': '/title/tt0765429/'}