<?php
$infoArray = array('Actors' => array('Brian Goodman',
            'Clifton Collins Jr',
            'David Powledge',
            'Dean Miller',
            'Delroy Lindo',
            'Frank Fox',
            'Frank Military',
            'George W Scott',
            'James Gandolfini',
            'Kathryn Morris',
            'Kristen Shaw',
            'Mark Ruffalo',
            'Michael Davis',
            'Michael Irby',
            'Paul Calderon',
            'Robert Redford',
            'Robin Wright',
            'Sam Ball',
            'Steve Burton'),
 'Added' => '2013-02-22',
 'Countries' => array('USA'),
 'Description' => '\nThe Last Castle: A Court Martialed general rallies together 1200 inmates to rise against the system that put him away. ',
 'Director' => array('Rod Lurie'),
 'Genres' => array('Action', 'Drama', 'Thriller'),
 'IMDB' => 'http://www.imdb.com/title/tt0272020',
 'PrimeWire' => 'http://www.primewire.ag/watch-2345-The-Last-Castle',
 'Ratings' => array('IMDB' => '6.9/10',
             'Metascore' => '43%',
             'PrimeWire' => '4.01/5',
             'RT' => '52%',
             'Votes' => '162'),
 'Released' => '2001-10-19',
 'Runtime' => '131 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2345_The_Last_Castle_2001.jpg',
 'Title' => 'The-Last-Castle');
?>