{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Primer',
 'EntryURL': 'https://www.imdb.com/title/tt0390384',
 'Entry_json': 'Favorites/Movies/snapshot/Primer/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Primer/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Primer/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Shane Carruth',
            'url': '/name/nm1503403/'},
           {'@type': 'Person',
            'name': 'David Sullivan',
            'url': '/name/nm1503383/'},
           {'@type': 'Person',
            'name': 'Casey Gooden',
            'url': '/name/nm1503463/'},
           {'@type': 'Person',
            'name': 'Anand Upadhyaya',
            'url': '/name/nm0881420/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 94678,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Shane Carruth',
              'url': '/name/nm1503403/'},
             {'@type': 'Organization', 'url': '/company/co0357938/'}],
 'datePublished': '2005-05-27',
 'description': 'Primer is a movie starring Shane Carruth, David Sullivan, and '
                'Casey Gooden. Four friends/fledgling entrepreneurs, knowing '
                "that there's something bigger and more innovative than the "
                "different error-checking devices they've built,...",
 'director': {'@type': 'Person',
              'name': 'Shane Carruth',
              'url': '/name/nm1503403/'},
 'duration': 'PT1H17M',
 'genre': ['Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjc3OWVjMTItYjc0Yi00NmFlLTk2YTgtYmU0MzcxMjBkNTYxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'changing the future,time travel,nonlinear '
             'timeline,invention,independent film',
 'name': 'Primer',
 'url': '/title/tt0390384/'}