{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-Ii-1988',
 'EntryURL': 'https://rawg.io/games/final-fantasy-ii-1988',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-Ii-1988/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-Ii-1988/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-Ii-1988/thumb.jpg',
 'added': 91,
 'background_image': 'https://media.rawg.io/media/games/f29/f29af1b9d00800b26af2a6fda55aa3b9.jpg',
 'developers': ['Square'],
 'genres': ['RPG'],
 'name': 'Final Fantasy II (1988)',
 'platforms': ['PSP',
               'NES',
               'PlayStation',
               'Wii',
               'iOS',
               'Wii U',
               'Nintendo 3DS'],
 'publishers': ['Square'],
 'released': '1988-12-17',
 'slug': 'final-fantasy-ii-1988'}