<?php
$infoArray = array('Actors' => array(' Alessandro Nivola ',
            ' Hank Azaria ',
            ' Kelly AuCoin ',
            ' Kristen Connolly ',
            ' Michelle Pfeiffer',
            ' Robert De Niro '),
 'Added' => '2017-05-24',
 'Countries' => array(),
 'Description' => "\nThe Wizard of Lies: A chronicle of Bernie Madoff's Ponzi scheme, which defrauded his clients of billions of dollars. ",
 'Director' => array(),
 'Genres' => array('Biography', 'Crime', 'Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt1933667',
 'PrimeWire' => 'http://www.primewire.ag/watch-2794110-The-Wizard-of-Lies',
 'Ratings' => array('IMDB' => 'N/A',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.19/5',
             'RT' => 'N/A',
             'Votes' => '31'),
 'Released' => '2017-05-20',
 'Runtime' => '133 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2794110_The_Wizard_of_Lies.jpg',
 'Title' => 'The-Wizard-of-Lies');
?>