{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2017-05-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Wizard-of-Lies',
 'EntryURL': 'https://www.imdb.com/title/tt1933667',
 'Entry_json': 'Favorites/Movies/snapshot/The-Wizard-of-Lies/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Wizard-of-Lies/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Wizard-of-Lies/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Robert De Niro',
            'url': '/name/nm0000134/'},
           {'@type': 'Person',
            'name': 'Michelle Pfeiffer',
            'url': '/name/nm0000201/'},
           {'@type': 'Person',
            'name': 'Alessandro Nivola',
            'url': '/name/nm0005273/'},
           {'@type': 'Person',
            'name': 'Nathan Darrow',
            'url': '/name/nm2080557/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 20892,
                      'ratingValue': '6.8',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Sam Levinson',
              'url': '/name/nm0506094/'},
             {'@type': 'Person',
              'name': 'John Burnham Schwartz',
              'url': '/name/nm2331718/'},
             {'@type': 'Person',
              'name': 'Samuel Baum',
              'url': '/name/nm1345603/'},
             {'@type': 'Person',
              'name': 'Diana Henriques',
              'url': '/name/nm4011170/'},
             {'@type': 'Person',
              'name': 'Laurie Sandell',
              'url': '/name/nm5409287/'},
             {'@type': 'Organization', 'url': '/company/co0008693/'},
             {'@type': 'Organization', 'url': '/company/co0063961/'}],
 'datePublished': '2017-05-20',
 'description': 'The Wizard of Lies is a TV movie starring Robert De Niro, '
                'Michelle Pfeiffer, and Alessandro Nivola. The fall of Bernie '
                'Madoff, whose Ponzi scheme robbed $65 billion from '
                'unsuspecting victims; the largest fraud in U.S. history.',
 'director': [{'@type': 'Person',
               'name': 'Barry Levinson',
               'url': '/name/nm0001469/'}],
 'duration': 'PT2H13M',
 'genre': ['Biography', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTc2NDM5MDI2NV5BMl5BanBnXkFtZTgwOTc5NzQzMjI@._V1_.jpg',
 'keywords': 'financial fraud,financier,ponzi scheme,fraudster,fraud',
 'name': 'The Wizard of Lies',
 'trailer': [{'@type': 'VideoObject',
              'description': 'The story of Bernie Madoff and his Ponzi scheme.',
              'embedUrl': '/video/imdb/vi42121497',
              'name': 'Tonight 8/7c',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTY3MDQxNTU0OF5BMl5BanBnXkFtZTgwODkxODczMjI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTY3MDQxNTU0OF5BMl5BanBnXkFtZTgwODkxODczMjI@._V1_.jpg',
              'uploadDate': '2017-05-17T17:20:38Z'}],
 'url': '/title/tt1933667/'}