{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Truman-Show',
 'EntryURL': 'https://www.imdb.com/title/tt0120382',
 'Entry_json': 'Favorites/Movies/snapshot/The-Truman-Show/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Truman-Show/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Truman-Show/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jim Carrey', 'url': '/name/nm0000120/'},
           {'@type': 'Person', 'name': 'Ed Harris', 'url': '/name/nm0000438/'},
           {'@type': 'Person',
            'name': 'Laura Linney',
            'url': '/name/nm0001473/'},
           {'@type': 'Person',
            'name': 'Noah Emmerich',
            'url': '/name/nm0001187/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 895508,
                     'ratingValue': '8.1',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Niccol',
              'url': '/name/nm0629272/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0093765/'}],
 'datePublished': '1998-06-05',
 'description': 'The Truman Show is a movie starring Jim Carrey, Ed Harris, '
                'and Laura Linney. An insurance salesman discovers his whole '
                'life is actually a reality TV show.',
 'director': {'@type': 'Person',
              'name': 'Peter Weir',
              'url': '/name/nm0001837/'},
 'duration': 'PT1H43M',
 'genre': ['Comedy', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
 'keywords': 'hidden camera,simulated reality,fictional reality '
             'show,controlled environment,deception',
 'name': 'The Truman Show',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Paramount',
             'embedUrl': '/video/imdb/vi1878327577',
             'name': 'The Truman Show',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjc5MGY5MTctNDE3OS00OWQ4LWFhYWQtNDc0NTBmYjFiNDM3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjc5MGY5MTctNDE3OS00OWQ4LWFhYWQtNDc0NTBmYjFiNDM3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:52:43Z'},
 'url': '/title/tt0120382/'}