<?php
$infoArray = array('Actors' => array('Benedict Cumberbatch',
            'Bill Paterson',
            'Catherine Terris',
            'Ellie Haddington',
            'Guy Henry',
            'Ian Mercer',
            'Jennifer Connelly',
            'Jeremy Northam',
            'Jim Carter',
            'Ken Drury',
            'Paul Bettany',
            'Paul Campbell',
            'Richard Ridings',
            'Robert Glenister',
            'Teresa Churcher',
            'Toby Jones',
            'Zak Davies'),
 'Added' => '2013-07-21',
 'Countries' => array('UK'),
 'Description' => '\r\n              Creation: What happens when a world-renowned scientist, crushed by the loss of his eldest daughter, formulates a theory in conflict with religious dogma? This is the story of Charles Darwin and his master-work "The Origin of Species". It tells of a global revolution played out the confines of a small English village; a passionate marriage torn apart by the most dangerous idea in history; and a theory saved from extinction by the logic of a child.            ',
 'Director' => array('Jon Amiel'),
 'Genres' => array('Drama', 'Biography'),
 'IMDB' => 'http://www.imdb.com/title/tt0974014',
 'PrimeWire' => 'http://www.primewire.ag/watch-25668-Creation',
 'Ratings' => array('IMDB' => '6.8/10',
             'Metascore' => '51%',
             'PrimeWire' => '3.94/5',
             'RT' => '46%',
             'Votes' => '109'),
 'Released' => '2009-09-10',
 'Runtime' => '108 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/25668_Creation_2009.jpg',
 'Title' => 'Creation');
?>