{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Pentagon-Wars',
 'EntryURL': 'https://www.imdb.com/title/tt0144550',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Pentagon-Wars/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Pentagon-Wars/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Pentagon-Wars/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Pentagon-Wars/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kelsey Grammer',
            'url': '/name/nm0001288/'},
           {'@type': 'Person', 'name': 'Cary Elwes', 'url': '/name/nm0000144/'},
           {'@type': 'Person',
            'name': 'Viola Davis',
            'url': '/name/nm0205626/'},
           {'@type': 'Person',
            'name': 'John C. McGinley',
            'url': '/name/nm0001525/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 3565,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'James Burton',
              'url': '/name/nm0123605/'},
             {'@type': 'Person',
              'name': 'Jamie Malanowski',
              'url': '/name/nm0538932/'},
             {'@type': 'Person',
              'name': 'Martyn Burke',
              'url': '/name/nm0121789/'},
             {'@type': 'Organization', 'url': '/company/co0008693/'}],
 'datePublished': '1998-02-28',
 'description': 'The Pentagon Wars is a TV movie starring Kelsey Grammer, Cary '
                'Elwes, and Viola Davis. Story of a cover up in the military.',
 'director': {'@type': 'Person',
              'name': 'Richard Benjamin',
              'url': '/name/nm0000907/'},
 'duration': 'PT1H44M',
 'genre': ['Comedy', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI4NjkxNjQyN15BMl5BanBnXkFtZTcwNzQ1NDgyMQ@@._V1_.jpg',
 'keywords': 'cover up,army,military,u.s. air force,u.s. army',
 'name': 'The Pentagon Wars',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'davs'},
            'dateCreated': '2002-11-25',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0144550/'},
            'name': 'Surprisingly compelling for a TV movie',
            'reviewBody': 'The ending scenes are Bill Murray hokey, but the '
                          'movie is surprisingly compelling.  I was vaguely '
                          'familiar with the facts behind the story, but I '
                          "intend to read Mr. Burton's book now.  The part of "
                          "Burton's assistant seemed to me to be well played.  "
                          "Grammer's portrayal fit my perception of a Pentagon "
                          'general, but his aides come out as just '
                          'caricatures.'},
 'url': '/title/tt0144550/'}