{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2017-05-29',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Everything-And-Nothing',
 'EntryURL': 'https://www.imdb.com/title/tt2071460',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Everything-And-Nothing/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Everything-And-Nothing/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Everything-And-Nothing/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Everything-And-Nothing/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jim Al-Khalili',
            'url': '/name/nm2629380/'},
           {'@type': 'Person',
            'name': 'Carlos Frenk',
            'url': '/name/nm3512822/'},
           {'@type': 'Person',
            'name': 'Simon Schaffer',
            'url': '/name/nm2406693/'},
           {'@type': 'Person',
            'name': 'Ian Stewart',
            'url': '/name/nm0829440/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 590,
                     'ratingValue': '8.6',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Organization', 'url': '/company/co0274645/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'}],
 'datePublished': '2011-03-21',
 'description': 'Everything and Nothing is a TV mini-series starring Jim '
                'Al-Khalili, Carlos Frenk, and Simon Schaffer. Two-part '
                'documentary which deals with two of the deepest questions '
                'there are - what is everything, and what is nothing? In '
                'two...',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BOTFhNzg4YzQtYjlmMC00N2E3LTkzZWEtNWI3YTY1NzUwYmJiXkEyXkFqcGdeQXVyNzY2MjA3MjQ@._V1_.jpg',
 'keywords': 'tv mini series',
 'name': 'Everything and Nothing',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'RiWeHa'},
            'dateCreated': '2018-12-05',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt2071460/'},
            'name': 'Creative visualisations',
            'reviewBody': 'Great explanations of these hard-to-grasp theories. '
                          'Very creative visualisations. Engaging narration.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '7',
                             'worstRating': '1'}},
 'url': '/title/tt2071460/'}