{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-10',
 'EntryPath': 'Favorites/Movies/snapshot/Public-Enemies',
 'EntryURL': 'https://www.imdb.com/title/tt1152836',
 'Entry_json': 'Favorites/Movies/snapshot/Public-Enemies/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Public-Enemies/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Public-Enemies/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Christian Bale',
            'url': '/name/nm0000288/'},
           {'@type': 'Person',
            'name': 'Johnny Depp',
            'url': '/name/nm0000136/'},
           {'@type': 'Person',
            'name': 'Christian Stolte',
            'url': '/name/nm0831601/'},
           {'@type': 'Person',
            'name': 'Jason Clarke',
            'url': '/name/nm0164809/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 274225,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Ronan Bennett',
              'url': '/name/nm0072032/'},
             {'@type': 'Person',
              'name': 'Michael Mann',
              'url': '/name/nm0000520/'},
             {'@type': 'Person',
              'name': 'Ann Biderman',
              'url': '/name/nm0081189/'},
             {'@type': 'Person',
              'name': 'Bryan Burrough',
              'url': '/name/nm0123174/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0142678/'},
             {'@type': 'Organization', 'url': '/company/co0035930/'},
             {'@type': 'Organization', 'url': '/company/co0085725/'},
             {'@type': 'Organization', 'url': '/company/co0063961/'},
             {'@type': 'Organization', 'url': '/company/co0088354/'},
             {'@type': 'Organization', 'url': '/company/co0169264/'}],
 'datePublished': '2009-07-01',
 'description': 'Public Enemies is a movie starring Christian Bale, Johnny '
                'Depp, and Christian Stolte. The Feds try to take down '
                'notorious American gangsters John Dillinger, Baby Face Nelson '
                'and Pretty Boy Floyd during a booming crime wave in the...',
 'director': [{'@type': 'Person',
               'name': 'Michael Mann',
               'url': '/name/nm0000520/'}],
 'duration': 'PT2H20M',
 'genre': ['Biography', 'Crime', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMGI4YTIxMDQtNDlmNC00ZDJhLWIyZGItM2QyODRiMTEzN2ViXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'celebrity criminal,manhunt,great depression,ends with '
             'biographical notes,reference to arizona',
 'name': 'Public Enemies',
 'trailer': [{'@type': 'VideoObject',
              'description': 'FBI agent Melvin Purvis (Bale) sets his sights '
                             'on American gangster John Dillinger (Depp) and '
                             'others in an attempt to curb a rampant Chicago '
                             'crime spree during the 1930s.',
              'embedUrl': '/video/imdb/vi3372221209',
              'name': 'Public Enemies',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQxNTIyMzA4NV5BMl5BanBnXkFtZTgwNjc4MTEzMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQxNTIyMzA4NV5BMl5BanBnXkFtZTgwNjc4MTEzMzE@._V1_.jpg',
              'uploadDate': '2009-03-06T18:32:06Z'}],
 'url': '/title/tt1152836/'}