{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/Tosh0',
 'EntryURL': 'https://www.imdb.com/title/tt1430587',
 'Entry_json': 'Favorites/TV/snapshot/Tosh0/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Tosh0/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Tosh0/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Daniel Tosh',
            'url': '/name/nm1169495/'},
           {'@type': 'Person', 'name': 'T.K. Kelly', 'url': '/name/nm5008780/'},
           {'@type': 'Person', 'name': 'Sam Jarvis', 'url': '/name/nm6190986/'},
           {'@type': 'Person',
            'name': 'Nick Malis',
            'url': '/name/nm1280290/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 14559,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Mike Gibbons',
              'url': '/name/nm1395537/'},
             {'@type': 'Person',
              'name': 'Daniel Tosh',
              'url': '/name/nm1169495/'},
             {'@type': 'Organization', 'url': '/company/co0183875/'},
             {'@type': 'Organization', 'url': '/company/co0029768/'},
             {'@type': 'Organization', 'url': '/company/co0319818/'},
             {'@type': 'Organization', 'url': '/company/co0299936/'}],
 'datePublished': '2009-06-04',
 'description': 'Tosh.0 is a TV series starring Daniel Tosh, T.K. Kelly, and '
                'Sam Jarvis. Daniel Tosh provides humorous commentary on '
                'content from the Internet.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BNWY4MWIzNDItMmM3MS00MjZkLTg0MzUtMjI2M2Y2ODI3NDRkXkEyXkFqcGdeQXVyODg3NDc1OTE@._V1_.jpg',
 'keywords': 'pixelated nudity,vomiting,2000s,2010s,reference to daniel tosh',
 'name': 'Tosh.0',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Tosh.0: Season 10',
              'embedUrl': '/video/imdb/vi933412121',
              'name': 'Tosh.0: Season 10',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZWQ3OGU4ZWYtMTg3NS00NDM2LThjNjAtYzhlNzUxZWQ4MzRhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZWQ3OGU4ZWYtMTg3NS00NDM2LThjNjAtYzhlNzUxZWQ4MzRhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-03-16T07:39:03Z'}],
 'url': '/title/tt1430587/'}