{'Actors': ['Daniel Tosh&tv'],
 'Added': '2011-08-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Tosh.0: Daniel Tosh provides humorous commentary on content '
                'from the Internet. ',
 'Director': [],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Tosh0',
 'EntryURL': 'https://www.imdb.com/title/tt1430587',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Tosh0/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Tosh0/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Tosh0/info.py',
 'Genres': ['Comedy&tv'],
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.68/5',
             'RT': 'N/A',
             'Votes': '890'},
 'Released': '2009-06-04',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/11149_Tosh0_2009.jpg',
 'Title': 'Tosh0'}