{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/The-Colbert-Report',
 'EntryURL': 'https://www.imdb.com/title/tt0458254',
 'Entry_json': 'Favorites/TV/snapshot/The-Colbert-Report/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Colbert-Report/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Colbert-Report/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Stephen Colbert',
            'url': '/name/nm0170306/'},
           {'@type': 'Person', 'name': 'Jay Katsir', 'url': '/name/nm2029859/'},
           {'@type': 'Person',
            'name': 'Jon Stewart',
            'url': '/name/nm0829537/'},
           {'@type': 'Person',
            'name': 'Paul Dinello',
            'url': '/name/nm0227576/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 37535,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Stephen Colbert',
              'url': '/name/nm0170306/'},
             {'@type': 'Person',
              'name': 'Ben Karlin',
              'url': '/name/nm0439499/'},
             {'@type': 'Person',
              'name': 'Jon Stewart',
              'url': '/name/nm0829537/'},
             {'@type': 'Organization', 'url': '/company/co0176273/'},
             {'@type': 'Organization', 'url': '/company/co0029768/'},
             {'@type': 'Organization', 'url': '/company/co0171943/'},
             {'@type': 'Organization', 'url': '/company/co0239595/'}],
 'datePublished': '2005-10-17',
 'description': 'The Colbert Report is a TV series starring Stephen Colbert, '
                'Jay Katsir, and Jon Stewart. Satirical newscaster Stephen '
                'Colbert provides humorous commentary on the big issues going '
                'on in the United States and the rest of the world,...',
 'genre': ['Comedy', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMGZjYzliOWUtOTNiYS00MDI4LTllMGQtYjgxYjRlODI2NDM3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
 'keywords': '2000s,2010s,three word series title,actor name in series '
             'title,surname in series title',
 'name': 'The Colbert Report',
 'url': '/title/tt0458254/'}