{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Gran-Turismo-3-A-Spec',
 'EntryURL': 'https://rawg.io/games/gran-turismo-3-a-spec',
 'Entry_json': 'Favorites/Games/snapshot/Gran-Turismo-3-A-Spec/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Gran-Turismo-3-A-Spec/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Gran-Turismo-3-A-Spec/thumb.jpg',
 'added': 33,
 'background_image': 'https://media.rawg.io/media/screenshots/f4a/f4ab18046500fe45c5648ea456b1a5b4.jpg',
 'developers': [],
 'genres': ['Racing'],
 'name': 'Gran Turismo 3: A-Spec',
 'platforms': ['PlayStation 2'],
 'publishers': [],
 'released': '2001-04-28',
 'slug': 'gran-turismo-3-a-spec'}