{'@context': 'http://schema.org',
 '@type': 'TVEpisode',
 'EntryAdded': '2014-09-16',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Tank-Man',
 'EntryURL': 'https://www.imdb.com/title/tt0872938',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Tank-Man/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Tank-Man/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Tank-Man/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'T.D. Allman',
            'url': '/name/nm2922340/'},
           {'@type': 'Person',
            'name': 'Nicholas Bequelin',
            'url': '/name/nm2518716/'},
           {'@type': 'Person',
            'name': 'Timothy Brook',
            'url': '/name/nm2921345/'},
           {'@type': 'Person',
            'name': 'Michael Callahan',
            'url': '/name/nm2921521/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 90,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Person',
             'name': 'Antony Thomas',
             'url': '/name/nm0002793/'},
 'datePublished': '2006-04-11',
 'director': {'@type': 'Person',
              'name': 'Antony Thomas',
              'url': '/name/nm0002793/'},
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM3MDFlZmEtODE0Ny00NjI5LWE4NmEtYjFjZGJlYTRlMTE4XkEyXkFqcGdeQXVyOTU4Nzg1NTI@._V1_.jpg',
 'keywords': 'beijing china,tiananmen square beijing,economy,china',
 'name': 'The Tank Man',
 'url': '/title/tt0872938/'}