{'@context': 'http://schema.org',
 '@type': 'CreativeWork',
 'EntryAdded': '2013-06-30',
 'EntryPath': 'Favorites/Movies/snapshot/Dantes-Inferno-An-Animated-Epic',
 'EntryURL': 'https://www.imdb.com/title/tt1401113',
 'Entry_json': 'Favorites/Movies/snapshot/Dantes-Inferno-An-Animated-Epic/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Dantes-Inferno-An-Animated-Epic/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Dantes-Inferno-An-Animated-Epic/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Graham McTavish',
            'url': '/name/nm0574615/'},
           {'@type': 'Person',
            'name': 'Vanessa Branch',
            'url': '/name/nm0104376/'},
           {'@type': 'Person', 'name': 'Steve Blum', 'url': '/name/nm0089710/'},
           {'@type': 'Person',
            'name': 'Peter Jessop',
            'url': '/name/nm0422247/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 7871,
                      'ratingValue': '6.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Dante Alighieri',
              'url': '/name/nm0019604/'},
             {'@type': 'Person',
              'name': 'Brandon Auman',
              'url': '/name/nm1737422/'},
             {'@type': 'Person',
              'name': 'Jonathan Knight',
              'url': '/name/nm0460965/'},
             {'@type': 'Organization', 'url': '/company/co0000869/'},
             {'@type': 'Organization', 'url': '/company/co0042369/'},
             {'@type': 'Organization', 'url': '/company/co0308949/'},
             {'@type': 'Organization', 'url': '/company/co0092021/'},
             {'@type': 'Organization', 'url': '/company/co0055491/'},
             {'@type': 'Organization', 'url': '/company/co0212708/'},
             {'@type': 'Organization', 'url': '/company/co0133439/'},
             {'@type': 'Organization', 'url': '/company/co0295658/'},
             {'@type': 'Organization', 'url': '/company/co0002212/'}],
 'datePublished': '2010-02-09',
 'description': "Dante's Inferno: An Animated Epic is a video starring Graham "
                'McTavish, Vanessa Branch, and Steve Blum. Dante journeys '
                'through the nine circles of Hell -- limbo, lust, gluttony, '
                'greed, anger, heresy, violence, fraud and treachery --...',
 'director': [{'@type': 'Person',
               'name': 'Victor Cook',
               'url': '/name/nm0177328/'},
              {'@type': 'Person',
               'name': 'Mike Disa',
               'url': '/name/nm1918538/'},
              {'@type': 'Person',
               'name': 'Sangjin Kim',
               'url': '/name/nm3259753/'},
              {'@type': 'Person',
               'name': 'Shûkô Murase',
               'url': '/name/nm0613562/'},
              {'@type': 'Person',
               'name': 'Jong-Sik Nam',
               'url': '/name/nm1245378/'},
              {'@type': 'Person',
               'name': 'Lee Seung-Gyu',
               'url': '/name/nm3793155/'},
              {'@type': 'Person',
               'name': 'Yasuomi Umetsu',
               'url': '/name/nm0880870/'}],
 'genre': ['Animation', 'Action', 'Adventure', 'Drama', 'Fantasy', 'Horror'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzEwMGY2OTItYTljMC00NTVkLWE1NGUtNGQ2ZmY3ODlkMmYzL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'hell,crusades,quest,sin,redemption',
 'name': "Dante's Inferno: An Animated Epic",
 'url': '/title/tt1401113/'}