{'Actors': ['Bart McCarthy',
            'Charlotte Cornwell',
            'Graham McTavish',
            'Grey DeLisle',
            'J Grant Albrecht',
            'Kevin Michael Richardson',
            'Mark Hamill',
            'Nika Futterman',
            'Steve Blum',
            'Vanessa Branch',
            'Vanessa Marshall',
            'Victoria Tennant'],
 'Added': '2013-06-30',
 'Countries': ['Japan', 'Singapore', 'South Korea', 'USA'],
 'Description': '\nDantes Inferno An Animated Epic: After fighting in the Crusades for three years, Dante rides back home to his family estate to reunite with his beloved Beatrice and his father. Dante sees a rider following him, but out of the blue, the man vanishes with no trace. When he arrives home, he sees the servants slaughtered, his father murdered and Beatrice near death. When her soul is going to the heaven, Lucifer takes Beatrice to Hell, telling her that Dante has betrayed her. Dante meets Virgil who guides him to Hell, and the poet explains that Beatrice had a bet with Lucifer that Dante would be faithful to her while in the holy war. In return, Lucifer would protect Dante and bring him back home safe and sound. Upon arrival in Hell, Dante learns that he needs to cross nine circles to reach Lucifer ad on his painful journey, he discovers who doomed his family to suffer in Hell. ',
 'Director': ['Victor Cook'],
 'Genres': ['Action', 'Animation', 'Fantasy', 'Horror'],
 'IMDB': 'http://www.imdb.com/title/tt1401113',
 'PrimeWire': 'http://www.primewire.ag/watch-2259707-Dantes-Inferno-An-Animated-Epic',
 'Ratings': {'IMDB': '6.6/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.77/5',
             'RT': 'N/A',
             'Votes': '122'},
 'Released': '2010-02-09',
 'Runtime': '84 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2259707_Dantes_Inferno_An_Animated_Epic_2010.jpg',
 'Title': 'Dantes-Inferno-An-Animated-Epic'}