{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Dark-City',
 'EntryURL': 'https://www.imdb.com/title/tt0118929',
 'Entry_json': 'Favorites/Movies/snapshot/Dark-City/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Dark-City/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Dark-City/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Rufus Sewell',
            'url': '/name/nm0001722/'},
           {'@type': 'Person',
            'name': 'Kiefer Sutherland',
            'url': '/name/nm0000662/'},
           {'@type': 'Person',
            'name': 'Jennifer Connelly',
            'url': '/name/nm0000124/'},
           {'@type': 'Person',
            'name': 'William Hurt',
            'url': '/name/nm0000458/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 183573,
                     'ratingValue': '7.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alex Proyas',
              'url': '/name/nm0001639/'},
             {'@type': 'Person',
              'name': 'Alex Proyas',
              'url': '/name/nm0001639/'},
             {'@type': 'Person',
              'name': 'Lem Dobbs',
              'url': '/name/nm0229644/'},
             {'@type': 'Person',
              'name': 'David S. Goyer',
              'url': '/name/nm0333060/'},
             {'@type': 'Organization', 'url': '/company/co0052515/'},
             {'@type': 'Organization', 'url': '/company/co0046718/'}],
 'datePublished': '1998-02-27',
 'description': 'Dark City is a movie starring Rufus Sewell, Kiefer '
                'Sutherland, and Jennifer Connelly. A man struggles with '
                'memories of his past, which includes a wife he cannot '
                'remember, and a nightmarish world, no one else seems to be '
                'waking up...',
 'director': {'@type': 'Person',
              'name': 'Alex Proyas',
              'url': '/name/nm0001639/'},
 'duration': 'PT1H40M',
 'genre': ['Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMGExOGExM2UtNWM5ZS00OWEzLTllNzYtM2NlMTJlYjBlZTJkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'neo noir,alien race,memory,experiment,serial killer',
 'name': 'Dark City',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Dark City',
             'embedUrl': '/video/imdb/vi2614494745',
             'name': 'Dark City',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODE0NThjNjktOWFjMy00N2YxLWJlOWEtMDlkOWFiMjAyMzY3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODE0NThjNjktOWFjMy00N2YxLWJlOWEtMDlkOWFiMjAyMzY3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2010-08-17T03:12:21Z'},
 'url': '/title/tt0118929/'}