{'Actors': ['Alan Cinis',
            'Bruce Spence',
            'Colin Friels',
            'David Wenham',
            'Deobia Oparei',
            'Doug Scroope',
            'Frank Gallacher',
            'Frederick Miragliotta',
            'Ian Richardson',
            'Jeanette Cronin',
            'Jennifer Connelly',
            'John Bluthal',
            'Justin Monjo',
            'Kiefer Sutherland',
            'Marin Mimica',
            'Marques Johnson',
            'Melissa George',
            'Michael Lake',
            'Mitchell Butel',
            'Nicholas Bell',
            'Paul Livingston',
            'Peter Callan',
            "Richard O'Brien",
            'Ritchie Singer',
            'Rufus Sewell',
            'Terry Bader',
            'William Hurt',
            'William Upjohn'],
 'Added': '2013-02-19',
 'Countries': ['Australia', 'USA'],
 'Description': '\n'
                'Dark City: A man struggles with memories of his past, '
                'including a wife he cannot remember, in a nightmarish world '
                'with no sun and run by beings with telekinetic powers who '
                'seek the souls of humans. ',
 'Director': ['Alex Proyas'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Dark-City',
 'EntryURL': 'http://www.imdb.com/title/tt0118929',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Dark-City/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Dark-City/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Dark-City/info.py',
 'Genres': ['Thriller', 'Sci-Fi', 'Crime', 'Mystery'],
 'IMDB': 'http://www.imdb.com/title/tt0118929',
 'PrimeWire': 'http://www.primewire.ag/watch-2465-Dark-City',
 'Ratings': {'IMDB': '7.8/10',
             'Metascore': '66%',
             'PrimeWire': '4.04/5',
             'RT': 'N/A',
             'Votes': '578'},
 'Released': '1998-02-27',
 'Runtime': '100 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2465_Dark_City_1998.jpg',
 'Title': 'Dark-City'}