{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Demons-Souls',
 'EntryURL': 'https://rawg.io/games/demons-souls',
 'Entry_json': 'Favorites/Games/snapshot/Demons-Souls/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Demons-Souls/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Demons-Souls/thumb.jpg',
 'added': 1404,
 'background_image': 'https://media.rawg.io/media/games/ac3/ac3a89bfbda76082402e42b933c5825a.jpg',
 'developers': ['Atlus U.S.A., Inc.', 'FromSoftware'],
 'genres': ['Action', 'RPG'],
 'name': "Demon's Souls",
 'platforms': ['PlayStation 3'],
 'publishers': ['Atlus'],
 'released': '2009-02-05',
 'slug': 'demons-souls'}