{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-07-02',
 'EntryPath': 'Favorites/Movies/snapshot/Tales-from-the-Organ-Trade',
 'EntryURL': 'https://www.imdb.com/title/tt2518924',
 'Entry_json': 'Favorites/Movies/snapshot/Tales-from-the-Organ-Trade/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Tales-from-the-Organ-Trade/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Tales-from-the-Organ-Trade/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Chas Bruns', 'url': '/name/nm2156661/'},
           {'@type': 'Person',
            'name': 'David Cronenberg',
            'url': '/name/nm0000343/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 213,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Ric Esther Bienstock',
              'url': '/name/nm0081516/'},
             {'@type': 'Organization', 'url': '/company/co0165892/'},
             {'@type': 'Organization', 'url': '/company/co0056415/'},
             {'@type': 'Organization', 'url': '/company/co0174066/'},
             {'@type': 'Organization', 'url': '/company/co0008693/'}],
 'datePublished': '2017-10-17',
 'description': 'Tales from the Organ Trade is a TV movie starring Chas Bruns '
                'and David Cronenberg. A look into the underground world of '
                'trafficking human body parts.',
 'director': {'@type': 'Person',
              'name': 'Ric Esther Bienstock',
              'url': '/name/nm0081516/'},
 'duration': 'PT1H22M',
 'genre': ['Documentary', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjI0NDk4NjAzOV5BMl5BanBnXkFtZTgwNDY1NzYzMDE@._V1_.jpg',
 'keywords': 'f rated',
 'name': 'Tales from the Organ Trade',
 'url': '/title/tt2518924/'}