{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-11-17',
 'EntryPath': 'Favorites/TV/snapshot/How-TV-Ruined-Your-Life',
 'EntryURL': 'https://www.imdb.com/title/tt1827733',
 'Entry_json': 'Favorites/TV/snapshot/How-TV-Ruined-Your-Life/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/How-TV-Ruined-Your-Life/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/How-TV-Ruined-Your-Life/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Charlie Brooker',
            'url': '/name/nm0111765/'},
           {'@type': 'Person',
            'name': 'Liz May Brice',
            'url': '/name/nm0108510/'},
           {'@type': 'Person',
            'name': 'Kevin Eldon',
            'url': '/name/nm0253126/'},
           {'@type': 'Person',
            'name': 'Beth Cordingly',
            'url': '/name/nm0179596/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1160,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0104481/'},
 'datePublished': '2011-01-25',
 'description': 'How TV Ruined Your Life is a TV mini-series starring Charlie '
                'Brooker, Liz May Brice, and Kevin Eldon. A comedic '
                'documentary series in which Charlie Brooker uses a mix of '
                'sketches and jaw-dropping archive footage to explore the '
                'gulf...',
 'genre': ['Documentary', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2NiMTE3YjktYWNhMS00NmVkLTk4NjYtZWNlY2Y0OGE1YmZmXkEyXkFqcGdeQXVyNjUwMTQ4NjE@._V1_.jpg',
 'keywords': 'tv mini series,reenactment',
 'name': 'How TV Ruined Your Life',
 'url': '/title/tt1827733/'}