{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-11-17',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/How-TV-Ruined-Your-Life',
 'EntryURL': 'https://www.imdb.com/title/tt1827733',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/How-TV-Ruined-Your-Life/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/How-TV-Ruined-Your-Life/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/How-TV-Ruined-Your-Life/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/How-TV-Ruined-Your-Life/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Charlie Brooker',
            'url': '/name/nm0111765/'},
           {'@type': 'Person',
            'name': 'Liz May Brice',
            'url': '/name/nm0108510/'},
           {'@type': 'Person',
            'name': 'Kevin Eldon',
            'url': '/name/nm0253126/'},
           {'@type': 'Person',
            'name': 'Beth Cordingly',
            'url': '/name/nm0179596/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1160,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0104481/'},
 'datePublished': '2011-01-25',
 'description': 'How TV Ruined Your Life is a TV mini-series starring Charlie '
                'Brooker, Liz May Brice, and Kevin Eldon. A comedic '
                'documentary series in which Charlie Brooker uses a mix of '
                'sketches and jaw-dropping archive footage to explore the '
                'gulf...',
 'genre': ['Documentary', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2NiMTE3YjktYWNhMS00NmVkLTk4NjYtZWNlY2Y0OGE1YmZmXkEyXkFqcGdeQXVyNjUwMTQ4NjE@._V1_.jpg',
 'keywords': 'tv mini series,reenactment',
 'name': 'How TV Ruined Your Life',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'georgestephenwalker'},
            'dateCreated': '2020-05-27',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt1827733/'},
            'name': "How TV Ruined Your Life, don't say it didn't.",
            'reviewBody': "It's a spin off of the wipe series what can I say? "
                          "It's extremely funny and definitely thought "
                          'provoking. The documentary style gives the show a '
                          'more mature feel over ScreenWipe or NewsWipe making '
                          'it feel more based around facts instead of Mr '
                          'Brookers opinion.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '10',
                             'worstRating': '1'}},
 'url': '/title/tt1827733/'}