{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Kill-Bill-Vol-1',
 'EntryURL': 'https://www.imdb.com/title/tt0266697',
 'Entry_json': 'Favorites/Movies/snapshot/Kill-Bill-Vol-1/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Kill-Bill-Vol-1/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Kill-Bill-Vol-1/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Uma Thurman',
            'url': '/name/nm0000235/'},
           {'@type': 'Person',
            'name': 'David Carradine',
            'url': '/name/nm0001016/'},
           {'@type': 'Person',
            'name': 'Daryl Hannah',
            'url': '/name/nm0000435/'},
           {'@type': 'Person',
            'name': 'Michael Madsen',
            'url': '/name/nm0000514/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 966051,
                      'ratingValue': '8.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Person',
              'name': 'Uma Thurman',
              'url': '/name/nm0000235/'},
             {'@type': 'Organization', 'url': '/company/co0022594/'},
             {'@type': 'Organization', 'url': '/company/co0019267/'},
             {'@type': 'Organization', 'url': '/company/co0086625/'},
             {'@type': 'Organization', 'url': '/company/co0128798/'}],
 'datePublished': '2003-10-10',
 'description': 'Kill Bill: Vol. 1 is a movie starring Uma Thurman, David '
                'Carradine, and Daryl Hannah. After awakening from a four-year '
                'coma, a former assassin wreaks vengeance on the team of '
                'assassins who betrayed her.',
 'director': [{'@type': 'Person',
               'name': 'Quentin Tarantino',
               'url': '/name/nm0000233/'}],
 'duration': 'PT1H51M',
 'genre': ['Action', 'Crime', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'revenge,bride,sword,female protagonist,martial arts',
 'name': 'Kill Bill: Vol. 1',
 'trailer': [{'@type': 'VideoObject',
              'description': 'CT #1, post',
              'embedUrl': '/video/imdb/vi3102711321',
              'name': 'Kill Bill: Vol. 1',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDFjYTYwNmMtY2YwMi00YmVhLTlhOTItMWE1MmQ2N2MyMDgwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDFjYTYwNmMtY2YwMi00YmVhLTlhOTItMWE1MmQ2N2MyMDgwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2011-10-26T03:31:19Z'}],
 'url': '/title/tt0266697/'}