<?php
$infoArray = array('Actors' => array('Ben Mendelsohn',
            'Bradley Cooper',
            'Bruce Greenwood',
            'Eva Mendes',
            'Harris Yulin',
            'Olga Merediz',
            'Ray Liotta',
            'Robert Clohessy',
            'Rose Byrne',
            'Ryan Gosling'),
 'Added' => '2013-05-05',
 'Countries' => array('USA'),
 'Description' => '\nThe Place Beyond the Pines: A motorcycle stunt rider turns to robbing banks as a way to provide for his lover and their newborn child, a decision that puts him on a collision course with an ambitious rookie cop navigating a department ruled by a corrupt detective. ',
 'Director' => array('Derek Cianfrance'),
 'Genres' => array('Crime', 'Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt1817273',
 'PrimeWire' => 'http://www.primewire.ag/watch-2739178-The-Place-Beyond-the-Pines',
 'Ratings' => array('IMDB' => '7.3/10',
             'Metascore' => '68%',
             'PrimeWire' => '4.08/5',
             'RT' => '80%',
             'Votes' => '950'),
 'Released' => '2013-03-20',
 'Runtime' => '140 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2739178_The_Place_Beyond_the_Pines_2013.jpg',
 'Title' => 'The-Place-Beyond-the-Pines');
?>