{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-Xii',
 'EntryURL': 'https://rawg.io/games/final-fantasy-xii',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-Xii/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-Xii/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-Xii/thumb.jpg',
 'added': 112,
 'background_image': 'https://media.rawg.io/media/games/ced/ced839e45016b23215e1f4e462204d6b.jpg',
 'developers': ['Square Enix'],
 'genres': ['RPG'],
 'name': 'Final Fantasy XII',
 'platforms': ['PlayStation 2'],
 'publishers': ['Square Enix'],
 'released': '2006-03-16',
 'slug': 'final-fantasy-xii'}