{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-16',
 'EntryPath': 'Favorites/Movies/snapshot/Sunshine',
 'EntryURL': 'https://www.imdb.com/title/tt0448134',
 'Entry_json': 'Favorites/Movies/snapshot/Sunshine/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Sunshine/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Sunshine/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Cillian Murphy',
            'url': '/name/nm0614165/'},
           {'@type': 'Person', 'name': 'Rose Byrne', 'url': '/name/nm0126284/'},
           {'@type': 'Person',
            'name': 'Chris Evans',
            'url': '/name/nm0262635/'},
           {'@type': 'Person',
            'name': 'Cliff Curtis',
            'url': '/name/nm0193295/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 228058,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alex Garland',
              'url': '/name/nm0307497/'},
             {'@type': 'Organization', 'url': '/company/co0103974/'},
             {'@type': 'Organization', 'url': '/company/co0136728/'},
             {'@type': 'Organization', 'url': '/company/co0016492/'},
             {'@type': 'Organization', 'url': '/company/co0104811/'}],
 'datePublished': '2007-04-05',
 'description': 'Sunshine is a movie starring Cillian Murphy, Rose Byrne, and '
                'Chris Evans. A team of international astronauts are sent on a '
                'dangerous mission to reignite the dying Sun with a nuclear '
                'fission bomb in 2057.',
 'director': {'@type': 'Person',
              'name': 'Danny Boyle',
              'url': '/name/nm0000965/'},
 'duration': 'PT1H47M',
 'genre': ['Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU5Nzg2OTk2NF5BMl5BanBnXkFtZTYwNTc1ODM3._V1_.jpg',
 'keywords': 'spacecraft,sun,spaceship,mission,wtf',
 'name': 'Sunshine',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Fox Searchlight Pictures',
             'embedUrl': '/video/imdb/vi1150026009',
             'name': 'Sunshine',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmU4OTI2YzItYzY4My00NzI3LWJhYjItZDcwMjlhNDMyODc1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmU4OTI2YzItYzY4My00NzI3LWJhYjItZDcwMjlhNDMyODc1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:20:38Z'},
 'url': '/title/tt0448134/'}