{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-07-27',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Humans',
 'EntryURL': 'https://www.imdb.com/title/tt4122068',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Humans/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Humans/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Humans/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Katherine Parkinson',
            'url': '/name/nm1817670/'},
           {'@type': 'Person', 'name': 'Gemma Chan', 'url': '/name/nm2110418/'},
           {'@type': 'Person',
            'name': 'Lucy Carless',
            'url': '/name/nm6845331/'},
           {'@type': 'Person',
            'name': 'Tom Goodman-Hill',
            'url': '/name/nm0329259/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 34195,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Organization', 'url': '/company/co0110977/'},
             {'@type': 'Organization', 'url': '/company/co0103528/'},
             {'@type': 'Organization', 'url': '/company/co0318834/'},
             {'@type': 'Organization', 'url': '/company/co0513319/'},
             {'@type': 'Organization', 'url': '/company/co0583726/'}],
 'datePublished': '2015-06-14',
 'description': 'Humans is a TV series starring Katherine Parkinson, Gemma '
                'Chan, and Lucy Carless. In a parallel present where the '
                "latest must-have gadget for any busy family is a 'Synth' - a "
                "highly-developed robotic servant that's so similar to a...",
 'genre': ['Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ3NjE2OTY4NF5BMl5BanBnXkFtZTgwMTE0NDc0ODE@._V1_.jpg',
 'keywords': 'based on tv series,female protagonist,robot,humanoid,artificial '
             'intelligence',
 'name': 'Humans',
 'trailer': {'@type': 'VideoObject',
             'description': 'In a parallel present where the latest must-have '
                            "gadget for any busy family is a 'Synth' - a "
                            "highly-developed robotic servant that's so "
                            "similar to a real human it's transforming the way "
                            'we live.',
             'embedUrl': '/video/imdb/vi2429007385',
             'name': 'Season 2 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTUwMzY2ODkxOF5BMl5BanBnXkFtZTgwMjI5MzE4MDI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTUwMzY2ODkxOF5BMl5BanBnXkFtZTgwMjI5MzE4MDI@._V1_.jpg',
             'uploadDate': '2016-12-09T12:39:26Z'},
 'url': '/title/tt4122068/'}