{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-02-12',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Real-Time-with-Bill-Maher',
 'EntryURL': 'https://www.imdb.com/title/tt0350448',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Real-Time-with-Bill-Maher/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Real-Time-with-Bill-Maher/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Real-Time-with-Bill-Maher/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Bill Maher', 'url': '/name/nm0005175/'},
           {'@type': 'Person',
            'name': 'Andrew Sullivan',
            'url': '/name/nm1783797/'},
           {'@type': 'Person',
            'name': 'Michael Moore',
            'url': '/name/nm0601619/'},
           {'@type': 'Person',
            'name': 'Arianna Huffington',
            'url': '/name/nm0400251/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 12060,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Organization', 'url': '/company/co0234811/'},
             {'@type': 'Organization', 'url': '/company/co0046803/'},
             {'@type': 'Organization', 'url': '/company/co0008693/'},
             {'@type': 'Organization', 'url': '/company/co0093906/'}],
 'datePublished': '2003-02-21',
 'description': 'Real Time with Bill Maher is a TV series starring Bill Maher, '
                'Andrew Sullivan, and Michael Moore. Comedian and political '
                'satirist Bill Maher discusses topical events with guests from '
                'various backgrounds.',
 'genre': ['Comedy', 'News', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzQ2MTM0MTUtZDQ0Yy00ZGM2LThkMmItNDdjMDRkMTZiMDlmXkEyXkFqcGdeQXVyODg3NDc1OTE@._V1_.jpg',
 'keywords': 'guest,witty host,social commentary,five word title,name in title',
 'name': 'Real Time with Bill Maher',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'pierpont75'},
            'dateCreated': '2003-10-30',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0350448/'},
            'name': 'Political views from a failed actor turned stand up comic',
            'reviewBody': 'Complete waste of time. As predictable as those old '
                          '"point/counterpoint" segments that ran on 60 '
                          'Minutes. Maher was funnier before he began to '
                          'actually think of himself as a pundit. To me, he '
                          'just comes across as an arrogant bore.'},
 'trailer': {'@type': 'VideoObject',
             'embedUrl': '/video/imdb/vi2030353177',
             'name': 'Season 16 Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYWU0MzhiODItY2RiOS00OGMyLTk2ODYtNzUxNmZhYTE3N2MwXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYWU0MzhiODItY2RiOS00OGMyLTk2ODYtNzUxNmZhYTE3N2MwXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
             'uploadDate': '2018-08-27T23:24:21Z'},
 'url': '/title/tt0350448/'}