{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Flash-of-Genius',
 'EntryURL': 'https://www.imdb.com/title/tt1054588',
 'Entry_json': 'Favorites/Movies/snapshot/Flash-of-Genius/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Flash-of-Genius/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Flash-of-Genius/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Greg Kinnear',
            'url': '/name/nm0001427/'},
           {'@type': 'Person',
            'name': 'Lauren Graham',
            'url': '/name/nm0334179/'},
           {'@type': 'Person', 'name': 'Alan Alda', 'url': '/name/nm0000257/'},
           {'@type': 'Person', 'name': 'Tim Eddis', 'url': '/name/nm1537811/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 16271,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Philip Railsback',
              'url': '/name/nm0706882/'},
             {'@type': 'Person',
              'name': 'John Seabrook',
              'url': '/name/nm0780415/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0031181/'},
             {'@type': 'Organization', 'url': '/company/co0086710/'},
             {'@type': 'Organization', 'url': '/company/co0212608/'}],
 'datePublished': '2008-10-03',
 'description': 'Flash of Genius is a movie starring Greg Kinnear, Lauren '
                'Graham, and Alan Alda. Robert Kearns takes on the Detroit '
                'automakers who he claims stole his idea for the intermittent '
                'windshield wiper.',
 'director': [{'@type': 'Person',
               'name': 'Marc Abraham',
               'url': '/name/nm0008953/'}],
 'duration': 'PT1H59M',
 'genre': ['Biography', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI5MDI0NDAxOV5BMl5BanBnXkFtZTcwNzk4ODk3MQ@@._V1_.jpg',
 'keywords': 'intellectual property,ford,windshield wiper,automaker,engineer',
 'name': 'Flash of Genius',
 'trailer': [{'@type': 'VideoObject',
              'description': 'This is the first trailer for Flash of Genius, '
                             'directed by Marc Abraham.',
              'embedUrl': '/video/imdb/vi1591476505',
              'name': 'Flash of Genius: Trailer #1',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTkyODczMjI3Ml5BMl5BanBnXkFtZTgwNjk2ODQyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTkyODczMjI3Ml5BMl5BanBnXkFtZTgwNjk2ODQyMzE@._V1_.jpg',
              'uploadDate': '2008-07-22T15:33:18Z'}],
 'url': '/title/tt1054588/'}