{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-03-28',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Crime',
 'EntryURL': 'https://www.imdb.com/title/tt3488298',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Crime/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Crime/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Crime/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Felicity Huffman',
            'url': '/name/nm0005031/'},
           {'@type': 'Person',
            'name': 'Regina King',
            'url': '/name/nm0005093/'},
           {'@type': 'Person',
            'name': 'Timothy Hutton',
            'url': '/name/nm0000459/'},
           {'@type': 'Person',
            'name': 'Richard Cabral',
            'url': '/name/nm3450051/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 8998,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'John Ridley',
              'url': '/name/nm0725983/'},
             {'@type': 'Organization', 'url': '/company/co0526380/'},
             {'@type': 'Organization', 'url': '/company/co0468286/'},
             {'@type': 'Organization', 'url': '/company/co0209226/'}],
 'datePublished': '2015-03-05',
 'description': 'American Crime is a TV series starring Felicity Huffman, '
                'Regina King, and Timothy Hutton. Seasonal anthology series. '
                'Season 1: The lives of the participants in a trial with '
                'significant racial motives are forever changed during the...',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNWEwY2Q5NDctZDFlYy00N2Y4LTlhYTMtY2U3ZDE3N2Y0ZTE5XkEyXkFqcGdeQXVyMzU3MTc5OTE@._V1_.jpg',
 'keywords': 'trial,anthology,seasonal anthology series,tragedy,criminal '
             'activity',
 'name': 'American Crime',
 'trailer': {'@type': 'VideoObject',
             'description': 'First look at Season 2 of American Crime on ABC.',
             'embedUrl': '/video/imdb/vi1363653145',
             'name': 'Season 2 Promo',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTg4NjQ3NTQ1NF5BMl5BanBnXkFtZTgwNzg2OTc1NzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTg4NjQ3NTQ1NF5BMl5BanBnXkFtZTgwNzg2OTc1NzE@._V1_.jpg',
             'uploadDate': '2015-12-29T09:58:14Z'},
 'url': '/title/tt3488298/'}