{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-07-08',
 'EntryPath': 'Favorites/Movies/snapshot/The-Prestige',
 'EntryURL': 'https://www.imdb.com/title/tt0482571',
 'Entry_json': 'Favorites/Movies/snapshot/The-Prestige/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Prestige/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Prestige/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Christian Bale',
            'url': '/name/nm0000288/'},
           {'@type': 'Person',
            'name': 'Hugh Jackman',
            'url': '/name/nm0413168/'},
           {'@type': 'Person',
            'name': 'Scarlett Johansson',
            'url': '/name/nm0424060/'},
           {'@type': 'Person',
            'name': 'Michael Caine',
            'url': '/name/nm0000323/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1138253,
                      'ratingValue': '8.5',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Jonathan Nolan',
              'url': '/name/nm0634300/'},
             {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
             {'@type': 'Person',
              'name': 'Christopher Priest',
              'url': '/name/nm1793993/'},
             {'@type': 'Organization', 'url': '/company/co0049348/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0041626/'},
             {'@type': 'Organization', 'url': '/company/co0147954/'}],
 'datePublished': '2006-10-19',
 'description': 'The Prestige is a movie starring Christian Bale, Hugh '
                'Jackman, and Scarlett Johansson. After a tragic accident, two '
                'stage magicians engage in a battle to create the ultimate '
                'illusion while sacrificing everything they have to outwit...',
 'director': [{'@type': 'Person',
               'name': 'Christopher Nolan',
               'url': '/name/nm0634240/'}],
 'duration': 'PT2H10M',
 'genre': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_.jpg',
 'keywords': 'rivalry,illusion,obsession,magician,secret',
 'name': 'The Prestige',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Two stage magicians engage in competitive '
                             'one-upmanship in an attempt to create the '
                             'ultimate stage illusion.',
              'embedUrl': '/video/imdb/vi2885334553',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTkzMzMyNzE0NV5BMl5BanBnXkFtZTgwMDU4NDM0MDI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTkzMzMyNzE0NV5BMl5BanBnXkFtZTgwMDU4NDM0MDI@._V1_.jpg',
              'uploadDate': '2016-10-27T01:19:48Z'}],
 'url': '/title/tt0482571/'}