{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-25',
 'EntryPath': 'Favorites/TV/snapshot/V',
 'EntryURL': 'https://www.imdb.com/title/tt0085106',
 'Entry_json': 'Favorites/TV/snapshot/V/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/V/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/V/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jane Badler',
            'url': '/name/nm0000826/'},
           {'@type': 'Person',
            'name': 'Michael Durrell',
            'url': '/name/nm0244359/'},
           {'@type': 'Person', 'name': 'Faye Grant', 'url': '/name/nm0002109/'},
           {'@type': 'Person',
            'name': 'Peter Nelson',
            'url': '/name/nm0625664/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 12979,
                     'ratingValue': '7.9',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Organization', 'url': '/company/co0016316/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'}],
 'datePublished': '1983-05-01',
 'description': 'V is a TV mini-series starring Jane Badler, Michael Durrell, '
                'and Faye Grant. When aliens come to Earth to ask for our '
                'help, a few suspicious humans discover their horrific true '
                'intentions and prepare to resist.',
 'genre': ['Action', 'Adventure', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjM1Mzk1NjQyM15BMl5BanBnXkFtZTgwNjY2NDI1MDE@._V1_.jpg',
 'keywords': '1980s,tv mini series,alien,resistance,reptilian',
 'name': 'V',
 'url': '/title/tt0085106/'}