{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Across-the-Universe',
 'EntryURL': 'https://www.imdb.com/title/tt0445922',
 'Entry_json': 'Favorites/Movies/snapshot/Across-the-Universe/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Across-the-Universe/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Across-the-Universe/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Evan Rachel Wood',
            'url': '/name/nm0939697/'},
           {'@type': 'Person',
            'name': 'Jim Sturgess',
            'url': '/name/nm0836343/'},
           {'@type': 'Person',
            'name': 'Joe Anderson',
            'url': '/name/nm1725848/'},
           {'@type': 'Person',
            'name': 'Dana Fuchs',
            'url': '/name/nm2085629/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 104835,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Dick Clement',
              'url': '/name/nm0166074/'},
             {'@type': 'Person',
              'name': 'Ian La Frenais',
              'url': '/name/nm0478588/'},
             {'@type': 'Person',
              'name': 'Julie Taymor',
              'url': '/name/nm0853380/'},
             {'@type': 'Person',
              'name': 'Dick Clement',
              'url': '/name/nm0166074/'},
             {'@type': 'Person',
              'name': 'Ian La Frenais',
              'url': '/name/nm0478588/'},
             {'@type': 'Organization', 'url': '/company/co0003580/'},
             {'@type': 'Organization', 'url': '/company/co0177684/'},
             {'@type': 'Organization', 'url': '/company/co0050544/'},
             {'@type': 'Organization', 'url': '/company/co0241724/'}],
 'datePublished': '2007-09-28',
 'description': 'Across the Universe is a movie starring Evan Rachel Wood, Jim '
                'Sturgess, and Joe Anderson. The music of The Beatles and the '
                'Vietnam War form the backdrop for the romance between an '
                'upper-class American girl and a poor Liverpudlian...',
 'director': [{'@type': 'Person',
               'name': 'Julie Taymor',
               'url': '/name/nm0853380/'}],
 'duration': 'PT2H13M',
 'genre': ['Drama', 'Fantasy', 'History', 'Music', 'Musical', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTIyMTUwNzg3Nl5BMl5BanBnXkFtZTcwMjM1MDI1MQ@@._V1_.jpg',
 'keywords': 'song,protest,artist,near death experience,vietnam war',
 'name': 'Across the Universe',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Columbia Pictures',
              'embedUrl': '/video/imdb/vi95748377',
              'name': 'Across the Universe',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2MzYTEwMDEtY2NjYi00MGNhLWEwN2ItMGU0ZjU3NDVjN2U0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2MzYTEwMDEtY2NjYi00MGNhLWEwN2ItMGU0ZjU3NDVjN2U0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T09:11:09Z'}],
 'url': '/title/tt0445922/'}