{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-08-21',
 'EntryPath': 'Favorites/Movies/snapshot/John-Dies-at-the-End',
 'EntryURL': 'https://www.imdb.com/title/tt1783732',
 'Entry_json': 'Favorites/Movies/snapshot/John-Dies-at-the-End/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/John-Dies-at-the-End/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/John-Dies-at-the-End/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Chase Williamson',
            'url': '/name/nm3311695/'},
           {'@type': 'Person', 'name': 'Rob Mayes', 'url': '/name/nm2373827/'},
           {'@type': 'Person',
            'name': 'Paul Giamatti',
            'url': '/name/nm0316079/'},
           {'@type': 'Person',
            'name': 'Clancy Brown',
            'url': '/name/nm0000317/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 35508,
                     'ratingValue': '6.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Don Coscarelli',
              'url': '/name/nm0181741/'},
             {'@type': 'Person',
              'name': 'David Wong',
              'url': '/name/nm4200139/'},
             {'@type': 'Organization', 'url': '/company/co0323699/'},
             {'@type': 'Organization', 'url': '/company/co0323671/'},
             {'@type': 'Organization', 'url': '/company/co0323778/'},
             {'@type': 'Organization', 'url': '/company/co0388505/'},
             {'@type': 'Organization', 'url': '/company/co0185917/'}],
 'datePublished': '2013-01-25',
 'description': 'John Dies at the End is a movie starring Chase Williamson, '
                'Rob Mayes, and Paul Giamatti. A new street drug that sends '
                'its users across time and dimensions has one drawback: some '
                'people return no longer human. Can two college...',
 'director': {'@type': 'Person',
              'name': 'Don Coscarelli',
              'url': '/name/nm0181741/'},
 'duration': 'PT1H39M',
 'genre': ['Comedy', 'Fantasy', 'Horror', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTUyNzIyNzc0MV5BMl5BanBnXkFtZTcwOTM5ODg1OA@@._V1_.jpg',
 'keywords': 'multiple dimensions,male friendship,cult film,mind altering '
             'drug,bullet time',
 'name': 'John Dies at the End',
 'trailer': {'@type': 'VideoObject',
             'description': 'A pair of college dropouts who can barely hold '
                            'down jobs are enlisted to save humanity from a '
                            'paranormal, psychoactive drug that promises an '
                            'out-of-body experience with each hit.',
             'embedUrl': '/video/imdb/vi643671065',
             'name': 'No. 1',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTcwMTY0ODI5Ml5BMl5BanBnXkFtZTcwNzE3NTg2OA@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTcwMTY0ODI5Ml5BMl5BanBnXkFtZTcwNzE3NTg2OA@@._V1_.jpg',
             'uploadDate': '2012-11-01T15:47:16Z'},
 'url': '/title/tt1783732/'}