{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Gran-Turismo-2',
 'EntryURL': 'https://rawg.io/games/gran-turismo-2',
 'Entry_json': 'Favorites/Games/snapshot/Gran-Turismo-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Gran-Turismo-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Gran-Turismo-2/thumb.jpg',
 'added': 101,
 'background_image': 'https://media.rawg.io/media/screenshots/98d/98dc5f038aa186b48aa16bbb858d276a.jpg',
 'developers': ['Polyphony Digital'],
 'genres': ['Racing'],
 'name': 'Gran Turismo 2',
 'platforms': ['Dreamcast', 'PlayStation'],
 'publishers': ['Sony Computer Entertainment',
                'Sony Interactive Entertainment'],
 'released': '1999-12-11',
 'slug': 'gran-turismo-2'}