{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-09',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Assassination-of-Jesse-James-by-the-Coward-Robert-Ford',
 'EntryURL': 'https://www.imdb.com/title/tt0443680',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Assassination-of-Jesse-James-by-the-Coward-Robert-Ford/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Assassination-of-Jesse-James-by-the-Coward-Robert-Ford/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Assassination-of-Jesse-James-by-the-Coward-Robert-Ford/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Assassination-of-Jesse-James-by-the-Coward-Robert-Ford/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Brad Pitt', 'url': '/name/nm0000093/'},
           {'@type': 'Person',
            'name': 'Casey Affleck',
            'url': '/name/nm0000729/'},
           {'@type': 'Person',
            'name': 'Sam Shepard',
            'url': '/name/nm0001731/'},
           {'@type': 'Person',
            'name': 'Mary-Louise Parker',
            'url': '/name/nm0000571/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 164092,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Dominik',
              'url': '/name/nm0231596/'},
             {'@type': 'Person',
              'name': 'Ron Hansen',
              'url': '/name/nm0361069/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0166295/'},
             {'@type': 'Organization', 'url': '/company/co0074212/'},
             {'@type': 'Organization', 'url': '/company/co0136967/'},
             {'@type': 'Organization', 'url': '/company/co0181866/'},
             {'@type': 'Organization', 'url': '/company/co0167271/'}],
 'datePublished': '2007-10-10',
 'description': 'The Assassination of Jesse James by the Coward Robert Ford is '
                'a movie starring Brad Pitt, Casey Affleck, and Sam Shepard. '
                "Robert Ford, who's idolized Jesse James since childhood, "
                'tries hard to join the reforming gang of the Missouri...',
 'director': {'@type': 'Person',
              'name': 'Andrew Dominik',
              'url': '/name/nm0231596/'},
 'duration': 'PT2H40M',
 'genre': ['Biography', 'Crime', 'Drama', 'History', 'Western'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY2NDI2MTc2NV5BMl5BanBnXkFtZTcwNjA2NTQzMw@@._V1_.jpg',
 'keywords': 'based on a novel,jesse james character,bob ford '
             'character,assassination,hero worship',
 'name': 'The Assassination of Jesse James by the Coward Robert Ford',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'MR_Heraclius'},
            'dateCreated': '2020-02-22',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0443680/'},
            'name': 'One of the most amazing movies I have ever seen.',
            'reviewBody': 'Masterful character study and motivationally driven '
                          'lives which clashed at the wrong time in history. '
                          'Performances were delivered by first class actors '
                          'and direction. An underrated tense thriller of one '
                          'of the most complex people in history versus one of '
                          'the most average.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for "The Assassination of Jesse James by '
                            'the Coward Robert Ford"',
             'embedUrl': '/video/imdb/vi2897281305',
             'name': 'Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTI3MTY1ODEzMF5BMl5BanBnXkFtZTYwMzgwMzYy._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTI3MTY1ODEzMF5BMl5BanBnXkFtZTYwMzgwMzYy._V1_.jpg',
             'uploadDate': '2007-09-07T07:42:47Z'},
 'url': '/title/tt0443680/'}