{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Network',
 'EntryURL': 'https://www.imdb.com/title/tt0074958',
 'Entry_json': 'Favorites/Movies/snapshot/Network/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Network/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Network/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Faye Dunaway',
            'url': '/name/nm0001159/'},
           {'@type': 'Person',
            'name': 'William Holden',
            'url': '/name/nm0000034/'},
           {'@type': 'Person',
            'name': 'Peter Finch',
            'url': '/name/nm0002075/'},
           {'@type': 'Person',
            'name': 'Robert Duvall',
            'url': '/name/nm0000380/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 139861,
                      'ratingValue': '8.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Paddy Chayefsky',
              'url': '/name/nm0154665/'},
             {'@type': 'Organization', 'url': '/company/co0007143/'}],
 'datePublished': '1976-11-27',
 'description': 'Network is a movie starring Faye Dunaway, William Holden, and '
                'Peter Finch. A television network cynically exploits a '
                "deranged former anchor's ravings and revelations about the "
                'news media for its own profit.',
 'director': [{'@type': 'Person',
               'name': 'Sidney Lumet',
               'url': '/name/nm0001486/'}],
 'duration': 'PT2H1M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BNmFiOWY3ZTktOTYwNy00ZTUzLTk0ODQtNzIxMzQ0ZDFjMTgyXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg',
 'keywords': 'media,television,television network,satire,ranting',
 'name': 'Network',
 'url': '/title/tt0074958/'}