{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-21',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hibernation',
 'EntryURL': 'https://www.imdb.com/title/tt0479926',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hibernation/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hibernation/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hibernation/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hibernation/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Adam Arnold',
            'url': '/name/nm2597055/'},
           {'@type': 'Person',
            'name': 'Sonny Rooney',
            'url': '/name/nm1060541/'},
           {'@type': 'Person',
            'name': 'Peter Reynolds',
            'url': '/name/nm2035474/'},
           {'@type': 'Person',
            'name': 'Adam Paroussos',
            'url': '/name/nm2055989/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 131,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'John Williams',
              'url': '/name/nm1084711/'},
             {'@type': 'Organization', 'url': '/company/co0104754/'},
             {'@type': 'Organization', 'url': '/company/co0159231/'}],
 'datePublished': '2005-08-14',
 'description': 'Hibernation is a short starring Adam Arnold, Sonny Rooney, '
                'and Peter Reynolds. 1985. A secret tree house. Two children '
                'dressed in animal costumes experiment to revive a bee. But '
                'they are searching for a way to bring back something...',
 'director': {'@type': 'Person',
              'name': 'John Williams',
              'url': '/name/nm1084711/'},
 'duration': 'PT15M',
 'genre': ['Short', 'Drama'],
 'name': 'Hibernation',
 'url': '/title/tt0479926/'}