{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Matchstick-Men',
 'EntryURL': 'https://www.imdb.com/title/tt0325805',
 'Entry_json': 'Favorites/Movies/snapshot/Matchstick-Men/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Matchstick-Men/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Matchstick-Men/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Nicolas Cage',
            'url': '/name/nm0000115/'},
           {'@type': 'Person',
            'name': 'Alison Lohman',
            'url': '/name/nm0517844/'},
           {'@type': 'Person',
            'name': 'Sam Rockwell',
            'url': '/name/nm0005377/'},
           {'@type': 'Person',
            'name': 'Bruce Altman',
            'url': '/name/nm0022883/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 121288,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Eric Garcia',
              'url': '/name/nm1201715/'},
             {'@type': 'Person',
              'name': 'Nicholas Griffin',
              'url': '/name/nm1206007/'},
             {'@type': 'Person',
              'name': 'Ted Griffin',
              'url': '/name/nm0341372/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0038131/'},
             {'@type': 'Organization', 'url': '/company/co0074212/'},
             {'@type': 'Organization', 'url': '/company/co0102305/'},
             {'@type': 'Organization', 'url': '/company/co0033633/'},
             {'@type': 'Organization', 'url': '/company/co0066003/'},
             {'@type': 'Organization', 'url': '/company/co0010750/'}],
 'datePublished': '2003-09-12',
 'description': 'Matchstick Men is a movie starring Nicolas Cage, Alison '
                'Lohman, and Sam Rockwell. A phobic con artist and his protégé '
                'are on the verge of pulling off a lucrative swindle when the '
                "former's teenage daughter arrives unexpectedly.",
 'director': [{'@type': 'Person',
               'name': 'Ridley Scott',
               'url': '/name/nm0000631/'}],
 'duration': 'PT1H56M',
 'genre': ['Comedy', 'Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA3NjMyNjIyMF5BMl5BanBnXkFtZTYwOTgzMDI3._V1_.jpg',
 'keywords': 'criminal,child,man wears a hospital gown,man wears '
             'eyeglasses,crying man',
 'name': 'Matchstick Men',
 'trailer': [{'@type': 'VideoObject',
              'description': 'hv-post',
              'embedUrl': '/video/imdb/vi3415539993',
              'name': 'Matchstick Men',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDU5ZDdlMTAtYjk1NS00NDgzLTgwNmItYWI5MTYwMzU0ODBlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDU5ZDdlMTAtYjk1NS00NDgzLTgwNmItYWI5MTYwMzU0ODBlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:59:03Z'}],
 'url': '/title/tt0325805/'}