{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/TV/snapshot/Space-Force',
 'EntryURL': 'https://www.imdb.com/title/tt9612516',
 'Entry_json': 'Favorites/TV/snapshot/Space-Force/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Space-Force/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Space-Force/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Steve Carell',
            'url': '/name/nm0136797/'},
           {'@type': 'Person',
            'name': 'John Malkovich',
            'url': '/name/nm0000518/'},
           {'@type': 'Person',
            'name': 'Ben Schwartz',
            'url': '/name/nm2355635/'},
           {'@type': 'Person',
            'name': 'Diana Silvers',
            'url': '/name/nm9537602/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 17809,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Steve Carell',
              'url': '/name/nm0136797/'},
             {'@type': 'Person',
              'name': 'Greg Daniels',
              'url': '/name/nm0199948/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2020-05-29',
 'description': 'Space Force is a TV series starring Steve Carell, John '
                'Malkovich, and Ben Schwartz. The people tasked with creating '
                'a sixth branch of the armed services: The Space Force.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BNWYwMzE2MGItOTYwYy00YmQyLWE0NGQtZWViMTU4ZTk4ZjQxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'space,america,china,rank,moon',
 'name': 'Space Force',
 'trailer': {'@type': 'VideoObject',
             'description': 'Space is...hard. A four-star general begrudgingly '
                            'teams up with an eccentric scientist to get the '
                            "U.S. military's newest agency — Space Force — "
                            'ready for lift-off.',
             'embedUrl': '/video/imdb/vi1875164697',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmRmZTE4NGEtZjlmNi00NmFlLTg1NTktMzA2Yzk4ZTkzM2I1XkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmRmZTE4NGEtZjlmNi00NmFlLTg1NTktMzA2Yzk4ZTkzM2I1XkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg',
             'uploadDate': '2020-05-19T14:25:16Z'},
 'url': '/title/tt9612516/'}