{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-07-11',
 'EntryPath': 'Favorites/TV/snapshot/Mr-Robot',
 'EntryURL': 'https://www.imdb.com/title/tt4158110',
 'Entry_json': 'Favorites/TV/snapshot/Mr-Robot/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Mr-Robot/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Mr-Robot/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Rami Malek', 'url': '/name/nm1785339/'},
           {'@type': 'Person',
            'name': 'Christian Slater',
            'url': '/name/nm0000225/'},
           {'@type': 'Person',
            'name': 'Carly Chaikin',
            'url': '/name/nm3361199/'},
           {'@type': 'Person',
            'name': 'Martin Wallström',
            'url': '/name/nm0909412/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 315036,
                      'ratingValue': '8.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Sam Esmail',
              'url': '/name/nm1322753/'},
             {'@type': 'Organization', 'url': '/company/co0017525/'},
             {'@type': 'Organization', 'url': '/company/co0641713/'},
             {'@type': 'Organization', 'url': '/company/co0242101/'}],
 'datePublished': '2015-06-24',
 'description': 'Mr. Robot is a TV series starring Rami Malek, Christian '
                'Slater, and Carly Chaikin. Elliot, a brilliant but highly '
                'unstable young cyber-security engineer and vigilante hacker, '
                'becomes a key figure in a complex game of global...',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzgxMmQxZjQtNDdmMC00MjRlLTk1MDEtZDcwNTdmOTg0YzA2XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
 'keywords': 'social anxiety disorder,anarchist,drug addict,split '
             'personality,paranoia',
 'name': 'Mr. Robot',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Season 4 will premiere Sunday, October 6 at '
                             '10/9c',
              'embedUrl': '/video/imdb/vi699842329',
              'name': 'Season 4 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTU4MzFiMDQtYTg2OS00NTJlLTg3ZDQtM2YwYTczYWM1ZDg4XkEyXkFqcGdeQWpnYW1i._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTU4MzFiMDQtYTg2OS00NTJlLTg3ZDQtM2YwYTczYWM1ZDg4XkEyXkFqcGdeQWpnYW1i._V1_.jpg',
              'uploadDate': '2019-08-27T20:11:20Z'}],
 'url': '/title/tt4158110/'}