{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air',
 'EntryURL': 'https://www.imdb.com/title/tt1193138',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'George Clooney',
            'url': '/name/nm0000123/'},
           {'@type': 'Person',
            'name': 'Vera Farmiga',
            'url': '/name/nm0267812/'},
           {'@type': 'Person',
            'name': 'Anna Kendrick',
            'url': '/name/nm0447695/'},
           {'@type': 'Person',
            'name': 'Jason Bateman',
            'url': '/name/nm0000867/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 311683,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Walter Kirn',
              'url': '/name/nm1174529/'},
             {'@type': 'Person',
              'name': 'Jason Reitman',
              'url': '/name/nm0718646/'},
             {'@type': 'Person',
              'name': 'Sheldon Turner',
              'url': '/name/nm1417242/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0199880/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0118469/'},
             {'@type': 'Organization', 'url': '/company/co0102305/'},
             {'@type': 'Organization', 'url': '/company/co0280848/'}],
 'datePublished': '2009-12-23',
 'description': 'Up in the Air is a movie starring George Clooney, Vera '
                'Farmiga, and Anna Kendrick. Ryan Bingham enjoys living out of '
                'a suitcase for his job, travelling around the country firing '
                'people, but finds that lifestyle threatened by the...',
 'director': {'@type': 'Person',
              'name': 'Jason Reitman',
              'url': '/name/nm0718646/'},
 'duration': 'PT1H49M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI3MzYxMTA4NF5BMl5BanBnXkFtZTcwMDE4ODg3Mg@@._V1_.jpg',
 'keywords': 'on the road,downsizing,travel,job termination,business trip',
 'name': 'Up in the Air',
 'trailer': {'@type': 'VideoObject',
             'description': 'Ryan Bingham is a corporate downsizing expert '
                            'whose cherished life on the road is threatened '
                            'just as he is on the cusp of reaching ten million '
                            "frequent flyer miles and just after he's met the "
                            'frequent-traveler woman of his dreams.',
             'embedUrl': '/video/imdb/vi3344040473',
             'name': 'Up in the Air: Trailer #2',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTk3ODI2NjM2Nl5BMl5BanBnXkFtZTgwODkzMTczMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTk3ODI2NjM2Nl5BMl5BanBnXkFtZTgwODkzMTczMzE@._V1_.jpg',
             'uploadDate': '2009-10-03T13:59:46Z'},
 'url': '/title/tt1193138/'}