{'Actors': ['Adam Rose',
            'Adhir Kalyan',
            'Alan David',
            'Amy Morton',
            'Anna Kendrick',
            'Arthur Hill',
            'Chris Lowell',
            'Chris Shaw',
            'Danny McBride',
            'George Clooney',
            'Grace Smith',
            'Greg Reynolds',
            'Jason Bateman',
            'Jeff Witzke',
            'JK Simmons',
            'Joe Hammerstone',
            'Lanette Fugit',
            'Lucas MacFadden',
            'Marvin Young',
            "Matt O'Toole",
            'Melanie Lynskey',
            'Morris Lee Sullivan',
            'Patricia Allison',
            'Sam Elliott',
            'Steve Eastin',
            'Tamala Jones',
            'Vera Farmiga',
            'Zach Galifianakis'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\n'
                'Up in the Air: Ryan Bingham is a corporate downsizing expert '
                'whose cherished life on the road is threatened just as he is '
                'on the cusp of reaching ten million frequent flyer miles and '
                "just after he's met the frequent-traveler woman of his "
                'dreams. ',
 'Director': ['Jason Reitman'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air',
 'EntryURL': 'https://www.imdb.com/title/tt1193138',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Up-in-the-Air/info.py',
 'Genres': ['Comedy', 'Drama', 'Romance'],
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': '83%',
             'PrimeWire': '3.69/5',
             'RT': '91%',
             'Votes': '773'},
 'Released': '2009-09-05',
 'Runtime': '109 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/24826_Up_in_the_Air_2009.jpg',
 'Title': 'Up-in-the-Air'}