{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-09-04',
 'EntryPath': 'Favorites/TV/snapshot/Penn-Teller-Bullshit',
 'EntryURL': 'https://www.imdb.com/title/tt0346369',
 'Entry_json': 'Favorites/TV/snapshot/Penn-Teller-Bullshit/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Penn-Teller-Bullshit/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Penn-Teller-Bullshit/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Penn Jillette',
            'url': '/name/nm0422710/'},
           {'@type': 'Person', 'name': 'Teller', 'url': '/name/nm0854418/'},
           {'@type': 'Person',
            'name': 'Shera Pollins',
            'url': '/name/nm7278501/'},
           {'@type': 'Person',
            'name': 'Gene Hatcher',
            'url': '/name/nm0368769/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 11337,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Randall Moldave',
              'url': '/name/nm0596462/'},
             {'@type': 'Person',
              'name': 'Eric Small',
              'url': '/name/nm0806450/'},
             {'@type': 'Organization', 'url': '/company/co0066107/'},
             {'@type': 'Organization', 'url': '/company/co0181096/'},
             {'@type': 'Organization', 'url': '/company/co0181234/'},
             {'@type': 'Organization', 'url': '/company/co0089381/'},
             {'@type': 'Organization', 'url': '/company/co0227855/'}],
 'datePublished': '2003-01-24',
 'description': 'Penn & Teller: Bullshit! is a TV series starring Penn '
                'Jillette, Teller, and Shera Pollins. The comedy illusionist '
                'duo explore various topics and debunk what they consider '
                'misconceptions about them.',
 'genre': ['Comedy', 'Documentary'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQxMDg0NTkzOV5BMl5BanBnXkFtZTcwNDUxNDcyMQ@@._V1_.jpg',
 'keywords': 'satire,libertarianism,propaganda,2000s,2010s',
 'name': 'Penn & Teller: Bullshit!',
 'trailer': {'@type': 'VideoObject',
             'description': 'Penn & Teller: Bullshit! Season 2',
             'embedUrl': '/video/imdb/vi1791409433',
             'name': 'Penn & Teller: Bullshit! Season 2',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTc2NGU3NzktZDQ0OS00MmZjLWI1NDctMWE5ZWEyZmJmNjk5XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTc2NGU3NzktZDQ0OS00MmZjLWI1NDctMWE5ZWEyZmJmNjk5XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-04-06T10:39:12Z'},
 'url': '/title/tt0346369/'}