{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Logans-Run',
 'EntryURL': 'https://www.imdb.com/title/tt0074812',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Logans-Run/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Logans-Run/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Logans-Run/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Michael York',
            'url': '/name/nm0001868/'},
           {'@type': 'Person',
            'name': 'Jenny Agutter',
            'url': '/name/nm0000256/'},
           {'@type': 'Person',
            'name': 'Richard Jordan',
            'url': '/name/nm0430151/'},
           {'@type': 'Person',
            'name': 'Roscoe Lee Browne',
            'url': '/name/nm0001975/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 50226,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'David Zelag Goodman',
              'url': '/name/nm0329051/'},
             {'@type': 'Person',
              'name': 'William F. Nolan',
              'url': '/name/nm0634368/'},
             {'@type': 'Person',
              'name': 'George Clayton Johnson',
              'url': '/name/nm0425138/'},
             {'@type': 'Organization', 'url': '/company/co0007143/'}],
 'datePublished': '1976-06-23',
 'description': "Logan's Run is a movie starring Michael York, Jenny Agutter, "
                'and Richard Jordan. An idyllic science fiction future has one '
                'major drawback: life must end at the age of thirty.',
 'director': {'@type': 'Person',
              'name': 'Michael Anderson',
              'url': '/name/nm0027183/'},
 'duration': 'PT1H59M',
 'genre': ['Action', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTEwNzUxMjMtOWIzOS00OTQ0LTk0MmQtMTIzYzJmNTVhYTI2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'cat,biosphere,dystopia,nursery,ageism',
 'name': "Logan's Run",
 'trailer': {'@type': 'VideoObject',
             'description': 'Official Trailer',
             'embedUrl': '/video/imdb/vi2257239833',
             'name': "Logan's Run",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMDBhOTIzNTUtOWZhMy00OWY3LTkwYjktOGM4MTAyYzZlYTk2XkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMDBhOTIzNTUtOWZhMy00OWY3LTkwYjktOGM4MTAyYzZlYTk2XkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
             'uploadDate': '2019-10-06T17:07:12Z'},
 'url': '/title/tt0074812/'}