{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/You',
 'EntryURL': 'https://www.imdb.com/title/tt7335184',
 'Entry_json': 'Favorites/TV/snapshot/You/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/You/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/You/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Penn Badgley',
            'url': '/name/nm0046112/'},
           {'@type': 'Person',
            'name': 'Ambyr Childers',
            'url': '/name/nm1024107/'},
           {'@type': 'Person',
            'name': 'Victoria Pedretti',
            'url': '/name/nm6442992/'},
           {'@type': 'Person',
            'name': 'Elizabeth Lail',
            'url': '/name/nm5634768/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 124188,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Sera Gamble',
              'url': '/name/nm1571148/'},
             {'@type': 'Person',
              'name': 'Greg Berlanti',
              'url': '/name/nm0075528/'},
             {'@type': 'Organization', 'url': '/company/co0467028/'},
             {'@type': 'Organization', 'url': '/company/co0142434/'},
             {'@type': 'Organization', 'url': '/company/co0330789/'},
             {'@type': 'Organization', 'url': '/company/co0183230/'}],
 'datePublished': '2018-09-09',
 'description': 'You is a TV series starring Penn Badgley, Ambyr Childers, and '
                'Victoria Pedretti. A dangerously charming, intensely '
                'obsessive young man goes to extreme measures to insert '
                'himself into the lives of those he is transfixed by.',
 'genre': ['Crime', 'Drama', 'Romance', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZDJjOTg4OWYtYWIyOS00MjQ3LTg5ZDktYzU2N2RkNmYzNjZlXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
 'keywords': 'bookstore,obsessive love,stalker,new york,obsession',
 'name': 'You',
 'trailer': [{'@type': 'VideoObject',
              'description': "Meet Will Bettelheim. He's not your regular Joe. "
                             "He's new to LA and has sworn off love. But love, "
                             'like murder, has a way of tracking you down.',
              'embedUrl': '/video/imdb/vi152878873',
              'name': 'Season 2 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMmM3MzkyNGItZWE0ZC00MzJhLTgxODItYTRhOTFlOTJmYzA4XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMmM3MzkyNGItZWE0ZC00MzJhLTgxODItYTRhOTFlOTJmYzA4XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-12-16T16:59:12Z'}],
 'url': '/title/tt7335184/'}