{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-07',
 'EntryPath': 'Favorites/Movies/snapshot/eXistenZ',
 'EntryURL': 'https://www.imdb.com/title/tt0120907',
 'Entry_json': 'Favorites/Movies/snapshot/eXistenZ/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/eXistenZ/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/eXistenZ/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jude Law', 'url': '/name/nm0000179/'},
           {'@type': 'Person',
            'name': 'Jennifer Jason Leigh',
            'url': '/name/nm0000492/'},
           {'@type': 'Person', 'name': 'Ian Holm', 'url': '/name/nm0000453/'},
           {'@type': 'Person',
            'name': 'Willem Dafoe',
            'url': '/name/nm0000353/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 91944,
                      'ratingValue': '6.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'David Cronenberg',
              'url': '/name/nm0000343/'},
             {'@type': 'Organization', 'url': '/company/co0019626/'},
             {'@type': 'Organization', 'url': '/company/co0054762/'},
             {'@type': 'Organization', 'url': '/company/co0012357/'},
             {'@type': 'Organization', 'url': '/company/co0100463/'},
             {'@type': 'Organization', 'url': '/company/co0016814/'},
             {'@type': 'Organization', 'url': '/company/co0130269/'},
             {'@type': 'Organization', 'url': '/company/co0043355/'},
             {'@type': 'Organization', 'url': '/company/co0053578/'},
             {'@type': 'Organization', 'url': '/company/co0069524/'}],
 'datePublished': '1999-04-14',
 'description': 'eXistenZ is a movie starring Jude Law, Jennifer Jason Leigh, '
                'and Ian Holm. A game designer on the run from assassins must '
                'play her latest virtual reality creation with a marketing '
                'trainee to determine if the game has been damaged.',
 'director': [{'@type': 'Person',
               'name': 'David Cronenberg',
               'url': '/name/nm0000343/'}],
 'duration': 'PT1H37M',
 'genre': ['Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMmU1MTJkYWItMzM5Ny00NDgxLTgxOGEtNTkzNDdkZjkwNGI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
 'keywords': 'game,alternate reality,game designer,body horror,parallel world',
 'name': 'eXistenZ',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for eXistenZ',
              'embedUrl': '/video/imdb/vi27656473',
              'name': 'eXistenZ',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMDc2NjZjZDctNmY2ZS00N2M4LTg0OTctNTE5ZTc1YzJiZjFjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMDc2NjZjZDctNmY2ZS00N2M4LTg0OTctNTE5ZTc1YzJiZjFjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:03:21Z'}],
 'url': '/title/tt0120907/'}