{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Alien',
 'EntryURL': 'https://www.imdb.com/title/tt0078748',
 'Entry_json': 'Favorites/Movies/snapshot/Alien/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Alien/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Alien/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sigourney Weaver',
            'url': '/name/nm0000244/'},
           {'@type': 'Person',
            'name': 'Tom Skerritt',
            'url': '/name/nm0000643/'},
           {'@type': 'Person', 'name': 'John Hurt', 'url': '/name/nm0000457/'},
           {'@type': 'Person',
            'name': 'Veronica Cartwright',
            'url': '/name/nm0001021/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 758534,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': "Dan O'Bannon",
              'url': '/name/nm0639321/'},
             {'@type': 'Person',
              'name': "Dan O'Bannon",
              'url': '/name/nm0639321/'},
             {'@type': 'Person',
              'name': 'Ronald Shusett',
              'url': '/name/nm0795953/'},
             {'@type': 'Organization', 'url': '/company/co0132161/'}],
 'datePublished': '1979-05-28',
 'description': 'Alien is a movie starring Sigourney Weaver, Tom Skerritt, and '
                'John Hurt. After a space merchant vessel receives an unknown '
                'transmission as a distress call, one of the crew is attacked '
                'by a mysterious life form and they soon realize...',
 'director': {'@type': 'Person',
              'name': 'Ridley Scott',
              'url': '/name/nm0000631/'},
 'duration': 'PT1H57M',
 'genre': ['Horror', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMmQ2MmU3NzktZjAxOC00ZDZhLTk4YzEtMDMyMzcxY2IwMDAyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'alien,spaceship,outer space,creature,female protagonist',
 'name': 'Alien',
 'trailer': {'@type': 'VideoObject',
             'description': 'A mining ship, investigating a suspected SOS, '
                            'lands on a distant planet. The crew discovers '
                            'some strange creatures and investigates.',
             'embedUrl': '/video/imdb/vi1497801241',
             'name': 'Theatrical Version',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTc4OTYzNjc2MV5BMl5BanBnXkFtZTgwNDA2MzIzMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTc4OTYzNjc2MV5BMl5BanBnXkFtZTgwNDA2MzIzMzE@._V1_.jpg',
             'uploadDate': '2012-06-22T10:09:58Z'},
 'url': '/title/tt0078748/'}