{'Actors': ['Eddie Powell',
            'Harry Dean Stanton',
            'Helen Horton',
            'Ian Holm',
            'John Hurt',
            'Sigourney Weaver',
            'Tom Skerritt',
            'Veronica Cartwright',
            'Yaphet Kotto'],
 'Added': '2013-02-23',
 'Countries': ['USA', 'UK'],
 'Description': '\n'
                'Alien: A mining ship, investigating a suspected SOS, lands on '
                'a distant planet. The crew discovers some strange creatures '
                'and investigates. ',
 'Director': ['Ridley Scott'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Alien',
 'EntryURL': 'https://www.imdb.com/title/tt0078748',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Alien/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Alien/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Alien/info.py',
 'Genres': ['Thriller', 'Sci-Fi', 'Horror'],
 'IMDB': 'http://www.imdb.com/title/tt0078748',
 'PrimeWire': 'http://www.primewire.ag/watch-873-Alien',
 'Ratings': {'IMDB': '8.5/10',
             'Metascore': '83%',
             'PrimeWire': '4.35/5',
             'RT': '97%',
             'Votes': '896'},
 'Released': '1979-05-25',
 'Runtime': '117 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/873_Alien_1979.jpg',
 'Title': 'Alien'}