{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Soloist',
 'EntryURL': 'https://www.imdb.com/title/tt0821642',
 'Entry_json': 'Favorites/Movies/snapshot/The-Soloist/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Soloist/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Soloist/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jamie Foxx', 'url': '/name/nm0004937/'},
           {'@type': 'Person',
            'name': 'Robert Downey Jr.',
            'url': '/name/nm0000375/'},
           {'@type': 'Person',
            'name': 'Catherine Keener',
            'url': '/name/nm0001416/'},
           {'@type': 'Person',
            'name': 'Tom Hollander',
            'url': '/name/nm0390903/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 50425,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Susannah Grant',
              'url': '/name/nm0335666/'},
             {'@type': 'Person',
              'name': 'Steve Lopez',
              'url': '/name/nm2311134/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0047476/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'},
             {'@type': 'Organization', 'url': '/company/co0174525/'},
             {'@type': 'Organization', 'url': '/company/co0057311/'}],
 'datePublished': '2009-04-24',
 'description': 'The Soloist is a movie starring Jamie Foxx, Robert Downey '
                'Jr., and Catherine Keener. A newspaper journalist discovers a '
                'homeless musical genius and tries to improve his situation.',
 'director': {'@type': 'Person',
              'name': 'Joe Wright',
              'url': '/name/nm0942504/'},
 'duration': 'PT1H57M',
 'genre': ['Biography', 'Drama', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjExODQ3MTI5Nl5BMl5BanBnXkFtZTcwMDEyMTQ5MQ@@._V1_.jpg',
 'keywords': 'wearing a traffic cone as a hat,reference to jascha '
             'heifetz,schizophrenia,juilliard school,facial injury',
 'name': 'The Soloist',
 'trailer': {'@type': 'VideoObject',
             'description': 'This is the theatrical trailer for The Soloist, '
                            'directed by Joe Wright and starring Jamie Foxx '
                            'and Robert Downey Jr.',
             'embedUrl': '/video/imdb/vi3497984025',
             'name': 'The Soloist: Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjE3MjE3MzA1OV5BMl5BanBnXkFtZTgwODg4MTMyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjE3MjE3MzA1OV5BMl5BanBnXkFtZTgwODg4MTMyMzE@._V1_.jpg',
             'uploadDate': '2008-10-16T12:52:44Z'},
 'url': '/title/tt0821642/'}