{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/21-Grams',
 'EntryURL': 'https://www.imdb.com/title/tt0315733',
 'Entry_json': 'Favorites/Movies/snapshot/21-Grams/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/21-Grams/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/21-Grams/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Sean Penn', 'url': '/name/nm0000576/'},
           {'@type': 'Person',
            'name': 'Benicio Del Toro',
            'url': '/name/nm0001125/'},
           {'@type': 'Person',
            'name': 'Naomi Watts',
            'url': '/name/nm0915208/'},
           {'@type': 'Person',
            'name': 'Danny Huston',
            'url': '/name/nm0396812/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 220824,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Guillermo Arriaga',
              'url': '/name/nm0037247/'},
             {'@type': 'Organization', 'url': '/company/co0017713/'},
             {'@type': 'Organization', 'url': '/company/co0109101/'},
             {'@type': 'Organization', 'url': '/company/co0175682/'}],
 'datePublished': '2003-11-19',
 'description': '21 Grams is a movie starring Sean Penn, Benicio Del Toro, and '
                'Naomi Watts. A freak accident brings together a critically '
                'ill mathematician, a grieving mother, and a born-again '
                'ex-con.',
 'director': [{'@type': 'Person',
               'name': 'Alejandro G. Iñárritu',
               'url': '/name/nm0327944/'}],
 'duration': 'PT2H4M',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA4MjI2OTM5N15BMl5BanBnXkFtZTcwNDA1NjUzMw@@._V1_.jpg',
 'keywords': 'sex in bed,breasts,unfaithfulness,extramarital affair,female '
             'nudity',
 'name': '21 Grams',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer',
              'embedUrl': '/video/imdb/vi3383951641',
              'name': '21 Grams',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYzRkMjI3N2YtZTdjZi00YzM3LTg4MDAtOGFhOTA5ZDE1NWMxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYzRkMjI3N2YtZTdjZi00YzM3LTg4MDAtOGFhOTA5ZDE1NWMxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T02:56:31Z'}],
 'url': '/title/tt0315733/'}