{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-09-14',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Show-with-Stephen-Colbert',
 'EntryURL': 'https://www.imdb.com/title/tt3697842',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Show-with-Stephen-Colbert/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Show-with-Stephen-Colbert/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Show-with-Stephen-Colbert/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Stephen Colbert',
            'url': '/name/nm0170306/'},
           {'@type': 'Person',
            'name': 'Jonathan Batiste',
            'url': '/name/nm4456022/'},
           {'@type': 'Person', 'name': 'Stay Human', 'url': '/name/nm7575542/'},
           {'@type': 'Person',
            'name': 'Brian Stack',
            'url': '/name/nm0821026/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 11068,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Organization', 'url': '/company/co0239595/'},
             {'@type': 'Organization', 'url': '/company/co0274041/'}],
 'datePublished': '2015-09-08',
 'description': 'The Late Show with Stephen Colbert is a TV series starring '
                'Stephen Colbert, Jonathan Batiste, and Stay Human. Stephen '
                'Colbert took over as host, executive producer and writer of '
                'THE LATE SHOW on Tuesday, Sept. 8, 2015. The...',
 'genre': ['Comedy', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOWU2MDU1ZjEtMDFhZC00NDQ4LTg5NzQtYjQ0Njg2NWI0MDI4XkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg',
 'keywords': 'six word series title,actor name in series title,2020s,woke,anti '
             'trump media',
 'name': 'The Late Show with Stephen Colbert',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'shawcarvetht'},
            'dateCreated': '2019-01-02',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt3697842/'},
            'name': 'Good snippets on YouTube.',
            'reviewBody': 'I watch the 5-10 mins of monologues that get posted '
                          'to YouTube regularly and love many of them. Always '
                          'looking forward to the next one. Stephen is brill. '
                          "I don't engage with the rest of the show - the "
                          'music and interviews. Good stuff',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '8',
                             'worstRating': '1'}},
 'url': '/title/tt3697842/'}