{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Red-Dead-Redemption',
 'EntryURL': 'https://rawg.io/games/red-dead-redemption',
 'Entry_json': 'Favorites/Games/snapshot/Red-Dead-Redemption/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Red-Dead-Redemption/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Red-Dead-Redemption/thumb.jpg',
 'added': 4573,
 'background_image': 'https://media.rawg.io/media/games/686/686909717c3aa01518bc42ae2bf4259e.jpg',
 'developers': ['Rockstar Games', 'Rockstar North', 'Rockstar San Diego'],
 'genres': ['Action', 'Shooter'],
 'name': 'Red Dead Redemption',
 'platforms': ['PlayStation 3', 'Xbox 360'],
 'publishers': ['Rockstar Games'],
 'released': '2010-05-18',
 'slug': 'red-dead-redemption'}