{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Children-of-Men',
 'EntryURL': 'https://www.imdb.com/title/tt0206634',
 'Entry_json': 'Favorites/Movies/snapshot/Children-of-Men/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Children-of-Men/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Children-of-Men/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Julianne Moore',
            'url': '/name/nm0000194/'},
           {'@type': 'Person', 'name': 'Clive Owen', 'url': '/name/nm0654110/'},
           {'@type': 'Person',
            'name': 'Chiwetel Ejiofor',
            'url': '/name/nm0252230/'},
           {'@type': 'Person',
            'name': 'Michael Caine',
            'url': '/name/nm0000323/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 454373,
                      'ratingValue': '7.9',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alfonso Cuarón',
              'url': '/name/nm0190859/'},
             {'@type': 'Person',
              'name': 'Timothy J. Sexton',
              'url': '/name/nm0786694/'},
             {'@type': 'Person',
              'name': 'David Arata',
              'url': '/name/nm0033153/'},
             {'@type': 'Person',
              'name': 'Mark Fergus',
              'url': '/name/nm1318843/'},
             {'@type': 'Person',
              'name': 'Hawk Ostby',
              'url': '/name/nm1319757/'},
             {'@type': 'Person',
              'name': 'P.D. James',
              'url': '/name/nm0416807/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0086710/'},
             {'@type': 'Organization', 'url': '/company/co0011026/'},
             {'@type': 'Organization', 'url': '/company/co0612222/'},
             {'@type': 'Organization', 'url': '/company/co0064457/'}],
 'datePublished': '2006-09-22',
 'description': 'Children of Men is a movie starring Julianne Moore, Clive '
                'Owen, and Chiwetel Ejiofor. In 2027, in a chaotic world in '
                'which women have become somehow infertile, a former activist '
                'agrees to help transport a miraculously pregnant woman...',
 'director': [{'@type': 'Person',
               'name': 'Alfonso Cuarón',
               'url': '/name/nm0190859/'}],
 'duration': 'PT1H49M',
 'genre': ['Adventure', 'Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ5NTI2NTI4NF5BMl5BanBnXkFtZTcwNjk2NDA2OQ@@._V1_.jpg',
 'keywords': 'long take,england,fertility,neo noir,allegory',
 'name': 'Children of Men',
 'url': '/title/tt0206634/'}