{'Actors': ['Dana Snyder&tv'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                'Code Monkeys: Two game developers try to survive their crazy '
                'Texas billionaire boss and his rich prissy son in 1983. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Code-Monkeys',
 'EntryURL': 'http://www.imdb.com/title/tt1068683',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Code-Monkeys/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Code-Monkeys/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Code-Monkeys/info.py',
 'Genres': ['Animation&tv', 'Comedy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt1068683',
 'PrimeWire': 'http://www.primewire.ag/tv-9807-Code-Monkeys',
 'Ratings': {'IMDB': '7.0/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.85/5',
             'RT': 'N/A',
             'Votes': '33'},
 'Released': '2007-07-11',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/9807_Code_Monkeys_2007.jpg',
 'Title': 'Code-Monkeys'}