{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/TV/snapshot/Code-Monkeys',
 'EntryURL': 'https://www.imdb.com/title/tt1068683',
 'Entry_json': 'Favorites/TV/snapshot/Code-Monkeys/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Code-Monkeys/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Code-Monkeys/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Adam De La Peña',
            'url': '/name/nm1089476/'},
           {'@type': 'Person', 'name': 'Andy Sipes', 'url': '/name/nm1558405/'},
           {'@type': 'Person',
            'name': 'Matt Mariska',
            'url': '/name/nm0963023/'},
           {'@type': 'Person',
            'name': 'Gretchen McNeil',
            'url': '/name/nm2217792/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2605,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Adam De La Peña',
              'url': '/name/nm1089476/'},
             {'@type': 'Organization', 'url': '/company/co0215053/'}],
 'datePublished': '2007-07-11',
 'description': 'Code Monkeys is a TV series starring Adam De La Peña, Andy '
                'Sipes, and Matt Mariska. Two game developers try to survive '
                'their crazy Texas billionaire boss and his rich prissy son in '
                '1983.',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM4NTU3ODY2M15BMl5BanBnXkFtZTcwODUzMTE4MQ@@._V1_.jpg',
 'keywords': 'game',
 'name': 'Code Monkeys',
 'trailer': {'@type': 'VideoObject',
             'description': 'Code Monkeys: Season One',
             'embedUrl': '/video/imdb/vi3296902425',
             'name': 'Code Monkeys: Season One',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYWMwYmNmYjEtY2U4OC00MDdhLWFmYTctZjc5MWQ4MTA5ODMzXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYWMwYmNmYjEtY2U4OC00MDdhLWFmYTctZjc5MWQ4MTA5ODMzXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-03-18T00:09:32Z'},
 'url': '/title/tt1068683/'}