{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Horror-Story',
 'EntryURL': 'https://www.imdb.com/title/tt1844624',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Horror-Story/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Horror-Story/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/American-Horror-Story/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Lady Gaga', 'url': '/name/nm3078932/'},
           {'@type': 'Person',
            'name': 'Kathy Bates',
            'url': '/name/nm0000870/'},
           {'@type': 'Person',
            'name': 'Angela Bassett',
            'url': '/name/nm0000291/'},
           {'@type': 'Person',
            'name': 'Sarah Paulson',
            'url': '/name/nm0005299/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 265985,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Brad Falchuk',
              'url': '/name/nm1004299/'},
             {'@type': 'Person',
              'name': 'Ryan Murphy',
              'url': '/name/nm0614682/'},
             {'@type': 'Organization', 'url': '/company/co0060381/'},
             {'@type': 'Organization', 'url': '/company/co0314634/'},
             {'@type': 'Organization', 'url': '/company/co0156994/'},
             {'@type': 'Organization', 'url': '/company/co0056447/'}],
 'datePublished': '2011-10-05',
 'description': 'American Horror Story is a TV series starring Lady Gaga, '
                'Kathy Bates, and Angela Bassett. An anthology series '
                'centering on different characters and locations, including a '
                'house with a murderous past, an insane asylum, a witch '
                'coven,...',
 'genre': ['Drama', 'Horror', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODZlYzc2ODYtYmQyZS00ZTM4LTk4ZDQtMTMyZDdhMDgzZTU0XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
 'keywords': 'anthology,serial killer,male objectification,supernatural,hotel',
 'name': 'American Horror Story',
 'trailer': {'@type': 'VideoObject',
             'description': 'The ninth season of "American Horror Story" '
                            'travels back to 1984 to celebrate slasher genre.',
             'embedUrl': '/video/imdb/vi3484729113',
             'name': '"AHS: 1984" Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYTc4NWU3YmEtODc5NC00NGRjLWEyYjUtNTcwMTk0YWQyMTVkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYTc4NWU3YmEtODc5NC00NGRjLWEyYjUtNTcwMTk0YWQyMTVkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-08-26T19:19:55Z'},
 'url': '/title/tt1844624/'}