{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Chrono-Trigger-1995',
 'EntryURL': 'https://rawg.io/games/chrono-trigger-1995',
 'Entry_json': 'Favorites/Games/snapshot/Chrono-Trigger-1995/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Chrono-Trigger-1995/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Chrono-Trigger-1995/thumb.jpg',
 'added': 525,
 'background_image': 'https://media.rawg.io/media/games/ae4/ae404f4e0f504131199703c09111bb78.jpg',
 'developers': ['Sony Interactive Entertainment', 'Square Enix', 'Square'],
 'genres': ['RPG'],
 'name': 'Chrono Trigger',
 'platforms': ['SNES',
               'PSP',
               'PlayStation 3',
               'PlayStation',
               'Android',
               'PS Vita',
               'PC',
               'iOS',
               'Nintendo DS',
               'Wii'],
 'publishers': ['Square Enix', 'Square'],
 'released': '1995-03-11',
 'slug': 'chrono-trigger-1995'}