{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-21',
 'EntryPath': 'Favorites/Movies/snapshot/The-Great-Martian-War',
 'EntryURL': 'https://www.imdb.com/title/tt3199240',
 'Entry_json': 'Favorites/Movies/snapshot/The-Great-Martian-War/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Great-Martian-War/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Great-Martian-War/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Mark Strong',
            'url': '/name/nm0835016/'},
           {'@type': 'Person',
            'name': 'Jock McLeod',
            'url': '/name/nm1853140/'},
           {'@type': 'Person',
            'name': 'Joan Gregson',
            'url': '/name/nm0339991/'},
           {'@type': 'Person',
            'name': 'Ian Downie',
            'url': '/name/nm0236060/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 395,
                      'ratingValue': '6.9',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Steve Maher',
              'url': '/name/nm1610272/'},
             {'@type': 'Person',
              'name': 'Stephen Sarossy',
              'url': '/name/nm2596568/'},
             {'@type': 'Organization', 'url': '/company/co0212327/'},
             {'@type': 'Organization', 'url': '/company/co0111305/'}],
 'datePublished': '2013-12-08',
 'description': 'The Great Martian War 1913 - 1917 is a TV movie starring Mark '
                'Strong, Jock McLeod, and Joan Gregson. Documentary-drama '
                'recounting the Martian War of 1913 - 1917. Europe was on '
                'tenterhooks in the 2nd decade of the 20th century,...',
 'director': [{'@type': 'Person',
               'name': 'Mike Slee',
               'url': '/name/nm0805690/'}],
 'duration': 'PT1H30M',
 'genre': ['Drama', 'Sci-Fi', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2U2NzM4MWItNmI5Ni00Y2FiLTk2ZDEtYWNiYTVlM2MzY2E2XkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_.jpg',
 'keywords': 'martian,tripod,alien invasion,1910s,fictional war',
 'name': 'The Great Martian War 1913 - 1917',
 'url': '/title/tt3199240/'}