<?php
$infoArray = array('Actors' => array('Chris Cooper&tv',
            'James Franco&tv',
            'Josh Duhamel&tv',
            'Lucy Fry&tv'),
 'Added' => '2016-02-16',
 'Countries' => array('USA'),
 'Description' => "\n112263: High school teacher Jake Epping travels back in time to prevent the assassination of President John F. Kennedy - but his mission is threatened by Lee Harvey Oswald, falling in love, and the past itself, which doesn't want to be changed. ",
 'Director' => array('NA'),
 'Genres' => array('Drama&tv', 'Sci-Fi&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt2879552',
 'PrimeWire' => 'http://www.primewire.ag/tv-2774063-112263',
 'Ratings' => array('IMDB' => 'N/A',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.38/5',
             'RT' => 'N/A',
             'Votes' => '504'),
 'Released' => '2016-02-15',
 'Runtime' => '81 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2774063_112263_2016_19.jpg',
 'Title' => '112263');
?>