{'Actors': ['Amy Huck',
            'Andrea Miltner',
            'David Fisher',
            'Diedrich Bader',
            'Dominic Raacke',
            'Ellen Savaria',
            'Fred Armisen',
            'Jacob Pitts',
            'Jakub Koh&#xE1;k',
            'Jan Nemejovsky',
            'Jana Pallaske',
            'Jeff Smith',
            'Jeffrey Tambor',
            'Joanna Lumley',
            'Joel Kirby',
            'John Comer',
            'JP Manoux',
            'Kristin Kreuk',
            'Lucy Lawless',
            'Matt Damon',
            'Michael Cella',
            'Michelle Trachtenberg',
            'Mindy Sterling',
            'Miroslav T&#xE1;borsk&#xFD;',
            'Nick Jameson',
            'Pat Kilbane',
            'Patrick Malahide',
            'Patrick Rapold',
            'Paul Oldham',
            'Petr J&#xE1;kl',
            'Predrag Bjelac',
            'Rade Serbedzija',
            'Steve Hytner',
            'Travis Wester',
            'Vinnie Jones',
            'Vitezslav Bouchner',
            'Walter Sittler'],
 'Added': '2013-02-20',
 'Countries': ['USA'],
 'Description': '\n'
                'EuroTrip: Dumped by his girlfriend, a high school grad '
                'decides to embark on an overseas adventure in Europe with his '
                'friends. ',
 'Director': ['Jeff Schaffer'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//EuroTrip',
 'EntryURL': 'https://www.imdb.com/title/tt0356150',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//EuroTrip/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//EuroTrip/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//EuroTrip/info.py',
 'Genres': ['Comedy', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0356150',
 'PrimeWire': 'http://www.primewire.ag/watch-2021-EuroTrip',
 'Ratings': {'IMDB': '6.6/10',
             'Metascore': '45%',
             'PrimeWire': '4.21/5',
             'RT': 'N/A',
             'Votes': '788'},
 'Released': '2004-02-20',
 'Runtime': '93 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2021_EuroTrip_2004.jpg',
 'Title': 'EuroTrip'}