{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-20',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/EuroTrip',
 'EntryURL': 'https://www.imdb.com/title/tt0356150',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/EuroTrip/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/EuroTrip/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/EuroTrip/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Scott Mechlowicz',
            'url': '/name/nm1310709/'},
           {'@type': 'Person',
            'name': 'Jacob Pitts',
            'url': '/name/nm0686009/'},
           {'@type': 'Person',
            'name': 'Michelle Trachtenberg',
            'url': '/name/nm0005502/'},
           {'@type': 'Person',
            'name': 'Travis Wester',
            'url': '/name/nm0922563/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 189627,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alec Berg',
              'url': '/name/nm0073688/'},
             {'@type': 'Person',
              'name': 'David Mandel',
              'url': '/name/nm0541635/'},
             {'@type': 'Person',
              'name': 'Jeff Schaffer',
              'url': '/name/nm0769840/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0118469/'},
             {'@type': 'Organization', 'url': '/company/co0098163/'}],
 'datePublished': '2004-02-20',
 'description': 'EuroTrip is a movie starring Scott Mechlowicz, Jacob Pitts, '
                'and Michelle Trachtenberg. Dumped by his girlfriend, a high '
                'school grad decides to embark on an overseas adventure in '
                'Europe with his friends.',
 'director': [{'@type': 'Person',
               'name': 'Jeff Schaffer',
               'url': '/name/nm0769840/'},
              {'@type': 'Person',
               'name': 'Alec Berg',
               'url': '/name/nm0073688/'},
              {'@type': 'Person',
               'name': 'David Mandel',
               'url': '/name/nm0541635/'}],
 'duration': 'PT1H32M',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTIxNjcxMDUxN15BMl5BanBnXkFtZTYwNjAxNTM3._V1_.jpg',
 'keywords': 'public nudity,nudist,nudity,incestuous kiss,female frontal '
             'nudity',
 'name': 'EuroTrip',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for EuroTrip',
             'embedUrl': '/video/imdb/vi2946826521',
             'name': 'EuroTrip',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2NjM2IwNGMtZTIzYS00NWIxLWI3NTEtZjc4ZmM4NTcxMzJlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2NjM2IwNGMtZTIzYS00NWIxLWI3NTEtZjc4ZmM4NTcxMzJlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:02:13Z'},
 'url': '/title/tt0356150/'}