{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-02-21',
 'EntryPath': 'Favorites/Movies/snapshot/Donald-Trumps-The-Art-of-the-Deal-The-Movie',
 'EntryURL': 'https://www.imdb.com/title/tt5456120',
 'Entry_json': 'Favorites/Movies/snapshot/Donald-Trumps-The-Art-of-the-Deal-The-Movie/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Donald-Trumps-The-Art-of-the-Deal-The-Movie/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Donald-Trumps-The-Art-of-the-Deal-The-Movie/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Johnny Depp',
            'url': '/name/nm0000136/'},
           {'@type': 'Person', 'name': 'Ron Howard', 'url': '/name/nm0000165/'},
           {'@type': 'Person',
            'name': 'Alfred Molina',
            'url': '/name/nm0000547/'},
           {'@type': 'Person',
            'name': 'Robert Morse',
            'url': '/name/nm0607666/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3701,
                      'ratingValue': '5.8',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Joe Randazzo',
              'url': '/name/nm4758452/'},
             {'@type': 'Organization', 'url': '/company/co0215655/'}],
 'datePublished': '2016-02-10',
 'description': "Donald Trump's The Art of the Deal: The Movie is a TV movie "
                'starring Johnny Depp, Ron Howard, and Alfred Molina. Funny or '
                "Die presents a satirical rendition of Donald Trump's 1987 "
                'best selling business book, The Art of the Deal.',
 'director': [{'@type': 'Person',
               'name': 'Jeremy Konner',
               'url': '/name/nm1225956/'}],
 'duration': 'PT50M',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BODcyNTk1ZGYtYzcwYy00Y2FiLTk4MjQtNmRlZmMyYWY1NzBkXkEyXkFqcGdeQXVyMjU3NDQ3MDg@._V1_.jpg',
 'keywords': 'elite,new york city,real estate,nazi salute,donald trump '
             'character',
 'name': "Donald Trump's The Art of the Deal: The Movie",
 'url': '/title/tt5456120/'}