{'Actors': [],
 'Added': '2012-12-02',
 'Countries': ['Australia'],
 'Description': '\nGrand Designs Australia: The series charts the in-depth process of elaborate design projects undertaken by self-builders - from the initial details of blueprints, to the long and often arduous task of turning the designs into a practical living space. ',
 'Director': ['NA'],
 'Genres': ['Documentary&tv', 'Reality-TV&tv'],
 'IMDB': 'http://www.imdb.com/title/tt1677691',
 'PrimeWire': 'http://www.primewire.ag/tv-2736292-Grand-Designs-Australia',
 'Ratings': {'IMDB': '8.0/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.09/5',
             'RT': 'N/A',
             'Votes': '11'},
 'Released': '2010-10-21',
 'Runtime': '50 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2736292_Grand_Designs_Australia.jpg',
 'Title': 'Grand-Designs-Australia'}