{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/South-Park-The-Fractured-But-Whole',
 'EntryURL': 'https://rawg.io/games/south-park-the-fractured-but-whole',
 'Entry_json': 'Favorites/Games/snapshot/South-Park-The-Fractured-But-Whole/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/South-Park-The-Fractured-But-Whole/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/South-Park-The-Fractured-But-Whole/thumb.jpg',
 'added': 1900,
 'background_image': 'https://media.rawg.io/media/games/63c/63cb04333dea1726e90b38dc3d10258f.jpg',
 'developers': ['Ubisoft San Francisco'],
 'genres': ['Adventure', 'RPG'],
 'name': 'South Park: The Fractured but Whole',
 'platforms': ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
 'publishers': ['Ubisoft Entertainment'],
 'released': '2017-03-31',
 'slug': 'south-park-the-fractured-but-whole'}