{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Santa-Clarita-Diet',
 'EntryURL': 'https://www.imdb.com/title/tt5580540',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Santa-Clarita-Diet/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Santa-Clarita-Diet/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Santa-Clarita-Diet/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Drew Barrymore',
            'url': '/name/nm0000106/'},
           {'@type': 'Person',
            'name': 'Timothy Olyphant',
            'url': '/name/nm0648249/'},
           {'@type': 'Person', 'name': 'Liv Hewson', 'url': '/name/nm5735148/'},
           {'@type': 'Person',
            'name': 'Skyler Gisondo',
            'url': '/name/nm1711114/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 53371,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Victor Fresco',
              'url': '/name/nm0294355/'},
             {'@type': 'Organization', 'url': '/company/co0071857/'},
             {'@type': 'Organization', 'url': '/company/co0483718/'},
             {'@type': 'Organization', 'url': '/company/co0275279/'},
             {'@type': 'Organization', 'url': '/company/co0148520/'},
             {'@type': 'Organization', 'url': '/company/co0627592/'}],
 'datePublished': '2017-02-03',
 'description': 'Santa Clarita Diet is a TV series starring Drew Barrymore, '
                'Timothy Olyphant, and Liv Hewson. Sheila and Joel are married '
                'real estate agents in Santa Clarita, California. When Sheila '
                'dies, their lives take a dark turn.',
 'genre': ['Comedy', 'Horror'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTIwMDkzNTMwMF5BMl5BanBnXkFtZTgwNDA4MjI2NzM@._V1_.jpg',
 'keywords': 'real estate,california,santa clarita california,dead body,family '
             'relationships',
 'name': 'Santa Clarita Diet',
 'trailer': {'@type': 'VideoObject',
             'description': 'True love never dies? "Santa Clarita Diet" Season '
                            '3 is coming March 29.',
             'embedUrl': '/video/imdb/vi4031429145',
             'name': 'Season 3 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2Y4NjFhMDUtNWQyYS00ZjFjLTlkYTYtZDU0ZTZjNTI2OTIyXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2Y4NjFhMDUtNWQyYS00ZjFjLTlkYTYtZDU0ZTZjNTI2OTIyXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-03-11T20:04:11Z'},
 'url': '/title/tt5580540/'}