{'@context': 'http://schema.org',
 '@type': 'CreativeWork',
 'EntryAdded': '2013-08-26',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Grounded-The-Making-of-The-Last-Of-Us',
 'EntryURL': 'https://www.imdb.com/title/tt3397502',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Grounded-The-Making-of-The-Last-Of-Us/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Grounded-The-Making-of-The-Last-Of-Us/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Grounded-The-Making-of-The-Last-Of-Us/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Christophe Balestra',
            'url': '/name/nm3914215/'},
           {'@type': 'Person',
            'name': 'Jacob Minkoff',
            'url': '/name/nm6320860/'},
           {'@type': 'Person',
            'name': 'Anthony Newman',
            'url': '/name/nm6320861/'},
           {'@type': 'Person',
            'name': 'Ricky Cambier',
            'url': '/name/nm6320862/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 572,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': {'@type': 'Organization', 'url': '/company/co0459801/'},
 'datePublished': '2013-06-14',
 'description': 'Grounded: Making the Last of Us is a video starring '
                'Christophe Balestra, Jacob Minkoff, and Anthony Newman. Go '
                'behind-the-scenes to learn about the dogged development and '
                'unique philosophy at work in the making of the universally...',
 'director': [{'@type': 'Person',
               'name': 'Jason Bertrand',
               'url': '/name/nm6154799/'},
              {'@type': 'Person',
               'name': 'Matt Chandronait',
               'url': '/name/nm6154801/'},
              {'@type': 'Person',
               'name': 'Jeffrey Keith Negus',
               'url': '/name/nm2554980/'},
              {'@type': 'Person',
               'name': "Ryan O'Donnell",
               'url': '/name/nm6154795/'},
              {'@type': 'Person',
               'name': 'Cesar Quintero',
               'url': '/name/nm4249006/'}],
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjM4NTcwMzMwMV5BMl5BanBnXkFtZTgwMzQ1NjAzMTE@._V1_.jpg',
 'name': 'Grounded: Making the Last of Us',
 'url': '/title/tt3397502/'}