{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-02-11',
 'EntryPath': 'Favorites/TV/snapshot/Better-Call-Saul',
 'EntryURL': 'https://www.imdb.com/title/tt3032476',
 'Entry_json': 'Favorites/TV/snapshot/Better-Call-Saul/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Better-Call-Saul/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Better-Call-Saul/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bob Odenkirk',
            'url': '/name/nm0644022/'},
           {'@type': 'Person',
            'name': 'Rhea Seehorn',
            'url': '/name/nm0781533/'},
           {'@type': 'Person',
            'name': 'Jonathan Banks',
            'url': '/name/nm0052186/'},
           {'@type': 'Person',
            'name': 'Patrick Fabian',
            'url': '/name/nm0264579/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 294520,
                     'ratingValue': '8.7',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Vince Gilligan',
              'url': '/name/nm0319213/'},
             {'@type': 'Person',
              'name': 'Peter Gould',
              'url': '/name/nm0332467/'},
             {'@type': 'Organization', 'url': '/company/co0212797/'},
             {'@type': 'Organization', 'url': '/company/co0520966/'},
             {'@type': 'Organization', 'url': '/company/co0071947/'},
             {'@type': 'Organization', 'url': '/company/co0086397/'},
             {'@type': 'Organization', 'url': '/company/co0019701/'}],
 'datePublished': '2015-02-08',
 'description': 'Better Call Saul is a TV series starring Bob Odenkirk, Rhea '
                'Seehorn, and Jonathan Banks. The trials and tribulations of '
                'criminal lawyer Jimmy McGill in the time before he '
                'established his strip-mall law office in Albuquerque, New...',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMGE4YzY4NGEtOWYyYS00ZDk2LWExMmMtZDIyODhiMmNlMGE0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'character flaw,prequel,spin off,financial struggle,shared '
             'universe',
 'name': 'Better Call Saul',
 'trailer': {'@type': 'VideoObject',
             'description': 'Welcome to Saul Goodman\'s world. "Better Call '
                            'Saul" Season 5 premieres Sunday, February 23, '
                            '2020.',
             'embedUrl': '/video/imdb/vi4166106905',
             'name': 'Season 5 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZWEyOTRmN2QtNDlmZS00YThiLWEzNGEtNzIxYTc4OTBjNDY0XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZWEyOTRmN2QtNDlmZS00YThiLWEzNGEtNzIxYTc4OTBjNDY0XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2020-01-30T04:14:46Z'},
 'url': '/title/tt3032476/'}