{'Actors': ['Adam Crosby',
            'Amber Heard',
            'Bill Hader',
            'Bobby Lee',
            'Brandon G Holley',
            'Brian Scannell',
            'Cleo King',
            'Connie Sawyer',
            'Craig Robinson',
            'Dana Lee',
            'Danny McBride',
            'David McDivitt',
            'Ed Begley Jr',
            'Eddie Rouse',
            'Gary Cole',
            'George F Watson',
            'Jack Kehler',
            'James Franco',
            'James Remar',
            'Jeannetta Arnette',
            'Jill Sayre',
            'Joe Lo Truglio',
            'Jonathan Spencer',
            'Ken Jeong',
            'Kendall Carly Browne',
            'Kevin Corrigan',
            'Nora Dunn',
            'Omar Leyva',
            'Peter Lewis',
            'Rosie Perez',
            'Sam Carson',
            'Seth Rogen',
            'Sheila Shaw',
            'Steve Bannos'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Pineapple Express: A stoner and his dealer are forced to go '
                'on the run from the police after the pothead witnesses a cop '
                'commit a murder. ',
 'Director': ['David Gordon Green'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pineapple-Express',
 'EntryURL': 'https://www.imdb.com/title/tt0910936',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pineapple-Express/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pineapple-Express/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Pineapple-Express/info.py',
 'Genres': ['Comedy', 'Thriller', 'Crime'],
 'IMDB': 'http://www.imdb.com/title/tt0910936',
 'PrimeWire': 'http://www.primewire.ag/watch-764-Pineapple-Express',
 'Ratings': {'IMDB': '7.0/10',
             'Metascore': '64%',
             'PrimeWire': '4.03/5',
             'RT': 'N/A',
             'Votes': '1887'},
 'Released': '2008-08-06',
 'Runtime': '111 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/764_Pineapple_Express_2008.jpg',
 'Title': 'Pineapple-Express'}