{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pineapple-Express',
 'EntryURL': 'https://www.imdb.com/title/tt0910936',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pineapple-Express/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pineapple-Express/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Pineapple-Express/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Seth Rogen', 'url': '/name/nm0736622/'},
           {'@type': 'Person',
            'name': 'James Franco',
            'url': '/name/nm0290556/'},
           {'@type': 'Person', 'name': 'Gary Cole', 'url': '/name/nm0170550/'},
           {'@type': 'Person',
            'name': 'Danny McBride',
            'url': '/name/nm1144419/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 307789,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Seth Rogen',
              'url': '/name/nm0736622/'},
             {'@type': 'Person',
              'name': 'Evan Goldberg',
              'url': '/name/nm1698571/'},
             {'@type': 'Person',
              'name': 'Judd Apatow',
              'url': '/name/nm0031976/'},
             {'@type': 'Person',
              'name': 'Seth Rogen',
              'url': '/name/nm0736622/'},
             {'@type': 'Person',
              'name': 'Evan Goldberg',
              'url': '/name/nm1698571/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0142678/'},
             {'@type': 'Organization', 'url': '/company/co0073081/'}],
 'datePublished': '2008-08-06',
 'description': 'Pineapple Express is a movie starring Seth Rogen, James '
                'Franco, and Gary Cole. A process server and his marijuana '
                'dealer wind up on the run from hitmen and a corrupt police '
                "officer after he witnesses his dealer's boss murder a...",
 'director': {'@type': 'Person',
              'name': 'David Gordon Green',
              'url': '/name/nm0337773/'},
 'duration': 'PT1H51M',
 'genre': ['Action', 'Comedy', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY1MTE4NzAwM15BMl5BanBnXkFtZTcwNzg3Mjg2MQ@@._V1_.jpg',
 'keywords': 'stoner,marijuana,falling downhill,watching tv,man tied up',
 'name': 'Pineapple Express',
 'trailer': {'@type': 'VideoObject',
             'description': 'This is the theatrical trailer for David Gordon '
                            "Green's Pineapple Express.",
             'embedUrl': '/video/imdb/vi2729574681',
             'name': 'Pineapple Express: Theatrical trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTc4NTY4NzYxNF5BMl5BanBnXkFtZTgwNjk3NDEyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTc4NTY4NzYxNF5BMl5BanBnXkFtZTgwNjk3NDEyMzE@._V1_.jpg',
             'uploadDate': '2008-03-29T07:02:49Z'},
 'url': '/title/tt0910936/'}