{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/When-They-See-Us',
 'EntryURL': 'https://www.imdb.com/title/tt7137906',
 'Entry_json': 'Favorites/TV/snapshot/When-They-See-Us/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/When-They-See-Us/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/When-They-See-Us/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Asante Blackk',
            'url': '/name/nm10040186/'},
           {'@type': 'Person',
            'name': 'Caleel Harris',
            'url': '/name/nm4144312/'},
           {'@type': 'Person',
            'name': 'Ethan Herisse',
            'url': '/name/nm5376232/'},
           {'@type': 'Person',
            'name': 'Marquis Rodriguez',
            'url': '/name/nm2532658/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 79949,
                      'ratingValue': '8.9',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Ava DuVernay',
              'url': '/name/nm1148550/'},
             {'@type': 'Organization', 'url': '/company/co0262187/'},
             {'@type': 'Organization', 'url': '/company/co0004231/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'},
             {'@type': 'Organization', 'url': '/company/co0063961/'}],
 'datePublished': '2019-05-31',
 'description': 'When They See Us is a TV mini-series starring Asante Blackk, '
                'Caleel Harris, and Ethan Herisse. Five teens from Harlem '
                "become trapped in a nightmare when they're falsely accused of "
                'a brutal attack in Central Park. Based on the true...',
 'genre': ['Biography', 'Crime', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZmJjM2YzOWEtOTYxYi00YjhkLTliMzgtMTA2MTc0NDQ1MDM4XkEyXkFqcGdeQXVyODY5OTk4MA@@._V1_.jpg',
 'keywords': 'agitprop,new york city,central park,rape accusation,1980s',
 'name': 'When They See Us',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Based on a true story that gripped the country, '
                             'When They See Us will chronicle the notorious '
                             'case of five teenagers of color, labeled the '
                             'Central Park Five, who were convicted of a rape '
                             'they did not commit.',
              'embedUrl': '/video/imdb/vi719305753',
              'name': 'New Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZmVhODNjODItMTQ5NC00MDJkLWJhZWMtMTM4MjVlNDczMWYyXkEyXkFqcGdeQXN3aWZ0dw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZmVhODNjODItMTQ5NC00MDJkLWJhZWMtMTM4MjVlNDczMWYyXkEyXkFqcGdeQXN3aWZ0dw@@._V1_.jpg',
              'uploadDate': '2019-05-28T15:17:00Z'}],
 'url': '/title/tt7137906/'}