{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Nines',
 'EntryURL': 'https://www.imdb.com/title/tt0810988',
 'Entry_json': 'Favorites/Movies/snapshot/The-Nines/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Nines/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Nines/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ryan Reynolds',
            'url': '/name/nm0005351/'},
           {'@type': 'Person', 'name': 'Hope Davis', 'url': '/name/nm0204706/'},
           {'@type': 'Person',
            'name': 'Melissa McCarthy',
            'url': '/name/nm0565250/'},
           {'@type': 'Person',
            'name': 'Elle Fanning',
            'url': '/name/nm1102577/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 32291,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'John August',
              'url': '/name/nm0041864/'},
             {'@type': 'Organization', 'url': '/company/co0017834/'},
             {'@type': 'Organization', 'url': '/company/co0021095/'}],
 'datePublished': '2007-11-30',
 'description': 'The Nines is a movie starring Ryan Reynolds, Hope Davis, and '
                'Melissa McCarthy. A troubled actor, a television show runner, '
                'and an acclaimed videogame designer find their lives '
                'intertwining in mysterious and unsettling ways.',
 'director': [{'@type': 'Person',
               'name': 'John August',
               'url': '/name/nm0041864/'}],
 'duration': 'PT1H40M',
 'genre': ['Drama', 'Fantasy', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI5ODI5MTUzN15BMl5BanBnXkFtZTcwOTIwMTE1MQ@@._V1_.jpg',
 'keywords': 'house arrest,screenwriter,fictional tv show,actress playing '
             'multiple roles,actor playing multiple roles',
 'name': 'The Nines',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A troubled actor, a television show runner, and '
                             'an acclaimed videogame designer find their lives '
                             'intertwining in mysterious and unsettling ways.',
              'embedUrl': '/video/imdb/vi3014721817',
              'name': 'The Nines Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTQ2MDkxMDk5OV5BMl5BanBnXkFtZTgwMTg1NDczMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTQ2MDkxMDk5OV5BMl5BanBnXkFtZTgwMTg1NDczMzE@._V1_.jpg',
              'uploadDate': '2007-09-05T11:23:00Z'}],
 'url': '/title/tt0810988/'}