{'Actors': ['Ben Falcone',
            'Dahlia Salem',
            'David Denman',
            'Elle Fanning',
            'Ellen Treanor',
            'Hope Davis',
            'Jim Rash',
            'John Gatins',
            'Martin Yu',
            'Melissa McCarthy',
            'Octavia Spencer',
            'Ryan Reynolds'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\n'
                'The Nines: A troubled actor, a television show runner, and an '
                'acclaimed videogame designer find their lives intertwining in '
                'mysterious and unsettling ways. ',
 'Director': ['John August'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Nines',
 'EntryURL': 'https://www.imdb.com/title/tt0810988',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Nines/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Nines/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Nines/info.py',
 'Genres': ['Drama', 'Sci-Fi', 'Fantasy', 'Mystery'],
 'Ratings': {'IMDB': '6.4/10',
             'Metascore': '52%',
             'PrimeWire': '3.56/5',
             'RT': '64%',
             'Votes': '404'},
 'Released': '2007-01-21',
 'Runtime': '100 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2775_The_Nines_2007.jpg',
 'Title': 'The-Nines'}