{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Mollys-Game',
 'EntryURL': 'https://www.imdb.com/title/tt4209788',
 'Entry_json': 'Favorites/Movies/snapshot/Mollys-Game/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Mollys-Game/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Mollys-Game/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jessica Chastain',
            'url': '/name/nm1567113/'},
           {'@type': 'Person', 'name': 'Idris Elba', 'url': '/name/nm0252961/'},
           {'@type': 'Person',
            'name': 'Kevin Costner',
            'url': '/name/nm0000126/'},
           {'@type': 'Person',
            'name': 'Michael Cera',
            'url': '/name/nm0148418/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 132110,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Aaron Sorkin',
              'url': '/name/nm0815070/'},
             {'@type': 'Person',
              'name': 'Molly Bloom',
              'url': '/name/nm6591098/'},
             {'@type': 'Organization', 'url': '/company/co0249694/'},
             {'@type': 'Organization', 'url': '/company/co0581352/'},
             {'@type': 'Organization', 'url': '/company/co0085751/'},
             {'@type': 'Organization', 'url': '/company/co0532247/'},
             {'@type': 'Organization', 'url': '/company/co0051618/'},
             {'@type': 'Organization', 'url': '/company/co0796482/'},
             {'@type': 'Organization', 'url': '/company/co0276464/'}],
 'datePublished': '2017-12-07',
 'description': "Molly's Game is a movie starring Jessica Chastain, Idris "
                'Elba, and Kevin Costner. The true story of Molly Bloom, an '
                "Olympic-class skier who ran the world's most exclusive "
                'high-stakes poker game and became an FBI target.',
 'director': [{'@type': 'Person',
               'name': 'Aaron Sorkin',
               'url': '/name/nm0815070/'}],
 'duration': 'PT2H20M',
 'genre': ['Biography', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTkzMzRlYjEtMTQ5Yi00OWY3LWI0NzYtNGQ4ZDkzZTU0M2IwXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'short skirt with heels,poker,lawyer,playing cards,female '
             'protagonist',
 'name': "Molly's Game",
 'trailer': [{'@type': 'VideoObject',
              'description': 'Aaron Sorkin annotates the theatrical trailer '
                             "for 'Molly's Game' to give you more insight to "
                             'his movie.',
              'embedUrl': '/video/imdb/vi1887483929',
              'name': 'Trailer With Commentary From Director Aaron Sorkin',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDNhZTM2NDYtZGU2MS00YThmLTk3OTMtNDRjY2ZjY2EwYWI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDNhZTM2NDYtZGU2MS00YThmLTk3OTMtNDRjY2ZjY2EwYWI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
              'uploadDate': '2017-12-22T19:33:55Z'}],
 'url': '/title/tt4209788/'}