{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-07-15',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Halt-and-Catch-Fire',
 'EntryURL': 'https://www.imdb.com/title/tt2543312',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Halt-and-Catch-Fire/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Halt-and-Catch-Fire/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Halt-and-Catch-Fire/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Lee Pace', 'url': '/name/nm1195855/'},
           {'@type': 'Person',
            'name': 'Scoot McNairy',
            'url': '/name/nm1058940/'},
           {'@type': 'Person',
            'name': 'Mackenzie Davis',
            'url': '/name/nm4496875/'},
           {'@type': 'Person',
            'name': 'Kerry Bishé',
            'url': '/name/nm2628935/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 26395,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Christopher Cantwell',
              'url': '/name/nm3437456/'},
             {'@type': 'Person',
              'name': 'Christopher C. Rogers',
              'url': '/name/nm4815022/'},
             {'@type': 'Organization', 'url': '/company/co0318834/'}],
 'datePublished': '2014-06-01',
 'description': 'Halt and Catch Fire is a TV series starring Lee Pace, Scoot '
                'McNairy, and Mackenzie Davis. Follows some players in the 80s '
                'technological revolution that lead to information society.',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTczNjAyMDg1Nl5BMl5BanBnXkFtZTgwMDQyNTA2OTE@._V1_.jpg',
 'keywords': '1980s,computer,female programmer,family relationships,computer '
             'programmer',
 'name': 'Halt and Catch Fire',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'Leon-hopp'},
            'dateCreated': '2019-02-17',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt2543312/'},
            'name': 'One step above the rest...',
            'reviewBody': "This is the first show I have seen, and I've seen "
                          'plenty, where after binging all four seasons in two '
                          'weeks, I just started all over again.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Halt and Catch Fire',
             'embedUrl': '/video/imdb/vi1893839385',
             'name': 'Halt And Catch Fire: Season 1',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmNhZjZkMzQtOTI3YS00NWMwLTlmMzAtZjc3NzNkYzhmNjc3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmNhZjZkMzQtOTI3YS00NWMwLTlmMzAtZjc3NzNkYzhmNjc3XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2015-11-27T07:26:20Z'},
 'url': '/title/tt2543312/'}