{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/The-Witcher',
 'EntryURL': 'https://www.imdb.com/title/tt5180504',
 'Entry_json': 'Favorites/TV/snapshot/The-Witcher/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Witcher/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Witcher/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Henry Cavill',
            'url': '/name/nm0147147/'},
           {'@type': 'Person',
            'name': 'Freya Allan',
            'url': '/name/nm8463347/'},
           {'@type': 'Person',
            'name': 'Anya Chalotra',
            'url': '/name/nm9923141/'},
           {'@type': 'Person',
            'name': 'Mimi Ndiweni',
            'url': '/name/nm5507408/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 263507,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Lauren Schmidt',
              'url': '/name/nm1274355/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0525779/'},
             {'@type': 'Organization', 'url': '/company/co0091558/'},
             {'@type': 'Organization', 'url': '/company/co0007038/'}],
 'datePublished': '2019-12-20',
 'description': 'The Witcher is a TV series starring Henry Cavill, Freya '
                'Allan, and Anya Chalotra. Geralt of Rivia, a solitary monster '
                'hunter, struggles to find his place in a world where people '
                'often prove more wicked than beasts.',
 'genre': ['Action', 'Adventure', 'Fantasy', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOGE4MmVjMDgtMzIzYy00NjEwLWJlODMtMDI1MGY2ZDlhMzE2XkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_.jpg',
 'keywords': 'magic,monster hunter,violence,based on novel,mutation',
 'name': 'The Witcher',
 'trailer': [{'@type': 'VideoObject',
              'description': 'On a Continent riddled with evil, the paths of a '
                             'monster hunter, a sorceress and a runaway '
                             'princess converge. "The Witcher," starring Henry '
                             'Cavill, arrives December 20, only on Netflix.',
              'embedUrl': '/video/imdb/vi840285977',
              'name': 'Final Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYjhmYWZhNzctNTI3NS00OTNlLTlmNWItNTU4OWI3NGI3OGRmXkEyXkFqcGdeQWpnYW1i._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYjhmYWZhNzctNTI3NS00OTNlLTlmNWItNTU4OWI3NGI3OGRmXkEyXkFqcGdeQWpnYW1i._V1_.jpg',
              'uploadDate': '2019-12-12T22:45:50Z'}],
 'url': '/title/tt5180504/'}