{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Pulp-Fiction',
 'EntryURL': 'https://www.imdb.com/title/tt0110912',
 'Entry_json': 'Favorites/Movies/snapshot/Pulp-Fiction/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Pulp-Fiction/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Pulp-Fiction/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Travolta',
            'url': '/name/nm0000237/'},
           {'@type': 'Person',
            'name': 'Uma Thurman',
            'url': '/name/nm0000235/'},
           {'@type': 'Person',
            'name': 'Samuel L. Jackson',
            'url': '/name/nm0000168/'},
           {'@type': 'Person',
            'name': 'Bruce Willis',
            'url': '/name/nm0000246/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1759456,
                      'ratingValue': '8.9',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Person',
              'name': 'Roger Avary',
              'url': '/name/nm0000812/'},
             {'@type': 'Person',
              'name': 'Quentin Tarantino',
              'url': '/name/nm0000233/'},
             {'@type': 'Organization', 'url': '/company/co0022594/'},
             {'@type': 'Organization', 'url': '/company/co0019267/'},
             {'@type': 'Organization', 'url': '/company/co0010434/'}],
 'datePublished': '1994-09-10',
 'description': 'Pulp Fiction is a movie starring John Travolta, Uma Thurman, '
                'and Samuel L. Jackson. The lives of two mob hitmen, a boxer, '
                'a gangster and his wife, and a pair of diner bandits '
                'intertwine in four tales of violence and redemption.',
 'director': [{'@type': 'Person',
               'name': 'Quentin Tarantino',
               'url': '/name/nm0000233/'}],
 'duration': 'PT2H34M',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'nonlinear timeline,overdose,drug overdose,black comedy,bondage',
 'name': 'Pulp Fiction',
 'trailer': [{'@type': 'VideoObject',
              'description': 'The lives of two mob hit men, a boxer, a '
                             "gangster's wife, and a pair of diner bandits "
                             'intertwine in four tales of violence and '
                             'redemption.',
              'embedUrl': '/video/imdb/vi2620371481',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjI5MzgxMTQ4M15BMl5BanBnXkFtZTgwNjczMTk0NzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjI5MzgxMTQ4M15BMl5BanBnXkFtZTgwNjczMTk0NzE@._V1_.jpg',
              'uploadDate': '2015-12-16T10:51:07Z'}],
 'url': '/title/tt0110912/'}