{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Mad-Men',
 'EntryURL': 'https://www.imdb.com/title/tt0804503',
 'Entry_json': 'Favorites/TV/snapshot/Mad-Men/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Mad-Men/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Mad-Men/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jon Hamm', 'url': '/name/nm0358316/'},
           {'@type': 'Person',
            'name': 'Elisabeth Moss',
            'url': '/name/nm0005253/'},
           {'@type': 'Person',
            'name': 'Vincent Kartheiser',
            'url': '/name/nm0440229/'},
           {'@type': 'Person',
            'name': 'January Jones',
            'url': '/name/nm0005064/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 198594,
                      'ratingValue': '8.6',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Matthew Weiner',
              'url': '/name/nm1980806/'},
             {'@type': 'Organization', 'url': '/company/co0026995/'},
             {'@type': 'Organization', 'url': '/company/co0247554/'},
             {'@type': 'Organization', 'url': '/company/co0019701/'},
             {'@type': 'Organization', 'url': '/company/co0308431/'}],
 'datePublished': '2007-07-19',
 'description': 'Mad Men is a TV series starring Jon Hamm, Elisabeth Moss, and '
                "Vincent Kartheiser. A drama about one of New York's most "
                'prestigious ad agencies at the beginning of the 1960s, '
                "focusing on one of the firm's most mysterious but...",
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BNTgxNDZlODQtNDcwOC00NWQ5LTljNWMtMDhjY2U5YTUzMTc4XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg',
 'keywords': 'advertising,chain smoking,1960s,new york,drinking',
 'name': 'Mad Men',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Watch a trailer for AMC\'s "Mad Men."',
              'embedUrl': '/video/imdb/vi69710105',
              'name': 'Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTEzNTI3ODk0NjZeQTJeQWpwZ15BbWU4MDQyOTg5MDUx._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTEzNTI3ODk0NjZeQTJeQWpwZ15BbWU4MDQyOTg5MDUx._V1_.jpg',
              'uploadDate': '2015-03-31T09:40:19Z'}],
 'url': '/title/tt0804503/'}