{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/The-House-Bunny',
 'EntryURL': 'https://www.imdb.com/title/tt0852713',
 'Entry_json': 'Favorites/Movies/snapshot/The-House-Bunny/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-House-Bunny/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-House-Bunny/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Anna Faris', 'url': '/name/nm0267506/'},
           {'@type': 'Person',
            'name': 'Colin Hanks',
            'url': '/name/nm0004988/'},
           {'@type': 'Person', 'name': 'Emma Stone', 'url': '/name/nm1297015/'},
           {'@type': 'Person',
            'name': 'Kat Dennings',
            'url': '/name/nm0993507/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 77586,
                     'ratingValue': '5.5',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Karen McCullah',
              'url': '/name/nm0527581/'},
             {'@type': 'Person',
              'name': 'Kirsten Smith',
              'url': '/name/nm0809006/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0142678/'},
             {'@type': 'Organization', 'url': '/company/co0059609/'},
             {'@type': 'Organization', 'url': '/company/co0008514/'}],
 'datePublished': '2008-08-22',
 'description': 'The House Bunny is a movie starring Anna Faris, Colin Hanks, '
                'and Emma Stone. After Playboy bunny Shelley is kicked out of '
                'the playboy mansion, she finds a job as the house mother for '
                'a sorority full of socially awkward girls.',
 'director': {'@type': 'Person',
              'name': 'Fred Wolf',
              'url': '/name/nm0937748/'},
 'duration': 'PT1H37M',
 'genre': ['Comedy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODkxMDg0MjM2OF5BMl5BanBnXkFtZTcwMjc0NTU4MQ@@._V1_.jpg',
 'keywords': 'no panties,sorority,playboy bunny,scantily clad female,playboy '
             'model',
 'name': 'The House Bunny',
 'trailer': {'@type': 'VideoObject',
             'description': 'A romantic comedy film, directed by Fred Wolf',
             'embedUrl': '/video/imdb/vi1305281305',
             'name': 'The House Bunny',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODAxYzc3ODQtMGZmMy00ZWVjLTlkODItYzBkNzVlMzE1NzFmXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODAxYzc3ODQtMGZmMy00ZWVjLTlkODItYzBkNzVlMzE1NzFmXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2009-01-23T07:42:27Z'},
 'url': '/title/tt0852713/'}