{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Waynes-World',
 'EntryURL': 'https://www.imdb.com/title/tt0105793',
 'Entry_json': 'Favorites/Movies/snapshot/Waynes-World/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Waynes-World/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Waynes-World/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Mike Myers', 'url': '/name/nm0000196/'},
           {'@type': 'Person',
            'name': 'Dana Carvey',
            'url': '/name/nm0001022/'},
           {'@type': 'Person', 'name': 'Rob Lowe', 'url': '/name/nm0000507/'},
           {'@type': 'Person',
            'name': 'Tia Carrere',
            'url': '/name/nm0000119/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 140759,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Mike Myers',
              'url': '/name/nm0000196/'},
             {'@type': 'Person',
              'name': 'Mike Myers',
              'url': '/name/nm0000196/'},
             {'@type': 'Person',
              'name': 'Bonnie Turner',
              'url': '/name/nm0877425/'},
             {'@type': 'Person',
              'name': 'Terry Turner',
              'url': '/name/nm0877901/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'}],
 'datePublished': '1992-02-14',
 'description': "Wayne's World is a movie starring Mike Myers, Dana Carvey, "
                'and Rob Lowe. Two slacker friends try to promote their '
                'public-access cable show.',
 'director': [{'@type': 'Person',
               'name': 'Penelope Spheeris',
               'url': '/name/nm0790715/'}],
 'duration': 'PT1H34M',
 'genre': ['Comedy', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMDAyNDY3MjUtYmJjYS00Zjc5LTlhM2MtNzgzYjNlOWVkZjkzL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'public access,headbanging,breaking the fourth wall,based on '
             'sketch comedy,reference to blazing saddles',
 'name': "Wayne's World",
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi3340484121',
              'name': 'Trailer [OV]',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZjk2YWQxZjctOWQwNy00YTMyLWI4YjctZjliMTBiNjRjYTRmXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZjk2YWQxZjctOWQwNy00YTMyLWI4YjctZjliMTBiNjRjYTRmXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2020-07-01T08:49:22Z'}],
 'url': '/title/tt0105793/'}