{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-08-04',
 'EntryPath': 'Favorites/Movies/snapshot/Hot-Coffee',
 'EntryURL': 'https://www.imdb.com/title/tt1445203',
 'Entry_json': 'Favorites/Movies/snapshot/Hot-Coffee/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Hot-Coffee/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Hot-Coffee/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Chuck Allen',
            'url': '/name/nm6256483/'},
           {'@type': 'Person', 'name': 'Judy Allen', 'url': '/name/nm6256484/'},
           {'@type': 'Person', 'name': 'Jay Angoff', 'url': '/name/nm6193797/'},
           {'@type': 'Person',
            'name': 'David Arredondo',
            'url': '/name/nm1428070/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3635,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Organization', 'url': '/company/co0373233/'},
             {'@type': 'Organization', 'url': '/company/co0321978/'},
             {'@type': 'Organization', 'url': '/company/co0181699/'}],
 'datePublished': '2011-06-17',
 'description': 'Hot Coffee is a movie starring Chuck Allen, Judy Allen, and '
                "Jay Angoff. How the infamous McDonald's hot coffee lawsuit "
                'and similar cases were exploited as part of a right wing '
                'crusade to weaken civil justice.',
 'director': [{'@type': 'Person',
               'name': 'Susan Saladoff',
               'url': '/name/nm3479392/'}],
 'duration': 'PT1H28M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BOTc3NTgyMDA5MV5BMl5BanBnXkFtZTcwNTc3NzUzNA@@._V1_.jpg',
 'keywords': 'coffee,legal,media,justice,tort reform',
 'name': 'Hot Coffee',
 'url': '/title/tt1445203/'}