{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-01-27',
 'EntryPath': 'Favorites/TV/snapshot/The-Circus-Inside-the-Greatest-Political-Show-on-Earth',
 'EntryURL': 'https://www.imdb.com/title/tt5351176',
 'Entry_json': 'Favorites/TV/snapshot/The-Circus-Inside-the-Greatest-Political-Show-on-Earth/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Circus-Inside-the-Greatest-Political-Show-on-Earth/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Circus-Inside-the-Greatest-Political-Show-on-Earth/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Heilemann',
            'url': '/name/nm2129264/'},
           {'@type': 'Person',
            'name': 'Mark McKinnon',
            'url': '/name/nm1502857/'},
           {'@type': 'Person',
            'name': 'Alex Wagner',
            'url': '/name/nm4757938/'},
           {'@type': 'Person',
            'name': 'Mark Halperin',
            'url': '/name/nm0356927/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 702,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Organization', 'url': '/company/co0354558/'}],
 'datePublished': '2016-01-17',
 'description': 'The Circus: Inside the Greatest Political Show on Earth is a '
                'TV series starring John Heilemann, Mark McKinnon, and Alex '
                'Wagner. Come one, come all to THE CIRCUS. This documentary '
                'series pulls back the curtain on the Trump era of...',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTRlYmI5NTUtNDYzNS00NjY3LWE4NTUtMThhNDE1NWM2YzkxXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_.jpg',
 'keywords': 'politics',
 'name': 'The Circus: Inside the Greatest Political Show on Earth',
 'trailer': [{'@type': 'VideoObject',
              'description': 'The Circus: Inside The Greatest Political Show '
                             'On Earth: Season 3',
              'embedUrl': '/video/imdb/vi938655001',
              'name': 'The Circus: Inside The Greatest Political Show On '
                      'Earth: Season 3',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDUzOTUwOTgtMjlmMS00MGFkLThiY2EtZWY0MTJkYTMyNWQ1XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDUzOTUwOTgtMjlmMS00MGFkLThiY2EtZWY0MTJkYTMyNWQ1XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-03-18T18:41:42Z'}],
 'url': '/title/tt5351176/'}