{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-12-26',
 'EntryPath': 'Favorites/Movies/snapshot/Mr-Nobody',
 'EntryURL': 'https://www.imdb.com/title/tt0485947',
 'Entry_json': 'Favorites/Movies/snapshot/Mr-Nobody/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Mr-Nobody/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Mr-Nobody/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jared Leto', 'url': '/name/nm0001467/'},
           {'@type': 'Person',
            'name': 'Sarah Polley',
            'url': '/name/nm0001631/'},
           {'@type': 'Person',
            'name': 'Diane Kruger',
            'url': '/name/nm1208167/'},
           {'@type': 'Person',
            'name': 'Linh Dan Pham',
            'url': '/name/nm0199006/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 209335,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jaco Van Dormael',
              'url': '/name/nm0233757/'},
             {'@type': 'Organization', 'url': '/company/co0060537/'},
             {'@type': 'Organization', 'url': '/company/co0065565/'},
             {'@type': 'Organization', 'url': '/company/co0183386/'},
             {'@type': 'Organization', 'url': '/company/co0061702/'},
             {'@type': 'Organization', 'url': '/company/co0294707/'},
             {'@type': 'Organization', 'url': '/company/co0056755/'},
             {'@type': 'Organization', 'url': '/company/co0044140/'},
             {'@type': 'Organization', 'url': '/company/co0160453/'},
             {'@type': 'Organization', 'url': '/company/co0666652/'},
             {'@type': 'Organization', 'url': '/company/co0028557/'},
             {'@type': 'Organization', 'url': '/company/co0418309/'},
             {'@type': 'Organization', 'url': '/company/co0028908/'},
             {'@type': 'Organization', 'url': '/company/co0146558/'},
             {'@type': 'Organization', 'url': '/company/co0445695/'},
             {'@type': 'Organization', 'url': '/company/co0270146/'},
             {'@type': 'Organization', 'url': '/company/co0011107/'},
             {'@type': 'Organization', 'url': '/company/co0061460/'},
             {'@type': 'Organization', 'url': '/company/co0169751/'},
             {'@type': 'Organization', 'url': '/company/co0004166/'},
             {'@type': 'Organization', 'url': '/company/co0130575/'},
             {'@type': 'Organization', 'url': '/company/co0176243/'},
             {'@type': 'Organization', 'url': '/company/co0077261/'},
             {'@type': 'Organization', 'url': '/company/co0138115/'},
             {'@type': 'Organization', 'url': '/company/co0002435/'},
             {'@type': 'Organization', 'url': '/company/co0093053/'},
             {'@type': 'Organization', 'url': '/company/co0053177/'},
             {'@type': 'Organization', 'url': '/company/co0053578/'},
             {'@type': 'Organization', 'url': '/company/co0024845/'}],
 'datePublished': '2009-11-06',
 'description': 'Mr. Nobody is a movie starring Jared Leto, Sarah Polley, and '
                'Diane Kruger. A boy stands on a station platform as a train '
                'is about to leave. Should he go with his mother or stay with '
                'his father? Infinite possibilities arise from this...',
 'director': [{'@type': 'Person',
               'name': 'Jaco Van Dormael',
               'url': '/name/nm0233757/'}],
 'duration': 'PT2H21M',
 'genre': ['Drama', 'Fantasy', 'Romance', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg4ODkzMDQ3Nl5BMl5BanBnXkFtZTgwNTEwMTkxMDE@._V1_.jpg',
 'keywords': 'multiple outcomes,stepbrother stepsister relationship,nonlinear '
             'timeline,mother spanking child,butterfly effect',
 'name': 'Mr. Nobody',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A young boy stands on a station platform. The '
                             'train is about to leave. Should he go with his '
                             'mother or stay with his father? An infinity of '
                             'possibilities rise from this decision. As long '
                             "as he doesn't choose, anything is possible. "
                             'Every life deserves to be lived.',
              'embedUrl': '/video/imdb/vi23832857',
              'name': 'Theatrical Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTc2MjQ5ODgyMV5BMl5BanBnXkFtZTgwNTk3NjAyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTc2MjQ5ODgyMV5BMl5BanBnXkFtZTgwNTk3NjAyMzE@._V1_.jpg',
              'uploadDate': '2013-09-13T10:37:07Z'}],
 'url': '/title/tt0485947/'}