{'Actors': ['Aaron Fletcher&tv'],
 'Added': '2015-06-07',
 'Countries': ['USA'],
 'Description': '\n'
                'The Mechanical Universe... and Beyond: Produced starting in '
                '1985, the videos make heavy use of historical dramatizations '
                'and visual aids to explain physics concepts. ',
 'Director': ['NA'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Mechanical-Universe-and-Beyond',
 'EntryURL': 'http://www.imdb.com/title/tt0396993',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Mechanical-Universe-and-Beyond/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Mechanical-Universe-and-Beyond/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//The-Mechanical-Universe-and-Beyond/info.py',
 'Genres': ['Documentary&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0396993',
 'PrimeWire': 'http://www.primewire.ag/tv-448067-The-Mechanical-Universe-and-Beyond',
 'Ratings': {'IMDB': '8.8/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.33/5',
             'RT': 'N/A',
             'Votes': '9'},
 'Released': '1985-01-30',
 'Runtime': '25 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/448067_The_Mechanical_Universe_and_Beyond_1969.jpg',
 'Title': 'The-Mechanical-Universe-and-Beyond'}