{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-06-07',
 'EntryPath': 'Favorites/TV/snapshot/The-Mechanical-Universe-and-Beyond',
 'EntryURL': 'https://www.imdb.com/title/tt0396993',
 'Entry_json': 'Favorites/TV/snapshot/The-Mechanical-Universe-and-Beyond/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Mechanical-Universe-and-Beyond/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Mechanical-Universe-and-Beyond/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Aaron Fletcher',
            'url': '/name/nm1891052/'},
           {'@type': 'Person',
            'name': 'David L. Goodstein',
            'url': '/name/nm1538900/'},
           {'@type': 'Person',
            'name': 'Chris Tashima',
            'url': '/name/nm0850875/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 125,
                     'ratingValue': '9.1',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Organization', 'url': '/company/co0124886/'},
             {'@type': 'Organization', 'url': '/company/co0168681/'}],
 'datePublished': '2007-10-03',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BOGM0MWY1YmUtOGVjNy00MmQyLWE2ZWYtNDVmMWJhM2E1NTVkXkEyXkFqcGdeQXVyMzYxOTQ1MTg@._V1_.jpg',
 'name': 'The Mechanical Universe... and Beyond',
 'url': '/title/tt0396993/'}