{'Actors': [''],
 'Added': '2013-11-22',
 'Countries': [],
 'Description': '\nFeynman: The Challenger: As a companion to the fictional drama THE CHALLENGER DISASTER Science Channel is airing FEYNMAN: THE CHALLENGER on Monday, November 18 at 10 PM ET/PT. This special one-hour documentary, narrated by Bruce Greenwood, examines the remarkable life of Dr. Richard Feynman, including his work on the Challenger and his role in The Manhattan Project, a U.S. government backed program that operated during the 1940s and led to the creation of the first atomic bombs. ',
 'Director': [],
 'Genres': ['Documentary'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2742793-Feynman-The-Challenger',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '4.33/5',
             'RT': 'N/A',
             'Votes': '6'},
 'Released': '2013-11-18',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2742793_Feynman_The_Challenger.jpg',
 'Title': 'Feynman-The-Challenger'}