{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-10',
 'EntryURL': 'https://rawg.io/games/final-fantasy-10',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-10/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-10/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-10/thumb.jpg',
 'added': 392,
 'background_image': 'https://media.rawg.io/media/games/496/4964790491867146081fe2d7055f787f.jpg',
 'developers': ['Square'],
 'genres': ['RPG'],
 'name': 'Final Fantasy X',
 'platforms': ['PC', 'PlayStation 4', 'PS Vita', 'PlayStation 2'],
 'publishers': ['Square'],
 'released': '2001-07-19',
 'slug': 'final-fantasy-10'}