{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-08-30',
 'EntryPath': 'Favorites/TV/snapshot/Klondike',
 'EntryURL': 'https://www.imdb.com/title/tt2761630',
 'Entry_json': 'Favorites/TV/snapshot/Klondike/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Klondike/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Klondike/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Abbie Cornish',
            'url': '/name/nm0180411/'},
           {'@type': 'Person',
            'name': 'Marton Csokas',
            'url': '/name/nm0190744/'},
           {'@type': 'Person', 'name': 'Ian Hart', 'url': '/name/nm0001324/'},
           {'@type': 'Person',
            'name': 'Greg Lawson',
            'url': '/name/nm0493222/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 5743,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0045277/'},
             {'@type': 'Organization', 'url': '/company/co0212327/'},
             {'@type': 'Organization', 'url': '/company/co0030020/'},
             {'@type': 'Organization', 'url': '/company/co0074212/'},
             {'@type': 'Organization', 'url': '/company/co0249368/'}],
 'datePublished': '2014-01-20',
 'description': 'Klondike is a TV mini-series starring Abbie Cornish, Marton '
                'Csokas, and Ian Hart. The lives of two childhood best '
                'friends, Bill and Epstein, in the late 1890s as they flock to '
                'the gold rush capital in the untamed Yukon Territory....',
 'genre': ['Adventure', 'Drama', 'Western'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTk2NDM2NjEyMV5BMl5BanBnXkFtZTgwOTgxNzQxMTE@._V1_.jpg',
 'keywords': 'tv mini series,set in canada,yukon territory,canadian content',
 'name': 'Klondike',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Klondike',
              'embedUrl': '/video/imdb/vi3498884377',
              'name': 'Klondike',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZmM5OWNhM2MtMjFiNC00MWMwLThjYzAtYzZiMjdjYzY4OTAzXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZmM5OWNhM2MtMjFiNC00MWMwLThjYzAtYzZiMjdjYzY4OTAzXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-03-18T12:10:23Z'}],
 'url': '/title/tt2761630/'}