{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Black-Mirror-Bandersnatch',
 'EntryURL': 'https://www.imdb.com/title/tt9495224',
 'Entry_json': 'Favorites/Movies/snapshot/Black-Mirror-Bandersnatch/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Black-Mirror-Bandersnatch/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Black-Mirror-Bandersnatch/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Fionn Whitehead',
            'url': '/name/nm7887725/'},
           {'@type': 'Person',
            'name': 'Craig Parkinson',
            'url': '/name/nm0971135/'},
           {'@type': 'Person', 'name': 'Alice Lowe', 'url': '/name/nm1546686/'},
           {'@type': 'Person',
            'name': 'Asim Chaudhry',
            'url': '/name/nm5219130/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 107210,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Charlie Brooker',
              'url': '/name/nm0111765/'},
             {'@type': 'Organization', 'url': '/company/co0493201/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2018-12-28',
 'description': 'Black Mirror: Bandersnatch is a TV movie starring Fionn '
                'Whitehead, Craig Parkinson, and Alice Lowe. A young '
                'programmer starts to question reality when he adapts a mad '
                "writer's fantasy novel into a video game.",
 'director': {'@type': 'Person',
              'name': 'David Slade',
              'url': '/name/nm1720541/'},
 'duration': 'PT1H30M',
 'genre': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjM5MzgzMjM3OF5BMl5BanBnXkFtZTgwMzQ2MzQwNzM@._V1_.jpg',
 'keywords': 'interactive movie,1980s,computer,gamebook,interactive',
 'name': 'Black Mirror: Bandersnatch',
 'trailer': {'@type': 'VideoObject',
             'description': 'In 1984, a young programmer begins to question '
                            'reality as he adapts a sprawling fantasy novel '
                            'into a video game and soon faces a mind-mangling '
                            'challenge. Welcome back. A "Black Mirror" event.',
             'embedUrl': '/video/imdb/vi2319104537',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOWZiMTY0ZjItZWQxOS00YzFmLTliMGItZDg5Y2ZhZDI2MzcyXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOWZiMTY0ZjItZWQxOS00YzFmLTliMGItZDg5Y2ZhZDI2MzcyXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
             'uploadDate': '2018-12-27T10:44:22Z'},
 'url': '/title/tt9495224/'}