{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/Family-Guy',
 'EntryURL': 'https://www.imdb.com/title/tt0182576',
 'Entry_json': 'Favorites/TV/snapshot/Family-Guy/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Family-Guy/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Family-Guy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Seth MacFarlane',
            'url': '/name/nm0532235/'},
           {'@type': 'Person',
            'name': 'Alex Borstein',
            'url': '/name/nm0097504/'},
           {'@type': 'Person', 'name': 'Seth Green', 'url': '/name/nm0001293/'},
           {'@type': 'Person',
            'name': 'Mila Kunis',
            'url': '/name/nm0005109/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 296189,
                      'ratingValue': '8.1',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Seth MacFarlane',
              'url': '/name/nm0532235/'},
             {'@type': 'Person',
              'name': 'David Zuckerman',
              'url': '/name/nm0958412/'},
             {'@type': 'Organization', 'url': '/company/co0056447/'},
             {'@type': 'Organization', 'url': '/company/co0065872/'},
             {'@type': 'Organization', 'url': '/company/co0159275/'}],
 'datePublished': '1999-01-31',
 'description': 'Family Guy is a TV series starring Seth MacFarlane, Alex '
                'Borstein, and Seth Green. In a wacky Rhode Island town, a '
                'dysfunctional family strive to cope with everyday life as '
                'they are thrown from one crazy scenario to another.',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODEwZjEzMjAtNjQxMy00Yjc4LWFlMDAtYjhjZTAxNDU3OTg3XkEyXkFqcGdeQXVyOTM2NTM4MjA@._V1_.jpg',
 'keywords': 'sexual reference,sexual innuendo,animal as '
             'human,pedophile,derivative',
 'name': 'Family Guy',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Watch a scene from the "Family Guy"/"Simpsons" '
                             'crossover, "Simpsons Guy".',
              'embedUrl': '/video/imdb/vi2124066585',
              'name': '#3',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjM2MDc0NzQ2N15BMl5BanBnXkFtZTgwODUwMDEyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjM2MDc0NzQ2N15BMl5BanBnXkFtZTgwODUwMDEyMzE@._V1_.jpg',
              'uploadDate': '2014-09-25T12:07:11Z'}],
 'url': '/title/tt0182576/'}