{'Actors': ['Alex Borstein&tv',
            'Danny Smith&tv',
            'John Viener&tv',
            'Lori Alan&tv',
            'Mike Henry&tv',
            'Mila Kunis&tv',
            'Patrick Warburton&tv',
            'Seth Green&tv',
            'Seth MacFarlane&tv'],
 'Added': '2011-08-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Family Guy: In a wacky Rhode Island town, a dysfunctional '
                'family strive to cope with everyday life as they are thrown '
                'from one crazy scenario to another. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Family-Guy',
 'EntryURL': 'http://www.imdb.com/title/tt0182576',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Family-Guy/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Family-Guy/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Family-Guy/info.py',
 'Genres': ['Animation&tv', 'Comedy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0182576',
 'PrimeWire': 'http://www.primewire.ag/tv-4132-Family-Guy',
 'Ratings': {'IMDB': '8.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.91/5',
             'RT': 'N/A',
             'Votes': '4729'},
 'Released': '1999-01-31',
 'Runtime': '22 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/4132_Family_Guy_1999.jpg',
 'Title': 'Family-Guy'}