{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-10-02',
 'EntryPath': 'Favorites/Movies/snapshot/Cartel-Land',
 'EntryURL': 'https://www.imdb.com/title/tt4126304',
 'Entry_json': 'Favorites/Movies/snapshot/Cartel-Land/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Cartel-Land/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Cartel-Land/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Tim Nailer Foley',
            'url': '/name/nm8166127/'},
           {'@type': 'Person',
            'name': "José Manuel 'El Doctor' Mireles",
            'url': '/name/nm7858356/'},
           {'@type': 'Person',
            'name': 'Paco Valencia',
            'url': '/name/nm8483522/'},
           {'@type': 'Person', 'name': 'Chaneque', 'url': '/name/nm8483523/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 17571,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Organization', 'url': '/company/co0152564/'},
             {'@type': 'Organization', 'url': '/company/co0299372/'},
             {'@type': 'Organization', 'url': '/company/co0202303/'},
             {'@type': 'Organization', 'url': '/company/co0109361/'}],
 'datePublished': '2015-07-03',
 'description': 'Cartel Land is a movie starring Tim Nailer Foley, José Manuel '
                "'El Doctor' Mireles, and Paco Valencia. Filmmaker Matthew "
                'Heineman examines the state of the ongoing drug problem along '
                'the U.S.-Mexican border.',
 'director': [{'@type': 'Person',
               'name': 'Matthew Heineman',
               'url': '/name/nm1292648/'}],
 'duration': 'PT1H40M',
 'genre': ['Documentary', 'News'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE1MzI2MzcxOV5BMl5BanBnXkFtZTgwNTE2Mjk4NTE@._V1_.jpg',
 'keywords': 'arizona desert,sonora mexico,arrest,drug,gunfire',
 'name': 'Cartel Land',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Cartel Land',
              'embedUrl': '/video/imdb/vi2916268057',
              'name': 'Cartel Land',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYThlOWRkN2QtODE4Zi00OWMxLWJhNzgtZmFkMzE2MjNjOTZjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYThlOWRkN2QtODE4Zi00OWMxLWJhNzgtZmFkMzE2MjNjOTZjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2018-02-01T17:05:08Z'}],
 'url': '/title/tt4126304/'}