{'Actors': [''],
 'Added': '2014-04-03',
 'Countries': [],
 'Description': '\nInside The Scientology Center: Steven Mango is an actor, business owner and he was a four-year parishioner of the church of Scientology Celebrity Center in Hollywood. He came in there in hope to find spiritual fulfillment and get some guidance in his acting career. Over the course of four years he has donated close to $50,000 to the church of scientology. ',
 'Director': [],
 'Genres': ['Documentary'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2745330-Inside-The-Scientology-Center',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '2.41/5',
             'RT': 'N/A',
             'Votes': '44'},
 'Released': '2014-01-27',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2745330_Inside_The_Scientology_Center.jpg',
 'Title': 'Inside-The-Scientology-Center'}