{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/The-Death-Of-Stalin',
 'EntryURL': 'https://www.imdb.com/title/tt4686844',
 'Entry_json': 'Favorites/Movies/snapshot/The-Death-Of-Stalin/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Death-Of-Stalin/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Death-Of-Stalin/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Steve Buscemi',
            'url': '/name/nm0000114/'},
           {'@type': 'Person',
            'name': 'Simon Russell Beale',
            'url': '/name/nm0750971/'},
           {'@type': 'Person',
            'name': 'Jeffrey Tambor',
            'url': '/name/nm0001787/'},
           {'@type': 'Person',
            'name': 'Andrea Riseborough',
            'url': '/name/nm2057859/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 81025,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Armando Iannucci',
              'url': '/name/nm0406334/'},
             {'@type': 'Person',
              'name': 'David Schneider',
              'url': '/name/nm0773768/'},
             {'@type': 'Person',
              'name': 'Ian Martin',
              'url': '/name/nm2254846/'},
             {'@type': 'Person',
              'name': 'Peter Fellows',
              'url': '/name/nm4397668/'},
             {'@type': 'Person',
              'name': 'Fabien Nury',
              'url': '/name/nm1942997/'},
             {'@type': 'Person',
              'name': 'Thierry Robin',
              'url': '/name/nm2934300/'},
             {'@type': 'Person',
              'name': 'Fabien Nury',
              'url': '/name/nm1942997/'},
             {'@type': 'Organization', 'url': '/company/co0098808/'},
             {'@type': 'Organization', 'url': '/company/co0595884/'},
             {'@type': 'Organization', 'url': '/company/co0172053/'},
             {'@type': 'Organization', 'url': '/company/co0044140/'},
             {'@type': 'Organization', 'url': '/company/co0384091/'},
             {'@type': 'Organization', 'url': '/company/co0244390/'},
             {'@type': 'Organization', 'url': '/company/co0028557/'},
             {'@type': 'Organization', 'url': '/company/co0641111/'},
             {'@type': 'Organization', 'url': '/company/co0354373/'},
             {'@type': 'Organization', 'url': '/company/co0009204/'},
             {'@type': 'Organization', 'url': '/company/co0396761/'}],
 'datePublished': '2017-10-20',
 'description': 'The Death of Stalin is a movie starring Steve Buscemi, Simon '
                'Russell Beale, and Jeffrey Tambor. Moscow, 1953. After being '
                'in power for nearly thirty years, Soviet dictator Joseph '
                'Vissarionovich Stalin (Adrian McLoughlin) takes ill...',
 'director': [{'@type': 'Person',
               'name': 'Armando Iannucci',
               'url': '/name/nm0406334/'}],
 'duration': 'PT1H47M',
 'genre': ['Comedy', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTcxMDc1NjcyNl5BMl5BanBnXkFtZTgwNDU0NDYxMzI@._V1_.jpg',
 'keywords': 'satire,black comedy,soviet union,nikita khrushchev '
             'character,based on comic book',
 'name': 'The Death of Stalin',
 'trailer': [{'@type': 'VideoObject',
              'description': "In the days following Stalin's collapse, his "
                             'core team of ministers tussle for control; some '
                             'want positive change in the Soviet Union, others '
                             'have more sinister motives. Their one common '
                             "trait? They're all just desperately trying to "
                             'remain alive.',
              'embedUrl': '/video/imdb/vi1778169881',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMzNjYWE2OWUtNWE5Zi00MGFkLTkxNmUtM2JjOGI4MWUzYTBjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMzNjYWE2OWUtNWE5Zi00MGFkLTkxNmUtM2JjOGI4MWUzYTBjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
              'uploadDate': '2018-01-17T21:00:25Z'}],
 'url': '/title/tt4686844/'}