{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2017-04-09',
 'EntryPath': 'Favorites/Movies/snapshot/The-Founder',
 'EntryURL': 'https://www.imdb.com/title/tt4276820',
 'Entry_json': 'Favorites/Movies/snapshot/The-Founder/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Founder/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Founder/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Michael Keaton',
            'url': '/name/nm0000474/'},
           {'@type': 'Person',
            'name': 'Nick Offerman',
            'url': '/name/nm0644406/'},
           {'@type': 'Person',
            'name': 'John Carroll Lynch',
            'url': '/name/nm0002253/'},
           {'@type': 'Person',
            'name': 'Linda Cardellini',
            'url': '/name/nm0004802/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 112738,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Robert Siegel',
              'url': '/name/nm1557909/'},
             {'@type': 'Organization', 'url': '/company/co0150452/'},
             {'@type': 'Organization', 'url': '/company/co0251858/'},
             {'@type': 'Organization', 'url': '/company/co0273107/'},
             {'@type': 'Organization', 'url': '/company/co0336582/'}],
 'datePublished': '2016-11-24',
 'description': 'The Founder is a movie starring Michael Keaton, Nick '
                'Offerman, and John Carroll Lynch. The story of Ray Kroc, a '
                "salesman who turned two brothers' innovative fast food "
                "eatery, McDonald's, into the biggest restaurant business in "
                'the...',
 'director': [{'@type': 'Person',
               'name': 'John Lee Hancock',
               'url': '/name/nm0359387/'}],
 'duration': 'PT1H55M',
 'genre': ['Biography', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzExNDg0MDk1M15BMl5BanBnXkFtZTgwNzE1Mjg0MDI@._V1_.jpg',
 'keywords': 'f word,swindle,burger,franchising,ambition',
 'name': 'The Founder',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Ray Kroc, a struggling salesman from Illinois, '
                             'meets Mac and Dick McDonald, co-operators of a '
                             'burger restaurant in 1950s Southern California.',
              'embedUrl': '/video/imdb/vi1128052249',
              'name': 'New Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ5Mzg4NDg5MV5BMl5BanBnXkFtZTgwMTkwNDEwMTI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ5Mzg4NDg5MV5BMl5BanBnXkFtZTgwMTkwNDEwMTI@._V1_.jpg',
              'uploadDate': '2017-01-04T04:28:04Z'}],
 'url': '/title/tt4276820/'}