{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Fire-In-Paradise',
 'EntryURL': 'https://www.imdb.com/title/tt11127056',
 'Entry_json': 'Favorites/Movies/snapshot/Fire-In-Paradise/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Fire-In-Paradise/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Fire-In-Paradise/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Joy Beeson',
            'url': '/name/nm11110567/'},
           {'@type': 'Person',
            'name': 'Beth Bowersox',
            'url': '/name/nm11109661/'},
           {'@type': 'Person',
            'name': 'Abbie Davis',
            'url': '/name/nm11109676/'},
           {'@type': 'Person',
            'name': 'Jennifer Johnson',
            'url': '/name/nm8115110/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 567,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'datePublished': '2019-11-01',
 'description': 'Fire in Paradise is a short starring Joy Beeson, Beth '
                'Bowersox, and Abbie Davis. On 8th November, 2018, a fire '
                'broke out in California near the town of Paradise. Over the '
                'course of a few hours, the Camp Fire grew into the '
                "country's...",
 'director': [{'@type': 'Person',
               'name': 'Zackary Canepari',
               'url': '/name/nm2558972/'},
              {'@type': 'Person',
               'name': 'Drea Cooper',
               'url': '/name/nm2645985/'}],
 'duration': 'PT39M',
 'genre': ['Documentary', 'Short'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOWJiMGU2YTEtMjQ5Zi00MTdlLTkxODgtNmM0ODhiODQwNWUzXkEyXkFqcGdeQXVyMTc2MzUwMjQ@._V1_.jpg',
 'name': 'Fire in Paradise',
 'url': '/title/tt11127056/'}