{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Mirrors-Edge-Catalyst',
 'EntryURL': 'https://rawg.io/games/mirrors-edge-catalyst',
 'Entry_json': 'Favorites/Games/snapshot/Mirrors-Edge-Catalyst/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Mirrors-Edge-Catalyst/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Mirrors-Edge-Catalyst/thumb.jpg',
 'added': 1411,
 'background_image': 'https://media.rawg.io/media/games/257/257c497aa4060f4a697ccbf5e99ec230.jpg',
 'developers': ['Electronic Arts'],
 'genres': ['Action'],
 'name': "Mirror's Edge Catalyst",
 'platforms': ['Xbox One', 'PlayStation 4', 'PC'],
 'publishers': ['Electronic Arts'],
 'released': '2016-06-07',
 'slug': 'mirrors-edge-catalyst'}