{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Catch-Me-If-You-Can',
 'EntryURL': 'https://www.imdb.com/title/tt0264464',
 'Entry_json': 'Favorites/Movies/snapshot/Catch-Me-If-You-Can/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Catch-Me-If-You-Can/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Catch-Me-If-You-Can/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Leonardo DiCaprio',
            'url': '/name/nm0000138/'},
           {'@type': 'Person', 'name': 'Tom Hanks', 'url': '/name/nm0000158/'},
           {'@type': 'Person',
            'name': 'Christopher Walken',
            'url': '/name/nm0000686/'},
           {'@type': 'Person',
            'name': 'Martin Sheen',
            'url': '/name/nm0000640/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 785671,
                      'ratingValue': '8.1',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Jeff Nathanson',
              'url': '/name/nm0622288/'},
             {'@type': 'Person',
              'name': 'Frank Abagnale Jr.',
              'url': '/name/nm0007646/'},
             {'@type': 'Person',
              'name': 'Stan Redding',
              'url': '/name/nm1127221/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0084134/'},
             {'@type': 'Organization', 'url': '/company/co0112912/'},
             {'@type': 'Organization', 'url': '/company/co0108321/'},
             {'@type': 'Organization', 'url': '/company/co0009119/'},
             {'@type': 'Organization', 'url': '/company/co0005803/'}],
 'datePublished': '2002-12-25',
 'description': 'Catch Me If You Can is a movie starring Leonardo DiCaprio, '
                'Tom Hanks, and Christopher Walken. A seasoned FBI agent '
                'pursues Frank Abagnale Jr. who, before his 19th birthday, '
                "successfully forged millions of dollars' worth of checks...",
 'director': [{'@type': 'Person',
               'name': 'Steven Spielberg',
               'url': '/name/nm0000229/'}],
 'duration': 'PT2H21M',
 'genre': ['Biography', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_.jpg',
 'keywords': 'race against time,mother son '
             'relationship,revenge,deception,investigation',
 'name': 'Catch Me If You Can',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Dreamworks',
              'embedUrl': '/video/imdb/vi1220346137',
              'name': 'Catch Me If You Can',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZWQxM2UxZTUtMzFlZS00YTVjLWFkNzctZjQzZjMwN2ZlNTllXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZWQxM2UxZTUtMzFlZS00YTVjLWFkNzctZjQzZjMwN2ZlNTllXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T13:05:05Z'}],
 'url': '/title/tt0264464/'}