<?php
$infoArray = array('Actors' => array('Edie Falco&tv',
            'Louis CK&tv',
            'Steve Buscemi&tv',
            'Steven Wright&tv'),
 'Added' => '2016-03-12',
 'Countries' => array('USA'),
 'Description' => "\nHorace and Pete: Horace and Pete (stylized as Horace and Pete's Est. 1916) is an American comedy-drama web series created by Louis C.K. starring himself and Steve Buscemi as Horace and Pete, co-owners of an Irish bar, Horace and Pete's. ",
 'Director' => array('NA'),
 'Genres' => array('Comedy&tv', 'Drama&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt5425186',
 'PrimeWire' => 'http://www.primewire.ag/tv-2774738-Horace-and-Pete',
 'Ratings' => array('IMDB' => '8.6/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.93/5',
             'RT' => 'N/A',
             'Votes' => '101'),
 'Released' => '2016-01-30',
 'Runtime' => '67 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2774738_Horace_and_Pete_2016_47.jpg',
 'Title' => 'Horace-and-Pete');
?>