{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Red-Dead-Redemption-2',
 'EntryURL': 'https://rawg.io/games/red-dead-redemption-2',
 'Entry_json': 'Favorites/Games/snapshot/Red-Dead-Redemption-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Red-Dead-Redemption-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Red-Dead-Redemption-2/thumb.jpg',
 'added': 7466,
 'background_image': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg',
 'developers': ['Rockstar Games'],
 'genres': ['Action', 'Adventure', 'RPG'],
 'name': 'Red Dead Redemption 2',
 'platforms': ['PC', 'Xbox One', 'PlayStation 4'],
 'publishers': ['Rockstar Games'],
 'released': '2018-10-26',
 'slug': 'red-dead-redemption-2'}