<?php
$infoArray = array('Actors' => array('Ben Reed',
            'Bradley Cooper',
            'Jake McDorman',
            "Keir O'Donnell",
            'Kyle Gallner',
            'Marnette Patterson',
            'Sienna Miller'),
 'Added' => '2015-01-18',
 'Countries' => array('USA'),
 'Description' => "\nAmerican Sniper: Navy SEAL sniper Chris Kyle's pinpoint accuracy saves countless lives on the battlefield and turns him into a legend. Back home to his wife and kids after four tours of duty, however, Chris finds that it is the war he can't leave behind. ",
 'Director' => array('Clint Eastwood'),
 'Genres' => array('Action', 'Biography', 'Thriller', 'War'),
 'IMDB' => 'http://www.imdb.com/title/tt2179136',
 'PrimeWire' => 'http://www.primewire.ag/watch-2756355-American-Sniper',
 'Ratings' => array('IMDB' => '7.4/10',
             'Metascore' => '72%',
             'PrimeWire' => '3.88/5',
             'RT' => '72%',
             'Votes' => '2530'),
 'Released' => '2014-12-25',
 'Runtime' => '132 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2756355_American_Sniper_2014_50.jpg',
 'Title' => 'American-Sniper');
?>