{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-01-18',
 'EntryPath': 'Favorites/Movies/snapshot/American-Sniper',
 'EntryURL': 'https://www.imdb.com/title/tt2179136',
 'Entry_json': 'Favorites/Movies/snapshot/American-Sniper/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/American-Sniper/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/American-Sniper/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bradley Cooper',
            'url': '/name/nm0177896/'},
           {'@type': 'Person',
            'name': 'Sienna Miller',
            'url': '/name/nm1092227/'},
           {'@type': 'Person',
            'name': 'Kyle Gallner',
            'url': '/name/nm0973177/'},
           {'@type': 'Person',
            'name': 'Cole Konis',
            'url': '/name/nm6518675/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 427796,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jason Hall',
              'url': '/name/nm0355699/'},
             {'@type': 'Person',
              'name': 'Chris Kyle',
              'url': '/name/nm4881574/'},
             {'@type': 'Person',
              'name': 'Scott McEwen',
              'url': '/name/nm6984200/'},
             {'@type': 'Person',
              'name': 'Jim DeFelice',
              'url': '/name/nm7198520/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0108864/'},
             {'@type': 'Organization', 'url': '/company/co0449458/'},
             {'@type': 'Organization', 'url': '/company/co0034487/'},
             {'@type': 'Organization', 'url': '/company/co0373725/'},
             {'@type': 'Organization', 'url': '/company/co0010258/'},
             {'@type': 'Organization', 'url': '/company/co0176310/'}],
 'datePublished': '2015-01-01',
 'description': 'American Sniper is a movie starring Bradley Cooper, Sienna '
                "Miller, and Kyle Gallner. Navy S.E.A.L. sniper Chris Kyle's "
                'pinpoint accuracy saves countless lives on the battlefield '
                'and turns him into a legend. Back home with his family...',
 'director': [{'@type': 'Person',
               'name': 'Clint Eastwood',
               'url': '/name/nm0000142/'}],
 'duration': 'PT2H13M',
 'genre': ['Action', 'Biography', 'Drama', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTkxNzI3ODI4Nl5BMl5BanBnXkFtZTgwMjkwMjY4MjE@._V1_.jpg',
 'keywords': 'assassin,violence,iraq war,sniper,mercenary',
 'name': 'American Sniper',
 'trailer': [{'@type': 'VideoObject',
              'description': "Navy SEAL sniper Chris Kyle's pinpoint accuracy "
                             'saves countless lives on the battlefield and '
                             'turns him into a legend. Back home to his wife '
                             'and kids after four tours of duty, however, '
                             "Chris finds that it is the war he can't leave "
                             'behind.',
              'embedUrl': '/video/imdb/vi3484134937',
              'name': 'Theatrical Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTg0ODI0NDY5M15BMl5BanBnXkFtZTgwMTc3MTU3MzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTg0ODI0NDY5M15BMl5BanBnXkFtZTgwMTc3MTU3MzE@._V1_.jpg',
              'uploadDate': '2014-12-19T10:52:37Z'}],
 'url': '/title/tt2179136/'}