{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Grand-Theft-Auto-San-Andreas',
 'EntryURL': 'https://rawg.io/games/grand-theft-auto-san-andreas',
 'Entry_json': 'Favorites/Games/snapshot/Grand-Theft-Auto-San-Andreas/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Grand-Theft-Auto-San-Andreas/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Grand-Theft-Auto-San-Andreas/thumb.jpg',
 'added': 5798,
 'background_image': 'https://media.rawg.io/media/games/1bb/1bb86c35ffa3eb0d299b01a7c65bf908.jpg',
 'developers': ['Rockstar North', 'War Drum Studios'],
 'genres': ['Action', 'Adventure'],
 'name': 'Grand Theft Auto: San Andreas',
 'platforms': ['PC',
               'iOS',
               'macOS',
               'Android',
               'PlayStation 3',
               'Xbox 360',
               'PlayStation 2',
               'Xbox'],
 'publishers': ['1C-SoftClub', 'Capcom', 'Rockstar Games'],
 'released': '2004-10-26',
 'slug': 'grand-theft-auto-san-andreas'}