<?php
$infoArray = array('Actors' => array('David Austin&tv',
            'Erin Cummings&tv',
            'John Hannah&tv',
            'Lucy Lawless&tv',
            'Manu Bennett&tv',
            'Peter Mensah&tv',
            'Raicho Vasilev&tv'),
 'Added' => '2011-10-18',
 'Countries' => array('USA'),
 'Description' => '\nSpartacus Blood and Sand: Betrayed by the Romans. Forced into slavery. Reborn as a Gladiator. The classic tale of the Republic\x92s most infamous rebel comes alive in the graphic and visceral new series, Spartacus: Blood and Sand. Torn from his homeland and the woman he loves, Spartacus is condemned to the brutal world of the arena where blood and death are primetime entertainment. But not all battles are fought upon the sands. Treachery, corruption, and the allure of sensual pleasures will constantly test Spartacus. To survive, he must become more than a man. More than a gladiator. He must become a legend.\n',
 'Director' => array(),
 'Genres' => array('Action&tv', 'Drama&tv', 'Fantasy&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt1442449',
 'PrimeWire' => 'http://www.primewire.ag/tv-26862-Spartacus-Blood-and-Sand',
 'Ratings' => array('IMDB' => '8.7/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.40/5',
             'RT' => 'N/A',
             'Votes' => '2396'),
 'Released' => '2010-01-22',
 'Runtime' => '60 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/26862_Spartacus_Blood_and_Sand_-0001.jpg',
 'Title' => 'Spartacus-Blood-and-Sand');
?>