{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Prince-Of-Persia-The-Sands-Of-Time',
 'EntryURL': 'https://rawg.io/games/prince-of-persia-the-sands-of-time',
 'Entry_json': 'Favorites/Games/snapshot/Prince-Of-Persia-The-Sands-Of-Time/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Prince-Of-Persia-The-Sands-Of-Time/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Prince-Of-Persia-The-Sands-Of-Time/thumb.jpg',
 'added': 1614,
 'background_image': 'https://media.rawg.io/media/games/99b/99b39612e864d6ddfdb2c407fd9010a1.jpg',
 'developers': ['Kudosoft', 'Ubisoft', 'Ubisoft Montreal'],
 'genres': ['Action', 'Adventure', 'Platformer'],
 'name': 'Prince of Persia: The Sands of Time',
 'platforms': ['Xbox', 'GameCube', 'PlayStation 3', 'PC', 'PlayStation 2'],
 'publishers': ['Ubisoft Entertainment'],
 'released': '2003-10-28',
 'slug': 'prince-of-persia-the-sands-of-time'}