{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2017-05-14',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Get-Out',
 'EntryURL': 'https://www.imdb.com/title/tt5052448',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Get-Out/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Get-Out/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Get-Out/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Daniel Kaluuya',
            'url': '/name/nm2257207/'},
           {'@type': 'Person',
            'name': 'Allison Williams',
            'url': '/name/nm4129745/'},
           {'@type': 'Person',
            'name': 'Bradley Whitford',
            'url': '/name/nm0925966/'},
           {'@type': 'Person',
            'name': 'Catherine Keener',
            'url': '/name/nm0001416/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 461408,
                     'ratingValue': '7.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jordan Peele',
              'url': '/name/nm1443502/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0098315/'},
             {'@type': 'Organization', 'url': '/company/co0555595/'},
             {'@type': 'Organization', 'url': '/company/co0369235/'},
             {'@type': 'Organization', 'url': '/company/co0169264/'},
             {'@type': 'Organization', 'url': '/company/co0055529/'}],
 'datePublished': '2017-02-24',
 'description': 'Get Out is a movie starring Daniel Kaluuya, Allison Williams, '
                'and Bradley Whitford. A young African-American visits his '
                "white girlfriend's parents for the weekend, where his "
                'simmering uneasiness about their reception of him...',
 'director': {'@type': 'Person',
              'name': 'Jordan Peele',
              'url': '/name/nm1443502/'},
 'duration': 'PT1H44M',
 'genre': ['Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_.jpg',
 'keywords': 'hypnosis,neurosurgeon,abduction,racism,brain surgery',
 'name': 'Get Out',
 'trailer': {'@type': 'VideoObject',
             'description': 'When a young African-American man visits his '
                            "white girlfriend's family estate, he becomes "
                            'ensnared in a more sinister real reason for the '
                            'invitation.',
             'embedUrl': '/video/imdb/vi2005186073',
             'name': 'Trailer #1',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDI0NjU3MTc3NF5BMl5BanBnXkFtZTgwNDc5MTMyMDI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDI0NjU3MTc3NF5BMl5BanBnXkFtZTgwNDc5MTMyMDI@._V1_.jpg',
             'uploadDate': '2016-10-05T05:37:22Z'},
 'url': '/title/tt5052448/'}