<?php
$infoArray = array('Actors' => array(' Betty Gabriel ',
            ' Caleb Landry Jones ',
            ' Lakeith Stanfield ',
            ' Marcus Henderson ',
            ' Stephen Root ',
            'Allison Williams',
            'Bradley Whitford',
            'Catherine Keener',
            'LaKeith Stanfield'),
 'Added' => '2017-05-14',
 'Countries' => array('USA'),
 'Description' => "\nGet Out: A young African-American man visits his Caucasian girlfriend's mysterious family estate. ",
 'Director' => array('Jordan Peele'),
 'Genres' => array('Comedy', 'Horror', 'Mystery'),
 'IMDB' => 'http://www.imdb.com/title/tt5052448',
 'PrimeWire' => 'http://www.primewire.ag/watch-2790906-Get-Out',
 'Ratings' => array('IMDB' => '5.7/10',
             'Metascore' => '80%',
             'PrimeWire' => '3.83/5',
             'RT' => '100%',
             'Votes' => '928'),
 'Released' => '2017-02-24',
 'Runtime' => '130 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2790906_Get_Out_2017.jpg',
 'Title' => 'Get-Out');
?>