{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Beyond-Two-Souls',
 'EntryURL': 'https://rawg.io/games/beyond-two-souls',
 'Entry_json': 'Favorites/Games/snapshot/Beyond-Two-Souls/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Beyond-Two-Souls/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Beyond-Two-Souls/thumb.jpg',
 'added': 3362,
 'background_image': 'https://media.rawg.io/media/games/aec/aecba5e6cf8713b3864a280efa110c0a.jpg',
 'developers': ['Quantic Dream'],
 'genres': ['Action', 'Adventure'],
 'name': 'BEYOND: Two Souls',
 'platforms': ['PlayStation 4', 'PC', 'PlayStation 3'],
 'publishers': ['Sony Computer Entertainment', 'Quantic Dream'],
 'released': '2013-10-08',
 'slug': 'beyond-two-souls'}