{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-12-22',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Perfume-The-Story-of-a-Murderer',
 'EntryURL': 'https://www.imdb.com/title/tt0396171',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Perfume-The-Story-of-a-Murderer/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Perfume-The-Story-of-a-Murderer/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Perfume-The-Story-of-a-Murderer/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ben Whishaw',
            'url': '/name/nm0924210/'},
           {'@type': 'Person',
            'name': 'Dustin Hoffman',
            'url': '/name/nm0000163/'},
           {'@type': 'Person',
            'name': 'Alan Rickman',
            'url': '/name/nm0000614/'},
           {'@type': 'Person',
            'name': 'Francesc Albiol',
            'url': '/name/nm0016852/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 229206,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Birkin',
              'url': '/name/nm0001949/'},
             {'@type': 'Person',
              'name': 'Bernd Eichinger',
              'url': '/name/nm0251536/'},
             {'@type': 'Person',
              'name': 'Tom Tykwer',
              'url': '/name/nm0878756/'},
             {'@type': 'Person',
              'name': 'Patrick Süskind',
              'url': '/name/nm0845752/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0002257/'},
             {'@type': 'Organization', 'url': '/company/co0319096/'},
             {'@type': 'Organization', 'url': '/company/co0139788/'},
             {'@type': 'Organization', 'url': '/company/co0076272/'},
             {'@type': 'Organization', 'url': '/company/co0080776/'},
             {'@type': 'Organization', 'url': '/company/co0142412/'},
             {'@type': 'Organization', 'url': '/company/co0074041/'},
             {'@type': 'Organization', 'url': '/company/co0114672/'},
             {'@type': 'Organization', 'url': '/company/co0002254/'},
             {'@type': 'Organization', 'url': '/company/co0090290/'},
             {'@type': 'Organization', 'url': '/company/co0056024/'},
             {'@type': 'Organization', 'url': '/company/co0066028/'},
             {'@type': 'Organization', 'url': '/company/co0027719/'},
             {'@type': 'Organization', 'url': '/company/co0224298/'},
             {'@type': 'Organization', 'url': '/company/co0032081/'},
             {'@type': 'Organization', 'url': '/company/co0163700/'},
             {'@type': 'Organization', 'url': '/company/co0004166/'},
             {'@type': 'Organization', 'url': '/company/co0046206/'}],
 'datePublished': '2006-09-14',
 'description': 'Perfume: The Story of a Murderer is a movie starring Ben '
                'Whishaw, Dustin Hoffman, and Alan Rickman. Jean-Baptiste '
                'Grenouille, born with a superior olfactory sense, creates the '
                "world's finest perfume. His work, however, takes a dark...",
 'director': {'@type': 'Person',
              'name': 'Tom Tykwer',
              'url': '/name/nm0878756/'},
 'duration': 'PT2H27M',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI0NjUyMTk3Nl5BMl5BanBnXkFtZTcwOTA5MzkzMQ@@._V1_.jpg',
 'keywords': '18th century,smell,scent,perfume,sense of smell',
 'name': 'Perfume: The Story of a Murderer',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'beeltink'},
            'dateCreated': '2006-09-20',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0396171/'},
            'name': 'Great movie, very good attempt to describe the book '
                    'without being violent.',
            'reviewBody': "I don't understand people who say this movie is "
                          'dull, boring or bad. I guess these people are only '
                          'into mindless action-movies with simple dialog '
                          'where people get slaughtered in a brutal and '
                          'visually gory way. If you have a mind and you are '
                          'able to think, this movie maybe something for you. '
                          'The characters in the movie are strong, you '
                          'sympathize with them easily. It is upsetting why '
                          'the main character is killing the girls, as it is '
                          'actually unnecessary. The sceneries and costumes '
                          'look great. I felt like I was there. The movie '
                          'shows moderate violence, which is all just '
                          "suggestive, you don't see any blood. I give this "
                          "movie 8 points. It is a good movie, which I'd "
                          'recommend to my friends.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '8',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Paramount Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi4003135769',
             'name': 'Perfume: The Story of a Murderer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMGQxYzE3ZTAtMTg0MC00MzlhLTgwZTEtNzBmNjkyZjBmZTU1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMGQxYzE3ZTAtMTg0MC00MzlhLTgwZTEtNzBmNjkyZjBmZTU1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T15:23:03Z'},
 'url': '/title/tt0396171/'}