{'Actors': ['Alan Rickman',
            'Ben Whishaw',
            'Birgit Minichmayr',
            'Bridget McConnell',
            'Carme Capdet',
            'Carmen Contreras',
            'Corinna Harfouch',
            'David Calder',
            'Derek Smee',
            'Duna Jove',
            'Dustin Hoffman',
            'Enric Arquimbau',
            'Ferm&#xED; Reixach',
            'Francesc Albiol',
            'Gonzalo Cunill',
            'Harris Gordon',
            'Jerome Willis',
            'Jessica Schwarz',
            'Joanna Griffiths',
            'John Hurt',
            'Karoline Herfurth',
            'Michael Smiley',
            'Miquel Bordoy',
            'Paul Berrondo',
            'Pedro Gutierrez',
            'Reg Wilson',
            'Sam Douglas',
            'Sian Thomas',
            'Simon Chandler',
            'Timothy Davies'],
 'Added': '2013-12-22',
 'Countries': ['Germany', 'France', 'Spain', 'USA'],
 'Description': '\n'
                'Perfume: The Story of a Murderer: Jean-Baptiste Grenouille, '
                "born with a superior olfactory sense, creates the world's "
                'finest perfume. His work, however, takes a dark turn as he '
                'searches for the ultimate scent. ',
 'Director': ['Tom Tykwer'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Perfume-The-Story-of-a-Murderer',
 'EntryURL': 'http://www.imdb.com/title/tt0396171',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Perfume-The-Story-of-a-Murderer/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Perfume-The-Story-of-a-Murderer/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Perfume-The-Story-of-a-Murderer/info.py',
 'Genres': ['Drama', 'Thriller', 'Romance', 'Crime'],
 'IMDB': 'http://www.imdb.com/title/tt0396171',
 'PrimeWire': 'http://www.primewire.ag/watch-5982-Perfume-The-Story-of-a-Murderer',
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': '56%',
             'PrimeWire': '4.11/5',
             'RT': '58%',
             'Votes': '867'},
 'Released': '2006-09-07',
 'Runtime': '147 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5982_Perfume_The_Story_of_a_Murderer_2006.jpg',
 'Title': 'Perfume-The-Story-of-a-Murderer'}