{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-11-09',
 'EntryPath': 'Favorites/TV/snapshot/Robot-Chicken',
 'EntryURL': 'https://www.imdb.com/title/tt0437745',
 'Entry_json': 'Favorites/TV/snapshot/Robot-Chicken/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Robot-Chicken/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Robot-Chicken/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Seth Green', 'url': '/name/nm0001293/'},
           {'@type': 'Person',
            'name': 'Matthew Senreich',
            'url': '/name/nm1803552/'},
           {'@type': 'Person',
            'name': 'Breckin Meyer',
            'url': '/name/nm0005227/'},
           {'@type': 'Person', 'name': 'Tom Root', 'url': '/name/nm1802814/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 38685,
                     'ratingValue': '7.7',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Matthew Senreich',
              'url': '/name/nm1803552/'},
             {'@type': 'Person',
              'name': 'Seth Green',
              'url': '/name/nm0001293/'},
             {'@type': 'Person',
              'name': 'Mike Fasolo',
              'url': '/name/nm1827639/'},
             {'@type': 'Organization', 'url': '/company/co0378918/'},
             {'@type': 'Organization', 'url': '/company/co0103531/'},
             {'@type': 'Organization', 'url': '/company/co0043801/'},
             {'@type': 'Organization', 'url': '/company/co0074006/'},
             {'@type': 'Organization', 'url': '/company/co0086397/'},
             {'@type': 'Organization', 'url': '/company/co0142485/'},
             {'@type': 'Organization', 'url': '/company/co0008281/'}],
 'datePublished': '2005-02-20',
 'description': 'Robot Chicken is a TV series starring Seth Green, Matthew '
                'Senreich, and Breckin Meyer. Pop culture references fly thick '
                'and fast as stop-motion animation is featured in sketches '
                'lampooning everything from television movies to comic...',
 'genre': ['Animation', 'Adventure', 'Comedy', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzcyMjQzYjQtNTU2My00ZjQ1LWI4NGEtODVjM2UwYjU5NDAzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': '2000s,2010s,animal in series title,bird in series title,toy',
 'name': 'Robot Chicken',
 'trailer': {'@type': 'VideoObject',
             'description': 'Watch the Season 9 Trailer that "Robot Chicken" '
                            'brought to Comic-Con 2017.',
             'embedUrl': '/video/imdb/vi3905927449',
             'name': 'Season 9 Comic-Con Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMmViYTVkYmEtOWE3MC00MDQ0LTk0MTgtMjlhMzQ4MGU2YTkxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMmViYTVkYmEtOWE3MC00MDQ0LTk0MTgtMjlhMzQ4MGU2YTkxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
             'uploadDate': '2017-07-21T23:36:42Z'},
 'url': '/title/tt0437745/'}