<?php
$infoArray = array('Actors' => array('Bob Odenkirk&tv',
            'Jonathan Banks&tv',
            'Michael McKean&tv',
            'Patrick Fabian&tv',
            'Rhea Seehorn&tv'),
 'Added' => '2015-02-11',
 'Countries' => array('USA'),
 'Description' => '\nBetter Call Saul: The trials and tribulations of criminal lawyer, Saul Goodman, in the time leading up to establishing his strip-mall law office in Albuquerque, New Mexico. ',
 'Director' => array('NA'),
 'Genres' => array('Comedy&tv', 'Crime&tv', 'Drama&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt3032476',
 'PrimeWire' => 'http://www.primewire.ag/tv-2757832-Better-Call-Saul',
 'Ratings' => array('IMDB' => '9.3/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.53/5',
             'RT' => 'N/A',
             'Votes' => '968'),
 'Released' => '2015-02-08',
 'Runtime' => '60 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2757832_Better_Call_Saul_2015.jpg',
 'Title' => 'Better-Call-Saul');
?>