{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Hot-Girls-Wanted',
 'EntryURL': 'https://www.imdb.com/title/tt4382552',
 'Entry_json': 'Favorites/Movies/snapshot/Hot-Girls-Wanted/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Hot-Girls-Wanted/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Hot-Girls-Wanted/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Farrah Laurel Abraham',
            'url': '/name/nm4766272/'},
           {'@type': 'Person',
            'name': 'John Anthony',
            'url': '/name/nm7361618/'},
           {'@type': 'Person',
            'name': 'Rachel Bernard',
            'url': '/name/nm6367070/'},
           {'@type': 'Person',
            'name': 'Carrie Brooks',
            'url': '/name/nm6844809/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 15064,
                     'ratingValue': '6.1',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Brittany Huckabee',
              'url': '/name/nm1628158/'},
             {'@type': 'Organization', 'url': '/company/co0376609/'}],
 'datePublished': '2015-05-29',
 'description': 'Hot Girls Wanted is a movie starring Farrah Laurel Abraham, '
                'John Anthony, and Rachel Bernard. A documentary about young '
                'women who have been drawn into the sex trade - and how easy '
                'it is for a web-savvy generation to end up making...',
 'director': [{'@type': 'Person',
               'name': 'Jill Bauer',
               'url': '/name/nm4991098/'},
              {'@type': 'Person',
               'name': 'Ronna Gradus',
               'url': '/name/nm4991143/'}],
 'duration': 'PT1H24M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTcyMjU5NjAwN15BMl5BanBnXkFtZTgwOTM1MTc4NTE@._V1_.jpg',
 'keywords': 'freedom of choice,porn actress,victimization porn,exploring '
             'sexuality,independent woman',
 'name': 'Hot Girls Wanted',
 'trailer': {'@type': 'VideoObject',
             'description': 'Official Trailer',
             'embedUrl': '/video/imdb/vi87601177',
             'name': 'Hot Girls Wanted - Documentary on Netflix',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjQxMjM2NjQwNV5BMl5BanBnXkFtZTgwOTQxOTk4NTE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjQxMjM2NjQwNV5BMl5BanBnXkFtZTgwOTQxOTk4NTE@._V1_.jpg',
             'uploadDate': '2015-06-05T08:01:50Z'},
 'url': '/title/tt4382552/'}