{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hold-The-Dark',
 'EntryURL': 'https://www.imdb.com/title/tt5057140',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hold-The-Dark/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hold-The-Dark/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Hold-The-Dark/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jeffrey Wright',
            'url': '/name/nm0942482/'},
           {'@type': 'Person',
            'name': 'Alexander Skarsgård',
            'url': '/name/nm0002907/'},
           {'@type': 'Person',
            'name': 'James Badge Dale',
            'url': '/name/nm0197647/'},
           {'@type': 'Person',
            'name': 'Riley Keough',
            'url': '/name/nm2142336/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 31341,
                     'ratingValue': '5.6',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Macon Blair',
              'url': '/name/nm0086301/'},
             {'@type': 'Person',
              'name': 'William Giraldi',
              'url': '/name/nm8838215/'},
             {'@type': 'Organization', 'url': '/company/co0563088/'},
             {'@type': 'Organization', 'url': '/company/co0160719/'},
             {'@type': 'Organization', 'url': '/company/co0516938/'}],
 'datePublished': '2018-09-28',
 'description': 'Hold the Dark is a movie starring Jeffrey Wright, Alexander '
                'Skarsgård, and James Badge Dale. After the deaths of three '
                'children suspected to be killed by wolves, writer Russell '
                'Core is hired by the the mother of a missing...',
 'director': {'@type': 'Person',
              'name': 'Jeremy Saulnier',
              'url': '/name/nm1099918/'},
 'duration': 'PT2H5M',
 'genre': ['Drama', 'Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjMwOTQ1MzM3M15BMl5BanBnXkFtZTgwODQyNDQxNjM@._V1_.jpg',
 'keywords': 'alaska,wolves,cmnf,breasts,female full frontal nudity',
 'name': 'Hold the Dark',
 'trailer': {'@type': 'VideoObject',
             'embedUrl': '/video/imdb/vi2741811993',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYjc0Y2VlOWQtYzBkZC00MTUyLWI0MzEtMDQ5NDMxYTdjOGYyXkEyXkFqcGdeQXRzdGFzaWVr._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYjc0Y2VlOWQtYzBkZC00MTUyLWI0MzEtMDQ5NDMxYTdjOGYyXkEyXkFqcGdeQXRzdGFzaWVr._V1_.jpg',
             'uploadDate': '2018-09-10T20:38:11Z'},
 'url': '/title/tt5057140/'}