{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-06-25',
 'EntryPath': 'Favorites/TV/snapshot/The-Newsroom',
 'EntryURL': 'https://www.imdb.com/title/tt1870479',
 'Entry_json': 'Favorites/TV/snapshot/The-Newsroom/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Newsroom/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Newsroom/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jeff Daniels',
            'url': '/name/nm0001099/'},
           {'@type': 'Person',
            'name': 'Emily Mortimer',
            'url': '/name/nm0607865/'},
           {'@type': 'Person',
            'name': 'John Gallagher Jr.',
            'url': '/name/nm0302330/'},
           {'@type': 'Person',
            'name': 'Alison Pill',
            'url': '/name/nm0683467/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 101474,
                      'ratingValue': '8.6',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Aaron Sorkin',
              'url': '/name/nm0815070/'},
             {'@type': 'Organization', 'url': '/company/co0284741/'}],
 'datePublished': '2012-06-24',
 'description': 'The Newsroom is a TV series starring Jeff Daniels, Emily '
                'Mortimer, and John Gallagher Jr.. A newsroom undergoes some '
                'changes in its workings and morals as a new team is brought '
                'in, bringing unexpected results for its existing news...',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BZDI0OWIwMTgtZGIyOC00ODRhLWIwNjAtOWViZmMwOWYwOGViXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_.jpg',
 'keywords': 'newsroom,ethics,television producer,news reporting,television '
             'news',
 'name': 'The Newsroom',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi3499276825',
              'name': 'Season 3 Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjVjNmNhNTEtYWQyZi00OTljLWI1YjUtMGMyNGFlOWM4NDg2XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjVjNmNhNTEtYWQyZi00OTljLWI1YjUtMGMyNGFlOWM4NDg2XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
              'uploadDate': '2018-10-11T23:13:45Z'}],
 'url': '/title/tt1870479/'}