{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/Law-Abiding-Citizen',
 'EntryURL': 'https://www.imdb.com/title/tt1197624',
 'Entry_json': 'Favorites/Movies/snapshot/Law-Abiding-Citizen/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Law-Abiding-Citizen/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Law-Abiding-Citizen/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gerard Butler',
            'url': '/name/nm0124930/'},
           {'@type': 'Person', 'name': 'Jamie Foxx', 'url': '/name/nm0004937/'},
           {'@type': 'Person',
            'name': 'Leslie Bibb',
            'url': '/name/nm0004753/'},
           {'@type': 'Person',
            'name': 'Colm Meaney',
            'url': '/name/nm0000538/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 264112,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Kurt Wimmer',
              'url': '/name/nm0934483/'},
             {'@type': 'Organization', 'url': '/company/co0332840/'},
             {'@type': 'Organization', 'url': '/company/co0187451/'},
             {'@type': 'Organization', 'url': '/company/co0125213/'},
             {'@type': 'Organization', 'url': '/company/co0232271/'}],
 'datePublished': '2009-10-16',
 'description': 'Law Abiding Citizen is a movie starring Gerard Butler, Jamie '
                'Foxx, and Leslie Bibb. A frustrated man decides to take '
                'justice into his own hands after a plea bargain sets one of '
                "his family's killers free.",
 'director': [{'@type': 'Person',
               'name': 'F. Gary Gray',
               'url': '/name/nm0336620/'}],
 'duration': 'PT1H49M',
 'genre': ['Action', 'Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTMyODY1NTg1N15BMl5BanBnXkFtZTcwMTUyODI4Mg@@._V1_.jpg',
 'keywords': 'justice,terrorism,deal,investigation,criminal mastermind',
 'name': 'Law Abiding Citizen',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A clip from the movie Law Abiding Citizen.',
              'embedUrl': '/video/imdb/vi1598816793',
              'name': 'Law Abiding Citizen: "Don\'t Even Twitch"',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTU2MDQ2MTEzNl5BMl5BanBnXkFtZTcwNzk2ODA5Mg@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTU2MDQ2MTEzNl5BMl5BanBnXkFtZTcwNzk2ODA5Mg@@._V1_.jpg',
              'uploadDate': '2009-10-15T13:30:58Z'}],
 'url': '/title/tt1197624/'}