{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-09-22',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Battle-360',
 'EntryURL': 'https://www.imdb.com/title/tt1194698',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Battle-360/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Battle-360/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Battle-360/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Alan Pietruszewski',
            'url': '/name/nm1830016/'},
           {'@type': 'Person',
            'name': 'Garth R. Hassell',
            'url': '/name/nm1980080/'},
           {'@type': 'Person',
            'name': 'Pedro Sandoval',
            'url': '/name/nm3403284/'},
           {'@type': 'Person',
            'name': 'Richard Harte',
            'url': '/name/nm1479382/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 258,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0194193/'},
 'datePublished': '2008-02-29',
 'description': 'Battle 360 is a TV series starring Alan Pietruszewski, Garth '
                "R. Hassell, and Pedro Sandoval. This series chronicle's the "
                'illustrious battle history of the U.S.S. Enterprise which '
                'played a critical role in World War Two and for a...',
 'genre': ['Documentary', 'History', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjEzODY2NDY3MF5BMl5BanBnXkFtZTcwMjQyNTkxMw@@._V1_.jpg',
 'keywords': 'world war two,u.s. navy,sea battle,pacific theatre,naval battle',
 'name': 'Battle 360',
 'trailer': {'@type': 'VideoObject',
             'description': "Military Combat: Relive History's Most Intense "
                            'Battles: Vol 3',
             'embedUrl': '/video/imdb/vi1626520601',
             'name': "Military Combat: Relive History's Most Intense Battles: "
                     'Vol 3',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTYyYjllYTMtYmJlNi00NDJiLTkzZTQtZTE2MzdlZDUwOGY3XkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTYyYjllYTMtYmJlNi00NDJiLTkzZTQtZTE2MzdlZDUwOGY3XkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
             'uploadDate': '2019-04-28T13:09:30Z'},
 'url': '/title/tt1194698/'}