{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Visioneers',
 'EntryURL': 'https://www.imdb.com/title/tt0833557',
 'Entry_json': 'Favorites/Movies/snapshot/Visioneers/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Visioneers/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Visioneers/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Zach Galifianakis',
            'url': '/name/nm0302108/'},
           {'@type': 'Person', 'name': 'Judy Greer', 'url': '/name/nm0339460/'},
           {'@type': 'Person',
            'name': 'Mía Maestro',
            'url': '/name/nm0535502/'},
           {'@type': 'Person',
            'name': 'Missi Pyle',
            'url': '/name/nm0701512/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 5617,
                      'ratingValue': '6.0',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Brandon Drake',
              'url': '/name/nm2339710/'},
             {'@type': 'Organization', 'url': '/company/co0191766/'},
             {'@type': 'Organization', 'url': '/company/co0178523/'},
             {'@type': 'Organization', 'url': '/company/co0441920/'}],
 'datePublished': '2008-06-12',
 'description': 'Visioneers is a movie starring Zach Galifianakis, Judy Greer, '
                'and Mía Maestro. When people begin exploding from stress, '
                'George Washington Winsterhammerman tries to ignore the '
                'epidemic and live his usual life, but then he suffers his...',
 'director': [{'@type': 'Person',
               'name': 'Jared Drake',
               'url': '/name/nm2335574/'}],
 'duration': 'PT1H34M',
 'genre': ['Comedy', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTgwMDMyMzA3NV5BMl5BanBnXkFtZTcwNTgwNjA3MQ@@._V1_.jpg',
 'keywords': 'exploding body,happiness,corporate,satire,one word title',
 'name': 'Visioneers',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for this dark comedy',
              'embedUrl': '/video/imdb/vi111018521',
              'name': 'Visioneers',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTk4OTE1MjE5M15BMl5BanBnXkFtZTcwOTI0MTk1Mg@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTk4OTE1MjE5M15BMl5BanBnXkFtZTcwOTI0MTk1Mg@@._V1_.jpg',
              'uploadDate': '2009-05-24T05:39:18Z'}],
 'url': '/title/tt0833557/'}