{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Gallery-Episode-1-Call-Of-The-Starseed',
 'EntryURL': 'https://rawg.io/games/the-gallery-episode-1-call-of-the-starseed',
 'Entry_json': 'Favorites/Games/snapshot/The-Gallery-Episode-1-Call-Of-The-Starseed/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Gallery-Episode-1-Call-Of-The-Starseed/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Gallery-Episode-1-Call-Of-The-Starseed/thumb.jpg',
 'added': 133,
 'background_image': 'https://media.rawg.io/media/screenshots/b16/b16628d73a1796b7bcdb2e10be0052da.jpg',
 'developers': ['Cloudhead Games ltd.'],
 'genres': ['Adventure', 'Indie'],
 'name': 'The Gallery - Episode 1: Call of the Starseed',
 'platforms': ['PC'],
 'publishers': ['Cloudhead Games ltd.'],
 'released': '2016-04-05',
 'slug': 'the-gallery-episode-1-call-of-the-starseed'}