{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-06-21',
 'EntryPath': 'Favorites/Movies/snapshot/Predestination',
 'EntryURL': 'https://www.imdb.com/title/tt2397535',
 'Entry_json': 'Favorites/Movies/snapshot/Predestination/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Predestination/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Predestination/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ethan Hawke',
            'url': '/name/nm0000160/'},
           {'@type': 'Person',
            'name': 'Sarah Snook',
            'url': '/name/nm3512758/'},
           {'@type': 'Person',
            'name': 'Noah Taylor',
            'url': '/name/nm0852965/'},
           {'@type': 'Person',
            'name': 'Madeleine West',
            'url': '/name/nm0922210/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 241692,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Michael Spierig',
              'url': '/name/nm1294961/'},
             {'@type': 'Person',
              'name': 'Peter Spierig',
              'url': '/name/nm1294962/'},
             {'@type': 'Person',
              'name': 'Robert A. Heinlein',
              'url': '/name/nm0374423/'},
             {'@type': 'Organization', 'url': '/company/co0234956/'},
             {'@type': 'Organization', 'url': '/company/co0311163/'},
             {'@type': 'Organization', 'url': '/company/co0380601/'},
             {'@type': 'Organization', 'url': '/company/co0380544/'},
             {'@type': 'Organization', 'url': '/company/co0222021/'}],
 'datePublished': '2014-06-13',
 'description': 'Predestination is a movie starring Ethan Hawke, Sarah Snook, '
                'and Noah Taylor. For his final assignment, a top temporal '
                'agent must pursue the one criminal that has eluded him '
                'throughout time. The chase turns into a unique, surprising...',
 'director': [{'@type': 'Person',
               'name': 'Michael Spierig',
               'url': '/name/nm1294961/'},
              {'@type': 'Person',
               'name': 'Peter Spierig',
               'url': '/name/nm1294962/'}],
 'duration': 'PT1H37M',
 'genre': ['Action', 'Adventure', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTAzODc3NjU1NzNeQTJeQWpwZ15BbWU4MDk5NTQ4NTMx._V1_.jpg',
 'keywords': 'time travel,temporal agent,time machine,time paradox,in love '
             'with oneself',
 'name': 'Predestination',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A Temporal Agent is sent on an intricate series '
                             'of time-travel journeys designed to ensure the '
                             'continuation of his law enforcement career for '
                             'eternity. Now, on his final assignment, he must '
                             'pursue the one criminal that has eluded him '
                             'throughout time.',
              'embedUrl': '/video/imdb/vi100904729',
              'name': 'International Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjIzMTIzNzYyNV5BMl5BanBnXkFtZTgwNTQwMDE0MzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjIzMTIzNzYyNV5BMl5BanBnXkFtZTgwNTQwMDE0MzE@._V1_.jpg',
              'uploadDate': '2014-11-12T10:20:32Z'}],
 'url': '/title/tt2397535/'}