{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-10-09',
 'EntryPath': 'Favorites/Movies/snapshot/The-Rise-and-Rise-of-Bitcoin',
 'EntryURL': 'https://www.imdb.com/title/tt2821314',
 'Entry_json': 'Favorites/Movies/snapshot/The-Rise-and-Rise-of-Bitcoin/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Rise-and-Rise-of-Bitcoin/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Rise-and-Rise-of-Bitcoin/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gavin Andresen',
            'url': '/name/nm5609792/'},
           {'@type': 'Person',
            'name': 'Brian Armstrong',
            'url': '/name/nm5683556/'},
           {'@type': 'Person',
            'name': 'Margaux Avedisian',
            'url': '/name/nm5746260/'},
           {'@type': 'Person',
            'name': 'Vitalik Buterin',
            'url': '/name/nm6841677/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1354,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Patrick Lope',
              'url': '/name/nm3092181/'},
             {'@type': 'Person',
              'name': 'Daniel Mross',
              'url': '/name/nm5610178/'},
             {'@type': 'Person',
              'name': 'Nicholas Mross',
              'url': '/name/nm3907719/'},
             {'@type': 'Organization', 'url': '/company/co0359562/'},
             {'@type': 'Organization', 'url': '/company/co0328074/'},
             {'@type': 'Organization', 'url': '/company/co0418217/'}],
 'datePublished': '2014-10-10',
 'description': 'The Rise and Rise of Bitcoin is a movie starring Gavin '
                'Andresen, Brian Armstrong, and Margaux Avedisian. A computer '
                'programmer becomes fascinated with the digital currency '
                'Bitcoin, and through his involvement in the Bitcoin...',
 'director': [{'@type': 'Person',
               'name': 'Nicholas Mross',
               'url': '/name/nm3907719/'}],
 'duration': 'PT1H36M',
 'genre': ['Documentary', 'History', 'News'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE1NTc4OTAzMl5BMl5BanBnXkFtZTcwMjU0ODA0OQ@@._V1_.jpg',
 'keywords': 'computer',
 'name': 'The Rise and Rise of Bitcoin',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for The Rise and Rise of Bitcoin',
              'embedUrl': '/video/imdb/vi567258393',
              'name': 'The Rise and Rise of Bitcoin',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTdjMmI4YWEtNDM5NS00ZDAwLTkwOGItYzllZDEwNmY4ZGY5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTdjMmI4YWEtNDM5NS00ZDAwLTkwOGItYzllZDEwNmY4ZGY5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2014-05-04T05:12:23Z'}],
 'url': '/title/tt2821314/'}