{'Actors': [''],
 'Added': '2014-04-16',
 'Countries': [],
 'Description': "\nDivorce Corp: More money flows through the family courts, and into the hands of courthouse insiders, than in all other court systems in America combined - over $50 billion a year and growing. Through extensive research and interviews with the nation's top divorce lawyers, mediators, judges, politicians, litigants and journalists, this documentary uncovers how children are torn from their homes, unlicensed custody evaluators extort money, and abusive judges play god with people's lives while enriching their friends. This explosive documentary reveals the family courts as unregulated, extra-constitutional fiefdoms. Rather than assist victims of domestic crimes, these courts often precipitate them. And rather than help parents and children move on, as they are mandated to do, these courts - and their associates - drag out cases for years, sometimes decades, ultimately resulting in a rash of social ills, including home foreclosure, bankruptcy, suicide and violence. Solutions to the crisis are sought out in countries where divorce is handled in a more holistic manner. ",
 'Director': [],
 'Genres': ['Documentary', 'Drama', 'History'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2745532-Divorce-Corp',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '3.95/5',
             'RT': 'N/A',
             'Votes': '97'},
 'Released': '2014-01-10',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2745532_Divorce_Corp_2014.jpg',
 'Title': 'Divorce-Corp'}