{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-04-16',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Divorce-Corp',
 'EntryURL': 'https://www.imdb.com/title/tt2636456',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Divorce-Corp/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Divorce-Corp/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Divorce-Corp/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gloria Allred',
            'url': '/name/nm0021608/'},
           {'@type': 'Person',
            'name': 'Wendy Archer',
            'url': '/name/nm6112904/'},
           {'@type': 'Person',
            'name': 'Alexandra Borg',
            'url': '/name/nm6112905/'},
           {'@type': 'Person',
            'name': 'Dennis Braun',
            'url': '/name/nm6112906/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 394,
                     'ratingValue': '8.1',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Blake Harjes',
              'url': '/name/nm2017020/'},
             {'@type': 'Person',
              'name': 'James D. Scurlock',
              'url': '/name/nm1749001/'},
             {'@type': 'Person',
              'name': 'Joseph Sorge',
              'url': '/name/nm3348253/'},
             {'@type': 'Person',
              'name': 'Philip Sternberg',
              'url': '/name/nm2094174/'},
             {'@type': 'Organization', 'url': '/company/co0354234/'}],
 'datePublished': '2014-01-10',
 'description': 'Divorce Corp is a movie starring Gloria Allred, Wendy Archer, '
                'and Alexandra Borg. More money flows through the family '
                'courts, than in all other court systems in America combined, '
                'over $50 billion a year. Through extensive research...',
 'director': {'@type': 'Person',
              'name': 'Joseph Sorge',
              'url': '/name/nm3348253/'},
 'duration': 'PT1H33M',
 'genre': ['Documentary', 'Drama', 'History', 'News'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU2MzgxOTEzOF5BMl5BanBnXkFtZTgwNzAwNzg2MDE@._V1_.jpg',
 'keywords': 'social injustice,court,custody,marriage,feminism',
 'name': 'Divorce Corp',
 'trailer': {'@type': 'VideoObject',
             'description': 'An exposÃ© of the inner workings of the $50 '
                            'billion a year U.S. family law industry that '
                            'shines a bright light on the waste and collusive '
                            'practices seen daily in family courts.',
             'embedUrl': '/video/imdb/vi270247961',
             'name': 'Theatrical Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjI0MTAyMzA5MF5BMl5BanBnXkFtZTgwNDgxNDM3MDE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjI0MTAyMzA5MF5BMl5BanBnXkFtZTgwNDgxNDM3MDE@._V1_.jpg',
             'uploadDate': '2013-12-04T11:09:32Z'},
 'url': '/title/tt2636456/'}