{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Explained',
 'EntryURL': 'https://www.imdb.com/title/tt8005374',
 'Entry_json': 'Favorites/TV/snapshot/Explained/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Explained/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Explained/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Estelle Caswell',
            'url': '/name/nm3490204/'},
           {'@type': 'Person',
            'name': 'Maria Bello',
            'url': '/name/nm0004742/'},
           {'@type': 'Person',
            'name': 'Kristen Bell',
            'url': '/name/nm0068338/'},
           {'@type': 'Person',
            'name': 'Rachel Bloom',
            'url': '/name/nm3417385/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 5700,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Joe Posner',
              'url': '/name/nm3438051/'},
             {'@type': 'Person',
              'name': 'Ezra Klein',
              'url': '/name/nm3831303/'},
             {'@type': 'Organization', 'url': '/company/co0402466/'}],
 'datePublished': '2018-05-09',
 'description': 'Explained is a TV series starring Estelle Caswell, Maria '
                'Bello, and Kristen Bell. A documentary series that looks to '
                'explore the big questions of today.',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BNjU1NzYwMmQtMjEzMS00ODEzLWIxNzAtYjI3M2QwYWFmMTIwXkEyXkFqcGdeQXVyNDA4NzUyMzg@._V1_.jpg',
 'name': 'Explained',
 'trailer': {'@type': 'VideoObject',
             'description': 'Explained: Season 2',
             'embedUrl': '/video/imdb/vi4036542233',
             'name': 'Explained: Season 2',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTgxMTk3MzEtNjdiNi00MWZhLTgyZWEtYjU1YWQ0MzlmY2JiXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTgxMTk3MzEtNjdiNi00MWZhLTgyZWEtYjU1YWQ0MzlmY2JiXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
             'uploadDate': '2019-09-21T13:02:25Z'},
 'url': '/title/tt8005374/'}