{'Actors': ['Ajay Naidu',
            'Aliya Campbell',
            'Ben Shenkman',
            'Bill Buell',
            'Christopher McDonald',
            'Denise Dowse',
            'Diana Berry',
            'Dylan Baker',
            'Ellen Burstyn',
            'Gregg Bello',
            'Heather Litteer',
            'Henry Stram',
            "Jack O'Connell",
            'Janet Sarno',
            'Jared Leto',
            'Jennifer Connelly',
            'Jimmie Ray Weeks',
            'John Bryant Davila',
            'John Getz',
            'Keith David',
            'Lianna Pai',
            'Louise Lasser',
            'Marcia Jean Kurtz',
            'Mark Margolis',
            'Marlon Wayans',
            'Michael Kaycheck',
            'Olga Merediz',
            'Peter Maloney',
            'Samia Shoaib',
            'Scott Miller',
            'Sean Gullette',
            'Suzanne Shepherd',
            'Todd Miller'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                'Requiem for a Dream: The hopes and dreams of four ambitious '
                'people are shattered when their drug addictions begin '
                'spiraling out of control. ',
 'Director': ['Darren Aronofsky'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Requiem-for-a-Dream',
 'EntryURL': 'https://www.imdb.com/title/tt0180093',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Requiem-for-a-Dream/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Requiem-for-a-Dream/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Requiem-for-a-Dream/info.py',
 'Genres': ['Drama'],
 'Ratings': {'IMDB': '8.4/10',
             'Metascore': '68%',
             'PrimeWire': '4.17/5',
             'RT': '78%',
             'Votes': '853'},
 'Released': '2000-10-27',
 'Runtime': '102 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/387_Requiem_for_a_Dream_2000.jpg',
 'Title': 'Requiem-for-a-Dream'}