{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Requiem-for-a-Dream',
 'EntryURL': 'https://www.imdb.com/title/tt0180093',
 'Entry_json': 'Favorites/Movies/snapshot/Requiem-for-a-Dream/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Requiem-for-a-Dream/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Requiem-for-a-Dream/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ellen Burstyn',
            'url': '/name/nm0000995/'},
           {'@type': 'Person', 'name': 'Jared Leto', 'url': '/name/nm0001467/'},
           {'@type': 'Person',
            'name': 'Jennifer Connelly',
            'url': '/name/nm0000124/'},
           {'@type': 'Person',
            'name': 'Marlon Wayans',
            'url': '/name/nm0005541/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 745490,
                      'ratingValue': '8.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Hubert Selby Jr.',
              'url': '/name/nm0782968/'},
             {'@type': 'Person',
              'name': 'Hubert Selby Jr.',
              'url': '/name/nm0782968/'},
             {'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Organization', 'url': '/company/co0014903/'},
             {'@type': 'Organization', 'url': '/company/co0042682/'},
             {'@type': 'Organization', 'url': '/company/co0067219/'},
             {'@type': 'Organization', 'url': '/company/co0062935/'},
             {'@type': 'Organization', 'url': '/company/co0024345/'},
             {'@type': 'Organization', 'url': '/company/co0069968/'},
             {'@type': 'Organization', 'url': '/company/co0049489/'},
             {'@type': 'Organization', 'url': '/company/co0076907/'}],
 'datePublished': '2000-11-03',
 'description': 'Requiem for a Dream is a movie starring Ellen Burstyn, Jared '
                'Leto, and Jennifer Connelly. The drug-induced utopias of four '
                'Coney Island people are shattered when their addictions run '
                'deep.',
 'director': [{'@type': 'Person',
               'name': 'Darren Aronofsky',
               'url': '/name/nm0004716/'}],
 'duration': 'PT1H42M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BOTdiNzJlOWUtNWMwNS00NmFlLWI0YTEtZmI3YjIzZWUyY2Y3XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'drug addiction,sex show,heroin,sex scene,addiction',
 'name': 'Requiem for a Dream',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Artisan',
              'embedUrl': '/video/imdb/vi2156069145',
              'name': 'Requiem for a Dream',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzFmMzRmMjQtOGNiZS00YjdjLThhNTUtM2M1YzI0NDQ1ZTcyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzFmMzRmMjQtOGNiZS00YjdjLThhNTUtM2M1YzI0NDQ1ZTcyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T15:51:51Z'}],
 'url': '/title/tt0180093/'}