{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-11-09',
 'EntryPath': 'Favorites/Movies/snapshot/Is-the-Man-Who-Is-Tall-Happy-An-Animated-Conversation-with-Noam-Chomsky',
 'EntryURL': 'https://www.imdb.com/title/tt1817287',
 'Entry_json': 'Favorites/Movies/snapshot/Is-the-Man-Who-Is-Tall-Happy-An-Animated-Conversation-with-Noam-Chomsky/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Is-the-Man-Who-Is-Tall-Happy-An-Animated-Conversation-with-Noam-Chomsky/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Is-the-Man-Who-Is-Tall-Happy-An-Animated-Conversation-with-Noam-Chomsky/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Noam Chomsky',
            'url': '/name/nm0159008/'},
           {'@type': 'Person',
            'name': 'Michel Gondry',
            'url': '/name/nm0327273/'},
           {'@type': 'Person',
            'name': 'Richard Feynman',
            'url': '/name/nm0275509/'},
           {'@type': 'Person',
            'name': 'Michèle Oshima',
            'url': '/name/nm5974032/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3320,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Michel Gondry',
              'url': '/name/nm0327273/'},
             {'@type': 'Organization', 'url': '/company/co0309685/'},
             {'@type': 'Organization', 'url': '/company/co0046394/'}],
 'datePublished': '2013-11-25',
 'description': 'Is the Man Who Is Tall Happy?: An Animated Conversation with '
                'Noam Chomsky is a movie starring Noam Chomsky, Michel Gondry, '
                'and Richard Feynman. A series of interviews featuring '
                'linguist, philosopher and activist Noam Chomsky done in...',
 'director': [{'@type': 'Person',
               'name': 'Michel Gondry',
               'url': '/name/nm0327273/'}],
 'duration': 'PT1H28M',
 'genre': ['Documentary', 'Animation', 'Biography'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU3MTYzMjgwM15BMl5BanBnXkFtZTgwMDkzMDY1MDE@._V1_.jpg',
 'keywords': 'interview,analysis,epistemology,continuity,why',
 'name': 'Is the Man Who Is Tall Happy?: An Animated Conversation with Noam '
         'Chomsky',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A series of interviews featuring linguist, '
                             'philosopher and activist Noam Chomsky done in '
                             'hand-drawn animation.',
              'embedUrl': '/video/imdb/vi2212276249',
              'name': 'Theatrical Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODUwMjE3MjgwMl5BMl5BanBnXkFtZTgwODU4NTU1MDE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODUwMjE3MjgwMl5BMl5BanBnXkFtZTgwODU4NTU1MDE@._V1_.jpg',
              'uploadDate': '2013-11-05T15:32:57Z'}],
 'url': '/title/tt1817287/'}