{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale',
 'EntryURL': 'https://www.imdb.com/title/tt0392465',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Josh Hartnett',
            'url': '/name/nm0001326/'},
           {'@type': 'Person',
            'name': 'Radha Mitchell',
            'url': '/name/nm0593664/'},
           {'@type': 'Person', 'name': 'Gary Cole', 'url': '/name/nm0170550/'},
           {'@type': 'Person',
            'name': 'Sheila Kelley',
            'url': '/name/nm0445992/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 8519,
                     'ratingValue': '6.9',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Ronald Bass',
              'url': '/name/nm0060103/'},
             {'@type': 'Organization', 'url': '/company/co0154654/'},
             {'@type': 'Organization', 'url': '/company/co0136722/'},
             {'@type': 'Organization', 'url': '/company/co0002572/'},
             {'@type': 'Organization', 'url': '/company/co0014171/'},
             {'@type': 'Organization', 'url': '/company/co0022821/'},
             {'@type': 'Organization', 'url': '/company/co0021936/'},
             {'@type': 'Organization', 'url': '/company/co0047890/'}],
 'datePublished': '2006-02-02',
 'description': 'Mozart and the Whale is a movie starring Josh Hartnett, Radha '
                'Mitchell, and Gary Cole. A love story between two savants '
                "with Asperger's syndrome, a kind of autism, whose conditions "
                'sabotage their budding relationship.',
 'director': {'@type': 'Person',
              'name': 'Petter Næss',
              'url': '/name/nm0639033/'},
 'duration': 'PT1H34M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTQ2YWQ5NjAtZWI1MS00NTlhLThjODktNWIxNTI1MGVmNjhmXkEyXkFqcGdeQXVyMTQ4NDY5OTc@._V1_.jpg',
 'keywords': "autism,asperger's syndrome,halloween costume,halloween "
             'party,love',
 'name': 'Mozart and the Whale',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Sony Pictures Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi1152188697',
             'name': 'Mozart and the Whale',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMDk1ZDg3MGEtYWE2YS00NTA5LWJhZDctNGI0Y2ZmY2VmMDM2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMDk1ZDg3MGEtYWE2YS00NTA5LWJhZDctNGI0Y2ZmY2VmMDM2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:26:32Z'},
 'url': '/title/tt0392465/'}