{'Actors': ['Christa Campbell',
            'Erica Leerhsen',
            'Gary Cole',
            'John Carroll Lynch',
            'Josh Hartnett',
            'Nate Mooney',
            'Radha Mitchell',
            'Robert Wisdom',
            'Ron Ford',
            'Rusty Schwimmer',
            'Sheila Kelley',
            'Suzanne Niles'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Mozart and the Whale: A love story between two savants with '
                "Asperger's syndrome, a kind of autism, whose conditions "
                'sabotage their budding relationship. ',
 'Director': ['Petter N&#xE6;ss'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale',
 'EntryURL': 'https://www.imdb.com/title/tt0392465',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Mozart-and-the-Whale/info.py',
 'Genres': ['Drama', 'Comedy', 'Romance'],
 'Ratings': {'IMDB': '7.0/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.03/5',
             'RT': 'N/A',
             'Votes': '77'},
 'Released': '2005-09-10',
 'Runtime': '92 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/20448_Mozart_and_the_Whale_2005.jpg',
 'Title': 'Mozart-and-the-Whale'}