{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/The-Office',
 'EntryURL': 'https://www.imdb.com/title/tt0386676',
 'Entry_json': 'Favorites/TV/snapshot/The-Office/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Office/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Office/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Steve Carell',
            'url': '/name/nm0136797/'},
           {'@type': 'Person',
            'name': 'Jenna Fischer',
            'url': '/name/nm0278979/'},
           {'@type': 'Person',
            'name': 'John Krasinski',
            'url': '/name/nm1024677/'},
           {'@type': 'Person',
            'name': 'Rainn Wilson',
            'url': '/name/nm0933988/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 361190,
                     'ratingValue': '8.9',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Greg Daniels',
              'url': '/name/nm0199948/'},
             {'@type': 'Person',
              'name': 'Ricky Gervais',
              'url': '/name/nm0315041/'},
             {'@type': 'Person',
              'name': 'Stephen Merchant',
              'url': '/name/nm0580351/'},
             {'@type': 'Organization', 'url': '/company/co0082215/'},
             {'@type': 'Organization', 'url': '/company/co0129175/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0093771/'},
             {'@type': 'Organization', 'url': '/company/co0196576/'},
             {'@type': 'Organization', 'url': '/company/co0046592/'}],
 'datePublished': '2005-03-24',
 'description': 'The Office is a TV series starring Steve Carell, Jenna '
                'Fischer, and John Krasinski. A mockumentary on a group of '
                'typical office workers, where the workday consists of ego '
                'clashes, inappropriate behavior, and tedium.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
 'keywords': 'mockumentary,sitcom,cringe comedy,office,job',
 'name': 'The Office',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for The Office: The Complete Series',
             'embedUrl': '/video/imdb/vi2686888217',
             'name': 'The Office: The Complete Series',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDczMWVjNWUtY2FiMC00MjUwLWIzZTItMTNiNTE2MWUzN2I5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDczMWVjNWUtY2FiMC00MjUwLWIzZTItMTNiNTE2MWUzN2I5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2013-08-15T04:59:22Z'},
 'url': '/title/tt0386676/'}