{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cashback',
 'EntryURL': 'https://www.imdb.com/title/tt0460740',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cashback/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cashback/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Cashback/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sean Biggerstaff',
            'url': '/name/nm0081801/'},
           {'@type': 'Person', 'name': 'Emilia Fox', 'url': '/name/nm0288976/'},
           {'@type': 'Person',
            'name': 'Michelle Ryan',
            'url': '/name/nm0752740/'},
           {'@type': 'Person',
            'name': 'Erica Ellis',
            'url': '/name/nm2931729/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 81491,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Sean Ellis',
              'url': '/name/nm1193346/'},
             {'@type': 'Organization', 'url': '/company/co0126540/'},
             {'@type': 'Organization', 'url': '/company/co0087854/'},
             {'@type': 'Organization', 'url': '/company/co0004166/'},
             {'@type': 'Organization', 'url': '/company/co0104690/'}],
 'datePublished': '2007-01-17',
 'description': 'Cashback is a movie starring Sean Biggerstaff, Emilia Fox, '
                'and Michelle Ryan. After a painful breakup, Ben develops '
                'insomnia. To kill time, he starts working the late night '
                'shift at the local supermarket, where his artistic...',
 'director': {'@type': 'Person',
              'name': 'Sean Ellis',
              'url': '/name/nm1193346/'},
 'duration': 'PT1H42M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZjhiZmYwMWEtZmZiOC00NDhhLWFhMjQtZmQ5Mjc0NjZhZjFmXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_.jpg',
 'keywords': 'female full frontal nudity,nipples,female explicit nudity,shaved '
             'vagina,labia',
 'name': 'Cashback',
 'url': '/title/tt0460740/'}