<?php
$infoArray = array('Actors' => array('Al Sotto',
            'Alan Davis',
            'Alex Hyde-White',
            'Ashlie Atkinson',
            'Austin Pendleton',
            "Brian d'Arcy James",
            'Brian Harrison',
            'Brian Howe',
            'Brian Lucero',
            'Bridget Gethins',
            'Bruce Altman',
            'Colby French',
            'Dan Desmond',
            'David Barry Gray',
            'Ed Harris',
            'Jamey Sheridan',
            'Jenna Stern',
            'Jennifer Butler',
            'John Mitchell',
            'John Rothman',
            'Joseph Tornatore',
            'Julia Williams',
            'Julianne Moore',
            'Larry Carter',
            'Larry Sullivan',
            'Liam Ferguson',
            'Lou Sumrall',
            'Matt Cannon',
            'Matthew James Gulbranson',
            'Michael J Kraycik',
            'Pamela Fischer',
            'Patrick Michael Strange',
            'Peter MacNicol',
            'Rain Pryor',
            'Rhonda Overby',
            'Ron Livingston',
            'Ron Perkins',
            'Sarah Paulson',
            'Spencer Garrett',
            'Steven J Klaszky',
            'Susan Allenback',
            'Terry Ward',
            'Tiffany Thornton',
            'Vincent Riviezzo',
            'Woody Harrelson'),
 'Added' => '2013-02-23',
 'Countries' => array('USA'),
 'Description' => '\nGame Change: Follows John McCain&#x27;s 2008 presidential campaign, from his selection of Alaska Governor Sarah Palin as his running mate to their ultimate defeat in the general election. ',
 'Director' => array('Jay Roach'),
 'Genres' => array('Drama', 'History'),
 'IMDB' => 'http://www.imdb.com/title/tt1848902',
 'PrimeWire' => 'http://www.primewire.ag/watch-2732264-Game-Change',
 'Ratings' => array('IMDB' => '7.5/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.76/5',
             'RT' => '65%',
             'Votes' => '321'),
 'Released' => '2012-02-28',
 'Runtime' => 'NA',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2732264_Game_Change_2012.jpg',
 'Title' => 'Game-Change');
?>