<?php
$infoArray = array('Actors' => array('Alex Burns',
            'Amy Ferguson',
            'Ann Dowd',
            'Armando Riesco',
            'Ato Essandoh',
            'Austin Lysy',
            'Ben Hauck',
            'Debbon Ayer',
            "Denis O'Hare",
            'Geoffrey Arend',
            'Ian Holm',
            'Ice',
            'Jackie Hoffman',
            'Jayne Houdyshell',
            'Jean Smart',
            'Jill Flint',
            'Jim Parsons',
            'Joe Bacino',
            'Marc Alan Austen',
            'Mark Murphy',
            'Method Man',
            'Michael Weston',
            'Natalie Portman',
            'Peter Sarsgaard',
            'Ron Leibman',
            'Yvette Mercedes',
            'Zach Braff'),
 'Added' => '2013-02-20',
 'Countries' => array('USA'),
 'Description' => "\nGarden State: A quietly troubled young man returns home for his mother's funeral after being estranged from his family for a decade. ",
 'Director' => array('Zach Braff'),
 'Genres' => array('Drama', 'Comedy', 'Romance'),
 'IMDB' => 'http://www.imdb.com/title/tt0333766',
 'PrimeWire' => 'http://www.primewire.ag/watch-2100-Garden-State',
 'Ratings' => array('IMDB' => '7.6/10',
             'Metascore' => '67%',
             'PrimeWire' => '3.95/5',
             'RT' => '86%',
             'Votes' => '582'),
 'Released' => '2004-01-16',
 'Runtime' => '102 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2100_Garden_State_2004.jpg',
 'Title' => 'Garden-State');
?>