{'Actors': ['Clark Johnson&tv',
            'John Goodman&tv',
            'Mark Consuelos&tv',
            'Matt Malloy&tv'],
 'Added': '2013-12-15',
 'Countries': [],
 'Description': '\nAlpha House: Follows four senators who live together in a rented house in Washington DC. ',
 'Director': ['Adam Bernstein'],
 'Genres': ['Comedy&tv', 'Drama&tv'],
 'IMDB': 'http://www.imdb.com/title/tt2584038',
 'PrimeWire': 'http://www.primewire.ag/tv-2739191-Alpha-House',
 'Ratings': {'IMDB': '7.2/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.99/5',
             'RT': 'N/A',
             'Votes': '104'},
 'Released': '2013-04-19',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2739191_Alpha_House.jpg',
 'Title': 'Alpha-House'}