<?php
$infoArray = array('Actors' => array('Alastair Mackenzie&tv',
            'Allen Leech&tv',
            'Amit Shah&tv',
            'Andrew Knott&tv',
            'Anna Wilson-Jones&tv',
            'Chetna Pandya&tv',
            'Daniel Kaluuya&tv',
            'Donald Sumpter&tv',
            'Helen Fospero&tv',
            'Jay Simpson&tv',
            'Jessica Brown Findlay&tv',
            'Jodie Whittaker&tv',
            'Johann Myers&tv',
            'Lindsay Duncan&tv',
            'Lydia Wilson&tv',
            'Nick Hendrix&tv',
            'Patrick Kennedy&tv',
            'Rakie Ayola&tv',
            'Rory Kinnear&tv',
            'Rupert Everett&tv',
            'Sophie Kennedy Clark&tv',
            'Sophie Wu&tv',
            'Toby Kebbell&tv',
            'Tom Cullen&tv',
            'Tom Goodman-Hill&tv'),
 'Added' => '2015-03-29',
 'Countries' => array(),
 'Description' => "\nBlack Mirror: Description : Charlie Brooker (E4's Bafta-nominated Dead Set author) returns with Black Mirror, a suspenseful, satirical three-part mini-series that taps into collective unease about our modern world. Over the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence. Our grip on reality is shifting. We worship at the altars of Google and Apple. Facebook algorithms know us more intimately than our own parents. We have access to all the information in the world, but no brainspace left to absorb anything longer than a 140-character tweet. Black Mirror is a hybrid of The Twilight Zone and Tales of the Unexpected which taps into our contemporary unease about our modern world. The three stand-alone dramas will be sharp, suspenseful, satirical tales with a techno-paranoia bent - all audacious \x91what if' stories: some comic, some shocking. ",
 'Director' => array(),
 'Genres' => array('Drama&tv', 'Sci-Fi&tv', 'Thriller&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt2085059',
 'PrimeWire' => 'http://www.primewire.ag/tv-2730529-Black-Mirror',
 'Ratings' => array('IMDB' => '8.8/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.33/5',
             'RT' => 'N/A',
             'Votes' => '509'),
 'Released' => '2011-12-04',
 'Runtime' => '50 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2730529_Black_Mirror_2011.jpg',
 'Title' => 'Black-Mirror');
?>