{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Russian-Doll',
 'EntryURL': 'https://www.imdb.com/title/tt7520794',
 'Entry_json': 'Favorites/TV/snapshot/Russian-Doll/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Russian-Doll/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Russian-Doll/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Natasha Lyonne',
            'url': '/name/nm0005169/'},
           {'@type': 'Person',
            'name': 'Charlie Barnett',
            'url': '/name/nm1854211/'},
           {'@type': 'Person', 'name': 'Greta Lee', 'url': '/name/nm2336966/'},
           {'@type': 'Person',
            'name': 'Elizabeth Ashley',
            'url': '/name/nm0039051/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 60742,
                      'ratingValue': '7.9',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Leslye Headland',
              'url': '/name/nm2853516/'},
             {'@type': 'Person',
              'name': 'Natasha Lyonne',
              'url': '/name/nm0005169/'},
             {'@type': 'Person',
              'name': 'Amy Poehler',
              'url': '/name/nm0688132/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0352965/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0236703/'},
             {'@type': 'Organization', 'url': '/company/co0046592/'}],
 'datePublished': '2019-02-01',
 'description': 'Russian Doll is a TV series starring Natasha Lyonne, Charlie '
                'Barnett, and Greta Lee. A cynical young woman in New York '
                "City keeps dying and returning to the party that's being "
                'thrown in her honor on that same evening. She tries to...',
 'genre': ['Adventure', 'Comedy', 'Drama', 'Mystery'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYmViMjdhZmQtODIyZi00Mzc4LWFhNTItOTk4NGM1NGU0ZDZjXkEyXkFqcGdeQXVyNjc2NTQzMjU@._V1_.jpg',
 'keywords': 'stuck in a time loop,time loop,facing the past,cynical '
             'woman,jewish woman',
 'name': 'Russian Doll',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Russian Doll: Season 1',
              'embedUrl': '/video/imdb/vi459521305',
              'name': 'Russian Doll: Season 1',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZGVhMDM3YzYtYWFlZi00Mzc5LWIzNWEtOThlZTg3YjJmNGRkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZGVhMDM3YzYtYWFlZi00Mzc5LWIzNWEtOThlZTg3YjJmNGRkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-04-14T00:15:32Z'}],
 'url': '/title/tt7520794/'}