{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth',
 'EntryURL': 'https://www.imdb.com/title/tt0756683',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'David Lee Smith',
            'url': '/name/nm0807900/'},
           {'@type': 'Person', 'name': 'Tony Todd', 'url': '/name/nm0865302/'},
           {'@type': 'Person',
            'name': 'John Billingsley',
            'url': '/name/nm0082517/'},
           {'@type': 'Person',
            'name': 'Ellen Crawford',
            'url': '/name/nm0186761/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 168613,
                     'ratingValue': '7.9',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Jerome Bixby',
              'url': '/name/nm0003198/'},
             {'@type': 'Organization', 'url': '/company/co0183125/'}],
 'datePublished': '2007-06-10',
 'description': 'The Man from Earth is a movie starring David Lee Smith, Tony '
                'Todd, and John Billingsley. An impromptu goodbye party for '
                'Professor John Oldman becomes a mysterious interrogation '
                'after the retiring scholar reveals to his colleagues he...',
 'director': {'@type': 'Person',
              'name': 'Richard Schenkman',
              'url': '/name/nm0770942/'},
 'duration': 'PT1H27M',
 'genre': ['Drama', 'Fantasy', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzQ5NGQwOTUtNWJlZi00ZTFiLWI0ZTEtOGU3MTA2ZGU5OWZiXkEyXkFqcGdeQXVyMTczNjQwOTY@._V1_.jpg',
 'keywords': 'single setting,dialogue driven,storytelling,cro magnon,professor',
 'name': 'The Man from Earth',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Starz!',
             'embedUrl': '/video/imdb/vi479396121',
             'name': "Jerome Bixby's The Man From Earth",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BN2IwZGI1MzAtZTdhYS00OWEyLThkZmEtNGFiNmJlYTc0YjRjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BN2IwZGI1MzAtZTdhYS00OWEyLThkZmEtNGFiNmJlYTc0YjRjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:49:45Z'},
 'url': '/title/tt0756683/'}