{'Actors': ['Alexis Thorpe',
            'Annika Peterson',
            'David Lee Smith',
            'Ellen Crawford',
            'John Billingsley',
            'Richard Riehle',
            'Tony Todd',
            'William Katt'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'The Man from Earth: An impromptu goodbye party for Professor '
                'John Oldman becomes a mysterious interrogation after the '
                'retiring... ',
 'Director': ['Richard Schenkman'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth',
 'EntryURL': 'https://www.imdb.com/title/tt0756683',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Man-from-Earth/info.py',
 'Genres': ['Drama', 'Sci-Fi', 'History'],
 'Ratings': {'IMDB': '8.0/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.15/5',
             'RT': 'N/A',
             'Votes': '510'},
 'Released': '2007-06-10',
 'Runtime': '87 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/6353_The_Man_from_Earth_2007.jpg',
 'Title': 'The-Man-from-Earth'}