{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Greys-Anatomy',
 'EntryURL': 'https://www.imdb.com/title/tt0413573',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Greys-Anatomy/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Greys-Anatomy/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Greys-Anatomy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ellen Pompeo',
            'url': '/name/nm0690186/'},
           {'@type': 'Person',
            'name': 'Chandra Wilson',
            'url': '/name/nm0933156/'},
           {'@type': 'Person',
            'name': 'James Pickens Jr.',
            'url': '/name/nm0681782/'},
           {'@type': 'Person',
            'name': 'Justin Chambers',
            'url': '/name/nm0150362/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 234295,
                     'ratingValue': '7.6',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Shonda Rhimes',
              'url': '/name/nm0722274/'},
             {'@type': 'Organization', 'url': '/company/co0170849/'},
             {'@type': 'Organization', 'url': '/company/co0085751/'},
             {'@type': 'Organization', 'url': '/company/co0067205/'},
             {'@type': 'Organization', 'url': '/company/co0209226/'}],
 'datePublished': '2005-03-27',
 'description': "Grey's Anatomy is a TV series starring Ellen Pompeo, Chandra "
                'Wilson, and James Pickens Jr.. A drama centered on the '
                'personal and professional lives of five surgical interns and '
                'their supervisors.',
 'genre': ['Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjgwNGNkZGYtMWQyYS00YjEzLWFmZTctODUzYWMxOWJkNTAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'surgeon,hospital,lesbian,work romance,surgery',
 'name': "Grey's Anatomy",
 'trailer': {'@type': 'VideoObject',
             'description': "Trailer for Season 12 of Grey's Anatomy from ABC.",
             'embedUrl': '/video/imdb/vi17412889',
             'name': 'Season 12 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2NjQyOTkzNV5BMl5BanBnXkFtZTgwNDI5NTY4NjE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2NjQyOTkzNV5BMl5BanBnXkFtZTgwNDI5NTY4NjE@._V1_.jpg',
             'uploadDate': '2015-09-23T10:21:18Z'},
 'url': '/title/tt0413573/'}