{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2011-12-31',
 'EntryPath': 'Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers',
 'EntryURL': 'https://www.imdb.com/title/tt1495980',
 'Entry_json': 'Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Corey Johnson',
            'url': '/name/nm0424819/'},
           {'@type': 'Person',
            'name': 'James Cromwell',
            'url': '/name/nm0000342/'},
           {'@type': 'Person',
            'name': 'David Annen',
            'url': '/name/nm1507556/'},
           {'@type': 'Person',
            'name': 'James Bolam',
            'url': '/name/nm0092639/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 460,
                      'ratingValue': '6.2',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Craig Warner',
              'url': '/name/nm0912438/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'}],
 'datePublished': '2009-09-09',
 'description': 'The Last Days of Lehman Brothers is a TV movie starring Corey '
                'Johnson, James Cromwell, and David Annen. The heads of Wall '
                "Street's biggest investment banks were summoned to an evening "
                'meeting by the US Treasury Secretary, Hank...',
 'director': [{'@type': 'Person',
               'name': 'Michael Samuels',
               'url': '/name/nm0760499/'}],
 'duration': 'PT1H',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BN2Q5MDc5YTktNGE2NS00YzQ1LWI1Y2ItMTc1MWVjNjNlNWQ1L2ltYWdlXkEyXkFqcGdeQXVyMDkzOTgyNw@@._V1_.jpg',
 'keywords': 'investment bank,ceo,financial crisis,secretary of the treasury',
 'name': 'The Last Days of Lehman Brothers',
 'url': '/title/tt1495980/'}