{'Actors': ['Alex Jennings',
            'Ben Daniels',
            'Corey Johnson',
            'James Bolam',
            'James Cromwell',
            'Michael Brandon',
            'Michael Landes',
            'Peter Polycarpou',
            'William Hope'],
 'Added': '2011-12-31',
 'Countries': ['UK'],
 'Description': '\n'
                "The Last Days of Lehman Brothers: The heads of Wall Street's "
                'biggest investment banks were summoned to an evening meeting '
                'by the US Treasury Secretary... ',
 'Director': ['Michael Samuels'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers',
 'EntryURL': 'https://www.imdb.com/title/tt1495980',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Last-Days-of-Lehman-Brothers/info.py',
 'Genres': ['Drama'],
 'Ratings': {'IMDB': '6.2/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.25/5',
             'RT': 'N/A',
             'Votes': '40'},
 'Released': '2009-09-09',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/12348_The_Last_Days_of_Lehman_Brothers_2009.jpg',
 'Title': 'The-Last-Days-of-Lehman-Brothers'}