{'Actors': ['Paul Jackson'],
 'Added': '2013-02-25',
 'Countries': ['USA'],
 'Description': '\nBetween the Folds: Depicts a cast of fine artists and eccentric scientists (from MIT and NASA) who have devoted their lives to the unlikely medium of modern origami. Through their determination to reinterpret the world in paper, they arouse a fascinating mix of sensibilities towards art, form, expressiveness, creativity and meaning. ',
 'Director': ['Vanessa Gould'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1253565',
 'PrimeWire': 'http://www.primewire.ag/watch-1976945-Between-the-Folds',
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.40/5',
             'RT': 'N/A',
             'Votes': '15'},
 'Released': '2008-05-31',
 'Runtime': '56 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1976945_Between_the_Folds_2008.jpg',
 'Title': 'Between-the-Folds'}