{'Actors': ['Al Pereira',
            'Alan Polonsky',
            'Angela Bettis',
            'Brent Roam',
            'Carlease Burke',
            'Christina Venuti',
            'Christopher Doyle',
            'Greg Travis',
            'Juliet Landau',
            'Marco Rodr&#xED;guez',
            'Price Carson',
            'Rance Howard',
            'Sara Downing',
            'Sheri Moon Zombie'],
 'Added': '2013-06-08',
 'Countries': ['USA'],
 'Description': '\n'
                'Toolbox Murders: A historic Hollywood hotel houses a '
                "supernatural evil. It's been subdued for decades - but when "
                "renovations start, a series of murders take place. It's up to "
                'our heroine to solve the mystery. ',
 'Director': ['Tobe Hooper'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders',
 'EntryURL': 'https://www.imdb.com/title/tt0367153',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders/info.py',
 'Genres': ['Horror', 'Mystery'],
 'Ratings': {'IMDB': '5.3/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.09/5',
             'RT': '53%',
             'Votes': '75'},
 'Released': '2004-04-14',
 'Runtime': '95 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/19836_Toolbox_Murders_2003.jpg',
 'Title': 'Toolbox-Murders'}