{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-08',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders',
 'EntryURL': 'https://www.imdb.com/title/tt0367153',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Toolbox-Murders/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Angela Bettis',
            'url': '/name/nm0079374/'},
           {'@type': 'Person', 'name': 'Brent Roam', 'url': '/name/nm0730099/'},
           {'@type': 'Person',
            'name': 'Marco Rodríguez',
            'url': '/name/nm0735424/'},
           {'@type': 'Person',
            'name': 'Rance Howard',
            'url': '/name/nm0397555/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 7628,
                     'ratingValue': '5.3',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jace Anderson',
              'url': '/name/nm0026829/'},
             {'@type': 'Person',
              'name': 'Adam Gierasch',
              'url': '/name/nm0317368/'},
             {'@type': 'Organization', 'url': '/company/co0485497/'},
             {'@type': 'Organization', 'url': '/company/co0107106/'},
             {'@type': 'Organization', 'url': '/company/co0003056/'},
             {'@type': 'Organization', 'url': '/company/co0107105/'}],
 'datePublished': '2004-09-09',
 'description': 'Toolbox Murders is a movie starring Angela Bettis, Brent '
                'Roam, and Marco Rodríguez. A historic Hollywood hotel houses '
                "a supernatural evil. It's been subdued for decades, but when "
                'renovations start, a series of murders take place.',
 'director': {'@type': 'Person',
              'name': 'Tobe Hooper',
              'url': '/name/nm0001361/'},
 'duration': 'PT1H35M',
 'genre': ['Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTE5YTUyNmMtNGFiOS00YmIyLTkzZjYtMWUyN2E3NGIzOWQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'neighbor,toolbox,slasher,elevator,secret entrance',
 'name': 'Toolbox Murders',
 'url': '/title/tt0367153/'}