{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-12-27',
 'EntryPath': 'Favorites/TV/snapshot/Legit',
 'EntryURL': 'https://www.imdb.com/title/tt2400391',
 'Entry_json': 'Favorites/TV/snapshot/Legit/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Legit/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Legit/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jim Jefferies',
            'url': '/name/nm1812944/'},
           {'@type': 'Person',
            'name': 'Dan Bakkedahl',
            'url': '/name/nm2045884/'},
           {'@type': 'Person', 'name': 'DJ Qualls', 'url': '/name/nm0702809/'},
           {'@type': 'Person',
            'name': 'Mindy Sterling',
            'url': '/name/nm0827565/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 7779,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Jim Jefferies',
              'url': '/name/nm1812944/'},
             {'@type': 'Person',
              'name': "Peter O'Fallon",
              'url': '/name/nm0640964/'},
             {'@type': 'Organization', 'url': '/company/co0216537/'}],
 'datePublished': '2013-01-17',
 'description': 'Legit is a TV series starring Jim Jefferies, Dan Bakkedahl, '
                'and DJ Qualls. Jim and his put upon friends try to learn what '
                'it means to be a good person.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTkzMzMzMjk5Ml5BMl5BanBnXkFtZTgwMjM4MTcyMDE@._V1_.jpg',
 'keywords': 'friend',
 'name': 'Legit',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Legit: The Complete First Season',
              'embedUrl': '/video/imdb/vi1912580889',
              'name': 'Legit: The Complete First Season',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOWZiZDYxZDAtN2VjZS00YzY4LTk3N2UtNGRjZDk1YmNmOTU0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOWZiZDYxZDAtN2VjZS00YzY4LTk3N2UtNGRjZDk1YmNmOTU0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2014-02-16T07:39:09Z'}],
 'url': '/title/tt2400391/'}