{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/The-Chronicles-of-Riddick',
 'EntryURL': 'https://www.imdb.com/title/tt0296572',
 'Entry_json': 'Favorites/Movies/snapshot/The-Chronicles-of-Riddick/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Chronicles-of-Riddick/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Chronicles-of-Riddick/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Vin Diesel', 'url': '/name/nm0004874/'},
           {'@type': 'Person', 'name': 'Judi Dench', 'url': '/name/nm0001132/'},
           {'@type': 'Person', 'name': 'Colm Feore', 'url': '/name/nm0272173/'},
           {'@type': 'Person',
            'name': 'Thandie Newton',
            'url': '/name/nm0628601/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 210715,
                      'ratingValue': '6.7',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jim Wheat',
              'url': '/name/nm0923646/'},
             {'@type': 'Person',
              'name': 'Ken Wheat',
              'url': '/name/nm0003117/'},
             {'@type': 'Person',
              'name': 'David Twohy',
              'url': '/name/nm0878638/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0023815/'},
             {'@type': 'Organization', 'url': '/company/co0026886/'},
             {'@type': 'Organization', 'url': '/company/co0094843/'}],
 'datePublished': '2004-06-11',
 'description': 'The Chronicles of Riddick is a movie starring Vin Diesel, '
                'Judi Dench, and Colm Feore. The wanted criminal Richard Bruno '
                'Riddick (Vin Diesel) arrives on a planet called Helion Prime '
                'and finds himself up against an invading empire...',
 'director': [{'@type': 'Person',
               'name': 'David Twohy',
               'url': '/name/nm0878638/'}],
 'duration': 'PT1H59M',
 'genre': ['Action', 'Adventure', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzBjNmJkYjUtMTFjMC00ZWI5LWEyM2YtNzczOTczMmM1ODY5XkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_.jpg',
 'keywords': 'shared universe,actor reprises previous '
             'role,warrior,planet,bounty hunter',
 'name': 'The Chronicles of Riddick',
 'url': '/title/tt0296572/'}