{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Manhunt',
 'EntryURL': 'https://rawg.io/games/manhunt',
 'Entry_json': 'Favorites/Games/snapshot/Manhunt/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Manhunt/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Manhunt/thumb.jpg',
 'added': 1046,
 'background_image': 'https://media.rawg.io/media/games/c23/c23b578d6a9dd1c73ee403157184e793.jpg',
 'developers': ['Rockstar Games', 'Rockstar North'],
 'genres': ['Action'],
 'name': 'Manhunt',
 'platforms': ['PC', 'PlayStation 2', 'PlayStation 4', 'PlayStation 3'],
 'publishers': ['Rockstar Games'],
 'released': '2003-11-18',
 'slug': 'manhunt'}