{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Dead-Space',
 'EntryURL': 'https://rawg.io/games/dead-space',
 'Entry_json': 'Favorites/Games/snapshot/Dead-Space/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Dead-Space/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Dead-Space/thumb.jpg',
 'added': 5406,
 'background_image': 'https://media.rawg.io/media/games/ebd/ebdbb7eb52bd58b0e7fa4538d9757b60.jpg',
 'developers': ['Electronic Arts',
                'Visceral Games',
                'Electronic Arts Redwood Shores'],
 'genres': ['Action', 'Shooter'],
 'name': 'Dead Space',
 'platforms': ['PC', 'PlayStation 3', 'Xbox 360'],
 'publishers': ['Electronic Arts'],
 'released': '2008-10-13',
 'slug': 'dead-space'}