{'Actors': [],
 'Added': '2015-01-24',
 'Countries': ['USA'],
 'Description': '\nKyle Kinane I Liked His Old Stuff Better: N/A ',
 'Director': ['Lance Bangs'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Kyle-Kinane-I-Liked-His-Old-Stuff-Better',
 'EntryURL': 'http://www.imdb.com/title/tt3973036',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Kyle-Kinane-I-Liked-His-Old-Stuff-Better/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Kyle-Kinane-I-Liked-His-Old-Stuff-Better/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Kyle-Kinane-I-Liked-His-Old-Stuff-Better/info.py',
 'Genres': ['Comedy'],
 'IMDB': 'http://www.imdb.com/title/tt3973036',
 'PrimeWire': 'http://www.primewire.ag/watch-2757114-Kyle-Kinane-I-Liked-His-Old-Stuff-Better',
 'Ratings': {'IMDB': '7.7/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.90/5',
             'RT': 'N/A',
             'Votes': '30'},
 'Released': '2015-01-23',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2757114_Kyle_Kinane_I_Liked_His_Old_Stuff_Better_2015.jpg',
 'Title': 'Kyle-Kinane-I-Liked-His-Old-Stuff-Better'}