{'@context': 'http://schema.org',
 '@type': 'CreativeWork',
 'EntryAdded': '2015-01-24',
 'EntryPath': 'Favorites/Movies/snapshot/Kyle-Kinane-I-Liked-His-Old-Stuff-Better',
 'EntryURL': 'https://www.imdb.com/title/tt3973036',
 'Entry_json': 'Favorites/Movies/snapshot/Kyle-Kinane-I-Liked-His-Old-Stuff-Better/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Kyle-Kinane-I-Liked-His-Old-Stuff-Better/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Kyle-Kinane-I-Liked-His-Old-Stuff-Better/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kyle Kinane',
            'url': '/name/nm2780278/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 163,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Kyle Kinane',
              'url': '/name/nm2780278/'},
             {'@type': 'Organization', 'url': '/company/co0384393/'}],
 'datePublished': '2015-01-23',
 'description': 'Kyle Kinane: I Liked His Old Stuff Better is a TV special '
                'starring Kyle Kinane. Filmed at the historic 40 Watt Club in '
                "Athens, Georgia, Kyle Kinane's new special delivers "
                'wonderfully grim anecdotes filtered through his own...',
 'director': [{'@type': 'Person',
               'name': 'Lance Bangs',
               'url': '/name/nm0051972/'}],
 'genre': ['Documentary', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYmE0OTA1ZWItODgwYy00ZmIwLWJiNjQtYzE5YmU2MDEwNjJlXkEyXkFqcGdeQXVyMTk2ODU0OTM@._V1_.jpg',
 'keywords': 'tv special,live audience,stand up comedy',
 'name': 'Kyle Kinane: I Liked His Old Stuff Better',
 'url': '/title/tt3973036/'}