{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-1987',
 'EntryURL': 'https://rawg.io/games/final-fantasy-1987',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-1987/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-1987/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-1987/thumb.jpg',
 'added': 139,
 'background_image': 'https://media.rawg.io/media/screenshots/656/6566c32aebb7b23af0573091132c2f2c.jpg',
 'developers': ['Square'],
 'genres': ['RPG'],
 'name': 'Final Fantasy (1987)',
 'platforms': ['NES', 'PlayStation', 'Nintendo 3DS', 'iOS', 'Wii', 'Wii U'],
 'publishers': ['Nintendo', 'Square'],
 'released': '1987-12-17',
 'slug': 'final-fantasy-1987'}