{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-03-12',
 'EntryPath': 'Favorites/Movies/snapshot/Big-Fish',
 'EntryURL': 'https://www.imdb.com/title/tt0319061',
 'Entry_json': 'Favorites/Movies/snapshot/Big-Fish/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Big-Fish/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Big-Fish/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ewan McGregor',
            'url': '/name/nm0000191/'},
           {'@type': 'Person',
            'name': 'Albert Finney',
            'url': '/name/nm0001215/'},
           {'@type': 'Person',
            'name': 'Billy Crudup',
            'url': '/name/nm0001082/'},
           {'@type': 'Person',
            'name': 'Jessica Lange',
            'url': '/name/nm0001448/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 407031,
                      'ratingValue': '8.0',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Daniel Wallace',
              'url': '/name/nm1180620/'},
             {'@type': 'Person',
              'name': 'John August',
              'url': '/name/nm0041864/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0021095/'},
             {'@type': 'Organization', 'url': '/company/co0093750/'},
             {'@type': 'Organization', 'url': '/company/co0081851/'}],
 'datePublished': '2004-01-09',
 'description': 'Big Fish is a movie starring Ewan McGregor, Albert Finney, '
                'and Billy Crudup. A frustrated son tries to determine the '
                "fact from fiction in his dying father's life.",
 'director': [{'@type': 'Person',
               'name': 'Tim Burton',
               'url': '/name/nm0000318/'}],
 'duration': 'PT2H5M',
 'genre': ['Adventure', 'Drama', 'Fantasy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMmU3NzIyODctYjVhOC00NzBmLTlhNWItMzBlODEwZTlmMjUzXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
 'keywords': 'storytelling,fish,father son relationship,death of '
             'father,flashback',
 'name': 'Big Fish',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A son tries to learn more about his dying father '
                             'by reliving stories and myths he told about his '
                             'life.',
              'embedUrl': '/video/imdb/vi1493149209',
              'name': 'Theatrical Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTk2OTYzNzE3M15BMl5BanBnXkFtZTcwMDY0NTMzOQ@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTk2OTYzNzE3M15BMl5BanBnXkFtZTcwMDY0NTMzOQ@@._V1_.jpg',
              'uploadDate': '2013-04-03T14:49:06Z'}],
 'url': '/title/tt0319061/'}