<?php
$infoArray = array('Actors' => array('Alec Baldwin',
            'Alex Fernandez',
            'Andrea Baker',
            'Annie Wu',
            'Barbara Harris',
            'Cathy Cavadini',
            'David Arnott',
            'David McCharen',
            'David Michie',
            'David Randolph',
            'David Rasner',
            'Donald Sutherland',
            'Dwight Schultz',
            'Greg Finley',
            'Jack Fletcher',
            'James Woods',
            'Jean Simmons',
            'John DeMita',
            'John Di Maggio',
            'Judi M Durand',
            'Julia Fletcher',
            'Keith David',
            'Lanei Chapman',
            'Matt Adler',
            'Matt McKenzie',
            'Ming-Na',
            'Peri Gilpin',
            'Richard Penn',
            'Steve Alterman',
            'Steve Buscemi',
            'Vicki Davis',
            'Ving Rhames'),
 'Added' => '2013-02-23',
 'Countries' => array('USA', 'Japan'),
 'Description' => '\nFinal Fantasy: The Spirits Within: A female scientist makes a last stand on Earth with the help of a ragtag team of soldiers against an invasion of alien phantoms. ',
 'Director' => array('Hironobu Sakaguchi'),
 'Genres' => array('Action',
            'Animation',
            'Thriller',
            'Sci-Fi',
            'Adventure',
            'Fantasy'),
 'IMDB' => 'http://www.imdb.com/title/tt0173840',
 'PrimeWire' => 'http://www.primewire.ag/watch-2277-Final-Fantasy-The-Spirits-Within',
 'Ratings' => array('IMDB' => '6.4/10',
             'Metascore' => '49%',
             'PrimeWire' => '4.10/5',
             'RT' => '44%',
             'Votes' => '343'),
 'Released' => '2001-07-02',
 'Runtime' => '106 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2277_Final_Fantasy_The_Spirits_Within_2001.jpg',
 'Title' => 'Final-Fantasy-The-Spirits-Within');
?>