{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Inside-Look-The-People-V-Oj-Simpson---American-Crime-Story',
 'EntryURL': 'https://www.imdb.com/title/tt6205862',
 'Entry_json': 'Favorites/TV/snapshot/Inside-Look-The-People-V-Oj-Simpson---American-Crime-Story/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Inside-Look-The-People-V-Oj-Simpson---American-Crime-Story/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Inside-Look-The-People-V-Oj-Simpson---American-Crime-Story/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sarah Paulson',
            'url': '/name/nm0005299/'},
           {'@type': 'Person',
            'name': 'Brad Simpson',
            'url': '/name/nm0800922/'},
           {'@type': 'Person',
            'name': 'Sterling K. Brown',
            'url': '/name/nm1250791/'},
           {'@type': 'Person',
            'name': 'Nina Jacobson',
            'url': '/name/nm1749221/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 21703,
                      'ratingValue': '8.4',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Organization', 'url': '/company/co0060381/'},
             {'@type': 'Organization', 'url': '/company/co0371071/'}],
 'datePublished': '2016-01-19',
 'description': 'Inside Look: The People v. O.J. Simpson - American Crime '
                'Story is a TV series starring Sarah Paulson, Brad Simpson, '
                'and Sterling K. Brown. Inside the series of the same name.',
 'genre': ['Documentary', 'Short'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTgyZmYzM2YtZDQ3YS00ODJhLWIyYzEtN2QzYjA5YTZjZGM0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'behind the scenes,making of',
 'name': 'Inside Look: The People v. O.J. Simpson - American Crime Story',
 'url': '/title/tt6205862/'}