{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-12-19',
 'EntryPath': 'Favorites/Movies/snapshot/Degenerate-Art-The-Art-and-Culture-of-Glass-Pipes',
 'EntryURL': 'https://www.imdb.com/title/tt2123927',
 'Entry_json': 'Favorites/Movies/snapshot/Degenerate-Art-The-Art-and-Culture-of-Glass-Pipes/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Degenerate-Art-The-Art-and-Culture-of-Glass-Pipes/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Degenerate-Art-The-Art-and-Culture-of-Glass-Pipes/thumb.jpg',
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 178,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Organization', 'url': '/company/co0363060/'}],
 'datePublished': '2011-10-12',
 'director': [{'@type': 'Person',
               'name': 'Marble Slinger',
               'url': '/name/nm5028199/'}],
 'duration': 'PT1H16M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjAxNjgyMTAyOF5BMl5BanBnXkFtZTgwODUxMTA3NjE@._V1_.jpg',
 'keywords': 'glass pipe,documentarian',
 'name': 'Degenerate Art: The Art and Culture of Glass Pipes',
 'url': '/title/tt2123927/'}