{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iv',
 'EntryURL': 'https://rawg.io/games/grand-theft-auto-iv',
 'Entry_json': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iv/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iv/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iv/thumb.jpg',
 'added': 7234,
 'background_image': 'https://media.rawg.io/media/games/4a0/4a0a1316102366260e6f38fd2a9cfdce.jpg',
 'developers': ['Rockstar North', 'Rockstar Toronto'],
 'genres': ['Action', 'Adventure'],
 'name': 'Grand Theft Auto IV',
 'platforms': ['PC', 'PlayStation 3', 'Xbox 360'],
 'publishers': ['Capcom', 'Rockstar Games', 'Take Two Interactive'],
 'released': '2008-04-29',
 'slug': 'grand-theft-auto-iv'}