{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Paradise-Pd',
 'EntryURL': 'https://www.imdb.com/title/tt8235236',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Paradise-Pd/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Paradise-Pd/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Paradise-Pd/info.py',
 'Title': 'Paradise PD',
 'actor': [{'@type': 'Person',
            'name': 'Sarah Chalke',
            'url': '/name/nm0149950/'},
           {'@type': 'Person',
            'name': 'David Herman',
            'url': '/name/nm0379114/'},
           {'@type': 'Person', 'name': 'Tom Kenny', 'url': '/name/nm0444786/'},
           {'@type': 'Person',
            'name': 'Kyle Kinane',
            'url': '/name/nm2780278/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 11734,
                     'ratingValue': '7.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Roger Black',
              'url': '/name/nm1318600/'},
             {'@type': 'Person',
              'name': "Waco O'Guin",
              'url': '/name/nm1975097/'},
             {'@type': 'Organization', 'url': '/company/co0323891/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0113457/'}],
 'datePublished': '2018-08-31',
 'description': 'Paradise PD is a TV series starring Sarah Chalke, David '
                'Herman, and Tom Kenny. Animated series about bad cops. Not '
                "bad as in corrupt, bad as in under-performing. They aren't "
                'first responders, they are the worst responders.',
 'genre': ['Animation', 'Action', 'Comedy', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU2NjgxNTUxMF5BMl5BanBnXkFtZTgwMzM4MjMwNjM@._V1_.jpg',
 'keywords': 'cop,cop comedy,adult cartoon,netflix original,ineptitude',
 'name': 'Paradise PD',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'nickspiros'},
            'dateCreated': '2018-09-28',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt8235236/'},
            'name': 'Mirroring Brickleberry (as already pointed out)',
            'reviewBody': "It's essentially the same characters from "
                          'Brickleberry in another universe, yet it still '
                          'works and works well! The show does not shy away '
                          'from admitting this either. Very goofy/quirky adult '
                          'cartoon comedy that really goes for it-akin to '
                          'South Park, Family Guy, Brickleberry and Archer. '
                          'Great show to unwind to!',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'url': '/title/tt8235236/'}