{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Paradise-Pd',
 'EntryURL': 'https://www.imdb.com/title/tt8235236',
 'Entry_json': 'Favorites/TV/snapshot/Paradise-Pd/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Paradise-Pd/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Paradise-Pd/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sarah Chalke',
            'url': '/name/nm0149950/'},
           {'@type': 'Person',
            'name': 'David Herman',
            'url': '/name/nm0379114/'},
           {'@type': 'Person', 'name': 'Tom Kenny', 'url': '/name/nm0444786/'},
           {'@type': 'Person',
            'name': 'Kyle Kinane',
            'url': '/name/nm2780278/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 12183,
                      'ratingValue': '6.9',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Roger Black',
              'url': '/name/nm1318600/'},
             {'@type': 'Person',
              'name': "Waco O'Guin",
              'url': '/name/nm1975097/'},
             {'@type': 'Organization', 'url': '/company/co0323891/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0113457/'}],
 'datePublished': '2018-08-31',
 'description': 'Paradise PD is a TV series starring Sarah Chalke, David '
                'Herman, and Tom Kenny. Animated series about bad cops. Not '
                "bad as in corrupt, bad as in under-performing. They aren't "
                'first responders, they are the worst responders.',
 'genre': ['Animation', 'Action', 'Comedy', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU2NjgxNTUxMF5BMl5BanBnXkFtZTgwMzM4MjMwNjM@._V1_.jpg',
 'keywords': 'cop,cop comedy,adult cartoon,netflix original,ineptitude',
 'name': 'Paradise PD',
 'url': '/title/tt8235236/'}