{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-11-13',
 'EntryPath': 'Favorites/Movies/snapshot/The-Citizen',
 'EntryURL': 'https://www.imdb.com/title/tt1942989',
 'Entry_json': 'Favorites/Movies/snapshot/The-Citizen/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Citizen/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Citizen/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Khaled Nabawy',
            'url': '/name/nm0252728/'},
           {'@type': 'Person',
            'name': 'Agnes Bruckner',
            'url': '/name/nm0115671/'},
           {'@type': 'Person',
            'name': 'Rizwan Manji',
            'url': '/name/nm0542492/'},
           {'@type': 'Person',
            'name': 'William Atherton',
            'url': '/name/nm0040472/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3151,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Jazmen Darnell Brown',
              'url': '/name/nm3195822/'},
             {'@type': 'Person', 'name': 'Sam Kadi', 'url': '/name/nm3018890/'},
             {'@type': 'Person', 'name': 'Sam Kadi', 'url': '/name/nm3018890/'},
             {'@type': 'Person',
              'name': 'Samir Younis',
              'url': '/name/nm1273456/'},
             {'@type': 'Organization', 'url': '/company/co0347252/'},
             {'@type': 'Organization', 'url': '/company/co0347255/'}],
 'datePublished': '2013-09-27',
 'description': 'The Citizen is a movie starring Khaled Nabawy, Agnes '
                'Bruckner, and Rizwan Manji. An Arab immigrant wins the '
                'American green card lottery, arriving in New York City on '
                'September 10, 2001.',
 'director': [{'@type': 'Person',
               'name': 'Sam Kadi',
               'url': '/name/nm3018890/'}],
 'duration': 'PT1H39M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BNjMwMjUxMzUxNF5BMl5BanBnXkFtZTcwNDIyNTUzOA@@._V1_.jpg',
 'keywords': 'city',
 'name': 'The Citizen',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A drama centered on Ibrahim, an Arab immigrant '
                             'who wins the American green card lottery, '
                             'arriving in New York City on September 10th, '
                             '2001.',
              'embedUrl': '/video/imdb/vi539796761',
              'name': 'U.S. Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjA5MjU2MTIyNF5BMl5BanBnXkFtZTcwNzY1OTQzOA@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjA5MjU2MTIyNF5BMl5BanBnXkFtZTcwNzY1OTQzOA@@._V1_.jpg',
              'uploadDate': '2012-08-29T08:51:59Z'}],
 'url': '/title/tt1942989/'}