{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Trailer-Park-Boys',
 'EntryURL': 'https://www.imdb.com/title/tt0290988',
 'Entry_json': 'Favorites/TV/snapshot/Trailer-Park-Boys/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Trailer-Park-Boys/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Trailer-Park-Boys/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Paul Tremblay',
            'url': '/name/nm1033215/'},
           {'@type': 'Person', 'name': 'Robb Wells', 'url': '/name/nm1036211/'},
           {'@type': 'Person', 'name': 'Mike Smith', 'url': '/name/nm1034266/'},
           {'@type': 'Person',
            'name': 'John Dunsworth',
            'url': '/name/nm0243082/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 35619,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Mike Clattenburg',
              'url': '/name/nm0154104/'},
             {'@type': 'Organization', 'url': '/company/co0452209/'},
             {'@type': 'Organization', 'url': '/company/co0045140/'},
             {'@type': 'Organization', 'url': '/company/co0064423/'},
             {'@type': 'Organization', 'url': '/company/co0044921/'}],
 'datePublished': '2001-04-22',
 'description': 'Trailer Park Boys is a TV series starring John Paul Tremblay, '
                'Robb Wells, and Mike Smith. Three petty felons have a '
                'documentary made about their life in a trailer park.',
 'genre': ['Comedy', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTA0NTAwMTc1MF5BMl5BanBnXkFtZTgwODk2NjY0ODE@._V1_.jpg',
 'keywords': 'trailer park,poverty,group of friends,mockumentary,trailer home',
 'name': 'Trailer Park Boys',
 'trailer': {'@type': 'VideoObject',
             'description': 'Season 10 trailer for Trailer Park Boys on '
                            'Netflix.',
             'embedUrl': '/video/imdb/vi1080472857',
             'name': 'Season 10 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjM1NzQwNTE1Ml5BMl5BanBnXkFtZTgwNjY2NjY0ODE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjM1NzQwNTE1Ml5BMl5BanBnXkFtZTgwNjY2NjY0ODE@._V1_.jpg',
             'uploadDate': '2016-03-29T08:18:15Z'},
 'url': '/title/tt0290988/'}