{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-07-20',
 'EntryPath': 'Favorites/Movies/snapshot/Pleasantville',
 'EntryURL': 'https://www.imdb.com/title/tt0120789',
 'Entry_json': 'Favorites/Movies/snapshot/Pleasantville/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Pleasantville/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Pleasantville/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Tobey Maguire',
            'url': '/name/nm0001497/'},
           {'@type': 'Person',
            'name': 'Jeff Daniels',
            'url': '/name/nm0001099/'},
           {'@type': 'Person', 'name': 'Joan Allen', 'url': '/name/nm0000260/'},
           {'@type': 'Person',
            'name': 'William H. Macy',
            'url': '/name/nm0000513/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 118631,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Gary Ross',
              'url': '/name/nm0002657/'},
             {'@type': 'Organization', 'url': '/company/co0046718/'},
             {'@type': 'Organization', 'url': '/company/co0018471/'}],
 'datePublished': '1998-10-23',
 'description': 'Pleasantville is a movie starring Tobey Maguire, Jeff '
                'Daniels, and Joan Allen. Two 1990s teenage siblings find '
                'themselves in a 1950s sitcom, where their influence begins to '
                'profoundly change that complacent world.',
 'director': {'@type': 'Person',
              'name': 'Gary Ross',
              'url': '/name/nm0002657/'},
 'duration': 'PT2H4M',
 'genre': ['Comedy', 'Drama', 'Fantasy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTRlYzk4NDktODE3Ni00YjFkLWFjYmUtNjg1MzdmYmFmOTJkXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg',
 'keywords': '1950s,trapped in tv,censorship,symbolism,rebellion',
 'name': 'Pleasantville',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi2979791129',
             'name': 'Pleasantville',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTc1ZDU2OWUtMGFmYy00YmFhLWIyOGQtOWJiNzUyYzhlMzU1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTc1ZDU2OWUtMGFmYy00YmFhLWIyOGQtOWJiNzUyYzhlMzU1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T15:25:12Z'},
 'url': '/title/tt0120789/'}