{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Witcher-3-Wild-Hunt',
 'EntryURL': 'https://rawg.io/games/the-witcher-3-wild-hunt',
 'Entry_json': 'Favorites/Games/snapshot/The-Witcher-3-Wild-Hunt/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Witcher-3-Wild-Hunt/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Witcher-3-Wild-Hunt/thumb.jpg',
 'added': 10199,
 'background_image': 'https://media.rawg.io/media/games/088/088b41ca3f9d22163e43be07acf42304.jpg',
 'developers': ['CD PROJEKT RED'],
 'genres': ['Action', 'Adventure', 'RPG'],
 'name': 'The Witcher 3: Wild Hunt',
 'platforms': ['PC', 'Xbox One', 'Nintendo Switch', 'PlayStation 4'],
 'publishers': ['CD PROJEKT RED'],
 'released': '2015-05-18',
 'slug': 'the-witcher-3-wild-hunt'}