{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-12-09',
 'EntryPath': 'Favorites/Movies/snapshot/One-Rat-Short',
 'EntryURL': 'https://www.imdb.com/title/tt0818125',
 'Entry_json': 'Favorites/Movies/snapshot/One-Rat-Short/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/One-Rat-Short/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/One-Rat-Short/thumb.jpg',
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 567,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Alex Weil',
              'url': '/name/nm0917933/'},
             {'@type': 'Organization', 'url': '/company/co0182075/'}],
 'datePublished': '2006-06-28',
 'director': [{'@type': 'Person',
               'name': 'Alex Weil',
               'url': '/name/nm0917933/'}],
 'duration': 'PT10M',
 'genre': ['Animation', 'Short'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY2MDk1ODYzN15BMl5BanBnXkFtZTcwNzY2MDUzMQ@@._V1_.jpg',
 'keywords': 'rat,snack,camera,barcode,injection',
 'name': 'One Rat Short',
 'url': '/title/tt0818125/'}