{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-30',
 'EntryPath': 'Favorites/Movies/snapshot/Waiting-for-Superman',
 'EntryURL': 'https://www.imdb.com/title/tt1566648',
 'Entry_json': 'Favorites/Movies/snapshot/Waiting-for-Superman/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Waiting-for-Superman/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Waiting-for-Superman/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Charles Adam',
            'url': '/name/nm5653572/'},
           {'@type': 'Person',
            'name': 'Charles Adams',
            'url': '/name/nm5653622/'},
           {'@type': 'Person',
            'name': 'Jonathan Alter',
            'url': '/name/nm1146602/'},
           {'@type': 'Person',
            'name': 'Robert Balfanz',
            'url': '/name/nm5661092/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 10517,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'Davis Guggenheim',
              'url': '/name/nm0346550/'},
             {'@type': 'Person',
              'name': 'Billy Kimball',
              'url': '/name/nm1269014/'},
             {'@type': 'Organization', 'url': '/company/co0247967/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'},
             {'@type': 'Organization', 'url': '/company/co0073388/'}],
 'datePublished': '2010-10-29',
 'description': "Waiting for 'Superman' is a movie starring Charles Adam, "
                'Charles Adams, and Jonathan Alter. An examination of the '
                'current state of education in America today.',
 'director': [{'@type': 'Person',
               'name': 'Davis Guggenheim',
               'url': '/name/nm0346550/'}],
 'duration': 'PT1H51M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI3ODUxODE0M15BMl5BanBnXkFtZTcwODM0NzU0Mw@@._V1_.jpg',
 'keywords': 'education,new york,los angeles california,redwood city '
             'california,woodside california',
 'name': "Waiting for 'Superman'",
 'trailer': [{'@type': 'VideoObject',
              'description': 'This documentary follows a handful of promising '
                             'kids through a system that inhibits, rather than '
                             'encourages, academic growth, and undertakes an '
                             'exhaustive review of public education, surveying '
                             '"drop-out factories" and "academic sinkholes," '
                             'methodically dissecting the system and its '
                             'seemingly intractable problems.',
              'embedUrl': '/video/imdb/vi2518550297',
              'name': 'Waiting for Superman',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjI3NDMyMzE1NF5BMl5BanBnXkFtZTgwMTQ0NDczMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjI3NDMyMzE1NF5BMl5BanBnXkFtZTgwMTQ0NDczMzE@._V1_.jpg',
              'uploadDate': '2010-05-11T13:31:45Z'}],
 'url': '/title/tt1566648/'}