{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Grand-Theft-Auto-V',
 'EntryURL': 'https://rawg.io/games/grand-theft-auto-v',
 'Entry_json': 'Favorites/Games/snapshot/Grand-Theft-Auto-V/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Grand-Theft-Auto-V/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Grand-Theft-Auto-V/thumb.jpg',
 'added': 11950,
 'background_image': 'https://media.rawg.io/media/games/b11/b115b2bc6a5957a917bc7601f4abdda2.jpg',
 'developers': ['Rockstar North'],
 'genres': ['Action', 'Adventure'],
 'name': 'Grand Theft Auto V',
 'platforms': ['PC', 'PlayStation 4', 'PlayStation 3', 'Xbox 360', 'Xbox One'],
 'publishers': ['1C-SoftClub', 'Rockstar Games', 'Take Two Interactive'],
 'released': '2013-09-17',
 'slug': 'grand-theft-auto-v'}