{'Actors': ['David Fincher',
            'David Lynch',
            'Dennis Muren',
            'George Lucas',
            'Greta Gerwig',
            'James Cameron',
            'Joel Schumacher',
            'Keanu Reeves',
            'Lars von Trier',
            'Lena Dunham',
            'Martin Scorsese',
            'Michael Ballhaus',
            'Michael Chapman',
            'Richard Linklater',
            'Robert Rodriguez',
            'Steven Soderbergh',
            'Vilmos Zsigmond',
            'Vittorio Storaro'],
 'Added': '2013-03-03',
 'Countries': ['USA'],
 'Description': '\nSide by Side: The documentary investigates the history, process and workflow of both digital and photochemical film creation. ',
 'Director': ['Christopher Kenneally'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt2014338',
 'PrimeWire': 'http://www.primewire.ag/watch-2735529-Side-by-Side',
 'Ratings': {'IMDB': '7.7/10',
             'Metascore': '82%',
             'PrimeWire': '4.17/5',
             'RT': '92%',
             'Votes': '29'},
 'Released': '2012-08-17',
 'Runtime': '99 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2735529_Side_by_Side_2012.jpg',
 'Title': 'Side-by-Side'}