{'@context': 'http://schema.org',
 '@type': 'CreativeWork',
 'EntryAdded': '2014-05-18',
 'EntryPath': 'Favorites/Movies/snapshot/The-Third-and-the-Seventh',
 'EntryURL': 'https://www.imdb.com/title/tt3321150',
 'Entry_json': 'Favorites/Movies/snapshot/The-Third-and-the-Seventh/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Third-and-the-Seventh/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Third-and-the-Seventh/thumb.jpg',
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 52,
                      'ratingValue': '7.9',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Alex Roman',
              'url': '/name/nm6074260/'}],
 'datePublished': '2009-11-24',
 'director': [{'@type': 'Person',
               'name': 'Alex Roman',
               'url': '/name/nm6074260/'}],
 'genre': 'Short',
 'image': 'https://m.media-amazon.com/images/M/MV5BNzAxM2M4ZjUtYmMzZC00OTZkLWFhNmYtZDZkMDI4MjVjOWNhXkEyXkFqcGdeQXVyMzIxNDM2NjU@._V1_.jpg',
 'name': 'The Third & the Seventh',
 'url': '/title/tt3321150/'}