{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-21',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Congress',
 'EntryURL': 'https://www.imdb.com/title/tt1821641',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Congress/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Congress/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Congress/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Robin Wright',
            'url': '/name/nm0000705/'},
           {'@type': 'Person',
            'name': 'Harvey Keitel',
            'url': '/name/nm0000172/'},
           {'@type': 'Person', 'name': 'Jon Hamm', 'url': '/name/nm0358316/'},
           {'@type': 'Person',
            'name': 'Kodi Smit-McPhee',
            'url': '/name/nm2240346/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 16925,
                     'ratingValue': '6.5',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Stanislaw Lem',
              'url': '/name/nm0501015/'},
             {'@type': 'Person',
              'name': 'Ari Folman',
              'url': '/name/nm0284369/'},
             {'@type': 'Organization', 'url': '/company/co0232356/'},
             {'@type': 'Organization', 'url': '/company/co0052813/'},
             {'@type': 'Organization', 'url': '/company/co0054609/'},
             {'@type': 'Organization', 'url': '/company/co0016812/'},
             {'@type': 'Organization', 'url': '/company/co0001178/'},
             {'@type': 'Organization', 'url': '/company/co0325503/'},
             {'@type': 'Organization', 'url': '/company/co0249743/'}],
 'datePublished': '2013-07-03',
 'description': 'The Congress is a movie starring Robin Wright, Harvey Keitel, '
                'and Jon Hamm. An aging, out-of-work actress accepts one last '
                'job, though the consequences of her decision affect her in '
                "ways she didn't consider.",
 'director': {'@type': 'Person',
              'name': 'Ari Folman',
              'url': '/name/nm0284369/'},
 'duration': 'PT2H2M',
 'genre': ['Animation', 'Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE5MTUzNDk3M15BMl5BanBnXkFtZTgwMTUwNTQ5MTE@._V1_.jpg',
 'keywords': 'satire,dystopia,cinema,tom cruise character,barcode license '
             'plate',
 'name': 'The Congress',
 'trailer': {'@type': 'VideoObject',
             'description': 'An aging, out-of-work actress accepts one last '
                            'job, though the consequences of her decision '
                            "affect her in ways she didn't consider",
             'embedUrl': '/video/imdb/vi892512537',
             'name': 'International Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjk1ODkwNzMwNV5BMl5BanBnXkFtZTgwMjU3NDAwMDE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjk1ODkwNzMwNV5BMl5BanBnXkFtZTgwMjU3NDAwMDE@._V1_.jpg',
             'uploadDate': '2013-08-06T19:57:14Z'},
 'url': '/title/tt1821641/'}