{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-07-01',
 'EntryPath': 'Favorites/Movies/snapshot/The-Internets-Own-Boy-The-Story-of-Aaron-Swartz',
 'EntryURL': 'https://www.imdb.com/title/tt3268458',
 'Entry_json': 'Favorites/Movies/snapshot/The-Internets-Own-Boy-The-Story-of-Aaron-Swartz/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Internets-Own-Boy-The-Story-of-Aaron-Swartz/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Internets-Own-Boy-The-Story-of-Aaron-Swartz/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Aaron Swartz',
            'url': '/name/nm2290901/'},
           {'@type': 'Person',
            'name': 'Tim Berners-Lee',
            'url': '/name/nm3805083/'},
           {'@type': 'Person', 'name': 'Cindy Cohn', 'url': '/name/nm3981659/'},
           {'@type': 'Person',
            'name': 'Gabriella Coleman',
            'url': '/name/nm4944031/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 15120,
                     'ratingValue': '8.0',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Brian Knappenberger',
              'url': '/name/nm0460534/'},
             {'@type': 'Organization', 'url': '/company/co0294764/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'},
             {'@type': 'Organization', 'url': '/company/co0319011/'},
             {'@type': 'Organization', 'url': '/company/co0510542/'}],
 'datePublished': '2014-06-27',
 'description': "The Internet's Own Boy: The Story of Aaron Swartz is a movie "
                'starring Aaron Swartz, Tim Berners-Lee, and Cindy Cohn. The '
                'story of programming prodigy and information activist Aaron '
                'Swartz, who took his own life at the age of 26.',
 'director': {'@type': 'Person',
              'name': 'Brian Knappenberger',
              'url': '/name/nm0460534/'},
 'duration': 'PT1H45M',
 'genre': ['Documentary', 'Biography', 'Crime'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjgwOTgwNjQ5MV5BMl5BanBnXkFtZTgwMzk1NTQ2MTE@._V1_.jpg',
 'keywords': 'internet,suicide,child prodigy,internet freedom,internet '
             'politics',
 'name': "The Internet's Own Boy: The Story of Aaron Swartz",
 'trailer': {'@type': 'VideoObject',
             'description': "Traile for The Internet's Own Boy: The Story of "
                            'Aaron Swartz',
             'embedUrl': '/video/imdb/vi937277977',
             'name': "The Internet's Own Boy: The Story of Aaron Swartz",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYzJjMDdjMmMtYTI2NC00ZTc4LWIxYmQtZmRjNDg2YmI1ZWYzXkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYzJjMDdjMmMtYTI2NC00ZTc4LWIxYmQtZmRjNDg2YmI1ZWYzXkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg',
             'uploadDate': '2018-12-04T17:31:47Z'},
 'url': '/title/tt3268458/'}