{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-08-13',
 'EntryPath': 'Favorites/TV/snapshot/Party-Legends',
 'EntryURL': 'https://www.imdb.com/title/tt5849156',
 'Entry_json': 'Favorites/TV/snapshot/Party-Legends/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Party-Legends/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Party-Legends/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Kreayshawn', 'url': '/name/nm4590612/'},
           {'@type': 'Person', 'name': 'Eric André', 'url': '/name/nm2765191/'},
           {'@type': 'Person',
            'name': 'Fred Armisen',
            'url': '/name/nm0035488/'},
           {'@type': 'Person',
            'name': 'Bushwick Bill',
            'url': '/name/nm0082266/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 96,
                     'ratingValue': '7.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': {'@type': 'Organization', 'url': '/company/co0285679/'},
 'datePublished': '2016-07-07',
 'description': 'Party Legends is a TV series starring Kreayshawn, Eric André, '
                'and Fred Armisen. Notable and notorious personalities share '
                'their best party stories. Filmmaker Lance Bangs envisions '
                'each one with help from emerging artists and...',
 'genre': 'Animation',
 'image': 'https://m.media-amazon.com/images/M/MV5BMWVmOWFjNmYtYmIzMy00ZTM0LWE2MGMtNDRjMDNmMTY4NzZhXkEyXkFqcGdeQXVyMjIwMTk3OTM@._V1_.jpg',
 'name': 'Party Legends',
 'url': '/title/tt5849156/'}