{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-08-21',
 'EntryPath': 'Favorites/TV/snapshot/The-Joy-of-Painting',
 'EntryURL': 'https://www.imdb.com/title/tt0383795',
 'Entry_json': 'Favorites/TV/snapshot/The-Joy-of-Painting/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Joy-of-Painting/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Joy-of-Painting/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Bob Ross', 'url': '/name/nm1470679/'},
           {'@type': 'Person', 'name': 'Steve Ross', 'url': '/name/nm7142061/'},
           {'@type': 'Person',
            'name': 'Dana Jester',
            'url': '/name/nm9100257/'},
           {'@type': 'Person', 'name': 'Peep', 'url': '/name/nm9461155/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3982,
                      'ratingValue': '9.4',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-G',
 'creator': [{'@type': 'Organization', 'url': '/company/co0068574/'}],
 'datePublished': '1983-01-11',
 'description': 'The Joy of Painting is a TV series starring Bob Ross, Steve '
                'Ross, and Dana Jester. In this half-hour program, artist Bob '
                'Ross paints on canvas a beautiful oil painting.',
 'genre': ['Documentary', 'Family'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODVhYjY3OGUtNmFkMi00ZTVkLWJjYTAtODBhN2JhNjAwOWI5XkEyXkFqcGdeQXVyNzcwMTc0Mg@@._V1_.jpg',
 'keywords': 'canvas,paint,painting,artist,landscape',
 'name': 'The Joy of Painting',
 'url': '/title/tt0383795/'}