{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-07-21',
 'EntryPath': 'Favorites/Movies/snapshot/Creation',
 'EntryURL': 'https://www.imdb.com/title/tt0974014',
 'Entry_json': 'Favorites/Movies/snapshot/Creation/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Creation/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Creation/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Paul Bettany',
            'url': '/name/nm0079273/'},
           {'@type': 'Person',
            'name': 'Jennifer Connelly',
            'url': '/name/nm0000124/'},
           {'@type': 'Person', 'name': 'Ian Kelly', 'url': '/name/nm4037686/'},
           {'@type': 'Person', 'name': 'Guy Henry', 'url': '/name/nm0377844/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 13573,
                      'ratingValue': '6.7',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'John Collee',
              'url': '/name/nm0171722/'},
             {'@type': 'Person',
              'name': 'Jon Amiel',
              'url': '/name/nm0000750/'},
             {'@type': 'Person',
              'name': 'John Collee',
              'url': '/name/nm0171722/'},
             {'@type': 'Person',
              'name': 'Randal Keynes',
              'url': '/name/nm2568171/'},
             {'@type': 'Organization', 'url': '/company/co0029168/'},
             {'@type': 'Organization', 'url': '/company/co0103694/'},
             {'@type': 'Organization', 'url': '/company/co0133023/'},
             {'@type': 'Organization', 'url': '/company/co0286801/'},
             {'@type': 'Organization', 'url': '/company/co0104811/'}],
 'datePublished': '2009-09-25',
 'description': 'Creation is a movie starring Paul Bettany, Jennifer Connelly, '
                'and Ian Kelly. Torn between faith and science, and suffering '
                'hallucinations, English naturalist Charles Darwin struggles '
                "to complete 'On the Origin of Species' and...",
 'director': [{'@type': 'Person',
               'name': 'Jon Amiel',
               'url': '/name/nm0000750/'}],
 'duration': 'PT1H48M',
 'genre': ['Biography', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjAwMjgxMDUwNl5BMl5BanBnXkFtZTcwMjM3ODAxMw@@._V1_.jpg',
 'keywords': 'hallucination,marriage between cousins,father daughter '
             'relationship,evolution,loss of daughter',
 'name': 'Creation',
 'trailer': [{'@type': 'VideoObject',
              'description': 'English naturalist Charles Darwin struggles to '
                             'find a balance between his revolutionary '
                             'theories on evolution and the relationship with '
                             'religious wife, whose faith contradicts his '
                             'work.',
              'embedUrl': '/video/imdb/vi764871705',
              'name': 'Creation',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTYwMjQ4NTM4MF5BMl5BanBnXkFtZTcwOTAzOTYwMw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTYwMjQ4NTM4MF5BMl5BanBnXkFtZTcwOTAzOTYwMw@@._V1_.jpg',
              'uploadDate': '2009-12-19T15:57:42Z'}],
 'url': '/title/tt0974014/'}