<?php
$infoArray = array('Actors' => array('Arnold Schwarzenegger',
            'Bill Clinton',
            'Dick Cheney',
            'George W Bush',
            'Jay Leno',
            'Kevin Phillips',
            'Maria Shriver',
            'Peter Coyote',
            'Ronald Reagan'),
 'Added' => '2016-09-14',
 'Countries' => array('USA'),
 'Description' => '\nEnron: The Smartest Guys in the Room: A documentary about the Enron corporation, its faulty and corrupt business practices, and how they led to its fall. ',
 'Director' => array('Alex Gibney'),
 'Genres' => array('Documentary'),
 'IMDB' => 'http://www.imdb.com/title/tt1016268',
 'PrimeWire' => 'http://www.primewire.ag/watch-19240-Enron-The-Smartest-Guys-in-the-Room',
 'Ratings' => array('IMDB' => '7.7/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.53/5',
             'RT' => 'N/A',
             'Votes' => '98'),
 'Released' => '2005-04-22',
 'Runtime' => '110 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/19240_Enron_The_Smartest_Guys_in_the_Room_2005.jpg',
 'Title' => 'Enron-The-Smartest-Guys-in-the-Room');
?>