{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-09-14',
 'EntryPath': 'Favorites/Movies/snapshot/Enron-The-Smartest-Guys-in-the-Room',
 'EntryURL': 'https://www.imdb.com/title/tt1016268',
 'Entry_json': 'Favorites/Movies/snapshot/Enron-The-Smartest-Guys-in-the-Room/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Enron-The-Smartest-Guys-in-the-Room/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Enron-The-Smartest-Guys-in-the-Room/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'John Beard', 'url': '/name/nm1933035/'},
           {'@type': 'Person', 'name': 'Tim Belden', 'url': '/name/nm4036323/'},
           {'@type': 'Person',
            'name': 'Barbara Boxer',
            'url': '/name/nm0101526/'},
           {'@type': 'Person',
            'name': 'George W. Bush',
            'url': '/name/nm0124133/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 16394,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alex Gibney',
              'url': '/name/nm0316795/'},
             {'@type': 'Person',
              'name': 'Bethany McLean',
              'url': '/name/nm1628322/'},
             {'@type': 'Person',
              'name': 'Peter Elkind',
              'url': '/name/nm1646482/'},
             {'@type': 'Organization', 'url': '/company/co0133364/'},
             {'@type': 'Organization', 'url': '/company/co0005596/'},
             {'@type': 'Organization', 'url': '/company/co0094788/'}],
 'datePublished': '2005-05-20',
 'description': 'Enron: The Smartest Guys in the Room is a movie starring John '
                'Beard, Tim Belden, and Barbara Boxer. A documentary about the '
                'Enron corporation, its faulty and corrupt business practices, '
                'and how they led to its fall.',
 'director': [{'@type': 'Person',
               'name': 'Alex Gibney',
               'url': '/name/nm0316795/'}],
 'duration': 'PT1H50M',
 'genre': ['Documentary', 'Biography', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjI0ODAxMDUwNl5BMl5BanBnXkFtZTcwMDU3MjE1MQ@@._V1_.jpg',
 'keywords': 'enron,corporation,accounting,accounting fraud,corporate crime',
 'name': 'Enron: The Smartest Guys in the Room',
 'url': '/title/tt1016268/'}