{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-11-05',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Apex-The-Story-of-the-Hypercar',
 'EntryURL': 'https://www.imdb.com/title/tt4325400',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Apex-The-Story-of-the-Hypercar/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Apex-The-Story-of-the-Hypercar/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Apex-The-Story-of-the-Hypercar/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Manuel Berglung',
            'url': '/name/nm7995173/'},
           {'@type': 'Person',
            'name': 'Chris Goodwin',
            'url': '/name/nm7995174/'},
           {'@type': 'Person',
            'name': 'Dan Greenawalt',
            'url': '/name/nm2204799/'},
           {'@type': 'Person',
            'name': 'Chris Harris',
            'url': '/name/nm1219851/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1534,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'Unrated',
 'creator': {'@type': 'Person',
             'name': 'Mike Spinelli',
             'url': '/name/nm6523814/'},
 'datePublished': '2016-03-29',
 'description': 'Apex: The Story of the Hypercar is a movie starring Manuel '
                'Berglung, Chris Goodwin, and Dan Greenawalt. "APEX: The Story '
                'of the Hypercar" spotlights a new class of exotic sports cars '
                'designed to blast from zero to 200 miles per hour...',
 'director': [{'@type': 'Person',
               'name': 'J.F. Musial',
               'url': '/name/nm6531331/'},
              {'@type': 'Person',
               'name': 'Josh Vietze',
               'url': '/name/nm7029305/'}],
 'duration': 'PT1H25M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BYWI1NGMxYjEtOWQ5My00NWY2LTlmMDEtZTBkNjYzZjZlYzI4XkEyXkFqcGdeQXVyNDI4ODczMDE@._V1_.jpg',
 'name': 'Apex: The Story of the Hypercar',
 'url': '/title/tt4325400/'}