{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Dragon-Age-Inquisition',
 'EntryURL': 'https://rawg.io/games/dragon-age-inquisition',
 'Entry_json': 'Favorites/Games/snapshot/Dragon-Age-Inquisition/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Dragon-Age-Inquisition/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Dragon-Age-Inquisition/thumb.jpg',
 'added': 2968,
 'background_image': 'https://media.rawg.io/media/games/260/26023c855f1769a93411d6a7ea084632.jpeg',
 'developers': ['BioWare', 'BioWare Edmonton'],
 'genres': ['RPG'],
 'name': 'Dragon Age: Inquisition',
 'platforms': ['PlayStation 3', 'Xbox 360', 'Xbox One', 'PlayStation 4', 'PC'],
 'publishers': ['Electronic Arts'],
 'released': '2014-11-18',
 'slug': 'dragon-age-inquisition'}