{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Revolutions',
 'EntryURL': 'https://www.imdb.com/title/tt0242653',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Revolutions/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Revolutions/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Revolutions/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Matrix-Revolutions/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Keanu Reeves',
            'url': '/name/nm0000206/'},
           {'@type': 'Person',
            'name': 'Laurence Fishburne',
            'url': '/name/nm0000401/'},
           {'@type': 'Person',
            'name': 'Carrie-Anne Moss',
            'url': '/name/nm0005251/'},
           {'@type': 'Person',
            'name': 'Hugo Weaving',
            'url': '/name/nm0915989/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 435277,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Lilly Wachowski',
              'url': '/name/nm0905152/'},
             {'@type': 'Person',
              'name': 'Lana Wachowski',
              'url': '/name/nm0905154/'},
             {'@type': 'Person',
              'name': 'Lilly Wachowski',
              'url': '/name/nm0905152/'},
             {'@type': 'Person',
              'name': 'Lana Wachowski',
              'url': '/name/nm0905154/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0108864/'},
             {'@type': 'Organization', 'url': '/company/co0024939/'},
             {'@type': 'Organization', 'url': '/company/co0019968/'}],
 'datePublished': '2003-11-05',
 'description': 'The Matrix Revolutions is a movie starring Keanu Reeves, '
                'Laurence Fishburne, and Carrie-Anne Moss. The human city of '
                'Zion defends itself against the massive invasion of the '
                'machines as Neo fights to end the war at another front...',
 'director': [{'@type': 'Person',
               'name': 'Lana Wachowski',
               'url': '/name/nm0905154/'},
              {'@type': 'Person',
               'name': 'Lilly Wachowski',
               'url': '/name/nm0905152/'}],
 'duration': 'PT2H9M',
 'genre': ['Action', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzNlZTZjMDctZjYwNi00NzljLWIwN2QtZWZmYmJiYzQ0MTk2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': '2200s,good versus evil,villain,male protagonist,supernatural '
             'power',
 'name': 'The Matrix Revolutions',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'MR_Heraclius'},
            'dateCreated': '2020-02-24',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0242653/'},
            'name': 'Another big disappointing sequel to "The Matrix,"',
            'reviewBody': "Like it's predecessor, the final installment of The "
                          'Matrix trilogy is overcomplicated in plot, yet even '
                          'more excessive in CGI. The entire 2nd half of the '
                          'film is a huge barrage of special effects, and '
                          "while it's not a huge bore, the brilliant "
                          "choreography has been sacrificed in it's place; "
                          'save for the final battle between Mr. Anderson and '
                          "Mr. Smith, and it's always a pleasure watching the "
                          'two stars square off. Fun moments aside, it feels '
                          'overlong like Reloaded and is just as unnecessary.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '6',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi2885026073',
             'name': 'The Matrix Revolutions',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDc2YjgyZmYtOTJhNy00MGI2LTg3ZGMtOGE4NWE5ZDU0Mzc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDc2YjgyZmYtOTJhNy00MGI2LTg3ZGMtOGE4NWE5ZDU0Mzc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:56:51Z'},
 'url': '/title/tt0242653/'}