{'Actors': ['Anthony Wong',
            'Anthony Zerbe',
            'Bernard White',
            'Bruce Spence',
            'Carrie-Anne Moss',
            'Christopher Kirby',
            'Clayton Watson',
            'Collin Chou',
            'Cornel West',
            'Craig Walker',
            'David Roberts',
            'Essie Davis',
            'Francine Bell',
            "Genevieve O'Reilly",
            'Gina Torres',
            'Harold Perrineau',
            'Harry Lennix',
            'Helmut Bakaitis',
            'Hugo Weaving',
            'Ian Bliss',
            'Jada Pinkett Smith',
            'Kate Beahan',
            'Keanu Reeves',
            'Kevin Michael Richardson',
            'Lachy Hulme',
            'Lambert Wilson',
            'Laurence Fishburne',
            'Mary Alice',
            'Monica Bellucci',
            'Nathaniel Lees',
            'Nona Gaye',
            'Peter Lamb',
            'Rene Naufahu',
            'Robert Mammone',
            'Robyn Nevin',
            'Rupert Reid'],
 'Added': '2013-02-19',
 'Countries': ['Australia', 'USA'],
 'Description': '\n'
                'The Matrix Revolutions: The human city of Zion defends itself '
                'against the massive invasion of the machines as Neo fights to '
                'end the war at another front while also opposing the rogue '
                'Agent Smith. ',
 'Director': ['Andy Wachowski'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Matrix-Revolutions',
 'EntryURL': 'http://www.imdb.com/title/tt0242653',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Matrix-Revolutions/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Matrix-Revolutions/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Matrix-Revolutions/info.py',
 'Genres': ['Action', 'Thriller', 'Sci-Fi', 'Adventure'],
 'IMDB': 'http://www.imdb.com/title/tt0242653',
 'PrimeWire': 'http://www.primewire.ag/watch-247-The-Matrix-Revolutions',
 'Ratings': {'IMDB': '6.7/10',
             'Metascore': '47%',
             'PrimeWire': '3.97/5',
             'RT': '36%',
             'Votes': '543'},
 'Released': '2003-11-05',
 'Runtime': '129 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/247_The_Matrix_Revolutions_2003.jpg',
 'Title': 'The-Matrix-Revolutions'}