{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Minecraft',
 'EntryURL': 'https://rawg.io/games/minecraft',
 'Entry_json': 'Favorites/Games/snapshot/Minecraft/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Minecraft/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Minecraft/thumb.jpg',
 'added': 2900,
 'background_image': 'https://media.rawg.io/media/games/b4e/b4e4c73d5aa4ec66bbf75375c4847a2b.jpg',
 'developers': ['Mojang', '4J Studios', 'Markus (aka Notch) Persson'],
 'genres': ['Action', 'Simulation', 'Arcade'],
 'name': 'Minecraft',
 'platforms': ['Android',
               'iOS',
               'PS Vita',
               'Xbox 360',
               'Wii U',
               'PlayStation 4',
               'Nintendo Switch',
               'macOS',
               'PC',
               'Xbox One',
               'PlayStation 3',
               'Linux',
               'Nintendo 3DS'],
 'publishers': ['Mojang', 'Mojang AB', 'Microsoft Studios'],
 'released': '2009-05-10',
 'slug': 'minecraft'}