<?php
$infoArray = array('Actors' => array('Andre Royo&tv',
            'Dana Delany&tv',
            'Garret Dillahunt&tv',
            'Ron Perlman&tv'),
 'Added' => '2015-09-07',
 'Countries' => array(),
 'Description' => '\nHand of God: A morally-corrupt judge suffers a breakdown and believes God is compelling him onto a path of vigilante justice. ',
 'Director' => array('NA'),
 'Genres' => array('Drama&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt3973768',
 'PrimeWire' => 'http://www.primewire.ag/tv-2749476-Hand-of-God',
 'Ratings' => array('IMDB' => '8.0/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.30/5',
             'RT' => 'N/A',
             'Votes' => '152'),
 'Released' => '2014-08-28',
 'Runtime' => '60 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2749476_Hand_of_God.jpg',
 'Title' => 'Hand-of-God');
?>