<?php
$infoArray = array('Actors' => array('Andrew Prine',
            'Blair Tefkin',
            'Bonnie Bartlett',
            'Camila Ashland',
            'Charles A Tamburro',
            'Clete Roberts',
            'Curt Lowens',
            'David Hooks',
            'David Packer',
            'Denny Miller',
            'Diane Cary',
            'Eric Johnston',
            'Evan C Kim',
            'Faye Grant',
            'Frank Ashmore',
            'George Morfogen',
            'Hansford Rowe',
            'Howard K Smith',
            'Jane Badler',
            'Jason Bernard',
            'Jenny Neumann',
            'Jenny Sullivan',
            'Joanna Kerns',
            'Leonardo Cimino',
            'Marc Singer',
            'Mary Alan Hokanson',
            'Michael Alldredge',
            'Michael Bond',
            'Michael Durrell',
            'Michael Swan',
            'Michael Wright',
            'Momo Yashima',
            'Myron Healey',
            'Neva Patterson',
            'Penelope Windust',
            'Peter Nelson',
            'Rafael Campos',
            'Richard Herd',
            'Richard Lawson',
            'Robert Englund',
            'Stack Pierce',
            'Stephanie Faulkner',
            'Tom Fuccello',
            'Tom Lawrence',
            'Viveka Davis',
            'Wiley Harker',
            'William Russ'),
 'Added' => '2013-02-25',
 'Countries' => array('USA'),
 'Description' => '\nV: When aliens come to Earth to ask for our help, a few suspicious humans discover their horrific true intentions and prepare to resist. ',
 'Director' => array('Kenneth Johnson'),
 'Genres' => array('Sci-Fi'),
 'IMDB' => 'http://www.imdb.com/title/tt0085106',
 'PrimeWire' => 'http://www.primewire.ag/watch-11666-V',
 'Ratings' => array('IMDB' => '7.9/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.30/5',
             'RT' => '70%',
             'Votes' => '82'),
 'Released' => '1983-05-01',
 'Runtime' => '197 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/11666_V_1983.jpg',
 'Title' => 'V');
?>