{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/The-Laundromat',
 'EntryURL': 'https://www.imdb.com/title/tt5865326',
 'Entry_json': 'Favorites/Movies/snapshot/The-Laundromat/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Laundromat/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Laundromat/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Gary Oldman',
            'url': '/name/nm0000198/'},
           {'@type': 'Person',
            'name': 'Antonio Banderas',
            'url': '/name/nm0000104/'},
           {'@type': 'Person', 'name': 'AJ Meijer', 'url': '/name/nm2973791/'},
           {'@type': 'Person',
            'name': 'Arsenio Castellanos',
            'url': '/name/nm11046604/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 40122,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jake Bernstein',
              'url': '/name/nm7328716/'},
             {'@type': 'Person',
              'name': 'Scott Z. Burns',
              'url': '/name/nm1994243/'},
             {'@type': 'Organization', 'url': '/company/co0017525/'},
             {'@type': 'Organization', 'url': '/company/co0436880/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'},
             {'@type': 'Organization', 'url': '/company/co0478896/'}],
 'datePublished': '2019-09-27',
 'description': 'The Laundromat is a movie starring Gary Oldman, Antonio '
                'Banderas, and AJ Meijer. A widow investigates an insurance '
                'fraud, chasing leads to a pair of Panama City law partners '
                "exploiting the world's financial system.",
 'director': [{'@type': 'Person',
               'name': 'Steven Soderbergh',
               'url': '/name/nm0001752/'}],
 'duration': 'PT1H35M',
 'genre': ['Comedy', 'Crime', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjFjMGVmYjUtNGVmYy00NTAwLWJhNjAtZGFkYjgzNzI3YTY4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'mossack fonseca scandal,panama papers scandal,greed,flamboyant '
             'villain,evil banker',
 'name': 'The Laundromat',
 'trailer': [{'@type': 'VideoObject',
              'description': "'The Laundromat' follows a group of journalists "
                             'who uncover the illicit money networks at the '
                             'heart of the Panama Papers - documents that '
                             'exposed a huge international system of legal '
                             'swindling.',
              'embedUrl': '/video/imdb/vi2025307929',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYjU3OGMzMjItZTMwZi00Mzc3LTllODgtNTE5ZjU0ZjdmZGFmXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYjU3OGMzMjItZTMwZi00Mzc3LTllODgtNTE5ZjU0ZjdmZGFmXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2019-08-28T14:58:25Z'}],
 'url': '/title/tt5865326/'}