{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Inception',
 'EntryURL': 'https://www.imdb.com/title/tt1375666',
 'Entry_json': 'Favorites/Movies/snapshot/Inception/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Inception/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Inception/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Leonardo DiCaprio',
            'url': '/name/nm0000138/'},
           {'@type': 'Person',
            'name': 'Joseph Gordon-Levitt',
            'url': '/name/nm0330687/'},
           {'@type': 'Person', 'name': 'Ellen Page', 'url': '/name/nm0680983/'},
           {'@type': 'Person',
            'name': 'Ken Watanabe',
            'url': '/name/nm0913822/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1969671,
                     'ratingValue': '8.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0159111/'},
             {'@type': 'Organization', 'url': '/company/co0147954/'}],
 'datePublished': '2010-07-14',
 'description': 'Inception is a movie starring Leonardo DiCaprio, Joseph '
                'Gordon-Levitt, and Ellen Page. A thief who steals corporate '
                'secrets through the use of dream-sharing technology is given '
                'the inverse task of planting an idea into the mind of a...',
 'director': {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
 'duration': 'PT2H28M',
 'genre': ['Action', 'Adventure', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg',
 'keywords': 'dream,subconscious,ambiguous ending,surprise ending,psycho '
             'thriller',
 'name': 'Inception',
 'trailer': {'@type': 'VideoObject',
             'description': 'Inception -- Characters Trailer',
             'embedUrl': '/video/imdb/vi4219471385',
             'name': 'Inception -- Characters',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTdlZGFmMDQtM2RiYi00NzUxLThhZWQtN2M4ZmYwMzllZGYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTdlZGFmMDQtM2RiYi00NzUxLThhZWQtN2M4ZmYwMzllZGYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
             'uploadDate': '2010-07-14T10:17:51Z'},
 'url': '/title/tt1375666/'}