{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fyre',
 'EntryURL': 'https://www.imdb.com/title/tt9412098',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fyre/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fyre/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fyre/info.py',
 'Title': 'Fyre',
 'actor': [{'@type': 'Person',
            'name': 'Billy McFarland',
            'url': '/name/nm10315000/'},
           {'@type': 'Person', 'name': 'Jason Bell', 'url': '/name/nm8709112/'},
           {'@type': 'Person',
            'name': 'Gabrielle Bluestone',
            'url': '/name/nm8832763/'},
           {'@type': 'Person',
            'name': 'Shiyuan Deng',
            'url': '/name/nm10412421/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 33651,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Organization', 'url': '/company/co0732430/'},
             {'@type': 'Organization', 'url': '/company/co0715297/'},
             {'@type': 'Organization', 'url': '/company/co0725032/'}],
 'datePublished': '2019-01-18',
 'description': 'Fyre is a movie starring Billy McFarland, Jason Bell, and '
                'Gabrielle Bluestone. An exclusive behind the scenes look at '
                'the infamous unraveling of the Fyre music festival.',
 'director': {'@type': 'Person',
              'name': 'Chris Smith',
              'url': '/name/nm0807687/'},
 'duration': 'PT1H37M',
 'genre': ['Documentary', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjQ2NzE1MjYxMV5BMl5BanBnXkFtZTgwMjM3MDQxNzM@._V1_.jpg',
 'name': 'Fyre',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'pubududias'},
            'dateCreated': '2019-02-03',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt9412098/'},
            'name': 'The dark side of the social media influencing',
            'reviewBody': "You'll laugh at some of the scenes, but this whole "
                          'thing is a no joke. The collapse of this whole '
                          'event (it was inevitable since inception), shows '
                          'that the governments should take necessary steps to '
                          'prevent financial fraud caused by social media.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '8',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'An exclusive behind the scenes look at the '
                            'infamous unraveling of the Fyre music festival.',
             'embedUrl': '/video/imdb/vi2433858073',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNGI0N2FkZTMtZGE0Ni00MDYxLTliODctOWVmNDkyNDU3ODQ1XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNGI0N2FkZTMtZGE0Ni00MDYxLTliODctOWVmNDkyNDU3ODQ1XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
             'uploadDate': '2019-01-10T19:03:04Z'},
 'url': '/title/tt9412098/'}