{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Fyre',
 'EntryURL': 'https://www.imdb.com/title/tt9412098',
 'Entry_json': 'Favorites/Movies/snapshot/Fyre/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Fyre/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Fyre/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Billy McFarland',
            'url': '/name/nm10315000/'},
           {'@type': 'Person', 'name': 'Jason Bell', 'url': '/name/nm8709112/'},
           {'@type': 'Person',
            'name': 'Gabrielle Bluestone',
            'url': '/name/nm8832763/'},
           {'@type': 'Person',
            'name': 'Shiyuan Deng',
            'url': '/name/nm10412421/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 33674,
                     'ratingValue': '7.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Organization', 'url': '/company/co0732430/'},
             {'@type': 'Organization', 'url': '/company/co0715297/'},
             {'@type': 'Organization', 'url': '/company/co0725032/'}],
 'datePublished': '2019-01-18',
 'description': 'Fyre is a movie starring Billy McFarland, Jason Bell, and '
                'Gabrielle Bluestone. An exclusive behind the scenes look at '
                'the infamous unraveling of the Fyre music festival.',
 'director': {'@type': 'Person',
              'name': 'Chris Smith',
              'url': '/name/nm0807687/'},
 'duration': 'PT1H37M',
 'genre': ['Documentary', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjQ2NzE1MjYxMV5BMl5BanBnXkFtZTgwMjM3MDQxNzM@._V1_.jpg',
 'name': 'Fyre',
 'trailer': {'@type': 'VideoObject',
             'description': 'An exclusive behind the scenes look at the '
                            'infamous unraveling of the Fyre music festival.',
             'embedUrl': '/video/imdb/vi2433858073',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNGI0N2FkZTMtZGE0Ni00MDYxLTliODctOWVmNDkyNDU3ODQ1XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNGI0N2FkZTMtZGE0Ni00MDYxLTliODctOWVmNDkyNDU3ODQ1XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
             'uploadDate': '2019-01-10T19:03:04Z'},
 'url': '/title/tt9412098/'}