{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-03-29',
 'EntryPath': 'Favorites/TV/snapshot/Black-Mirror',
 'EntryURL': 'https://www.imdb.com/title/tt2085059',
 'Entry_json': 'Favorites/TV/snapshot/Black-Mirror/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Black-Mirror/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Black-Mirror/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Daniel Lapaine',
            'url': '/name/nm0487406/'},
           {'@type': 'Person',
            'name': 'Hannah John-Kamen',
            'url': '/name/nm4789912/'},
           {'@type': 'Person',
            'name': 'Michaela Coel',
            'url': '/name/nm3948190/'},
           {'@type': 'Person',
            'name': 'Beatrice Robertson-Jones',
            'url': '/name/nm7379039/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 403733,
                     'ratingValue': '8.8',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Charlie Brooker',
              'url': '/name/nm0111765/'},
             {'@type': 'Organization', 'url': '/company/co0104481/'},
             {'@type': 'Organization', 'url': '/company/co0103528/'},
             {'@type': 'Organization', 'url': '/company/co0584794/'}],
 'datePublished': '2011-12-04',
 'description': 'Black Mirror is a TV series starring Daniel Lapaine, Hannah '
                'John-Kamen, and Michaela Coel. An anthology series exploring '
                "a twisted, high-tech multiverse where humanity's greatest "
                'innovations and darkest instincts collide.',
 'genre': ['Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTM3YWVhMDMtNjczMy00NGEyLWJhZDctYjNhMTRkNDE0ZTI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'anthology,satire,dystopian future,dystopia,netflix original',
 'name': 'Black Mirror',
 'trailer': {'@type': 'VideoObject',
             'description': 'Two estranged college friends reunite in later '
                            'life, triggering a series of events that could '
                            'alter their lives forever.',
             'embedUrl': '/video/imdb/vi1456913433',
             'name': '"Striking Vipers" Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTlhZGU5ZWMtZWY4ZS00Y2VhLTg0YzUtMzEwN2Q2M2E0Yzc0XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTlhZGU5ZWMtZWY4ZS00Y2VhLTg0YzUtMzEwN2Q2M2E0Yzc0XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-05-21T15:40:58Z'},
 'url': '/title/tt2085059/'}