{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Chrono-Cross-1999',
 'EntryURL': 'https://rawg.io/games/chrono-cross-1999',
 'Entry_json': 'Favorites/Games/snapshot/Chrono-Cross-1999/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Chrono-Cross-1999/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Chrono-Cross-1999/thumb.jpg',
 'added': 146,
 'background_image': 'https://media.rawg.io/media/screenshots/68a/68a2ff5767595c9abcc1aae3ee293daa.jpg',
 'developers': ['Square', 'Square Product Development Division 3'],
 'genres': ['RPG'],
 'name': 'Chrono Cross',
 'platforms': ['PlayStation', 'PSP', 'PS Vita', 'PlayStation 3'],
 'publishers': ['Electronic Arts', 'Square'],
 'released': '1999-11-18',
 'slug': 'chrono-cross-1999'}