{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Fallout-New-Vegas',
 'EntryURL': 'https://rawg.io/games/fallout-new-vegas',
 'Entry_json': 'Favorites/Games/snapshot/Fallout-New-Vegas/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Fallout-New-Vegas/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Fallout-New-Vegas/thumb.jpg',
 'added': 4920,
 'background_image': 'https://media.rawg.io/media/games/995/9951d9d55323d08967640f7b9ab3e342.jpg',
 'developers': ['Bethesda Softworks', 'Obsidian Entertainment'],
 'genres': ['Action', 'Shooter', 'RPG'],
 'name': 'Fallout: New Vegas',
 'platforms': ['PlayStation 3', 'PC', 'Xbox 360'],
 'publishers': ['Bethesda Softworks'],
 'released': '2010-10-19',
 'slug': 'fallout-new-vegas'}