{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Talented-Mr-Ripley',
 'EntryURL': 'https://www.imdb.com/title/tt0134119',
 'Entry_json': 'Favorites/Movies/snapshot/The-Talented-Mr-Ripley/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Talented-Mr-Ripley/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Talented-Mr-Ripley/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Matt Damon', 'url': '/name/nm0000354/'},
           {'@type': 'Person',
            'name': 'Gwyneth Paltrow',
            'url': '/name/nm0000569/'},
           {'@type': 'Person', 'name': 'Jude Law', 'url': '/name/nm0000179/'},
           {'@type': 'Person',
            'name': 'Cate Blanchett',
            'url': '/name/nm0000949/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 177185,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Patricia Highsmith',
              'url': '/name/nm0383604/'},
             {'@type': 'Person',
              'name': 'Anthony Minghella',
              'url': '/name/nm0005237/'},
             {'@type': 'Organization', 'url': '/company/co0022594/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0038270/'},
             {'@type': 'Organization', 'url': '/company/co0032447/'}],
 'datePublished': '1999-12-25',
 'description': 'The Talented Mr. Ripley is a movie starring Matt Damon, '
                'Gwyneth Paltrow, and Jude Law. In late 1950s New York, Tom '
                'Ripley, a young underachiever, is sent to Italy to retrieve '
                'Dickie Greenleaf, a rich and spoiled millionaire playboy....',
 'director': [{'@type': 'Person',
               'name': 'Anthony Minghella',
               'url': '/name/nm0005237/'}],
 'duration': 'PT2H19M',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODA3NDhiZjYtYTk2NS00ZWYwLTljYTQtMjU0NzcyMGEzNTU2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'nudity,italy,sociopath,male frontal nudity,neo noir',
 'name': 'The Talented Mr. Ripley',
 'url': '/title/tt0134119/'}