{'@context': 'http://schema.org',
 '@type': 'TVEpisode',
 'EntryAdded': '2015-08-08',
 'EntryPath': 'Favorites/TV/snapshot/Sneaky-Pete',
 'EntryURL': 'https://www.imdb.com/title/tt4200136',
 'Entry_json': 'Favorites/TV/snapshot/Sneaky-Pete/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Sneaky-Pete/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Sneaky-Pete/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Giovanni Ribisi',
            'url': '/name/nm0000610/'},
           {'@type': 'Person',
            'name': 'Marin Ireland',
            'url': '/name/nm1677477/'},
           {'@type': 'Person',
            'name': 'Shane McRae',
            'url': '/name/nm0574460/'},
           {'@type': 'Person',
            'name': 'Libe Barer',
            'url': '/name/nm2842971/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 3176,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'David Shore',
              'url': '/name/nm0794914/'},
             {'@type': 'Person',
              'name': 'Bryan Cranston',
              'url': '/name/nm0186505/'},
             {'@type': 'Person',
              'name': 'David Shore',
              'url': '/name/nm0794914/'},
             {'@type': 'Person',
              'name': 'David Shore',
              'url': '/name/nm0794914/'},
             {'@type': 'Person',
              'name': 'Bryan Cranston',
              'url': '/name/nm0186505/'},
             {'@type': 'Person',
              'name': 'Ian MacDonald',
              'url': '/name/nm2349385/'},
             {'@type': 'Organization', 'url': '/company/co0146945/'},
             {'@type': 'Organization', 'url': '/company/co0441037/'},
             {'@type': 'Organization', 'url': '/company/co0471089/'},
             {'@type': 'Organization', 'url': '/company/co0319272/'},
             {'@type': 'Organization', 'url': '/company/co0086397/'}],
 'datePublished': '2015-08-07',
 'description': 'Pilot is an episode of Sneaky Pete starring Giovanni Ribisi, '
                'Marin Ireland, and Shane McRae. After leaving prison, Marius '
                'takes cover from his past by assuming the identity of his '
                "cellmate, Pete. He moves in with Pete's...",
 'director': [{'@type': 'Person',
               'name': 'Seth Gordon',
               'url': '/name/nm1164861/'}],
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNGZjZGY5ZWQtZTU5Ni00NWVlLWJkNjItZDkxN2MwNDE2ZGYzL2ltYWdlXkEyXkFqcGdeQXVyNjkwNzEwMzU@._V1_.jpg',
 'keywords': 'tv dinner,tire swing,pickpocket,road map,hitchhiking',
 'name': 'Pilot',
 'timeRequired': 'PT54M',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Official trailer for Sneaky Pete available on '
                             'Amazon Instant Video.',
              'embedUrl': '/video/imdb/vi2933961497',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTk5MTkxOTcxNV5BMl5BanBnXkFtZTgwNzM2Nzc0NjE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTk5MTkxOTcxNV5BMl5BanBnXkFtZTgwNzM2Nzc0NjE@._V1_.jpg',
              'uploadDate': '2015-08-07T05:25:56Z'}],
 'url': '/title/tt4200136/'}