{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-22',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted',
 'EntryURL': 'https://www.imdb.com/title/tt1757746',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Sasha Roiz', 'url': '/name/nm1501388/'},
           {'@type': 'Person',
            'name': 'Jenny Mollen',
            'url': '/name/nm1200748/'},
           {'@type': 'Person',
            'name': 'Dominic Bogart',
            'url': '/name/nm1665054/'},
           {'@type': 'Person',
            'name': 'Richard Riehle',
            'url': '/name/nm0726223/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 11280,
                     'ratingValue': '6.5',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Nir Paniry',
              'url': '/name/nm2040027/'},
             {'@type': 'Person',
              'name': 'Gabriel Cowan',
              'url': '/name/nm1410462/'},
             {'@type': 'Person',
              'name': 'Nir Paniry',
              'url': '/name/nm2040027/'},
             {'@type': 'Person',
              'name': 'John Suits',
              'url': '/name/nm2986811/'},
             {'@type': 'Organization', 'url': '/company/co0237280/'}],
 'datePublished': '2013-09-09',
 'description': 'Extracted is a movie starring Sasha Roiz, Jenny Mollen, and '
                'Dominic Bogart. A scientist who has invented a technology to '
                "construct virtual realities from people's memories finds "
                'himself in a perilous situation, after he reluctantly...',
 'director': {'@type': 'Person',
              'name': 'Nir Paniry',
              'url': '/name/nm2040027/'},
 'duration': 'PT1H25M',
 'genre': ['Drama', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQ3MzExNjczOF5BMl5BanBnXkFtZTcwMTE3Mjg4OQ@@._V1_.jpg',
 'keywords': 'bumming a cigarette,murder,scientist,memory,sousveillance',
 'name': 'Extracted',
 'trailer': {'@type': 'VideoObject',
             'description': "A scientist invents a technique to enter people's "
                            'memories deep within their subconscious when '
                            'their mind is at its most vulnerable state. When '
                            "he is tasked with entering a convicted criminal's "
                            'mind to see whether he committed murder, he is '
                            'faced with his most dangerous and risky memory '
                            'extraction ever.',
             'embedUrl': '/video/imdb/vi2448468249',
             'name': 'Theatrical Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjA5MDA5NTcwM15BMl5BanBnXkFtZTgwMjQyMTYyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjA5MDA5NTcwM15BMl5BanBnXkFtZTgwMjQyMTYyMzE@._V1_.jpg',
             'uploadDate': '2013-07-16T08:40:00Z'},
 'url': '/title/tt1757746/'}