{'Actors': ['David Sullivan',
            'DT Carney',
            'Frank Ashmore',
            'Jenny Mollen',
            'Nick Jameson',
            'Richard Riehle',
            'Robert Lewis Stephenson',
            'Rodney Eastman',
            'Sasha Roiz',
            'Ty Simpkins'],
 'Added': '2013-02-22',
 'Countries': ['USA'],
 'Description': '\n'
                'Extracted: A scientist who has invented a technique to watch '
                'people&#x27;s memories finds himself in a dangerous situation '
                'after he&#x27;s tasked with entering a heroin addict&#x27;s '
                'mind to see whether the man committed murder. ',
 'Director': ['Nir Paniry'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted',
 'EntryURL': 'https://www.imdb.com/title/tt1757746',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Extracted/info.py',
 'Genres': ['Drama', 'Sci-Fi'],
 'Ratings': {'IMDB': '6.5/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.13/5',
             'RT': 'N/A',
             'Votes': '457'},
 'Released': '2012-03-10',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2736149_Extracted_2012.jpg',
 'Title': 'Extracted'}