<?php
$infoArray = array('Actors' => array('David Sullivan',
            'DT Carney',
            'Frank Ashmore',
            'Jenny Mollen',
            'Nick Jameson',
            'Richard Riehle',
            'Robert Lewis Stephenson',
            'Rodney Eastman',
            'Sasha Roiz',
            'Ty Simpkins'),
 'Added' => '2013-02-22',
 'Countries' => array('USA'),
 'Description' => '\nExtracted: A scientist who has invented a technique to watch people&#x27;s memories finds himself in a dangerous situation after he&#x27;s tasked with entering a heroin addict&#x27;s mind to see whether the man committed murder. ',
 'Director' => array('Nir Paniry'),
 'Genres' => array('Drama', 'Sci-Fi'),
 'IMDB' => 'http://www.imdb.com/title/tt1757746',
 'PrimeWire' => 'http://www.primewire.ag/watch-2736149-Extracted',
 'Ratings' => array('IMDB' => '6.5/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.13/5',
             'RT' => 'N/A',
             'Votes' => '457'),
 'Released' => '2012-03-10',
 'Runtime' => 'NA',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2736149_Extracted_2012.jpg',
 'Title' => 'Extracted');
?>