{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-17',
 'EntryPath': 'Favorites/Movies/snapshot/National-Security',
 'EntryURL': 'https://www.imdb.com/title/tt2466786',
 'Entry_json': 'Favorites/Movies/snapshot/National-Security/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/National-Security/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/National-Security/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jang-Su Bae',
            'url': '/name/nm9229298/'},
           {'@type': 'Person',
            'name': 'Kim Jung-gi',
            'url': '/name/nm5390655/'},
           {'@type': 'Person',
            'name': 'Eui-sung Kim',
            'url': '/name/nm0453440/'},
           {'@type': 'Person',
            'name': 'Cheon-hee Lee',
            'url': '/name/nm1950558/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 225,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Sang-Hyup Chung',
              'url': '/name/nm5391802/'},
             {'@type': 'Person',
              'name': 'Lee Dae-il',
              'url': '/name/nm5389906/'},
             {'@type': 'Person',
              'name': 'Kim Geun-tae',
              'url': '/name/nm5842242/'},
             {'@type': 'Person',
              'name': 'Ji-yeong Jeong',
              'url': '/name/nm0161244/'},
             {'@type': 'Person',
              'name': 'Kang Min-hee',
              'url': '/name/nm5391287/'},
             {'@type': 'Organization', 'url': '/company/co0357875/'}],
 'datePublished': '2014-04-26',
 'description': 'Namyeong-dong 1985 is a movie starring Jang-Su Bae, Kim '
                'Jung-gi, and Eui-sung Kim. On September 4, 1984, democracy '
                'movement leader Kim Jong Tae (Park Won Sang) is arrested and '
                'taken to an infamous interrogation facility in...',
 'director': [{'@type': 'Person',
               'name': 'Ji-yeong Jeong',
               'url': '/name/nm0161244/'},
              {'@type': 'Person',
               'name': 'Ji-yeong Jeong',
               'url': '/name/nm0161244/'}],
 'duration': 'PT1H50M',
 'genre': ['Drama', 'History', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZmQ0MTNlNDEtOGYyYy00NzBkLWFhYzktM2VhM2M2YWY3OWNjXkEyXkFqcGdeQXVyMjI2MDQxODA@._V1_.jpg',
 'keywords': 'torture',
 'name': 'Namyeong-dong 1985',
 'url': '/title/tt2466786/'}