{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2011-10-22',
 'EntryPath': 'Favorites/Movies/snapshot/Margin-Call',
 'EntryURL': 'https://www.imdb.com/title/tt1615147',
 'Entry_json': 'Favorites/Movies/snapshot/Margin-Call/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Margin-Call/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Margin-Call/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Zachary Quinto',
            'url': '/name/nm0704270/'},
           {'@type': 'Person',
            'name': 'Stanley Tucci',
            'url': '/name/nm0001804/'},
           {'@type': 'Person',
            'name': 'Kevin Spacey',
            'url': '/name/nm0000228/'},
           {'@type': 'Person',
            'name': 'Paul Bettany',
            'url': '/name/nm0079273/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 112628,
                     'ratingValue': '7.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'J.C. Chandor',
              'url': '/name/nm1170855/'},
             {'@type': 'Organization', 'url': '/company/co0271126/'},
             {'@type': 'Organization', 'url': '/company/co0232586/'},
             {'@type': 'Organization', 'url': '/company/co0092503/'},
             {'@type': 'Organization', 'url': '/company/co0034249/'}],
 'datePublished': '2011-09-29',
 'description': 'Margin Call is a movie starring Zachary Quinto, Stanley '
                'Tucci, and Kevin Spacey. Follows the key people at an '
                'investment bank, over a 24-hour period, during the early '
                'stages of the 2008 financial crisis.',
 'director': {'@type': 'Person',
              'name': 'J.C. Chandor',
              'url': '/name/nm1170855/'},
 'duration': 'PT1H47M',
 'genre': ['Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE5NzkyNDI2Nl5BMl5BanBnXkFtZTcwMTYzNDc2Ng@@._V1_.jpg',
 'keywords': 'financial crisis,financial disaster,capital '
             'management,investment fraud,21st century',
 'name': 'Margin Call',
 'trailer': {'@type': 'VideoObject',
             'description': 'A thriller that revolves around the key people at '
                            'a investment bank over a 24-hour period during '
                            'the early stages of the financial crisis.',
             'embedUrl': '/video/imdb/vi1070504985',
             'name': 'Trailer #1',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjIzMTQ0MDE1MF5BMl5BanBnXkFtZTcwNzEyMjYxNg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjIzMTQ0MDE1MF5BMl5BanBnXkFtZTcwNzEyMjYxNg@@._V1_.jpg',
             'uploadDate': '2011-08-02T10:40:13Z'},
 'url': '/title/tt1615147/'}