{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/One-Flew-Over-the-Cuckoos-Nest',
 'EntryURL': 'https://www.imdb.com/title/tt0073486',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/One-Flew-Over-the-Cuckoos-Nest/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/One-Flew-Over-the-Cuckoos-Nest/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/One-Flew-Over-the-Cuckoos-Nest/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/One-Flew-Over-the-Cuckoos-Nest/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jack Nicholson',
            'url': '/name/nm0000197/'},
           {'@type': 'Person',
            'name': 'Louise Fletcher',
            'url': '/name/nm0001221/'},
           {'@type': 'Person',
            'name': 'Will Sampson',
            'url': '/name/nm0760225/'},
           {'@type': 'Person',
            'name': 'Michael Berryman',
            'url': '/name/nm0077720/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 881141,
                     'ratingValue': '8.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Lawrence Hauben',
              'url': '/name/nm0369142/'},
             {'@type': 'Person',
              'name': 'Bo Goldman',
              'url': '/name/nm0325743/'},
             {'@type': 'Person',
              'name': 'Ken Kesey',
              'url': '/name/nm0450181/'},
             {'@type': 'Person',
              'name': 'Dale Wasserman',
              'url': '/name/nm0913670/'},
             {'@type': 'Organization', 'url': '/company/co0066949/'}],
 'datePublished': '1975-11-19',
 'description': "One Flew Over the Cuckoo's Nest is a movie starring Jack "
                'Nicholson, Louise Fletcher, and Will Sampson. A criminal '
                'pleads insanity and is admitted to a mental institution, '
                'where he rebels against the oppressive nurse and rallies '
                'up...',
 'director': {'@type': 'Person',
              'name': 'Milos Forman',
              'url': '/name/nm0001232/'},
 'duration': 'PT2H13M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'mental institution,mental illness,nurse,escape,tragicomedy',
 'name': "One Flew Over the Cuckoo's Nest",
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'perica-43151'},
            'dateCreated': '2018-07-20',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0073486/'},
            'name': 'A masterpiece',
            'reviewBody': 'The seventies produced some of the most interesting '
                          'and worthy Hollywood movies. Before the era of '
                          'blockbusters, and ever increasing dumbing down of '
                          'the cinema art by the Hollywood power-brokers and '
                          'greedy moneymakers, there was this short but truly '
                          'amazing window of time that produced many of the '
                          'timeless gems. A great portrayal of oppression, '
                          'this gem should not be overlooked by anyone. Truly '
                          'recommended.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '10',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'A criminal pleads insanity after getting into '
                            'trouble again and once in the mental institution '
                            'rebels against the oppressive nurse and rallies '
                            'up the scared patients.',
             'embedUrl': '/video/imdb/vi3943282969',
             'name': 'Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BM2NhZWYwOWEtNmRjMC00YTVjLWIxZjYtNWY2OGIwZTM5OTdlXkEyXkFqcGdeQXVyMjM4OTI2MTU@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BM2NhZWYwOWEtNmRjMC00YTVjLWIxZjYtNWY2OGIwZTM5OTdlXkEyXkFqcGdeQXVyMjM4OTI2MTU@._V1_.jpg',
             'uploadDate': '2017-09-08T01:58:01Z'},
 'url': '/title/tt0073486/'}