{'Actors': ['Anjelica Huston',
            'Audrey Landers',
            'Brad Dourif',
            'Christopher Lloyd',
            'Danny DeVito',
            'Delos V Smith Jr',
            'Dwight Marfield',
            'Jack Nicholson',
            'Josip Elic',
            'Louisa Moritz',
            'Louise Fletcher',
            'Mews Small',
            'Michael Berryman',
            'Mwako Cumbuka',
            'Nathan George',
            'Peter Brocco',
            'Philip Roth',
            'Scatman Crothers',
            'Sydney Lassick',
            'Ted Markland',
            'Vincent Schiavelli',
            'Will Sampson',
            'William Duell',
            'William Redfield'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\n'
                "One Flew Over the Cuckoo's Nest: Upon arrival at a mental "
                'institution, a brash rebel rallies the patients together to '
                'take on the oppressive Nurse Ratched, a woman more a dictator '
                'than a nurse. ',
 'Director': ['Milos Forman'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//One-Flew-Over-the-Cuckoos-Nest',
 'EntryURL': 'http://www.imdb.com/title/tt0073486',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//One-Flew-Over-the-Cuckoos-Nest/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//One-Flew-Over-the-Cuckoos-Nest/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//One-Flew-Over-the-Cuckoos-Nest/info.py',
 'Genres': ['Drama'],
 'IMDB': 'http://www.imdb.com/title/tt0073486',
 'PrimeWire': 'http://www.primewire.ag/watch-819-One-Flew-Over-the-Cuckoos-Nest',
 'Ratings': {'IMDB': '8.7/10',
             'Metascore': '79%',
             'PrimeWire': '4.21/5',
             'RT': '96%',
             'Votes': '469'},
 'Released': '1975-11-21',
 'Runtime': '133 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/819_One_Flew_Over_the_Cuckoos_Nest_1976.jpg',
 'Title': 'One-Flew-Over-the-Cuckoos-Nest'}