{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Diablo-2',
 'EntryURL': 'https://rawg.io/games/diablo-2',
 'Entry_json': 'Favorites/Games/snapshot/Diablo-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Diablo-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Diablo-2/thumb.jpg',
 'added': 965,
 'background_image': 'https://media.rawg.io/media/games/135/13553828105bbb700a04e7517f12e34e.jpg',
 'developers': ['Blizzard Entertainment, Inc.', 'Blizzard North'],
 'genres': ['Action', 'RPG'],
 'name': 'Diablo 2',
 'platforms': ['macOS', 'PC'],
 'publishers': ['Blizzard Entertainment'],
 'released': '2000-06-29',
 'slug': 'diablo-2'}