{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Slaughterhouse-Five',
 'EntryURL': 'https://www.imdb.com/title/tt0069280',
 'Entry_json': 'Favorites/Movies/snapshot/Slaughterhouse-Five/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Slaughterhouse-Five/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Slaughterhouse-Five/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Michael Sacks',
            'url': '/name/nm0755310/'},
           {'@type': 'Person',
            'name': 'Ron Leibman',
            'url': '/name/nm0500038/'},
           {'@type': 'Person',
            'name': 'Eugene Roche',
            'url': '/name/nm0733929/'},
           {'@type': 'Person',
            'name': 'Sharon Gans',
            'url': '/name/nm0304535/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 11890,
                      'ratingValue': '6.9',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Kurt Vonnegut Jr.',
              'url': '/name/nm0903361/'},
             {'@type': 'Person',
              'name': 'Stephen Geller',
              'url': '/name/nm0312409/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0061989/'}],
 'datePublished': '1972-03-15',
 'description': 'Slaughterhouse-Five is a movie starring Michael Sacks, Ron '
                'Leibman, and Eugene Roche. A man named Billy Pilgrim tells '
                'the story of how he became unstuck in time and was abducted '
                'by aliens.',
 'director': [{'@type': 'Person',
               'name': 'George Roy Hill',
               'url': '/name/nm0001351/'}],
 'duration': 'PT1H44M',
 'genre': ['Comedy', 'Drama', 'Sci-Fi', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjE5MzE4ODAyMV5BMl5BanBnXkFtZTgwMTU3NTk4MDE@._V1_.jpg',
 'keywords': 'prisoner of war camp,alien abduction,nonlinear timeline,time '
             'travel,world war two',
 'name': 'Slaughterhouse-Five',
 'url': '/title/tt0069280/'}