{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-07-05',
 'EntryPath': 'Favorites/Movies/snapshot/Pirates-of-Silicon-Valley',
 'EntryURL': 'https://www.imdb.com/title/tt0168122',
 'Entry_json': 'Favorites/Movies/snapshot/Pirates-of-Silicon-Valley/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Pirates-of-Silicon-Valley/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Pirates-of-Silicon-Valley/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Anthony Michael Hall',
            'url': '/name/nm0001309/'},
           {'@type': 'Person', 'name': 'Noah Wyle', 'url': '/name/nm0001864/'},
           {'@type': 'Person',
            'name': 'Joey Slotnick',
            'url': '/name/nm0806217/'},
           {'@type': 'Person',
            'name': 'J.G. Hertzler',
            'url': '/name/nm0381117/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 23214,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Paul Freiberger',
              'url': '/name/nm0293753/'},
             {'@type': 'Person',
              'name': 'Michael Swaine',
              'url': '/name/nm0841517/'},
             {'@type': 'Person',
              'name': 'Martyn Burke',
              'url': '/name/nm0121789/'},
             {'@type': 'Organization', 'url': '/company/co0045494/'},
             {'@type': 'Organization', 'url': '/company/co0043795/'},
             {'@type': 'Organization', 'url': '/company/co0009512/'}],
 'datePublished': '1999-06-20',
 'description': 'Pirates of Silicon Valley is a TV movie starring Anthony '
                'Michael Hall, Noah Wyle, and Joey Slotnick. History of Apple '
                'and Microsoft.',
 'director': [{'@type': 'Person',
               'name': 'Martyn Burke',
               'url': '/name/nm0121789/'}],
 'duration': 'PT1H35M',
 'genre': ['Biography', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDc2NTE0NzE4N15BMl5BanBnXkFtZTgwMDQ5MzgwMzE@._V1_.jpg',
 'keywords': 'microsoft,apple computer,bill gates,business rivalry,software '
             'company',
 'name': 'Pirates of Silicon Valley',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from TBS',
              'embedUrl': '/video/imdb/vi1521418521',
              'name': 'Pirates of Silicon Valley',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNGViMjFjODEtNzExYy00YjkwLWEzNGUtZWYzNGM5OWU0ZWE5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNGViMjFjODEtNzExYy00YjkwLWEzNGUtZWYzNGM5OWU0ZWE5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:35:21Z'}],
 'url': '/title/tt0168122/'}