{'Actors': ['Adina Porter&tv',
            'Alison Pill&tv',
            'Charlie Weirauch&tv',
            'Dev Patel&tv',
            'Emily Mortimer&tv',
            'Jeff Daniels&tv',
            'Olivia Munn&tv',
            'Sam Waterston&tv',
            'Thomas Sadoski&tv',
            'Wynn Everett&tv'],
 'Added': '2013-06-25',
 'Countries': ['USA'],
 'Description': '\n'
                "The Newsroom (2012): A news anchor's life is stirred up when "
                "he's forced to work with a new team of colleagues. ",
 'Director': ['NA'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Newsroom-2012',
 'EntryURL': 'https://www.imdb.com/title/tt1870479',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Newsroom-2012/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Newsroom-2012/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Newsroom-2012/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Newsroom-2012/thumb.jpg',
 'Genres': ['Drama&tv'],
 'Ratings': {'IMDB': '8.7/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.46/5',
             'RT': 'N/A',
             'Votes': '875'},
 'Released': '2012-06-24',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2734005_The_Newsroom_2012.jpg',
 'Title': 'The-Newsroom-2012'}