{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Doom-Ii',
 'EntryURL': 'https://rawg.io/games/doom-ii',
 'Entry_json': 'Favorites/Games/snapshot/Doom-Ii/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Doom-Ii/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Doom-Ii/thumb.jpg',
 'added': 1582,
 'background_image': 'https://media.rawg.io/media/games/38a/38af969459ad6e5de116ec8a4a84218c.jpg',
 'developers': ['Bethesda Softworks', 'id Software'],
 'genres': ['Action', 'Shooter'],
 'name': 'DOOM II',
 'platforms': ['PC',
               'PlayStation 4',
               'Nintendo Switch',
               'iOS',
               'macOS',
               'Xbox 360',
               'Classic Macintosh',
               'Game Boy Advance'],
 'publishers': ['Bethesda Softworks',
                'id Software',
                'Valve',
                'Activision Blizzard',
                'GT Interactive Software',
                'Virgin Interactive'],
 'released': '1994-09-30',
 'slug': 'doom-ii'}