{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-03-13',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rapa-Nui',
 'EntryURL': 'https://www.imdb.com/title/tt0110944',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rapa-Nui/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rapa-Nui/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rapa-Nui/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jason Scott Lee',
            'url': '/name/nm0001462/'},
           {'@type': 'Person',
            'name': 'Esai Morales',
            'url': '/name/nm0005246/'},
           {'@type': 'Person',
            'name': 'Sandrine Holt',
            'url': '/name/nm0002142/'},
           {'@type': 'Person',
            'name': 'Eru Potaka Dewes',
            'url': '/name/nm0223103/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 4542,
                     'ratingValue': '6.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Kevin Reynolds',
              'url': '/name/nm0721817/'},
             {'@type': 'Person',
              'name': 'Tim Rose Price',
              'url': '/name/nm0741217/'},
             {'@type': 'Person',
              'name': 'Kevin Reynolds',
              'url': '/name/nm0721817/'},
             {'@type': 'Organization', 'url': '/company/co0067785/'},
             {'@type': 'Organization', 'url': '/company/co0012728/'},
             {'@type': 'Organization', 'url': '/company/co0009392/'},
             {'@type': 'Organization', 'url': '/company/co0012524/'}],
 'datePublished': '1994-03-31',
 'description': 'Rapa Nui is a movie starring Jason Scott Lee, Esai Morales, '
                'and Sandrine Holt. Love between the representatives of two '
                'warring tribes changes the balance of power on the whole '
                'remote island.',
 'director': {'@type': 'Person',
              'name': 'Kevin Reynolds',
              'url': '/name/nm0721817/'},
 'duration': 'PT1H47M',
 'genre': ['Action', 'Adventure', 'Drama', 'History', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzcyNWZhZTYtZmI4ZC00ZjgzLWIwYzEtZWNlOTQ2YmJhMzgyXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_.jpg',
 'keywords': '17th century,aboriginal western,easter island,statue,kiss',
 'name': 'Rapa Nui',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Warner Home Video',
             'embedUrl': '/video/imdb/vi1279433753',
             'name': 'Rapa Nui',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYWQ4M2E3YzMtY2Y1My00Y2MyLWFkODktMGNkOTQxZWM4YzA0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYWQ4M2E3YzMtY2Y1My00Y2MyLWFkODktMGNkOTQxZWM4YzA0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-09-21T03:28:17Z'},
 'url': '/title/tt0110944/'}