{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Yes-Man',
 'EntryURL': 'https://www.imdb.com/title/tt1068680',
 'Entry_json': 'Favorites/Movies/snapshot/Yes-Man/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Yes-Man/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Yes-Man/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jim Carrey', 'url': '/name/nm0000120/'},
           {'@type': 'Person',
            'name': 'Zooey Deschanel',
            'url': '/name/nm0221046/'},
           {'@type': 'Person',
            'name': 'Bradley Cooper',
            'url': '/name/nm0177896/'},
           {'@type': 'Person',
            'name': 'John Michael Higgins',
            'url': '/name/nm0383422/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 326461,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Nicholas Stoller',
              'url': '/name/nm0831557/'},
             {'@type': 'Person',
              'name': 'Jarrad Paul',
              'url': '/name/nm0666871/'},
             {'@type': 'Person',
              'name': 'Andrew Mogel',
              'url': '/name/nm2361949/'},
             {'@type': 'Person',
              'name': 'Danny Wallace',
              'url': '/name/nm0991245/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0108864/'},
             {'@type': 'Organization', 'url': '/company/co0159772/'},
             {'@type': 'Organization', 'url': '/company/co0093750/'}],
 'datePublished': '2008-12-17',
 'description': 'Yes Man is a movie starring Jim Carrey, Zooey Deschanel, and '
                'Bradley Cooper. A man challenges himself to say "yes" to '
                'everything.',
 'director': {'@type': 'Person',
              'name': 'Peyton Reed',
              'url': '/name/nm0715636/'},
 'duration': 'PT1H44M',
 'genre': ['Comedy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzBmZTMzYmItNzhhMC00M2FkLWIxMGEtMjIxMjAwNmQ2ZmM4XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
 'keywords': 'dvd,the beatles song,music gig,character appears on tv,harry '
             'potter costume',
 'name': 'Yes Man',
 'trailer': {'@type': 'VideoObject',
             'description': 'Yes Man - Trailer #2',
             'embedUrl': '/video/imdb/vi3042902041',
             'name': 'Yes Man',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTkxNTAzMzE5N15BMl5BanBnXkFtZTgwNzU3MzczMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTkxNTAzMzE5N15BMl5BanBnXkFtZTgwNzU3MzczMzE@._V1_.jpg',
             'uploadDate': '2008-11-12T09:28:29Z'},
 'url': '/title/tt1068680/'}