{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Happiness',
 'EntryURL': 'https://www.imdb.com/title/tt0147612',
 'Entry_json': 'Favorites/Movies/snapshot/Happiness/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Happiness/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Happiness/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jane Adams', 'url': '/name/nm0011038/'},
           {'@type': 'Person', 'name': 'Jon Lovitz', 'url': '/name/nm0001484/'},
           {'@type': 'Person',
            'name': 'Philip Seymour Hoffman',
            'url': '/name/nm0000450/'},
           {'@type': 'Person',
            'name': 'Dylan Baker',
            'url': '/name/nm0048414/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 65227,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'Unrated',
 'creator': [{'@type': 'Person',
              'name': 'Todd Solondz',
              'url': '/name/nm0001754/'},
             {'@type': 'Organization', 'url': '/company/co0007554/'},
             {'@type': 'Organization', 'url': '/company/co0030755/'}],
 'datePublished': '1998-10-16',
 'description': 'Happiness is a movie starring Jane Adams, Jon Lovitz, and '
                'Philip Seymour Hoffman. The lives of several individuals '
                'intertwine as they go about their lives in their own unique '
                'ways, engaging in acts society as a whole might find...',
 'director': [{'@type': 'Person',
               'name': 'Todd Solondz',
               'url': '/name/nm0001754/'}],
 'duration': 'PT2H14M',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2FlNzE0ZmUtMmVkZS00MWQ3LWE4OWQtYjQwZjdhNzRmNWE2XkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg',
 'keywords': 'black comedy,suburb,social satire,satire,episodic structure',
 'name': 'Happiness',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Trimark',
              'embedUrl': '/video/imdb/vi632029465',
              'name': 'Happiness',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTE4OTBlZmItYzczZC00MTllLWJmNjQtNDFlMGM2ODMxMjg5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTE4OTBlZmItYzczZC00MTllLWJmNjQtNDFlMGM2ODMxMjg5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:23:11Z'}],
 'url': '/title/tt0147612/'}