<?php
$infoArray = array('Actors' => array('Anne Bobby',
            'Arthur J Nascarella',
            'Ben Gazzara',
            'Camryn Manheim',
            'Cynthia Stevenson',
            'Dan Moran',
            'Douglas McGrath',
            'Dylan Baker',
            'Elizabeth Ashley',
            'Gerry Becker',
            'Hope Pomerance',
            'Jane Adams',
            'Jared Harris',
            'Joe Lisi',
            'Johann Carlo',
            'Jon Lovitz',
            'Jose Rabelo',
            'Lara Flynn Boyle',
            'Lisa Louise Langford',
            'Louise Lasser',
            'Marla Maples',
            'Matt Malloy',
            'Molly Shannon',
            'Philip Seymour Hoffman',
            'Socorro Santiago',
            'Wai Ching Ho'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nHappiness: Three middle-class New Jersey sisters all have their problems with their families and sex lives. ',
 'Director' => array('Todd Solondz'),
 'Genres' => array('Drama', 'Comedy'),
 'IMDB' => 'http://www.imdb.com/title/tt0147612',
 'PrimeWire' => 'http://www.primewire.ag/watch-7318-Happiness',
 'Ratings' => array('IMDB' => '7.8/10',
             'Metascore' => '81%',
             'PrimeWire' => '3.58/5',
             'RT' => '85%',
             'Votes' => '111'),
 'Released' => '1998-05-15',
 'Runtime' => '134 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/7318_Happiness_1998.jpg',
 'Title' => 'Happiness');
?>