<?php
$infoArray = array('Actors' => array('Dee Bradley Baker&tv',
            'Mike Barker&tv',
            'Rachael MacFarlane&tv',
            'Scott Grimes&tv',
            'Seth MacFarlane&tv',
            'Wendy Schaal&tv'),
 'Added' => '2015-01-30',
 'Countries' => array('USA'),
 'Description' => '\nAmerican Dad!: The random escapades of Stan Smith, an extreme right wing CIA agent dealing with family life and keeping America safe, all in the most absurdist way possible. ',
 'Director' => array(),
 'Genres' => array('Animation&tv', 'Comedy&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt0397306',
 'PrimeWire' => 'http://www.primewire.ag/tv-4326-American-Dad',
 'Ratings' => array('IMDB' => '7.6/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.20/5',
             'RT' => 'N/A',
             'Votes' => '1802'),
 'Released' => '2005-02-06',
 'Runtime' => '30 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/4326_American_Dad_2005.jpg',
 'Title' => 'American-Dad');
?>