{'Actors': ['Aubrey Plaza&tv',
            "Katie O'Grady&tv",
            'Kyle MacLachlan&tv',
            'Sam Adams&tv'],
 'Added': '2014-06-01',
 'Countries': ['USA'],
 'Description': '\n'
                'Portlandia: A sketch comedy which combines short films about '
                'people and relationships in Portland ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Portlandia',
 'EntryURL': 'http://www.imdb.com/title/tt1780441',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Portlandia/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Portlandia/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Portlandia/info.py',
 'Genres': ['Comedy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt1780441',
 'PrimeWire': 'http://www.primewire.ag/tv-2708731-Portlandia',
 'Ratings': {'IMDB': '7.8/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.23/5',
             'RT': 'N/A',
             'Votes': '243'},
 'Released': '2011-01-21',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2708730_Portlandia_2011.jpg',
 'Title': 'Portlandia'}