{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2014-06-01',
 'EntryPath': 'Favorites/TV/snapshot/Portlandia',
 'EntryURL': 'https://www.imdb.com/title/tt1780441',
 'Entry_json': 'Favorites/TV/snapshot/Portlandia/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Portlandia/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Portlandia/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Fred Armisen',
            'url': '/name/nm0035488/'},
           {'@type': 'Person',
            'name': 'Carrie Brownstein',
            'url': '/name/nm1247855/'},
           {'@type': 'Person',
            'name': 'Kyle MacLachlan',
            'url': '/name/nm0001492/'},
           {'@type': 'Person', 'name': 'Sam Adams', 'url': '/name/nm4291018/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 17675,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Fred Armisen',
              'url': '/name/nm0035488/'},
             {'@type': 'Person',
              'name': 'Carrie Brownstein',
              'url': '/name/nm1247855/'},
             {'@type': 'Person',
              'name': 'Jonathan Krisel',
              'url': '/name/nm1730037/'},
             {'@type': 'Organization', 'url': '/company/co0013731/'}],
 'datePublished': '2011-01-11',
 'description': 'Portlandia is a TV series starring Fred Armisen, Carrie '
                'Brownstein, and Kyle MacLachlan. A sketch-comedy series that '
                'parodies life in Portland, Oregon.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BOGE2ZTQ3YTEtZTU4NC00NGVlLThjNmUtMGVmYjAzNjdjZmQyL2ltYWdlXkEyXkFqcGdeQXVyMzIyMjcyODI@._V1_.jpg',
 'keywords': '2010s,generation x,hipster,man wears eyeglasses,woman wears '
             'eyeglasses',
 'name': 'Portlandia',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Watch the trailer for the fifth season of '
                             '"Portlandia".',
              'embedUrl': '/video/imdb/vi2774642457',
              'name': 'Season 5 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTY1MzU4MDIwNl5BMl5BanBnXkFtZTgwODAwMzg0MzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTY1MzU4MDIwNl5BMl5BanBnXkFtZTgwODAwMzg0MzE@._V1_.jpg',
              'uploadDate': '2014-11-22T11:12:10Z'}],
 'url': '/title/tt1780441/'}