{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-08-19',
 'EntryPath': 'Favorites/TV/snapshot/South-Park',
 'EntryURL': 'https://www.imdb.com/title/tt0121955',
 'Entry_json': 'Favorites/TV/snapshot/South-Park/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/South-Park/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/South-Park/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Trey Parker',
            'url': '/name/nm0005295/'},
           {'@type': 'Person', 'name': 'Matt Stone', 'url': '/name/nm0001778/'},
           {'@type': 'Person',
            'name': 'Isaac Hayes',
            'url': '/name/nm0005002/'},
           {'@type': 'Person',
            'name': 'Mona Marshall',
            'url': '/name/nm0551065/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 320070,
                      'ratingValue': '8.7',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Trey Parker',
              'url': '/name/nm0005295/'},
             {'@type': 'Person',
              'name': 'Matt Stone',
              'url': '/name/nm0001778/'},
             {'@type': 'Person',
              'name': 'Brian Graden',
              'url': '/name/nm0333536/'},
             {'@type': 'Organization', 'url': '/company/co0029768/'},
             {'@type': 'Organization', 'url': '/company/co0180031/'},
             {'@type': 'Organization', 'url': '/company/co0074014/'},
             {'@type': 'Organization', 'url': '/company/co0347885/'}],
 'datePublished': '1997-08-13',
 'description': 'South Park is a TV series starring Trey Parker, Matt Stone, '
                'and Isaac Hayes. Follows the misadventures of four irreverent '
                'grade-schoolers in the quiet, dysfunctional town of South '
                'Park, Colorado.',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOGE2YWUzMDItNTg2Ny00NTUzLTlmZGYtNWMyNzVjMjQ3MThkXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
 'keywords': 'elementary school,colorado,religious humor,political '
             'humor,profanity',
 'name': 'South Park',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Teaser trailer for Season 19 of South Park on '
                             'Comedy Central.',
              'embedUrl': '/video/imdb/vi3609309977',
              'name': 'Season 19 Teaser',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTg0NDQ2MjIyNF5BMl5BanBnXkFtZTgwNTg3NzY3MjI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTg0NDQ2MjIyNF5BMl5BanBnXkFtZTgwNTg3NzY3MjI@._V1_.jpg',
              'uploadDate': '2015-09-03T08:50:48Z'}],
 'url': '/title/tt0121955/'}