{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-10-18',
 'EntryPath': 'Favorites/Movies/snapshot/Parkland',
 'EntryURL': 'https://www.imdb.com/title/tt2345112',
 'Entry_json': 'Favorites/Movies/snapshot/Parkland/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Parkland/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Parkland/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Zac Efron', 'url': '/name/nm1374980/'},
           {'@type': 'Person',
            'name': 'Tom Welling',
            'url': '/name/nm0919991/'},
           {'@type': 'Person',
            'name': 'Billy Bob Thornton',
            'url': '/name/nm0000671/'},
           {'@type': 'Person',
            'name': 'Paul Giamatti',
            'url': '/name/nm0316079/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 14696,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Peter Landesman',
              'url': '/name/nm1481618/'},
             {'@type': 'Person',
              'name': 'Vincent Bugliosi',
              'url': '/name/nm0119514/'},
             {'@type': 'Organization', 'url': '/company/co0234935/'},
             {'@type': 'Organization', 'url': '/company/co0176864/'},
             {'@type': 'Organization', 'url': '/company/co0036575/'}],
 'datePublished': '2013-10-02',
 'description': 'Parkland is a movie starring Zac Efron, Tom Welling, and '
                'Billy Bob Thornton. A recounting of the chaotic events that '
                "occurred at Dallas' Parkland Hospital on the day U.S. "
                'President John F. Kennedy was assassinated.',
 'director': [{'@type': 'Person',
               'name': 'Peter Landesman',
               'url': '/name/nm1481618/'}],
 'duration': 'PT1H33M',
 'genre': ['Drama', 'History', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjE2NjkwNDE2MF5BMl5BanBnXkFtZTgwNDY5ODIxMDE@._V1_.jpg',
 'keywords': 'john f. kennedy assassination,secret '
             'service,assassination,motorcade,year 1963',
 'name': 'Parkland',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A recounting of the chaotic events that occurred '
                             "at Dallas' Parkland Hospital on the day U.S. "
                             'President John F. Kennedy was assassinated.',
              'embedUrl': '/video/imdb/vi2669390105',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzY0MjAyODQ3NF5BMl5BanBnXkFtZTgwMzg0ODAxMDE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzY0MjAyODQ3NF5BMl5BanBnXkFtZTgwMzg0ODAxMDE@._V1_.jpg',
              'uploadDate': '2013-08-24T12:58:29Z'}],
 'url': '/title/tt2345112/'}