{'Actors': ['Adam Brody&tv',
            'Alan Tudyk&tv',
            'Cree Summer&tv',
            'Danny McBride&tv',
            'Debi Mazar&tv',
            'Jake Busey&tv',
            'Josh Gad&tv',
            'Kari Wahlgren&tv',
            'Olivia Thirlby&tv',
            'Tony Hale&tv'],
 'Added': '2012-03-10',
 'Countries': ['USA'],
 'Description': '\n'
                'Good Vibes: This coming-of-age story set in a beach town is '
                'the brainchild of Pineapple Express director David Gordon '
                'Green.\n',
 'Director': [],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Good-Vibes',
 'EntryURL': 'https://www.imdb.com/title/tt1701982',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Good-Vibes/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Good-Vibes/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Good-Vibes/info.py',
 'Genres': ['Animation&tv', 'Comedy&tv'],
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.35/5',
             'RT': 'N/A',
             'Votes': '168'},
 'Released': '2011-10-27',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2729235_Good_Vibes_2011.jpg',
 'Title': 'Good-Vibes'}