{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2012-03-10',
 'EntryPath': 'Favorites/TV/snapshot/Good-Vibes',
 'EntryURL': 'https://www.imdb.com/title/tt1701982',
 'Entry_json': 'Favorites/TV/snapshot/Good-Vibes/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Good-Vibes/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Good-Vibes/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Adam Brody', 'url': '/name/nm0111013/'},
           {'@type': 'Person', 'name': 'Jake Busey', 'url': '/name/nm0000998/'},
           {'@type': 'Person', 'name': 'Josh Gad', 'url': '/name/nm1265802/'},
           {'@type': 'Person', 'name': 'Tony Hale', 'url': '/name/nm0355024/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 902,
                     'ratingValue': '7.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'David Gordon Green',
              'url': '/name/nm0337773/'},
             {'@type': 'Organization', 'url': '/company/co0066916/'},
             {'@type': 'Organization', 'url': '/company/co0227256/'},
             {'@type': 'Organization', 'url': '/company/co0054176/'},
             {'@type': 'Organization', 'url': '/company/co0120568/'}],
 'datePublished': '2011-10-27',
 'description': 'Good Vibes is a TV series starring Adam Brody, Jake Busey, '
                'and Josh Gad. Transplanted Jersey boy, Mondo and his best bud '
                'Woodie are on a mission to surf the biggest waves, crash the '
                'wildest parties and chase the prettiest girls in...',
 'genre': ['Animation', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg0NzY5MjQxNV5BMl5BanBnXkFtZTcwMDUyODY5Ng@@._V1_.jpg',
 'name': 'Good Vibes',
 'url': '/title/tt1701982/'}