{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Star-Wars-Episode-IV-A-New-Hope',
 'EntryURL': 'https://www.imdb.com/title/tt0076759',
 'Entry_json': 'Favorites/Movies/snapshot/Star-Wars-Episode-IV-A-New-Hope/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Star-Wars-Episode-IV-A-New-Hope/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Star-Wars-Episode-IV-A-New-Hope/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Mark Hamill',
            'url': '/name/nm0000434/'},
           {'@type': 'Person',
            'name': 'Harrison Ford',
            'url': '/name/nm0000148/'},
           {'@type': 'Person',
            'name': 'Carrie Fisher',
            'url': '/name/nm0000402/'},
           {'@type': 'Person',
            'name': 'Alec Guinness',
            'url': '/name/nm0000027/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1200179,
                      'ratingValue': '8.6',
                      'worstRating': '1.0'}],
 'contentRating': 'PG',
 'creator': [{'@type': 'Person',
              'name': 'George Lucas',
              'url': '/name/nm0000184/'},
             {'@type': 'Organization', 'url': '/company/co0071326/'},
             {'@type': 'Organization', 'url': '/company/co0000756/'}],
 'datePublished': '1977-05-25',
 'description': 'Star Wars is a movie starring Mark Hamill, Harrison Ford, and '
                'Carrie Fisher. Luke Skywalker joins forces with a Jedi '
                'Knight, a cocky pilot, a Wookiee and two droids to save the '
                "galaxy from the Empire's world-destroying battle...",
 'director': [{'@type': 'Person',
               'name': 'George Lucas',
               'url': '/name/nm0000184/'}],
 'duration': 'PT2H1M',
 'genre': ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'rebellion,galactic war,space opera,princess,droid',
 'name': 'Star Wars',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Watch the original teaser trailer for Star Wars.',
              'embedUrl': '/video/imdb/vi1317709849',
              'name': 'Original Teaser Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTUzNDY0NjY4Nl5BMl5BanBnXkFtZTgwNjY4MTQ0NzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTUzNDY0NjY4Nl5BMl5BanBnXkFtZTgwNjY4MTQ0NzE@._V1_.jpg',
              'uploadDate': '2013-10-13T13:57:04Z'}],
 'url': '/title/tt0076759/'}