{'Actors': ['&tv'],
 'Added': '2013-03-17',
 'Countries': [],
 'Description': '\nCoal: A docuseries chronicling the dangerous profession of coal mining, featuring Mike Crowder and Tom Roberts, co-owners of Cobalt Mine in Westchester, W.Va. and their mining team. ',
 'Director': [],
 'Genres': ['Documentary&tv'],
 'IMDB': 'http://www.imdb.com/title/tt1745045',
 'PrimeWire': 'http://www.primewire.ag/tv-2719513-Coal',
 'Ratings': {'IMDB': '8.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.24/5',
             'RT': 'N/A',
             'Votes': '37'},
 'Released': '2011-03-30',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2719513_Coal_2011.jpg',
 'Title': 'Coal'}