{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-20',
 'EntryPath': 'Favorites/Movies/snapshot/Art-School-Confidential',
 'EntryURL': 'https://www.imdb.com/title/tt0364955',
 'Entry_json': 'Favorites/Movies/snapshot/Art-School-Confidential/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Art-School-Confidential/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Art-School-Confidential/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Max Minghella',
            'url': '/name/nm1540404/'},
           {'@type': 'Person',
            'name': 'Sophia Myles',
            'url': '/name/nm0617009/'},
           {'@type': 'Person',
            'name': 'John Malkovich',
            'url': '/name/nm0000518/'},
           {'@type': 'Person',
            'name': 'Jim Broadbent',
            'url': '/name/nm0000980/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 16491,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Daniel Clowes',
              'url': '/name/nm0167280/'},
             {'@type': 'Person',
              'name': 'Daniel Clowes',
              'url': '/name/nm0167280/'},
             {'@type': 'Organization', 'url': '/company/co0026841/'},
             {'@type': 'Organization', 'url': '/company/co0014453/'},
             {'@type': 'Organization', 'url': '/company/co0040322/'}],
 'datePublished': '2006-05-12',
 'description': 'Art School Confidential is a movie starring Max Minghella, '
                'Sophia Myles, and John Malkovich. Starting from childhood '
                'attempts at illustration, the protagonist pursues his true '
                'obsession to art school. But as he learns how the art...',
 'director': [{'@type': 'Person',
               'name': 'Terry Zwigoff',
               'url': '/name/nm0959062/'}],
 'duration': 'PT1H42M',
 'genre': ['Comedy', 'Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA2NzUzNzIwMV5BMl5BanBnXkFtZTcwMDgxNDgzMQ@@._V1_.jpg',
 'keywords': 'art school,nude modeling,nude model,art model,art class',
 'name': 'Art School Confidential',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Sony Pictures Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi2981560601',
              'name': 'Art School Confidential',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTlhMzU5ZGYtMTc4Ni00ZDU1LWFkMDYtNjA5ZmFiOTQyYzYwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTlhMzU5ZGYtMTc4Ni00ZDU1LWFkMDYtNjA5ZmFiOTQyYzYwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T12:08:07Z'}],
 'url': '/title/tt0364955/'}