{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Oddworld-Abes-Exoddus',
 'EntryURL': 'https://rawg.io/games/oddworld-abes-exoddus',
 'Entry_json': 'Favorites/Games/snapshot/Oddworld-Abes-Exoddus/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Oddworld-Abes-Exoddus/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Oddworld-Abes-Exoddus/thumb.jpg',
 'added': 891,
 'background_image': 'https://media.rawg.io/media/screenshots/ba5/ba5f0dd05f44cc48c918683764e3a125.jpg',
 'developers': ['Oddworld Inhabitants',
                'Sony Interactive Entertainment',
                'Digital Dialect (PC)'],
 'genres': ['Action', 'Adventure', 'Platformer'],
 'name': "Oddworld: Abe's Exoddus",
 'platforms': ['PC',
               'PlayStation 3',
               'Game Boy Color',
               'PlayStation',
               'PSP',
               'PS Vita'],
 'publishers': ['Oddworld Inhabitants', 'GT Interactive Software'],
 'released': '1998-11-17',
 'slug': 'oddworld-abes-exoddus'}