{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-15',
 'EntryPath': 'Favorites/Movies/snapshot/Into-Eternity',
 'EntryURL': 'https://www.imdb.com/title/tt1194612',
 'Entry_json': 'Favorites/Movies/snapshot/Into-Eternity/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Into-Eternity/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Into-Eternity/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Carl Reinhold Bråkenhjelm',
            'url': '/name/nm1815379/'},
           {'@type': 'Person',
            'name': 'Mikael Jensen',
            'url': '/name/nm1495134/'},
           {'@type': 'Person',
            'name': 'Berit Lundqvist',
            'url': '/name/nm3764896/'},
           {'@type': 'Person',
            'name': 'Michael Madsen',
            'url': '/name/nm1378517/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 2812,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Person',
              'name': 'Michael Madsen',
              'url': '/name/nm1378517/'},
             {'@type': 'Person',
              'name': 'Jesper Bergmann',
              'url': '/name/nm2939945/'},
             {'@type': 'Organization', 'url': '/company/co0037084/'},
             {'@type': 'Organization', 'url': '/company/co0001935/'},
             {'@type': 'Organization', 'url': '/company/co0264574/'},
             {'@type': 'Organization', 'url': '/company/co0100550/'},
             {'@type': 'Organization', 'url': '/company/co0232065/'},
             {'@type': 'Organization', 'url': '/company/co0079546/'},
             {'@type': 'Organization', 'url': '/company/co0013526/'}],
 'datePublished': '2010-01-06',
 'description': 'Into Eternity: A Film for the Future is a movie starring Carl '
                'Reinhold Bråkenhjelm, Mikael Jensen, and Berit Lundqvist. A '
                'documentary on the safety of nuclear storage.',
 'director': [{'@type': 'Person',
               'name': 'Michael Madsen',
               'url': '/name/nm1378517/'}],
 'duration': 'PT1H15M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjI4NzUxMjA2NF5BMl5BanBnXkFtZTcwNjczNjI0NA@@._V1_.jpg',
 'keywords': 'nuclear,storage,radiation,dump,underground',
 'name': 'Into Eternity: A Film for the Future',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A documentary on the safety of nuclear storage.',
              'embedUrl': '/video/imdb/vi1560713753',
              'name': 'Into Eternity',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjAwOTM2NDk0Ml5BMl5BanBnXkFtZTgwMDgzNDIzMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjAwOTM2NDk0Ml5BMl5BanBnXkFtZTgwMDgzNDIzMzE@._V1_.jpg',
              'uploadDate': '2011-02-02T14:00:42Z'}],
 'url': '/title/tt1194612/'}