{'Actors': [' James Franco ',
            ' Lizzy Caplan ',
            ' Michael Shannon ',
            ' Miley Cyrus ',
            ' Nathan Fielder ',
            ' Tracy Morgan ',
            'Anthony Mackie',
            'Jillian Bell',
            'Joseph Gordon-Levitt',
            'Seth Rogen'],
 'Added': '2016-02-22',
 'Countries': ['USA'],
 'Description': '\n'
                'The Night Before: On Christmas eve, three lifelong friends '
                'spend the night in New York City looking for the Holy Grail '
                'of Christmas parties. ',
 'Director': ['Jonathan Levine'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Night-Before',
 'EntryURL': 'https://www.imdb.com/title/tt3530002',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Night-Before/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Night-Before/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Night-Before/info.py',
 'Genres': ['Comedy'],
 'Ratings': {'IMDB': '7.2/10',
             'Metascore': '58%',
             'PrimeWire': '3.69/5',
             'RT': '67%',
             'Votes': '447'},
 'Released': '2015-11-20',
 'Runtime': '101 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2773847_The_Night_Before_2015.jpg',
 'Title': 'The-Night-Before'}