{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Diablo',
 'EntryURL': 'https://rawg.io/games/diablo',
 'Entry_json': 'Favorites/Games/snapshot/Diablo/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Diablo/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Diablo/thumb.jpg',
 'added': 453,
 'background_image': 'https://media.rawg.io/media/games/923/923a5dd13b6e79dd23ab2d09934f0e8d.jpg',
 'developers': ['Blizzard Entertainment, Inc.', 'Blizzard North'],
 'genres': ['Action', 'RPG'],
 'name': 'Diablo',
 'platforms': ['PlayStation', 'PC', 'macOS'],
 'publishers': ['Electronic Arts',
                'Ubisoft Entertainment',
                'Blizzard Entertainment'],
 'released': '1996-12-30',
 'slug': 'diablo'}