{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/28-Days-Later',
 'EntryURL': 'https://www.imdb.com/title/tt0289043',
 'Entry_json': 'Favorites/Movies/snapshot/28-Days-Later/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/28-Days-Later/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/28-Days-Later/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Cillian Murphy',
            'url': '/name/nm0614165/'},
           {'@type': 'Person',
            'name': 'Naomie Harris',
            'url': '/name/nm0365140/'},
           {'@type': 'Person',
            'name': 'Christopher Eccleston',
            'url': '/name/nm0001172/'},
           {'@type': 'Person',
            'name': 'Alex Palmer',
            'url': '/name/nm0658099/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 368305,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alex Garland',
              'url': '/name/nm0307497/'},
             {'@type': 'Organization', 'url': '/company/co0103974/'},
             {'@type': 'Organization', 'url': '/company/co0104387/'}],
 'datePublished': '2002-11-01',
 'description': '28 Days Later... is a movie starring Cillian Murphy, Naomie '
                'Harris, and Christopher Eccleston. Four weeks after a '
                'mysterious, incurable virus spreads throughout the UK, a '
                'handful of survivors try to find sanctuary.',
 'director': [{'@type': 'Person',
               'name': 'Danny Boyle',
               'url': '/name/nm0000965/'}],
 'duration': 'PT1H53M',
 'genre': ['Action', 'Drama', 'Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTFkM2ViMmQtZmI5NS00MjQ2LWEyN2EtMTI1ZmNlZDU3MTZjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'virus,military,london england,zombie apocalypse,laboratory',
 'name': '28 Days Later...',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from 20th Century Fox Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi4071817497',
              'name': '28 Days Later',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzkzYjhjMGMtZDYxNC00YTI4LWI2MzctZmY4Mjg4YmUyYjRjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzkzYjhjMGMtZDYxNC00YTI4LWI2MzctZmY4Mjg4YmUyYjRjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T03:10:08Z'}],
 'url': '/title/tt0289043/'}