{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-10-08',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Late-Show-with-Craig-Ferguson',
 'EntryURL': 'https://www.imdb.com/title/tt0437729',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Late-Show-with-Craig-Ferguson/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Late-Show-with-Craig-Ferguson/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Late-Late-Show-with-Craig-Ferguson/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Craig Ferguson',
            'url': '/name/nm0272401/'},
           {'@type': 'Person',
            'name': 'Shadoe Stevens',
            'url': '/name/nm0828770/'},
           {'@type': 'Person',
            'name': 'Josh Robert Thompson',
            'url': '/name/nm2590280/'},
           {'@type': 'Person',
            'name': 'Joseph Bolter',
            'url': '/name/nm3733525/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 10155,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': {'@type': 'Organization', 'url': '/company/co0066959/'},
 'datePublished': '2005-01-03',
 'description': 'The Late Late Show with Craig Ferguson is a TV series '
                'starring Craig Ferguson, Shadoe Stevens, and Josh Robert '
                'Thompson. Making a satire out of the entire Late Night Show '
                'concept Scotsman Craig Ferguson hosts his show with a '
                'robot...',
 'genre': ['Comedy', 'Music', 'Talk-Show'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTcyMjIwNzM0Ml5BMl5BanBnXkFtZTcwNDAxNjgwNA@@._V1_.jpg',
 'keywords': 'robot,horse costume,skeleton,awkward pause,scotsman abroad',
 'name': 'The Late Late Show with Craig Ferguson',
 'trailer': {'@type': 'VideoObject',
             'description': 'The Late Late Show With Craig Ferguson',
             'embedUrl': '/video/imdb/vi3001859353',
             'name': 'The Late Late Show With Craig Ferguson',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BN2ZhOTJmZGQtOGU4MS00YWY3LWJhNTgtY2RhYmM5Mjk3MTIxXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BN2ZhOTJmZGQtOGU4MS00YWY3LWJhNTgtY2RhYmM5Mjk3MTIxXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-04-04T22:21:24Z'},
 'url': '/title/tt0437729/'}