{'Actors': [''],
 'Added': '2011-09-24',
 'Countries': [],
 'Description': '\nBBC Natural World Empire of the Desert Ants: Natural World visits the Arizona desert, where a new honey ant queen wages an intense battle for survival as she attempts to build and defend her empire. Eliminating rivals with ruthless efficiency, sacrificing thousands in her quest for domination murder, cannibalism, genocide, she will do anything to keep her crown. The epic story of one honey ant queen\x92s dramatic rise to power and her brutal fall from grace. ',
 'Director': [],
 'Genres': ['Documentary'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2726093-BBC-Natural-World-Empire-of-the-Desert-Ants',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '4.37/5',
             'RT': 'N/A',
             'Votes': '119'},
 'Released': '2011-08-12',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2726092_BBC_Natural_World_Empire_of_the_Desert_Ants.jpg',
 'Title': 'BBC-Natural-World-Empire-of-the-Desert-Ants'}