<?php
$infoArray = array('Actors' => array('Alex Palmer',
            'Brendan Gleeson',
            'Christopher Dunne',
            'Christopher Eccleston',
            'Cillian Murphy',
            'David Schneider',
            'Leo Bill',
            'Luke Mably',
            'Naomie Harris',
            'Noah Huntley',
            'Paul Kasey',
            'Ray Panthaki',
            'Ricci Harnett',
            'Sebastian Knapp',
            'Stuart McQuarrie',
            'Terry John'),
 'Added' => '2013-02-19',
 'Countries' => array('UK'),
 'Description' => '\n28 Days Later...: Four weeks after a mysterious, incurable virus spreads throughout the UK, a handful of survivors try to find sanctuary. ',
 'Director' => array('Danny Boyle'),
 'Genres' => array('Thriller', 'Sci-Fi', 'Horror', 'Zombies'),
 'IMDB' => 'http://www.imdb.com/title/tt0289043',
 'PrimeWire' => 'http://www.primewire.ag/watch-1349-28-Days-Later',
 'Ratings' => array('IMDB' => '7.6/10',
             'Metascore' => '73%',
             'PrimeWire' => '4.09/5',
             'RT' => '87%',
             'Votes' => '1221'),
 'Released' => '2003-06-27',
 'Runtime' => '113 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1349_28_Days_Later_2003.jpg',
 'Title' => '28-Days-Later');
?>