{'Actors': [],
 'Added': '2013-06-29',
 'Countries': ['USA'],
 'Description': '\n'
                'Vice: News series featuring startling, groundbreaking stories '
                'from around the world. ',
 'Director': ['NA'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice',
 'EntryURL': 'https://www.imdb.com/title/tt2782710',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Vice/info.py',
 'Genres': ['Documentary&tv'],
 'Ratings': {'IMDB': '8.8/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.20/5',
             'RT': 'N/A',
             'Votes': '693'},
 'Released': '2013-04-05',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2739173_Vice_2013.jpg',
 'Title': 'Vice'}