{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-06-29',
 'EntryPath': 'Favorites/TV/snapshot/Vice',
 'EntryURL': 'https://www.imdb.com/title/tt2782710',
 'Entry_json': 'Favorites/TV/snapshot/Vice/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Vice/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Vice/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Shane Smith',
            'url': '/name/nm2448288/'},
           {'@type': 'Person',
            'name': 'Gianna Toboni',
            'url': '/name/nm7359869/'},
           {'@type': 'Person',
            'name': 'Thomas Morton',
            'url': '/name/nm3832443/'},
           {'@type': 'Person',
            'name': 'Ben Anderson',
            'url': '/name/nm2423453/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 4038,
                      'ratingValue': '8.9',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Organization', 'url': '/company/co0403586/'}],
 'datePublished': '2013-04-05',
 'description': 'Vice is a TV series starring Shane Smith, Gianna Toboni, and '
                'Thomas Morton. Documentary series featuring startling, '
                'groundbreaking stories from around the world.',
 'genre': ['Documentary', 'News'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYjU4OWM0NzktMmM1NS00ZWJiLWExNGEtYWFjZDdmMmRlNTdlXkEyXkFqcGdeQXVyNzEyMTk4Mzk@._V1_.jpg',
 'name': 'Vice',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Vice: Basketball Diplomacy',
              'embedUrl': '/video/imdb/vi1933360153',
              'name': 'Vice: Basketball Diplomacy',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZDRhNjM3MGItMmM1Mi00MDUwLWJjMmEtZDljY2QyZGYyYWFjXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZDRhNjM3MGItMmM1Mi00MDUwLWJjMmEtZDljY2QyZGYyYWFjXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
              'uploadDate': '2019-06-15T13:06:00Z'}],
 'url': '/title/tt2782710/'}