{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Hollywood',
 'EntryURL': 'https://www.imdb.com/title/tt9827854',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Hollywood/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Hollywood/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Hollywood/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Hollywood/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'David Corenswet',
            'url': '/name/nm4825178/'},
           {'@type': 'Person',
            'name': 'Darren Criss',
            'url': '/name/nm2023050/'},
           {'@type': 'Person',
            'name': 'Laura Harrier',
            'url': '/name/nm5637553/'},
           {'@type': 'Person',
            'name': 'Joe Mantello',
            'url': '/name/nm0544079/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 19526,
                     'ratingValue': '7.6',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Ian Brennan',
              'url': '/name/nm0107302/'},
             {'@type': 'Person',
              'name': 'Ryan Murphy',
              'url': '/name/nm0614682/'},
             {'@type': 'Organization', 'url': '/company/co0156994/'}],
 'datePublished': '2020-05-01',
 'description': 'Hollywood is a TV mini-series starring David Corenswet, '
                'Darren Criss, and Laura Harrier. A group of aspiring actors '
                'and filmmakers in post-World War II Hollywood try to make it '
                'big - no matter the cost.',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BODc5ZDZmNTEtZDJjZC00ZmMzLWJlZWQtOWNiODI5YjE0YzBmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'hollywood,1940s,post world war two,actor,filmmaking',
 'name': 'Hollywood',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'rhianin'},
            'dateCreated': '2020-05-24',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt9827854/'},
            'name': 'Ryan Murphy hits again',
            'reviewBody': 'Just binged Hollywood on Netflix. That was amazing! '
                          'A revisionist fantasy of acceptance, inclusion, '
                          'representation, and pride. It was salacious and '
                          'distasteful, but also funny and hopeful. '
                          "Ultimately, it's about the power of movies that can "
                          'maybe change the world.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'In post-World War II Hollywood, an ambitious '
                            'group of aspiring actors and filmmakers will do '
                            'almost anything to make their showbiz dreams come '
                            'true.',
             'embedUrl': '/video/imdb/vi1727970841',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTI2ZGYwODQtNzkzYi00MGExLTk5ZDEtYmY2NWQ2ZGFlZjlhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTI2ZGYwODQtNzkzYi00MGExLTk5ZDEtYmY2NWQ2ZGFlZjlhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2020-04-20T15:16:27Z'},
 'url': '/title/tt9827854/'}