{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/The-Lost-Vikings',
 'EntryURL': 'https://rawg.io/games/the-lost-vikings',
 'Entry_json': 'Favorites/Games/snapshot/The-Lost-Vikings/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/The-Lost-Vikings/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/The-Lost-Vikings/thumb.jpg',
 'added': 138,
 'background_image': 'https://media.rawg.io/media/screenshots/be7/be7d798ec269ef8cca2e7fea0ef0481d.jpg',
 'developers': ['Blizzard Entertainment, Inc.', 'Silicon & Synapse'],
 'genres': ['Strategy', 'Puzzle', 'Platformer'],
 'name': 'The Lost Vikings',
 'platforms': ['Commodore / Amiga',
               'SNES',
               'Game Boy Advance',
               'PC',
               'Genesis'],
 'publishers': ['Blizzard Entertainment',
                'Interplay Productions',
                'Interplay Entertainment'],
 'released': '1993-04-23',
 'slug': 'the-lost-vikings'}