<?php
$infoArray = array('Actors' => array('Alan D Purwin',
            'Calvi Pabon',
            'Catherine Sutherland',
            'Colton James',
            'Dean Norris',
            'Dylan Baker',
            'Gareth Williams',
            'Gerry Becker',
            'Jack Conley',
            'Jake Thomas',
            'Jake Weber',
            'James Gammon',
            'Jennifer Day',
            'Jennifer Lopez',
            'John Cothran Jr',
            'Kamar De Los Reyes',
            'Lauri Johnson',
            'Leanna Creel',
            'Marianne Jean-Baptiste',
            'Monica Creel',
            'Musetta Vander',
            'Nicholas Cascone',
            'Patrick Bauchau',
            'Peter Sarsgaard',
            'Pruitt Taylor Vince',
            'Tara Subkoff',
            'Vanessa Branch',
            'Vince Vaughn',
            "Vincent D'Onofrio"),
 'Added' => '2013-03-24',
 'Countries' => array('USA', 'Germany'),
 'Description' => '\nThe Cell: A psychotherapist journeys inside a comatose serial killer in the hopes of saving his latest victim. ',
 'Director' => array('Tarsem Singh'),
 'Genres' => array('Crime', 'Drama', 'Fantasy', 'Horror', 'Sci-Fi', 'Thriller'),
 'IMDB' => 'http://www.imdb.com/title/tt0209958',
 'PrimeWire' => 'http://www.primewire.ag/watch-2158-The-Cell',
 'Ratings' => array('IMDB' => '6.3/10',
             'Metascore' => '40%',
             'PrimeWire' => '3.80/5',
             'RT' => '45%',
             'Votes' => '342'),
 'Released' => '2000-08-17',
 'Runtime' => '107 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2158_The_Cell_2000_31.jpg',
 'Title' => 'The-Cell');
?>