{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Myst-Masterpiece-Edition',
 'EntryURL': 'https://rawg.io/games/myst-masterpiece-edition',
 'Entry_json': 'Favorites/Games/snapshot/Myst-Masterpiece-Edition/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Myst-Masterpiece-Edition/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Myst-Masterpiece-Edition/thumb.jpg',
 'added': 165,
 'background_image': 'https://media.rawg.io/media/games/9b2/9b2a970c6f28090e857bd69244cd51e5.jpg',
 'developers': ['Cyan Worlds'],
 'genres': ['Adventure', 'Casual'],
 'name': 'Myst: Masterpiece Edition',
 'platforms': ['PC'],
 'publishers': ['Cyan Worlds'],
 'released': '2011-02-02',
 'slug': 'myst-masterpiece-edition'}