{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/The-Dark-Knight',
 'EntryURL': 'https://www.imdb.com/title/tt0468569',
 'Entry_json': 'Favorites/Movies/snapshot/The-Dark-Knight/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Dark-Knight/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Dark-Knight/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Christian Bale',
            'url': '/name/nm0000288/'},
           {'@type': 'Person',
            'name': 'Heath Ledger',
            'url': '/name/nm0005132/'},
           {'@type': 'Person',
            'name': 'Aaron Eckhart',
            'url': '/name/nm0001173/'},
           {'@type': 'Person',
            'name': 'Michael Caine',
            'url': '/name/nm0000323/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 2215079,
                      'ratingValue': '9.0',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Jonathan Nolan',
              'url': '/name/nm0634300/'},
             {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
             {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
             {'@type': 'Person',
              'name': 'David S. Goyer',
              'url': '/name/nm0333060/'},
             {'@type': 'Person', 'name': 'Bob Kane', 'url': '/name/nm0004170/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0159111/'},
             {'@type': 'Organization', 'url': '/company/co0147954/'},
             {'@type': 'Organization', 'url': '/company/co0038332/'}],
 'datePublished': '2008-07-16',
 'description': 'The Dark Knight is a movie starring Christian Bale, Heath '
                'Ledger, and Aaron Eckhart. When the menace known as the Joker '
                'wreaks havoc and chaos on the people of Gotham, Batman must '
                'accept one of the greatest psychological and...',
 'director': [{'@type': 'Person',
               'name': 'Christopher Nolan',
               'url': '/name/nm0634240/'}],
 'duration': 'PT2H32M',
 'genre': ['Action', 'Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
 'keywords': 'dc comics,joker,psychopath,clown,criminal mastermind',
 'name': 'The Dark Knight',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Blu-ray/DVD release of most recent '
                             'Batman installment',
              'embedUrl': '/video/imdb/vi324468761',
              'name': 'The Dark Knight',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWJkYWJlOWMtY2ZhZi00YWM0LTliZDktYmRiMGYwNzczMTZhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWJkYWJlOWMtY2ZhZi00YWM0LTliZDktYmRiMGYwNzczMTZhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-11-05T06:59:18Z'}],
 'url': '/title/tt0468569/'}