{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Dirt',
 'EntryURL': 'https://www.imdb.com/title/tt0800325',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Dirt/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Dirt/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Dirt/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Dirt/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Douglas Booth',
            'url': '/name/nm3150488/'},
           {'@type': 'Person', 'name': 'Iwan Rheon', 'url': '/name/nm3701064/'},
           {'@type': 'Person',
            'name': 'Machine Gun Kelly',
            'url': '/name/nm0446622/'},
           {'@type': 'Person',
            'name': 'Daniel Webber',
            'url': '/name/nm3206486/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 35686,
                     'ratingValue': '7.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Amanda Adelson',
              'url': '/name/nm5287325/'},
             {'@type': 'Person',
              'name': 'Tommy Lee',
              'url': '/name/nm0005136/'},
             {'@type': 'Person',
              'name': 'Mick Mars',
              'url': '/name/nm1016427/'},
             {'@type': 'Person',
              'name': 'Vince Neil',
              'url': '/name/nm0624702/'},
             {'@type': 'Person',
              'name': 'Nikki Sixx',
              'url': '/name/nm1015634/'},
             {'@type': 'Person',
              'name': 'Neil Strauss',
              'url': '/name/nm2196897/'},
             {'@type': 'Person',
              'name': 'Rich Wilkes',
              'url': '/name/nm0929186/'},
             {'@type': 'Organization', 'url': '/company/co0142009/'},
             {'@type': 'Organization', 'url': '/company/co0299664/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2019-03-22',
 'description': 'The Dirt is a movie starring Douglas Booth, Iwan Rheon, and '
                'Machine Gun Kelly. Based on the bestselling autobiography '
                'from Mötley Crüe, the film is an unflinching tale of success '
                'and excess as four misfits rise from the streets of...',
 'director': {'@type': 'Person',
              'name': 'Jeff Tremaine',
              'url': '/name/nm0871860/'},
 'duration': 'PT1H47M',
 'genre': ['Biography', 'Comedy', 'Drama', 'Music'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODhiMzkwYTctYzgwOC00MDM2LWExYjQtMzY4MDljZjQ3M2RmXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg',
 'keywords': 'junkie,poseur,soft rock,topless female nudity,squirting',
 'name': 'The Dirt',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'megavahinko'},
            'dateCreated': '2019-03-22',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0800325/'},
            'name': 'Great movie even if your not a fan',
            'reviewBody': 'I know some die-hard fans are gonna whine about how '
                          'not everything in the movie was accurate but hey, '
                          'neither was Bohemian Rhapsody (.. and look how well '
                          'that went!). If you want historic accuracy, read a '
                          'book. The Dirt was an ENTERTAINING two hours and '
                          "hell, I enjoyed it even though I'm not the biggest "
                          'fan of the Crüe. And would watch it again.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Based on the bestselling autobiography from '
                            'Mötley Crüe, the film is an unflinching tale of '
                            'success and excess as four misfits rise from the '
                            'streets of Hollywood to the heights of '
                            'international fame, starring Douglas Booth, Iwan '
                            'Rheon, Colson Baker, and Daniel Webber.',
             'embedUrl': '/video/imdb/vi1064221209',
             'name': "Netflix's Mötley Crüe Biopic - Official Trailer",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTIyYzI3YzctMjYxOC00ZmFkLTg5NmEtZmUxNDlmYmNjYzUzXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTIyYzI3YzctMjYxOC00ZmFkLTg5NmEtZmUxNDlmYmNjYzUzXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
             'uploadDate': '2019-02-19T15:15:51Z'},
 'url': '/title/tt0800325/'}