{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-07-25',
 'EntryPath': 'Favorites/TV/snapshot/The-Saboteurs',
 'EntryURL': 'https://www.imdb.com/title/tt3280150',
 'Entry_json': 'Favorites/TV/snapshot/The-Saboteurs/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Saboteurs/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Saboteurs/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Andreas Döhler',
            'url': '/name/nm2435705/'},
           {'@type': 'Person',
            'name': 'Robert Hunger-Bühler',
            'url': '/name/nm0402234/'},
           {'@type': 'Person',
            'name': 'Marc Ben Puch',
            'url': '/name/nm1892161/'},
           {'@type': 'Person',
            'name': 'Christoph Bach',
            'url': '/name/nm1047726/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 6067,
                      'ratingValue': '8.0',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Petter S. Rosenlund',
              'url': '/name/nm1662793/'},
             {'@type': 'Organization', 'url': '/company/co0023617/'},
             {'@type': 'Organization', 'url': '/company/co0374582/'},
             {'@type': 'Organization', 'url': '/company/co0195590/'},
             {'@type': 'Organization', 'url': '/company/co0037782/'},
             {'@type': 'Organization', 'url': '/company/co0079546/'},
             {'@type': 'Organization', 'url': '/company/co0025978/'},
             {'@type': 'Organization', 'url': '/company/co0009436/'},
             {'@type': 'Organization', 'url': '/company/co0777321/'},
             {'@type': 'Organization', 'url': '/company/co0740367/'},
             {'@type': 'Organization', 'url': '/company/co0740368/'},
             {'@type': 'Organization', 'url': '/company/co0004166/'},
             {'@type': 'Organization', 'url': '/company/co0755326/'}],
 'datePublished': '2015-01-04',
 'description': 'Kampen om tungtvannet is a TV mini-series starring Andreas '
                'Döhler, Robert Hunger-Bühler, and Marc Ben Puch. The story '
                "behind Hitler's plan of Germany getting the atomic bomb "
                'during WW2, and the heavy water sabotages in Rjukan,...',
 'genre': ['Drama', 'History', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU4NTU0NDc5OV5BMl5BanBnXkFtZTgwMjc0ODk1NTE@._V1_.jpg',
 'keywords': 'sabotage,physicist,nazi germany,resistance,world war two',
 'name': 'Kampen om tungtvannet',
 'url': '/title/tt3280150/'}