<?php
$infoArray = array('Actors' => array('Brian Haley',
            'Brian Howe',
            'Clint Eastwood',
            'Cory Hardrict',
            'Geraldine Hughes',
            'Jeffrey Feingold',
            'Jerry Lee',
            'John Carroll Lynch',
            'Scott Eastwood',
            'William Hill'),
 'Added' => '2013-08-22',
 'Countries' => array('USA', 'Germany'),
 'Description' => "\nGran Torino: Disgruntled Korean War vet Walt Kowalski sets out to reform his neighbor, a young Hmong teenager, who tried to steal Kowalski's prized possession: his 1972 Gran Torino. ",
 'Director' => array('Clint Eastwood'),
 'Genres' => array('Crime', 'Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt1205489',
 'PrimeWire' => 'http://www.primewire.ag/watch-320-Gran-Torino',
 'Ratings' => array('IMDB' => '8.2/10',
             'Metascore' => '72%',
             'PrimeWire' => '3.94/5',
             'RT' => '79%',
             'Votes' => '1169'),
 'Released' => '2009-01-09',
 'Runtime' => '116 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/320_Gran_Torino_2009.jpg',
 'Title' => 'Gran-Torino');
?>