{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-08-22',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gran-Torino',
 'EntryURL': 'https://www.imdb.com/title/tt1205489',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gran-Torino/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gran-Torino/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gran-Torino/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Clint Eastwood',
            'url': '/name/nm0000142/'},
           {'@type': 'Person', 'name': 'Bee Vang', 'url': '/name/nm3057402/'},
           {'@type': 'Person',
            'name': 'Christopher Carley',
            'url': '/name/nm1542291/'},
           {'@type': 'Person', 'name': 'Ahney Her', 'url': '/name/nm3115704/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 700631,
                     'ratingValue': '8.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Nick Schenk',
              'url': '/name/nm1010405/'},
             {'@type': 'Person',
              'name': 'Dave Johannson',
              'url': '/name/nm3164738/'},
             {'@type': 'Person',
              'name': 'Nick Schenk',
              'url': '/name/nm1010405/'},
             {'@type': 'Organization', 'url': '/company/co0255998/'},
             {'@type': 'Organization', 'url': '/company/co0112616/'},
             {'@type': 'Organization', 'url': '/company/co0062831/'},
             {'@type': 'Organization', 'url': '/company/co0010258/'},
             {'@type': 'Organization', 'url': '/company/co0108864/'},
             {'@type': 'Organization', 'url': '/company/co0257319/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'}],
 'datePublished': '2009-01-09',
 'description': 'Gran Torino is a movie starring Clint Eastwood, Bee Vang, and '
                'Christopher Carley. Disgruntled Korean War veteran Walt '
                'Kowalski sets out to reform his neighbor, Thao Lor, a Hmong '
                "teenager who tried to steal Kowalski's prized...",
 'director': {'@type': 'Person',
              'name': 'Clint Eastwood',
              'url': '/name/nm0000142/'},
 'duration': 'PT1H56M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTc5NTk2OTU1Nl5BMl5BanBnXkFtZTcwMDc3NjAwMg@@._V1_.jpg',
 'keywords': 'gang,widower,teenager,street gang,gang rape',
 'name': 'Gran Torino',
 'trailer': {'@type': 'VideoObject',
             'description': 'A music video for the song "Gran Torino" by Jamie '
                            'Cullum, from the Gran Torino motion picture '
                            'soundtrack.',
             'embedUrl': '/video/imdb/vi517604121',
             'name': 'Gran Torino music video',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2OTE5MjQyM15BMl5BanBnXkFtZTgwNTc5ODIyMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ2OTE5MjQyM15BMl5BanBnXkFtZTgwNTc5ODIyMzE@._V1_.jpg',
             'uploadDate': '2009-01-06T17:01:46Z'},
 'url': '/title/tt1205489/'}