{'Actors': ['Agam Darshi',
            'Alessandro Juliani',
            'Alexander Mandra',
            'Alison Araya',
            'Apollonia Vanova',
            'Billy Crudup',
            'Brett Stimely',
            'Carla Gugino',
            'Carrie Genzel',
            'Chris Burns',
            'Chris Gauthier',
            'Chris Weber',
            'Clay St Thomas',
            'Clint Carleton',
            'Colin Lawrence',
            'Dan Payne',
            'Danny Wattley',
            'Danny Woodburn',
            'Darren Shahlavi',
            'Darryl Scheelar',
            'Daryl Shuttleworth',
            'David MacKay',
            'Dawn Chubai',
            'Don Thompson',
            'Douglas Chapman',
            'Ed Metzger',
            'Frank Cassini',
            'Frank Novak',
            'Fulvio Cecere',
            'Gary Chalk',
            'Gary Houston',
            'Glenn Ennis',
            'Greg Travis',
            'Isabelle Champeau',
            'Jackie Earle Haley',
            'James M Connor',
            'Jason Schombing',
            'Jay Brazeau',
            'Jeffrey Dean Morgan',
            'Jerry Wasserman',
            'John B Destry',
            'John R Taylor',
            'John Shaw',
            'John Tench',
            'Keith Gordey',
            'Ken Tremblett',
            'Kevin McNulty',
            'Kurt Evans',
            'L Harvey Gold',
            'Laura Mennell',
            'Leah Gibson',
            'Louis Chirillo',
            'Malcolm Scott',
            'Malin Akerman',
            'Manoj Sood',
            'Mark Acheson',
            'Mark Docherty',
            'Mark Gash',
            'Marsha Regis',
            'Matt Frewer'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Watchmen: When an ex-superhero is murdered, a vigilante named '
                'Rorschach begins an investigation into the murder, which '
                'begins to lead to a much more terrifying conclusion. ',
 'Director': ['Zack Snyder'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Watchmen',
 'EntryURL': 'https://www.imdb.com/title/tt0409459',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Watchmen/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Watchmen/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Watchmen/info.py',
 'Genres': ['Action', 'Drama', 'Fantasy', 'Sci-Fi', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt0409459',
 'PrimeWire': 'http://www.primewire.ag/watch-267-Watchmen',
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': '56%',
             'PrimeWire': '3.99/5',
             'RT': '65%',
             'Votes': '1389'},
 'Released': '2009-03-06',
 'Runtime': '162 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/267_Watchmen_2009.jpg',
 'Title': 'Watchmen'}