{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Watchmen',
 'EntryURL': 'https://www.imdb.com/title/tt0409459',
 'Entry_json': 'Favorites/Movies/snapshot/Watchmen/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Watchmen/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Watchmen/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jackie Earle Haley',
            'url': '/name/nm0355097/'},
           {'@type': 'Person',
            'name': 'Patrick Wilson',
            'url': '/name/nm0933940/'},
           {'@type': 'Person',
            'name': 'Carla Gugino',
            'url': '/name/nm0001303/'},
           {'@type': 'Person',
            'name': 'Malin Akerman',
            'url': '/name/nm0015196/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 485628,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'David Hayter',
              'url': '/name/nm0371684/'},
             {'@type': 'Person', 'name': 'Alex Tse', 'url': '/name/nm0874844/'},
             {'@type': 'Person',
              'name': 'Dave Gibbons',
              'url': '/name/nm1733301/'},
             {'@type': 'Person',
              'name': 'Alan Moore',
              'url': '/name/nm0600872/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0159111/'},
             {'@type': 'Organization', 'url': '/company/co0041635/'},
             {'@type': 'Organization', 'url': '/company/co0038332/'}],
 'datePublished': '2009-03-04',
 'description': 'Watchmen is a movie starring Jackie Earle Haley, Patrick '
                'Wilson, and Carla Gugino. In 1985 where former superheroes '
                'exist, the murder of a colleague sends active vigilante '
                'Rorschach into his own sprawling investigation, uncovering...',
 'director': [{'@type': 'Person',
               'name': 'Zack Snyder',
               'url': '/name/nm0811583/'}],
 'duration': 'PT2H42M',
 'genre': ['Action', 'Drama', 'Mystery', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BY2IzNGNiODgtOWYzOS00OTI0LTgxZTUtOTA5OTQ5YmI3NGUzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
 'keywords': 'rape,conspiracy,doomsday clock,false promise of the american '
             'dream,nihilist',
 'name': 'Watchmen',
 'trailer': [{'@type': 'VideoObject',
              'description': 'When an ex-superhero is murdered, a vigilante '
                             'named Rorshach begins an investigation into the '
                             'murder, which begins to lead to a much more '
                             'terrifying conclusion.',
              'embedUrl': '/video/imdb/vi3326279705',
              'name': 'Watchmen: Trailer #2',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTUzODA1MDE3Ml5BMl5BanBnXkFtZTgwMzAzOTYzMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTUzODA1MDE3Ml5BMl5BanBnXkFtZTgwMzAzOTYzMzE@._V1_.jpg',
              'uploadDate': '2008-11-15T16:33:12Z'}],
 'url': '/title/tt0409459/'}