{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Sonic-Adventure',
 'EntryURL': 'https://rawg.io/games/sonic-adventure',
 'Entry_json': 'Favorites/Games/snapshot/Sonic-Adventure/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Sonic-Adventure/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Sonic-Adventure/thumb.jpg',
 'added': 422,
 'background_image': 'https://media.rawg.io/media/screenshots/a64/a64b59aec49d84b4b89001c10eb6325d.jpg',
 'developers': ['SEGA', 'Sonic Team', 'Now Production'],
 'genres': ['Action', 'Adventure', 'RPG', 'Family', 'Platformer'],
 'name': 'Sonic Adventure',
 'platforms': ['PlayStation 3', 'Dreamcast', 'Xbox 360'],
 'publishers': ['SEGA'],
 'released': '1998-12-23',
 'slug': 'sonic-adventure'}