{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iii',
 'EntryURL': 'https://rawg.io/games/grand-theft-auto-iii',
 'Entry_json': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iii/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iii/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Grand-Theft-Auto-Iii/thumb.jpg',
 'added': 3931,
 'background_image': 'https://media.rawg.io/media/games/5fa/5fae5fec3c943179e09da67a4427d68f.jpg',
 'developers': ['Rockstar North', 'DMA Design', 'Rockstar Vienna'],
 'genres': ['Action', 'Adventure'],
 'name': 'Grand Theft Auto III',
 'platforms': ['PC',
               'iOS',
               'Android',
               'macOS',
               'PlayStation 4',
               'PlayStation 2',
               'Xbox'],
 'publishers': ['1C-SoftClub',
                'Buka Entertainment',
                'Capcom',
                'Rockstar Games'],
 'released': '2001-10-22',
 'slug': 'grand-theft-auto-iii'}