<?php
$infoArray = array('Actors' => array('Brie Larson',
            'Glenne Headly',
            'Joseph Gordon-Levitt',
            'Julianne Moore',
            'Loanne Bishop',
            'Rob Brown',
            'Scarlett Johansson',
            'Tony Danza'),
 'Added' => '2013-12-17',
 'Countries' => array('USA'),
 'Description' => '\r\n              Don Jon: Jon Martello objectifies everything in his life: his apartment, his car, his family, his church, and, of course, women. His buddies even call him Don Jon because of his ability to pull "10s" every weekend without fail. Yet even the finest flings don\'t compare to the transcendent bliss he achieves alone in front of the computer watching pornography. Dissatisfied, he embarks on a journey to find a more gratifying sex life, but ends up learning larger lessons of life and love through relationships with two very different women.            ',
 'Director' => array('Joseph Gordon-Levitt'),
 'Genres' => array('Comedy'),
 'IMDB' => 'http://www.imdb.com/title/tt2229499',
 'PrimeWire' => 'http://www.primewire.ag/watch-2743296-Don-Jon',
 'Ratings' => array('IMDB' => '6.7/10',
             'Metascore' => '66%',
             'PrimeWire' => '3.64/5',
             'RT' => '81%',
             'Votes' => '1085'),
 'Released' => '2013-09-27',
 'Runtime' => '90 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2743296_Don_Jon_2013.jpg',
 'Title' => 'Don-Jon');
?>