{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Bronson',
 'EntryURL': 'https://www.imdb.com/title/tt1172570',
 'Entry_json': 'Favorites/Movies/snapshot/Bronson/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Bronson/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Bronson/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Hardy', 'url': '/name/nm0362766/'},
           {'@type': 'Person',
            'name': 'Kelly Adams',
            'url': '/name/nm1433549/'},
           {'@type': 'Person',
            'name': 'Luing Andrews',
            'url': '/name/nm1568589/'},
           {'@type': 'Person',
            'name': 'Katy Barker',
            'url': '/name/nm3032715/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 117117,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Brock Norman Brock',
              'url': '/name/nm0635431/'},
             {'@type': 'Person',
              'name': 'Nicolas Winding Refn',
              'url': '/name/nm0716347/'},
             {'@type': 'Organization', 'url': '/company/co0113509/'},
             {'@type': 'Organization', 'url': '/company/co0203328/'},
             {'@type': 'Organization', 'url': '/company/co0250100/'},
             {'@type': 'Organization', 'url': '/company/co0091923/'},
             {'@type': 'Organization', 'url': '/company/co0231406/'},
             {'@type': 'Organization', 'url': '/company/co0798920/'},
             {'@type': 'Organization', 'url': '/company/co0211009/'},
             {'@type': 'Organization', 'url': '/company/co0228888/'},
             {'@type': 'Organization', 'url': '/company/co0219021/'}],
 'datePublished': '2009-03-13',
 'description': 'Bronson is a movie starring Tom Hardy, Kelly Adams, and Luing '
                'Andrews. A young man who was sentenced to seven years in '
                'prison for robbing a post office ends up spending three '
                'decades in solitary confinement. During this time, his...',
 'director': [{'@type': 'Person',
               'name': 'Nicolas Winding Refn',
               'url': '/name/nm0716347/'}],
 'duration': 'PT1H32M',
 'genre': ['Action', 'Biography', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZGYwYzdkYmYtYTIzOC00OWU3LWFkOTAtYTFjZTY0MDE4M2VkXkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_.jpg',
 'keywords': 'male full frontal nudity,prison,sadism,art teacher,mustache',
 'name': 'Bronson',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A biopic of notorious British criminal Charles '
                             'Bronson.',
              'embedUrl': '/video/imdb/vi1194066457',
              'name': 'Bronson',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ3MzY2MjY1NV5BMl5BanBnXkFtZTgwODkyODkxMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ3MzY2MjY1NV5BMl5BanBnXkFtZTgwODkyODkxMzE@._V1_.jpg',
              'uploadDate': '2009-08-25T07:27:25Z'}],
 'url': '/title/tt1172570/'}