{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-X-2',
 'EntryURL': 'https://rawg.io/games/final-fantasy-x-2',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-X-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-X-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-X-2/thumb.jpg',
 'added': 114,
 'background_image': 'https://media.rawg.io/media/screenshots/f13/f13d40a85a2e75d8306760f831a8d835.jpg',
 'developers': ['Square'],
 'genres': ['RPG'],
 'name': 'Final Fantasy X-2',
 'platforms': ['PS Vita', 'PlayStation 3', 'PlayStation 2'],
 'publishers': ['Square Enix', 'Square'],
 'released': '2003-03-13',
 'slug': 'final-fantasy-x-2'}