{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Is-What-Winning-Looks-Like',
 'EntryURL': 'https://www.imdb.com/title/tt10466466',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Is-What-Winning-Looks-Like/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Is-What-Winning-Looks-Like/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Is-What-Winning-Looks-Like/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/This-Is-What-Winning-Looks-Like/thumb.jpg',
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 6,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0403586/'},
 'datePublished': '2013-05-27',
 'director': {'@type': 'Person',
              'name': 'Ben Anderson',
              'url': '/name/nm10756392/'},
 'duration': 'PT1H29M',
 'genre': 'Documentary',
 'name': 'This Is What Winning Looks Like',
 'url': '/title/tt10466466/'}