{'Actors': [''],
 'Added': '2015-08-08',
 'Countries': [],
 'Description': '\nThe Flying Man: A super powered vigilante defies the law using extreme violence to fight crime. ',
 'Director': [],
 'Genres': ['Action', 'Fantasy', 'Short'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/watch-2740823-The-Flying-Man',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '4.14/5',
             'RT': 'N/A',
             'Votes': '36'},
 'Released': '2013-07-31',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2740823_The_Flying_Man.jpg',
 'Title': 'The-Flying-Man'}