{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Grand-Theft-Auto-Vice-City',
 'EntryURL': 'https://rawg.io/games/grand-theft-auto-vice-city',
 'Entry_json': 'Favorites/Games/snapshot/Grand-Theft-Auto-Vice-City/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Grand-Theft-Auto-Vice-City/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Grand-Theft-Auto-Vice-City/thumb.jpg',
 'added': 5023,
 'background_image': 'https://media.rawg.io/media/games/13a/13a528ac9cf48bbb6be5d35fe029336d.jpg',
 'developers': ['Rockstar North', 'War Drum Studios', 'Rockstar Vienna'],
 'genres': ['Action', 'Adventure'],
 'name': 'Grand Theft Auto: Vice City',
 'platforms': ['Android',
               'PC',
               'iOS',
               'macOS',
               'PlayStation 2',
               'PlayStation 3',
               'PlayStation 4',
               'Xbox'],
 'publishers': ['1C-SoftClub', 'Capcom', 'Rockstar Games'],
 'released': '2002-10-27',
 'slug': 'grand-theft-auto-vice-city'}