{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Earthbound',
 'EntryURL': 'https://rawg.io/games/earthbound',
 'Entry_json': 'Favorites/Games/snapshot/Earthbound/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Earthbound/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Earthbound/thumb.jpg',
 'added': 279,
 'background_image': 'https://media.rawg.io/media/screenshots/8db/8dbfbaf477c8985e5f19c3e3ced79a65.jpg',
 'developers': ['Ape Inc.', 'HAL Laboratory', 'Nintendo'],
 'genres': ['RPG'],
 'name': 'EarthBound',
 'platforms': ['Game Boy Advance', 'Wii U', 'SNES', 'Nintendo 3DS'],
 'publishers': ['Nintendo'],
 'released': '1994-08-27',
 'slug': 'earthbound'}