{'Actors': ['Louise Barnes&tv', 'Toby Stephens&tv', 'Zach McGowan&tv'],
 'Added': '2015-01-26',
 'Countries': [],
 'Description': '\r\n'
                '              Black Sails: Captain Flint and his pirates, '
                "twenty years prior to Robert Louis Stevenson's classic "
                '"Treasure Island".            ',
 'Director': ['NA'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Black-Sails',
 'EntryURL': 'https://www.imdb.com/title/tt2375692',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Black-Sails/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Black-Sails/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Black-Sails/info.py',
 'Genres': ['Action&tv', 'Adventure&tv', 'Drama&tv'],
 'IMDB': 'http://www.imdb.com/title/tt2375692',
 'PrimeWire': 'http://www.primewire.ag/tv-2743738-Black-Sails',
 'Ratings': {'IMDB': '7.9/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.41/5',
             'RT': 'N/A',
             'Votes': '780'},
 'Released': '2014-01-25',
 'Runtime': '60 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2743738_Black_Sails_2014.jpg',
 'Title': 'Black-Sails'}