{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-01-26',
 'EntryPath': 'Favorites/TV/snapshot/Black-Sails',
 'EntryURL': 'https://www.imdb.com/title/tt2375692',
 'Entry_json': 'Favorites/TV/snapshot/Black-Sails/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Black-Sails/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Black-Sails/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jessica Parker Kennedy',
            'url': '/name/nm2498781/'},
           {'@type': 'Person',
            'name': 'Toby Stephens',
            'url': '/name/nm0827170/'},
           {'@type': 'Person', 'name': 'Hannah New', 'url': '/name/nm4026222/'},
           {'@type': 'Person',
            'name': 'Zach McGowan',
            'url': '/name/nm2090702/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 88515,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Robert Levine',
              'url': '/name/nm1766619/'},
             {'@type': 'Person',
              'name': 'Jonathan E. Steinberg',
              'url': '/name/nm2379544/'},
             {'@type': 'Organization', 'url': '/company/co0049118/'},
             {'@type': 'Organization', 'url': '/company/co0071240/'},
             {'@type': 'Organization', 'url': '/company/co0473348/'}],
 'datePublished': '2014-01-25',
 'description': 'Black Sails is a TV series starring Jessica Parker Kennedy, '
                'Toby Stephens, and Hannah New. Follows Captain Flint and his '
                "pirates twenty years prior to Robert Louis Stevenson's "
                'classic novel "Treasure Island."',
 'genre': ['Adventure', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZmExNzU1M2YtNGUzOC00MmM0LWEwYzYtZWJiYjYxNDcwY2E0XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
 'keywords': 'pirate,bare breasts,pistol,musket,treasure',
 'name': 'Black Sails',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Season 4 trailer for "Black Sails" on Starz.',
              'embedUrl': '/video/imdb/vi2786375193',
              'name': 'Season 4 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjMwMTMwNjA1OV5BMl5BanBnXkFtZTgwNDgzNTEyMTI@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjMwMTMwNjA1OV5BMl5BanBnXkFtZTgwNDgzNTEyMTI@._V1_.jpg',
              'uploadDate': '2017-01-22T14:29:07Z'}],
 'url': '/title/tt2375692/'}