{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-29',
 'EntryPath': 'Favorites/Movies/snapshot/Flight',
 'EntryURL': 'https://www.imdb.com/title/tt1907668',
 'Entry_json': 'Favorites/Movies/snapshot/Flight/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Flight/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Flight/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Denzel Washington',
            'url': '/name/nm0000243/'},
           {'@type': 'Person',
            'name': 'Nadine Velazquez',
            'url': '/name/nm1229204/'},
           {'@type': 'Person',
            'name': 'Don Cheadle',
            'url': '/name/nm0000332/'},
           {'@type': 'Person',
            'name': 'John Goodman',
            'url': '/name/nm0000422/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 316638,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'John Gatins',
              'url': '/name/nm0309691/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0038131/'},
             {'@type': 'Organization', 'url': '/company/co0108321/'},
             {'@type': 'Organization', 'url': '/company/co0251916/'},
             {'@type': 'Organization', 'url': '/company/co0139355/'}],
 'datePublished': '2012-11-02',
 'description': 'Flight is a movie starring Denzel Washington, Nadine '
                'Velazquez, and Don Cheadle. An airline pilot saves almost all '
                'his passengers on his malfunctioning airliner which '
                'eventually crashed, but an investigation into the accident...',
 'director': [{'@type': 'Person',
               'name': 'Robert Zemeckis',
               'url': '/name/nm0000709/'}],
 'duration': 'PT2H18M',
 'genre': ['Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTUxMjI1OTMxNl5BMl5BanBnXkFtZTcwNjc3NTY1OA@@._V1_.jpg',
 'keywords': 'stewardess,alcoholism,pilot,lawyer,alcoholic',
 'name': 'Flight',
 'trailer': [{'@type': 'VideoObject',
              'description': 'An airline pilot saves a flight from crashing, '
                             'but an investigation into the malfunctions '
                             'reveals something troubling.',
              'embedUrl': '/video/imdb/vi2384176153',
              'name': 'UK Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ0NjAzNTMzM15BMl5BanBnXkFtZTcwNTQ2MTA2OA@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTQ0NjAzNTMzM15BMl5BanBnXkFtZTcwNTQ2MTA2OA@@._V1_.jpg',
              'uploadDate': '2012-10-13T07:53:13Z'}],
 'url': '/title/tt1907668/'}