{'Actors': ['Adam Tomei',
            'Anthony B Harris',
            'Brian F Durkin',
            'Brian Geraghty',
            'Bruce Greenwood',
            'Denzel Washington',
            'Don Cheadle',
            'Dylan Kussman',
            'E Roger Mitchell',
            'Garcelle Beauvais',
            'Jackson Walker',
            'Jacqueline Marie Zwick',
            'Jill Jane Clements',
            'John Goodman',
            'Justin Martin',
            'Kelly Reilly',
            'Melissa Leo',
            'Michael Beasley',
            'Nadine Velazquez',
            'Peter Gerety',
            'Philip Pavel',
            'Piers Morgan',
            'Ravi Kapoor',
            'Rhoda Griffis',
            'Ric Reitz',
            'Sharon Blackwood',
            'Steve Coulter',
            'Tamara Tunie',
            'Ted Huckabee',
            'Thomas Elliott',
            'Timothy Scott',
            'Todd Maynor',
            'Tom Nowicki'],
 'Added': '2013-06-29',
 'Countries': ['USA'],
 'Description': '\n'
                'Flight: An airline pilot saves a flight from crashing, but an '
                'investigation into the malfunctions reveals something '
                'troubling. ',
 'Director': ['Robert Zemeckis'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Flight',
 'EntryURL': 'https://www.imdb.com/title/tt1907668',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Flight/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Flight/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Flight/info.py',
 'Genres': ['Drama'],
 'IMDB': 'http://www.imdb.com/title/tt1907668',
 'PrimeWire': 'http://www.primewire.ag/watch-2735979-Flight',
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': '76%',
             'PrimeWire': '3.89/5',
             'RT': '78%',
             'Votes': '3369'},
 'Released': '2012-10-14',
 'Runtime': '138 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2735979_Flight_2012.jpg',
 'Title': 'Flight'}