{'Actors': ['Noam Chomsky'],
 'Added': '2014-11-09',
 'Countries': ['France'],
 'Description': '\nIs the Man Who Is Tall Happy An Animated Conversation with Noam Chomsky: A series of interviews featuring linguist, philosopher and activist Noam Chomsky done in hand-drawn animation. ',
 'Director': ['Michel Gondry'],
 'Genres': ['Animation', 'Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1817287',
 'PrimeWire': 'http://www.primewire.ag/watch-2743020-Is-the-Man-Who-Is-Tall-Happy-An-Animated-Conversation-with-Noam-Chomsky',
 'Ratings': {'IMDB': '7.0/10',
             'Metascore': '76%',
             'PrimeWire': '3.84/5',
             'RT': '91%',
             'Votes': '19'},
 'Released': '2013-02-12',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2743020_Is_the_Man_Who_Is_Tall_Happy_An_Animated_Conversation_with_Noam_Chomsky_2013.jpg',
 'Title': 'Is-the-Man-Who-Is-Tall-Happy-An-Animated-Conversation-with-Noam-Chomsky'}