{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Ultima-9-Ascension',
 'EntryURL': 'https://rawg.io/games/ultima-9-ascension',
 'Entry_json': 'Favorites/Games/snapshot/Ultima-9-Ascension/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Ultima-9-Ascension/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Ultima-9-Ascension/thumb.jpg',
 'added': 75,
 'background_image': 'https://media.rawg.io/media/screenshots/f94/f946c70f60aa0a9f5cc290798be83b84.jpg',
 'developers': ['Origin Systems'],
 'genres': ['Action', 'RPG'],
 'name': 'Ultima IX: Ascension',
 'platforms': ['PC'],
 'publishers': ['Electronic Arts'],
 'released': '1999-11-29',
 'slug': 'ultima-9-ascension'}