{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Initial-D',
 'EntryURL': 'https://www.imdb.com/title/tt0385426',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Initial-D/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Initial-D/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Initial-D/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Greg Ayres', 'url': '/name/nm1364905/'},
           {'@type': 'Person',
            'name': 'Christopher Bevins',
            'url': '/name/nm1215197/'},
           {'@type': 'Person', 'name': 'Steve Blum', 'url': '/name/nm0089710/'},
           {'@type': 'Person',
            'name': 'Z. Charles Bolton',
            'url': '/name/nm1236503/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2208,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Shuichi Shigeno',
              'url': '/name/nm1482322/'},
             {'@type': 'Organization', 'url': '/company/co0113720/'}],
 'datePublished': '1998-04-18',
 'description': 'Initial D: First Stage is a TV series starring Greg Ayres, '
                'Christopher Bevins, and Steve Blum. The story of a young '
                'delivery boy who becomes a drift-racing legend.',
 'genre': ['Animation', 'Action', 'Comedy', 'Sport'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDQ1MTQ2OTA1M15BMl5BanBnXkFtZTcwNDIxNzcyMQ@@._V1_.jpg',
 'keywords': 'driving,car,drift racing,based on comic book,teenage boy',
 'name': 'Initial D: First Stage',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'aditbiju'},
            'dateCreated': '2019-05-05',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt0385426/'},
            'name': 'Just like the Fast and the Furious',
            'reviewBody': "It's feels just like the Fast and the Furious "
                          "movies, it's an Anime Fast and the Furious, and "
                          'Initial D compared to the Fast and the Furious, '
                          "it's fun for All Ages.",
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '10',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Initial D: Fourth Stage - Part 1',
             'embedUrl': '/video/imdb/vi1827642905',
             'name': 'Initial D: Fourth Stage',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYTMxNGY0MjQtYmYzYi00NDAzLWI1MWMtZjIwYzJiMjhkNjUwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYTMxNGY0MjQtYmYzYi00NDAzLWI1MWMtZjIwYzJiMjhkNjUwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-10-26T03:28:36Z'},
 'url': '/title/tt0385426/'}