{'Actors': [],
 'Added': '2013-11-30',
 'Countries': ['France'],
 'Description': '\nThe Battle of Chernobyl: Documentary of the nuclear disaster of Chernobyl. ',
 'Director': ['Thomas Johnson'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1832484',
 'PrimeWire': 'http://www.primewire.ag/watch-2724987-The-Battle-of-Chernobyl',
 'Ratings': {'IMDB': '8.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.58/5',
             'RT': 'N/A',
             'Votes': '53'},
 'Released': '1986-04-26',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2724987_Tschernobyl_Alles_ber_die_grsste_Atomkatastrophe_der_Welt_1986.jpg',
 'Title': 'The-Battle-of-Chernobyl'}