{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-08-22',
 'EntryPath': 'Favorites/Movies/snapshot/Krakatoa-The-Last-Days',
 'EntryURL': 'https://www.imdb.com/title/tt0791318',
 'Entry_json': 'Favorites/Movies/snapshot/Krakatoa-The-Last-Days/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Krakatoa-The-Last-Days/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Krakatoa-The-Last-Days/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Rupert Penry-Jones',
            'url': '/name/nm0672303/'},
           {'@type': 'Person',
            'name': 'Olivia Williams',
            'url': '/name/nm0931404/'},
           {'@type': 'Person',
            'name': 'Kevin McMonagle',
            'url': '/name/nm0573379/'},
           {'@type': 'Person',
            'name': 'Ramon Tikaram',
            'url': '/name/nm0863130/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 706,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Colin Heber-Percy',
              'url': '/name/nm2222463/'},
             {'@type': 'Person',
              'name': 'Michael Olmert',
              'url': '/name/nm0647431/'},
             {'@type': 'Person',
              'name': 'Lyall B. Watson',
              'url': '/name/nm2439672/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'}],
 'datePublished': '2006-05-07',
 'description': 'Krakatoa: The Last Days is a TV movie starring Rupert '
                'Penry-Jones, Olivia Williams, and Kevin McMonagle. A '
                'documentary on the 1883 eruption of Krakatoa in the Sunda '
                'Strait of Indonesia, bringing tsunamis, rains of pumice and '
                'ash,...',
 'director': {'@type': 'Person',
              'name': 'Sam Miller',
              'url': '/name/nm0589284/'},
 'duration': 'PT1H27M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTcyNzUxOTAwMl5BMl5BanBnXkFtZTcwNDYwNzMzMQ@@._V1_.jpg',
 'keywords': 'volcano,docudrama,1880s',
 'name': 'Krakatoa: The Last Days',
 'url': '/title/tt0791318/'}