{'Actors': ['Bill Flynn',
            'Farouk Valley-Omar',
            'Janine Wood',
            'Jeremy Crutchley',
            'Michael Brunner',
            'Olivia Williams',
            'Ramon Tikaram',
            'Robert Hobbs',
            'Rupert Penry-Jones',
            'Sam Miller',
            'William Miller'],
 'Added': '2014-08-22',
 'Countries': ['UK'],
 'Description': '\n'
                'Krakatoa The Last Days: In 1883, the volcanic island of '
                'Krakatoa erupted, killing 36,000 people and unleashing a '
                'series of terrifying tsunamis. This docu-drama uses eye '
                'witness accounts to tell the true story of one of the most '
                'destructive natural disasters in history. ',
 'Director': ['Sam Miller'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Krakatoa-The-Last-Days',
 'EntryURL': 'https://www.imdb.com/title/tt0791318',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Krakatoa-The-Last-Days/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Krakatoa-The-Last-Days/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Krakatoa-The-Last-Days/info.py',
 'Genres': ['Drama'],
 'IMDB': 'http://www.imdb.com/title/tt0791318',
 'PrimeWire': 'http://www.primewire.ag/watch-23269-Krakatoa-The-Last-Days',
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.61/5',
             'RT': 'N/A',
             'Votes': '82'},
 'Released': '2006-05-07',
 'Runtime': '87 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/23269_Krakatoa_The_Last_Days_2006.jpg',
 'Title': 'Krakatoa-The-Last-Days'}