{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Grand-Theft-Auto-2-1999',
 'EntryURL': 'https://rawg.io/games/grand-theft-auto-2-1999',
 'Entry_json': 'Favorites/Games/snapshot/Grand-Theft-Auto-2-1999/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Grand-Theft-Auto-2-1999/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Grand-Theft-Auto-2-1999/thumb.jpg',
 'added': 1150,
 'background_image': 'https://media.rawg.io/media/games/623/623eff489e5fcfd3d684e902d3efad8b.jpg',
 'developers': ['DMA Design', 'Tarantula Studios'],
 'genres': ['Action', 'Adventure'],
 'name': 'Grand Theft Auto 2 (1999)',
 'platforms': ['Game Boy Color',
               'PC',
               'PlayStation 3',
               'PlayStation',
               'Dreamcast'],
 'publishers': ['Buka Entertainment', 'Rockstar Games', 'Take Two Interactive'],
 'released': '1999-09-30',
 'slug': 'grand-theft-auto-2-1999'}