{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Dark-Souls-Ii-Scholar-Of-The-First-Sin',
 'EntryURL': 'https://rawg.io/games/dark-souls-ii-scholar-of-the-first-sin',
 'Entry_json': 'Favorites/Games/snapshot/Dark-Souls-Ii-Scholar-Of-The-First-Sin/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Dark-Souls-Ii-Scholar-Of-The-First-Sin/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Dark-Souls-Ii-Scholar-Of-The-First-Sin/thumb.jpg',
 'added': 2708,
 'background_image': 'https://media.rawg.io/media/games/7d9/7d9fd2b2b53a27f1af20b96b8d40c538.jpg',
 'developers': ['BANDAI NAMCO Entertainment America Inc.', 'FromSoftware'],
 'genres': ['Action', 'RPG'],
 'name': 'Dark Souls II: Scholar of the First Sin',
 'platforms': ['PC', 'Xbox One', 'PlayStation 4'],
 'publishers': ['BANDAI NAMCO Entertainment America',
                'Bandai Namco Entertainment',
                'FromSoftware, Inc',
                'BANDAI NAMCO Entertainment US'],
 'released': '2015-04-01',
 'slug': 'dark-souls-ii-scholar-of-the-first-sin'}