<?php
$infoArray = array('Actors' => array('Alex Hyde-White',
            'Alexander Bisping',
            'Alfred Dennis',
            'Amy Acker',
            'Amy Adams',
            'Ana Maria Quintana',
            'Andy Signore',
            'Anthony Powers',
            'Benita Krista Nall',
            'Beverly Lynne',
            'Brandon Keener',
            'Brian Goodman',
            'Brian Howe',
            'Brian Reed Garvin',
            'Camille Wainwright',
            'Candice Azzara',
            'Charles McClelland',
            'Charlotte Kyle',
            'Chris Ellis',
            'Christopher Metas',
            'Christopher Walken',
            'Clyde Tull',
            'Dave Hager',
            'David Austin',
            'Deborah Kellner',
            'Donna Kimball',
            'Elizabeth Banks',
            'Ellen Pompeo',
            'Evis Xheneti',
            'Fabrizio Fante',
            'Frank John Hughes',
            'G Larry Butler',
            'Gerald R Molen',
            'Guy Thauvette',
            'J Patrick McCormack',
            'Jack Knight',
            'Jaime Ray Newman',
            'James Brolin',
            'James DuMont',
            'James Morrison',
            'Jamie Anderson',
            'Jan Munroe',
            'Jane Edith Wilson',
            'Jean-Fran&#xE7;ois Blanchard',
            'Jeffrey Pritz',
            'Jennifer Garner',
            'Jeremy Howard',
            'Jesse Heiman',
            'Jessica Collins',
            'Jim Antonio',
            'Jimmie F Skaggs',
            'Joe Garagiola',
            'John Finn',
            'Johnny Drocco',
            'Jonathan Brent',
            'Joshua Boyd',
            'Kaitlin Doubleday',
            'Kam Heskin',
            'Kelly McNair',
            'Kitty Carlisle'),
 'Added' => '2013-02-24',
 'Countries' => array('USA'),
 'Description' => '\nCatch Me If You Can: A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars worth of checks as a Pan Am pilot, doctor, and legal prosecutor. ',
 'Director' => array('Steven Spielberg'),
 'Genres' => array('Drama', 'Crime', 'Biography'),
 'IMDB' => 'http://www.imdb.com/title/tt0264464',
 'PrimeWire' => 'http://www.primewire.ag/watch-1154-Catch-Me-If-You-Can',
 'Ratings' => array('IMDB' => '8.0/10',
             'Metascore' => '76%',
             'PrimeWire' => '3.96/5',
             'RT' => '96%',
             'Votes' => '1059'),
 'Released' => '2002-12-16',
 'Runtime' => '141 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/1154_Catch_Me_If_You_Can_2002.jpg',
 'Title' => 'Catch-Me-If-You-Can');
?>