{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Uncharted-Drakes-Fortune',
 'EntryURL': 'https://rawg.io/games/uncharted-drakes-fortune',
 'Entry_json': 'Favorites/Games/snapshot/Uncharted-Drakes-Fortune/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Uncharted-Drakes-Fortune/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Uncharted-Drakes-Fortune/thumb.jpg',
 'added': 2524,
 'background_image': 'https://media.rawg.io/media/games/f2e/f2e6dcf9c27d99ba2551f1094ad41756.jpg',
 'developers': ['Naughty Dog'],
 'genres': ['Action', 'Adventure'],
 'name': "UNCHARTED: Drake's Fortune",
 'platforms': ['PlayStation 3', 'PlayStation 4'],
 'publishers': ['Sony Computer Entertainment'],
 'released': '2007-11-19',
 'slug': 'uncharted-drakes-fortune'}