{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2012-02-20',
 'EntryPath': 'Favorites/TV/snapshot/Archer',
 'EntryURL': 'https://www.imdb.com/title/tt1486217',
 'Entry_json': 'Favorites/TV/snapshot/Archer/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Archer/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Archer/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'H. Jon Benjamin',
            'url': '/name/nm0071304/'},
           {'@type': 'Person', 'name': 'Judy Greer', 'url': '/name/nm0339460/'},
           {'@type': 'Person', 'name': 'Amber Nash', 'url': '/name/nm2436722/'},
           {'@type': 'Person',
            'name': 'Chris Parnell',
            'url': '/name/nm0663177/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 132926,
                      'ratingValue': '8.6',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Adam Reed',
              'url': '/name/nm0994488/'},
             {'@type': 'Organization', 'url': '/company/co0284276/'},
             {'@type': 'Organization', 'url': '/company/co0216537/'},
             {'@type': 'Organization', 'url': '/company/co0159275/'},
             {'@type': 'Organization', 'url': '/company/co0179915/'}],
 'datePublished': '2009-09-17',
 'description': 'Archer is a TV series starring H. Jon Benjamin, Judy Greer, '
                'and Amber Nash. Covert black ops and espionage take a back '
                'seat to zany personalities and relationships between secret '
                'agents and drones.',
 'genre': ['Animation', 'Action', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTg3NTMwMzY2OF5BMl5BanBnXkFtZTgwMDcxMjQ0NDE@._V1_.jpg',
 'keywords': 'spy,espionage,domineering mother,retro style secret '
             'agent,fictional spy agency',
 'name': 'Archer',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Archer is awake....and he needs a drink. The new '
                             'season of "Archer" premieres September 16, 2020.',
              'embedUrl': '/video/imdb/vi3380264473',
              'name': 'Season 11 Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYTNhMDE0OWYtNzg0YS00ODZjLTljYjktY2NlZmQ3YWIyNjBhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYTNhMDE0OWYtNzg0YS00ODZjLTljYjktY2NlZmQ3YWIyNjBhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2020-07-25T04:12:50Z'}],
 'url': '/title/tt1486217/'}