{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Paycheck',
 'EntryURL': 'https://www.imdb.com/title/tt0338337',
 'Entry_json': 'Favorites/Movies/snapshot/Paycheck/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Paycheck/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Paycheck/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ben Affleck',
            'url': '/name/nm0000255/'},
           {'@type': 'Person',
            'name': 'Aaron Eckhart',
            'url': '/name/nm0001173/'},
           {'@type': 'Person',
            'name': 'Uma Thurman',
            'url': '/name/nm0000235/'},
           {'@type': 'Person',
            'name': 'Michael C. Hall',
            'url': '/name/nm0355910/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 100760,
                     'ratingValue': '6.3',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Philip K. Dick',
              'url': '/name/nm0001140/'},
             {'@type': 'Person',
              'name': 'Dean Georgaris',
              'url': '/name/nm1212988/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0040938/'},
             {'@type': 'Organization', 'url': '/company/co0022730/'},
             {'@type': 'Organization', 'url': '/company/co0038408/'},
             {'@type': 'Organization', 'url': '/company/co0098168/'},
             {'@type': 'Organization', 'url': '/company/co0099164/'}],
 'datePublished': '2003-12-25',
 'description': 'Paycheck is a movie starring Ben Affleck, Aaron Eckhart, and '
                'Uma Thurman. What seemed like a breezy idea for an engineer '
                'to net him millions of dollars, leaves him on the run for his '
                "life and piecing together why he's being chased.",
 'director': {'@type': 'Person', 'name': 'John Woo', 'url': '/name/nm0000247/'},
 'duration': 'PT1H59M',
 'genre': ['Action', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTczMzU5NDk4MV5BMl5BanBnXkFtZTYwNDQxNzc3._V1_.jpg',
 'keywords': 'time,pipe wrench,babe scientist,seeing the future,evil '
             'corporation',
 'name': 'Paycheck',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from Paramount Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi3399155993',
             'name': 'Paycheck',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWEwOWEzZDctM2M5NC00YTcwLTg1MjYtYzMwMjc4N2E5NGJmXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWEwOWEzZDctM2M5NC00YTcwLTg1MjYtYzMwMjc4N2E5NGJmXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T15:22:36Z'},
 'url': '/title/tt0338337/'}