{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Doom-2',
 'EntryURL': 'https://rawg.io/games/doom-2',
 'Entry_json': 'Favorites/Games/snapshot/Doom-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Doom-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Doom-2/thumb.jpg',
 'added': 632,
 'background_image': 'https://media.rawg.io/media/games/47b/47b50d880be8453bf9cda6e5c007bc26.jpg',
 'developers': ['id Software', 'Nerve Software'],
 'genres': ['Action', 'Shooter'],
 'name': 'Doom',
 'platforms': ['PlayStation 3',
               'Xbox 360',
               'Nintendo Switch',
               'Xbox One',
               'PlayStation 4',
               'PC',
               'Linux',
               'PlayStation',
               'Game Boy Advance',
               'Jaguar',
               'SEGA 32X',
               '3DO',
               'SNES'],
 'publishers': ['Atari',
                'Bethesda Softworks',
                'SEGA',
                'Valve',
                'Activision Blizzard',
                'GT Interactive Software',
                'Ocean Software',
                'Williams Entertainment',
                'WMS Industries',
                'Imagineer',
                'GT Interactive',
                "'''Genesis'''",
                "'''PlayStation",
                "'''SNES (Europe)'''",
                "SNES (North America)'''",
                "'''Game Boy Advance",
                "'''SNES (Japan)'''"],
 'released': '1993-12-10',
 'slug': 'doom-2'}