{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2016-02-12',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-People-V-Oj-Simpson',
 'EntryURL': 'https://www.imdb.com/title/tt2788432',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-People-V-Oj-Simpson/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-People-V-Oj-Simpson/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-People-V-Oj-Simpson/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sarah Paulson',
            'url': '/name/nm0005299/'},
           {'@type': 'Person',
            'name': 'Annaleigh Ashford',
            'url': '/name/nm2807560/'},
           {'@type': 'Person',
            'name': 'Sterling K. Brown',
            'url': '/name/nm1250791/'},
           {'@type': 'Person',
            'name': 'Kenneth Choi',
            'url': '/name/nm0158846/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 75535,
                     'ratingValue': '8.4',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Scott Alexander',
              'url': '/name/nm0018735/'},
             {'@type': 'Person',
              'name': 'Larry Karaszewski',
              'url': '/name/nm0438989/'},
             {'@type': 'Person',
              'name': 'Tom Rob Smith',
              'url': '/name/nm1602547/'},
             {'@type': 'Organization', 'url': '/company/co0156994/'},
             {'@type': 'Organization', 'url': '/company/co0212151/'},
             {'@type': 'Organization', 'url': '/company/co0579230/'},
             {'@type': 'Organization', 'url': '/company/co0314634/'},
             {'@type': 'Organization', 'url': '/company/co0216537/'},
             {'@type': 'Organization', 'url': '/company/co0511631/'},
             {'@type': 'Organization', 'url': '/company/co0020336/'}],
 'datePublished': '2016-02-02',
 'description': 'American Crime Story is a TV series starring Sarah Paulson, '
                'Annaleigh Ashford, and Sterling K. Brown. An anthology series '
                "centered around America's most notorious crimes and "
                'criminals.',
 'genre': ['Biography', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzc2MzJmM2ItMjgzYy00MjgxLTljYjctZjJhYzM1ODFhMzU0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'anthology,seasonal anthology series,courtroom,jury,racism',
 'name': 'American Crime Story',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'onetruejewell1'},
            'dateCreated': '2018-04-18',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt2788432/'},
            'name': 'Superb writing and acting!',
            'reviewBody': 'Darren Criss as Andrew Cunanan just Amazing!!! The '
                          'writing excellent!! The whole cast just '
                          'mesmerizing! This series continues to surprise me!',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Watch the OFFICIAL TRAILER for The Assassination '
                            'of Gianni Versace: American Crime Story. The next '
                            "installment of FX's award-winning original series "
                            'premieres January 17th. The Assassination of '
                            'Gianni Versace: American Crime Story is the '
                            "second installment of FX's award-winning limited "
                            'series, American Crime Story.',
             'embedUrl': '/video/imdb/vi1521989657',
             'name': 'Season 2: Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTdjY2MzZjQtOTQ2Yy00YTQ5LTg2MzQtZGNhOGUxZjA3MDM1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTdjY2MzZjQtOTQ2Yy00YTQ5LTg2MzQtZGNhOGUxZjA3MDM1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg',
             'uploadDate': '2017-11-15T01:49:18Z'},
 'url': '/title/tt2788432/'}