{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Eraserhead',
 'EntryURL': 'https://www.imdb.com/title/tt0074486',
 'Entry_json': 'Favorites/Movies/snapshot/Eraserhead/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Eraserhead/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Eraserhead/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Jack Nance', 'url': '/name/nm0620756/'},
           {'@type': 'Person',
            'name': 'Charlotte Stewart',
            'url': '/name/nm0829270/'},
           {'@type': 'Person',
            'name': 'Allen Joseph',
            'url': '/name/nm0430535/'},
           {'@type': 'Person',
            'name': 'Jeanne Bates',
            'url': '/name/nm0060931/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 97540,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'David Lynch',
              'url': '/name/nm0000186/'},
             {'@type': 'Organization', 'url': '/company/co0017295/'},
             {'@type': 'Organization', 'url': '/company/co0139613/'}],
 'datePublished': '1978-02-03',
 'description': 'Eraserhead is a movie starring Jack Nance, Charlotte Stewart, '
                'and Allen Joseph. Henry Spencer tries to survive his '
                'industrial environment, his angry girlfriend, and the '
                'unbearable screams of his newly born mutant child.',
 'director': [{'@type': 'Person',
               'name': 'David Lynch',
               'url': '/name/nm0000186/'}],
 'duration': 'PT1H29M',
 'genre': 'Horror',
 'image': 'https://m.media-amazon.com/images/M/MV5BMDExYzg5YjQtMzE0Yy00OWJjLThiZTctMWI5MzhjM2RmNjA4L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'surrealism,nightmare,psychosis,factory,deformed baby',
 'name': 'Eraserhead',
 'url': '/title/tt0074486/'}