{'Actors': ['Allen Joseph',
            'Charlotte Stewart',
            'Darwin Joston',
            'Gill Dennis',
            'Hal Landon Jr',
            'Jack Nance',
            'Jack Walsh',
            'Jeanne Bates',
            'Judith Roberts',
            'T Max Graham'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\n'
                'Eraserhead: Henry Spencer tries to survive his industrial '
                'environment, his angry girlfriend, and the unbearable screams '
                'of his newly born mutant child. ',
 'Director': ['David Lynch'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Eraserhead',
 'EntryURL': 'https://www.imdb.com/title/tt0074486',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Eraserhead/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Eraserhead/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Eraserhead/info.py',
 'Genres': ['Sci-Fi', 'Horror', 'Fantasy'],
 'IMDB': 'http://www.imdb.com/title/tt0074486',
 'PrimeWire': 'http://www.primewire.ag/watch-3880-Eraserhead',
 'Ratings': {'IMDB': '7.4/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.22/5',
             'RT': '91%',
             'Votes': '181'},
 'Released': '1977-03-19',
 'Runtime': '85 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/3880_Eraserhead_1977.jpg',
 'Title': 'Eraserhead'}