{'@context': 'http://schema.org',
 '@type': 'CreativeWork',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Dave-Chappelle-Sticks--Stones',
 'EntryURL': 'https://www.imdb.com/title/tt10810424',
 'Entry_json': 'Favorites/Movies/snapshot/Dave-Chappelle-Sticks--Stones/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Dave-Chappelle-Sticks--Stones/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Dave-Chappelle-Sticks--Stones/thumb.jpg',
 'actor': {'@type': 'Person',
           'name': 'Dave Chappelle',
           'url': '/name/nm0152638/'},
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 19787,
                     'ratingValue': '8.5',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Dave Chappelle',
              'url': '/name/nm0152638/'},
             {'@type': 'Organization', 'url': '/company/co0120987/'}],
 'datePublished': '2019-08-26',
 'description': 'Dave Chappelle: Sticks & Stones is a TV special starring Dave '
                'Chappelle. Dave Chappelle takes on gun culture, the opioid '
                'crisis, and the tidal wave of celebrity scandals in a defiant '
                'stand-up special filmed in Atlanta.',
 'director': {'@type': 'Person',
              'name': 'Stan Lathan',
              'url': '/name/nm0490133/'},
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BOWQ2NDZhNGMtOWMwNS00ZWJhLTk2ZGEtY2VkOTY3ZTljNDQ2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'tv special,stand up comedy,comedy special,reference to michael '
             'jackson,reference to r. kelly',
 'name': 'Dave Chappelle: Sticks & Stones',
 'url': '/title/tt10810424/'}