{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-02-02',
 'EntryPath': 'Favorites/Movies/snapshot/Pandoras-Promise',
 'EntryURL': 'https://www.imdb.com/title/tt1992193',
 'Entry_json': 'Favorites/Movies/snapshot/Pandoras-Promise/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Pandoras-Promise/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Pandoras-Promise/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Stewart Brand',
            'url': '/name/nm1674895/'},
           {'@type': 'Person',
            'name': 'Richard Rhodes',
            'url': '/name/nm2090110/'},
           {'@type': 'Person',
            'name': 'Gwyneth Cravens',
            'url': '/name/nm0186651/'},
           {'@type': 'Person',
            'name': 'Mark Lynas',
            'url': '/name/nm1751915/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1802,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Robert Stone',
              'url': '/name/nm0832134/'},
             {'@type': 'Organization', 'url': '/company/co0085230/'},
             {'@type': 'Organization', 'url': '/company/co0042766/'}],
 'datePublished': '2013-11-15',
 'description': "Pandora's Promise is a movie starring Stewart Brand, Richard "
                'Rhodes, and Gwyneth Cravens. A feature-length documentary '
                'about the history and future of nuclear power. The film '
                "explores how and why mankind's most feared and...",
 'director': {'@type': 'Person',
              'name': 'Robert Stone',
              'url': '/name/nm0832134/'},
 'duration': 'PT1H27M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTgyNDYxMzQxM15BMl5BanBnXkFtZTcwODQ0NTY0OQ@@._V1_.jpg',
 'name': "Pandora's Promise",
 'trailer': {'@type': 'VideoObject',
             'description': 'A documentary about the history and future of '
                            'nuclear power. The film explores how and why '
                            "mankind's most feared and controversial "
                            'technological discovery is now passionately '
                            'embraced by many of those who once led the charge '
                            'against it',
             'embedUrl': '/video/imdb/vi2888148505',
             'name': "Pandora's Promise",
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzg0MTEyNzEyM15BMl5BanBnXkFtZTgwMTEzOTg4MjE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzg0MTEyNzEyM15BMl5BanBnXkFtZTgwMTEzOTg4MjE@._V1_.jpg',
             'uploadDate': '2013-05-03T08:46:02Z'},
 'url': '/title/tt1992193/'}