{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Naked-Lunch',
 'EntryURL': 'https://www.imdb.com/title/tt0102511',
 'Entry_json': 'Favorites/Movies/snapshot/Naked-Lunch/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Naked-Lunch/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Naked-Lunch/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Peter Weller',
            'url': '/name/nm0000693/'},
           {'@type': 'Person', 'name': 'Judy Davis', 'url': '/name/nm0001114/'},
           {'@type': 'Person', 'name': 'Ian Holm', 'url': '/name/nm0000453/'},
           {'@type': 'Person',
            'name': 'Julian Sands',
            'url': '/name/nm0001696/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 45850,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'William S. Burroughs',
              'url': '/name/nm0123221/'},
             {'@type': 'Person',
              'name': 'David Cronenberg',
              'url': '/name/nm0000343/'},
             {'@type': 'Organization', 'url': '/company/co0029168/'},
             {'@type': 'Organization', 'url': '/company/co0053578/'},
             {'@type': 'Organization', 'url': '/company/co0017692/'},
             {'@type': 'Organization', 'url': '/company/co0039782/'},
             {'@type': 'Organization', 'url': '/company/co0052648/'},
             {'@type': 'Organization', 'url': '/company/co0045032/'},
             {'@type': 'Organization', 'url': '/company/co0064350/'}],
 'datePublished': '1992-03-11',
 'description': 'Naked Lunch is a movie starring Peter Weller, Judy Davis, and '
                'Ian Holm. After developing an addiction to the substance he '
                'uses to kill bugs, an exterminator accidentally kills his '
                'wife, and becomes involved in a secret government...',
 'director': [{'@type': 'Person',
               'name': 'David Cronenberg',
               'url': '/name/nm0000343/'}],
 'duration': 'PT1H55M',
 'genre': 'Drama',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTRiOTQ2ZWQtMmIwYy00Y2Y3LWFmMzgtNzgzZWU1MDhlOGJhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'secret agent,lynchian,psychological disintegration,reality vs '
             'fantasy,repressed homosexual',
 'name': 'Naked Lunch',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi1534443033',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOWQyY2M3ZDEtM2M4MS00ZGVlLTg5MTQtNmY4Y2Y2ZDAzZGRiXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOWQyY2M3ZDEtM2M4MS00ZGVlLTg5MTQtNmY4Y2Y2ZDAzZGRiXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2020-07-22T16:10:37Z'}],
 'url': '/title/tt0102511/'}