{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/What-Dreams-May-Come',
 'EntryURL': 'https://www.imdb.com/title/tt0120889',
 'Entry_json': 'Favorites/Movies/snapshot/What-Dreams-May-Come/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/What-Dreams-May-Come/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/What-Dreams-May-Come/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Robin Williams',
            'url': '/name/nm0000245/'},
           {'@type': 'Person',
            'name': 'Cuba Gooding Jr.',
            'url': '/name/nm0000421/'},
           {'@type': 'Person',
            'name': 'Annabella Sciorra',
            'url': '/name/nm0001711/'},
           {'@type': 'Person',
            'name': 'Max von Sydow',
            'url': '/name/nm0001884/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 100534,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Richard Matheson',
              'url': '/name/nm0558577/'},
             {'@type': 'Person',
              'name': 'Ronald Bass',
              'url': '/name/nm0060103/'},
             {'@type': 'Organization', 'url': '/company/co0030612/'},
             {'@type': 'Organization', 'url': '/company/co0031772/'},
             {'@type': 'Organization', 'url': '/company/co0052106/'}],
 'datePublished': '1998-10-02',
 'description': 'What Dreams May Come is a movie starring Robin Williams, Cuba '
                'Gooding Jr., and Annabella Sciorra. Chris Nielsen dies in an '
                'accident, and enters Heaven. But when he discovers that his '
                'beloved wife Annie has killed herself out of...',
 'director': [{'@type': 'Person',
               'name': 'Vincent Ward',
               'url': '/name/nm0911910/'}],
 'duration': 'PT1H53M',
 'genre': ['Drama', 'Fantasy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTg5ZWRjNTctNmMyMi00NTJmLTg3YjktMzJlMDRiYWQ0MjMzL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'heaven,soul mate,afterlife,reference to william '
             "shakespeare,reference to shakespeare's hamlet",
 'name': 'What Dreams May Come',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Universal Studios Home '
                             'Entertainment',
              'embedUrl': '/video/imdb/vi4110156057',
              'name': 'What Dreams May Come',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYTg1NjAyMGItMDBhYS00MmIxLWI3MGYtMzNjZWE2ZDgyYzJkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYTg1NjAyMGItMDBhYS00MmIxLWI3MGYtMzNjZWE2ZDgyYzJkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T17:22:20Z'}],
 'url': '/title/tt0120889/'}