<?php
$infoArray = array('Actors' => array('Andre Hennicke',
            'Christian Hoening',
            'Gerald Alexander Held',
            'J&#xF6;rg Hube',
            'Joachim H&#xF6;ppner',
            'Johanna Gastdorf',
            'Johannes Herrschmann',
            'Julia Jentsch',
            'Klaus H&#xE4;ndl',
            'Maria Hofst&#xE4;tter',
            'Norbert Heckner',
            'Paul Herwig',
            'Petra Kelling',
            'Walter Hess',
            'Wolfgang Pregler'),
 'Added' => '2013-06-30',
 'Countries' => array('Germany'),
 'Description' => "\nSophie Scholl - Die letzten Tage: The Final Days is the true story of Germany's most famous anti-Nazi heroine brought to life. Sophie Scholl is the fearless activist of the underground student resistance group, The White Rose. Using historical records of her incarceration, the film re-creates the last six days of Sophie Scholl's life: a journey from arrest to interrogation, trial and sentence in 1943 Munich. Unwavering in her convictions and loyalty to her comrades, her cross-examination by the Gestapo quickly escalates into a searing test of wills as Scholl delivers a passionate call to freedom and personal responsibility that is both haunting and timeless. ",
 'Director' => array('Marc Rothemund'),
 'Genres' => array('Biography', 'Crime', 'Drama', 'History', 'War'),
 'IMDB' => 'http://www.imdb.com/title/tt0426578',
 'PrimeWire' => 'http://www.primewire.ag/watch-476182-Sophie-Scholl-Die-letzten-Tage',
 'Ratings' => array('IMDB' => '7.7/10',
             'Metascore' => '76%',
             'PrimeWire' => '3.96/5',
             'RT' => '87%',
             'Votes' => '75'),
 'Released' => '2005-02-13',
 'Runtime' => '120 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/476182_Sophie_Scholl_Die_letzten_Tage_2005.jpg',
 'Title' => 'Sophie-Scholl-Die-letzten-Tage');
?>