{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2011-10-06',
 'EntryPath': 'Favorites/TV/snapshot/Nick-Swardsons-Pretend-Time',
 'EntryURL': 'https://www.imdb.com/title/tt1721648',
 'Entry_json': 'Favorites/TV/snapshot/Nick-Swardsons-Pretend-Time/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Nick-Swardsons-Pretend-Time/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Nick-Swardsons-Pretend-Time/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Nick Swardson',
            'url': '/name/nm0841910/'},
           {'@type': 'Person',
            'name': 'John Cramer',
            'url': '/name/nm0186161/'},
           {'@type': 'Person',
            'name': 'Deirdre Wall',
            'url': '/name/nm2874881/'},
           {'@type': 'Person',
            'name': 'Julia Lea Wolov',
            'url': '/name/nm0938661/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 802,
                      'ratingValue': '6.1',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Tom Gianas',
              'url': '/name/nm0316139/'},
             {'@type': 'Person',
              'name': 'Nick Swardson',
              'url': '/name/nm0841910/'},
             {'@type': 'Organization', 'url': '/company/co0202412/'},
             {'@type': 'Organization', 'url': '/company/co0059609/'}],
 'datePublished': '2010-10-12',
 'description': 'Pretend Time is a TV series starring Nick Swardson, John '
                'Cramer, and Deirdre Wall. Sketch comedy show starring Nick '
                'Swardson.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjEyNzU0MTM4Ml5BMl5BanBnXkFtZTgwODc5NzcwMzE@._V1_.jpg',
 'keywords': 'alternative comedy,vulgarity,stand up comedian,shock '
             'humor,sexual humor',
 'name': 'Pretend Time',
 'url': '/title/tt1721648/'}