{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-06-29',
 'EntryPath': 'Favorites/Movies/snapshot/Knuckleball',
 'EntryURL': 'https://www.imdb.com/title/tt2343601',
 'Entry_json': 'Favorites/Movies/snapshot/Knuckleball/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Knuckleball/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Knuckleball/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Tim Wakefield',
            'url': '/name/nm0906807/'},
           {'@type': 'Person',
            'name': 'Dave Lennon',
            'url': '/name/nm4537372/'},
           {'@type': 'Person', 'name': 'Jim Bouton', 'url': '/name/nm0100357/'},
           {'@type': 'Person',
            'name': 'Charles Hough',
            'url': '/name/nm0396409/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1567,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Organization', 'url': '/company/co0080941/'},
             {'@type': 'Organization', 'url': '/company/co0093738/'}],
 'datePublished': '2012-09-18',
 'description': 'Knuckleball! is a movie starring Tim Wakefield, Dave Lennon, '
                "and Jim Bouton. A documentary that showcases baseball's most "
                'unpredictable pitch.',
 'director': [{'@type': 'Person',
               'name': 'Ricki Stern',
               'url': '/name/nm0827830/'},
              {'@type': 'Person',
               'name': 'Anne Sundberg',
               'url': '/name/nm0839064/'}],
 'duration': 'PT1H33M',
 'genre': ['Documentary', 'Sport'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTgzNTkyMjk0N15BMl5BanBnXkFtZTcwODQ5NDUyOA@@._V1_.jpg',
 'keywords': 'baseball,professional sports,boston red sox,fenway park',
 'name': 'Knuckleball!',
 'trailer': [{'@type': 'VideoObject',
              'description': "A documentary that showcases baseball's most "
                             'unpredictable pitch.',
              'embedUrl': '/video/imdb/vi3385304345',
              'name': 'Theatrical Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjM5MDUyMjAwOF5BMl5BanBnXkFtZTcwNTczNTAzOA@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjM5MDUyMjAwOF5BMl5BanBnXkFtZTcwNTczNTAzOA@@._V1_.jpg',
              'uploadDate': '2012-08-21T15:35:51Z'}],
 'url': '/title/tt2343601/'}