{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Tony-Hawks-Pro-Skater-2',
 'EntryURL': 'https://rawg.io/games/tony-hawks-pro-skater-2',
 'Entry_json': 'Favorites/Games/snapshot/Tony-Hawks-Pro-Skater-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Tony-Hawks-Pro-Skater-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Tony-Hawks-Pro-Skater-2/thumb.jpg',
 'added': 333,
 'background_image': 'https://media.rawg.io/media/screenshots/c21/c2123c3dea40946f705a54772ed6238b.jpg',
 'developers': ['Neversoft',
                'Treyarch',
                'Neversoft Entertainment',
                'Aspyr Media'],
 'genres': ['Sports', 'Arcade'],
 'name': "Tony Hawk's Pro Skater 2",
 'platforms': ['PC',
               'Dreamcast',
               'Nintendo 64',
               'Classic Macintosh',
               'Game Boy Color',
               'PlayStation',
               'iOS',
               'Game Boy Advance'],
 'publishers': ['Activision Blizzard'],
 'released': '2000-09-19',
 'slug': 'tony-hawks-pro-skater-2'}