{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-10-16',
 'EntryPath': 'Favorites/Movies/snapshot/Experimenter',
 'EntryURL': 'https://www.imdb.com/title/tt3726704',
 'Entry_json': 'Favorites/Movies/snapshot/Experimenter/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Experimenter/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Experimenter/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'John Palladino',
            'url': '/name/nm3746649/'},
           {'@type': 'Person',
            'name': 'Anthony Edwards',
            'url': '/name/nm0000381/'},
           {'@type': 'Person',
            'name': 'Jim Gaffigan',
            'url': '/name/nm0300712/'},
           {'@type': 'Person',
            'name': 'Peter Sarsgaard',
            'url': '/name/nm0765597/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 17053,
                      'ratingValue': '6.6',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Michael Almereyda',
              'url': '/name/nm0021899/'},
             {'@type': 'Organization', 'url': '/company/co0308292/'},
             {'@type': 'Organization', 'url': '/company/co0182563/'},
             {'@type': 'Organization', 'url': '/company/co0072994/'},
             {'@type': 'Organization', 'url': '/company/co0224649/'}],
 'datePublished': '2015-10-16',
 'description': 'Experimenter is a movie starring John Palladino, Anthony '
                'Edwards, and Jim Gaffigan. In 1961, famed social psychologist '
                'Stanley Milgram conducted a series of radical behavior '
                "experiments that tested ordinary humans' willingness to...",
 'director': [{'@type': 'Person',
               'name': 'Michael Almereyda',
               'url': '/name/nm0021899/'}],
 'duration': 'PT1H38M',
 'genre': ['Biography', 'Drama', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTA4NzYwMDI0NF5BMl5BanBnXkFtZTgwNTgzNDczNjE@._V1_.jpg',
 'keywords': 'psychologist,electric shock,human behavior,milgram,experiment',
 'name': 'Experimenter',
 'url': '/title/tt3726704/'}