{'Actors': ['Anton Yelchin',
            'Peter Sarsgaard',
            'Taryn Manning',
            'Winona Ryder'],
 'Added': '2015-10-16',
 'Countries': ['USA'],
 'Description': '\n'
                'Experimenter: Famed social psychologist Stanley Milgram, in '
                '1961 conducted a series of radical behavior experiments that '
                'tested ordinary humans willingness to obey authority. ',
 'Director': ['Michael Almereyda'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Experimenter',
 'EntryURL': 'https://www.imdb.com/title/tt3726704',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Experimenter/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Experimenter/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Experimenter/info.py',
 'Genres': ['Biography'],
 'IMDB': 'http://www.imdb.com/title/tt3726704',
 'PrimeWire': 'http://www.primewire.ag/watch-2769602-Experimenter',
 'Ratings': {'IMDB': '7.1/10',
             'Metascore': '80%',
             'PrimeWire': '3.38/5',
             'RT': '67%',
             'Votes': '8'},
 'Released': '2015-10-16',
 'Runtime': '90 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2769602_Experimenter_2015.jpg',
 'Title': 'Experimenter'}