{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Beach',
 'EntryURL': 'https://www.imdb.com/title/tt0163978',
 'Entry_json': 'Favorites/Movies/snapshot/The-Beach/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Beach/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Beach/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Leonardo DiCaprio',
            'url': '/name/nm0000138/'},
           {'@type': 'Person',
            'name': 'Daniel York',
            'url': '/name/nm0948679/'},
           {'@type': 'Person',
            'name': 'Patcharawan Patarakijjanon',
            'url': '/name/nm0665265/'},
           {'@type': 'Person',
            'name': 'Virginie Ledoyen',
            'url': '/name/nm0001461/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 217342,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'John Hodge',
              'url': '/name/nm0388076/'},
             {'@type': 'Person',
              'name': 'Alex Garland',
              'url': '/name/nm0307497/'},
             {'@type': 'Organization', 'url': '/company/co0103732/'}],
 'datePublished': '2000-02-03',
 'description': 'The Beach is a movie starring Leonardo DiCaprio, Daniel York, '
                'and Patcharawan Patarakijjanon. Vicenarian Richard travels to '
                'Thailand and finds himself in possession of a strange map. '
                'Rumours state that it leads to a solitary beach...',
 'director': {'@type': 'Person',
              'name': 'Danny Boyle',
              'url': '/name/nm0000965/'},
 'duration': 'PT1H59M',
 'genre': ['Adventure', 'Drama', 'Romance', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNTljZTUzYWUtOTI4YS00NmZlLWE5MmQtZjFlZDZhNjg4MjQxXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg',
 'keywords': 'thailand,beach,pretentiousness,cricket the sport,map',
 'name': 'The Beach',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from 20th Century Fox',
             'embedUrl': '/video/imdb/vi3699966233',
             'name': 'The Beach',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTQ0NmY3NjYtZmY0OC00OWI2LThhMDktMjlmZGE4OWZjNjMwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTQ0NmY3NjYtZmY0OC00OWI2LThhMDktMjlmZGE4OWZjNjMwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:12:07Z'},
 'url': '/title/tt0163978/'}