{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Books/snapshot/Running-Out-Of-Time',
 'EntryURL': 'https://www.goodreads.com/book/show/227658.Running_Out_of_Time',
 'Entry_json': 'Favorites/Books/snapshot/Running-Out-Of-Time/entry.json',
 'Entry_py': 'Favorites/Books/snapshot/Running-Out-Of-Time/info.py',
 'Entry_thumb': 'Favorites/Books/snapshot/Running-Out-Of-Time/thumb.jpg',
 'authors': [{'id': '14617',
              'image_url': '\n'
                           'https://images.gr-assets.com/authors/1309842407p5/14617.jpg\n',
              'link': 'https://www.goodreads.com/author/show/14617.Margaret_Peterson_Haddix',
              'name': 'Margaret Peterson Haddix',
              'role': None,
              'small_image_url': '\n'
                                 'https://images.gr-assets.com/authors/1309842407p2/14617.jpg\n'}],
 'description': None,
 'edition_information': None,
 'format': 'Paperback',
 'id': '227658',
 'image_url': 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1408913584l/227658._SX98_.jpg',
 'isbn': '0439632501',
 'isbn13': '9780439632508',
 'large_image_url': None,
 'link': 'https://www.goodreads.com/book/show/227658.Running_Out_of_Time',
 'num_pages': '184',
 'publication_day': None,
 'publication_month': None,
 'publication_year': '2004',
 'published': '2004',
 'publisher': 'Scholastic',
 'small_image_url': 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1408913584l/227658._SY75_.jpg',
 'title': 'Running Out of Time',
 'title_without_series': 'Running Out of Time',
 'uri': 'kca://book/amzn1.gr.book.v1.EHLFm1kaEW5RpKkoywTU8g',
 'work': '  '}