{'Actors': ['&tv'],
 'Added': '2015-01-18',
 'Countries': [],
 'Description': '\nDrunk History UK: UK comedians relate their favorite historical stories while getting absolutely bladdered on a mixture of beers, wines and spirits. Their slurred versions of history are then acted out, word for word, by a host of well-known actors, celebrities and comedians including Johnny Vegas, Russell Kane, Joe Lycett, Rob Beckett, Alex Horne and James Acaster. Luckily, Jimmy Carr is on voice-over duties to restore some order if the drinking sessions get out of hand. ',
 'Director': [],
 'Genres': ['Comedy&tv'],
 'IMDB': 'NA',
 'PrimeWire': 'http://www.primewire.ag/tv-2756814-Drunk-History-UK',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '3.46/5',
             'RT': 'N/A',
             'Votes': '35'},
 'Released': '2015-01-12',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2756814_Drunk_History_UK.jpg',
 'Title': 'Drunk-History-UK'}