{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/6-Days-to-Air-The-Making-of-South-Park',
 'EntryURL': 'https://www.imdb.com/title/tt2076781',
 'Entry_json': 'Favorites/Movies/snapshot/6-Days-to-Air-The-Making-of-South-Park/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/6-Days-to-Air-The-Making-of-South-Park/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/6-Days-to-Air-The-Making-of-South-Park/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Trey Parker',
            'url': '/name/nm0005295/'},
           {'@type': 'Person', 'name': 'Matt Stone', 'url': '/name/nm0001778/'},
           {'@type': 'Person',
            'name': 'Anne Garefino',
            'url': '/name/nm0307187/'},
           {'@type': 'Person',
            'name': 'Frank C. Agnone II',
            'url': '/name/nm0013166/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 2189,
                     'ratingValue': '7.7',
                     'worstRating': '1.0'},
 'contentRating': 'Not Rated',
 'creator': {'@type': 'Organization', 'url': '/company/co0029768/'},
 'datePublished': '2011-10-09',
 'description': '6 Days to Air: The Making of South Park is a TV movie '
                'starring Trey Parker, Matt Stone, and Anne Garefino. A look '
                'at the making of HUMANCENTiPAD (2011).',
 'director': {'@type': 'Person',
              'name': 'Arthur Bradford',
              'url': '/name/nm0102994/'},
 'duration': 'PT42M',
 'genre': ['Documentary', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDUyMzY1NDcwNV5BMl5BanBnXkFtZTgwODExNjMyMjE@._V1_.jpg',
 'keywords': 'making of,countdown,television show,number in title',
 'name': '6 Days to Air: The Making of South Park',
 'url': '/title/tt2076781/'}