{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gangs-Of-New-York',
 'EntryURL': 'https://www.imdb.com/title/tt0217505',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gangs-Of-New-York/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gangs-Of-New-York/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Gangs-Of-New-York/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Leonardo DiCaprio',
            'url': '/name/nm0000138/'},
           {'@type': 'Person',
            'name': 'Cameron Diaz',
            'url': '/name/nm0000139/'},
           {'@type': 'Person',
            'name': 'Daniel Day-Lewis',
            'url': '/name/nm0000358/'},
           {'@type': 'Person',
            'name': 'Jim Broadbent',
            'url': '/name/nm0000980/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 392530,
                     'ratingValue': '7.5',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Jay Cocks',
              'url': '/name/nm0168379/'},
             {'@type': 'Person',
              'name': 'Jay Cocks',
              'url': '/name/nm0168379/'},
             {'@type': 'Person',
              'name': 'Steven Zaillian',
              'url': '/name/nm0001873/'},
             {'@type': 'Person',
              'name': 'Kenneth Lonergan',
              'url': '/name/nm0518836/'},
             {'@type': 'Organization', 'url': '/company/co0022594/'},
             {'@type': 'Organization', 'url': '/company/co0011877/'},
             {'@type': 'Organization', 'url': '/company/co0108557/'}],
 'datePublished': '2002-12-20',
 'description': 'Gangs of New York is a movie starring Leonardo DiCaprio, '
                'Cameron Diaz, and Daniel Day-Lewis. In 1862, Amsterdam Vallon '
                'returns to the Five Points area of New York City seeking '
                "revenge against Bill the Butcher, his father's killer.",
 'director': {'@type': 'Person',
              'name': 'Martin Scorsese',
              'url': '/name/nm0000217/'},
 'duration': 'PT2H47M',
 'genre': ['Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNDg3MmI1ZDYtMDZjYi00ZWRlLTk4NzEtZjY4Y2U0NjE5YmRiXkEyXkFqcGdeQXVyNzAxMjE1NDg@._V1_.jpg',
 'keywords': 'gangster,new york city,butcher,immigrant,title at the end',
 'name': 'Gangs of New York',
 'trailer': {'@type': 'VideoObject',
             'description': 'CT# 2 w/DVD Box Art',
             'embedUrl': '/video/imdb/vi2166859289',
             'name': 'Gangs of New York',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTdiMzE3ZTYtZDAwNi00NTM3LThkNjYtNzA5MjIzMTdiYWVkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTdiMzE3ZTYtZDAwNi00NTM3LThkNjYtNzA5MjIzMTdiYWVkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2013-05-04T04:13:30Z'},
 'url': '/title/tt0217505/'}