{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Final-Fantasy-Vii',
 'EntryURL': 'https://rawg.io/games/final-fantasy-vii',
 'Entry_json': 'Favorites/Games/snapshot/Final-Fantasy-Vii/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Final-Fantasy-Vii/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Final-Fantasy-Vii/thumb.jpg',
 'added': 2147,
 'background_image': 'https://media.rawg.io/media/games/6c0/6c00ee85d1344f58c469e8e47fd8ae7c.jpg',
 'developers': ['Square Enix', 'Square'],
 'genres': ['Adventure', 'RPG'],
 'name': 'Final Fantasy VII',
 'platforms': ['PlayStation',
               'Android',
               'PlayStation 4',
               'PlayStation 3',
               'iOS',
               'Xbox One',
               'PlayStation 2',
               'Nintendo Switch',
               'PS Vita',
               'PSP',
               'PC'],
 'publishers': ['Square Enix',
                'Sony Computer Entertainment',
                'Eidos Interactive',
                'Square',
                "'''PlayStation'''",
                'vgrelease',
                'Microsoft Studios'],
 'released': '1997-01-31',
 'slug': 'final-fantasy-vii'}