<?php
$infoArray = array('Actors' => array('Alexia Fast&tv',
            'Christopher Denham&tv',
            'David Harbour&tv',
            'John Benjamin Hickey&tv',
            'Michael Chernus&tv',
            'Olivia Williams&tv'),
 'Added' => '2015-07-15',
 'Countries' => array(),
 'Description' => "\nManhattan: Set against the backdrop of the greatest clandestine race against time in the history of science with the mission to build the world's first atomic bomb in Los Alamos, New Mexico. Flawed scientists and their families attempt to co-exist in a world where secrets and lies infiltrate every aspect of their lives. ",
 'Director' => array('NA'),
 'Genres' => array('Drama&tv'),
 'IMDB' => 'http://www.imdb.com/title/tt3231564',
 'PrimeWire' => 'http://www.primewire.ag/tv-2747514-Manhattan',
 'Ratings' => array('IMDB' => '7.8/10',
             'Metascore' => 'N/A',
             'PrimeWire' => '4.48/5',
             'RT' => 'N/A',
             'Votes' => '165'),
 'Released' => '2014-07-27',
 'Runtime' => '60 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2747514_Manhattan.jpg',
 'Title' => 'Manhattan');
?>