<?php
$infoArray = array('Actors' => array('Andy Calderwood',
            'Brad Moore',
            'David OConnor',
            'Gerard Kearns',
            'Grant Crookes',
            'Iwan Rheon',
            'Liam Tulley',
            'Lucy Fenton',
            'Luke Treadaway',
            'Matthew Lewis',
            'Neil Maskell',
            'Paul Clayton',
            'Peter Foster',
            'Timothy Spall',
            'Vanessa Kirby'),
 'Added' => '2013-07-10',
 'Countries' => array('UK'),
 'Description' => '\nWasteland: A young Englishman recently released from prison recruits his three best friends and to rob the local drug kingpin who is responsible for his incarceration. Can he get revenge and win back his fed-up girlfriend? ',
 'Director' => array('Rowan Athale'),
 'Genres' => array('Crime', 'Drama', 'Thriller'),
 'IMDB' => 'http://www.imdb.com/title/tt1981140',
 'PrimeWire' => 'http://www.primewire.ag/watch-2740461-Wasteland',
 'Ratings' => array('IMDB' => '6.6/10',
             'Metascore' => '52%',
             'PrimeWire' => '3.61/5',
             'RT' => '63%',
             'Votes' => '147'),
 'Released' => '2012-09-07',
 'Runtime' => '108 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2740461_Wasteland_2013.jpg',
 'Title' => 'Wasteland');
?>