{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2011-11-17',
 'EntryPath': 'Favorites/Movies/snapshot/Puncture',
 'EntryURL': 'https://www.imdb.com/title/tt1582248',
 'Entry_json': 'Favorites/Movies/snapshot/Puncture/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Puncture/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Puncture/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Chris Evans',
            'url': '/name/nm0262635/'},
           {'@type': 'Person',
            'name': 'Mark Kassen',
            'url': '/name/nm0440860/'},
           {'@type': 'Person',
            'name': 'Vinessa Shaw',
            'url': '/name/nm0005416/'},
           {'@type': 'Person',
            'name': 'Marshall Bell',
            'url': '/name/nm0068382/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 22325,
                      'ratingValue': '6.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Paul Danziger',
              'url': '/name/nm3754817/'},
             {'@type': 'Person',
              'name': 'Chris Lopata',
              'url': '/name/nm0519802/'},
             {'@type': 'Person',
              'name': 'Ela Thier',
              'url': '/name/nm0858008/'},
             {'@type': 'Organization', 'url': '/company/co0032062/'},
             {'@type': 'Organization', 'url': '/company/co0183529/'},
             {'@type': 'Organization', 'url': '/company/co0198690/'}],
 'datePublished': '2012-03-15',
 'description': 'Puncture is a movie starring Chris Evans, Mark Kassen, and '
                'Vinessa Shaw. A David and Goliath law drama about a '
                'drug-addicted lawyer who takes on a health supply corporation '
                'while battling his own personal demons.',
 'director': [{'@type': 'Person',
               'name': 'Adam Kassen',
               'url': '/name/nm0440859/'},
              {'@type': 'Person',
               'name': 'Mark Kassen',
               'url': '/name/nm0440860/'}],
 'duration': 'PT1H40M',
 'genre': ['Biography', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTYzODIxNjAxNV5BMl5BanBnXkFtZTcwOTcxNzQzNg@@._V1_.jpg',
 'keywords': 'based on real people,based on real person,man,lawyer,needle',
 'name': 'Puncture',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A David and Goliath law drama about a '
                             'drug-addicted lawyer who takes on a health '
                             'supply corporation while battling his own '
                             'personal demons.',
              'embedUrl': '/video/imdb/vi3910179865',
              'name': 'Theatrical',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTg0NjMwMjQ0OF5BMl5BanBnXkFtZTcwMTU2NzQzNg@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTg0NjMwMjQ0OF5BMl5BanBnXkFtZTcwMTU2NzQzNg@@._V1_.jpg',
              'uploadDate': '2011-08-18T08:37:14Z'}],
 'url': '/title/tt1582248/'}