{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Obduction',
 'EntryURL': 'https://rawg.io/games/obduction',
 'Entry_json': 'Favorites/Games/snapshot/Obduction/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Obduction/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Obduction/thumb.jpg',
 'added': 973,
 'background_image': 'https://media.rawg.io/media/games/c01/c0137ea58ab81b909685b5fb78d788cc.jpg',
 'developers': ['Cyan Worlds', 'Cyan, Inc.'],
 'genres': ['Adventure', 'Indie', 'Puzzle'],
 'name': 'Obduction',
 'platforms': ['Xbox One', 'macOS', 'PC', 'PlayStation 4'],
 'publishers': ['Cyan Inc.', 'Cyan Inc'],
 'released': '2016-08-23',
 'slug': 'obduction'}