{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-11-30',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battle-of-Chernobyl',
 'EntryURL': 'https://www.imdb.com/title/tt1832484',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battle-of-Chernobyl/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battle-of-Chernobyl/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battle-of-Chernobyl/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/The-Battle-of-Chernobyl/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Tim Birkett',
            'url': '/name/nm4299133/'},
           {'@type': 'Person', 'name': 'Hans Blix', 'url': '/name/nm1556284/'},
           {'@type': 'Person',
            'name': 'Mikhail Gorbachev',
            'url': '/name/nm0329784/'},
           {'@type': 'Person',
            'name': 'Oleg Mirochnikov',
            'url': '/name/nm1360310/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1298,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0121147/'},
 'datePublished': '2007-01-28',
 'description': 'The Battle of Chernobyl is a movie starring Tim Birkett, Hans '
                'Blix, and Mikhail Gorbachev. Documentary of the nuclear '
                'disaster of Chernobyl.',
 'director': {'@type': 'Person',
              'name': 'Thomas Johnson',
              'url': '/name/nm4297891/'},
 'duration': 'PT1H34M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BZGI4NjYzYjItZmIwYy00YTMzLWI1ZjctYWQ5MDFlMzRmMjgzXkEyXkFqcGdeQXVyMzkxNjQ1Mw@@._V1_.jpg',
 'keywords': 'nuclear energy,nuclear,nuclear power,nuclear disaster,nuclear '
             'accident',
 'name': 'The Battle of Chernobyl',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'mrchevyii'},
            'dateCreated': '2019-07-15',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt1832484/'},
            'name': 'Surreal.',
            'reviewBody': 'The suffering in this documentary makes you '
                          'shutter. The people sacrificed their very lives to '
                          'stop a horrible disaster. I wish I could get this '
                          'on DVD.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '9',
                             'worstRating': '1'}},
 'url': '/title/tt1832484/'}