{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Oa',
 'EntryURL': 'https://www.imdb.com/title/tt4635282',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Oa/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Oa/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/The-Oa/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Brit Marling',
            'url': '/name/nm1779870/'},
           {'@type': 'Person',
            'name': 'Jason Isaacs',
            'url': '/name/nm0005042/'},
           {'@type': 'Person',
            'name': 'Scott Wilson',
            'url': '/name/nm0934113/'},
           {'@type': 'Person',
            'name': 'Alice Krige',
            'url': '/name/nm0000481/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 84826,
                     'ratingValue': '7.9',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Zal Batmanglij',
              'url': '/name/nm2610231/'},
             {'@type': 'Person',
              'name': 'Brit Marling',
              'url': '/name/nm1779870/'},
             {'@type': 'Organization', 'url': '/company/co0136967/'},
             {'@type': 'Organization', 'url': '/company/co0017525/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2016-12-16',
 'description': 'The OA is a TV series starring Brit Marling, Jason Isaacs, '
                'and Scott Wilson. Having gone missing seven years ago, the '
                'previously blind Prairie returns home, now in her twenties '
                'with her sight restored. While many believe she is a...',
 'genre': ['Drama', 'Fantasy', 'Mystery', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY5OTkwNDkzOF5BMl5BanBnXkFtZTgwMDEyNzI1NzM@._V1_.jpg',
 'keywords': 'near death experience,blindness,kidnapping,supernatural '
             'power,psychotronic series',
 'name': 'The OA',
 'trailer': {'@type': 'VideoObject',
             'description': 'OA successfully jumps dimensions but finds '
                            'herself at the center of a mystery she cannot '
                            'solve without the help of a cynical private '
                            'detective.',
             'embedUrl': '/video/imdb/vi274315801',
             'name': 'Season 2 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZjVhYTMyYTktZGFhMi00M2ZmLTlhMTAtZWM2NzNiZDkwYmZlXkEyXkFqcGdeQWFybm8@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZjVhYTMyYTktZGFhMi00M2ZmLTlhMTAtZWM2NzNiZDkwYmZlXkEyXkFqcGdeQWFybm8@._V1_.jpg',
             'uploadDate': '2019-02-27T15:27:27Z'},
 'url': '/title/tt4635282/'}