{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/American-Psycho',
 'EntryURL': 'https://www.imdb.com/title/tt0144084',
 'Entry_json': 'Favorites/Movies/snapshot/American-Psycho/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/American-Psycho/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/American-Psycho/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Christian Bale',
            'url': '/name/nm0000288/'},
           {'@type': 'Person',
            'name': 'Justin Theroux',
            'url': '/name/nm0857620/'},
           {'@type': 'Person', 'name': 'Josh Lucas', 'url': '/name/nm0524197/'},
           {'@type': 'Person', 'name': 'Bill Sage', 'url': '/name/nm0756083/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 469891,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Bret Easton Ellis',
              'url': '/name/nm0254735/'},
             {'@type': 'Person',
              'name': 'Mary Harron',
              'url': '/name/nm0366004/'},
             {'@type': 'Person',
              'name': 'Guinevere Turner',
              'url': '/name/nm0877587/'},
             {'@type': 'Organization', 'url': '/company/co0220056/'},
             {'@type': 'Organization', 'url': '/company/co0006728/'},
             {'@type': 'Organization', 'url': '/company/co0060306/'},
             {'@type': 'Organization', 'url': '/company/co0019350/'},
             {'@type': 'Organization', 'url': '/company/co0018564/'},
             {'@type': 'Organization', 'url': '/company/co0048446/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'}],
 'datePublished': '2000-04-14',
 'description': 'American Psycho is a movie starring Christian Bale, Justin '
                'Theroux, and Josh Lucas. A wealthy New York City investment '
                'banking executive, Patrick Bateman, hides his alternate '
                'psychopathic ego from his co-workers and friends as he...',
 'director': [{'@type': 'Person',
               'name': 'Mary Harron',
               'url': '/name/nm0366004/'}],
 'duration': 'PT1H41M',
 'genre': ['Comedy', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZTM2ZGJmNjQtN2UyOS00NjcxLWFjMDktMDE2NzMyNTZlZTBiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'narcissism,materialism,serial murder,1980s,business card',
 'name': 'American Psycho',
 'trailer': [{'@type': 'VideoObject',
              'description': 'text os',
              'embedUrl': '/video/imdb/vi4060743449',
              'name': 'American Psycho',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMzFiZmIwOTUtMmVkNy00YmZkLWE4ODAtYjE4NWUwNzNiZDM0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMzFiZmIwOTUtMmVkNy00YmZkLWE4ODAtYjE4NWUwNzNiZDM0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2010-05-18T14:52:19Z'}],
 'url': '/title/tt0144084/'}