{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Star-Ocean-The-Last-Hope',
 'EntryURL': 'https://rawg.io/games/star-ocean-the-last-hope',
 'Entry_json': 'Favorites/Games/snapshot/Star-Ocean-The-Last-Hope/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Star-Ocean-The-Last-Hope/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Star-Ocean-The-Last-Hope/thumb.jpg',
 'added': 11,
 'background_image': 'https://media.rawg.io/media/screenshots/df0/df072bfb44c5b77227c8e91764f5406d.jpg',
 'developers': ['tri-Ace Corporation'],
 'genres': ['RPG'],
 'name': 'Star Ocean: The Last Hope',
 'platforms': ['PlayStation 3'],
 'publishers': ['Square Enix'],
 'released': '2009-02-24',
 'slug': 'star-ocean-the-last-hope'}