{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Equilibrium',
 'EntryURL': 'https://www.imdb.com/title/tt0238380',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Equilibrium/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Equilibrium/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Equilibrium/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Christian Bale',
            'url': '/name/nm0000288/'},
           {'@type': 'Person', 'name': 'Sean Bean', 'url': '/name/nm0000293/'},
           {'@type': 'Person',
            'name': 'Emily Watson',
            'url': '/name/nm0001833/'},
           {'@type': 'Person',
            'name': 'Taye Diggs',
            'url': '/name/nm0004875/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 305946,
                     'ratingValue': '7.4',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Kurt Wimmer',
              'url': '/name/nm0934483/'},
             {'@type': 'Organization', 'url': '/company/co0019626/'},
             {'@type': 'Organization', 'url': '/company/co0007610/'}],
 'datePublished': '2002-12-06',
 'description': 'Equilibrium is a movie starring Christian Bale, Sean Bean, '
                'and Emily Watson. In an oppressive future where all forms of '
                'feeling are illegal, a man in charge of enforcing the law '
                'rises to overthrow the system and state.',
 'director': {'@type': 'Person',
              'name': 'Kurt Wimmer',
              'url': '/name/nm0934483/'},
 'duration': 'PT1H47M',
 'genre': ['Action', 'Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTkzMzA1OTI3N15BMl5BanBnXkFtZTYwMzUyMDg5._V1_.jpg',
 'keywords': 'dystopia,suppression of emotion,brainwashing,gun fu,law',
 'name': 'Equilibrium',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi368025113',
             'name': 'Equilibrium',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTg5NmRmYzUtYzM3MS00OWU0LTgzYmMtNzc2OTFkZGZhMzI5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTg5NmRmYzUtYzM3MS00OWU0LTgzYmMtNzc2OTFkZGZhMzI5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2011-10-26T03:19:50Z'},
 'url': '/title/tt0238380/'}