{'Actors': ['Anatole Taubman',
            'Angus Macfadyen',
            'Armin Marewski',
            'Brian Conley',
            'Christian Bale',
            'Christian Kahrmann',
            'Danny Lee Clark',
            'David Hemmings',
            'Dennenesch Zoude',
            'Dirk Martens',
            'Dominic Purcell',
            'Emily Watson',
            'Florian Fitz',
            'John Keogh',
            'Klaus Schindler',
            'Maria Pia Calzone',
            'Matthew Harbour',
            'Mehmet Kurtulus',
            'Mike Smith',
            'Oliver Brandl',
            'Sean Bean',
            'Sean Pertwee',
            'Taye Diggs',
            'William Fichtner'],
 'Added': '2013-02-19',
 'Countries': ['USA'],
 'Description': '\nEquilibrium: In a Fascist future where all forms of feeling are illegal, a man in charge of enforcing the law rises to overthrow the system. ',
 'Director': ['Kurt Wimmer'],
 'Genres': ['Action', 'Thriller', 'Sci-Fi'],
 'IMDB': 'http://www.imdb.com/title/tt0238380',
 'PrimeWire': 'http://www.primewire.ag/watch-1943-Equilibrium',
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': '33%',
             'PrimeWire': '4.32/5',
             'RT': '38%',
             'Votes': '1318'},
 'Released': '2002-12-06',
 'Runtime': '107 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1943_Equilibrium_2002.jpg',
 'Title': 'Equilibrium'}