{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Halo-2',
 'EntryURL': 'https://rawg.io/games/halo-2',
 'Entry_json': 'Favorites/Games/snapshot/Halo-2/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Halo-2/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Halo-2/thumb.jpg',
 'added': 353,
 'background_image': 'https://media.rawg.io/media/games/0c9/0c98889aa28b7c27474be0156961bee2.jpg',
 'developers': ['Bungie, Inc.', 'Microsoft Game Studios'],
 'genres': ['Action', 'Shooter'],
 'name': 'Halo 2',
 'platforms': ['Xbox One', 'Xbox', 'PC'],
 'publishers': ['Microsoft Studios'],
 'released': '2004-11-09',
 'slug': 'halo-2'}