{'Actors': ['Adam Bryant',
            'Alexander Kanellakos',
            'Andy Arness',
            'Barry J Ratcliffe',
            'Benny Buettner',
            'Bradley Whitford',
            'Brett Wagner',
            'Clarke Devereux',
            'Embeth Davidtz',
            'George Wallace',
            'Hallie Kate Eisenberg',
            'Jay Johnston',
            'Joe Bellan',
            'John Michael Higgins',
            'Kiersten Warren',
            'Lynne Thigpen',
            'Oliver Platt',
            'Robin Williams',
            'Sam Neill',
            'Scott Trimble',
            'Scott Waugh',
            'Stephen Root',
            'Wendy Crewson',
            'Whayne Jerome-Clayton'],
 'Added': '2013-02-19',
 'Countries': ['USA', 'Germany'],
 'Description': '\nBicentennial Man: An android endeavors to become human as he gradually acquires emotions. ',
 'Director': ['Chris Columbus'],
 'Genres': ['Drama', 'Romance', 'Sci-Fi'],
 'IMDB': 'http://www.imdb.com/title/tt0182789',
 'PrimeWire': 'http://www.primewire.ag/watch-2109-Bicentennial-Man',
 'Ratings': {'IMDB': '6.8/10',
             'Metascore': '42%',
             'PrimeWire': '4.25/5',
             'RT': '37%',
             'Votes': '303'},
 'Released': '1999-12-13',
 'Runtime': '132 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2109_Bicentennial_Man_1999.jpg',
 'Title': 'Bicentennial-Man'}