{'Actors': ['Anthony Chan', 'Fat Chung', 'Kara Hui'],
 'Added': '2015-08-03',
 'Countries': [],
 'Description': '\n'
                'Rigor Mortis: A public housing tenement is plunged into a '
                'dark storm of supernatural chaos. ',
 'Director': ['Juno Mak'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Rigor-Mortis',
 'EntryURL': 'https://www.imdb.com/title/tt2771800',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Rigor-Mortis/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Rigor-Mortis/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Rigor-Mortis/info.py',
 'Genres': ['Action', 'Drama', 'Horror'],
 'IMDB': 'http://www.imdb.com/title/tt2771800',
 'PrimeWire': 'http://www.primewire.ag/watch-2744028-Rigor-Mortis',
 'Ratings': {'IMDB': '6.3/10',
             'Metascore': '53%',
             'PrimeWire': '4.08/5',
             'RT': '58%',
             'Votes': '111'},
 'Released': '2013-10-24',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2744028_Rigor_Mortis.jpg',
 'Title': 'Rigor-Mortis'}