{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2015-08-03',
 'EntryPath': 'Favorites/Movies/snapshot/Rigor-Mortis',
 'EntryURL': 'https://www.imdb.com/title/tt2771800',
 'Entry_json': 'Favorites/Movies/snapshot/Rigor-Mortis/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Rigor-Mortis/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Rigor-Mortis/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Siu-Ho Chin',
            'url': '/name/nm0157785/'},
           {'@type': 'Person', 'name': 'Kara Wai', 'url': '/name/nm0401192/'},
           {'@type': 'Person',
            'name': 'Hee Ching Paw',
            'url': '/name/nm0667978/'},
           {'@type': 'Person',
            'name': 'Anthony Chan',
            'url': '/name/nm0150796/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 5367,
                      'ratingValue': '6.3',
                      'worstRating': '1.0'}],
 'contentRating': 'Not Rated',
 'creator': [{'@type': 'Person',
              'name': 'Philip Yung',
              'url': '/name/nm3491515/'},
             {'@type': 'Person',
              'name': 'Lai-Yin Leung',
              'url': '/name/nm4183613/'},
             {'@type': 'Person', 'name': 'Juno Mak', 'url': '/name/nm1474034/'},
             {'@type': 'Organization', 'url': '/company/co0357024/'}],
 'datePublished': '2013-10-24',
 'description': 'Geung see is a movie starring Siu-Ho Chin, Kara Wai, and Hee '
                'Ching Paw. A public housing tenement is plunged into a dark '
                'storm of supernatural chaos.',
 'director': [{'@type': 'Person',
               'name': 'Juno Mak',
               'url': '/name/nm1474034/'}],
 'duration': 'PT1H43M',
 'genre': ['Action', 'Horror'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZWNkYmZiNWMtNDNjMS00ZWYzLWE4NDItOTc4MmE2ZjQ1ODgwL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'possession,haunted,shaman,supernatural fight,psychotronic film',
 'name': 'Geung see',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Rigor Mortis',
              'embedUrl': '/video/imdb/vi2877466905',
              'name': 'Rigor Mortis',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTkyNjgxMjk1OF5BMl5BanBnXkFtZTgwODM5MDQzMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTkyNjgxMjk1OF5BMl5BanBnXkFtZTgwODM5MDQzMzE@._V1_.jpg',
              'uploadDate': '2013-07-10T12:17:38Z'}],
 'url': '/title/tt2771800/'}