{'Actors': ['Adam LeFevre',
            'Bill Walters',
            'Brooke Smith',
            'Bruce McGill',
            'Byron Utley',
            'Chet Grissom',
            'Colin Powell',
            'Condoleezza Rice',
            'David Andrews',
            'David Denman',
            'David Ilku',
            'David Warshofsky',
            'Deidre Goodwin',
            'Dick Cheney',
            'Geoffrey Cantor',
            'George W Bush',
            'Harry L Seddon',
            'Iris Bahr',
            'Jane Lee',
            'Jessica Hecht',
            'Ken Sladyk',
            'Kevin Makely',
            'Kristoffer Ryan Winters',
            'Michael Goodwin',
            'Michael Kelly',
            'Naomi Watts',
            'Nasser',
            'Nicholas Sadler',
            'Noah Emmerich',
            'Norbert Leo Butz',
            'Polly Holliday',
            'Rebecca Rigg',
            'Remy Auberjonois',
            'Sam Shepard',
            'Sean Penn',
            'Thomas McCarthy',
            'Tim Griffin',
            'Tricia Munford',
            'Ty Burrell'],
 'Added': '2013-02-25',
 'Countries': ['USA', 'United Arab Emirates'],
 'Description': '\n'
                "Fair Game: Plame's status as a CIA agent was revealed by "
                'White House officials allegedly out to discredit her husband '
                'after he wrote a 2003 New York Times op-ed piece saying that '
                'the Bush administration had manipulated intelligence about '
                'weapons of mass destruction to justify the invasion of Iraq. ',
 'Director': ['Doug Liman'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game',
 'EntryURL': 'https://www.imdb.com/title/tt0977855',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game/info.py',
 'Genres': ['Action', 'Biography', 'Drama', 'Thriller'],
 'Ratings': {'IMDB': '6.8/10',
             'Metascore': '69%',
             'PrimeWire': '3.92/5',
             'RT': '79%',
             'Votes': '252'},
 'Released': '2010-05-20',
 'Runtime': '108 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1450077_Fair_Game_2010.jpg',
 'Title': 'Fair-Game'}