{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-25',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game',
 'EntryURL': 'https://www.imdb.com/title/tt0977855',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Fair-Game/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Naomi Watts',
            'url': '/name/nm0915208/'},
           {'@type': 'Person', 'name': 'Sean Penn', 'url': '/name/nm0000576/'},
           {'@type': 'Person',
            'name': 'Sonya Davison',
            'url': '/name/nm4156443/'},
           {'@type': 'Person',
            'name': 'Vanessa Chong',
            'url': '/name/nm2878323/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 45354,
                     'ratingValue': '6.8',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Jez Butterworth',
              'url': '/name/nm0125336/'},
             {'@type': 'Person',
              'name': 'John-Henry Butterworth',
              'url': '/name/nm3890871/'},
             {'@type': 'Person',
              'name': 'Joseph Wilson',
              'url': '/name/nm1468642/'},
             {'@type': 'Person',
              'name': 'Valerie Plame Wilson',
              'url': '/name/nm1976209/'},
             {'@type': 'Organization', 'url': '/company/co0120121/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'},
             {'@type': 'Organization', 'url': '/company/co0251916/'},
             {'@type': 'Organization', 'url': '/company/co0110404/'},
             {'@type': 'Organization', 'url': '/company/co0093488/'},
             {'@type': 'Organization', 'url': '/company/co0035615/'},
             {'@type': 'Organization', 'url': '/company/co0252836/'},
             {'@type': 'Organization', 'url': '/company/co0302256/'}],
 'datePublished': '2010-10-15',
 'description': 'Fair Game is a movie starring Naomi Watts, Sean Penn, and '
                'Sonya Davison. CIA operative Valerie Plame discovers her '
                'identity is allegedly leaked by the government as payback for '
                'an op-ed article her husband wrote criticizing the Bush...',
 'director': {'@type': 'Person',
              'name': 'Doug Liman',
              'url': '/name/nm0510731/'},
 'duration': 'PT1H48M',
 'genre': ['Biography', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjIyOTg1NzU0Ml5BMl5BanBnXkFtZTcwMjA2OTY5Mw@@._V1_.jpg',
 'keywords': 'cia agent,year 1972,year 1985,year 1982,year 1992',
 'name': 'Fair Game',
 'trailer': {'@type': 'VideoObject',
             'description': 'CIA operative Valerie Plame (Watts), who is '
                            'investigating the existence of Weapons of Mass '
                            'Destruction in Iraq, discovers her identity '
                            'allegedly leaked by the government as payback for '
                            'an op-ed article her husband (Penn) wrote '
                            'criticizing the Bush administration.',
             'embedUrl': '/video/imdb/vi3772581401',
             'name': 'Fair Game',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjI5MzU2NTM3M15BMl5BanBnXkFtZTgwNjc1NzYzMzE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjI5MzU2NTM3M15BMl5BanBnXkFtZTgwNjc1NzYzMzE@._V1_.jpg',
             'uploadDate': '2010-08-20T12:21:40Z'},
 'url': '/title/tt0977855/'}