{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Tomb-Raider-Ii',
 'EntryURL': 'https://rawg.io/games/tomb-raider-ii',
 'Entry_json': 'Favorites/Games/snapshot/Tomb-Raider-Ii/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Tomb-Raider-Ii/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Tomb-Raider-Ii/thumb.jpg',
 'added': 1743,
 'background_image': 'https://media.rawg.io/media/screenshots/c9c/c9c4e6d1792b5e12676819f3b57e5e26.jpeg',
 'developers': ['Core Design',
                'Sony Interactive Entertainment',
                'Square Enix',
                'Core Design Limited',
                'Westlake Interactive',
                'MacSoft Games'],
 'genres': ['Action', 'Shooter', 'Adventure', 'Platformer'],
 'name': 'Tomb Raider II',
 'platforms': ['Android',
               'iOS',
               'PlayStation',
               'PSP',
               'PC',
               'PS Vita',
               'Classic Macintosh',
               'PlayStation 3'],
 'publishers': ['Aspyr',
                'Square Enix',
                'Eidos Interactive',
                'Victor Interactive Software'],
 'released': '1997-10-31',
 'slug': 'tomb-raider-ii'}