{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Uncharted-4-A-Thiefs-End',
 'EntryURL': 'https://rawg.io/games/uncharted-4-a-thiefs-end',
 'Entry_json': 'Favorites/Games/snapshot/Uncharted-4-A-Thiefs-End/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Uncharted-4-A-Thiefs-End/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Uncharted-4-A-Thiefs-End/thumb.jpg',
 'added': 6033,
 'background_image': 'https://media.rawg.io/media/games/0ea/0ea05d4703f3af63a570471fbad79d40.jpg',
 'developers': ['Naughty Dog'],
 'genres': ['Action', 'Adventure'],
 'name': 'Uncharted 4: A Thief’s End',
 'platforms': ['PlayStation 4'],
 'publishers': ['Sony Computer Entertainment'],
 'released': '2016-05-10',
 'slug': 'uncharted-4-a-thiefs-end'}