{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Colony-Wars-Red-Sun',
 'EntryURL': 'https://rawg.io/games/colony-wars-red-sun',
 'Entry_json': 'Favorites/Games/snapshot/Colony-Wars-Red-Sun/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Colony-Wars-Red-Sun/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Colony-Wars-Red-Sun/thumb.jpg',
 'added': 6,
 'background_image': 'https://media.rawg.io/media/screenshots/b72/b7214fbd313f1e70e1ff6fb86b32fb9c.jpg',
 'developers': ['Psygnosis', 'SCE Studio Liverpool'],
 'genres': [],
 'name': 'Colony Wars: Red Sun',
 'platforms': ['PlayStation'],
 'publishers': ['Psygnosis', 'Sony Interactive Entertainment'],
 'released': '2000-05-02',
 'slug': 'colony-wars-red-sun'}