{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-01-18',
 'EntryPath': 'Favorites/TV/snapshot/Drunk-History',
 'EntryURL': 'https://www.imdb.com/title/tt2712612',
 'Entry_json': 'Favorites/TV/snapshot/Drunk-History/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Drunk-History/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Drunk-History/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Derek Waters',
            'url': '/name/nm1169531/'},
           {'@type': 'Person',
            'name': 'Bennie Arthur',
            'url': '/name/nm3286433/'},
           {'@type': 'Person',
            'name': 'Craig Cackowski',
            'url': '/name/nm1854497/'},
           {'@type': 'Person',
            'name': 'Maria Blasucci',
            'url': '/name/nm3675501/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 8483,
                     'ratingValue': '7.8',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Jeremy Konner',
              'url': '/name/nm1225956/'},
             {'@type': 'Person',
              'name': 'Derek Waters',
              'url': '/name/nm1169531/'},
             {'@type': 'Organization', 'url': '/company/co0186190/'},
             {'@type': 'Organization', 'url': '/company/co0543841/'}],
 'datePublished': '2013-07-09',
 'description': 'Drunk History is a TV series starring Derek Waters, Bennie '
                'Arthur, and Craig Cackowski. Historical reenactments by '
                'A-list talent are presented by inebriated storytellers.',
 'genre': ['Comedy', 'History'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTY5MTEzNTY4MV5BMl5BanBnXkFtZTcwNjUzMTA3OQ@@._V1_.jpg',
 'keywords': '2010s,u.s. president,president,american history,army',
 'name': 'Drunk History',
 'trailer': {'@type': 'VideoObject',
             'description': 'If you want to find out how Frankenstein came to '
                            'be or whether John F. Kennedy ever took meth, '
                            'then get excited for Season 6 of "Drunk History".',
             'embedUrl': '/video/imdb/vi120896025',
             'name': 'Season 6 Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZGE3YTRlYzEtMTJjMS00ZjY0LThiMDAtZmEyNTQxN2ZmZDI5XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZGE3YTRlYzEtMTJjMS00ZjY0LThiMDAtZmEyNTQxN2ZmZDI5XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg',
             'uploadDate': '2018-12-20T00:15:05Z'},
 'url': '/title/tt2712612/'}