{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-08-01',
 'EntryPath': 'Favorites/Movies/snapshot/Moneyball',
 'EntryURL': 'https://www.imdb.com/title/tt1210166',
 'Entry_json': 'Favorites/Movies/snapshot/Moneyball/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Moneyball/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Moneyball/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Brad Pitt', 'url': '/name/nm0000093/'},
           {'@type': 'Person',
            'name': 'Robin Wright',
            'url': '/name/nm0000705/'},
           {'@type': 'Person', 'name': 'Jonah Hill', 'url': '/name/nm1706767/'},
           {'@type': 'Person',
            'name': 'Philip Seymour Hoffman',
            'url': '/name/nm0000450/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 348229,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Steven Zaillian',
              'url': '/name/nm0001873/'},
             {'@type': 'Person',
              'name': 'Aaron Sorkin',
              'url': '/name/nm0815070/'},
             {'@type': 'Person',
              'name': 'Stan Chervin',
              'url': '/name/nm3133181/'},
             {'@type': 'Person',
              'name': 'Michael Lewis',
              'url': '/name/nm1034122/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0093765/'},
             {'@type': 'Organization', 'url': '/company/co0174505/'},
             {'@type': 'Organization', 'url': '/company/co0208135/'},
             {'@type': 'Organization', 'url': '/company/co0015447/'},
             {'@type': 'Organization', 'url': '/company/co0332023/'}],
 'datePublished': '2011-09-23',
 'description': 'Moneyball is a movie starring Brad Pitt, Robin Wright, and '
                "Jonah Hill. Oakland A's general manager Billy Beane's "
                'successful attempt to assemble a baseball team on a lean '
                'budget by employing computer-generated analysis to acquire '
                'new...',
 'director': [{'@type': 'Person',
               'name': 'Bennett Miller',
               'url': '/name/nm0587955/'}],
 'duration': 'PT2H13M',
 'genre': ['Biography', 'Drama', 'Sport'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjAxOTU3Mzc1M15BMl5BanBnXkFtZTcwMzk1ODUzNg@@._V1_.jpg',
 'keywords': 'strategy,baseball,statistics,voice over,meeting',
 'name': 'Moneyball',
 'trailer': [{'@type': 'VideoObject',
              'description': "Oakland A's general manager Billy Beane (Brad "
                             'Pitt) works to put together a baseball club on a '
                             'budget by employing computer-generated analysis '
                             'to draft his players.',
              'embedUrl': '/video/imdb/vi3229326361',
              'name': 'International Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BODM1NDMxMTI3M15BMl5BanBnXkFtZTcwMDAzODY1Ng@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BODM1NDMxMTI3M15BMl5BanBnXkFtZTcwMDAzODY1Ng@@._V1_.jpg',
              'uploadDate': '2011-09-06T07:41:44Z'}],
 'url': '/title/tt1210166/'}