{'Actors': ['Alexander Kanellakos',
            'Arliss Howard',
            'Big Spence',
            'Bob Costas',
            'Brad Pitt',
            'Brent Jennings',
            'Cabran E Chamberlain',
            'Chris Pratt',
            'Dave Bean',
            'David Alan Hodges',
            'Diane Behrens',
            'Eddie Frierson',
            'Eric Winzenried',
            'George Thomas',
            'Glenn Morshower',
            'Jack Knight',
            'Jack McGee',
            'James Shanklin',
            'Janine King',
            'John Clerkin',
            'Jonah Hill',
            'Joyce Guy',
            'Keith Middlebrook',
            'Ken Medlock',
            'Ken Rudulph',
            'Lisa Guerrero',
            'Nick Searcy',
            'Philip Seymour Hoffman',
            'Reed Diamond',
            'Robin Wright',
            'Rudolph W Giuliani',
            'Simon James',
            'Spike Jonze',
            'Stephen Bishop',
            'Takayo Fischer',
            'Tammy Blanchard',
            'Tim McCarver',
            'Vyto Ruginis',
            'Zachary Culbertson'],
 'Added': '2013-08-01',
 'Countries': ['USA'],
 'Description': '\n'
                "Moneyball: Oakland A's GM Billy Beane is handicapped with the "
                'lowest salary constraint in baseball. If he ever wants to win '
                'the World Series, Billy must find a competitive advantage. '
                'Billy is about to turn baseball on its ear when he uses '
                'statistical data to analyze and place value on the players he '
                'picks for the team. ',
 'Director': [],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Moneyball',
 'EntryURL': 'https://www.imdb.com/title/tt1210166',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Moneyball/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Moneyball/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Moneyball/info.py',
 'Genres': ['Biography', 'Drama', 'Sport'],
 'Ratings': {'IMDB': '7.6/10',
             'Metascore': '87%',
             'PrimeWire': '3.89/5',
             'RT': '94%',
             'Votes': '854'},
 'Released': '2011-09-09',
 'Runtime': '133 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1894001_Die_Kunst_zu_gewinnen_Moneyball_2011.jpg',
 'Title': 'Moneyball'}