{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Hard-Candy',
 'EntryURL': 'https://www.imdb.com/title/tt0424136',
 'Entry_json': 'Favorites/Movies/snapshot/Hard-Candy/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Hard-Candy/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Hard-Candy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Patrick Wilson',
            'url': '/name/nm0933940/'},
           {'@type': 'Person', 'name': 'Ellen Page', 'url': '/name/nm0680983/'},
           {'@type': 'Person', 'name': 'Sandra Oh', 'url': '/name/nm0644897/'},
           {'@type': 'Person',
            'name': 'Odessa Rae',
            'url': '/name/nm1230874/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 150885,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Brian Nelson',
              'url': '/name/nm0625198/'},
             {'@type': 'Organization', 'url': '/company/co0060306/'},
             {'@type': 'Organization', 'url': '/company/co0042766/'},
             {'@type': 'Organization', 'url': '/company/co0164701/'}],
 'datePublished': '2006-04-28',
 'description': 'Hard Candy is a movie starring Patrick Wilson, Ellen Page, '
                'and Sandra Oh. A teenager meets a man in order to expose him '
                'under the suspicion that he abducts underage girls.',
 'director': [{'@type': 'Person',
               'name': 'David Slade',
               'url': '/name/nm1720541/'}],
 'duration': 'PT1H44M',
 'genre': ['Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTc0MzgzNTI3N15BMl5BanBnXkFtZTcwNDk3MDIzMQ@@._V1_.jpg',
 'keywords': 'pedophilia,manipulation,missing person poster,sexual '
             'predator,online dating',
 'name': 'Hard Candy',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Lionsgate',
              'embedUrl': '/video/imdb/vi2217190937',
              'name': 'Hard Candy',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOGY1MzVlYWUtOWNkZC00YjhiLThlZTItYjFlOGY0NWVmYmJkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOGY1MzVlYWUtOWNkZC00YjhiLThlZTItYjFlOGY0NWVmYmJkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2013-05-04T04:15:05Z'}],
 'url': '/title/tt0424136/'}