{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-08-14',
 'EntryPath': 'Favorites/TV/snapshot/The-Worst-Jobs-in-History',
 'EntryURL': 'https://www.imdb.com/title/tt0423775',
 'Entry_json': 'Favorites/TV/snapshot/The-Worst-Jobs-in-History/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/The-Worst-Jobs-in-History/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/The-Worst-Jobs-in-History/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Tony Robinson',
            'url': '/name/nm0733153/'},
           {'@type': 'Person',
            'name': 'Damian Brooke',
            'url': '/name/nm3214279/'},
           {'@type': 'Person',
            'name': 'Jonathan Foyle',
            'url': '/name/nm1660043/'},
           {'@type': 'Person',
            'name': 'Marc Meltonville',
            'url': '/name/nm3010809/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 251,
                     'ratingValue': '8.3',
                     'worstRating': '1.0'},
 'creator': {'@type': 'Organization', 'url': '/company/co0133443/'},
 'datePublished': '2004-08-28',
 'description': 'The Worst Jobs in History is a TV series starring Tony '
                'Robinson, Damian Brooke, and Jonathan Foyle. Tony Robinson '
                'visits various periods in history, literally getting involved '
                'in the worst jobs our ancestors had to endure.',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BYTk0MTU1MzAtNWFlOS00ZTAwLWEwZWMtNzE2ZjUyYzcwNGI0XkEyXkFqcGdeQXVyODY5MTYzNDA@._V1_.jpg',
 'keywords': 'visit',
 'name': 'The Worst Jobs in History',
 'url': '/title/tt0423775/'}