{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Doki-Doki-Literature-Club',
 'EntryURL': 'https://rawg.io/games/doki-doki-literature-club',
 'Entry_json': 'Favorites/Games/snapshot/Doki-Doki-Literature-Club/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Doki-Doki-Literature-Club/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Doki-Doki-Literature-Club/thumb.jpg',
 'added': 2498,
 'background_image': 'https://media.rawg.io/media/games/216/2160ccf104a99fa278e4da0f86bcaf66.png',
 'developers': ['Team Salvato'],
 'genres': ['Adventure', 'Indie'],
 'name': 'Doki Doki Literature Club!',
 'platforms': ['macOS', 'PC', 'Linux'],
 'publishers': ['Team Salvato'],
 'released': '2017-09-22',
 'slug': 'doki-doki-literature-club'}