{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-12-21',
 'EntryPath': 'Favorites/TV/snapshot/Atlantis',
 'EntryURL': 'https://www.imdb.com/title/tt2705602',
 'Entry_json': 'Favorites/TV/snapshot/Atlantis/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Atlantis/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Atlantis/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Mark Addy', 'url': '/name/nm0004692/'},
           {'@type': 'Person',
            'name': 'Jack Donnelly',
            'url': '/name/nm3214649/'},
           {'@type': 'Person',
            'name': 'Robert Emms',
            'url': '/name/nm3016166/'},
           {'@type': 'Person',
            'name': 'Aiysha Hart',
            'url': '/name/nm4408716/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 10382,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'creator': [{'@type': 'Person',
              'name': 'Johnny Capps',
              'url': '/name/nm0999606/'},
             {'@type': 'Person',
              'name': 'Julian Murphy',
              'url': '/name/nm0614414/'},
             {'@type': 'Person',
              'name': 'Howard Overman',
              'url': '/name/nm1882744/'},
             {'@type': 'Organization', 'url': '/company/co0445615/'},
             {'@type': 'Organization', 'url': '/company/co0197209/'},
             {'@type': 'Organization', 'url': '/company/co0118334/'}],
 'datePublished': '2013-09-28',
 'description': 'Atlantis is a TV series starring Mark Addy, Jack Donnelly, '
                'and Robert Emms. Far from home, Jason washes up on the shores '
                'of the ancient and mysterious city of Atlantis.',
 'genre': ['Adventure', 'Drama', 'Fantasy', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BN2Y1YzAyZjgtMDI0NS00MjM0LWExNWQtYjE2NDAyOGExNzIxXkEyXkFqcGdeQXVyOTQxNzM2MjY@._V1_.jpg',
 'keywords': 'greek mythology,atlantis,hercules character,medusa '
             'character,pythagoras character',
 'name': 'Atlantis',
 'trailer': {'@type': 'VideoObject',
             'description': 'Atlantis',
             'embedUrl': '/video/imdb/vi1640348953',
             'name': 'Atlantis',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYTVhZmM1NmUtNGY4Mi00ZWFiLThmZmUtNzEwNzliNTg4MzRkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYTVhZmM1NmUtNGY4Mi00ZWFiLThmZmUtNzEwNzliNTg4MzRkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-04-06T09:01:22Z'},
 'url': '/title/tt2705602/'}