{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-28',
 'EntryPath': 'Favorites/Movies/snapshot/The-Insider',
 'EntryURL': 'https://www.imdb.com/title/tt0140352',
 'Entry_json': 'Favorites/Movies/snapshot/The-Insider/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Insider/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Insider/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Russell Crowe',
            'url': '/name/nm0000128/'},
           {'@type': 'Person', 'name': 'Al Pacino', 'url': '/name/nm0000199/'},
           {'@type': 'Person',
            'name': 'Christopher Plummer',
            'url': '/name/nm0001626/'},
           {'@type': 'Person',
            'name': 'Diane Venora',
            'url': '/name/nm0893204/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 155629,
                      'ratingValue': '7.8',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Marie Brenner',
              'url': '/name/nm0107493/'},
             {'@type': 'Person',
              'name': 'Eric Roth',
              'url': '/name/nm0744839/'},
             {'@type': 'Person',
              'name': 'Michael Mann',
              'url': '/name/nm0000520/'},
             {'@type': 'Organization', 'url': '/company/co0049348/'},
             {'@type': 'Organization', 'url': '/company/co0035930/'},
             {'@type': 'Organization', 'url': '/company/co0160787/'},
             {'@type': 'Organization', 'url': '/company/co0437457/'},
             {'@type': 'Organization', 'url': '/company/co0004216/'},
             {'@type': 'Organization', 'url': '/company/co0037280/'},
             {'@type': 'Organization', 'url': '/company/co0031181/'}],
 'datePublished': '1999-11-05',
 'description': 'The Insider is a movie starring Russell Crowe, Al Pacino, and '
                'Christopher Plummer. A research chemist comes under personal '
                'and professional attack when he decides to appear in a 60 '
                'Minutes exposé on Big Tobacco.',
 'director': [{'@type': 'Person',
               'name': 'Michael Mann',
               'url': '/name/nm0000520/'}],
 'duration': 'PT2H37M',
 'genre': ['Biography', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BODg0YjAzNDQtOGFkMi00Yzk2LTg1NzYtYTNjY2UwZTM2ZDdkL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'whistleblower,tortuous interference,1990s,tobacco,cbs news',
 'name': 'The Insider',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Touchstone Pictures',
              'embedUrl': '/video/imdb/vi1173618969',
              'name': 'The Insider',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNzIwYjI3OTUtNjE0MS00YzMyLWE0Y2QtYmI2Y2VlMmE3NjhjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNzIwYjI3OTUtNjE0MS00YzMyLWE0Y2QtYmI2Y2VlMmE3NjhjXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T16:49:00Z'}],
 'url': '/title/tt0140352/'}