{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-08-11',
 'EntryPath': 'Favorites/Movies/snapshot/Kids-for-Cash',
 'EntryURL': 'https://www.imdb.com/title/tt2925642',
 'Entry_json': 'Favorites/Movies/snapshot/Kids-for-Cash/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Kids-for-Cash/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Kids-for-Cash/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Charlie Balasavage',
            'url': '/name/nm7490679/'},
           {'@type': 'Person',
            'name': 'Joanne Balasavage',
            'url': '/name/nm7490680/'},
           {'@type': 'Person',
            'name': 'Justin Bodnar',
            'url': '/name/nm7490681/'},
           {'@type': 'Person',
            'name': 'Lisa Griffiths',
            'url': '/name/nm7490682/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 1861,
                      'ratingValue': '7.1',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Robert May',
              'url': '/name/nm1254338/'},
             {'@type': 'Organization', 'url': '/company/co0081078/'}],
 'datePublished': '2015-08-01',
 'description': 'Kids for Cash is a movie starring Charlie Balasavage, Joanne '
                'Balasavage, and Justin Bodnar. Kids For Cash is a riveting '
                'look behind the notorious judicial scandal that rocked the '
                'nation. Beyond the millions paid and high stakes...',
 'director': [{'@type': 'Person',
               'name': 'Robert May',
               'url': '/name/nm1254338/'}],
 'duration': 'PT1H42M',
 'genre': ['Documentary', 'Crime', 'Drama', 'News'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTQxNTI0OTUyMl5BMl5BanBnXkFtZTgwNDc2Mjk3MDE@._V1_.jpg',
 'keywords': 'scandal,home movie footage,archive footage,suicide,hanging judge',
 'name': 'Kids for Cash',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Kids for Cash',
              'embedUrl': '/video/imdb/vi108374041',
              'name': 'Kids for Cash',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYmJiMjcyNDUtYmU3Yi00NzE1LWE3ZDQtZjc3YjhhYzI4ZmNlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYmJiMjcyNDUtYmU3Yi00NzE1LWE3ZDQtZjc3YjhhYzI4ZmNlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2013-12-14T07:39:18Z'}],
 'url': '/title/tt2925642/'}