{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/New-Girl',
 'EntryURL': 'https://www.imdb.com/title/tt1826940',
 'Entry_json': 'Favorites/TV/snapshot/New-Girl/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/New-Girl/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/New-Girl/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Zooey Deschanel',
            'url': '/name/nm0221046/'},
           {'@type': 'Person',
            'name': 'Jake Johnson',
            'url': '/name/nm2159926/'},
           {'@type': 'Person',
            'name': 'Max Greenfield',
            'url': '/name/nm0339011/'},
           {'@type': 'Person',
            'name': 'Hannah Simone',
            'url': '/name/nm1924196/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 180136,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Elizabeth Meriwether',
              'url': '/name/nm2057975/'},
             {'@type': 'Organization', 'url': '/company/co0368370/'},
             {'@type': 'Organization', 'url': '/company/co0363589/'},
             {'@type': 'Organization', 'url': '/company/co0286257/'},
             {'@type': 'Organization', 'url': '/company/co0056447/'}],
 'datePublished': '2011-09-20',
 'description': 'New Girl is a TV series starring Zooey Deschanel, Jake '
                'Johnson, and Max Greenfield. After a bad break-up, Jess, an '
                'offbeat young woman, moves into an apartment loft with three '
                'single men. Although they find her behavior very...',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BMjA0MDc1NTk0Ml5BMl5BanBnXkFtZTgwMTk2ODA5NDM@._V1_.jpg',
 'keywords': 'apartment building,woman wears eyeglasses,babe,thin attractive '
             'woman,loft',
 'name': 'New Girl',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi1436923417',
              'name': "Season 6 New Girl--What's New",
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjkzMTU3Nzc5MF5BMl5BanBnXkFtZTgwODA0NTg5OTE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjkzMTU3Nzc5MF5BMl5BanBnXkFtZTgwODA0NTg5OTE@._V1_.jpg',
              'uploadDate': '2016-09-10T03:58:55Z'}],
 'url': '/title/tt1826940/'}