{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2012-12-02',
 'EntryPath': 'Favorites/TV/snapshot/Grand-Designs-Australia',
 'EntryURL': 'https://www.imdb.com/title/tt1677691',
 'Entry_json': 'Favorites/TV/snapshot/Grand-Designs-Australia/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Grand-Designs-Australia/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Grand-Designs-Australia/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Peter Maddison',
            'url': '/name/nm4129581/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 243,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0035637/'}],
 'datePublished': '2010-10-21',
 'description': 'Grand Designs Australia is a TV series starring Peter '
                'Maddison. Each episode is about the host visiting people who '
                'have a dream to build a house and how they bring the build to '
                'fruition. We see their trials and tribulations along...',
 'genre': ['Documentary', 'Reality-TV'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYTUzYTM3ZGMtMzljMC00Mjg1LWFmZTMtYjllYjg4OGIxZjJhXkEyXkFqcGdeQXVyNTUxNDYxNzM@._V1_.jpg',
 'keywords': 'lifestyle',
 'name': 'Grand Designs Australia',
 'url': '/title/tt1677691/'}