{'Actors': ['Al Goto',
            'Chad Stahelski',
            'Chi Ma',
            'Chia Yung Liu',
            'Chun Lei',
            'Fei Lung',
            'Fu Chiang Chi',
            'Hiro Koda',
            'Ho Wu',
            'Hui Lou Chen',
            'James Wing Woo',
            'Jen Sung Outerbridge',
            'Jennifer Tung',
            'John Koyama',
            'Leo Lee',
            'Lo Ming',
            'Marcus Young',
            'Philip Kwok',
            'Philip Tan',
            'Ron Yuan',
            'Simon Rhee',
            'Steve Oedekerk',
            'Sung Chao Yu',
            'Tad Horino',
            'Will Leong',
            'Woon Young Park',
            'Yu Wang'],
 'Added': '2013-02-23',
 'Countries': ['USA', 'Hong Kong'],
 'Description': '\n'
                'Kung Pow: Enter the Fist: Kung Pow: Enter the Fist is a movie '
                'within a movie, created to spoof the martial arts genre. '
                'Writer/director... ',
 'Director': ['Steve Oedekerk'],
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist',
 'EntryURL': 'https://www.imdb.com/title/tt0240468',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist/info.py',
 'Genres': ['Action', 'Comedy'],
 'Ratings': {'IMDB': '6.2/10',
             'Metascore': '14%',
             'PrimeWire': '3.78/5',
             'RT': '11%',
             'Votes': '332'},
 'Released': '2002-01-25',
 'Runtime': '81 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2094_Kung_Pow_Enter_the_Fist_2002.jpg',
 'Title': 'Kung-Pow-Enter-the-Fist'}