{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist',
 'EntryURL': 'https://www.imdb.com/title/tt0240468',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Kung-Pow-Enter-the-Fist/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Steve Oedekerk',
            'url': '/name/nm0644203/'},
           {'@type': 'Person', 'name': 'Fei Lung', 'url': '/name/nm0526694/'},
           {'@type': 'Person', 'name': 'Leo Lee', 'url': '/name/nm0497735/'},
           {'@type': 'Person',
            'name': 'Ling-Ling Hsieh',
            'url': '/name/nm1119886/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 42758,
                     'ratingValue': '6.2',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Steve Oedekerk',
              'url': '/name/nm0644203/'},
             {'@type': 'Organization', 'url': '/company/co0000756/'},
             {'@type': 'Organization', 'url': '/company/co0009845/'},
             {'@type': 'Organization', 'url': '/company/co0179259/'}],
 'datePublished': '2002-01-25',
 'description': 'Kung Pow: Enter the Fist is a movie starring Steve Oedekerk, '
                'Fei Lung, and Leo Lee. A rough-around-the-edges martial arts '
                "master seeks revenge for his parent's death.",
 'director': {'@type': 'Person',
              'name': 'Steve Oedekerk',
              'url': '/name/nm0644203/'},
 'duration': 'PT1H21M',
 'genre': ['Action', 'Comedy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMGQxZDEwZDctMjNkMi00YmIxLTgyN2MtYmJhYjEzZGY0NjljXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'kung fu,chosen one,martial arts,intentionally bad,hero',
 'name': 'Kung Pow: Enter the Fist',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from 20th Century Fox Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi429195545',
             'name': 'Kung Pow: Enter the Fist',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDQyZmVmYzgtZDQ2OS00MGMxLWE3ZjgtNjJlZjdhYmMxMTE2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDQyZmVmYzgtZDQ2OS00MGMxLWE3ZjgtNjJlZjdhYmMxMTE2XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:56:35Z'},
 'url': '/title/tt0240468/'}