{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-25',
 'EntryPath': 'Favorites/Movies/snapshot/Between-the-Folds',
 'EntryURL': 'https://www.imdb.com/title/tt1253565',
 'Entry_json': 'Favorites/Movies/snapshot/Between-the-Folds/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Between-the-Folds/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Between-the-Folds/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Erik D. Demaine',
            'url': '/name/nm3060130/'},
           {'@type': 'Person',
            'name': 'Martin L. Demaine',
            'url': '/name/nm3059795/'},
           {'@type': 'Person',
            'name': 'Vincent Floderer',
            'url': '/name/nm3060321/'},
           {'@type': 'Person',
            'name': 'Miri Golan',
            'url': '/name/nm3059221/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 808,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'G',
 'creator': [{'@type': 'Person',
              'name': 'Vanessa Gould',
              'url': '/name/nm3059129/'},
             {'@type': 'Organization', 'url': '/company/co0241648/'}],
 'datePublished': '2008-05-31',
 'description': 'Between the Folds is a movie starring Erik D. Demaine, Martin '
                'L. Demaine, and Vincent Floderer. Depicts a cast of fine '
                'artists and eccentric scientists (from MIT and NASA) who have '
                'devoted their lives to the unlikely medium of...',
 'director': [{'@type': 'Person',
               'name': 'Vanessa Gould',
               'url': '/name/nm3059129/'}],
 'duration': 'PT56M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTM5MzYxNzg0MV5BMl5BanBnXkFtZTcwNzAwMjM5MQ@@._V1_.jpg',
 'keywords': 'scientist,paper,origami,art,artist',
 'name': 'Between the Folds',
 'url': '/title/tt1253565/'}