{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Ultima-Iv-Quest-Of-The-Avatar',
 'EntryURL': 'https://rawg.io/games/ultima-iv-quest-of-the-avatar',
 'Entry_json': 'Favorites/Games/snapshot/Ultima-Iv-Quest-Of-The-Avatar/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Ultima-Iv-Quest-Of-The-Avatar/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Ultima-Iv-Quest-Of-The-Avatar/thumb.jpg',
 'added': 993,
 'background_image': 'https://media.rawg.io/media/screenshots/773/7730495e8fc0fe7e1e747cb9449399ac.jpeg',
 'developers': ['Elite Systems Ltd', 'Origin Systems'],
 'genres': ['Adventure', 'RPG'],
 'name': 'Ultima IV: Quest of the Avatar',
 'platforms': ['PC',
               'macOS',
               'iOS',
               'Atari ST',
               'SEGA Master System',
               'Classic Macintosh',
               'Apple II',
               'Atari 8-bit',
               'Commodore / Amiga',
               'NES'],
 'publishers': ['Electronic Arts',
                'Elite Systems Ltd',
                'SEGA',
                'Origin Systems',
                'Pony Canyon',
                'Fujisankei Communications International'],
 'released': '1985-09-16',
 'slug': 'ultima-iv-quest-of-the-avatar'}