<?php
$infoArray = array('Actors' => array('Alicia Vikander',
            'Bradley Cooper',
            'Daniel Br\xc3\xbchl',
            'Emma Thompson',
            'Matthew Rhys',
            'Omar Sy',
            'Riccardo Scamarcio',
            'Sarah Greene',
            'Sienna Miller',
            'Uma Thurman'),
 'Added' => '2016-02-22',
 'Countries' => array('USA'),
 'Description' => '\nBurnt: Adam Jones (Bradley Cooper) is a Chef who destroyed his career with drugs and diva behavior. He cleans up and returns to London, determined to redeem himself by spearheading a top restaurant that can gain three Michelin stars. ',
 'Director' => array('John Wells'),
 'Genres' => array('Comedy', 'Drama'),
 'IMDB' => 'http://www.imdb.com/title/tt2503944',
 'PrimeWire' => 'http://www.primewire.ag/watch-2770598-Burnt',
 'Ratings' => array('IMDB' => 'N/A',
             'Metascore' => 'N/A',
             'PrimeWire' => '3.61/5',
             'RT' => 'N/A',
             'Votes' => '808'),
 'Released' => '2015-10-30',
 'Runtime' => '100 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2770598_Burnt_2015.jpg',
 'Title' => 'Burnt');
?>