{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2016-02-22',
 'EntryPath': 'Favorites/Movies/snapshot/Burnt',
 'EntryURL': 'https://www.imdb.com/title/tt2503944',
 'Entry_json': 'Favorites/Movies/snapshot/Burnt/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Burnt/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Burnt/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bradley Cooper',
            'url': '/name/nm0177896/'},
           {'@type': 'Person',
            'name': 'Sienna Miller',
            'url': '/name/nm1092227/'},
           {'@type': 'Person',
            'name': 'Daniel Brühl',
            'url': '/name/nm0117709/'},
           {'@type': 'Person',
            'name': 'Riccardo Scamarcio',
            'url': '/name/nm1249052/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 102356,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Steven Knight',
              'url': '/name/nm1140275/'},
             {'@type': 'Person',
              'name': 'Michael Kalesniko',
              'url': '/name/nm0435701/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0118437/'},
             {'@type': 'Organization', 'url': '/company/co0278336/'}],
 'datePublished': '2015-10-22',
 'description': 'Burnt is a movie starring Bradley Cooper, Sienna Miller, and '
                'Daniel Brühl. Adam Jones (Bradley Cooper) is a chef who '
                'destroyed his career with drugs and diva behavior. He cleans '
                'up and returns to London, determined to redeem himself...',
 'director': {'@type': 'Person',
              'name': 'John Wells',
              'url': '/name/nm0920274/'},
 'duration': 'PT1H41M',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNjEzNTk2OTEwNF5BMl5BanBnXkFtZTgwNzExMTg0NjE@._V1_.jpg',
 'keywords': 'abusive boss,chef,restaurant,superiority complex,workplace '
             'bullying',
 'name': 'Burnt',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer for Burnt',
             'embedUrl': '/video/imdb/vi2849159193',
             'name': 'Burnt',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOWU3MjY1OWQtNTgxYS00NjExLTk5MzAtMzUwMWViNTZhNDdlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOWU3MjY1OWQtNTgxYS00NjExLTk5MzAtMzUwMWViNTZhNDdlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2018-02-01T17:04:39Z'},
 'url': '/title/tt2503944/'}