{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Lucifer',
 'EntryURL': 'https://www.imdb.com/title/tt4052886',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Lucifer/entry.json',
 'Entry_php': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Lucifer/info.php',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/TV/snapshot/Lucifer/info.py',
 'Title': 'Lucifer',
 'actor': [{'@type': 'Person', 'name': 'Tom Ellis', 'url': '/name/nm0255124/'},
           {'@type': 'Person',
            'name': 'Lauren German',
            'url': '/name/nm0314514/'},
           {'@type': 'Person',
            'name': 'Kevin Alejandro',
            'url': '/name/nm1204760/'},
           {'@type': 'Person',
            'name': 'Lesley-Ann Brandt',
            'url': '/name/nm2788229/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 195390,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Tom Kapinos',
              'url': '/name/nm1093513/'},
             {'@type': 'Organization', 'url': '/company/co0225724/'},
             {'@type': 'Organization', 'url': '/company/co0283444/'},
             {'@type': 'Organization', 'url': '/company/co0039979/'},
             {'@type': 'Organization', 'url': '/company/co0084207/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'}],
 'datePublished': '2015-05-08',
 'description': 'Lucifer is a TV series starring Tom Ellis, Lauren German, and '
                "Kevin Alejandro. Lucifer Morningstar has decided he's had "
                'enough of being the dutiful servant in Hell and decides to '
                'spend some time on Earth to better understand...',
 'genre': ['Crime', 'Drama', 'Fantasy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZTA2NTBkYWUtMzM4Zi00YzhlLTk4NWItY2U1ODczNDMyNDAzXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg',
 'keywords': 'devil,female police detective,fallen angel,the devil,lapd',
 'name': 'Lucifer',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'pmelrose524'},
            'dateCreated': '2018-05-14',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt4052886/'},
            'name': '#SaveLucifer #PickUpLucifer',
            'reviewBody': '#SaveLucifer #PickUpLucifer\n'
                          '\n'
                          'One of the best shows around. It deserves to '
                          'continue right where it left off.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '10',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Reeling from the aftermath of Chloe seeing his '
                            'devil face, Lucifer faces a new challenge: Eve, '
                            'the original sinner herself, is back. Does she '
                            'want revenge for when he tempted her out of Eden '
                            'oh so many years ago... or something else '
                            'entirely?',
             'embedUrl': '/video/imdb/vi160283673',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTdmOWM4NDEtZGM2MS00YTUxLTgyYTEtYzViNjhhODdjY2JjXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTdmOWM4NDEtZGM2MS00YTUxLTgyYTEtYzViNjhhODdjY2JjXkEyXkFqcGdeQW1yb3NzZXI@._V1_.jpg',
             'uploadDate': '2019-04-25T14:30:35Z'},
 'url': '/title/tt4052886/'}