{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Lucifer',
 'EntryURL': 'https://www.imdb.com/title/tt4052886',
 'Entry_json': 'Favorites/TV/snapshot/Lucifer/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Lucifer/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Lucifer/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Tom Ellis', 'url': '/name/nm0255124/'},
           {'@type': 'Person',
            'name': 'Lauren German',
            'url': '/name/nm0314514/'},
           {'@type': 'Person',
            'name': 'Kevin Alejandro',
            'url': '/name/nm1204760/'},
           {'@type': 'Person',
            'name': 'Lesley-Ann Brandt',
            'url': '/name/nm2788229/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 200757,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Person',
              'name': 'Tom Kapinos',
              'url': '/name/nm1093513/'},
             {'@type': 'Organization', 'url': '/company/co0225724/'},
             {'@type': 'Organization', 'url': '/company/co0283444/'},
             {'@type': 'Organization', 'url': '/company/co0039979/'},
             {'@type': 'Organization', 'url': '/company/co0084207/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'}],
 'datePublished': '2016-01-25',
 'description': 'Lucifer is a TV series starring Tom Ellis, Lauren German, and '
                "Kevin Alejandro. Lucifer Morningstar has decided he's had "
                'enough of being the dutiful servant in Hell and decides to '
                'spend some time on Earth to better understand...',
 'genre': ['Crime', 'Drama', 'Fantasy'],
 'image': 'https://m.media-amazon.com/images/M/MV5BNzY1YjIxOGMtOTAyZC00YTcyLWFhMzQtZTJkYTljYzU0MGRlXkEyXkFqcGdeQXVyMTAwMzM3NDI3._V1_.jpg',
 'keywords': 'devil,female police detective,fallen angel,the devil,lapd',
 'name': 'Lucifer',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Lucifer makes a tumultuous return, Chloe '
                             'rethinks romance, Ella finally finds a nice guy, '
                             'and Amenadiel adjusts to the whole fatherhood '
                             'thing.',
              'embedUrl': '/video/imdb/vi319602201',
              'name': 'Season 5 Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMzZiNzVhOGItNTgwYS00NjljLWI2NjQtNzVlMjA1OTA5NDI4XkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMzZiNzVhOGItNTgwYS00NjljLWI2NjQtNzVlMjA1OTA5NDI4XkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg',
              'uploadDate': '2020-07-14T14:56:33Z'}],
 'url': '/title/tt4052886/'}