{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/TV/snapshot/Shameless',
 'EntryURL': 'https://www.imdb.com/title/tt1586680',
 'Entry_json': 'Favorites/TV/snapshot/Shameless/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Shameless/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Shameless/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Emmy Rossum',
            'url': '/name/nm0002536/'},
           {'@type': 'Person',
            'name': 'William H. Macy',
            'url': '/name/nm0000513/'},
           {'@type': 'Person',
            'name': 'Ethan Cutkosky',
            'url': '/name/nm3103119/'},
           {'@type': 'Person',
            'name': 'Jeremy Allen White',
            'url': '/name/nm2087739/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 190215,
                     'ratingValue': '8.6',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Paul Abbott',
              'url': '/name/nm0008036/'},
             {'@type': 'Person',
              'name': 'John Wells',
              'url': '/name/nm0920274/'},
             {'@type': 'Organization', 'url': '/company/co0265986/'},
             {'@type': 'Organization', 'url': '/company/co0037310/'},
             {'@type': 'Organization', 'url': '/company/co0005035/'},
             {'@type': 'Organization', 'url': '/company/co0052980/'},
             {'@type': 'Organization', 'url': '/company/co0332089/'}],
 'datePublished': '2011-01-09',
 'description': 'Shameless is a TV series starring Emmy Rossum, William H. '
                'Macy, and Ethan Cutkosky. A scrappy, feisty, fiercely loyal '
                'Chicago family makes no apologies.',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYzFmODNkNDMtOTgzMy00NzQ1LWEwNDItNzU1MmYyYThhYzUwXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_.jpg',
 'keywords': 'gay relationship,alcoholic father,poor family,brother sister '
             'relationship,gay brother',
 'name': 'Shameless',
 'trailer': {'@type': 'VideoObject',
             'description': 'Catch the season premiere of Shameless on '
                            'November 10 at 9/8c. Starring William H. Macy.',
             'embedUrl': '/video/imdb/vi2660286233',
             'name': 'Season 10 Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZmJlMDVmNmItOGEzNy00ZjhlLWFlODItZGEwNTBlMDczOWI0XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZmJlMDVmNmItOGEzNy00ZjhlLWFlODItZGEwNTBlMDczOWI0XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-09-15T16:20:15Z'},
 'url': '/title/tt1586680/'}