{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Pi',
 'EntryURL': 'https://www.imdb.com/title/tt0138704',
 'Entry_json': 'Favorites/Movies/snapshot/Pi/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Pi/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Pi/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Sean Gullette',
            'url': '/name/nm0347797/'},
           {'@type': 'Person',
            'name': 'Mark Margolis',
            'url': '/name/nm0546797/'},
           {'@type': 'Person',
            'name': 'Ben Shenkman',
            'url': '/name/nm0791570/'},
           {'@type': 'Person',
            'name': 'Pamela Hart',
            'url': '/name/nm0366466/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 167163,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Person',
              'name': 'Sean Gullette',
              'url': '/name/nm0347797/'},
             {'@type': 'Person',
              'name': 'Eric Watson',
              'url': '/name/nm0914615/'},
             {'@type': 'Person',
              'name': 'Darren Aronofsky',
              'url': '/name/nm0004716/'},
             {'@type': 'Person',
              'name': 'Sean Gullette',
              'url': '/name/nm0347797/'},
             {'@type': 'Organization', 'url': '/company/co0145522/'},
             {'@type': 'Organization', 'url': '/company/co0076907/'},
             {'@type': 'Organization', 'url': '/company/co0145523/'},
             {'@type': 'Organization', 'url': '/company/co0062935/'}],
 'datePublished': '1998-07-10',
 'description': 'Pi is a movie starring Sean Gullette, Mark Margolis, and Ben '
                'Shenkman. A paranoid mathematician searches for a key number '
                'that will unlock the universal patterns found in nature.',
 'director': [{'@type': 'Person',
               'name': 'Darren Aronofsky',
               'url': '/name/nm0004716/'}],
 'duration': 'PT1H24M',
 'genre': ['Drama', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjYzNTA4YzItYTQ2Yy00NDQwLWI2OGItN2JmMjZhZTVhMzI5L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
 'keywords': 'cult film,the letter pi,go,mathematician,headache',
 'name': 'Pi',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Artisan',
              'embedUrl': '/video/imdb/vi1904214297',
              'name': 'Pi',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTZkNWU3YjgtZTg4Ni00MzA1LThkODItZDMyZmNkODlmOWYwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTZkNWU3YjgtZTg4Ni00MzA1LThkODItZDMyZmNkODlmOWYwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T15:39:28Z'}],
 'url': '/title/tt0138704/'}