{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/The-Adjustment-Bureau',
 'EntryURL': 'https://www.imdb.com/title/tt1385826',
 'Entry_json': 'Favorites/Movies/snapshot/The-Adjustment-Bureau/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Adjustment-Bureau/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Adjustment-Bureau/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Matt Damon', 'url': '/name/nm0000354/'},
           {'@type': 'Person',
            'name': 'Emily Blunt',
            'url': '/name/nm1289434/'},
           {'@type': 'Person',
            'name': 'Lisa Thoreson',
            'url': '/name/nm2564974/'},
           {'@type': 'Person',
            'name': 'Florence Kastriner',
            'url': '/name/nm1505460/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 239188,
                      'ratingValue': '7.0',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'George Nolfi',
              'url': '/name/nm1079776/'},
             {'@type': 'Person',
              'name': 'Philip K. Dick',
              'url': '/name/nm0001140/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0194736/'},
             {'@type': 'Organization', 'url': '/company/co0177587/'},
             {'@type': 'Organization', 'url': '/company/co0185913/'}],
 'datePublished': '2011-03-03',
 'description': 'The Adjustment Bureau is a movie starring Matt Damon, Emily '
                'Blunt, and Lisa Thoreson. The affair between a politician and '
                'a contemporary dancer is affected by mysterious forces '
                'keeping the lovers apart.',
 'director': [{'@type': 'Person',
               'name': 'George Nolfi',
               'url': '/name/nm1079776/'}],
 'duration': 'PT1H46M',
 'genre': ['Romance', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMzc0ZDcwZTYtOWUzZi00NDE4LWI4NjgtMWVjZTUyYTA2ZTNhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
 'keywords': 'fate,teleportation,love at first sight,free will,political '
             'superpower',
 'name': 'The Adjustment Bureau',
 'trailer': [{'@type': 'VideoObject',
              'description': 'The Adjustment Bureau -- Super Bowl Spot',
              'embedUrl': '/video/imdb/vi2215418393',
              'name': 'The Adjustment Bureau -- Super Bowl Spot',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTY0MTE3ODMyOV5BMl5BanBnXkFtZTgwNDE4MTQyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTY0MTE3ODMyOV5BMl5BanBnXkFtZTgwNDE4MTQyMzE@._V1_.jpg',
              'uploadDate': '2011-02-05T17:20:12Z'}],
 'url': '/title/tt1385826/'}