{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-12-14',
 'EntryPath': 'Favorites/TV/snapshot/Breakthrough',
 'EntryURL': 'https://www.imdb.com/title/tt4622776',
 'Entry_json': 'Favorites/TV/snapshot/Breakthrough/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Breakthrough/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Breakthrough/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Mike Colter',
            'url': '/name/nm1591496/'},
           {'@type': 'Person',
            'name': 'Sheila Vand',
            'url': '/name/nm2611074/'},
           {'@type': 'Person',
            'name': 'Steven Austad',
            'url': '/name/nm7790375/'},
           {'@type': 'Person',
            'name': 'Nir Barzilai',
            'url': '/name/nm3877017/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 250,
                      'ratingValue': '7.6',
                      'worstRating': '1.0'}],
 'creator': [{'@type': 'Organization', 'url': '/company/co0003687/'},
             {'@type': 'Organization', 'url': '/company/co0139461/'},
             {'@type': 'Organization', 'url': '/company/co0108336/'},
             {'@type': 'Organization', 'url': '/company/co0017595/'}],
 'datePublished': '2015-11-01',
 'description': 'Breakthrough is a TV series starring Mike Colter, Sheila '
                'Vand, and Steven Austad. An anthology of leading scientists '
                'and how their cutting-edge innovations and advancements will '
                'change our lives in the immediate future and beyond....',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BMTkwNzY0OTgwMl5BMl5BanBnXkFtZTgwNjA2OTgxNzE@._V1_.jpg',
 'name': 'Breakthrough',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Official trailer for Breakthrough from Nat Geo.',
              'embedUrl': '/video/imdb/vi3163664921',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjQzMTA3NDYzNl5BMl5BanBnXkFtZTgwNjY2OTgxNzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjQzMTA3NDYzNl5BMl5BanBnXkFtZTgwNjY2OTgxNzE@._V1_.jpg',
              'uploadDate': '2015-11-04T08:51:15Z'}],
 'url': '/title/tt4622776/'}