<?php
$infoArray = array('Actors' => array('Bob Stephenson',
            'Bob Yerkes',
            'Brian Cox',
            'Cara Seymour',
            'Catherine Keener',
            'Chris Cooper',
            'Curt Clendenin',
            'Curtis Hanson',
            'Doug Jones',
            'Gary Farmer',
            'Gregory Itzin',
            'Jay Tavare',
            'Jim Beaver',
            'John Cusack',
            'John Malkovich',
            'Judy Greer',
            'Maggie Gyllenhaal',
            'Meryl Streep',
            'Nancy Lenehan',
            'Nicolas Cage',
            'Peter Jason',
            'Rheagan Wallace',
            'Ron Livingston',
            'Sandra Lee Gimpel',
            'Spike Jonze',
            'Stephen Tobolowsky',
            'Tilda Swinton',
            'Tony Collucci'),
 'Added' => '2013-02-19',
 'Countries' => array('USA'),
 'Description' => '\nAdaptation.: A lovelorn screenwriter turns to his less talented twin brother for help when his efforts to adapt a non-fiction book go nowhere. ',
 'Director' => array('Spike Jonze'),
 'Genres' => array('Drama', 'Comedy'),
 'IMDB' => 'http://www.imdb.com/title/tt0268126',
 'PrimeWire' => 'http://www.primewire.ag/watch-4525-Adaptation',
 'Ratings' => array('IMDB' => '7.7/10',
             'Metascore' => '83%',
             'PrimeWire' => '3.59/5',
             'RT' => '91%',
             'Votes' => '109'),
 'Released' => '2002-12-06',
 'Runtime' => '114 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/4525_Adaptation_2002.jpg',
 'Title' => 'Adaptation');
?>