{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Adaptation',
 'EntryURL': 'https://www.imdb.com/title/tt0268126',
 'Entry_json': 'Favorites/Movies/snapshot/Adaptation/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Adaptation/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Adaptation/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Nicolas Cage',
            'url': '/name/nm0000115/'},
           {'@type': 'Person',
            'name': 'Meryl Streep',
            'url': '/name/nm0000658/'},
           {'@type': 'Person',
            'name': 'Chris Cooper',
            'url': '/name/nm0177933/'},
           {'@type': 'Person',
            'name': 'Tilda Swinton',
            'url': '/name/nm0842770/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 172027,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Susan Orlean',
              'url': '/name/nm0650036/'},
             {'@type': 'Person',
              'name': 'Charlie Kaufman',
              'url': '/name/nm0442109/'},
             {'@type': 'Organization', 'url': '/company/co0058058/'},
             {'@type': 'Organization', 'url': '/company/co0093046/'},
             {'@type': 'Organization', 'url': '/company/co0007554/'},
             {'@type': 'Organization', 'url': '/company/co0040675/'},
             {'@type': 'Organization', 'url': '/company/co0046935/'},
             {'@type': 'Organization', 'url': '/company/co0058765/'}],
 'datePublished': '2002-12-26',
 'description': 'Adaptation. is a movie starring Nicolas Cage, Meryl Streep, '
                'and Chris Cooper. A lovelorn screenwriter becomes desperate '
                "as he tries and fails to adapt 'The Orchid Thief' by Susan "
                'Orlean for the screen.',
 'director': [{'@type': 'Person',
               'name': 'Spike Jonze',
               'url': '/name/nm0005069/'}],
 'duration': 'PT1H55M',
 'genre': ['Comedy', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZjIwZWU0ZDItNzBlNS00MDIwLWFlZjctZTJjODdjZWYxNzczL2ltYWdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'magical realism,metafiction,voice over inner thoughts,meta '
             'film,loner',
 'name': 'Adaptation.',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer 2',
              'embedUrl': '/video/imdb/vi1706934041',
              'name': 'Adaptation.',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWZlNjBhNjUtN2QwZS00YWIyLTg0ZWUtNWFmMWRmMzBjYmJjXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWZlNjBhNjUtN2QwZS00YWIyLTg0ZWUtNWFmMWRmMzBjYmJjXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg',
              'uploadDate': '2019-09-01T17:05:37Z'}],
 'url': '/title/tt0268126/'}