{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Conspiracy',
 'EntryURL': 'https://www.imdb.com/title/tt0266425',
 'Entry_json': 'Favorites/Movies/snapshot/Conspiracy/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Conspiracy/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Conspiracy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Kenneth Branagh',
            'url': '/name/nm0000110/'},
           {'@type': 'Person',
            'name': 'Clare Bullus',
            'url': '/name/nm0120206/'},
           {'@type': 'Person',
            'name': 'Stanley Tucci',
            'url': '/name/nm0001804/'},
           {'@type': 'Person',
            'name': 'Simon Markey',
            'url': '/name/nm0548412/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 17955,
                      'ratingValue': '7.7',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Loring Mandel',
              'url': '/name/nm0541662/'},
             {'@type': 'Organization', 'url': '/company/co0005861/'},
             {'@type': 'Organization', 'url': '/company/co0043107/'}],
 'datePublished': '2001-05-19',
 'description': 'Conspiracy is a TV movie starring Kenneth Branagh, Clare '
                'Bullus, and Stanley Tucci. At the Wannsee Conference on '
                'January 20, 1942, senior Nazi officials meet to determine the '
                'manner in which the so-called "Final Solution to the...',
 'director': [{'@type': 'Person',
               'name': 'Frank Pierson',
               'url': '/name/nm0682757/'}],
 'duration': 'PT1H36M',
 'genre': ['Biography', 'Drama', 'History', 'War'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU3MDYxNjYxM15BMl5BanBnXkFtZTYwOTc2ODY5._V1_.jpg',
 'keywords': 'holocaust,nazis,final solution,conference,ss',
 'name': 'Conspiracy',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from HBO Home Video',
              'embedUrl': '/video/imdb/vi2042560793',
              'name': 'Conspiracy',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNmM2YmQ1OTctZjhhZC00MGQ1LWE5ZmUtN2NmMzZkMDY2YzMwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNmM2YmQ1OTctZjhhZC00MGQ1LWE5ZmUtN2NmMzZkMDY2YzMwXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T13:32:28Z'}],
 'url': '/title/tt0266425/'}