{'Actors': ['Richard Rhodes'],
 'Added': '2014-02-02',
 'Countries': [],
 'Description': "\nPandoras Promise: A feature-length documentary about the history and future of nuclear power. The film explores how and why mankind's most feared and controversial technological discovery is now passionately embraced by many of those who once led the charge against it. Operating as history, cultural meditation and contemporary exploration, PANDORA'S PROMISE aims to inspire a serious and realistic debate over what is without question the most important question of our time: how do we continue to power modern civilization without destroying it? ",
 'Director': ['Robert Stone'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1992193',
 'PrimeWire': 'http://www.primewire.ag/watch-2744143-Pandoras-Promise',
 'Ratings': {'IMDB': '7.3/10',
             'Metascore': '54%',
             'PrimeWire': '3.58/5',
             'RT': '64%',
             'Votes': '26'},
 'Released': '2013-11-25',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2744143_Pandoras_Promise.jpg',
 'Title': 'Pandoras-Promise'}