{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Ecco-The-Dolphin-1992',
 'EntryURL': 'https://rawg.io/games/ecco-the-dolphin-1992',
 'Entry_json': 'Favorites/Games/snapshot/Ecco-The-Dolphin-1992/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Ecco-The-Dolphin-1992/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Ecco-The-Dolphin-1992/thumb.jpg',
 'added': 81,
 'background_image': 'https://media.rawg.io/media/screenshots/64a/64af1ca2f537454750e658de96422e2f.jpg',
 'developers': ['Appaloosa Interactive', 'Novotrade International'],
 'genres': [],
 'name': 'Ecco the Dolphin (1992)',
 'platforms': ['Nintendo 3DS',
               'iOS',
               'SEGA Master System',
               'Wii',
               'Game Gear',
               'PC',
               'SEGA CD',
               'Xbox 360',
               'Genesis'],
 'publishers': ['SEGA'],
 'released': '1992-07-31',
 'slug': 'ecco-the-dolphin-1992'}