{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Fallout-A-Post-Nuclear-Role-Playing-Game',
 'EntryURL': 'https://rawg.io/games/fallout-a-post-nuclear-role-playing-game',
 'Entry_json': 'Favorites/Games/snapshot/Fallout-A-Post-Nuclear-Role-Playing-Game/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Fallout-A-Post-Nuclear-Role-Playing-Game/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Fallout-A-Post-Nuclear-Role-Playing-Game/thumb.jpg',
 'added': 4804,
 'background_image': 'https://media.rawg.io/media/games/14a/14a83c56ff668baaced6e8c8704b6391.jpg',
 'developers': ['Interplay Entertainment'],
 'genres': ['RPG'],
 'name': 'Fallout: A Post Nuclear Role Playing Game',
 'platforms': ['PC', 'macOS', 'Classic Macintosh'],
 'publishers': ['Bethesda Softworks', 'Interplay Productions'],
 'released': '1997-09-30',
 'slug': 'fallout-a-post-nuclear-role-playing-game'}