{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Beneath-A-Steel-Sky',
 'EntryURL': 'https://rawg.io/games/beneath-a-steel-sky',
 'Entry_json': 'Favorites/Games/snapshot/Beneath-A-Steel-Sky/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Beneath-A-Steel-Sky/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Beneath-A-Steel-Sky/thumb.jpg',
 'added': 1112,
 'background_image': 'https://media.rawg.io/media/screenshots/f6b/f6b3338889ec877c9d3d89fc4f665152.jpg',
 'developers': ['Revolution Software'],
 'genres': ['Adventure'],
 'name': 'Beneath a Steel Sky',
 'platforms': ['PC',
               'macOS',
               'Linux',
               'Commodore / Amiga',
               'iOS',
               'Classic Macintosh'],
 'publishers': ['Revolution Software',
                'Virgin Interactive Entertainment',
                'Virgin Interactive'],
 'released': '1994-04-10',
 'slug': 'beneath-a-steel-sky'}