{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2015-07-27',
 'EntryPath': 'Favorites/TV/snapshot/Jeopardy',
 'EntryURL': 'https://www.imdb.com/title/tt0159881',
 'Entry_json': 'Favorites/TV/snapshot/Jeopardy/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Jeopardy/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Jeopardy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Alex Trebek',
            'url': '/name/nm0871618/'},
           {'@type': 'Person',
            'name': 'Johnny Gilbert',
            'url': '/name/nm0318114/'},
           {'@type': 'Person',
            'name': 'Jimmy McGuire',
            'url': '/name/nm1177149/'},
           {'@type': 'Person',
            'name': 'Sarah Whitcomb Foss',
            'url': '/name/nm1176865/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 5602,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'contentRating': 'TV-G',
 'creator': [{'@type': 'Person',
              'name': 'Merv Griffin',
              'url': '/name/nm0341311/'},
             {'@type': 'Organization', 'url': '/company/co0074221/'},
             {'@type': 'Organization', 'url': '/company/co0108288/'},
             {'@type': 'Organization', 'url': '/company/co0093384/'},
             {'@type': 'Organization', 'url': '/company/co0086397/'}],
 'datePublished': '1984-09-10',
 'description': 'Jeopardy! is a TV series starring Alex Trebek, Johnny '
                'Gilbert, and Jimmy McGuire. A returning champion and two '
                'challengers test their buzzer skills and their knowledge in a '
                'wide range of academic and popular categories.',
 'genre': 'Game-Show',
 'image': 'https://m.media-amazon.com/images/M/MV5BYmJjM2FhYTEtMjliYS00OThhLTk1NDgtNDYyNDJjNTNjY2NiXkEyXkFqcGdeQXVyODg3NDc1OTE@._V1_.jpg',
 'keywords': 'quiz show,non fiction,champion,tournament,host',
 'name': 'Jeopardy!',
 'url': '/title/tt0159881/'}