{'Actors': ['George Reeves'],
 'Added': '2013-06-30',
 'Countries': ['USA'],
 'Description': '\r\n              Waiting for Superman: Filmmaker Davis Guggenheim reminds us that education "statistics" have names: Anthony, Francisco, Bianca, Daisy, and Emily, whose stories make up the engrossing foundation of WAITING FOR SUPERMAN. As he follows a handful of promising kids through a system that inhibits, rather than encourages, academic growth, Guggenheim undertakes an exhaustive review of public education, surveying "drop-out factories" and "academic sinkholes," methodically dissecting the system and its seemingly intractable problems.            ',
 'Director': ['Davis Guggenheim'],
 'Genres': ['Documentary'],
 'IMDB': 'http://www.imdb.com/title/tt1566648',
 'PrimeWire': 'http://www.primewire.ag/watch-2580719-Waiting-for-Superman',
 'Ratings': {'IMDB': '7.5/10',
             'Metascore': '81%',
             'PrimeWire': '3.82/5',
             'RT': '89%',
             'Votes': '123'},
 'Released': '2010-01-22',
 'Runtime': '111 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2580719_Waiting_for_Superman_2010.jpg',
 'Title': 'Waiting-for-Superman'}