{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-11-30',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Interstellar',
 'EntryURL': 'https://www.imdb.com/title/tt0816692',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Interstellar/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Interstellar/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Interstellar/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Matthew McConaughey',
            'url': '/name/nm0000190/'},
           {'@type': 'Person',
            'name': 'Anne Hathaway',
            'url': '/name/nm0004266/'},
           {'@type': 'Person',
            'name': 'Jessica Chastain',
            'url': '/name/nm1567113/'},
           {'@type': 'Person',
            'name': 'Mackenzie Foy',
            'url': '/name/nm3237775/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 1420584,
                     'ratingValue': '8.6',
                     'worstRating': '1.0'},
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Jonathan Nolan',
              'url': '/name/nm0634300/'},
             {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0159111/'},
             {'@type': 'Organization', 'url': '/company/co0147954/'},
             {'@type': 'Organization', 'url': '/company/co0071668/'},
             {'@type': 'Organization', 'url': '/company/co0627877/'},
             {'@type': 'Organization', 'url': '/company/co0422290/'}],
 'datePublished': '2014-11-05',
 'description': 'Interstellar is a movie starring Matthew McConaughey, Anne '
                'Hathaway, and Jessica Chastain. A team of explorers travel '
                'through a wormhole in space in an attempt to ensure '
                "humanity's survival.",
 'director': {'@type': 'Person',
              'name': 'Christopher Nolan',
              'url': '/name/nm0634240/'},
 'duration': 'PT2H49M',
 'genre': ['Adventure', 'Drama', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
 'keywords': 'astronaut,saving the world,relativity,gravity,nasa',
 'name': 'Interstellar',
 'trailer': {'@type': 'VideoObject',
             'description': 'A group of explorers make use of a newly '
                            'discovered wormhole to surpass the limitations on '
                            'human space travel and conquer the vast distances '
                            'involved in an interstellar voyage.',
             'embedUrl': '/video/imdb/vi1586278169',
             'name': 'Trailer #4',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNjM5OTQzMTg4N15BMl5BanBnXkFtZTgwOTgyMjM0NTE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNjM5OTQzMTg4N15BMl5BanBnXkFtZTgwOTgyMjM0NTE@._V1_.jpg',
             'uploadDate': '2014-10-02T08:55:19Z'},
 'url': '/title/tt0816692/'}