<?php
$infoArray = array('Actors' => array(' Anne Hathaway',
            'Ellen Burstyn',
            'John Lithgow',
            'Mackenzie Foy',
            'Matthew McConaughey'),
 'Added' => '2014-11-30',
 'Countries' => array(),
 'Description' => '\nInterstellar: A group of explorers make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage. ',
 'Director' => array('Christopher Nolan'),
 'Genres' => array('Adventure', 'Sci-Fi'),
 'IMDB' => 'http://www.imdb.com/title/tt0816692',
 'PrimeWire' => 'http://www.primewire.ag/watch-2753796-Interstellar',
 'Ratings' => array('IMDB' => '8.8/10',
             'Metascore' => '74%',
             'PrimeWire' => '4.43/5',
             'RT' => '72%',
             'Votes' => '3234'),
 'Released' => '2014-11-07',
 'Runtime' => '169 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2753796_Interstellar.jpg',
 'Title' => 'Interstellar');
?>