{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/TV/snapshot/Better-Off-Ted',
 'EntryURL': 'https://www.imdb.com/title/tt1235547',
 'Entry_json': 'Favorites/TV/snapshot/Better-Off-Ted/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Better-Off-Ted/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Better-Off-Ted/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jay Harrington',
            'url': '/name/nm0364280/'},
           {'@type': 'Person',
            'name': 'Portia de Rossi',
            'url': '/name/nm0005577/'},
           {'@type': 'Person',
            'name': 'Andrea Anders',
            'url': '/name/nm1627969/'},
           {'@type': 'Person',
            'name': 'Jonathan Slavin',
            'url': '/name/nm0805587/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 24248,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Victor Fresco',
              'url': '/name/nm0294355/'},
             {'@type': 'Organization', 'url': '/company/co0071857/'},
             {'@type': 'Organization', 'url': '/company/co0056447/'}],
 'datePublished': '2009-03-18',
 'description': 'Better Off Ted is a TV series starring Jay Harrington, Portia '
                'de Rossi, and Andrea Anders. In a science-based company, a '
                'manager tries to keep control of his scientists while being '
                'pressured by his shrewd boss.',
 'genre': ['Comedy', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTI3NDgzMTU2Nl5BMl5BanBnXkFtZTcwOTUzMzA1Mg@@._V1_.jpg',
 'keywords': 'breaking the fourth wall by talking to the audience,workplace '
             'romance,workplace,offbeat,scientific research',
 'name': 'Better Off Ted',
 'trailer': [{'@type': 'VideoObject',
              'embedUrl': '/video/imdb/vi2356264473',
              'name': 'Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNDhkOTcwNmItMjNmMy00YjBiLWJlOTktODNjYWZkNDk2NTk4XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNDhkOTcwNmItMjNmMy00YjBiLWJlOTktODNjYWZkNDk2NTk4XkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
              'uploadDate': '2020-07-18T23:00:29Z'}],
 'url': '/title/tt1235547/'}