{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rattlesnake',
 'EntryURL': 'https://www.imdb.com/title/tt9257484',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rattlesnake/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rattlesnake/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Rattlesnake/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Carmen Ejogo',
            'url': '/name/nm0252238/'},
           {'@type': 'Person', 'name': 'Theo Rossi', 'url': '/name/nm0744331/'},
           {'@type': 'Person',
            'name': 'Emma Greenwell',
            'url': '/name/nm4563896/'},
           {'@type': 'Person',
            'name': 'Apollonia Pratt',
            'url': '/name/nm9722439/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 6551,
                     'ratingValue': '4.6',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Zak Hilditch',
              'url': '/name/nm1991847/'},
             {'@type': 'Organization', 'url': '/company/co0454339/'},
             {'@type': 'Organization', 'url': '/company/co0144901/'}],
 'datePublished': '2019-10-25',
 'description': 'Rattlesnake is a movie starring Carmen Ejogo, Theo Rossi, and '
                'Emma Greenwell. When a single mother accepts the help of a '
                'mysterious woman after her daughter is bitten by a '
                'rattlesnake, she finds herself making an unthinkable deal...',
 'director': {'@type': 'Person',
              'name': 'Zak Hilditch',
              'url': '/name/nm1991847/'},
 'duration': 'PT1H25M',
 'genre': ['Drama', 'Horror', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjlhZTVmMzktMmQzMy00MzQ2LWJkNzQtYTdjMjZjZmY0NjQ5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'single mother,roadtrip,rattlesnake bite,deal with the '
             'devil,sunset',
 'name': 'Rattlesnake',
 'trailer': {'@type': 'VideoObject',
             'description': 'When a single mother accepts the help of a '
                            'mysterious woman after her daughter is bitten by '
                            'a rattlesnake, she finds herself making an '
                            'unthinkable deal to repay her debt.',
             'embedUrl': '/video/imdb/vi3448749849',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMmE0YWZhZjMtNzgwZC00YTQ3LThjNzAtMWFmZDIwYzE2NTJkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMmE0YWZhZjMtNzgwZC00YTQ3LThjNzAtMWFmZDIwYzE2NTJkXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg',
             'uploadDate': '2019-10-10T20:00:14Z'},
 'url': '/title/tt9257484/'}