{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ex-Machina',
 'EntryURL': 'https://www.imdb.com/title/tt0470752',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ex-Machina/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ex-Machina/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Ex-Machina/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Alicia Vikander',
            'url': '/name/nm2539953/'},
           {'@type': 'Person',
            'name': 'Domhnall Gleeson',
            'url': '/name/nm1727304/'},
           {'@type': 'Person',
            'name': 'Oscar Isaac',
            'url': '/name/nm1209966/'},
           {'@type': 'Person',
            'name': 'Sonoya Mizuno',
            'url': '/name/nm4420495/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 455660,
                     'ratingValue': '7.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Alex Garland',
              'url': '/name/nm0307497/'},
             {'@type': 'Organization', 'url': '/company/co0390816/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0197272/'},
             {'@type': 'Organization', 'url': '/company/co0103974/'},
             {'@type': 'Organization', 'url': '/company/co0093463/'}],
 'datePublished': '2015-01-21',
 'description': 'Ex Machina is a movie starring Alicia Vikander, Domhnall '
                'Gleeson, and Oscar Isaac. A young programmer is selected to '
                'participate in a ground-breaking experiment in synthetic '
                'intelligence by evaluating the human qualities of a highly...',
 'director': {'@type': 'Person',
              'name': 'Alex Garland',
              'url': '/name/nm0307497/'},
 'duration': 'PT1H48M',
 'genre': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_.jpg',
 'keywords': 'artificial intelligence,turing test,minimal cast,robot human '
             'relationship,video surveillance',
 'name': 'Ex Machina',
 'trailer': {'@type': 'VideoObject',
             'description': 'A young programmer is selected to participate in '
                            'a breakthrough experiment in artificial '
                            'intelligence by evaluating the human qualities of '
                            'a breathtaking female A.I.',
             'embedUrl': '/video/imdb/vi744337689',
             'name': 'New Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTUyMjQzNzk0MF5BMl5BanBnXkFtZTgwNTE4NjM0NTE@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTUyMjQzNzk0MF5BMl5BanBnXkFtZTgwNTE4NjM0NTE@._V1_.jpg',
             'uploadDate': '2015-04-22T18:03:47Z'},
 'url': '/title/tt0470752/'}