{'Actors': ['Alec Murdock',
            'Becca Sweitzer',
            'Benji Madden',
            'Beverly Polcyn',
            'Candice Cook',
            'Cassie Townsend',
            'Cerina Vincent',
            'China Shavers',
            'Chris Evans',
            'Chyler Leigh',
            'Cody McMains',
            'Daniel Spink',
            'Deon Richmond',
            'Ed Lauter',
            'Eric Christian Olsen',
            'Eric Jungmann',
            'George Wyner',
            'H Jon Benjamin',
            'Heather Brown',
            'Jackie Harris',
            'Jaime Pressly',
            'James Read',
            'Jarrett Lennon',
            'Jay Johnston',
            'Jeanette Miller',
            'Jim Wise',
            'Joanna Garcia',
            'Josh Jacobson',
            'Joy Gohring',
            'Kelly King',
            'Lacey Chabert',
            'Lukas Behnken',
            'Lyman Ward',
            'Melissa Joan Hart',
            'Mia Kirshner',
            'Michael Ensign',
            'Molly Ringwald',
            'Mr T',
            'Nathan West',
            'Nectar Rose',
            'Nick Bakay',
            'Oz Perkins',
            'Paul Gleason',
            'Paul Goebel',
            'Paul Thomas',
            'Peter Simon',
            'Randy Quaid',
            'Riley Smith',
            'Rob Benedict',
            'Sam Ayers',
            'Sam Huntington',
            'Samaire Armstrong',
            'Samm Levine',
            'Sarah Christine Smith',
            'Sean Patrick Thomas',
            'Sean Smith',
            'Will Gill Jr',
            'Zachary Woodlee'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\nNot Another Teen Movie: A sendup of all the teen movies that have accumulated in the past two decades. ',
 'Director': ['Joel Gallen'],
 'Genres': ['Comedy'],
 'IMDB': 'http://www.imdb.com/title/tt0277371',
 'PrimeWire': 'http://www.primewire.ag/watch-4355-Not-Another-Teen-Movie',
 'Ratings': {'IMDB': '5.7/10',
             'Metascore': '32%',
             'PrimeWire': '3.74/5',
             'RT': '28%',
             'Votes': '468'},
 'Released': '2001-12-07',
 'Runtime': '89 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/4355_Not_Another_Teen_Movie_2001.jpg',
 'Title': 'Not-Another-Teen-Movie'}