{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Uncharted-3-Drakes-Deception',
 'EntryURL': 'https://rawg.io/games/uncharted-3-drakes-deception',
 'Entry_json': 'Favorites/Games/snapshot/Uncharted-3-Drakes-Deception/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Uncharted-3-Drakes-Deception/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Uncharted-3-Drakes-Deception/thumb.jpg',
 'added': 4585,
 'background_image': 'https://media.rawg.io/media/games/589/589fc47c5ae34160d65c4682e21fed66.jpg',
 'developers': ['Naughty Dog'],
 'genres': ['Action', 'Adventure'],
 'name': "Uncharted 3: Drake's Deception",
 'platforms': ['PlayStation 3', 'PlayStation 4'],
 'publishers': ['Sony Computer Entertainment'],
 'released': '2011-11-01',
 'slug': 'uncharted-3-drakes-deception'}