{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-08-10',
 'EntryPath': 'Favorites/Movies/snapshot/Something-the-Lord-Made',
 'EntryURL': 'https://www.imdb.com/title/tt0386792',
 'Entry_json': 'Favorites/Movies/snapshot/Something-the-Lord-Made/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Something-the-Lord-Made/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Something-the-Lord-Made/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Alan Rickman',
            'url': '/name/nm0000614/'},
           {'@type': 'Person', 'name': 'Yasiin Bey', 'url': '/name/nm0080049/'},
           {'@type': 'Person',
            'name': 'Kyra Sedgwick',
            'url': '/name/nm0001718/'},
           {'@type': 'Person',
            'name': 'Gabrielle Union',
            'url': '/name/nm0005517/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 11778,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-PG',
 'creator': [{'@type': 'Person',
              'name': 'Peter Silverman',
              'url': '/name/nm0798960/'},
             {'@type': 'Person',
              'name': 'Robert Caswell',
              'url': '/name/nm0145781/'},
             {'@type': 'Organization', 'url': '/company/co0005861/'},
             {'@type': 'Organization', 'url': '/company/co0015134/'}],
 'datePublished': '2004-05-30',
 'description': 'Something the Lord Made is a TV movie starring Alan Rickman, '
                'Yasiin Bey, and Kyra Sedgwick. A dramatization of the '
                'relationship between heart surgery pioneers Alfred Blalock '
                'and Vivien Thomas.',
 'director': [{'@type': 'Person',
               'name': 'Joseph Sargent',
               'url': '/name/nm0765121/'}],
 'duration': 'PT1H50M',
 'genre': ['Biography', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTIzNTE0NjU4N15BMl5BanBnXkFtZTcwNjgyNDcyMQ@@._V1_.jpg',
 'keywords': 'heart surgery,blue baby syndrome,surgery,baby,heart',
 'name': 'Something the Lord Made',
 'url': '/title/tt0386792/'}