{'EntryAdded': '06-05-2020',
 'EntryPath': 'Favorites/Games/snapshot/Rune-Halls-Of-Valhalla',
 'EntryURL': 'https://rawg.io/games/rune-halls-of-valhalla',
 'Entry_json': 'Favorites/Games/snapshot/Rune-Halls-Of-Valhalla/entry.json',
 'Entry_py': 'Favorites/Games/snapshot/Rune-Halls-Of-Valhalla/info.py',
 'Entry_thumb': 'Favorites/Games/snapshot/Rune-Halls-Of-Valhalla/thumb.jpg',
 'added': 540,
 'background_image': 'https://media.rawg.io/media/screenshots/f83/f8324f17a0b08015911d878d881a0b71.jpg',
 'developers': ['Human Head Studios', 'HumanHead Studios'],
 'genres': ['Action', 'Adventure', 'RPG'],
 'name': 'Rune',
 'platforms': ['PC'],
 'publishers': ['Human Head Studios',
                'Nine Realms',
                'Take Two Interactive',
                'Gathering of Developers',
                'Ragnarok Game, LLC'],
 'released': '2000-11-18',
 'slug': 'rune-halls-of-valhalla'}