{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Chinatown',
 'EntryURL': 'https://www.imdb.com/title/tt0071315',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Chinatown/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Chinatown/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/Chinatown/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jack Nicholson',
            'url': '/name/nm0000197/'},
           {'@type': 'Person',
            'name': 'Faye Dunaway',
            'url': '/name/nm0001159/'},
           {'@type': 'Person',
            'name': 'John Huston',
            'url': '/name/nm0001379/'},
           {'@type': 'Person',
            'name': 'Perry Lopez',
            'url': '/name/nm0520164/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 282629,
                     'ratingValue': '8.2',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Robert Towne',
              'url': '/name/nm0001801/'},
             {'@type': 'Person',
              'name': 'Roman Polanski',
              'url': '/name/nm0000591/'},
             {'@type': 'Organization', 'url': '/company/co0023400/'},
             {'@type': 'Organization', 'url': '/company/co0001235/'},
             {'@type': 'Organization', 'url': '/company/co0044146/'},
             {'@type': 'Organization', 'url': '/company/co0079716/'}],
 'datePublished': '1974-06-20',
 'description': 'Chinatown is a movie starring Jack Nicholson, Faye Dunaway, '
                'and John Huston. A private detective hired to expose an '
                'adulterer finds himself caught up in a web of deceit, '
                'corruption, and murder.',
 'director': {'@type': 'Person',
              'name': 'Roman Polanski',
              'url': '/name/nm0000591/'},
 'duration': 'PT2H10M',
 'genre': ['Drama', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOGMwYmY5ZmEtMzY1Yi00OWJiLTk1Y2MtMzI2MjBhYmZkNTQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
 'keywords': 'neo noir,police,private detective,femme fatale,corruption',
 'name': 'Chinatown',
 'trailer': {'@type': 'VideoObject',
             'description': 'Theatrical Trailer from Paramount',
             'embedUrl': '/video/imdb/vi1220411673',
             'name': 'Chinatown',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZjY0NzViNDYtMzQ1My00NTlhLWJjYzEtNTNhNjZiZDczN2VlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZjY0NzViNDYtMzQ1My00NTlhLWJjYzEtNTNhNjZiZDczN2VlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T13:23:02Z'},
 'url': '/title/tt0071315/'}