{'Actors': ['Allan Warnick',
            'Beulah Quo',
            'Bob Golden',
            'Bruce Glover',
            'Burt Young',
            'Cecil Elliott',
            'Charles Knapp',
            'Claudio Mart&#xED;nez',
            'Darrell Zwerling',
            'Diane Ladd',
            'Faye Dunaway',
            'Federico Roberto',
            'Fritzi Burr',
            'Jack Nicholson',
            'James Hong',
            "James O'Rear",
            'Jerry Fujikawa',
            'Jesse Vint',
            'Jim Burk',
            'Joe Mantell',
            'John Hillerman',
            'John Holland',
            'John Huston',
            'John Rogers',
            'Lee de Broux',
            'Noble Willingham',
            'Paul Jenkins',
            'Perry Lopez',
            'Rance Howard',
            'Richard Bakalyan',
            'Richard Warren',
            'Roman Polanski',
            'Roy Jenson',
            'Roy Roberts'],
 'Added': '2013-02-24',
 'Countries': ['USA'],
 'Description': '\n'
                'Chinatown: A private detective investigating an adultery case '
                'stumbles on to a scheme of murder that has something to do '
                'with water. ',
 'Director': ['Roman Polanski'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Chinatown',
 'EntryURL': 'https://www.imdb.com/title/tt0071315',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Chinatown/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Chinatown/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//Chinatown/info.py',
 'Genres': ['Thriller', 'Mystery'],
 'IMDB': 'http://www.imdb.com/title/tt0071315',
 'PrimeWire': 'http://www.primewire.ag/watch-879-Chinatown',
 'Ratings': {'IMDB': '8.3/10',
             'Metascore': '86%',
             'PrimeWire': '3.95/5',
             'RT': '98%',
             'Votes': '128'},
 'Released': '1974-06-20',
 'Runtime': '130 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/879_Chinatown_1974.jpg',
 'Title': 'Chinatown'}