{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/American-Factory',
 'EntryURL': 'https://www.imdb.com/title/tt9351980',
 'Entry_json': 'Favorites/Movies/snapshot/American-Factory/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/American-Factory/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/American-Factory/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': "Junming 'Jimmy' Wang",
            'url': '/name/nm10930330/'},
           {'@type': 'Person',
            'name': 'Robert Allen',
            'url': '/name/nm10930331/'},
           {'@type': 'Person',
            'name': 'Sherrod Brown',
            'url': '/name/nm2414445/'},
           {'@type': 'Person',
            'name': 'Dave Burrows',
            'url': '/name/nm10930329/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 14625,
                      'ratingValue': '7.4',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-14',
 'creator': [{'@type': 'Organization', 'url': '/company/co0720404/'},
             {'@type': 'Organization', 'url': '/company/co0132772/'}],
 'datePublished': '2019-08-21',
 'description': "American Factory is a movie starring Junming 'Jimmy' Wang, "
                'Robert Allen, and Sherrod Brown. In post-industrial Ohio, a '
                'Chinese billionaire opens a factory in an abandoned General '
                'Motors plant, hiring two thousand Americans. Early...',
 'director': [{'@type': 'Person',
               'name': 'Steven Bognar',
               'url': '/name/nm0091840/'},
              {'@type': 'Person',
               'name': 'Julia Reichert',
               'url': '/name/nm0717064/'}],
 'duration': 'PT1H50M',
 'genre': 'Documentary',
 'image': 'https://m.media-amazon.com/images/M/MV5BNWFkMDY1MjItZmNkOS00MDg2LWFlMjMtZWU3YmM0MmY3MWM3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'working class,blue collar,factory worker,culture clash',
 'name': 'American Factory',
 'trailer': [{'@type': 'VideoObject',
              'description': 'In post-industrial Ohio, a Chinese billionaire '
                             'opens a new factory in the husk of an abandoned '
                             'General Motors plant, hiring two thousand '
                             'blue-collar Americans. Early days of hope and '
                             'optimism give way to setbacks as high-tech China '
                             'clashes with working-class America.',
              'embedUrl': '/video/imdb/vi4081433625',
              'name': 'Official Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BZTMzY2JjYzMtNGYwYy00MmVjLTgzOGUtN2EzY2U4NDZkM2U1XkEyXkFqcGdeQWFybm8@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BZTMzY2JjYzMtNGYwYy00MmVjLTgzOGUtN2EzY2U4NDZkM2U1XkEyXkFqcGdeQWFybm8@._V1_.jpg',
              'uploadDate': '2019-08-14T15:51:42Z'}],
 'url': '/title/tt9351980/'}