{'Actors': ['Na&tv'],
 'Added': '2016-08-13',
 'Countries': ['USA'],
 'Description': '\nParty Legends: Notable and notorious personalities share their most candid party stories with help from emerging artists and animators. ',
 'Director': ['NA'],
 'Genres': ['Animation&tv'],
 'IMDB': 'http://www.imdb.com/title/tt5849156',
 'PrimeWire': 'http://www.primewire.ag/tv-2780247-Party-Legends',
 'Ratings': {'IMDB': 'N/A',
             'Metascore': 'N/A',
             'PrimeWire': '4.37/5',
             'RT': 'N/A',
             'Votes': '19'},
 'Released': '2016-07-07',
 'Runtime': 'NA',
 'ThumbURL': 'http://images.primewire.ag/thumbs/2780247_Party_Legends_2016_45.jpg',
 'Title': 'Party-Legends'}