{'Actors': ['Aaron Michael Lacey',
            'Adolf Hitler',
            'Alec Baldwin',
            'Alec Von Bargen',
            'Amy Wright',
            'Angelina Jolie',
            'Austin Williams',
            'Billy Crudup',
            'Carl Burrows',
            'Christopher Evan Welch',
            'Christopher Stadulis',
            'Darryl Reuben Hall',
            'Dominick Cicco',
            'Eddie Redmayne',
            'Fidel Castro',
            'Gabriel Macht',
            'Gregory Marcel',
            'Hristo Hristov',
            'Jack Martin',
            'James Faulkner',
            'Jeff Skowron',
            'Joe Pesci',
            'John F Kennedy',
            'John Henry',
            'John Knox',
            'John Sessions',
            'John Turturro',
            'Jonah Falcon',
            'Justin Restivo',
            'Karron Graves',
            'Katherine Hoskins Mackey',
            'Keir Dullea',
            'Laila Robins',
            'Lee Bryant',
            'Lee Pace',
            'Leonard Silver',
            'Mark Ivanir',
            'Martina Gedeck',
            'Matt Damon',
            'Michael Gambon',
            'Neal Huff',
            'Nick Poltoranin',
            'Oleg Shtefanko',
            'Peter Kybart',
            'Reathel Bean',
            'Robert C Kirk',
            'Robert De Niro',
            'Robert Dearle',
            'Robert Prescott',
            'Roy William Gardner',
            'S&#xE1;ndor Tecsy',
            'Susan Haskell',
            'Tammy Blanchard',
            'Timothy Hutton',
            'Tommy Nelson',
            'Tuc Watkins',
            'Wally Dunn',
            'William Hurt',
            'Yevgeniy Dekhtyar'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                'The Good Shepherd: The tumultuous early history of the '
                'Central Intelligence Agency is viewed through the prism of '
                "one man's life. ",
 'Director': ['Robert De Niro'],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Good-Shepherd',
 'EntryURL': 'http://www.imdb.com/title/tt0343737',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Good-Shepherd/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Good-Shepherd/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/Movies/snapshot//The-Good-Shepherd/info.py',
 'Genres': ['Drama', 'Thriller'],
 'IMDB': 'http://www.imdb.com/title/tt0343737',
 'PrimeWire': 'http://www.primewire.ag/watch-1133-The-Good-Shepherd',
 'Ratings': {'IMDB': '6.7/10',
             'Metascore': '61%',
             'PrimeWire': '3.77/5',
             'RT': '54%',
             'Votes': '159'},
 'Released': '2006-12-11',
 'Runtime': '167 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/1133_The_Good_Shepherd_2006.jpg',
 'Title': 'The-Good-Shepherd'}