{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/The-Good-Shepherd',
 'EntryURL': 'https://www.imdb.com/title/tt0343737',
 'Entry_json': 'Favorites/Movies/snapshot/The-Good-Shepherd/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Good-Shepherd/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Good-Shepherd/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Matt Damon', 'url': '/name/nm0000354/'},
           {'@type': 'Person',
            'name': 'Angelina Jolie',
            'url': '/name/nm0001401/'},
           {'@type': 'Person',
            'name': 'Robert De Niro',
            'url': '/name/nm0000134/'},
           {'@type': 'Person',
            'name': 'Alec Baldwin',
            'url': '/name/nm0000285/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 96702,
                     'ratingValue': '6.7',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Eric Roth',
              'url': '/name/nm0744839/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'},
             {'@type': 'Organization', 'url': '/company/co0033472/'},
             {'@type': 'Organization', 'url': '/company/co0063961/'},
             {'@type': 'Organization', 'url': '/company/co0020958/'}],
 'datePublished': '2006-12-22',
 'description': 'The Good Shepherd is a movie starring Matt Damon, Angelina '
                'Jolie, and Robert De Niro. The tumultuous early history of '
                'the Central Intelligence Agency is viewed through the prism '
                "of one man's life.",
 'director': {'@type': 'Person',
              'name': 'Robert De Niro',
              'url': '/name/nm0000134/'},
 'duration': 'PT2H47M',
 'genre': ['Drama', 'History', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMTU5MjExMzA1Nl5BMl5BanBnXkFtZTgwMzIxNzQxMTE@._V1_.jpg',
 'keywords': 'cia,year 1962,year 1960,year 1958,year 1947',
 'name': 'The Good Shepherd',
 'url': '/title/tt0343737/'}