{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Hoyo',
 'EntryURL': 'https://www.imdb.com/title/tt8228288',
 'Entry_json': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Hoyo/entry.json',
 'Entry_py': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Hoyo/info.py',
 'Entry_thumb': 'W:/Portfolio/PersonalWebsite/Favorites/Movies/snapshot/El-Hoyo/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ivan Massagué',
            'url': '/name/nm1293644/'},
           {'@type': 'Person',
            'name': 'Zorion Eguileor',
            'url': '/name/nm1445349/'},
           {'@type': 'Person',
            'name': 'Antonia San Juan',
            'url': '/name/nm0760665/'},
           {'@type': 'Person',
            'name': 'Emilio Buale',
            'url': '/name/nm0117763/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 127518,
                     'ratingValue': '7.0',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'David Desola',
              'url': '/name/nm1457642/'},
             {'@type': 'Person',
              'name': 'David Desola',
              'url': '/name/nm1457642/'},
             {'@type': 'Person',
              'name': 'Pedro Rivero',
              'url': '/name/nm1038878/'},
             {'@type': 'Organization', 'url': '/company/co0163271/'},
             {'@type': 'Organization', 'url': '/company/co0758856/'},
             {'@type': 'Organization', 'url': '/company/co0758857/'},
             {'@type': 'Organization', 'url': '/company/co0514197/'},
             {'@type': 'Organization', 'url': '/company/co0040714/'},
             {'@type': 'Organization', 'url': '/company/co0149773/'},
             {'@type': 'Organization', 'url': '/company/co0157183/'},
             {'@type': 'Organization', 'url': '/company/co0157689/'},
             {'@type': 'Organization', 'url': '/company/co0064682/'},
             {'@type': 'Organization', 'url': '/company/co0299856/'}],
 'datePublished': '2019-11-08',
 'description': 'El hoyo is a movie starring Ivan Massagué, Zorion Eguileor, '
                'and Antonia San Juan. A vertical prison with one cell per '
                'level. Two people per cell. One only food platform and two '
                'minutes per day to feed from up to down. An endless...',
 'director': {'@type': 'Person',
              'name': 'Galder Gaztelu-Urrutia',
              'url': '/name/nm2008067/'},
 'duration': 'PT1H34M',
 'genre': ['Horror', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BOTMyYTIyM2MtNjQ2ZC00MWFkLThhYjQtMjhjMGZiMjgwYjM2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
 'keywords': 'hunger,prison,floor,cannibalism,inmate',
 'name': 'El hoyo',
 'review': {'@type': 'Review',
            'author': {'@type': 'Person', 'name': 'pesaresigiovanni'},
            'dateCreated': '2020-03-22',
            'inLanguage': 'English',
            'itemReviewed': {'@type': 'CreativeWork',
                             'url': '/title/tt8228288/'},
            'name': 'Great idea, good movie',
            'reviewBody': 'The idea behind the plot is interesting and the '
                          'movie is effective and powerful but the end left me '
                          'a bit confused and disappointed.',
            'reviewRating': {'@type': 'Rating',
                             'bestRating': '10',
                             'ratingValue': '7',
                             'worstRating': '1'}},
 'trailer': {'@type': 'VideoObject',
             'description': 'Inside a vertical prison system, inmates are '
                            'assigned to a level and forced to ration food '
                            'from a platform that moves between the floors.',
             'embedUrl': '/video/imdb/vi2275851801',
             'name': 'Official Trailer',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2EwYTdmOWUtMzI2Mi00NjU1LWFkZjItOThhZTVkYTlmNzhjXkEyXkFqcGdeQWFybm8@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2EwYTdmOWUtMzI2Mi00NjU1LWFkZjItOThhZTVkYTlmNzhjXkEyXkFqcGdeQWFybm8@._V1_.jpg',
             'uploadDate': '2020-03-08T23:54:58Z'},
 'url': '/title/tt8228288/'}