{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/Idiocracy',
 'EntryURL': 'https://www.imdb.com/title/tt0387808',
 'Entry_json': 'Favorites/Movies/snapshot/Idiocracy/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Idiocracy/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Idiocracy/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Luke Wilson',
            'url': '/name/nm0005561/'},
           {'@type': 'Person',
            'name': 'Maya Rudolph',
            'url': '/name/nm0748973/'},
           {'@type': 'Person',
            'name': 'Dax Shepard',
            'url': '/name/nm1009277/'},
           {'@type': 'Person',
            'name': 'Terry Crews',
            'url': '/name/nm0187719/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 139451,
                     'ratingValue': '6.6',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Mike Judge',
              'url': '/name/nm0431918/'},
             {'@type': 'Person',
              'name': 'Mike Judge',
              'url': '/name/nm0431918/'},
             {'@type': 'Person',
              'name': 'Etan Cohen',
              'url': '/name/nm1000113/'},
             {'@type': 'Organization', 'url': '/company/co0000756/'},
             {'@type': 'Organization', 'url': '/company/co0274496/'},
             {'@type': 'Organization', 'url': '/company/co0174362/'}],
 'datePublished': '2007-01-25',
 'description': 'Idiocracy is a movie starring Luke Wilson, Maya Rudolph, and '
                'Dax Shepard. Private Joe Bauers, the definition of "average '
                'American", is selected by the Pentagon to be the guinea pig '
                'for a top-secret hibernation program. Forgotten, he...',
 'director': {'@type': 'Person',
              'name': 'Mike Judge',
              'url': '/name/nm0431918/'},
 'duration': 'PT1H24M',
 'genre': ['Adventure', 'Comedy', 'Sci-Fi', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMWQ4MzI2ZDQtYjk3MS00ODdjLTkwN2QtOTBjYzIwM2RmNzgyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'political comedy,hibernation,stupidity,futuristic,false utopia',
 'name': 'Idiocracy',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from 20th Century Fox Home '
                            'Entertainment',
             'embedUrl': '/video/imdb/vi1622016281',
             'name': 'Idiocracy',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMWY4MzE1ZGMtOWIyNC00NDY5LTg1MTUtMjdlM2Y4NzcwNDNlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMWY4MzE1ZGMtOWIyNC00NDY5LTg1MTUtMjdlM2Y4NzcwNDNlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T14:30:45Z'},
 'url': '/title/tt0387808/'}