{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '06-03-2020',
 'EntryPath': 'Favorites/Movies/snapshot/Three-Billboards-Outside-Ebbing-Missouri',
 'EntryURL': 'https://www.imdb.com/title/tt5027774',
 'Entry_json': 'Favorites/Movies/snapshot/Three-Billboards-Outside-Ebbing-Missouri/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Three-Billboards-Outside-Ebbing-Missouri/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Three-Billboards-Outside-Ebbing-Missouri/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Frances McDormand',
            'url': '/name/nm0000531/'},
           {'@type': 'Person',
            'name': 'Woody Harrelson',
            'url': '/name/nm0000437/'},
           {'@type': 'Person',
            'name': 'Sam Rockwell',
            'url': '/name/nm0005377/'},
           {'@type': 'Person',
            'name': 'Caleb Landry Jones',
            'url': '/name/nm2655177/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 400581,
                      'ratingValue': '8.2',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Martin McDonagh',
              'url': '/name/nm1732981/'},
             {'@type': 'Organization', 'url': '/company/co0010002/'},
             {'@type': 'Organization', 'url': '/company/co0476818/'},
             {'@type': 'Organization', 'url': '/company/co0028932/'}],
 'datePublished': '2017-12-01',
 'description': 'Three Billboards Outside Ebbing, Missouri is a movie starring '
                'Frances McDormand, Woody Harrelson, and Sam Rockwell. A '
                'mother personally challenges the local authorities to solve '
                "her daughter's murder when they fail to catch the...",
 'director': [{'@type': 'Person',
               'name': 'Martin McDonagh',
               'url': '/name/nm1732981/'}],
 'duration': 'PT1H55M',
 'genre': ['Comedy', 'Crime', 'Drama'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjI0ODcxNzM1N15BMl5BanBnXkFtZTgwMzIwMTEwNDI@._V1_.jpg',
 'keywords': 'billboard,police brutality,black comedy,ambiguous ending,thrown '
             'through a window',
 'name': 'Three Billboards Outside Ebbing, Missouri',
 'trailer': [{'@type': 'VideoObject',
              'description': 'In this darkly comic drama, a mother personally '
                             'challenges the local authorities to solve her '
                             "daughter's murder, when they fail to catch the "
                             'culprit.',
              'embedUrl': '/video/imdb/vi3585980441',
              'name': 'Now Playing',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BOTUxMzJjNDEtNzI3MS00OWFkLTliZjYtYjc3ZTZiMDc2YWZhXkEyXkFqcGdeQXVyNzQ0MDUyMzg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BOTUxMzJjNDEtNzI3MS00OWFkLTliZjYtYjc3ZTZiMDc2YWZhXkEyXkFqcGdeQXVyNzQ0MDUyMzg@._V1_.jpg',
              'uploadDate': '2017-11-20T23:46:09Z'}],
 'url': '/title/tt5027774/'}