{'Actors': ['Charlie Day&tv',
            'Danny DeVito&tv',
            'Glenn Howerton&tv',
            'Kaitlin Olson&tv',
            'Rob McElhenney&tv'],
 'Added': '2013-02-23',
 'Countries': ['USA'],
 'Description': '\n'
                "It's Always Sunny in Philadelphia: Four young friends with "
                'big egos and slightly arrogant attitudes are the proprietors '
                'of an Irish bar in Philadelphia. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Its-Always-Sunny-in-Philadelphia',
 'EntryURL': 'http://www.imdb.com/title/tt0472954',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Its-Always-Sunny-in-Philadelphia/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Its-Always-Sunny-in-Philadelphia/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Its-Always-Sunny-in-Philadelphia/info.py',
 'Genres': ['Comedy&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0472954',
 'PrimeWire': 'http://www.primewire.ag/tv-5163-Its-Always-Sunny-in-Philadelphia',
 'Ratings': {'IMDB': '8.8/10',
             'Metascore': 'N/A',
             'PrimeWire': '4.32/5',
             'RT': 'N/A',
             'Votes': '1662'},
 'Released': '2005-08-04',
 'Runtime': '30 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5163_Its_Always_Sunny_in_Philadelphia_2005.jpg',
 'Title': 'Its-Always-Sunny-in-Philadelphia'}