{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/TV/snapshot/Its-Always-Sunny-in-Philadelphia',
 'EntryURL': 'https://www.imdb.com/title/tt0472954',
 'Entry_json': 'Favorites/TV/snapshot/Its-Always-Sunny-in-Philadelphia/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Its-Always-Sunny-in-Philadelphia/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Its-Always-Sunny-in-Philadelphia/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Charlie Day',
            'url': '/name/nm0206359/'},
           {'@type': 'Person',
            'name': 'Glenn Howerton',
            'url': '/name/nm1097351/'},
           {'@type': 'Person',
            'name': 'Rob McElhenney',
            'url': '/name/nm0568390/'},
           {'@type': 'Person',
            'name': 'Kaitlin Olson',
            'url': '/name/nm0647698/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 182109,
                      'ratingValue': '8.8',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Glenn Howerton',
              'url': '/name/nm1097351/'},
             {'@type': 'Person',
              'name': 'Rob McElhenney',
              'url': '/name/nm0568390/'},
             {'@type': 'Organization', 'url': '/company/co0206017/'},
             {'@type': 'Organization', 'url': '/company/co0070636/'},
             {'@type': 'Organization', 'url': '/company/co0216537/'},
             {'@type': 'Organization', 'url': '/company/co0363412/'},
             {'@type': 'Organization', 'url': '/company/co0223784/'},
             {'@type': 'Organization', 'url': '/company/co0299260/'}],
 'datePublished': '2005-08-04',
 'description': "It's Always Sunny in Philadelphia is a TV series starring "
                'Charlie Day, Glenn Howerton, and Rob McElhenney. Five friends '
                'with big egos and slightly arrogant attitudes are the '
                'proprietors of an Irish pub in Philadelphia.',
 'genre': 'Comedy',
 'image': 'https://m.media-amazon.com/images/M/MV5BOTExNGZkMWMtMmIwZC00YjA3LTgwM2ItZjQ2YmZkMzQ1YWZkXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
 'keywords': 'cringe comedy,crude humor,black comedy,south '
             'philadelphia,philadelphia',
 'name': "It's Always Sunny in Philadelphia",
 'trailer': [{'@type': 'VideoObject',
              'description': "Season 11 teaser for It's Always Sunny in "
                             'Philadelphia on FXX.',
              'embedUrl': '/video/imdb/vi611693081',
              'name': 'Season 11 Teaser - "Ideas"',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjAzNzUzMjc3OV5BMl5BanBnXkFtZTgwMjYxNTM1NzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjAzNzUzMjc3OV5BMl5BanBnXkFtZTgwMjYxNTM1NzE@._V1_.jpg',
              'uploadDate': '2015-12-22T13:05:11Z'}],
 'url': '/title/tt0472954/'}