{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '07-18-2020',
 'EntryPath': 'Favorites/Movies/snapshot/The-Devils-Advocate',
 'EntryURL': 'https://www.imdb.com/title/tt0118971',
 'Entry_json': 'Favorites/Movies/snapshot/The-Devils-Advocate/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Devils-Advocate/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Devils-Advocate/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Keanu Reeves',
            'url': '/name/nm0000206/'},
           {'@type': 'Person', 'name': 'Al Pacino', 'url': '/name/nm0000199/'},
           {'@type': 'Person',
            'name': 'Charlize Theron',
            'url': '/name/nm0000234/'},
           {'@type': 'Person',
            'name': 'Jeffrey Jones',
            'url': '/name/nm0000470/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 320582,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Andrew Neiderman',
              'url': '/name/nm0003825/'},
             {'@type': 'Person',
              'name': 'Jonathan Lemkin',
              'url': '/name/nm0501380/'},
             {'@type': 'Person',
              'name': 'Tony Gilroy',
              'url': '/name/nm0006904/'},
             {'@type': 'Organization', 'url': '/company/co0002663/'},
             {'@type': 'Organization', 'url': '/company/co0021592/'},
             {'@type': 'Organization', 'url': '/company/co0044240/'},
             {'@type': 'Organization', 'url': '/company/co0043164/'},
             {'@type': 'Organization', 'url': '/company/co0043831/'},
             {'@type': 'Organization', 'url': '/company/co0025101/'}],
 'datePublished': '1997-10-17',
 'description': "The Devil's Advocate is a movie starring Keanu Reeves, Al "
                'Pacino, and Charlize Theron. An exceptionally adept Florida '
                'lawyer is offered a job at a high-end New York City law firm '
                'with a high-end boss - the biggest opportunity of his...',
 'director': [{'@type': 'Person',
               'name': 'Taylor Hackford',
               'url': '/name/nm0000431/'}],
 'duration': 'PT2H24M',
 'genre': ['Drama', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BM2M2MDJhMDgtMmJkYy00MTgzLTkyZTktODM5NzE1MWUyNDA4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg',
 'keywords': 'deal with the devil,lawyer,the devil,vanity,female full frontal '
             'nudity',
 'name': "The Devil's Advocate",
 'trailer': [{'@type': 'VideoObject',
              'description': 'Home Video Trailer from Warner Home Video',
              'embedUrl': '/video/imdb/vi2728460569',
              'name': "Devil's Advocate",
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNWVmYjE5YTQtN2Y2Yy00NGI4LWE5NTUtYTM3NGUyZTMyN2YzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNWVmYjE5YTQtN2Y2Yy00NGI4LWE5NTUtYTM3NGUyZTMyN2YzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T13:50:10Z'}],
 'url': '/title/tt0118971/'}