{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-09-06',
 'EntryPath': 'Favorites/TV/snapshot/Oz',
 'EntryURL': 'https://www.imdb.com/title/tt0118421',
 'Entry_json': 'Favorites/TV/snapshot/Oz/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Oz/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Oz/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ernie Hudson',
            'url': '/name/nm0001368/'},
           {'@type': 'Person',
            'name': 'J.K. Simmons',
            'url': '/name/nm0799777/'},
           {'@type': 'Person',
            'name': 'Lee Tergesen',
            'url': '/name/nm0855564/'},
           {'@type': 'Person',
            'name': 'Dean Winters',
            'url': '/name/nm0935921/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 85740,
                     'ratingValue': '8.7',
                     'worstRating': '1.0'},
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Tom Fontana',
              'url': '/name/nm0284956/'},
             {'@type': 'Organization', 'url': '/company/co0030480/'},
             {'@type': 'Organization', 'url': '/company/co0068745/'}],
 'datePublished': '1997-07-12',
 'description': 'Oz is a TV series starring Ernie Hudson, J.K. Simmons, and '
                'Lee Tergesen. A series chronicling the daily activities of an '
                'unusual prison facility and its criminal inhabitants.',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BYjY3N2M2YjgtZTFjZS00ODA1LWJjMDgtNDgxZDllZWFiMmYyXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
 'keywords': 'male rape,prison,italian,gay,aryan brotherhood',
 'name': 'Oz',
 'trailer': {'@type': 'VideoObject',
             'description': 'Home Video Trailer from HBO Home Video',
             'embedUrl': '/video/imdb/vi2476671257',
             'name': 'Oz: The Complete First Season',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTBjMTgxOTQtNTYyYy00YWM2LWIzMmMtZGRkNDBjNmYyMmY5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTBjMTgxOTQtNTYyYy00YWM2LWIzMmMtZGRkNDBjNmYyMmY5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T15:35:58Z'},
 'url': '/title/tt0118421/'}