{'Actors': ['Adewale Akinnuoye-Agbaje&tv',
            'BD Wong&tv',
            'Christopher Meloni&tv',
            'Chuck Zito&tv',
            'Craig muMs Grant&tv',
            'David Zayas&tv',
            'Dean Winters&tv',
            'Eamonn Walker&tv',
            'Edie Falco&tv',
            'Ernie Hudson&tv',
            'George Morfogen&tv',
            'Harold Perrineau&tv',
            'JD Williams&tv',
            'JK Simmons&tv',
            'Kirk Acevedo&tv',
            'Lauren Velez&tv',
            'Lee Tergesen&tv',
            'Michael Wright&tv',
            'Otto Sanchez&tv',
            'RE Rodgers&tv',
            'Rita Moreno&tv',
            'Robert Clohessy&tv',
            'Scott William Winters&tv',
            'Steven Wishnoff&tv',
            'Terry Kinney&tv',
            'Tom Mardirosian&tv',
            'Zeljko Ivanek&tv'],
 'Added': '2013-09-06',
 'Countries': ['USA'],
 'Description': '\n'
                'Oz: A series chronicling the daily activities of an unusual '
                'prison facility and its criminal inhabitants. ',
 'Director': [],
 'EntryPath': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Oz',
 'EntryURL': 'http://www.imdb.com/title/tt0118421',
 'Entry_json': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Oz/entry.json',
 'Entry_php': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Oz/info.php',
 'Entry_py': 'W:\\Portfolio\\PersonalWebsite\\Favorites/TV/snapshot//Oz/info.py',
 'Genres': ['Crime&tv', 'Drama&tv', 'Thriller&tv'],
 'IMDB': 'http://www.imdb.com/title/tt0118421',
 'PrimeWire': 'http://www.primewire.ag/tv-5190-Oz',
 'Ratings': {'IMDB': '8.9/10',
             'Metascore': 'N/A',
             'PrimeWire': '3.53/5',
             'RT': 'N/A',
             'Votes': '913'},
 'Released': '1997-07-12',
 'Runtime': '100 mins ',
 'ThumbURL': 'http://images.primewire.ag/thumbs/5190_Oz_1997.jpg',
 'Title': 'Oz'}