{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-19',
 'EntryPath': 'Favorites/Movies/snapshot/The-Evil-Dead',
 'EntryURL': 'https://www.imdb.com/title/tt0083907',
 'Entry_json': 'Favorites/Movies/snapshot/The-Evil-Dead/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Evil-Dead/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Evil-Dead/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Bruce Campbell',
            'url': '/name/nm0132257/'},
           {'@type': 'Person',
            'name': 'Ellen Sandweiss',
            'url': '/name/nm0762445/'},
           {'@type': 'Person',
            'name': 'Richard DeManincor',
            'url': '/name/nm0217822/'},
           {'@type': 'Person',
            'name': 'Betsy Baker',
            'url': '/name/nm0048260/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 180147,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'NC-17',
 'creator': [{'@type': 'Person',
              'name': 'Sam Raimi',
              'url': '/name/nm0000600/'},
             {'@type': 'Organization', 'url': '/company/co0047594/'}],
 'datePublished': '1983-01-16',
 'description': 'The Evil Dead is a movie starring Bruce Campbell, Ellen '
                'Sandweiss, and Richard DeManincor. Five friends travel to a '
                'cabin in the woods, where they unknowingly release '
                'flesh-possessing demons.',
 'director': [{'@type': 'Person',
               'name': 'Sam Raimi',
               'url': '/name/nm0000600/'}],
 'duration': 'PT1H25M',
 'genre': 'Horror',
 'image': 'https://m.media-amazon.com/images/M/MV5BODc2MmVjZmUtNjAzMS00MDNiLWIyM2YtOGEzMjg0YjRhMzRmXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
 'keywords': 'cult film,evil dead,necronomicon,supernatural rape,book of the '
             'dead',
 'name': 'The Evil Dead',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Five friends travel to a cabin in the woods, '
                             'where they unknowingly release flesh-possessing '
                             'demons.',
              'embedUrl': '/video/imdb/vi37529113',
              'name': 'U.S. Version',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BNTExMzg0OTU4OV5BMl5BanBnXkFtZTgwNTA0OTIyMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BNTExMzg0OTU4OV5BMl5BanBnXkFtZTgwNTA0OTIyMzE@._V1_.jpg',
              'uploadDate': '2013-04-30T20:03:16Z'}],
 'url': '/title/tt0083907/'}