{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-23',
 'EntryPath': 'Favorites/Movies/snapshot/Final-Fantasy-The-Spirits-Within',
 'EntryURL': 'https://www.imdb.com/title/tt0173840',
 'Entry_json': 'Favorites/Movies/snapshot/Final-Fantasy-The-Spirits-Within/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Final-Fantasy-The-Spirits-Within/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Final-Fantasy-The-Spirits-Within/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Alec Baldwin',
            'url': '/name/nm0000285/'},
           {'@type': 'Person',
            'name': 'Steve Buscemi',
            'url': '/name/nm0000114/'},
           {'@type': 'Person',
            'name': 'Ming-Na Wen',
            'url': '/name/nm0001840/'},
           {'@type': 'Person',
            'name': 'Ving Rhames',
            'url': '/name/nm0000609/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 79278,
                      'ratingValue': '6.4',
                      'worstRating': '1.0'}],
 'contentRating': 'PG-13',
 'creator': [{'@type': 'Person',
              'name': 'Hironobu Sakaguchi',
              'url': '/name/nm0756983/'},
             {'@type': 'Person',
              'name': 'Al Reinert',
              'url': '/name/nm0718031/'},
             {'@type': 'Person',
              'name': 'Jeff Vintar',
              'url': '/name/nm0899113/'},
             {'@type': 'Person',
              'name': 'Jack Fletcher',
              'url': '/name/nm0282027/'},
             {'@type': 'Person',
              'name': 'Bruce B.L. Jurgens',
              'url': '/name/nm10455508/'},
             {'@type': 'Person',
              'name': 'Ramin Mebdy',
              'url': '/name/nm1804369/'},
             {'@type': 'Organization', 'url': '/company/co0012408/'},
             {'@type': 'Organization', 'url': '/company/co0035851/'},
             {'@type': 'Organization', 'url': '/company/co0040831/'}],
 'datePublished': '2001-07-11',
 'description': 'Final Fantasy: The Spirits Within is a movie starring Alec '
                'Baldwin, Steve Buscemi, and Ming-Na Wen. A scientist makes a '
                'last stand on Earth with the help of a ragtag team of '
                'soldiers against an invasion of alien phantoms.',
 'director': [{'@type': 'Person',
               'name': 'Hironobu Sakaguchi',
               'url': '/name/nm0756983/'},
              {'@type': 'Person',
               'name': 'Motonori Sakakibara',
               'url': '/name/nm1012102/'}],
 'duration': 'PT1H46M',
 'genre': ['Animation', 'Action', 'Adventure', 'Fantasy', 'Romance', 'Sci-Fi'],
 'image': 'https://m.media-amazon.com/images/M/MV5BZWFmYmViNGEtNzM5NC00NDliLThmNTUtYTY1NjhiN2ZjMGM5XkEyXkFqcGdeQXVyMDM5ODIyNw@@._V1_.jpg',
 'keywords': 'based on video game,motion capture,profanity,weapons '
             'fire,scientist',
 'name': 'Final Fantasy: The Spirits Within',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Theatrical Trailer from Columbia Tristar',
              'embedUrl': '/video/imdb/vi715587865',
              'name': 'Final Fantasy: The Spirits Within',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BY2Q4NmRlYmItYTA1Yy00MjI0LTliODktY2UzMWU4OTg4MDc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BY2Q4NmRlYmItYTA1Yy00MjI0LTliODktY2UzMWU4OTg4MDc5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2008-04-11T14:07:29Z'}],
 'url': '/title/tt0173840/'}