{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2014-09-14',
 'EntryPath': 'Favorites/Movies/snapshot/Closer',
 'EntryURL': 'https://www.imdb.com/title/tt0376541',
 'Entry_json': 'Favorites/Movies/snapshot/Closer/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/Closer/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/Closer/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Natalie Portman',
            'url': '/name/nm0000204/'},
           {'@type': 'Person', 'name': 'Jude Law', 'url': '/name/nm0000179/'},
           {'@type': 'Person', 'name': 'Clive Owen', 'url': '/name/nm0654110/'},
           {'@type': 'Person',
            'name': 'Julia Roberts',
            'url': '/name/nm0000210/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 198175,
                      'ratingValue': '7.2',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Patrick Marber',
              'url': '/name/nm0544999/'},
             {'@type': 'Person',
              'name': 'Patrick Marber',
              'url': '/name/nm0544999/'},
             {'@type': 'Organization', 'url': '/company/co0050868/'},
             {'@type': 'Organization', 'url': '/company/co0184459/'},
             {'@type': 'Organization', 'url': '/company/co0256573/'},
             {'@type': 'Organization', 'url': '/company/co0240889/'}],
 'datePublished': '2004-12-03',
 'description': 'Closer is a movie starring Natalie Portman, Jude Law, and '
                'Clive Owen. The relationships of two couples become '
                'complicated and deceitful when the man from one couple meets '
                'the woman of the other.',
 'director': [{'@type': 'Person',
               'name': 'Mike Nichols',
               'url': '/name/nm0001566/'}],
 'duration': 'PT1H44M',
 'genre': ['Drama', 'Romance'],
 'image': 'https://m.media-amazon.com/images/M/MV5BN2I0Y2JmZjQtNjEyOC00ODhkLWE5YWUtOWFkOGQwMGYyODRiXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
 'keywords': 'love triangle,adultery,pubic hair,stripper,pole dance',
 'name': 'Closer',
 'trailer': [{'@type': 'VideoObject',
              'description': 'Trailer for Closer',
              'embedUrl': '/video/imdb/vi2308413465',
              'name': 'Closer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTMyYmFjNGUtZThlZS00NGRkLTk2ZDgtYzAxMDZiODNlMTA5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTMyYmFjNGUtZThlZS00NGRkLTk2ZDgtYzAxMDZiODNlMTA5XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
              'uploadDate': '2010-12-11T06:09:14Z'}],
 'url': '/title/tt0376541/'}