<?php
$infoArray = array('Actors' => array('Clive Owen',
            'Colin Stinton',
            'Daniel Dresner',
            'Jude Law',
            'Julia Roberts',
            'Leonard Silver',
            'Michael Haley',
            'Natalie Portman',
            'Peter Rnic',
            'Ray Donn',
            'Robert Stone',
            'Selena Mars'),
 'Added' => '2014-09-14',
 'Countries' => array('USA', 'UK'),
 'Description' => '\nCloser: The relationships of two couples become complicated and deceitful when the man from one couple meets the woman of the other. ',
 'Director' => array('Mike Nichols'),
 'Genres' => array('Drama', 'Romance'),
 'IMDB' => 'http://www.imdb.com/title/tt0376541',
 'PrimeWire' => 'http://www.primewire.ag/watch-2237-Closer',
 'Ratings' => array('IMDB' => '7.3/10',
             'Metascore' => '65%',
             'PrimeWire' => '3.86/5',
             'RT' => '68%',
             'Votes' => '431'),
 'Released' => '2004-12-03',
 'Runtime' => '104 mins ',
 'ThumbURL' => 'http://images.primewire.ag/thumbs/2237_Closer_2004.jpg',
 'Title' => 'Closer');
?>