{'@context': 'http://schema.org',
 '@type': 'TVSeries',
 'EntryAdded': '2013-12-15',
 'EntryPath': 'Favorites/TV/snapshot/Mob-City',
 'EntryURL': 'https://www.imdb.com/title/tt2176609',
 'Entry_json': 'Favorites/TV/snapshot/Mob-City/entry.json',
 'Entry_py': 'Favorites/TV/snapshot/Mob-City/info.py',
 'Entry_thumb': 'Favorites/TV/snapshot/Mob-City/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Jon Bernthal',
            'url': '/name/nm1256532/'},
           {'@type': 'Person',
            'name': 'Milo Ventimiglia',
            'url': '/name/nm0893257/'},
           {'@type': 'Person',
            'name': 'Neal McDonough',
            'url': '/name/nm0568180/'},
           {'@type': 'Person',
            'name': 'Alexa Davalos',
            'url': '/name/nm1111968/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 6939,
                      'ratingValue': '7.5',
                      'worstRating': '1.0'}],
 'contentRating': 'TV-MA',
 'creator': [{'@type': 'Person',
              'name': 'Frank Darabont',
              'url': '/name/nm0001104/'},
             {'@type': 'Organization', 'url': '/company/co0088248/'}],
 'datePublished': '2013-12-04',
 'description': 'Mob City is a TV series starring Jon Bernthal, Milo '
                'Ventimiglia, and Neal McDonough. 1947, Los Angeles. Cop Joe '
                'Teague walks the line between the LAPD, led by William '
                'Parker, and the mob, led by Bugsy Siegel.',
 'genre': ['Crime', 'Drama', 'Mystery', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjk0MDJkYTctOTkzNi00NWZlLTkyZDYtYzgxNzk0MmY2MWZjXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
 'keywords': 'lapd,neo noir,city hall,lawyer,police detective',
 'name': 'Mob City',
 'trailer': [{'@type': 'VideoObject',
              'description': "Watch a trailer for Frank Darabont's upcoming "
                             'TNT series "Mob City".',
              'embedUrl': '/video/imdb/vi1059367193',
              'name': 'Official Sneak Peek',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMTUwODU5NzA4Ml5BMl5BanBnXkFtZTgwMTY0ODkxMzE@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMTUwODU5NzA4Ml5BMl5BanBnXkFtZTgwMTY0ODkxMzE@._V1_.jpg',
              'uploadDate': '2013-08-14T10:16:05Z'}],
 'url': '/title/tt2176609/'}