{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-05-05',
 'EntryPath': 'Favorites/Movies/snapshot/The-Place-Beyond-the-Pines',
 'EntryURL': 'https://www.imdb.com/title/tt1817273',
 'Entry_json': 'Favorites/Movies/snapshot/The-Place-Beyond-the-Pines/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/The-Place-Beyond-the-Pines/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/The-Place-Beyond-the-Pines/thumb.jpg',
 'actor': [{'@type': 'Person',
            'name': 'Ryan Gosling',
            'url': '/name/nm0331516/'},
           {'@type': 'Person',
            'name': 'Bradley Cooper',
            'url': '/name/nm0177896/'},
           {'@type': 'Person', 'name': 'Eva Mendes', 'url': '/name/nm0578949/'},
           {'@type': 'Person',
            'name': 'Craig Van Hook',
            'url': '/name/nm3995471/'}],
 'aggregateRating': [{'@type': 'AggregateRating',
                      'bestRating': '10.0',
                      'ratingCount': 238459,
                      'ratingValue': '7.3',
                      'worstRating': '1.0'}],
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Derek Cianfrance',
              'url': '/name/nm0161834/'},
             {'@type': 'Person',
              'name': 'Ben Coccio',
              'url': '/name/nm1397579/'},
             {'@type': 'Person',
              'name': 'Derek Cianfrance',
              'url': '/name/nm0161834/'},
             {'@type': 'Person',
              'name': 'Ben Coccio',
              'url': '/name/nm1397579/'},
             {'@type': 'Person',
              'name': 'Darius Marder',
              'url': '/name/nm2942187/'},
             {'@type': 'Organization', 'url': '/company/co0015447/'},
             {'@type': 'Organization', 'url': '/company/co0366362/'},
             {'@type': 'Organization', 'url': '/company/co0212525/'}],
 'datePublished': '2013-03-20',
 'description': 'The Place Beyond the Pines is a movie starring Ryan Gosling, '
                'Bradley Cooper, and Eva Mendes. A motorcycle stunt rider '
                'turns to robbing banks as a way to provide for his lover and '
                'their newborn child, a decision that puts him on a...',
 'director': [{'@type': 'Person',
               'name': 'Derek Cianfrance',
               'url': '/name/nm0161834/'}],
 'duration': 'PT2H20M',
 'genre': ['Crime', 'Drama', 'Thriller'],
 'image': 'https://m.media-amazon.com/images/M/MV5BMjc1OTEwNjU4N15BMl5BanBnXkFtZTcwNzUzNDIwOQ@@._V1_.jpg',
 'keywords': 'bank robbery,neo noir,original story,bank,high school student',
 'name': 'The Place Beyond the Pines',
 'trailer': [{'@type': 'VideoObject',
              'description': 'A motorcycle stunt rider turns to robbing banks '
                             'as a way to provide for his lover and their '
                             'newborn child, a decision that puts him on a '
                             'collision course with an ambitious rookie cop '
                             'navigating a department ruled by a corrupt '
                             'detective.',
              'embedUrl': '/video/imdb/vi267494937',
              'name': 'UK Trailer',
              'thumbnail': {'@type': 'ImageObject',
                            'contentUrl': 'https://m.media-amazon.com/images/M/MV5BMjIyMzkwNzU0N15BMl5BanBnXkFtZTcwODczNzAzOQ@@._V1_.jpg'},
              'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BMjIyMzkwNzU0N15BMl5BanBnXkFtZTcwODczNzAzOQ@@._V1_.jpg',
              'uploadDate': '2013-03-28T05:18:03Z'}],
 'url': '/title/tt1817273/'}