{'@context': 'http://schema.org',
 '@type': 'Movie',
 'EntryAdded': '2013-02-24',
 'EntryPath': 'Favorites/Movies/snapshot/House-of-1000-Corpses',
 'EntryURL': 'https://www.imdb.com/title/tt0251736',
 'Entry_json': 'Favorites/Movies/snapshot/House-of-1000-Corpses/entry.json',
 'Entry_py': 'Favorites/Movies/snapshot/House-of-1000-Corpses/info.py',
 'Entry_thumb': 'Favorites/Movies/snapshot/House-of-1000-Corpses/thumb.jpg',
 'actor': [{'@type': 'Person', 'name': 'Sid Haig', 'url': '/name/nm0354085/'},
           {'@type': 'Person',
            'name': 'Karen Black',
            'url': '/name/nm0000947/'},
           {'@type': 'Person',
            'name': 'Bill Moseley',
            'url': '/name/nm0608405/'},
           {'@type': 'Person',
            'name': 'Sheri Moon Zombie',
            'url': '/name/nm0600667/'}],
 'aggregateRating': {'@type': 'AggregateRating',
                     'bestRating': '10.0',
                     'ratingCount': 73930,
                     'ratingValue': '6.1',
                     'worstRating': '1.0'},
 'contentRating': 'R',
 'creator': [{'@type': 'Person',
              'name': 'Rob Zombie',
              'url': '/name/nm0957772/'},
             {'@type': 'Organization', 'url': '/company/co0215893/'},
             {'@type': 'Organization', 'url': '/company/co0005073/'}],
 'datePublished': '2003-04-11',
 'description': 'House of 1000 Corpses is a movie starring Sid Haig, Karen '
                'Black, and Bill Moseley. Two young couples traveling across '
                'the backwoods of Texas searching for urban legends of murder '
                'end up as prisoners of a bizarre and sadistic...',
 'director': {'@type': 'Person',
              'name': 'Rob Zombie',
              'url': '/name/nm0957772/'},
 'duration': 'PT1H29M',
 'genre': 'Horror',
 'image': 'https://m.media-amazon.com/images/M/MV5BNjUyNjU0NDE0OV5BMl5BanBnXkFtZTYwNzcwMzg3._V1_.jpg',
 'keywords': 'depravity,masked man,giant,clown face,dark comedy',
 'name': 'House of 1000 Corpses',
 'trailer': {'@type': 'VideoObject',
             'description': 'Trailer',
             'embedUrl': '/video/imdb/vi284426521',
             'name': 'House of 1000 Corpses',
             'thumbnail': {'@type': 'ImageObject',
                           'contentUrl': 'https://m.media-amazon.com/images/M/MV5BYzkyZGZhOWQtZTZlYi00NWZkLTk0ZGMtOGUzODhiNDBiOWY1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg'},
             'thumbnailUrl': 'https://m.media-amazon.com/images/M/MV5BYzkyZGZhOWQtZTZlYi00NWZkLTk0ZGMtOGUzODhiNDBiOWY1XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg',
             'uploadDate': '2008-04-11T16:47:55Z'},
 'url': '/title/tt0251736/'}